### ISSUE TITLE
Percorrendo um array e verificando quantas vendas eu tenho e validando as datas

### ISSUE THREAD

**Issue by samaelsimoes** [frontendbr/forum#1007]
Opa boa tarde, galera estou com uma grande dificuldade, seguinte meu problema seria eu tenho um array com todas as minhas vendas certo eu gostaria de verificar quantos produtos dessa venda eu tenho e criar um campo total, vou colocar meu código aqui de como estou montando.

Primeiramente tenho 2 .json um é catalog.json e outro seria sales.json 
Catalogo seria meus produtos, e sales seria meus produtos que foram vendido.
Cada um deles esta desse formato ex:

```
catalog:
[
  {
    "id": 9599537847884886,
    "price": "609.99"
  },
  {
    "id": 8399591348177295,
    "price": "99.99"
  },
  {
    "id": 2893662359426173,
    "price": "409.99"
  },
  {
    "id": 5617504184669957,
    "price": "309.99"
  },
  {
    "id": 5674914429632271,
    "price": "99.99"
  }
]
sales: 
	{
		"n_payments":1,
		"sale_id":"8290374294974384",
		"timestamp":"2017-03-17 01:37:44",
		"payment_method":"credit",
		"product_id":"9967875963780555"
	},

	{
		"n_payments":1,
		"sale_id":"3636278704297674",
		"timestamp":"2017-02-05 01:36:10",
		"payment_method":"credit",
		"product_id":"3728239112716673"
	},

	{
		"n_payments":6,
		"sale_id":"6512811117371592",
		"timestamp":"2017-10-24 03:59:23",
		"payment_method":"credit",
		"product_id":"5233682584076731"
	}
]
```

nisso estou pegando eles desse modo 

```
objSales = JSON.parse(fs.readFileSync('public/sales.json', 'utf8'));
objCatalog = JSON.parse(fs.readFileSync('public/catalog.json', 'utf8'));
```

após isso estou passando objSales e objCatalog para minha função 

```
valueSalesCatalog = salesCatalog(objSales, objCatalog);
```

que está do seguinte modo 

```
function salesCatalog(objSales, objCatalog) {

	salesCatalog = [];

	var teste;
	objSales.map( function(sale) { //varrendo as vendas 
		sale.catalog = objCatalog.filter(function(catalog) { //após varrer vou pegar o produto			
			return sale.product_id === catalog.id.toString();
		});
		sale.qtproduto = sale.catalog.length; //pegando quantidade de produto aqui esta sempre pegando 1 mas tenho varias venda de um unico produto como contar ?

					console.log(sale.catalog.length);
		if (sale.catalog[0] != "" && sale.catalog[0] != undefined) {			
			sale.value = sale.qtproduto * parseFloat(sale.catalog[0].price);
		}	

		salesCatalog.push(sale);
	});

	return salesCatalog;
};
```

Como comentei no código estou tentando fazer a contagem de quantas vendas tenho desse produto e nisso multiplicar pelo valor do meu produto. 

Esse seria um ponto que não estou conseguindo o outro seria 
Para cada compra pegar o mes e adicionar nesse objeto pelo mes e somando os valores.
	fechamento do cartão de crédito é no dia 5 de cada mes
		- Parceka cai no dia 10 de cada mes
			exemplo comprei uma bola dia dia 05/1/2018 o pagamento ira cair			dia 10/2/2018.
			se a compra tivesse sido feita dia 02/2/2018 o pagamento iria cair 	dia 10/2/2018
	validar se foi débito ou crédito
	crédito cai o pagamento no mesmo dia
eu fiz minha função desse modo.

```
function valCatalogDebCre (valdateCatalog){
	var monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

	var dataByMonth = valdateCatalog.reduce(function(dataByMonth, datum){
		var date, day, month, year, value, group; 

		date = new Date(datum.timestamp);

		day = date.getDate(); // dia
		month = monthNames[date.getMonth()]; // mes
		year  = ('' + date.getFullYear()).slice(-2); // ano
		group =  day + '\'' + month + '\'' + year;

		value = datum.value;

		dataByMonth[group] = (dataByMonth[group] || 0) + value;

  		return dataByMonth;
	});	
};
```

**Comment by LFeh** [comment]
Editei um pouco seu post para melhor compreensão dos códigos.

**Comment by nandosangenetto** [comment]
Estou fazendo a primeira parte antes de ler a segunda parte. Me explica uma coisa, o que seria `n_payments`? É a quantidade de itens vendidos em uma única compra?

**Comment by samaelsimoes** [comment]
seria o tipo se é credito ou débito payment_method

**Comment by nandosangenetto** [comment]
Entendi, mas era isso o que você queria? @samaelsimoes

**Comment by samaelsimoes** [comment]
Quase isso.

a primeira parte teria que nos retornar as vendas de cada produto 
por exemplo, vendi 15 bolas ai vai me trazer no retorno algo parecido com isso.

 { n_payments: 2,
    sale_id: '3855814248940884',
    timestamp: '2017-12-09 03:24:39',
    payment_method: 'credit',
    product_id: '9934377972692633',
    catalog: [],
    qtproduto: 15 },

só que precisamos da quantidade do produto

**Comment by samaelsimoes** [comment]
Me desculpa vou tentar explicar melhor

Criei um metodo para retornar o produto pelo id ai nisso esse metodo ele tem um looping para pegar o produto, no caso varrer as vendas e para uma pegar o produto, preço + total * a quantia 

ai a segunda parte separar por datas

**Comment by nandosangenetto** [comment]
Não sei se entendi muito bem, mas você ajudaria bastante ao especificar postando um exemplo "real" de entrada e saída, por exemplo, passando quais seriam os arrays de entrada e como você gostaria que fosse o resultado (saída).

Assim fica claro o seu objetivo e fica mais fácil de pensar em uma solução.

**Comment by samaelsimoes** [comment]
Opa consegui, primeiro fiz para me retornar todas as vendas dos produtos do catalogo. 
esse é meu retorno 
{ n_payments: 1,
    sale_id: '9852626988374763',
    timestamp: '2017-12-14 21:39:39',
    payment_method: 'debit',
    product_id: '6602140437364424',
    catalog: [ [Object] ],
    qtproduto: 1,
    value: 119.99 },
Agora vou ter que verificar  
 para cada compra pegar o mes e adicionar nesse objeto pelo mes e somando os valores.
fechamento do cartão de crédito é no dia 5 de cada mes
- Parcela cai no dia 10 de cada mes
	exemplo comprei uma bola dia dia 05/10/2018 o pagamento ira cair dia 10/11/2018.
	se a compra tivesse sido feita dia 04/10/2018 o pagamento iria cair dia 10/10
	validar se foi débito ou crédito
	crédito cai o pagamento no mesmo dia

**Comment by samaelsimoes** [comment]
Opa boa noite, estava verificando novamente os Json que estou utilizando, uma venda sempre vai ser só de um produto, vi pelo motivo que é  não posso juntar produtos de outras vendas por conta que as minhas outras vendas do mesmo catalogo 'id' tem datas diferentes, o seu modo que você fez me ajudou para uma outra situação obrigado. a minha saída agora ficou desse modo e esta bem certinha.

{ n_payments: 1,
sale_id: '9852626988374763',
timestamp: '2017-12-14 21:39:39',
payment_method: 'debit',
product_id: '6602140437364424',
catalog: [ [Object] ],
qtproduto: 1,
value: 119.99 },

A segunda parte irei utilizar essa lista para verificar o seguinte modo. 

É preciso considerar que a data de fechamento do cartão de crédito é no dia 5 de cada mês. Porém, a parcela em si cai apenas no dia 10. Se uma compra ou pagamento foi feito dia 2017-01-05 em diante, a primeira parcela cairá no dia 2017-02-10. Já se tivesse sido no dia 2017-2-04, cairia em 2017-02-10.
Se o método de pagamento for débito, cairá no mesmo instante descrito na coluna timestamp.

Eu fiz algo desse estilo mas ainda estou montando, tentei de outros modos mas não deram certo.

function valCatalogDebCre (valdateCatalog){
	var monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

	var dataByMonth = valdateCatalog.reduce(function(dataByMonth, datum){
		var date, day, month, year, value, group; 

		date = new Date(datum.timestamp);

		day = date.getDate(); // dia
		month = monthNames[date.getMonth()]; // mes
		year  = ('' + date.getFullYear()).slice(-2); // ano
		group =  day + '\'' + month + '\'' + year;

		value = datum.value;

		dataByMonth[group] = (dataByMonth[group] || 0) + value;

  		return dataByMonth;
	});	
};
