### ISSUE TITLE
IMultiSelectOption

### ISSUE THREAD

**Issue by fie23777** [frontendbr/forum#1010]
Olá alguém saberia como fazer uma IMultiSelectOption trazer alguns itens selecionado?
tipo:

```
  myOptionsGrupo= [];

  this.myOptionsGrupo = [
    { id: 'honda', name: 'honda'},
    { id: 'fiat', name: 'fiat' },
    { id: 'chevrolet, name: 'chevrolet' },
    { id: 'bmw' , name: 'bmw' },

   ];
```

e trazer honda e fiat checked

**Comment by bernardodiasc** [comment]
Antes de dar a resposta, @fie23777 voce conseguiu imaginar alguma estratégia/lógica para resolver isso? Conseguiria descrever alguma ideia de solução? Não se preocupe em errar, use a oportunidade para elaborar uma linha de raciocínio e encontrar (com nossa ajuda) a forma técnica de programar a sua ideia.

**Comment by fie23777** [comment]
Na Interface de tem esses atributos, porem nao existe a opção de checked.
export interface IMultiSelectOption {
    id: any;
    name: string;
    isLabel?: boolean;
    parentId?: any;
    params?: any;
    classes?: string;
    image?: string;
}

Nesta outra  interface tem o checked, porem não conseguimos passar um parametro na string:
export interface IMultiSelectTexts {
    checkAll?: string;
    uncheckAll?: string;
    checked?: string; = "{ id: 'honda', name: 'honda'},"
    checkedPlural?: string;
    searchPlaceholder?: string;
    searchEmptyResult?: string;
    searchNoRenderText?: string;
    defaultTitle?: string;
    allSelected?: string;
}

**Comment by fie23777** [comment]
Na interface tem a opção checked, porem nao podemos passar um array ou qualquer campo.
export interface IMultiSelectTexts {
    checkAll?: string;
    uncheckAll?: string;
    checked?: string;
    checkedPlural?: string;
    searchPlaceholder?: string;
    searchEmptyResult?: string;
    searchNoRenderText?: string;
    defaultTitle?: string;
    allSelected?: string;
}

**Comment by fie23777** [comment]
poderia ter uma opção igual a isso
{ id: 'honda', name: 'honda', checked : true},

**Comment by bernardodiasc** [comment]
Legal voce estar conferindo as interfaces e tentando entender pelo código fonte, legal mesmo. Mas vc chegou a ver a documentação da lib? Algo tão fundamental como os itens ativos da lista deve estar explicado nos docs :)

**Comment by fie23777** [comment]
Depois de muito tempo consegui resolver. quebrei um pouco a cabeça com Observable mas deu certo. Obrigado.
