### ISSUE TITLE
O que vcs usam pra UI? frameworks ou criam do zero? 

### ISSUE THREAD

**Issue by thiagofrancisquete** [frontendbr/forum#1012]
Salve galera, tenho buscado estudar mais essa parte de _UI_ e tal e queria saber _**o que vcs mais usam no dia a dia**_,  se é algo do tipo _Vuetify, material / semantic_ e etc ou se fazem tudo na mao? Sei que as vezes depende da aplicação e talvez vc nao tenha a liberdade pra escolher, mas se tivesse, o que escolheria?

enfim, algum roadmap mais pratico nessa parte me ajudaria muito :sweat_smile:

Li também alguns artigos falando sobre as tendências em relação a UI, como por exemplo [layout fora do grid](https://dribbble.com/shots/2265940-Yellowstone-NP-Full/attachments/424982), interfaces conversacionais e ilustrações ao invés de fotos, o que acham sobre?

###### edit: sorry for bother your holiday

**Comment by ninetails** [comment]
Geralmente crio do zero, gosto de deixar o html o mais semântico possível.

Já se for componentes, aí depende. Para React tem bastante libs, coleções e frameworks, uns que já usei (para UI): material-ui, react-icons... Utilizo os que eu vejo que não saem muito do que já tem no projeto. Por exemplo, gosto de usar Stylus ou CSS-in-JS, não faria muito sentido baixar componentes UI que compilam SASS.

Mas recomendo ir atrás de framework quando não se tem budget (tempo) para fazer tudo artesanal.

**Comment by israelmarmar** [comment]
Eu preferiria criar do zero, mas tenho que estudar estas frameworks por exigência do mercado

**Comment by kvnol** [comment]
Frameworks para UI eu nunca utilizei, sempre preferi fazer artesanalmente (como o @ninetails citou)

**Comment by leticiacostadias** [comment]
Depende muito da situação. Mas basicamente:

- em projetos pessoais e estudos eu faço tudo manualmente, usando Stylus (que é amorzinho <3)
- para freelas, que normalmente tem como base a grid do Bootstrap, eu gosto de importar apenas a base do Bootstrap e a grid e fazer o resto na mão
- aqui onde trabalho, nós temos um projeto interno que usa o AntD, mas o app principal foi feito do 0, sem frameworks

Para mim, tudo depende do tempo, orçamento e vontade (no caso dos projetos pessoais) pra fazer tudo na mão.

**Comment by LFeh** [comment]
## Contextualizando

### 2012~2014

Meus primeiros contatos com frameworks de UI foi com o Bootstrap e Foundation em meados de 2012 ~2013. De cara me apaixonei, traziam uma série de componentes razoavelmente bonitos e bem documentados, ajudavam o designer a seguir uma linha de raciocinio e foram fundamentais naquele momento, para as pessoas perceberem a importância de componentizar e documentar.

Mas vieram os problemas, o fato de trazer vários e vários componentes era sensacional, mas tinha um colateral grave: Carregar código (muito código) que não seria utilizado. E pior ainda, as modificações visuais desses componentes eram razoavelmente dificeis (se feita do jeito certo) e se feita do jeito errado, podia destruir a manutenção a longo prazo.

Claro que arrumei um [jeito de usar o Boostrap diminuindo os colaterais](https://www.felipefialho.com/blog/2014/utilizando-o-bootstrap-de-forma-consistente), mas as refatorações eram tantas que basicamente estava escrevendo do 0 sem perceber.

Sendo assim, deixei de usar esses frameworks e passei a fazer questão de escrever tudo na mão.

### 2018

Os anos passaram e os SPAs e ES6/7/8 tomaram de assalto o cenário de desenvolvimento. Aqui na empresa, chegamos em um ponto de refatoração visual da aplicação. Usamos Angular e provavelmente vamos para a linha estética do material. 

Fui portanto dar uma olhada em frameworks com essa caracteristica, e para a minha surpresa... Eles estão muito melhores, muito mesmo. Usam técnicas bem modernas, são fáceis de implementar, muito bem documentados,  são automaticamente modularizados (evitando código extra) e são pensados para ser possível mudar seu visual de forma consistente. 

Foi uma grata surpresa. 

Ainda não sei até que ponto vale ou não usar essas soluções hoje em dia, e varia muito de projeto para projeto. Mas não tenha preconceito, vale dar uma conferida.

**Comment by lucianobarauna** [comment]
Rapaz usei em um projeto o foundation e achei ele robusto demais além de ser complicado para se lidar com coisas que queira customizar. Mediante a isso voltei a usar o bootstrap mas já na versão 4 dele e tenho gostado muito.

Agora hoje o mundo vive numa correria só e esses frameworks estão resolvendo bem esses gargalos em contra partida se você não tiver um conhecimento legal em html e css seu código vai ficar muito mais complexo do que as marcações deles que são descritas nas documentações, então você e qualquer um que está iniciando com um framework deve tomar cuidado com isso.

Também sinto falta de criar meu CSS do zero , hoje quando começo um projeto pessoal penso em escrever do zero para lembrar os bons tempos rs mais cada vez mais as empresas estão presando em frameworks de UI e isso é meio frustrante às vezes rs

**Comment by XorAndre** [comment]
Usar ou não frameworks?  De fato uma pergunta de grande peso! É muito comum hoje vermos a molecada querer cair de boca em um Frame "modinha" sem saber nem o básico. Em muitos projetos uso Bootstrap e em casos onde é site rápido eu faço na mão! Me lembro de uma palestra do Diego Eis onde ele falava que usava as grids do Bootstrap e os outros componentes fazia na mão. Ao meu ver desenvolver com ou sem frameworks é uma questão de estudos de casos de uso da ferramenta além de estudar o tempo desenvolvimento do projeto.

**Comment by Guilherme2020** [comment]
Alguém aqui já usou e curtiu  o materializecss?

**Comment by cjpatoilo** [comment]
Nos meus projetos pessoais uso [Milligram](https://github.com/milligram/milligram). Milligram é uma ótima opção para quem curte fazer UI do zero por ser muito leve e possuir poucas propriedades definidas. Particularmente tenho um enorme prazer em construir UI "na mão" pq sempre aprendo algo novo, além de definir menos propriedades resultando em uma maior manutenibilidade e performance no projeto.

Tb curto trabalhar com os frameworks mais populares. A experiência normalmente é boa e quando não há necessidade de customização a minha produtividade/entrega se torna muito maior.

Já trabalhei em algumas empresas onde tive a necessidade de fazer os dois para manter o próprio framework da empresa. Sem modificar o core do framework criamos uma camada a cima para customizar os estilos. Com o passar do tempo é natural que esse framework tome vida e comece a ter princípios que a referencia inicial não possuía.

Pure, Bootstrap, Foundation, BaseCSS, e até mesmo o SemanticUI, todos são frameworks incríveis, porém gigantes. E mesmo com várias linhas CSS é normal que eles não atendam 100% da produtividade desejada para determinados projetos.

=)
