### ISSUE TITLE
Repositório de link's de cursos e livros voltados para front-end

### ISSUE THREAD

**Issue by oguhpereira** [frontendbr/forum#1019]
Eai pessoal, aqui alguém sabe de um repositório que lista recomendações de cursos e livros de front-end ?Tipo os cursos e livros brasileiros de javascript. 

Se tiver algum manda o link por favor. Se conhecer um que fala só de canvas manda o link tmb kk'.

**Comment by tarciozemel** [comment]
http://www.cursosfrontend.com.br/ (ainda em desenvolvimento)

**Comment by kvnol** [comment]
Tá aí: https://github.com/kvnol/aprenda-frontend

Montei com referência ao repo sobre Ruby do @felipeorlando.
