### ISSUE TITLE
Usabilidade de um Quiz

### ISSUE THREAD

**Issue by heliomsolivas** [frontendbr/forum#1021]
Pessoal, estou com o seguinte dilema aqui, tenho um quiz que a funcionalidade é a seguinte, se o usuário acertar ele continua respondendo (as perguntas aparecem na ordem randomica), se ele errar ele perde.

Porém se ele não acertar/errar ele consegue dar F5 ou fechar a janela, e entrar novamente no quiz, seria um meio do usuário "pular" uma pergunta do quiz.

Quais seriam as alternativas para lidar com isso? Creio que não é possível mostrar um overlay quando o usuário tentasse sair da página.

Para o usuário participar do Quiz ele tem que preencher um cadastro, fazer o login e inserir um código (fica salvo no back-end), depois disso ele começa o Quiz, a questão seriam alternativas de que ação tomar quando o usuário tentasse sair da página do Quiz.

**Comment by cezinha** [comment]
seria melhor forçar ele fazer um login para garantir que ele sempre vá continuar o quiz da posição que estava mesmo quando ele quiser tentar burlar (ia sugerir um cookie mas se ele abrir em outro browser ou se ele apagar os cookies, já conseguiria burlar)
