### ISSUE TITLE
Manipular variável CSS pelo javascript

### ISSUE THREAD

**Issue by oguhpereira** [frontendbr/forum#1025]
Pessoal criei a variável:

```css
:root{
--text-background-1:#000;
}
```
É possível com javascript eu buscar ela saber sé ela existe no meu arquivo css. Tipo da um Find(text-background-0) se não encontrar retorna nulo se encontra me retorna a cor.

**Comment by kvnol** [comment]
Se liga nisso, mano: https://codepen.io/electerious/pen/rroqdL

**Comment by luizbills** [comment]
Você pode usar isso:
```js
const computedStyle = window.getComputedStyle(document.documentElement);
const textBackground = computedStyle.getPropertyValue('--text-background-1');
```
