### ISSUE TITLE
quero começar

### ISSUE THREAD

**Issue by paulo36** [frontendbr/forum#1026]
ola estou começando  no front end/wordpress como desenvolvedor e gostaria de achar projetos para contribuir

**Comment by luizbills** [comment]
A grande maioria dos temas e plugins de WordPress são open source, procura por alguns que você usa e ajuda os desenvolvedores com correção de bugs ou tradução.

**Comment by LFeh** [comment]
Aqui tem vários -> https://github.com/frontendbr/open-source
