### ISSUE TITLE
Duvida em relação a semântica para elementos com pequenos textos

### ISSUE THREAD

**Issue by matheusrod92** [frontendbr/forum#1039]
Olá pessoal, tenho uma dúvida em relação a semântica elementos que possuem pequenos textos e que devem aparecer como um block.

**Exemplo:**
Tenho uma div que mostra a minibio de uma pessoa e nessa div devo ter o nome como um "titulo" da div, mas não chegaria ao caso de ser uma heading. Então eu poderia utilizar um span com display block, uma div ou até mesmo um p.

Qual dessas opções ou alguma outra seria mais "correta"/melhor em relação a semântica? E sugiram outras alternativas também!

**Comment by ortizvinicius** [comment]
Eu usaria algum Hn mesmo e dá pra usar microdata também, como é uma bio: https://schema.org/Person

**Comment by LFeh** [comment]
Vou repetir minha resposta no Twitter :)

Depende muito do contexto, se for um titulo, o correto é usar `<h1> <h2>`... se for um texto simples, o ideal é usar um `<p>`.

Lembrando que se usar `<h1>` por exemplo, ele deve estar atrelado em algumas tags especificas, portando, se for um card, pode usar:

```
<article class="card">
  <h1 class="card__title>
```

**Comment by matheusrod92** [comment]
Valeu galera, já estou seguindo esse caminho do article com h1!
