### ISSUE TITLE
Skills de Back-end necessárias para um Dev Front-end.

### ISSUE THREAD

**Issue by manzolidev** [frontendbr/forum#1049]
Li um topico no "Back-end BR" que era "Skills de front-end necessárias para um dev back-end" e como estou tentando arrumar um emprego com Desenvolvedor Front-end fiquei curioso o que um Front-end deve saber de Back-end?

Banco de Dados? RESTful APIs? Docker?

**Comment by LFeh** [comment]
Linkando: https://github.com/backend-br/forum/issues/60

🎉 🎉 🎉

**Comment by weltonsanches** [comment]
O mínimo:

- Saber enviar informações para o servidor. Receber as informações do servidor e renderizar no navegador. Pra isso é legal ter uma noção de Rest e métodos HTTP.

Tenho visto muito front usando o Wordpress pra gerenciar conteúdo, nesse caso é bom aprender o **básico** de PHP e MySQL.

Tem muita coisa legal pra saber, mas o necessário é isso. Já existe tanta coisa pra aprender no front acho que dizer que um monte de coisa de back-end é **necessário** acaba dificultando mais ainda a entrada de novos devs no mercado.

**Comment by leticiacostadias** [comment]
Acredito que isso depende muito do quão independente você quer ou precisa ser. Num time reduzido, talvez o profissional back end não consiga resolver todas as demandas que chegam pra ele, nesses casos, vale a pena estudar um pouco mais pra realmente botar a mão na massa quando for preciso.

Idealmente, num time completo e com funções muito bem definidas, talvez o front não precise saber mais do que teoria (fundamentos de REST, HTTP, DB, etc). No fim, a profundidade do teu conhecimento deveria variar cenário a cenário.

Para começar, eu me focaria nesses assuntos que são base pra você entender o que está acontecendo do outro lado.

**Comment by carloap** [comment]
O que acho de skill válida para o front-end + back, é conhecer sobre REST e SOAP, por ser possível implantar na camada de server ou de client, em alguns casos.

Saber configurar um servidor web sem ajuda, ou seja, conhecer sobre as diretivas como, configuração do "CORS", habilitar o SSL ou o cURL. Saber as diferenças e peculiaridade por exemplo, de um Tomcat pra um Apache.

Limpar e validar variáveis na camada do servidor e executar as operações CRUD de Banco de dados, sem se aprofundar em permissões.

Saber quando usar variáveis de ambiente, sessões, cookies...

Acho que isso se encaixaria para o caso de conseguir dar um help a um time ágil e fluir as tarefas. Depende de cada empresa, mas não que seja a função principal do front saber de tudo.

**Comment by spocck** [comment]
Pelo que entendi você está procurando um emprego na área de front-end, pressupõem que você não tenha experiência na área, acredito que você está procurando vagas como Júnior/estágio, se esse for realmente seu foco no momento, não se preocupe com back end no momento, você aprenderá coisas básicas no back com experiências como essas, se for seu primeiro emprego na área de front-end meu conselho seria foque em HTML5/CSS3 e javascript.
