### ISSUE TITLE
Consulta firebase passando lista como parametros

### ISSUE THREAD

**Issue by brownjrfla** [frontendbr/forum#1051]
Galera, 
Boa tarde!
Isto é usando para trazer todos os usuários

this.users = this.db.list(`/users`,
(ref: firebase.database.Reference) => ref.limitToLast(30).orderByChild('name')
);

Mas se eu quisesse fazer isso  para não trazer todos e sim apenas o que estão na lista
tipo isso

listausuarios 
this.users = this.db.list(`/users/${listausuarios} `,
(ref: firebase.database.Reference) => ref.limitToLast(30).orderByChild('name')
);

Vamos supor que no firebase tivesse os usuários:
AAAAAAA
BBBBBBB
CCCCCC
DDDDDD
ZZZZZZZ
E na minha lista eu só mandasse  
listausuarios  {BBBBBBB,  DDDDDD, ZZZZZZZ}
É possivel?

**Comment by klarkc** [comment]
Acho que você teria de fazer assim:

```js
const filteredUsers = []
const usersRef = this.db.child("users")
listusuarios.forEach(
    user => usersRef.orderByKey().equalTo(user).on(value => filteredUsers.push(value))
)
```
