### ISSUE TITLE
PJ - Quais atividades vocês costumam registrar suas empresas?

### ISSUE THREAD

**Issue by diogorodrigues** [frontendbr/forum#106]
# Hey galera! Blz?

Estou passando por um problema e gostaria de saber se vocês também já passaram por isso: minha empresa foi aberta com uma atividade bem genérica que a minha contadora indicou: manutenção e reparos de computador. E onde eu trabalhava na época como PJ, nunca tinha tido problemas com isso.

No entanto, uma empresa que estou negociando para trabalhar agora não aceitou essa atividade e argumentou que precisa de outras atividades mais amplas e que tem mais a ver com desenvolvimento de sites/sistemas.

**Assim, quero saber quais são as atividades que suas empresas estão registradas?**

Valeu!

**Comment by viniciusdocanto** [comment]
Eu botei essa e Treinamento em informatica, porque não achei nenhuma que se encaixasse.

**Comment by rkb81** [comment]
O problema é o simples nacional que não aceita a categoria de Web Design CNAE 6201-5/02 cujo o valor de NFe é de 19,50%.

Eu mesmo pra me enquadrar no Simples e reduzir os custos tive que mudar eu não posso mais emitir nota como Consultoria em TI( ou Hospedagem de sites (CNAE 6311-9/00).

Aqui tem uma [lista e aliquotas](http://contabnet.com.br/simples-nacional-servicos-de-informatica/) pra quem trabalha com TI.

**Comment by diogorodrigues** [comment]
Valeu @viniciusdocanto  e @rkb81 

Nessa lista que você me passou, @rkb81 , encontrei essas atividades com alíquota de 6% e que parecem ser interessantes:

6311-9/00 - Tratamento de dados, provedores de serviços de aplicação e serviços de hospedagem na internet
6319-4/00 - Portais, provedores de conteúdo e outros serviços de informação na internet
6190-6/01 - Provedores de acesso às redes de comunicações

**Comment by LFeh** [comment]
Só verifica se eles aceitam essas atividades. Se sim, manda ver ;)

**Comment by nighto** [comment]
Hello!

 

You have a new message, please read <http://allcitysurf.com/scatter.php?n4>

 

nighto@nighto.net

**Comment by andrearanha** [comment]
Pessoal,

Eu sempre faturo como "Suporte técnico em informática", mas poderia ser "Análise e desenvolvimento de sistemas" numa boa, hoje. Na hora de abrir a empresa, a nomenclatura muda um pouco, mas pode ser aberta com serviços desse tipo.

A partir de **2018**, o Simples Nacional mudou nesse ponto.
Não só aceita atividades técnicas, como admite um imposto de 6% nelas. Porém, para pagar só 6% você precisa tirar um certo valor de pró-labore pra sua pessoa física. Se não fizer isso, aí paga 15,5%.

Mais detalhes aqui: https://www.contratopj.com.br/simples-nacional-2018-para-profissionais-pj/
Acho que a mudança foi pra melhor.

Abs.
