### ISSUE TITLE
Template Admin Materialize

### ISSUE THREAD

**Issue by guilhermecostalopes** [frontendbr/forum#1067]
A empresa comprou um template para implementarmos um menu,

Mas ao clicar no botão do menu está dando este erro no console.
```
FullComponent.html:34 ERROR TypeError: Cannot read property 'toggle' of undefined
    at Object.eval [as handleEvent] (FullComponent.html:34)
    at handleEvent (core.js:13547)
    at callWithDebugContext (core.js:15056)
    at Object.debugHandleEvent [as handleEvent] (core.js:14643)
    at dispatchEvent (core.js:9962)
    at eval (core.js:10587)
    at HTMLButtonElement.eval (platform-browser.js:2628)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4740)
    at ZoneDelegate.invokeTask (zone.js:420)
```
A linha 34 do arquivo **FullComponent.html** está assim:
```
<button mat-icon-button (click)="snav.toggle()" value="sidebarclosed">
   <mat-icon>menu</mat-icon>
</button>
```

Entendo que fiz o que está no arquivo original, mas está faltando algo que não sei, pois quando rodo o template que compramos funciona normalmente.

O template que compramos é este: https://wrappixel.com/demos/angular-admin-templates/material-angular/material

**Comment by LFeh** [comment]
A função `snav.toggle()` existe?

**Comment by guilhermecostalopes** [comment]
Quando pesquiso no que compramos, vem somente um, conforme imagem em anexo.

![snav toggle](https://user-images.githubusercontent.com/24395029/39706564-35ddc31e-51e8-11e8-859b-34ad19add400.png)

**Comment by LFeh** [comment]
Template pronto é complicado, mas provavelmente você precisa implementar essa função.

Na hora do clique ele procura e não acha, dai o erro.

Tenta implementar uma função de teste e verifica se executa.

**Comment by guilhermecostalopes** [comment]
Consegui resolver, utilizando o próprio template e passando minha aplicação para lá.
