### ISSUE TITLE
Ler digital com JS

### ISSUE THREAD

**Issue by albertopida** [frontendbr/forum#1068]
Bom dia,

Gostaria de saber se alguém ja conseguiu usar um leitor de digital com JS no browser?

Obrigado

**Comment by LFeh** [comment]
Tem o [fingerprintjs](https://github.com/Valve/fingerprintjs2)

**Comment by kivervinicius** [comment]
@LFeh acredito que ele quis dizer um leitor de digitais mesmo, rs, há uns 10 anos atrás eu fiz um projeto com o Hamster II da Nitgen, na época havia um SDK que havia JS porém utilizava ActiveX porém como sabem já foi descontinuado nem é recomendado, seria interessante verificar com um fabricante e verificar a disponibilidade.

**Comment by LFeh** [comment]
Achei que o fingerprintjs servisse pra isso também haha

**Comment by marconimotta** [comment]
@albertopida desculpa perguntar, mas você conseguiu implementar? Estou tentando fazer o mesmo e não acho muito conteúdo para auxiliar.
