### ISSUE TITLE
CSS para dispositivos mobile e de legado 

### ISSUE THREAD

**Issue by didiraja** [frontendbr/forum#1074]
Me ocorreu o seguinte problema, estou desenvolvendo um site institucional, simples até, apenas com HTML/CSS e JS. Porém depois do site pronto, nas testagens do mobile, me foi solicitado que ele teria que ser compatível com iPhone 5 e 6. Nisso vemos problemas comuns de dispositivos antigos, com css quebrado, sem suporte ao flexbox e tudo mais. 

Só que eu sempre uso o Chrome pra debugar o conteúdo e geralmente, eu no máximo tenho que ajustar o width da tela pra ver o problema no cliente. Nesse caso buraco é mais embaixo e eu não tenho como inspecionar num navegador mobile, o maximo é visualizar o site no dispositivo usando o CrossBrowserTesting. 

Incluí o Modernizr pra pelo menos me ajudar com o flexbox. Mas e o resto? Como vou identificar o motivo da quebra do layout num dispositivo mobile? E depois, como fazer para essas correções afetarem só dispositivos antigos, ou quem sabe, até especifica iphone5 e 6?

**edit:** Segue o link do site http://www.sensorialbr.com/clientes/piimo/site/index.php

**Comment by luizbills** [comment]
Recomendo usar o https://www.browserstack.com/ para realizar esses testes.

**Comment by didiraja** [comment]
@luizbills o CrossBrowserTesting é similar ao BrowserStack, inclusive acho até melhor porque ele tem menos delay.

**Comment by wmartins** [comment]
Isso é um problema bem chato de solucionar/mitigar/resolver.

Tu pode tentar como "boa prática", de forma a simular o que acontece, "desabilitar" as linhas que envolvem essas funcionalidades mais "novas" (aqui, tu pode usar o [`caniuse`](https://caniuse.com/) para detectar as features "novas"). No teu caso, por exemplo, comentar/remover classes como `.d-flex`.

Isso vai te permitir ver a página como se essa classe não funcionasse (que vai ser o caso dos iPhones mais antigos).

Uma outra forma mais "simples" de fazer é prefixar essas classes com as classes do `Modernizr`, no caso, `.d-flex` viraria `.flexbox .d-flex`. Assim, basta tu mexer no html da página e remover a classe `.flexbox` para ver como a página iria se comportar. Da mesma forma, tu pode "arrumar" o layout para esses cenários implementando a classe `.no-flexbox .d-flex` e as outras.

A alternativa anterior é bem manual e vai te demandar algum tempo para fazer, porém, te garante uma entrega mais rápida. Se tu quiser algo mais a longo prazo, acho que faz sentido tu automatizar esse processo usando o [`AWS Device Farm`](https://aws.amazon.com/device-farm/?nc1=h_ls) ou alguma outra solução de Device Farm.

Caso tu não queira gastar com um Device Farm, tu pode fazer algum nível de automação usando `Chrome Headless` ou `Selenium`. Porém, aí tu vai ter que misturar um pouco a primeira alternativa para ficar mexendo nas classes e tirando algumas screenshots para ver como fica o layout, fazendo alguma espécie de [`regression testing`](https://github.com/mojoaxel/awesome-regression-testing).

Não tem muita mágica para esse tipo de cenário, é um pouco de bom senso na hora de codificar/testar. No teu cenário, utilizar o mindset de [`Progressive Enhancement`](https://www.quora.com/Can-I-convert-a-non-responsive-website-to-responsive-design/answer/Kevin-Suttle) pode te ajudar um pouco. :)

**Comment by didiraja** [comment]
Então, galera, só atualizando. Dei uma pesquisada e o [Safari 10 é conhecido por ter bugs com flexbox](https://www.google.com.br/search?ei=jOb5WvWML8P4wgT41byACQ&q=safari+10+flexbox&oq=safari+10+flexbox&gs_l=psy-ab.3...6367.8339.0.8533.0.0.0.0.0.0.0.0..0.0....0...1c.1.64.psy-ab..0.0.0....0.u5rsoI-Zy-k), mesmo que supostamente ele permita. Geralmente, são erros na hora de renderizar a caixa, que se resolvem com `height`. Muito útil, foi conhecer o [Flexbugs](https://github.com/philipwalton/flexbugs) que tem uma lista enorme de erros comuns.

Mas o melhor fica pro final, o problema aparentemente sumiu da pagina (?). Mesmo com alterações posteriores, o site continua funcionando. Não tenho certeza se foi a simples inclusão do `Modernizr`, mas pra falar a verdade tenho até medo de tirar e dar ruim de novo haha é isto.
