### ISSUE TITLE
Erro no servidor de homologação

### ISSUE THREAD

**Issue by guilhermecostalopes** [frontendbr/forum#1076]
Gerei o build de homologação com o comando **ng build**

inclui no servidor TOMCAT.

**Failed to load resource: the server responded with a status of 404 (Not Found)**

**:8080/#/**, normal sem rota
![erro 1](https://user-images.githubusercontent.com/24395029/39840157-d64913ee-53b4-11e8-919d-1de504e4ed1a.png)

**:8080/#/arquivo**, esta rota existe
![erro 2](https://user-images.githubusercontent.com/24395029/39840158-d6696a5e-53b4-11e8-923d-a8a03298a222.png)

Está faltando algo ?

**Comment by samuelsilvadev** [comment]
Olá tudo bele?

Poderia postar como está a sua index.html? especificamente o atributo `base`

**Comment by guilhermecostalopes** [comment]
Está assim, na verdade não foi mudado.
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>DESIF.ORG</title>
  <base href="./">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="assets/images/favicon.png">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
  <app-root></app-root>
<script type="text/javascript" src="inline.bundle.js"></script><script type="text/javascript" src="polyfills.bundle.js"></script><script type="text/javascript" src="scripts.bundle.js"></script><script type="text/javascript" src="styles.bundle.js"></script><script type="text/javascript" src="vendor.bundle.js"></script><script type="text/javascript" src="main.bundle.js"></script></body>
</html>
```

**Comment by barbier** [comment]
Você desenvolveu usando Node?

**Comment by guilhermecostalopes** [comment]
Não com angular

**Comment by guilhermecostalopes** [comment]
Hoje refiz o processo e funcionou.
