### ISSUE TITLE
Custom Fields no Wordpress

### ISSUE THREAD

**Issue by didiraja** [frontendbr/forum#1082]
Estou fazendo um tema que é para um site de eventos, daí me veio a necessidade de criar Campos Personalizados (atualmente, apenas Data e Local). Daí por causa da minha necessidade, tenho as seguintes perguntas:

1. Uso os próprios campos personalizadas que o WP oferece, ou é melhor aprender a usar o ACF?

2. Sobre o campo Data, eu gostaria de estilizar ele igual o próprio facebook faz na página de eventos. Qual a melhor maneira de receber o output de Dia e Mês separado?

![image](https://user-images.githubusercontent.com/10463976/40052928-c3d7ad5a-5815-11e8-8be5-c6c534c67398.png)

3. Ainda sobre a data, alguma sugestão de como preencher esse campo na hora de criá-lo de maneira dinâmica que não seja apenas uma string comum digitada? Até porque pretendo eventualmente, fazer uma busca por data dos eventos e a data dos posts não serve porque a intenção é adicionar eventos em datas futuras no site.

**Comment by renanlara** [comment]
**1 - Uso os próprios campos personalizadas que o WP oferece, ou é melhor aprender a usar o ACF?**
_Use o ACF, não é difícil aprender uma vez que você já possui conhecimentos do WordPress. [Veja >](https://www.advancedcustomfields.com/resources/)_

**2 - Sobre o campo Data, eu gostaria de estilizar ele igual o próprio facebook faz na página de eventos. Qual a melhor maneira de receber o output de Dia e Mês separado?**
_No ACF você pode configurar para que o field tenha um output de Object ou Array, com isso você pode controlar bem isso._

**3 - Ainda sobre a data, alguma sugestão de como preencher esse campo na hora de criá-lo de maneira dinâmica que não seja apenas uma string comum digitada? Até porque pretendo eventualmente, fazer uma busca por data dos eventos e a data dos posts não serve porque a intenção é adicionar eventos em datas futuras no site.**
_No WordPress, você pode filtrar posts através de meta_query, no ACF existe uma documentação explicando como usar isso com ele, [aqui](https://www.advancedcustomfields.com/resources/query-posts-custom-fields/)._

**Comment by didiraja** [comment]
Vlw @renanlara pelo visto o ACF cumpre todas as necessidades 🔝

**Comment by allysonsouza** [comment]
Se quiser uma alternativa mais voltada para desenvolvedores ao ACF, pode tentar o CMB2, tem recursos bem poderosos para criação de custom fields para posts, taxonomias, usuários, etc.
https://github.com/CMB2/CMB2

**Comment by renanlara** [comment]
CMB2 é bem irado mesmo!
Mas @allysonsouza, ACF não seria também para desenvolvedores?

**Comment by didiraja** [comment]
Aproveitando que ressuscitaram o tópico. Consegui implementa a dita cuja data, do jeito que eu queria, perfeitinnha. Porém, os meses estão em Inglês. Falaram sobre localen no php, mas to começando ainda na linguagem, alguem consegue explicar melhor como fazer, ou onde implementar?

---

@allysonsouza obrigado pela dica, vou conferir

@renanlara até é, mas tem muita coisa q faz pelo painel lá. Pra mim, quando se diz em pra desenvolvedor, é algo que envolva código ou permita customização via código.

**Comment by luizbills** [comment]
@didiraja Use o `date_i18n`: https://codex.wordpress.org/Function_Reference/date_i18n

```php
$month = date_i18n('F'); // retorna o nome do mês atual
```

obs: vc pode passar o timestamp como segundo argumento.

**Comment by allysonsouza** [comment]
@renanlara exatamente o que o @didiraja falou, o ACF foca muito no usuário final, que foi seu grande público no início, e portanto quando você parte para codificação ele não é tão legal quanto o CMB2 pelo que já experimentei

**Comment by didiraja** [comment]
@luizbills caralho o Wordpress tem codigo pra tudo mesmo hahaha vlw
