### ISSUE TITLE
Antes de logar no sistema - Angular

### ISSUE THREAD

**Issue by guilhermecostalopes** [frontendbr/forum#1084]
Tenho uma tela de login, com a total “/authentication/login”.

Como fazer no angular quando o usuário entrar no sistema, ele vai direto para esta rota ?

Após logar se ele digitar esta rota, ele sempre valida e se o usuário tiver logado ele vai para a rota “/” ?

**Comment by ericOnda** [comment]
Olá, @guilhermecostalopes! Tudo bem? Você poderia mostrar como tá o seu arquivo de rotas?
Nele, você pode definir de forma simples, mais ou menos assim:

`{ 
    path: '',
    redirectTo: '/authentication/login',
    pathMatch: 'full'
  },
  {
    path: 'authentication/login',
    component: LoginComponent,
  },
`
A segunda questão, você pode tratar com um Service que pode servir de Auth Guard

Da uma olhadinha aqui -> [Routing & Navigation - Angular](https://angular.io/guide/router)

**Comment by guilhermecostalopes** [comment]
Então, tenho este serviço de **Anti Guard**.

> import { Injectable } from '@angular/core';
> import { Router, CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';
> import { AuthenticationService } from '../servico/authentication/authentication.service';
>  
> @Injectable()
> export class CanActivateAuthGuard implements CanActivate {
>  
>   constructor(
>     private router: Router, 
>     private authService: AuthenticationService
>   ) {}
>  
>   canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
>     if (this.authService.isLoggedIn()) {
>         return true;
>     }
>     this.router.navigate(['/authentication']);
>     return false;
>   }
> }

**Rota**

> import { Routes } from '@angular/router';
> 
> import { FullComponent } from './layouts/full/full.component';
> import { AppBlankComponent } from './layouts/blank/blank.component';
> 
> export const AppRoutes: Routes = 
> [
>   {
>     path: '',
>     component: FullComponent,
>     children: 
>     [
>       {
>         path: '',
>         loadChildren: './dashboards/dashboards.module#DashboardsModule'  
>         /*pathMatch: 'full',
>         redirectTo: '/dashboards/dashboard1', */
>       },
>       {
>         path: 'configuracao',
>         loadChildren: './paginas/configuracao/configuracao.module#ConfiguracaoModule'  
>       },
>       {
>         path: 'arquivo',
>         loadChildren: './paginas/arquivo/arquivo.module#ArquivoModule'  
>       },
>       {
>         path: 'declaracao',
>         loadChildren: './paginas/declaracao/declaracao.module#DeclaracaoModule'  
>       },
>       {
>         path: 'parametro',
>         loadChildren: './paginas/parametro/parametro.module#ParametroModule'  
>       },
>       {
>         path: 'endereco',
>         loadChildren: './paginas/endereco/endereco.module#EnderecoModule'  
>       },
>       {
>         path: 'contribuinte',
>         loadChildren: './paginas/banco/banco.module#BancoModule'  
>       },
>       {
>         path: 'dashboard',
>         loadChildren: './dashboards/dashboards.module#DashboardsModule'  
>       }
>     ]
>   },
>   {
>     path: '',
>     component: AppBlankComponent,
>     children: 
>     [
>       {
>         path: 'authentication',
>         loadChildren: './authentication/authentication.module#AuthenticationModule'
>       }
>     ]
>   },
>   {
>     path: '**',
>     redirectTo: '404' 
>   }
> ];

Não consegui implementar.

**Comment by guilhermecostalopes** [comment]
**Serviço de autenticação**

> import { Injectable } from '@angular/core';
> import { Http, Headers, Response } from '@angular/http';
> import { Observable } from 'rxjs/Rx';
> import 'rxjs/add/operator/map';
> import 'rxjs/add/operator/catch';
> import 'rxjs/add/observable/throw';
> 
> import { Usuario } from '../../modelo/usuario/usuario.model';
> import { BASE_AUT_URL } from '../base-api-url-defaul';
>  
> @Injectable()
> export class AuthenticationService {
> 
>     private base: string;
>     private options: Function;
>     
>     private headers = new Headers({
>         'Content-Type': 'application/json',
>         'Accept': 'application/json',
>         'Access-Control-Allow-Origin': '*',
>         'Access-Control-Allow-Credentials': 'true'
>     });
>  
>     constructor(private http: Http) {
>         this.base = BASE_AUT_URL
>     }
>  
>     login(usuario: Usuario): Observable<boolean> {
>         console.log(this.headers);
>         return this.http.post(this.base, JSON.stringify({login: usuario.login, senha: usuario.senha}), {headers: this.headers})
>             .map((response: Response) => {
>                 let token = response.json() && response.json().token;
>                 if (token) {
>                     localStorage.setItem('currentUser', 
>                     JSON.stringify({ username: usuario.login, token: token }));
>                     localStorage.setItem('token', token);
>                     localStorage.setItem('user', JSON.stringify(usuario.login));
>                     localStorage.setItem('usuario', response.json().usuario);
>                     localStorage.setItem('nomeUsuario', response.json().nomeUsuario);
>                     localStorage.setItem('grupoUsuario', response.json().grupo);
>                     return true;
>                 } else {
>                     return false;
>                 }
>             }
>         ).catch(
>             (error:any) => Observable.throw(error.json().error || 'Server error')
>         );
>     }
> 
>     getToken(): String {
>         var currentUser = JSON.parse(localStorage.getItem('currentUser'));
>         var token = currentUser && currentUser.token;
>         return token ? token : "";
>     }
>  
>     logout(): void {
>         localStorage.removeItem('currentUser');
>     }
> 
>     isLoggedIn(): boolean {
>         var token: String = this.getToken();
>         return token && token.length > 0;
>     }
> }

**Comment by emerpaiva** [comment]
Tudo blz?
Quando eu preciso fazer uma rota protegida por auth eu utilizo o Route Guards do próprio angular.

```javascript
{ path: '', component: HomeComponent },
  { 
    path: 'profile',
    component: ProfileComponent,
    canActivate: [AuthGuard] 
  },
```
Uso como referência esse artigo: [Angular Authentication: Using Route Guards](https://medium.com/@ryanchenkie_40935/angular-authentication-using-route-guards-bf7a4ca13ae3)

Dá uma olhada e fala com a gente se conseguiu algo. 👍

**Comment by guilhermecostalopes** [comment]
Obrigado @emerpaiva .

Funcionou.
