### ISSUE TITLE
How to docker both moodle and its populated database, each one on its container?

### ISSUE THREAD

**Issue by Fabot7** [frontendbr/forum#1086]
Hi Git Hub Community,

I am working with a PC, running **Moodle 3.3** in **Ubuntu 16.04** LTS. This Moodle is using **MySQL** database. It already is configured and populated. In such context, I need to create a **docker** for the Moodle application and another docker for its MySQL database. However, the challenge here is on dockering them with its populated data. In other words, It is indispensable to docker them, including all their configurations, e. g. created users, courses, themes, page layout and its styles, and so on. The main idea is to clone the Moodle exactaly it is running locally into a docker.
In this sense, could you please give me a good tip on how to do it in a timely manner?

**Comment by LFeh** [comment]
@Fabot7 The main language of this forum is `pt-br` 🇧🇷

**Comment by Fabot7** [comment]
Muito obrigado, @RatoX !

**Comment by LFeh** [comment]
@Fabot7 Consegue traduzir sua issue?
