### ISSUE TITLE
Gráfico e Datas no Chart.js

### ISSUE THREAD

**Issue by didiraja** [frontendbr/forum#1102]
Fala pessoal, venho pedir ajuda pra vocês de um caso que está fritando meu neurônios, e é importante pois se trata da seleção de uma vaga bem legal. 

O teste me pedia pra reproduzir a seguinte tela usando a **API do Github**:
![image](https://user-images.githubusercontent.com/10463976/40522117-9273892c-5fa5-11e8-9324-a6dbea2142fa.png)

A parte do AJAX foi tudo certo, já consigo até exportar as datas dos commits. Mas estou tendo muito problema com o gráfico. Estou usando o **[Chart.js](https://www.chartjs.org)** que é a biblioteca sugerida pelo texto da vaga. Mas, gente tô achando complicado demais. A documentação não explica com muita clareza quais dados são obrigatórios e a página de demo tem muita informação externa o que dificulta mais ainda.

Minhas dúvidas são:

**1. Como controlo o range de exibição dos meses/anos embaixo?
2. Como agrupo os commits dentro de um mesmo período?**

Aqui está o [meu repositório](https://github.com/didiraja/teste-tecnico-vml) e aqui a [documentação do plugin](http://www.chartjs.org/docs/latest/axes/cartesian/time.html). Tô muito nervoso porque a vaga é foda e vou ficar bem chateado se perder por não ter cumprido o teste.

**Comment by LFeh** [comment]
Fala @didiraja, já usei essa lib algumas vezes, foi a que mais curti para trabalhar com exibições desse tipo.

Acredito que o que esteja buscando [seja algo assim](http://www.chartjs.org/samples/latest/scales/time/financial.html), certo?

Aqui está o exemplo do [código no Github](https://github.com/chartjs/Chart.js/blob/master/samples/scales/time/financial.html), dei uma olhada e parece bem próximo, da uma estudada e retorna falando se deu certo 😄

**Comment by didiraja** [comment]
Fala **frontendbr**, venho compartilhar que **CONSEGUI** resolver!

A solução foi:
- Pegar o Array das datas
- Formatar usando o **Moment.js** (lib de formatação de datas recomendado pelo próprio Chart.js)
- Daí o que era 2014-11-05, virou Nov 14 e com isso várias datas ficaram "duplicadas"
- Usar uma função pra contabilizar e separar as datas duplicadas
- Pronto! Daí eu tinha um array com os datas para alimentar o gráfico e os valores respectivos de cada label.

A solução parece simples falando, mas fritei muita cabeça no sábado resolvendo 😅

**Comment by LFeh** [comment]
hahaha, é sempre assim, a gente passa a semana inteira estudando e tentando aprender algo e quando a gente aprende da aquela sensação "nossa, como era simples, como não conseguia antes" 😂 

Faz parte da evolução profissional, mas em todo caso trabalhar com gráficos é complicadinho mesmo, que bom que deu certo.

**Comment by didiraja** [comment]
Só ressuscitando o tópico pra compartilhar que consegui a vaga. A empresa é bem legal e parece ser bem o que tava procurando.

Vlw **frontendbr** por mais um profissional no mercado 🎉 🎉 🎉
