### ISSUE TITLE
Vamos compartilhar músicas/playlists?

### ISSUE THREAD

**Issue by helderburato** [frontendbr/forum#1103]
Olá pessoal!

Vi que já existe uma issue sobre o assunto em #145, porém a proposta aqui é a troca para ampliarmos nosso conhecimento em bandas e estilos musicais. 💯 

Bom, vamos lá!

## Playlists/bandas (Spotify)

[Explosions In The Sky - Banda](https://open.spotify.com/artist/1uQWmt1OhuHGRKmZ2ZcL6p?si=7sWlY1LjQ_-akEoIMM2apA)
[Lofi Hip Hop Beats - Playlist](https://open.spotify.com/user/chillhopmusic/playlist/74sUjcvpGfdOvCHvgzNEDO?si=j_8MPNBHQIqCr78HQsZdSg)
[Ritalin (Hyper Focus) - Playlist](https://open.spotify.com/user/12177768210/playlist/3FAlO9LEpzUsNYPaUusfAz?si=3QbKZgiyQe6ueAdeIu1AlQ)
[DVLPR_FOCUS-v2.1 - Playlist](https://open.spotify.com/user/123472771/playlist/1KswcbMwcGC9RY84ZxNNi4?si=btCkadkYTEWFb_-MniIVcA)
[Programming - Playlist](https://open.spotify.com/user/mrbandler/playlist/3QK4ddLe1ADnI6lesTd27T?si=nzcC3zISQMeu4C0zSZ8VAQ)
[Rock Anthems - Playlist](https://open.spotify.com/user/spotify/playlist/37i9dQZF1DWXRqgorJj26U?si=cessAlPUQjW-yEof_RBdEg)
[Deep Focus - Playlist](https://open.spotify.com/user/spotify/playlist/37i9dQZF1DWZeKCadgRdKQ?si=e5MUbLhrQhqykceBvpoF2Q)

---

Essas são algumas das playlists que tenho acompanhado. :)

**Comment by tarciozemel** [comment]
- https://www.youtube.com/watch?v=LsBrT6vbQa8
- https://www.youtube.com/watch?v=twcOr043i4k
- https://www.youtube.com/watch?v=8gdhoj8HgaQ

**Comment by VSPPedro** [comment]
Será que cola um mix nesse post?

[Chuva](https://www.youtube.com/watch?v=nDq6TstdEi8) + [Moolingth Sonata](https://www.youtube.com/watch?v=4Tr0otuiQuU&lc=z22vgxfwcriyyr3ob04t1aokgth2r3vbxgybudnigobnrk0h00410)

Sugestão: abaixar o som da chuva até uns 10%.

**Comment by helderburato** [comment]
@tarciozemel **lofi** é demais! Ouço quase que diariamente.

@VSPPedro curti demais o som da **Chuva**, valeu pela indicação!

**Comment by klarkc** [comment]
Minha preferida: [Rick and Morty](https://open.spotify.com/user/1262817498/playlist/2Mkx1ytCuVVVtutFQomNKf?si=72UI_k3BR-qOSgteH4zxRQ)

Outras q eu ouço quando estou enjoado da acima rs
[Mr. Robot Season 1](https://open.spotify.com/user/whoismrrobot/playlist/2Lv6c0lwFRTCA4npIxVJhX?si=OckqiMVRRR6IFg8Ng0rydA)
[Celtic Music](https://open.spotify.com/user/dfiechter2/playlist/5aSO2lT7sVPKut6F9L6IAc?si=FM1BzYsvQxaCAm9LTg3NoA)
[This is Gorillaz](https://open.spotify.com/user/spotify/playlist/37i9dQZF1DWSxQLa5KoDYW?si=8AnSkVc5Qs-iEnu8YqaggA)
[Confesso música latina é ótima para programar](https://open.spotify.com/user/spotify/playlist/37i9dQZF1DX3omIq8ziEt6?si=4LCYMWAjQ2qVA1ysU4IpLw)
[Confesso ² MPB tbm](https://open.spotify.com/user/spotify/playlist/37i9dQZF1DWV6hddfqLW3Z?si=3V6zh1sqS4-UEvt_LUEGcg)

**Comment by didiraja** [comment]
No geral, qualquer coisa instrumental serve. Post-rock, RnB, vale tudo. 

Mas, de maneira prática, eu fiz MUITOS exercícios da Alura, ouvindo essa [playlist de rock psicodélico](https://www.youtube.com/watch?v=iuWa5wh8lG0). E ultimamente, tenho curtido essa playlist aqui de [Vaporwave no Spotify](https://open.spotify.com/user/iam3/playlist/17HYiAIcwlDEg5RgVkm4L7?si=vz9QT2aZTRqZUC5Oh4a8lQ).

**Comment by leoamrl** [comment]
Pra quem gosta de eletrônica. Do low ao high bpm, segue abaixo alguns artistas que eu curto pra caramba.

## Techno
[Boris Brejcha](https://soundcloud.com/search?q=boris%20brejcha)

## Tech House
(gravadora) [Sublime Records](https://soundcloud.com/sublimemusicrecords)
[Dubdisko](https://soundcloud.com/search?q=dubdisko)
[FractaLL](https://soundcloud.com/search?q=fractall)
[Rocksted](https://soundcloud.com/search?q=rocksted)
[FlexB](https://soundcloud.com/search?q=flexb)

## House
Illusionise
Damien 'n Drix
Volac
Visage
Victor Lou
Breaking Beattz
Kvsh
Groove Delight
Gustavo Mota
Gabriel Boni
Shapeless
Paskal
Woak
Malaa

## Minimal
Devochka
Toporcov
Minimal Monkey
Henrique Camacho
BIG Smoke
Jon Mesquita
R3ckz3t

## Trance
Aura Vortex
Zanon
Major 7
Skazi
Blastoyz
Blazy
Gottinari
Belik Boom
Marambá

**Comment by LFeh** [comment]
Curto as dicas do @willianjusten :D

**Comment by willianjusten** [comment]
Ixi...eu ouço taaanta coisa, que colocar uma lista aqui deixaria esse negócio enorme =o
Em cada post que faço no [meu blog](https://willianjusten.com.br/) desde quando comecei tem dica de uma música, então é só ir lá e pegar uma ahuahuahua

Nesse exato momento estou ouvindo [Vök - Before (Neelix Remix)](https://www.youtube.com/watch?v=3TCTJ_Rqyf4) é um remix de uma banda islandesa bem maneira, achei boa para concentrar no trabalho =p

**Comment by helderburato** [comment]
Conheci "Explosions in the sky" no blog do @willianjusten, banda foda demais!

**Comment by danilocandido** [comment]
Gosto de programar com essa de Rock Progressivo que é atualizada progressivamente. :goat:

[Rock Progressivo ](https://open.spotify.com/user/danilo07/playlist/6jjLut1DiQy4xFrL0JvqJX?si=YPeyd8YoQkesuro6OELi2w)

**Comment by helderburato** [comment]
@kelciocajueiro dei uma googlada aqui, e a banda "Explosions In The Sky" é classificada como [Post rock](https://pt.wikipedia.org/wiki/Post-rock).

**Comment by willianjusten** [comment]
Post Rock é um dos meus estilos de música favoritos. Aconselho muito uma banda chamada [Maybeshewill](https://www.youtube.com/watch?v=Gi1B8lZNHbI) se vocês curtem =)

**Comment by willianjusten** [comment]
Para quem curte Post-Rock, algumas bandas que eu aconselho:

- If These Trees Could Talk
- God is An Astronaut
- sleepmakeswaves
- 65daysofstatic
- Red Sparowes
- Collapse Under the Emprie
- Russian Circles
- This Will Destroy You
- Caspian
- pg.lost
- Mogwai (uma das primeiras bandas do estilo)

Provavelmente to esquecendo um monte, mas aí já são algumas xD

**Comment by marceloavf** [comment]
Algumas Post-Rock que curto, em adição as que o @willianjusten já citou:
- Long Distance Calling
- Pelican
- Jakob
- Moonlit Sailor
- Joy Wants Eternety
- The Ocean
- Callisto

Progressive Metal
- TesseracT
- Skyharbor
- Mechina
- Animals As Leaders
- Destiny Potato
- Pomegranate Tiger
- Protest The Hero

Hard Rock
- Smile Empty Soul
- Trapt
- Crossfade
- Staind
- Breaking Benjamin

New metal / Metalcore
- 36 Crazyfists
- Architects
- Breakdown of Sanity
- Northlane

Melodic Death Metal
- Be'lakor
- Insomnium
- Obscura

**Comment by ricardogouveia3** [comment]
A playlist da coworking onde eu trampo tá uma mistura de estilos, mas eu acho legal pra ouvir codando: 
https://open.spotify.com/user/ricardogouveia3/playlist/54MPVJCqzEdSL0BO9CaO0Q?si=xQKWOdkjT1KMweYbgRPbSQ

**Comment by RatoX** [comment]
Eu tenho umas playlist:

**RAP pra lembrar q nois é preto**
https://open.spotify.com/user/12167146129/playlist/5Tmg5d4Ww3qA5p3CZBDyhI

**Tudo que cê tem preconceito de ouvir mas se acaba de dançar quando toca!**
https://open.spotify.com/user/12167146129/playlist/5Z3LuXNssD7V09qyTPXZTg?si=OGZXbnu9Ql2OpaOnhyeeyQ

**Comment by LFeh** [comment]
Quero sair do padrão e mandar [minha lista de modão no Spotify](https://open.spotify.com/user/12142158508/playlist/0IGbBFtZXPrWbEDGkOQfbr?si=fITyEJxAR86l8EBRejD2xQ), é minha trilha sonora toda sexta-feira e presença garantida no fim de festa com os amigos 😍

**Comment by helderburato** [comment]
Onde vai ser o churras @LFeh? hahah combinação perfeita 😄

**Comment by jhonnymoreira** [comment]
@marceloavf só banda linda, hein mano? <3

**Comment by jhonnymoreira** [comment]
Eu tenho uma forte preferência por ouvir Drum and Bass (liquid), pq tem vocais suaves e consigo abstrair a batida.

Comecei uma playlist no Spotify, tá com 2h de música: https://open.spotify.com/user/jhonnoso/playlist/2e9b9U4Zl6kna8nidoy6BG?si=xJRuZBpEQYewWE73KTqshA

Vou atualizar aos poucos, mas espero que gostem!

**Comment by raisiqueira** [comment]
Curto bastante a Ritalin Hiper Focus: https://open.spotify.com/user/12177768210/playlist/3FAlO9LEpzUsNYPaUusfAz?si=kqZLW7IoT4i6Xzz8Yh1ueA

**Comment by rapharma** [comment]
### ## Instrumental

[Vaporwave](https://open.spotify.com/user/iam3/playlist/17HYiAIcwlDEg5RgVkm4L7?si=RdNRotYlTOayMj82NRPOuQ)

[Starbucks Jazz
](https://open.spotify.com/user/starbucks/playlist/2UPjWBRjJqMQY3LRV2aDTS?si=e9N3m_U2QXmlJCOm17N4Fg)

### ## Rock

[This is Skillet](https://open.spotify.com/user/spotify/playlist/37i9dQZF1DZ06evO2qgZOg?si=CWFLa5GvQ8CR_rDUk8jTNA) 

[This is Oficina G3](https://open.spotify.com/user/spotify/playlist/37i9dQZF1DXdLXJfbLZljt?si=1dCcV_YkQJmqXf3AqvPVAQ)

**Comment by nunesdaniel** [comment]
Gosto dessa [Hora do Pesadelo](https://open.spotify.com/user/spotify/playlist/37i9dQZF1DX0H97kz3DdJ6?si=Dl4XMGB1TDaEtfhQOnIJHA)

**Comment by AmandaFonseca** [comment]
As que eu mais escuto: 
[Brasil anos 80](https://open.spotify.com/user/amandafonseca207/playlist/7jTfQF4F6kBVkUGoTYSXju?si=AasKJR3JS6y6nImhkwRTSQ)
[California Rock State](https://open.spotify.com/user/spotify/playlist/37i9dQZF1DWTlgzqHpWg4m?si=19yIerLFRyCNIeDUNt2LqA)
[Anos 80 internacional](https://open.spotify.com/user/filtr.br/playlist/0yW1DogO2Gh5T5tZ1iq9iG?si=3RjylHHOQf-BdUicnmM5CQ)
[As 500 mais da Kiss](https://open.spotify.com/user/radiokissfm/playlist/3boghiuoZ0tQpZGf5p2MME?si=DdQ1PD9rR9O_0w_uDbX8zwl)
[Novelas](https://open.spotify.com/user/22q476ksdlj2xj2yr4pvjzf3a/playlist/19kXNtkGkPh9miSsRqlaNi?si=TXdRY2qhQNu8P2pCDooICgl)
[This is tove lo](https://open.spotify.com/user/spotify/playlist/37i9dQZF1DX0Slb2ylojAg?si=yn4cSgQBTVqftdnvQqvpVg)
[[This is Lana del rey]([url](url))](https://open.spotify.com/user/spotify/playlist/37i9dQZF1DX3XuY09ikg3x?si=-QrwYV-0SEW9UlwiWx75CQ)
[I'm the Devil](https://open.spotify.com/user/americanhsbr/playlist/1LC0bgpJifvBJZUwtiJ8M6?si=Q8yxt2dkRZqcTQK71rWdQQ)

Quase não escuto música nova a maioria é Flash back...

**Comment by JacksonOsvaldo** [comment]
Dentre outras coisas, as mais "cosumidas":

https://open.spotify.com/user/jacksonosvaldo/playlist/0PLiNJdhhJVsQcEicW4GoV

https://open.spotify.com/user/jacksonosvaldo/playlist/6DLOByLTq7Gx63YirZ2DU2

https://open.spotify.com/user/jacksonosvaldo/playlist/5s3X3eyPskzZaStHkhcWPT

:)

**Comment by rcbpgpg** [comment]
Fresquinha daqui de BH.

https://open.spotify.com/track/1RvbLntceW3cly66STNM7s?si=lnl_d8qRTzybhJ4KsOxOBQ

**Comment by rodrigets** [comment]
Pra quem  curte um Metal :metal: 

## Nowrong ##
https://open.spotify.com/album/7MqwARx3Es72uNS2ITj059

**Comment by praganavictor** [comment]
Estou fazendo essa de lofi: https://www.youtube.com/playlist?list=PL8gUHPip3lUmYUmU2aaRnWjXMrCOp66nk

Musica eletronica(boa pra jogar): https://www.youtube.com/playlist?list=PL8H85HKySx21UaDs0qoY5N-yTTU8R_4Qg

Musicas para fazer corno chorar(nao julguem kkk é mt boa): https://open.spotify.com/user/12151328780/playlist/0k1U1kHvbn2pGKhdfinn1P?si=YsG9JD0jTV2wrst2wBLeRg

**Comment by kvnol** [comment]
Meu negócio é black music então: [Groove Nosso de Cada Dia](https://open.spotify.com/playlist/2Fa8VoowmqhT5XgAZR8zLv)
