### ISSUE TITLE
Como eu faço para renderizar os dados de uma requisição com React ?

### ISSUE THREAD

**Issue by grodrigues** [frontendbr/forum#1110]
Estou Utilizando o Axios para fazer a requisição. Os dados já estão vindo mas não consigo acessar os dados do array para serem renderizados no render do react ?

```jsx
class App extends Component {
  state = {
    person: {}
  }

  componentDidMount() {
    axios.get(`http://www.mocky.io/v2/5a5e38f3330000b0261923a5`)
      .then(res => {
        const person = res.data;
        this.setState({ person });
        console.log(this.state.person);
      })
  }

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>  
        <p>{aux.contact}</p>
      </div>
    );
  }
}

export default App;
```

**Comment by fdaciuk** [comment]
Oi @grodrigues! Você está tentando usar um objeto `aux` no `render`, mas de onde vem `aux`? Para pegar os dados de `person` que estão no `state`, seria só usar `this.state.person` no render =)

**Comment by helderburato** [comment]
Oi @grodrigues,

Tenta da seguinte forma:
```
class App extends Component {
  state = {
    person: {}
  }

  componentDidMount() {
    axios.get(`http://www.mocky.io/v2/5a5e38f3330000b0261923a5`)
      .then(res => {
       if (res) {
          const person = res.data;
          this.setState({ person });
          console.log(this.state.person);
       }
      })
  }

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>  
        <p>{this.state.person.contact}</p>
      </div>
    );
  }
}

export default App;
```

**Comment by grodrigues** [comment]
@fdaciuk  eu tinha colocado uma var local mais não funcionou.

**Comment by grodrigues** [comment]
![image](https://user-images.githubusercontent.com/3936016/40934089-08c228f6-680a-11e8-9c1f-343818d98ac4.png)

**Comment by grodrigues** [comment]
@helderburato   quando coloquei da forma que você falou desse erro.

**Comment by grodrigues** [comment]
Agora Assim Funcionou... import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import axios from 'axios';


class App extends Component {
  state = {
    person: {}

  }

  componentDidMount() {
    axios.get(`http://www.mocky.io/v2/5a5e38f3330000b0261923a5`)
      .then(res => {
        const person = res.data;
        this.setState({ person, name: person.profile.name });
        console.log(this.state.person, this.state.name);
      })
  }

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p> 
        <p>{this.state.name}</p>
      </div>
    );
  }
}

export default App;

**Comment by fdaciuk** [comment]
@grodrigues, no JSX vc vai renderizar o dado que precisa, não um objeto. O que eu falei de renderizar o `this.state.person`, era pegar a informação que você precisa dali ;)

Não precisa adicionar uma propriedade `name` no `state` se essa propriedade já está no objeto `person`, saca? Seria só renderizar `this.state.person.profile.name`, entendeu? =)

Só no `state` inicial, você precisa garantir que `this.state.person.profile` vai ser um objeto, senão você vai continuar tendo um erro. Então você pode ter seu `state` inicial assim:

```js
state = {
  person: {
    profile: {}
  }
}
```

**Comment by fdaciuk** [comment]
Ou ainda, antes de renderizar o que está em `this.state.person`, você checa se existe alguma propriedade nele.. se não existir, quer dizer que a o request ainda não foi feito, ae você pode mostrar um `Loading...` ou algo assim ;)

**Comment by grodrigues** [comment]
@fdaciuk Muito Obrigado Funcionando com sucesso.

**Comment by mathloureiro** [comment]
Uma dúvida @grodrigues porque usar o axio e não o fetch?

**Comment by grodrigues** [comment]
@mathloureiro não conhecia o fetch só depois que eu realizei o projeto.

**Comment by reinaldovale** [comment]
@mathloureiro, no Fetch, como usar o https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent?
