### ISSUE TITLE
Exemplo de uso de ITCSS?

### ISSUE THREAD

**Issue by simaodeveloper** [frontendbr/forum#1135]
Olá galera tudo bom, algum de vocês já utilizou a estrutura ITCSS em algum projeto Open Source? Se sim, conseguem deixar os links aqui em baixo para eu entender melhor como exemplo de uso ^^.

**Comment by LFeh** [comment]
Qual sua dúvida exatamente?

**Comment by simaodeveloper** [comment]
@LFeh Eu só gostaria de ver o ITCSS aplicado em projetos mesmo :D

**Comment by leandroruel** [comment]
dá uma olhada nisso aqui https://github.com/inuitcss

**Comment by LFeh** [comment]
@willianjusten Tem algum projeto open-source que usa essa metodologia?

**Comment by simaodeveloper** [comment]
@leandroruel valeu, vou dar uma olhada, curti que tem comentários bem explicativos dentro dos arquivos.

**Comment by willianjusten** [comment]
Infelizmente não tenho nada opensource usando (ao menos na rápida procura que dei), mas tirando o excelente inuitcss, tem também:

- https://github.com/NebulaUI/nebula-css
- https://github.com/BlazeUI/blaze/tree/master/scss/src
- https://github.com/csswizardry/frcss

**Comment by willianjusten** [comment]
Acabei de achar esse também:

- https://github.com/iotacss/iotacss

**Comment by simaodeveloper** [comment]
@willianjusten Valeu Professor, ajudou muito, para eu não encher mais o saco, mas quais palavras chaves você utilizou para realizar a busca no github?

**Comment by willianjusten** [comment]
O basico lol

- https://github.com/search?l=CSS&q=itcss&type=Repositories

**Comment by simaodeveloper** [comment]
Valeu @willianjusten eu que fiquei confuso na hora de realizar a pesquisa, obrigado!
