### ISSUE TITLE
Jquery, ainda é valido aprender?

### ISSUE THREAD

**Issue by romulosousa27** [frontendbr/forum#1142]
Pessoa que saber na opnião de vocês se ainda vale a pena usar o Jquery, vejo pessoas ultilizando outras tecnologias que fazem o mesmo papel ou até melhor que o Jquery.

**Comment by SandroSena** [comment]
https://github.com/frontendbr/forum/issues/1080

Abriram uma issue sobre o tema faz um tempo, da uma olhada.

**Comment by SandroSena** [comment]
Abriram uma [Issue](https://github.com/frontendbr/forum/issues/1080) sobre o tema faz um tempo, da uma olhada.

**Comment by simaodeveloper** [comment]
Depende do projeto! 

Essa pergunta é facilmente respondida lendo a documentação do JQuery, 
desse modo você entende os problemas que ele resolve, sabendo isso, 
você conseguirá decidir se ele resolve os problemas do seu projeto.

**Comment by simaodeveloper** [comment]
Vou acrescentar alguns pontos:

- JQuery é simples, fácil de ler e entender;
- É CrossBrowser;
- A Web é composta por Websites, e caso precise construir-los na minha opinião o JQuery é a melhor opção para entregar um resultado satisfatório em um prazo pequeno.
- Manipula DOM (Events, Traversing, Forms, Attributes, entre outros), realiza requisições HTTP (AJAX), cria Animações, Manipula múltiplas chamadas assíncronas via callback com Object.deferred (Você pode fragmentar esses recursos e adicionar no seu projeto, apenas o que for utilizar);
- Há uma vasta gama de Plugins a sua disposição;

Minha opinião ainda é **DEPENDE**, porém, acho que é um conhecimento válido, ele é fácil de ser aprendido, na verdade, o que precisar é só buscar na documentação, que é super fácil de ser compreendida.

**Comment by kvnol** [comment]
Issues iguais: #1080 #1142

**Comment by LFeh** [comment]
Duplicada
