### ISSUE TITLE
Coisas estranhas no mercado de front-end

### ISSUE THREAD

**Issue by nazarepiedady** [frontendbr/forum#1145]
Alguém já reparou em uma honda de vagas de desenvolvidores front-end em que é requerido como diferencial o profissional saber ou conhecer alguma linguagem de back-end e sem esquecer que a remuneração é medriuque em comparação com outras vagas que exigem muito bem pouco mais o remuneração é muito melhor?

**Comment by phsantiago** [comment]
Muitas empresas hoje em dia utilizam o scrum, nele é desejado que os developers saibam um pouco a mais do que a sua especialidade.
https://www.scrum.org/resources/blog/who-are-professional-scrum-developers

Não tem problema algum você ser especialista em front, mas o ideal é que você além da sua especialidade saiba pelo menos o feijão com arroz de outras, como UX, Back, QA... Fora isso você também pode manjar tudo de todas as áreas, e ser um profissional extremamente raro.

Sobre a remuneração é complicado, pois você vai receber pelo que você é capaz de produzir, se a empresa te oferece 1.000,00 R$ pela vaga, ela está esperando que você retorne mais que esse valor para ela. Para subir esses 1.000 para 10.000 por exemplo, você tem que convencer a empresa que consegue retornar muito mais dinheiro para ela do que ela está esperando de você.

**Comment by luizbills** [comment]
Infelizmente o mercado é complicado, ainda mais se for uma agência. Pedem várias  linguagens e tecnologias, mas quando você vai botar a mão na massa você praticamente usa apenas 10% do que eles pediam na vaga. Tem que penerar bastante e procurar boas empresas.

**Comment by thismarcoantonio** [comment]
É um pouco do que o @phsantiago disse, porém por vezes essas vagas são postadas por profissionais de RH que não fazem ideia do que estão escrevendo ali na vaga, imagine a situação:

Ronaldo precisa que Júlia, profissional do RH contrate profissionais que saibam Angular, porém Ronaldo também precisa de um Backend .NET, dessa forma pede a Júlia que procure por pessoas no nível Júnior/Pleno que saibam Angular e .NET.
Júlia não conhecendo o contexto, manda aquela vaga deliciosa no LinkedIn.

"Procuramos programadores Angular 2-5 com conhecimentos em .NET para executar juntamente com nosso time em x lugar

Salário inicial: 2500 reais".

Acredite, eu vejo isso acontecendo direto e não culpo quem postou a vaga, porém sempre aviso quando entram em contato comigo.

**Comment by vinicius73** [comment]
Há vários fatores que precisam ser observados.
O @phsantiago já comentou sobre a **necessidade** de profissionais especialistas com base generalistas, também conhecidos como [Profissionais T-shaped](https://tableless.com.br/o-perfil-t-shaped-e-o-dev-full-stack/)

Sobre vagas e requisitos... Há sempre esse problema de comunicação entre RH e quem solicitou a vaga, mas acredito que isso esta diminuindo.

Vejo muitos profissionais reclamando de vagas **honestas** por que não gostam da cidade da vaga.
Outros não leem o enunciado onde diz:

> Requisitos: Vue.js, ES2015+ e PWA
> Diferenciais: C#, Laravel e Rails

A vaga esta sendo clara, *"precisamos que você saiba Vue, ... e se souber C#,... será um plus"*  

Além disso, a percepção muda dependendo de onde você esta vendo essas vagas. Muitas (muitas mesmo) são divulgadas em grupos de desenvolvedores, comunidades. E muitas dessas divulgadas nem chegam a sites especializados, pois buscam indicações de quem é da comunidade.  

Já foi dito, e vale reforçar. Se você quer receber 5k, a empresa espera que você gere 10k, no minimo.

É importante ter em mente que salário varia muito dependendo da região do Brasil. Muitas vezes existe uma expectativa de altos salários logo no começo de carreia, isso não reflete a realidade.
