### ISSUE TITLE
Boilerplates para react

### ISSUE THREAD

**Issue by magnolemos** [frontendbr/forum#1147]
Pessoal, vou iniciar meu primeiro projeto em react amanhã. Tive 4 dias para estudar, e, nesses dias, fiz a carreira de react da Alura. O curso, como esperava, não é super atualizado. Tive bastante problema com plugins desatualizados, como, por exemplo, o react-router que foi usado na versão 3, dentre outros.
Sendo assim, gostaria de saber quais os melhores plugins/módulos vocês estão usando. Por exemplo, no curso, ele começa fazendo requisição ajax com jquery e depois muda para fetch api.
Fech api é uma boa? React-router 3 é confiável , ou devo atualizar para o 4?  
Terei algum problema conhecido de usar o react create app? No curso ele coloca o bundle de todas as páginas no App.js. Terei problema para gerar bundle por página?

Sei que a dúvida está um pouco vaga, mas  qualquer experiencia de alguém que ja usou react será muito valida. 

Valeu demais!

**Comment by carloshenriqueribeiro** [comment]
@magnolemos, sempre que começo em uma nova Stack curte pegar algum modelo Free como base do projeto de startup.
Aqui vai encontrar uma boa opção.
https://www.creative-tim.com/bootstrap-themes/free

**Comment by magnolemos** [comment]
@carloshenriqueribeiro , muito obrigado, não conhecia o site. Vou baixar um projeto lá para analisar. Uma pena não da para usar esses uikit, pois o layout já foi aprovado pela empresa.

**Comment by barbier** [comment]
[Lá no MPRJ nós criamos](https://github.com/MinisterioPublicoRJ/boilerplate) um com React, Redux e Axios, quando usamos rotas num projeto, usamos o Router 4

**Comment by magnolemos** [comment]
Legal @barbier, vou da uma olhada. Algum motivo para usar Axios e não fetch api? Pergunto pq nunca dei uma olhada no Axios

**Comment by marcosabb** [comment]
@magnolemos acredito eu que a fetch api só funciona em navegadores modernos, e o axios dá mais suporte a navegadores mais antigos, esse seria um motivo pra não usar a fetch api, ainda. ps: me corrijam se eu estiver errado.

**Comment by magnolemos** [comment]
@marcosabb, tem razão, preciso da suporte ao ie11, e não funciona nele. Sabe se o babel resolve esse problema?  Estou usando mac agora e não consigo testar no ie

**Comment by ninetails** [comment]
Se gostou de ter usado fetch, indico o [cross-fetch](https://www.npmjs.com/package/cross-fetch). Uma das poucas libs que dá pra dizer: _Write once, run everywhere_

Sobre o `create-react-app`, dá pra fazer muita coisa sem dar _eject_ e aprender muita coisa depois de rodar um eject. E ele vai te dar um workspace limpo sempre que você precisar testar alguma coisa em React.

Sobre versões do `react-router`, eu diria, claro, pra usar a última dada a preocupação da reescrita do pacote pra prover as rotas de um jeito mais declarativo. A versão 3 é confiável, não é beta, pode usar sem problemas e se não me engano não tem problemas de compatibilidade ainda com o React 16 (posso estar enganado). Mas ainda acho que vale a pena aprender e usar a versão 4. O único revés que vejo é que nessa versão nova ela usa `render props` e pode ser um pouco confuso para quem tá começando.

Sobre o ie11, creio que para os casos mais triviais, o `Babel` resolva sim. Precisaria configurar o `@babel/preset-env` e incluir o `@babel/polyfill`.

Sobre boilerplates prontos, indico o [Razzle](https://github.com/jaredpalmer/razzle), só não lembro se é `react-router` 4, mas inclui SSR (server side rendering) usando express.

**Comment by mahenrique94** [comment]
Sobre problemas de curso, é normal mano, manter cursos sempre atualizados é algo impossível.

Recomendo ir sempre das verões mais novas (estáveis), no caso do `react-router` vá com a versão 4.

Tanto `axios` quanto o `fetch` você conseguirá chegar no mesmo resultado, porém, o `axios` pode ser mais simples em alguns momentos, além de possuir mais recursos como *interceptors* de forma muito simples.

Questões de suporte, sempre existem os *polyfills* para resolver o problema (pelo menos tentar).

Utilize o `create-react-app` sem medo, se precisar customizar algo, faça o *eject* dele e boa.

**Comment by magnolemos** [comment]
Galera, muito obrigado pelas Dicas. Atualize o react-router pro 4, é um pouco diferente mas bem simples também (pelo menos por enquanto).
Comecei a da uma olhada no Axios agora. Vou usar ele mesmo, acredito que vai da menos trabalho estudar ele a fazer polyfill pro ie. 

Sobre o Eject, ainda não fiz, vou ler sobre ele e a alternativa passada pelo @edmolima.

Com o creat react app, o webpack pega os styles importados e da um append no header.
Eu tinha separado todo o css em componentes, porém, da forma que o webpack está configurado, da na mesma de colocar todos os componentes num arquivo só.

Como vocês costumam fazer? Deixam todos os componentes num arquivo só mesmo? Separam para facilitar a manutenção? Ou tem alguma forma de trazer apenas o css que aquela parte estar usando?

Obrigado demais a todos, estão me ajudando demais!

**Comment by edmolima** [comment]
@magnolemos  eu uso styled-components. E a gente testou várias possibilidades. A que atualmente usamos e vem funcionando bem é:


- Container,
- Stateless (biblioteca que construimos),
- Styles

Em outras palavras venho separando, isso significa que um modal por exemplo eu tenho:

modal.container.js
modal.js
modal.style.js

Como uso styled-components que falei acima, eu recebo as props no componente e uso pra coisas do tipo validação, desabilitar e etc.

Isso escala bem, mas não há um jeito certo. Como te falei é bom tu ir testando e vendo o que fica melhor.

**Comment by magnolemos** [comment]
@edmolima , bem legal cara, era algo assim que estava precisando mesmo. Vou tentar implementar ele aqui.

O problema é que preciso entregar a primeira sprint daqui a duas semanas. Então não da para testar muita coisa =/.

**Comment by edmolima** [comment]
Entendi @magnolemos 
Mas quando falo testar é implementar. Depois de feito se tu achar que ficaria melhor de outro jeito vai lá e faz diferente.

É normal você ir evoluindo e reler um código e achar que ficaria melhor de outro jeito. Faz parte de nós hehe.

Então o legal é que você tome uma decisão e faça. É aquele lance de melhoria continua.

Mas funciona bem cara, segue uma linha que vai escalar. Se tu usar composição com HOCs melhor ainda que u pode ir reaproveitando comportamentos por exemplo:

Upload de foto
Upload de Arquivo.

Pode ser um componente (hoc) com essa função e assim vai...

**Comment by magnolemos** [comment]
@edmolima, verdade! Bom que com a ajuda de vocês, a chance de refazer algumas coisas diminuem bastante. 
Como vc usa a arquitetura de pastas?
Eu criei uma pasta components, que tenho todos meus componentes. Cada componente vai ter uma pasta, porque vou usar o styled-components. E tenho uma pasta chamada pages, a qual monto as páginas e importo os componentes que vou usar. Logo, o hoc é a página. 

Fazendo como vc sugeriu, de ter o hoc por componente mesmo (que faz mais sentido), eu crio o hoc como se fosse mais um componente, dentro da pasta components. Você faz +- dessa forma?

**Comment by edmolima** [comment]
@magnolemos boa cara!

Então a idéia como te falei é: A maioria (80%) dos componentes stateless eu uso numa biblioteca externa que criamos. Basicamente é uma lib de componentes. Existe as vezes um componente que não será reaproveitado ai crio direto na aplicação.

Isso nos leva a ter na aplicação apenas componentes statefull no geral e algumas hocs. Nossa organização fica assim:

```
/src
  /config
  /services
  /store
  /utils
  /components
      /Home
      /About
      /Routes
      index.js
```

Qualquer coisa do "dominio" do componente eu deixo explicito dentro da pasta do componente. Por exemplo:
```
/Home
  Home.js
  Home.reducer.js
  Home.saga.js
  Home.spec.js
  Home.theme.js (um arquivo de tema do componente)
  Home.style.js
```

Isso me garante isolar para futuros reaproveitamento e me dá maior coesão. Se for algo compartilhado por exemplo: Uma saga que vai ser usada por todos. Ai eu já sei e removo daí, dessa forma fica claro e previsível o que é compartilhado e o que é especifico.

**Comment by magnolemos** [comment]
Bacana @edmolima 
Por horas aqui tá assim
/src
Router.js
Index.js
App.js
  /config
  /functions
  /styles (ainda to migrando)
  /store
  /components 
     /Card
  /pages
      /Home
        HomePage.js
        HomeActions.js
        HomeReducer.js
        HomeTypes.js
     /About

Bom que todos os componentes que criei até agora são apenas para exibir dados da requisição, então tá tranquilo de criar hoc da forma que você fez quando tiver um componente com funcionalidade

Valeu demais!

**Comment by edmolima** [comment]
Massa @magnolemos, o que importa cara é você seguir uma linha. Se tu tem uma equipe alinhar com eles e seguir. Nada de otimização prematura mas sempre pensando na evolução da aplicação. Se você ver que não tá fácil escalar, melhor pensar em outra abordagem. Discute com o time, acerta todos os detalhes e segue numa linha de pensamento.

No fim é isso que importa.

**Comment by ninetails** [comment]
Como disseram, também acho que o ideal é vc adotar um padrão e ver as dores, pq não há estrutura ideal (de pastas, do que vc vai usar como axios ou fetch), mas sim deixar de um jeito que seja fácil de evoluir e reescrever futuramente. Não existe bala de prata e também a gente nunca vai fazer uma estrutura que vai ser ideal e escalável a longo prazo, ou mesmo fatalmente vai precisar atualizar algum pacote e reescrever parte do código. E muitas vezes o que alguém fez, não vai necessariamente refletir ao que vc e seu time ou produto precisa.

Tem diversas threads já sobre estrutura de pastas por aqui :D Além de artigos no Medium

**Comment by clucasalcantara** [comment]
@magnolemos Fora o conteúdo excelente ai em  cima que já dá pra resolver todos os seus problemas :P eu  tb acho que seria legal vc tentar estudar alguns padrões de divisão de componentes/pastas e tentar achar um que mais faça sentido pro layout e serviços que vc tem. 

Alguns textos pra te guiar a começar, recomendo pesquisa e reforço que não existe **bala de prata** :)
https://medium.com/reactbrasil/react-estruturando-projetos-e-nomeando-componentes-b62ddad69a11
https://speakerdeck.com/matheusml/organizando-aplicacoes-com-react

**Comment by magnolemos** [comment]
@edmolima  falou tudo cara.
@ninetails, pior que sobre essa parte, eu perguntei aqui antes de pesquisar mesmo, porque veio no fluxo da conversa. Dei uma lida nos artigos enviados pelo @clucasalcantara (valeu cara :D ) e alguns outros,  agora to mais confortável com a arquitetura que estou seguindo. 
Valeu demais Galera!
