### ISSUE TITLE
github port 22

### ISSUE THREAD

**Issue by romulo2735** [frontendbr/forum#1149]
Galera queria pedir uma ajuda, estou usando o GIT a muito tempo para versionar meus codigos, sendo que de ontem para hoje ele não consegue fazer nada pelo SSH, diz que não `connect to host github port 22: Connection timed out`

Alguém poderia me ajudar?

**Comment by LFeh** [comment]
Está usando a NET?

**Comment by romulosousa27** [comment]
Como assim NET, Linguagem?

**Comment by carloshenriqueribeiro** [comment]
muda para o HTTPS. Só dar um set-url no seu remote alias (geralmente origin) com o caminho indicado pelo seu client do Git (Github, VSTS ou qualquer outro).

**Comment by carloshenriqueribeiro** [comment]
git remote set-url origin "aqui vai o endereço HTTPS"

**Comment by carloshenriqueribeiro** [comment]
O meu deu o mesmo problema hoje. Estou usando VSTS e no meu caso a chave não expirou (geralmente 1 ano para expirar). Depende de como você configura.

**Comment by LFeh** [comment]
Exatamente, a NET (deve acontecer com outras operadoras), basta fazer isso que o @carloshenriqueribeiro que deve resolver.

**Comment by romulosousa27** [comment]
@LFeh uso PHP + Laravel

**Comment by romulosousa27** [comment]
@carloshenriqueribeiro eu estou usando o HTTP agora, mas troquei o ssh e ainda continua.

**Comment by carloshenriqueribeiro** [comment]
@romulosousa27 continua funcionando ou sem funcionar ?

**Comment by romulosousa27** [comment]
@carloshenriqueribeiro ainda nada, estou usando HTTPS :(

**Comment by carloshenriqueribeiro** [comment]
Calma. 
1) Pelo o que entendi o https tá funcionando, certo ? Então pelo menos tem como trabalhar.
2) Pq precisa tanto do túnel SSH ?
3) Para configurar o SSH, faça o procedimento novamente, ou seja, gere uma nova chave pública e depois, usando essa chave, configura a conexão com o seu client web.

**Comment by carloshenriqueribeiro** [comment]
Pelo o que entendi o seu client web é o Github
Tá aqui o passo a passo
https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

Só preste atenção em qual é o seu SO para saber exatamente onde a chave é salva mas sinceramente não vejo vantagem no uso do SSH, principalmente se manter as chaves no diretório padrão.

**Comment by Sabidos** [comment]
Amigo,

Tenta usar o 

https://www.sourcetreeapp.com/

Desde que comecei a usar ele não tive mais vontade de trocar de cliente GIT

**Comment by carloshenriqueribeiro** [comment]
@romulosousa27 https não é lento, tão rápido quanto e não é preciso interface para uso de https. Só rodar via terminal.

**Comment by romulosousa27** [comment]
@carloshenriqueribeiro to ligado.

**Comment by felipemfp** [comment]
SSH tem a vantagem de não precisar digitar senhas a cada *push*.

**Comment by carloshenriqueribeiro** [comment]
@felipemfp https não precisa tbm

**Comment by carloshenriqueribeiro** [comment]
@felipemfp
Eh nada. Só usar o config credencial.
Só pesquisar no Google por Git credencial for "o seu SO".
Ou usar o Git credencial Heller
https://git-scm.com/docs/gitcredentials
Boa sorte!

**Comment by felipemfp** [comment]
> @felipemfp
> Eh nada. Só usar o config credencial.
> Só pesquisar no Google por Git credencial for "o seu SO".
> Ou usar o Git credencial Heller
> https://git-scm.com/docs/gitcredentials
> Boa sorte!

Hmmm, então precisa de senha sim. Você só tá utilizando uma tool para informar a senha. :slightly_smiling_face: 

Aliás, SSH é [mais](http://blog.iqandreas.com/git/storing-https-authentication-in-ubuntu-and-arch-linux/) [seguro](http://jr0cket.co.uk/2016/05/ssh-or-https-that-is-the-github-question.html). E a única vantagem do HTTPS é a porta ser aberta em todos os firewalls (algumas redes preferem bloquear o SSH, não que eu já tenha passado por isso).

E não esquece de criptografar suas credenciais e habilitar o 2FA, se continuar optando pelo HTTPS.

**Comment by carloshenriqueribeiro** [comment]
@felipemfp claro que precisa da senha assim como o ssh precisa da chave. Você reclamou que teria que digitar a senha toda vez e isso não é preciso, já que existem soluções de cache. Besteira afirmar que SSH é + seguro. Se roubarem seu note com a configuração da sua conta do Github, basta mudar a senha do seu usuario, assim como deveria fazer com todas as outras senhas salvas no seu Browser. Além da facilidade de configurar a configuração HTTPS, bom o próprio Github recomenda HTTPS.

**Comment by carloshenriqueribeiro** [comment]
Só um push e um pull ? Kkkkk Ok.

**Comment by carloshenriqueribeiro** [comment]
Já vi que é do estilo extremista. Sou + o perfil do ponderado mas obrigado pelas dicas.

**Comment by barraponto** [comment]
Se a sua conexão bloqueia a porta 22, como algumas empresas fazem (a Unicamp, por exemplo) vc pode usar o SSH do github pela porta 443 (a porta do HTTPS, que dificilmente vai ser bloqueada). É simples: https://help.github.com/articles/using-ssh-over-the-https-port/

**Comment by grsabreu** [comment]
a NET é conhecida por essas sacanagens, além de poder usar o HTTPS no lugar vc pode tb usar um proxy que funciona deboa. Eu recomendo o https://www.privateinternetaccess.com/

**Comment by gregorbr** [comment]
Eu tô tendo o mesmo problema. Erro: "ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

Eu segui este artigo e não revolveu: https://help.github.com/articles/connecting-to-github-with-ssh/

**Comment by gregorbr** [comment]
Tentando a solução do Carlos (git remote set-url origin "aqui vai o endereço HTTPS"), quando eu tento dar o push, retorna o erro: "fatal: unable to access 'https://github.com/gregorbr/portfolio-gregor.git/': Failed to connect to github.com port 443: Timed out".

**Comment by ranosi** [comment]
Esse problema de bloqueio de portas ou algo parecido, rolou com um amigo aqui, usando a Claro.
https://medium.com/we-are-bunny-inc/https-medium-com-we-are-bunny-inc-blocked-ports-a-story-of-brazilian-net-neutrality-8bc36040d6d0

**Comment by romulosousa27** [comment]
Foi resolvido aqui! Valeu galera

**Comment by romulosousa27** [comment]
Mais ou menos, como peguei um novo processador tive que formatar, ai "voltou"

**Comment by guilhermefontans** [comment]
Alterei o arquivo ~/.ssh/config e coloquei essas linhas:
`Host github.com
  Hostname ssh.github.com
  Port 443
`

**Comment by tadeumesquita** [comment]
> Se a sua conexão bloqueia a porta 22, como algumas empresas fazem (a Unicamp, por exemplo) vc pode usar o SSH do github pela porta 443 (a porta do HTTPS, que dificilmente vai ser bloqueada). É simples: https://help.github.com/articles/using-ssh-over-the-https-port/

Aqui deu certo! Uso Kubuntu 18.04 e meu proivedor é a NET
