### ISSUE TITLE
Segmentos dentro do front-end

### ISSUE THREAD

**Issue by leocavalcante** [frontendbr/forum#115]
Lembram do final dos anos 90 que o webdesigner era o menino do computador que fazia do layout até o servidor? Pois é, os tempos mudaram e hoje temos diversos segmentos dentro do desenvolvimento web, um deles, o Front-end.

Só que tenho visto algumas vagas na gringa intituladas "Front-end Designer" e outras "Front-end engineer". Acho que já da pra saber onde quero chegar.

Será que teremos o cara do HTML/CSS que implementa a UI/UX e o motion e um cara do JavaScript que implementa as interações de forma separada numa equipe?

**Comment by bernardodiasc** [comment]
Acho que as issues #49, #75 e #32 são sobre esse mesmo tema.

**Comment by leocavalcante** [comment]
Legal, a #32 é praticamente isso mesmo.

**Comment by LFeh** [comment]
Boa, valeu @bernardodiasc. 

@leocavalcante COnsegue postar em alguma das issues?
