### ISSUE TITLE
Dificuldades ao ingressar no mercado de front-end!.

### ISSUE THREAD

**Issue by nazarepiedady** [frontendbr/forum#1150]
Qual foi os seus desafios quando esteve para entrar no mercado de front-end development?

**Comment by renanlara** [comment]
A mais de 6 anos, venho trabalhando com o WordPress, nas agências que trabalhei, a minha tarefa era desenvolver o front e boa parte do back-end. Durante esses anos, eu meio que fiquei preso à isso, o que não é nada bom. Eu não tive a oportunidade em aprender de fato JavaScript, só o basicão posso dizer assim...

Hoje, estou procurando mergulhar em JavaScript, procurando estudar o máximo que posso. A minha meta é que se possível, eu venha trabalhar só com ele. Só quê, melhor do que estudar uma linguagem, conhecer ela de cabo a rabo, é você trabalhar com aquilo no seu dia-a-dia. Aí sim você terá um domínio em pouco tempo do que está aprendendo.

Sendo assim, a minha dificuldade é essa: encontrar um lugar onde eu possa não só trabalhar mas também aprender, imergido na linguagem. 

Para resolver isso, estou procurando vagas aqui mesmo com testes no processo seletivo para enxergar o quanto eu estou melhorando.

**Comment by kelvinoenning** [comment]
Concordo com o @fernandoRj, vejo bastante desenvolvedores reclamando que não conseguem ingressar no mercado, porém quase nenhum se preocupa em mostrar o trabalho que já aprendeu.

Realmente ingressar neste mercado sem saber muita coisa é complicado.

Minha dica é sempre ter um portfolio, blog ou projetos open source atualizados para mostrar seu conhecimento, isso ajuda muito na contratação. Foi como eu iniciei, e vem sendo até hoje bastante positivo.

**Comment by caioincau** [comment]
Acho que um dos desafios hoje, é que existem "poucas" vagas para Jr ou Estágio, o pessoal sabe que Front ficou complexo e está focando em contratar Pleno para cima.

**Comment by synga** [comment]
Trabalho com front há 2 anos, essa empresa que estou é a primeiro que trabalho na área de T.I. e etc. Minha dificuldade na época foi totalmente técnica, vim de trainee de backend pra área de front praticamente sem conhecimento, meu diferencial foi em soft skills, me comunico bem e mostrei que queria realmente aprender, nem só de hard skills vive um homem.

Chega em entrevista e conversa bem, se solta, questiona. Se não tem portfólio pede um teste, pede uns dias, fala que conhece pouco, mas que vai tentar fazer o melhor possível, pergunte sobre o teste, se querem que use uma ferramenta especifica e etc.

Equilibre o conhecimento que te falta com a vontade de aprender. Mas não fique só esperando soft skills resolver tudo, nesse meio tempo vá atrás de aprender sim, converse com o pessoal da comunidade, pegue dicas, siga pessoas legais, estude muito e crie algo palpável, que poderá ser visto.

**Comment by matheus-rosin** [comment]
Será que existe algum site que tenha esse foco, digo, que disponibilize vagas de nível júnior, para que está tentando ingressar? Porque tenho procurado há tempos e não tenho conseguido nada...

Meu primeiro problema é não ter curso superior; e, pelo que tenho visto, especialmente aqui no Brasil a galera preza muito por isso. Daí das vagas que geralmente sobram, ou pedem bastante tempo de experiência (em geral no mínimo 3+ anos), ou pedem algum teste (que geralmente faço, mas nunca sequer recebo uma negativa).

Tenho um conhecimento legalzinho, e como estou desempregado, gasto várias horas por dia aprendendo coisa nova, sempre com a intenção de me adaptar melhor às oportunidades. Mas, na realidade, o que tenho percebido é que, bem lá no fundo, quando a galera vê que não tenho curso nem experiência (e não tenho experiência por causa do curso, um belo loop infinito), me jogam pra escanteio, porque especialmente aqui no Brasil tem muita gente disputando as mesmas vagas e os caras podem escolher a dedo quem querem.

Sei lá, também tenho tentado algumas coisas lá fora por meio do Angel List e do StackOverflow, mas são sites muito "visados", todo mundo vê por lá, então acho que são poucas as chances reais.
