### ISSUE TITLE
É dever do desenvolvedor front-end ter dominio de design gráfico?

### ISSUE THREAD

**Issue by nazarepiedady** [frontendbr/forum#1151]
Eu tenho a certeza de que é um plus para as capacidades do desenvolver front-end aprender a dominar ferramentas de design gráfico e saber ilustração e art digital.

**Comment by tgmarinho** [comment]
acho que é um plus e não dever, geralmente vc vai receber as artes prontas e colocar isso dentro do seu html, css, javascript.

Imagina você vai escrever o front-end e ainda criar todas as artes do seu site? Deve ser muita coisa para fazer, estudar e se aperfeiçoar.

**Comment by nazarepiedady** [comment]
Ajuda a desenvolver a criatividade.

**Comment by magnolemos** [comment]
OI @nazarepiedady , acho que varia bastante de empresa para empresa. Acho necessário saber pelo menos o básico.
Onde eu trabalho todos os fronts fazem design, ui, ux.
Mas ja trabalhei em lugar que eram bem dividido as responsabilidades

**Comment by carloap** [comment]
Acredito que já disseram tudo. 
O front-end developer precisa ter as noções básicas de design e ux, até para ter um briefing mais claro dos projetos.
Sem manter o foco demais nisso, pois são áreas distintas. 
Mas tem casos e casos, esses são os famigerados "programadores ninja".

**Comment by fernandoRj** [comment]
hoje em dia estao exigindo mais que vc saiba design, pq o front end ta meio dividido em pessoas que sabe react,angular e o front end que cria somente a parte visual do site, hoje em dia mts design de formação estão estudando html  css javascript.

**Comment by renanlimabl** [comment]
Cara, depende onde você vai trabalhar! Se for uma empresa boa, vai ter os designs e vai ter os desenvolvedores, mas sempre é bom você ter pelo menos uma base! Vai ter situações que você terá que "falar mais alto" que o design e dizer pra ele que da tua forma é melhor, mas tu vai ter que saber argumentar aquilo.

**Comment by LFeh** [comment]
Acho que precisa de senso estético, não acho que precise dominar uma segunda área.

Mas se dominar é um plus, e um puta plus.
