### ISSUE TITLE
O Front-end esta com os dias contados?

### ISSUE THREAD

**Issue by fernandoRj** [frontendbr/forum#1152]
li um artigo falando que cada vez mais os sites estao deixando de ser apenas uma pagina web e estao se transformando em sistemas que faz algo, e por isso tende a se padronizar cada vez mais interface, sendo assim o front-end que geralmente transforma o psd em site estaria com os dias contados, ja que cada vez mais design UI/UX com suas ferramentas de geração de codigo estao fazendo o trabalho que nos realizarmos hoje, o que vcs acham disso? qual a tendencia do front-end na visao de vcs para os proximos 3 ou 4 anos?

**Comment by ViniciusGularteMartin** [comment]
Olha essa issue [490](https://github.com/frontendbr/forum/issues/490)
é uma das mais comentadas aqui no forum e traz a sua mesma questão.

**Comment by LFeh** [comment]
Vale manter a discussão nessa issue que o @ViniciusGularteMartin citou (essa issue ainda é bem viva, hahaha). 

@renanlimaweb Consegue jogar seus pontos lá tambem? 😄
