### ISSUE TITLE
Imprimindo dados do sistema web para impressora

### ISSUE THREAD

**Issue by renanlara** [frontendbr/forum#1155]
Pessoal, bom dia!
Eu tenho alguns cartões impressos. Neles, existe uma tabela para ser preenchida. A minha ideia é criar um sisteminha para armazenar os dados e imprimir depois nesses cartões.

Para isso, eu teria que “recriar” o layout do cartão na web e puxar os dados e depois imprimir.

A minha dificuldade é que, na impressora, a unidade de medida é em centímetros e na web é em pixels.
Como que eu consigo fazer essa comunicação do meu sistema com a impressora?

**Comment by renanlara** [comment]
@kivervinicius, que sensacional!
Muito obrigado!

**Comment by drianoaz** [comment]
@kivervinicius, não acredito que passei minha vida inteira sem conhecer este repositório. Sempre sofri muito para fazer isso, mas agora utilizarei essa parada!

**Comment by kivervinicius** [comment]
@drianoaz  que bom que foi útil, eu realmente abstrai as regras do css e usei nos meus projetos, pq são mto simples
