### ISSUE TITLE
Moodle em Docker Apresentando Problemas ao Tentar Carregar Imagens e outros Arquivos

### ISSUE THREAD

**Issue by Fabot7** [frontendbr/forum#1156]
Prezada Comunidade GitHub,

Estou executando o Moodle em Docker, com um contêiner para a aplicação moodle e outro para o banco de dados do Moodle (MySQL). Os contêineres se comunicam entre si e tudo está em funcionamento, com apenas uma exceção: a aplicação não está localizando algumas imagens (banners e logotipo) e outros arquivos, como .doc, .xls, .pdf, entre outros. Esse problema provavelmente está relacionado a um problema de caminho relativo. Como medida de contorno, eu tenho procurado pelo PHP Relative Path, por exemplo include_path (php.ini), require_once dirname (FILE) (pluginfile.php) e funções relacionadas, ainda sem sucesso. Além disso, eu busquei por erros de log no Apache2 e PHP, mas nada foi encontrado. Também verifiquei o VirtualHost do Apache2, mas ainda não tive nenhuma ideia do que poderia estar errado. É importante lembrar que localmente essa configuração do Moodle está funcionando conforme esperado, quando executada diretamente no meu PC Ubuntu. Esse problema só acontece quando eu executo o Moodle no container Docker, que também executa a mesma imagem Ubuntu 16.04, que uso localmente no PC.

Alguém tem alguma ideia de como lidar com esse tipo de problema?

![moodle em docker](https://user-images.githubusercontent.com/39347088/42773418-a70b4a32-891c-11e8-8e89-6def9161fefe.PNG)

**Comment by LFeh** [comment]
@Fabot7 Just in pt-br 🇧🇷, please

**Comment by Fabot7** [comment]
Prezada Comunidade GitHub,

Estou executando o Moodle em Docker, com um contêiner para a aplicação moodle e outro para o banco de dados do Moodle (MySQL). Os contêineres se comunicam entre si e tudo está em funcionamento, com apenas uma exceção: a aplicação não está localizando algumas imagens (banners e logotipo) e outros arquivos, como .doc, .xls, .pdf, entre outros. Esse problema provavelmente está relacionado a um problema de caminho relativo. Como medida de contorno, eu tenho procurado pelo PHP Relative Path, por exemplo include_path (php.ini), require_once dirname (FILE) (pluginfile.php) e funções relacionadas, ainda sem sucesso. Além disso, eu busquei por erros de log no Apache2 e PHP, mas nada foi encontrado. Também verifiquei o VirtualHost do Apache2, mas ainda não tive nenhuma ideia do que poderia estar errado. É importante lembrar que localmente essa configuração do Moodle está funcionando conforme esperado, quando executada diretamente no meu PC Ubuntu. Esse problema só acontece quando eu executo o Moodle no container Docker, que também executa a mesma imagem Ubuntu 16.04, que uso localmente no PC.

Alguém tem alguma ideia de como lidar com esse tipo de problema?

**Comment by danjesus** [comment]
@Fabot7 como fica o caminho do arquivo no browser?

**Comment by Fabot7** [comment]
Prezados(as),

O problema foi solucionado ao direcionar o $CFG->dataroot (config.php), para o local exato onde se encontrava na máquina local da qual foi realizada a exportação do banco de dados (.sql).
