### ISSUE TITLE
Verificação de autorização em cada rota de SPA

### ISSUE THREAD

**Issue by hectorgrecco** [frontendbr/forum#1159]
Fala, galera! Gostaria de saber como vocês fazem verificação de autorização do usuário em cada rota da sua Single-Page Application e também ver se o jeito que estou fazendo é o mais adequado. Vamos lá:

"Ambiente": Um usuário tem um tipo (admin ou usuário normal). Um usuário normal não pode acessar a rota de Configurações do Sistema na SPA.

Como vocês verificam a autorização dele vinda do servidor? Atualmente antes de entrar em cada rota é feita uma requisição no Axios pra verificar se o usuário tem permissão pra acessar aquilo, porém eu penso que executar uma requisição pra cada rota que os usuários acessarem é uma "tragédia", kakakaka... E também nem rola de jogar o role do usuário no local Storage, tendo em vista que ele pode ser editado pelo Developer Console do Google...

Utilizei a busca mas não encontrei uma resposta que se aplicasse à minha situação...

**Comment by hectorgrecco** [comment]
Não sejam como eu... usem a busca! hahahahaha

**Comment by kivervinicius** [comment]
coloca a resposta ai para a galera que cair na busca kkk

**Comment by kavalcante** [comment]
Eu utilizo Vue.js com Nuxt, no Nuxt, existe o conceito de middleware (igual no back-end). A ideia é simples, em toda página eu posso setar middleware que serão executados antes do usuário de fato entrar na rota.

Já a questão de permissão, nós temos 2 padrões aqui, um por ROLES (já explico) e outra por permissão mesmo.

A permissão é simples, eu defino um "tipo" de usuário, por exemplo:
- Comprador
- Fornecedor
- Admin

Com base nisso, eu crio diferentes middlewares que bloqueiam baseado no tipo do usuário. Porém, o mais comum para mim é renderizar componentes baseado no tipo. Ou seja, cada componente mostra as informações que aquele tipo de usuário pode visualizar.

Esse "tipo" do usuário, eu carrego na minha sessão, no meu caso, utilizando Vuex. Mas poderia ser localStorage, Redux ou qualquer coisa do tipo.

O outro método, mais completo, porém mais trabalhoso. É com base em ROLES, basicamente, cada usuário possui um array de roles, que são as permissões dele no sistema, por exemplo, o usuário 1 possui tais roles:

- createProduct
- editProduct
- seeProduct

Dai baseado na rota, eu verifico se ele possui aquela role para, por exemplo, visualizar um produto. Se ele não possuir eu redireciono ou dou um erro de permissão na página.

Mas eu nunca vou no back-end para ver isso, pois essas informações o back-end me retorna quando o usuário loga.

Existem também essas mesmas validações no back-end pra evitar bugs. Mas no geral é isso. Espero ter ajudado!

**Comment by hectorgrecco** [comment]
Fala, @kavalcante  beleza?
Esqueci de mencionar na issue que também tô usando Vue.js, só que sem Nuxt ou Vuex.
Enfim, mas ainda fico na dúvida, o usuário pode editar os dados persistidos vindos com o login a qualquer momento ainda, certo?

**Comment by kavalcante** [comment]
Olha cara, honestamente, acredito que ele até possa editar. Porém, entra o fator back-end bloquear dados e informações que ele teoricamente não pode ver. Então ao entrar na rota, o seu back-end já iria bloquear, só que de uma maneira menos "amigável".

E na real, eu não achei nada falando sobre mudar o Vuex diretamente pelo console, por exemplo. Então nem sei se é possível. Mas mesmo sendo, entra no fator acima.

**Comment by kavalcante** [comment]
Aqui tem uma explicação um pouco melhor sobre isso:

https://stackoverflow.com/questions/49122648/vuex-is-it-possible-to-directly-change-state-even-if-not-recommended

**Comment by kavalcante** [comment]
Nós utilizamos JWT Token, o back-end sempre descriptografa o token e pega o usuário logado. Então mesmo que ele mude a sessão dele, é impossível ele criar um token, por conta do salt.

**Comment by hectorgrecco** [comment]
@kavalcante Agora eu entendi! (Faltou um pouco mais de estudo sobre o real uso do Vuex hehehe), só seria possível editar os dados novamente se eu desse outro "set" na variavel que está no store do Vuex... Valeu demais!!!!
