### ISSUE TITLE
Pusher + Ionic vale a pena?

### ISSUE THREAD

**Issue by wpbarcelos** [frontendbr/forum#1167]
Olá,

Pessoal eu gostaria de saber o que acham da combinação de Pusher(pusher.com) + Ionic.

Eu precisei implementar socket no app e já conhecia o pusher, porem estou achando uma solução cara, já que para atender ao cliente será preciso um plano de 90$ (doletas) . 

Você tem algum outro serviço como alternativa, ou criar um serviço de socket seria o ideal? E qual o framework mais indicado para criar o serviço de socket+ api?

**Comment by LFeh** [comment]
Conhece algo @willgm

**Comment by luizbills** [comment]
Acho que você podia trocar o ionic pelo React Native ou pelo NativeScript, caso não manje de react.

Na parte *realtime* têm várias soluções open source que podem te ajudar. Algumas que eu conheço/lembro:

- https://feathersjs.com/
- https://www.rethinkdb.com/
- https://gun.eco/

**Comment by wpbarcelos** [comment]
Obrigado @luizbills ,

Eu obrigado pelas opções do realtime, quanto ao React Native concordo, aqui na empresa é algo que tenho que trazer e nivelar com a equipe.

Vou testar as opções, estou pensando em criar um serviço para atender a todos os clientes.

**Comment by houstondapaz** [comment]
@wpbarcelos dependendo da sua demanda, o Pusher não vale a pena.
Eu fiz uma cotação e ia ficar um preço absurdo para o meu sistema.
Criar um serviço de socket com socketio está fora de cogitação? Se não quer se preocupar com websocket, o Firebase tb é uma boa alternativa.

A maior treta com socketio é sua infra, tem que ficar ligeiro com numero de conexões e configurar bem seu nginx para fazer os parsers/routers

**Comment by synga** [comment]
Cara acho muito boa a combinação de Ionic + Firebase, como o @houstondapaz já deu a ideia ai acima. Nunca me deixou na mão, é rápido de configurar, fácil de aprender, te disponibiliza varias coisas legais a mais e o plano intermediário deles, o Flame, já atende muita coisa, depois tem o Blaze que é pago por uso. Enfim, uso e recomendo independente do intuito em que real time vai ser necessário.

**Comment by wpbarcelos** [comment]
Vlw Pessoal pelas dicas vou tentar o Firebase, 
Apesar do cliente falar que paga , eu sinceramente achei muito caro e está me incomodando, 
Não queria fazer um serviço por questões de implantação,porque o sistema atual roda no IIS , com  PHP e Oracle.
