### ISSUE TITLE
Materiais para quem quer dar mais um passo adiante no front-end

### ISSUE THREAD

**Issue by nazarepiedady** [frontendbr/forum#1173]
Livros ou artigos para se aprofundar no conhecimento de html5, html5.2, semântica e acessibilidade.

**Comment by diessica** [comment]
https://frontendmasters.com/books/front-end-handbook/2018/

**Comment by luizbills** [comment]
para um front mais focado em UI:
https://medium.com/@erikdkennedy/7-rules-for-creating-gorgeous-ui-part-1-559d4e805cda
https://atomiks.github.io/30-seconds-of-css/
https://www.smashingmagazine.com/2016/04/web-developer-guide-color/

**Comment by rubenmarcus** [comment]
Vc nao citou JS , mas vou colocar alguns cursos que tão no meu radar

[Learning Algorithms in JavaScript from Scratch](https://www.udemy.com/learning-algorithms-in-javascript-from-scratch/)
[JS com TDD na Prática](https://www.udemy.com/js-com-tdd-na-pratica/)

[Learning Data Structures in JavaScript from Scratch](https://www.udemy.com/learning-data-structures-in-javascript-from-scratch/

[Javascript Intermediate level 2 - All about functions](https://www.udemy.com/javascript-intermediate-mastering-functions/)

[JavaScript Design Patterns: 20 Patterns for Expert Code](https://www.udemy.com/javascript-design-patterns-20-patterns-for-expert-code/)

**Comment by tarciozemel** [comment]
Obrigado pela lembrança, @linconkusunoki!

Quem achar que vale a pena, tô liberando uns cupons de desconto aqui:

* https://www.udemy.com/css-um-passo-adiante/?couponCode=RECURSOS_FRONTEND
* https://www.udemy.com/css-grid-layout/?couponCode=RECURSOS_FRONTEND
* https://www.udemy.com/flexbox-guia-completo/?couponCode=RECURSOS_FRONTEND
