### ISSUE TITLE
[React/Redux] Imutabilidade com objeto audio no redux.

### ISSUE THREAD

**Issue by tunnes** [frontendbr/forum#1174]
Pessoal, boa noite  =]

Estou estudando o react com o redux e acredito conhecer os pilares do paradigma funcional, mas treinando em um pequeno player de audio e me deparei com um ponto e estou incerto de ter resolvido  da melhor forma... Como o redux gera uma trilha de estados, quando eu chavama a action para troca de música (No caso do [gist](https://gist.github.com/tunnes/a90d17257b7b8f686e24a4131967bfc5) a action `CHANGE_TRACK`) ele não parava o antigo audio ai misturava todas as musicas... Pensei em deixar na action de troca parando o audio do estado atual, ai sim trocar, mas ai pensei na questão do acoplamento ficar alto. 

Caso seja necessário esse é o projeto completo: [projeto completo](https://github.com/tunnes/web-player)

A solução que adotei foi jogar isso no reducer, no dia-a-dia de vocês isso é considerado uma má prática? Como vocês trabalham com o objeto audio no redux, tem como eu torná-lo um objeto controlado?

**Comment by phsantiago** [comment]
`state.audio.pause()` é um side effect.

Deixe seu reducer assim:

```jsx
const INITIAL_STATE = { data: null, audio: null }

export default (state = INITIAL_STATE, action) => {
  switch (action.type) {
    case 'CHANGE_TRACK':
      return { ...state, data: action.payload, audio: action.payload.download_url }
    default:
      return state
  }
}
```

O lugar onde os side effects devem ficar é nas actions. Se você quer dar play ou pause, use um middleware para fazer isso na action. Pode ser Saga, Thunk, Observable, Promise.

**Comment by tunnes** [comment]
@phsantiago Só uma outra dúvida bixo, o objeto audio eu não devo deixar no state do track? Pergunto isso pois pelo que estava rolando instanciando um novo audio toda vez que o estado mudava ele misturava as músicas e como esse objeto não estava no state eu não conseguia chamar o método pause daquela instância que tava tocando.

**Comment by LFeh** [comment]
@fdaciuk

**Comment by tunnes** [comment]
@dougaraujos, @phsantiago e @LFeh Brigadão pela ajuda caras! Compreendi que realmente não é nem um pouco okay deixar na store o audio, aproveitei e atualizei seguindo algo parecido com a linha de raciocínio do @dougaraujos 


**Obs:** Por questões de pesquisa vou deixar abaixo como fiz:

1 - Deixei a `currentTrack` no reducer e adicionei o estado do player :
```js
export default (state = INITIAL_STATE, action) => {
  switch (action.type) {
    case 'CHANGE_TRACK':
      return { ...state, data: action.payload }
    case 'PLAY_CURRENT_TRACK':
      return { ...state, playing: true }
    case 'PAUSE_CURRENT_TRACK':
      return { ...state, playing: false }
    default:
      return state
  }
}

```
2 - Passei o objeto audio para o componente principal do player:
```js
class WebPlayer extends Component {
  constructor(props) {
    super(props)
    this.audio = new Audio()
    this.updateCurrentAudio = this.updateCurrentAudio.bind(this)
  }

  updateCurrentAudio() {
    const { currentTrack } = this.props
    if (currentTrack.playing && currentTrack.data !== null) {
      this.audio.src = currentTrack.data.download_url
      this.audio.play()
    } else if (!currentTrack.playing && currentTrack.data !== null) {
      this.audio.pause()
    }
  }

  render() {
    this.updateCurrentAudio()
  ...
```

3 - Dai é só evoluir o estado usando as actions.
```js
export const playTrack = () => ({
  type: 'PLAY_CURRENT_TRACK',
})
```
