### ISSUE TITLE
Lembrando como se fosse ontem.

### ISSUE THREAD

**Issue by nazarepiedady** [frontendbr/forum#1175]
Em poucas palavras partilhe as suas experiências no mundo desenvolvimento front-end, principalmente as mais constragedoras afim de alertar os que estão entrando neste mundo.

**Comment by didiraja** [comment]
- Sempre use GIT, eventualmente você se arrepende de não ter usado
- As vezes é melhor reiniciar a etapa do que ficar eternamente preso num problema que voce não consegue resolver

**Comment by kavalcante** [comment]
- Refatore antes que vire um monstro
- Não construa uma bazuca para matar uma formiga, espere ela crescer e virar um elefante, para ai sim, cogitar uma bazuca
- Sempre em movimento, nunca se acomode com uma tecnologia/stack.

**Comment by kazzkiq** [comment]
- Indentação bem feita é antídoto de bugs. Sempre indente seu código;
- Sério. Indentação é importante. **Indente!**;
- Faça sempre versionamento de código (nada de `meu-site-v5-FINAL.zip`);
- Sempre confira se salvou o arquivo no editor antes de pedir ajuda porque não está funcionando;
- O console é seu amigo. Use-o antes de pedir ajuda "porque deu erro";
- E falando em pedir ajuda, sempre tente investigar o erro ao máximo antes de perguntar. Além de mostrar que você tentou resolver por conta própria, também facilita pra contextualizar em que ponto você já chegou e o que já foi tentado;
- Tente manter um código padronizado. Se começou dando nome de métodos em inglês e camelCase, continue seguindo essa linha em todo o projeto;
- Padronize também os commits. Seja descritivo, mas sem ser redundante. Se começou escrevendo inglês, continue em inglês, etc.
- Evite usar IDs no CSS. **Mesmo que você só vá utilizar esse estilo uma vez** (você provavelmente vai precisar sim reusar ao longo do projeto);
- Jamais use inline styles, a não ser que você tenha um motivo muito bom para tal (e mesmo assim, ele provavelmente não justifica o uso);
- Jamais tente consertar um layout com `float: left` usando margin para tirar um elemento de cima do outro, (dessa eu tenho vergonha até hoje);
- Aprenda Flexbox;
- Aprenda JavaScript (e não algum framework do momento);

**Comment by klarkc** [comment]
Se você está se sentindo bem acomodado, cuidado, isso é sinal de perigo!

**Comment by dougaraujos** [comment]
- NUNCA escreva rascunho de conversas/emails em comentários do código. Você pode acabar fazendo um commit de coisas indesejáveis (como sua pretensão salarial para outra vaga (pois é já fiz isso)).
