### ISSUE TITLE
Iniciante no React - webpack

### ISSUE THREAD

**Issue by alexandreramosdev** [frontendbr/forum#1176]
## Olá devs!

Minha principal duvida é na organização das pastas em um pequeno projeto em React ou webpack!  Já pesquisei bastante sobre o assunto mas exitem muitos modelos/padrões para seguir!  Como vocês começaram a organizar as pasta dos seus projeto no inicio das suas carreiras?

**Comment by edmolima** [comment]
@AlexandreRStos nesse caso não é o react que vai determinar como você vai organizar. Vai depender da tua arquitetura. Então estudar arquitetura e saber o que o modelo resolve é uma ótima forma de definir.

Se o projeto é pequeno e tô trabalhando só com react eu crio uma única pasta "src/" e faço tudo ali. Em algum momento tenho que lidar com serviços de chamadas ajax ai começo a separar.

Sempre pensando em componentes puros e caso precise reaproveitar algo eu penso sempre em composição usando compose.

Como você bem viu existem N formas de organizar seu projeto. Nenhuma delas é unanimidade, porque o modelo depende muito do que tu tá resolvendo.

Se você realmente tá aprendendo react foque em todos os conceitos da lib e lembre-se que parece muito um lego, tudo pode e deve "compor". Se você pensar em SOLID e trouxer conceitos de DDD fácil será sua vida pra mudar a arquitetura em qualquer momento.

**Comment by dougaraujos** [comment]
Dá uma olhada nessa thread: https://github.com/frontendbr/forum/issues/726

**Comment by AlexandreRStos** [comment]
@edmolima show!

**Comment by AlexandreRStos** [comment]
@dougaraujos dei uma olhada legal as estruturas mas acho elas com muitas informações para eu. Pois realmente sou muito iniciante no front-End, so tenho alguns projetos pessoais , e ainda não estou trabalhando em nenhuma agencia ou frella!  Vou estudar como nosso amigo @edmolima  descreveu.

**Comment by vitocaio** [comment]
Recomendo fazer cursos no Udemy, tem tudo que precisa la.

**Comment by LFeh** [comment]
@AlexandreRStos De fato organizar pastas é uma coisa que demoramos muito tempo para chegar em uma solução confortável.

Atualmente considero que trabalhar com menos pastas é melhor, mas já tive fases de separar muito as coisas. 

E isso vai muito do time e do projeto que está trabalhando também.

**Comment by AlexandreRStos** [comment]
@LFeh bacana !  minha duvida é por causa que muito novo no front-end  e como estudo sozinho muitas vezes fico sem um norte!  Ha um mes começai a estudar Javascript  e esta semana comecei a fazer alguns testes com react e alguns com webpack!  

Pois o mercado de trabalho pede muito esta habilidade! Como o react é uma lib e pode ser usada de muitas maneira não deixa claro como organizar as pastas !   
Mas por enquanto  em meus testes e estudo uso o minimo possível de pastas praticamente somente a pasta ./src/components !  

valew

**Comment by dougaraujos** [comment]
@AlexandreRStos Eu entendo sua dor. Particularmente, organização e arquitetura me consomem muito sempre que vou iniciar qualquer coisa que não estou habituado.

Pra amenizar isso, procuro aplicar [YAGNI](https://martinfowler.com/bliki/Yagni.html)
como filosofia (de vida, inclusive). No começo, parece que você está fazendo as coisas de maneira simplória e causa um desconforto. Depois que você acostuma, aumenta muito a produtividade e ajuda a poupar energias desnecessárias.

**Comment by AlexandreRStos** [comment]
@dougaraujos Obrigado pela dica estarei estudando sobre e talvez implementando esta filosofia!

**Comment by AlexandreRStos** [comment]
@dougaraujos @LFeh @vitocaio @edmolima Obrigado a todos !  Foi muito esclarecedor e me deu um norte bem claro para meus próximos estudos !  Para eu iniciar nesta carreira da melhor forma possível :smile:
