### ISSUE TITLE
Ionic ou React?

### ISSUE THREAD

**Issue by romulo2735** [frontendbr/forum#1179]
Pessoal quero entrar no mundo mobile, e vejo que IONIC e REACT são as mais badaladas do mercado, antes disso estava aprendendo PHONE GAP + CORDOVA, e agora estou meio perdido, Qual metodo de mobile hibrido seguir? Ionic? React? os dois ou só um deles? Valeu.

**Comment by kivervinicius** [comment]
React Native, ionic utiliza webview (cordova) e é bem mais lento.

**Comment by LFeh** [comment]
Acho que além de performance, depende até mesmo das suas skills ou da equipe, Ionic usa Angular + TypeScript por debaixo dos panos, se tem mais facilidade com isso vai em frente...

**Comment by jeftarmascarenhas** [comment]
Simples, se você está apenas querendo estudar e já tem alguma experiência com angular o entendimento do Ionic é mais rápido, se tem conhecimento do React o entendimento do React Native é mais rápido.

Se você tem a intenção de estudar pensando no mercado de trabalho, freelas... O React Nativo neste momento seria a melhor escolha na minha opinião.

**Comment by grsabreu** [comment]
> Caso sua aplicação não utilizar muitos recursos nativos do celular, e precisa fazer um projeto em um curto tempo, utilize Ionic.
Não concordo com essa afirmação.

Acho o custo de começar um projeto com React Native muito baixo, mais baixo até do que lidar com Ionic. Pode estar enviesado pq uso React todo dia, mas depois que usei RN pela primeira vez depois de sofrer muito com Ionic a diferença de experiência pra melhor foi imediata.

**Comment by romulosousa27** [comment]
Valeu Pessoal!

**Comment by rickslayer** [comment]
Estou com a mesma dúvida e acabei achando um artigo (em inglês) com explicações bem detalhadas das duas ferramentas.
https://www.codementor.io/fmcorz/react-native-vs-ionic-du1087rsw
