### ISSUE TITLE
Disable do click do Fancybox 3 do background

### ISSUE THREAD

**Issue by grodrigues** [frontendbr/forum#1183]
Como faço para desabilitar o click do Fancybox 3 no background para não fechar a o modal  ?

**Comment by felipeorlando** [comment]
Opa, não conhecia a ferramenta mas procurei na doc pra ti:

https://fancyapps.com/fancybox/3/docs/#options

No objeto de opções na hora de inicializar a lib, você passa a opção `clickOutside` com o valor `false`.

Exemplo:

```js
$('.slide').fancybox({
  clickOutside: false
});
```

**Comment by grodrigues** [comment]
Muito Obrigado @felipeorlando
