### ISSUE TITLE
bower ENOENT No bower.json present

### ISSUE THREAD

**Issue by almleoalmeida** [frontendbr/forum#1189]
Falaê

Estava instalando o MEAN na minha máquina e não consegui executar o comando **bower install** pois ele apresenta o erro **bower ENOENT No bower.json present**. A recomendação é que eu migre para o Yarn, no entanto não sei fazer isso.

**Comment by LFeh** [comment]
Na estrutura desse projeto tem o arquivo `bower.json`?

**Comment by almleoalmeida** [comment]
tem sim

**Comment by LFeh** [comment]
Bower está instalado?
