### ISSUE TITLE
Verificar se thunk emitiu action correta durante requisição assíncrona

### ISSUE THREAD

**Issue by matheusrod92** [frontendbr/forum#1190]
Pessoal, estou com uma duvida em relação ao Formik e ao Redux! Eu possuo um formulário do tipo wizard (aquele com vários passos) com apenas um botão chamado próximo e este botão é responsável por submeter o formulário e enviar o usuário para o próximo passo. Uma vez que o usuário clica no botão próximo é chamada a função `handleSubmit` do HOC `withFormik` do Formik, dentro desse handle submit eu executo um thunk para persistir o dado no back-end e então gostaria que após isso ele verificasse se o dado foi persistido com a action SUCCESS que é emitida dentro do meu thunk. Isso é possível?

FORM:
```
@withFormik({
	handleSubmit: (values, {props, isSubmitting}) => {
		//chamo o thunk para enviar os dados ao servidor
		this.props.finishStep(values);

		//AQUI QUE É A MINHA DUVIDA
		//Como posso fazer um condicional aqui embaixo para
		//verificar se a action sucess foi emitida ou não
		//para chamar o metodo this.gotToNextStep()
	}
})
<componente de formulário />
```

DUCK:
```
const REQUEST = 'REQUEST';
const SUCCESS = 'SUCCESS';
const FAILURE = 'FAILURE';

//reducer

//...actions

//thunk
export function finishStep() {
  return dispatch => {
    dispatch(requestAction());
    fetch(url, options)
      .then(response => {
        if(!response.ok) {
          if(response.status >= 500)
            throw new Error('Error 500');
          if(response.status == 403)
            history.push('/')
          return Promise.reject(dispatch(failureAction(response.statusText)));
        }
        return response;
      })
      .then(response => response.json().then(body => body))
      .then(body => dispatch(successAction(body.enrollment)))
  }
}

```

**Comment by fdaciuk** [comment]
@matheusrod92 você pode fazer a função `finishStep` retornar o `fetch` que está sendo feito. Isso vai fazer com que ela retorne uma Promise, que você consegue checar que resolveu usando o `.then` =)

**Comment by fdaciuk** [comment]
Outro ponto (nada a ver com a dúvida): não faça isso:

```js
throw new Error('Error 500');
```

Você, com certeza, não quer quebrar a aplicação dessa forma! Crie uma action que dispara um erro e mostra uma mensagem amigável ao usuário se acontecer um erro desse tipo.

Se esse `throw` disparar, o usuário nem vai saber o que aconteceu, e não vai ter feedback nenhum.

**Comment by matheusrod92** [comment]
@fdaciuk só pra me justificar hahahah, esse throw eu to utilizando pra testar o Error Boundary.. Se você tiver algum exemplo melhor aí pra me passar seria do caralho!

**Comment by fdaciuk** [comment]
Saquei! Nesse caso, se funciona certinho, não tem problema =)
O meu ponto foi apenas para o caso de cair no erro, mas o usuário não ter feedback =)

**Comment by matheusrod92** [comment]
funciona "certinho" hahahaha
vou dar uma  testada no `finishStep` retornando o fetch agora e qualquer coisa te chamo aqui, valeu @fdaciuk

**Comment by LFeh** [comment]
@matheusrod92 Quando rolar avisa nóis ;)

**Comment by fdaciuk** [comment]
Pode deixar a issue aberta @matheusrod92! Assim, se outras pessoas tiverem a mesma dúvida, fica mais fácil de achar =)
