### ISSUE TITLE
[Angular 6] Reutilização de componentes

### ISSUE THREAD

**Issue by thiagofrancisquete** [frontendbr/forum#1197]
Boa tarde galera, tenho duas duvidas _"de iniciante"_

Eu tenho o seguinte card
```Html
<div class="card">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <h2 class="plano">R$ <span class="valor">valor</span></h2>
      <p class="card-text">texto descritivo</p>
      <a href="#" class="btn btn-principal">Go somewhere</a>
    </div>
  </div>
```

Eu repito ele na _section x_ e _section y_, de 4 cards cada, só as informações que o preenchem que mudam. Esses dados no caso o _.card-title_, _.plano_ e o _.card-text_ mudam conforme o json. Então...

1. Como reutilizar esse componente? Me peguei codando e estilizando a _section x_, mas percebi que teria que copiar e colar o mesmo codigo e alterar os dados, não creio que isso seja uma boa prática :grimacing:

2. Como pegar esses dados do .json? dou um _import { arquivo } from 'localdoarquivo/arquivo.json;_ e uso como um array de objetos normalmente?

Desde ja valeu pela ajuda galera :blush:

**Comment by matheusrod92** [comment]
Fala @thiagofrancisquete vou responder suas perguntas aqui abaixo fora de ordem!


Sim, é possivel importar o `.json` da maneira que você citou mas precisamos adicionar uma declaração de módulos para que o typescript entenda a importação! Uma maneira (que não necessariamente é a correta) é criar um arquivo na sua pasta `app/` chamado `json-typings.d.ts` e adicionar este código abaixo nele:
```
declare module "*.json" {
  const value: any;
  export default value;
}
```
_(caso o servidor esteja aberto, reinicie o mesmo)_ 

Após adicionar esse arquivo você poderá importar o arquivo utilizando a seguinte notação:
`import * as NomeDaVariavel from './caminho/do/arquivo.json';`
e é só utilizar a variável `NomeDaVariavel` normalmente.

Para passar propriedades de componente pai para filho você consegue fazer utilizando input binding. Segue exemplo abaixo:

**Componente-Pai.html:**
```
<div *ngFor="let card of cards">
  <app-child [card]="card"></app-child>
</div>
```
**Componente-Pai.ts:**
```
import { Component } from '@angular/core';
import * as cardsJSON from './cards.json';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  cards = cardsJSON;
}
```

**Componente-filho.html:**
```
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{card.title}}</h5>
    <h2 class="plano">R$ <span class="valor">{{card.value}}</span></h2>
    <p class="card-text">{{card.description}}</p>
    <a href="#" class="btn btn-principal">{{card.link}}</a>
  </div>
</div>
```

**Componente-filho.ts:**
```
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-child',
  templateUrl: './child.component.html',
  styleUrls: ['./child.component.css']
})
export class ChildComponent implements OnInit {
  @Input() card: object;
}
```

Não sei se essa é a melhor maneira de se fazer mas acredito que pode te ajudar no seu caso!

**Comment by thiagofrancisquete** [comment]
Show! Muito obrigado @matheusrod92, vou seguir suas dicas e volto depois (provavelmente amanhã) com o feedback.

**Comment by thiagofrancisquete** [comment]
@matheusrod92 fiquei com algumas duvidas na hora da importação. :disappointed: 

_import * as NomeDaVariavel from './caminho/do/arquivo.json'_
eu assumi que _NomeDaVariavel_ seja o nome do meu arquivo json. Ok. Mas onde exatamente eu importo isso? 

_import * as cardsJSON from './cards.json';_
cardsJSON é o meu json com os dados certo?
eu entendi a ideia mas nao consegui executa-la :grimacing:

**Comment by matheusrod92** [comment]
Exatamente @thiagofrancisquete , você vai chamar o seu json sempre no componente pai que é o responsável de passar as informações para o componente filho (no seu caso, você vai importar no componente que chama o seu componente card)!

**Comment by thiagofrancisquete** [comment]
@matheusrod92 mano, deu tudo certo do jeitinho q v falou, problema tava só pra me achar nos arrays, valeu brigadão

**Comment by matheusrod92** [comment]
Animal @thiagofrancisquete , que bom que rolou não sou a melhor pessoa em angular hahaha.. Mas essa prática de passar informações de componente pai para filho é bem comum no React (chamamos de props), não sei se você já experimentou a biblioteca mas vale a pena também dependendo do caso! Depois da uma olhadinha.
