### ISSUE TITLE
#OpenDesign: Olá pessoal. Estamos trabalhando numa plataforma para suporte ao design de soluções tecnológicas (ou não), a plataforma OpenDesing. O foco da ferramenta é o desenvolvimento de soluções tecnológicas. Publiquei no forum open para pedir ajuda a desenvolvedores, no entanto, gostaria de ter um feedback de vocês que já estão na comunidade para saber se conhecem alguma ferramenta que de suporte ao design de produtos e da forma como é o opensource também possa ser compartilhada, estendida e ou outros possam colaborar com o design de solução? Aguardo.

### ISSUE THREAD

**Issue by jvander** [frontendbr/forum#1200]
Olá! Antes de criar essa issue, algumas dicas:

### Pesquise no fórum
Será que a issue que você vai criar já não foi criada e/ou até respondida?

1. Utilize a função de busca no [topo desse repositório](https://github.com/frontendbr/forum/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) (certifique-se de não estar em um fork)
2. Pesquise assuntos próximos, talvez sua dúvida possa ter sido respondida em alguma issue parecida

### Código de Conduta
Como qualquer grupo de discussões, existem algumas regras que devem ser seguidas para proporcionar uma melhor experiência à todos.

* Respeite para ser respeitado. Não escreva algo que possa ofender alguém. Reflita se o texto não é agressivo/mal educado antes de enviar.
* Mantenha as críticas nas idéias e não nas pessoas.
* Não será permitido qualquer tipo de assédio ou discriminação relacionados a características ou escolhas pessoais, bem como bullying, sexismo, racismo ou qualquer outro tipo de ação que possa proporcionar constrangimento aos outros participantes.
* Comporte-se profissionalmente. Os participantes que violarem tais regras serão convidados a se retirar ou banidos dada a gravidade de suas ações.

### Outros pontos
* Escreva o português de forma correta e bem pontuado.
* Evite sair do escopo inicial da issue. Caso necessário, crie uma nova issue e mencione o número da issue.
* Se precisar de ajuda em um código, forneça trechos, [Gists](https://gist.github.com/) (recomendamos [Codepen](https://codepen.io/) pela facilidade de visualização), e lembre-se, ninguém tem a obrigação de resolver seu problema.
* Não seja um monólogo que só fala de si. Interaja com as respostas, cite pessoas, gere uma discussão saudável e construtiva. Afinal, quanto mais informações, mais rico nosso ambiente será e ajudará mais pessoas.

**Comment by jvander** [comment]
Olá pessoal. Estamos trabalhando numa plataforma para suporte ao design de soluções tecnológicas (ou não), a plataforma OpenDesing. O foco da ferramenta é o desenvolvimento de soluções tecnológicas. Publiquei no forum open para pedir ajuda a desenvolvedores, no entanto, gostaria de ter um feedback de vocês que já estão na comunidade para saber se conhecem alguma ferramenta que de suporte ao design de produtos e da forma como é o opensource também possa ser compartilhada, estendida e ou outros possam colaborar com o design de solução? Aguardo.

**Comment by dtfialho** [comment]
Juro que perdi um tempo tentando entender
 :|
@jvander edita aí, e deixa o título com só OpenDesign ou algo mais curto, acho que você colocou a descrição da issue no título.

**Comment by LFeh** [comment]
Carario...

**Comment by LFeh** [comment]
Bom, já foi criado aqui, melhor fechar, hahaha.

https://github.com/frontendbr/open-source/issues/64
