### ISSUE TITLE
Portfolio em inglês ou português  ?

### ISSUE THREAD

**Issue by ViniciusGularte** [frontendbr/forum#1201]
Fala pessoal, 

uma coisa que venho pensando a tempos, devo migrar todo meu portfólio  para linguá inglesa ? ou manter no pt-br ? Li alguns artigos que é mais bem visto um portfólio totalmente em inglês, outros que depende..

Alguns projetos e artigos que estou desenvolvendo, eu queria um alcance maior , porém outros são especificamente voltado pro pessoal br, não sei se ficaria legal, algumas coisas em inglês e outras em pt-br .. 

Como vocês organizam  seus portfólios e projetos ? Vocês definem um publico alvo ou definiram uma linguagem padrão para todos ?

Sobre meu foco no momento, eu moro no interior do Rio Grande do Sul, e  estou juntando dinheiro pra   me mudar pra uma cidade grande ( São Paulo, Porto Alegre...), então ainda não estou focando no mercado internacional(Mas sempre aberto a oportunidades :smile: ).

**Comment by leandrocunha** [comment]
O mercado fora do Brasil está bem aquecido, se sua intenção é atingir o mercado fora, faça em inglês. O ideal seria bilingue.

**Comment by LFeh** [comment]
Como geralmente o ideal é não adicionar muitos textos no portfolio, acho uma boa ser em inglês. Meio que já tem potencial de atingir qualquer pessoa no mundo.

**Comment by phenriqueleao** [comment]
Como o @leandrocunha disse, acho interessante ser bilíngue, já que você deseja atingir os dois públicos. Um exemplo que acho muito legal é o do @rubenmarcus, [aqui](http://www.rubenmarcus.com/)

**Comment by diessica** [comment]
Tecnicamente, nada te impede de fazer os dois! Se ainda está começando sua carreira no Brasil, é legal focar no português também. Como é importante saber inglês de qualquer forma, você pode ir trabalhando em uma versão em inglês.

**Comment by nazarepiedady** [comment]
Faça um portifolio que possua um script de geolocalização e mude o idioma do seu portifolio segundo o local de acesso, se for um pais lusofono é português se não for é inglês.

**Comment by ViniciusGularte** [comment]
Obrigado a todas colaborações, como sempre esse fórum está recheado de pessoas incríveis :heart: .

Segui algumas dicas e estou refatorando alguns projetos meus para ter o famoso botão PT/EN, e também ando escrevendo alguns artigos em inglês, @victorkurauchi não conhecia esse, achei bem legal e já recomendei pra uma galera que tava apanhando pra criar um bom currículo aqui na região.
