### ISSUE TITLE
[Angular 6] Rotas dinâmicas e default

### ISSUE THREAD

**Issue by thiagofrancisquete** [frontendbr/forum#1203]
Galera eu dnv aqui haha

surgiuram alguns problemas pra mim hoje no estágio e não faco a menor ideia de como resolver ou o que/como procurar pra resolver

Eu tenho que criar rotas pra minha aplicação dinamicamente conforme recebo os dados do json, cada chave é uma rota. Com a ajuda de um colega consegui criar uma funcao que faz isso

*app.routing.ts*
```Typescript
const APP_ROUTES: Routes = getScreens();

export function getScreens() {

let cards = cardsJSON;
let keyss = Object.keys(cards);

let iterador: Routes = [];

keyss.forEach(function (chave) {
  iterador.push({
    path:  chave,
    component : AppComponent
  });
});

  return iterador;
}


export const routing: ModuleWithProviders = RouterModule.forRoot(APP_ROUTES);
```
e pego o valor da url assim no componente:

```Javascript
const url = window.location.pathname.substring(1);
``` 

até ai tudo certo, o conteudo da aplicação mudava conforme a rota e show, só que na hora de dar o ng build --prod eu recebo esse erro:

```
Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'getScreens' was called in 'routing'
    'routing' calls 'getScreens'.
```

Não achei nada na net que desse pra me ajudar a resolver a questão desse erro, algumas pessoas falaram pra remover o node_modules, outras falaram que era problema de caminho na importação do _tsconfig_ mas nada resolveu. Alguém saberia me ajudar a resolver esse erro do build --prod ou a gerar essas rotas dinamicas de uma outra maneira? 

---------------------------------------------------------------------------------------------------------------------------

Quanto a questão da rota estática, é que essa função getScreens só cria rotas dinamicas, então o conteudo da rota default fica vazio. *Hoje* nao existe o componente pra essa rota default, mas segunda feira existirá, então como eu resolveria a questão do app-root? 

hj a configuracao esta assim
``` html
<div>
<app-header></app-header>
<app-section1></app-section1>
<app-section2></app-section1>
<app-section3></app-section1>
<app-footer></app-footer>
</div>
```
mas esse é o conteudo da *http://rota/id*, como eu faria pra resolver essa questão quando o usuario acessar *http://rota/* e só aparecer o conteudo desse componente?

não sei se consegui me expressar muito bem, é a primeira aplicação que desenvolvo então to meio perdido nessa parte de rotas :grimacing: :disappointed:

**Comment by guilhermejcgois** [comment]
Oi Thiago, tem uma extensa discussão sobre um problema aparentemente parecido com o seu, essa resposta na thread é uma possível [solução](https://github.com/angular/angular/issues/23609#issuecomment-386876693). Espero que ajude! Não sei se com Angular 6 já é possível ter rotas dinâmicas, fiz algumas tentativas a um tempo atrás com a versão 4 mas não consegui... ;s

**Comment by thiagofrancisquete** [comment]
vou dar uma olhada @guilhermejcgois 

por enquanto nao achei uma solução pras rotas dinamicas...
