### ISSUE TITLE
Desenvolvedores do Governo

### ISSUE THREAD

**Issue by jampinha** [frontendbr/forum#1205]
### Comunidade de Desenvolvedores do Governo
Olá pessoal, tudo bom?
Então, eu atualmente trabalho como desenvolvedor para uma instituição pública e senti a necessidade de termos uma comunidade focada em desenvolvedores que atuam em órgãos públicos e afins.
Pensando nisso, me reuni com alguns devs em grupos do telegram para pensar ações com o objetivo de engajar a comunidade de devs à formar um ecossistema de troca de conhecimento técnico entre desenvolvedores do governo.

Se você trabalha em alguma instituição pública e deseja colaborar com esse projeto, informe o seu usuário do telegram que nós iremos adicioná-lo ao grupo DevsGovBR.

Sua participação será fundamental para que possamos mudar a cultura trivial dos ambientes de desenvolvimento do governo a fim de fomentar a inovação nos setores públicos do país.

Desde já, agradeço a todos pelo apoio!

**Comment by mariodkr** [comment]
@didiraja , pode ser... é que, existem algumas observações a serem consideradas, com relação a sigilo de informações sensíveis e afins... seria bom fazer um brainstorm com os profissionais da área pra ver se um repositório aqui no github atenderia bem a proposta sem ferir nenhum princípio ético, etc. Por isso a criação do grupo no telegram. É mais para promover a troca de ideias para a comunidade.

De qualquer forma, segue o link do grupo, para os interessados: https://t.me/joinchat/HFh0CAuJJyvSfm1IzbDJJw

Obrigado pela colaboração, @didiraja 
Toda sugestão será bem vinda.

**Comment by grsabreu** [comment]
Essa é uma ideia muito boa!
Meu sonho era ver coisas do governo virando open-source e usando a própria comunidade como auditoria e correção de falhas e etc. Ia acabar com muita conspiração por aí.

**Comment by mariodkr** [comment]
@grsabreu , também parece ser uma ótima plataforma para estabelecer a comunidade.
Cola lá no grupo e sugere pro pessoal...

**Comment by LuanFreitas** [comment]
Baita iniciativa fera, parabéns!
Nunca trabalhei pro Gov mas a gente que tá de fora escuta muito sobre as coisas triviais que acontecem e em alguns serviços até percebemos isso. Tomara que dê muito certo!

**Comment by daniloarodrigues** [comment]
Boa iniciativa. @daniloarodrigues
