### ISSUE TITLE
[Vue.js] Como manter uma variável global ao atualizar a página?

### ISSUE THREAD

**Issue by kvnol** [frontendbr/forum#1211]
e aí!

> olha, não sei se essa é a melhor forma de se fazer isso porque sou um mero recortador de layout se aventurando no Vue, mas deem sugestões (kkk)

Pessoal, estou trabalhando com Vue no Laravel, consumindo uma API com Axios, onde envio o CPF através do input numa tela de login. Se a API encontra o CPF (status 200), ela redireciona para a tela principal. Só que, ao atualizar a página, eu perco esse CPF que eu precisaria para renderizar as informações do cliente.

Eu teria que usar Vuex? O que seria o melhor a fazer?

**Comment by caioincau** [comment]
Você pode usar o Vuex, ou usar o famoso "EventHub" .

https://medium.com/vuejobs/create-a-global-event-bus-in-vue-js-838a5d9ab03a

Dependendo do tamanho da aplicação, não vai precisar de Vuex.

**Comment by luizbills** [comment]
Você pode passar o CPF como argumento da URL (https://seusite.com/pagina?cpf=12121212122) ou gravar ele no navegador (localstorage, cookies, etc). Assim quando a outra página carregar você vai ter meios para recuperar esse CPF.

**Comment by kvnol** [comment]
@caioincau a aplicação é bem pequena, três views apenas. Tô tentando implementar esse $eventHub.

**Comment by kvnol** [comment]
@luizbills Tinha pensado pela url, mas não sei se isso é gambiarra.

**Comment by diemoritat** [comment]
Não sei se é a melhor opção, mas se você precisa ter a possibilidade de recuperar esse CPF depois, eu acho que optaria pelo localStorage. E quando você inicializa a app, verifica se já existe um CPF salvo no localStorage, se não tiver, inicializa zerado. 
Eu fiz algo do tipo em um projetinho que tava usando pra testar umas coisas e usei vuex + localStorage, se quiser dar uma olhada: 
https://github.com/diemoritat/doit/blob/master/src/main.js (aqui, no `beforeCreate` eu disparo a mutation de `initialiseStorage`)
https://github.com/diemoritat/doit/blob/master/src/store.js (aqui tem a mutation `initialiseStorage`, que verifica se a store tá salva no `localStorage` e parte daí)

**Comment by luizbills** [comment]
@kvnol não é gambiarra. Se você não quer que o CPF apareça na URL é só passar pelo localstorage então ou por cookie, assim você pode até acessar pelo backend.
Até porque o Vue é um framework frontend, para você fazer o vue acessar um conteudo depois que a pagina atualizou, você tem que deixar esse conteudo disponível em algum lugar, seja no storage, seja nos cookies, na url, etc...

**Comment by didiraja** [comment]
Dúvida: passar essas informações  via url (get) não pode ser considerado falha de segurança?

**Comment by luizbills** [comment]
@didiraja se sua entrada não favorecer acesso ou gravação de dados no backend, então não será um falha de segurança. Nesse caso será apenas uma página que é modificada dependendo da entrada na url.

**Comment by kivervinicius** [comment]
@kvnol invés do localStorage eu utilizaria o sessionStorage, após o término da aba vc não precisa se preocupar em limpar, ou via url tbm como o @luizbills disse, é uma forma bem limpa.

**Comment by LFeh** [comment]
@kvnol Resolveu?

**Comment by kvnol** [comment]
Refatorei o código passando o JSON de retorno direto para o sessionStorage, aí não preciso ficar fazendo Ajax em todos os componentes para retornar o `response.data`, como estava sendo com o CPF/CNPJ como parâmetro de URL.

Tá rodando lindo. Valeu, galera! :heart:
