### ISSUE TITLE
Como solicitar palestras?

### ISSUE THREAD

**Issue by MatCunha** [frontendbr/forum#1217]
Primeiramente, como vocês estão? Tudo bem? 

Me desculpem se estou abrindo esse questionamento em um local incorreto, não sei ao certo. 

É o seguinte, eu sou de São Paulo e estou cursando Design de Mídias Digitais na Fatec Barueri (curso bem louco que mistura design com programação web e marketing digital), vamos ter uma semana da tecnologia e estou procurando palestrantes que possam falar sobre design web, ui/ux, front e back end e também sobre como está nosso mercado. 

Sei que bastante gente aqui da comunidade faz palestras e seria show se pudessem dar uma ajuda pra gente lá no evento, sempre é bom! hahaha

Além disso o evento é aberto pra comunidade e quem quiser ir pra conhecer tá convidado.

**Comment by raffaeldantass** [comment]
Opa, tudo em ordem cara? 

Cara eu organizo o Meetup do HTML SP aqui em São Paulo e conheço bastante gente que palestra sobre temas diversos, porém com mais foco em front-end 

Eu mesmo palestro as vezes (inclusive na semana de tecnologia de Jundiaí) hahahaha

Se quiser posso te ajudar nessa, até pq eu me formei na FATEC Jundiaí e sempre tivemos a semana de tecnologia por lá também, acho bem legal e importante hahaha

Quando vai ser? 
Valeu!

**Comment by elvisdetona** [comment]
Opa, beleza?
Meu... tem muita gente querendo palestrar e muita gente procurando palestrantes e no seu caso, tem algumas formas de vc encontrar gente.
Eu indico o https://www.codamos.club/pessoas (tem uma lista de gente querendo palestrar) ou abre um "formulário do google", dizendo do "evento" que vai acontecer e pede para as pessoas "submeterem palestras" (em eventos de frontend por exemplo, o pessoal faz assim e depois "escolhem/convidam" as pessoas). 

Acho que é o primeiro passo :D 
Boa sorte aí 
E se precisar de ajuda para divulgar o "form", posta ele aqui que com certeza o pessoal ajudará a espalhar :D 
👊

**Comment by LarissaAbreu** [comment]
Fala, @MatCunha beleza?

Eu acredito que haja duas formas de encontrar palestrantes para eventos Formulário de Call for Papers e você entrar em contato direto com a pessoa (caso já tenha em mente alguém em específico que gostaria que desse as palestras).

No caso de escolher achar pessoas através de Call for papers seria bom criar um formulário (do google mesmo) explicando um pouco sobre o evento e falando sobre os temas que gostaria que fossem falados no evento. Aí geralmente as pessoas costumam pedir informações básicas (nome, título da talk, resumo, link das redes sociais, link para uma foto e um e-mail para contato). Aí, feito o formulário é só divulgar e pedir para a galera ajudar a divulgar também hehehe (assim as pessoas vão te enviar as propostas de palestras, você analisa uma por uma e escolhe quais gostou mais e etc).

Caso você queira que uma pessoa específica vá e compartilhe sobre determinado assunto é só entrar em contato com ela por algum lugar (e-mail ou alguma rede social) e fazer o convite. Já aproveitando para passar todas as informações do evento e tals nesse primeiro e-mail mesmo porque assim a pessoa já olha o e-mail e analisa se poderá ir e etc xD

Se precisar de ajuda é gritar 🤓

**Comment by cesarolvr** [comment]
Salve @MatCunha, tranquilo cara?

Tudo isso que a @LarissaAbreu, @raffaeldantass e o @elvisdetona disseram vai te ajudar demais em achar lugares pra compartilhar o que tu sabe.

Fica grudado nas páginas das comunidade no [Twitter](https://twitter.com/ONerdzao) e no Meetup que sempre tem posts anunciando os eventos. No [Nerdzão](https://www.meetup.com/pt-BR/Nerdzao/) mesmo tem VÁRIOS eventos abertos precisando de gente como você pra ir falar!

**Comment by MatCunha** [comment]
Eita, quanta informação! hahaha :D 

@raffaeldantass o evento rola dia 23, 24 e 25/10. 

@elvisdetona muito obrigado pela dica mano, nem conhecia esse local e acho que vai ser muito útil mesmo. 

@LarissaAbreu muito obrigado pela dica de como chamar a pessoa, tava meio perdido nisso também. 

E a todos muito obrigado pelas dicas, eu vou correr atrás disso até segunda-feira e se precisar de ajuda posto mais aqui. Valeu!
