### ISSUE TITLE
Sobre as dependencias do npm 

### ISSUE THREAD

**Issue by felipefialho** [frontendbr/forum#122]
Fala pessoal, beleza?

De fato comecei a utilizar o NPM para gerenciar todas as dependências do projeto, inclusive as que ficavam por conta do bower. Como discutimos nessa issue #17 

Porém surgiu uma questão, estruturei um novo tomando de base o do @willianjusten e no [package.json, adicionei `*` para baixar sempre a ultima versão](https://github.com/LFeh/kratos-boilerplate/blob/master/package.json).

Essa é uma abordagem correta ou tem outra solução mais adequada?

**Comment by vitorabner** [comment]
Eu já usei o latest, não conhecia o * ainda. De acordo com a semantic version do npm: https://docs.npmjs.com/misc/semver#x-ranges-12x-1x-12- o asterisco baixa qualquer versão acima ou igual a 0.0.0 veja: 

Any of X, x, or * may be used to "stand in" for one of the numeric values in the [major, minor, patch] tuple.

'*' := >=0.0.0 (Any version satisfies)
1.x := >=1.0.0 <2.0.0 (Matching major version)
1.2.x := >=1.2.0 <1.3.0 (Matching major and minor versions)

Me corrijam se estiver errado, mas fiz uns testes com o jscs e ambos baixaram a última versão. Dei uma [pesquisada melhor](http://stackoverflow.com/questions/16073603/how-do-i-update-each-dependency-in-package-json-to-the-latest-version) e vi que a diferença é:

latest baixa a última versão estável e * baixa a última versão(estável ou não).

**Comment by kazzkiq** [comment]
Acho que o ideal seria utilizar algum tipo de  *version range* mais específico e ir alterando as versões dos pacotes conforme você achar necessário.

Se você usa um package na versão `1.0.0` mas no seu package.json está como `*`, caso outra pessoa dê um `npm install` e já tenha saído uma outra versão mais nova que quebra o código legado, esta pessoa teria um package com API nova, rodando em um projeto que espera uma API antiga para funcionar.

Neste caso o ideal é sempre usar a mesma versão MAJOR no seu projeto para correr menos riscos de quebra. Exemplo:

```js
{
    babel: "^5.0.0",  // Vai sempre pegar a última versão abaixo 6.0.0
    gulp: "~1.3.1"    // Vai sempre pegar a última versão abaixo de 1.4.0
}
```

**Comment by bernardodiasc** [comment]
Sou da opinião do @kazzkiq, até mesmo pra saber qual a versão que o código usa e funciona. Em caso de pânico, sempre da pra escolher manualmente, e olhar no git por exemplo quando algo mudou no projeto nas versões dos pacotes, mas se for *, não tem como saber.

**Comment by vitorabner** [comment]
Concordo com o @kazzkiq.

**Comment by kazzkiq** [comment]
@bernardodiasc Exatamente. Eu já tive problemas com erros de build porque quando instalei as dependências em outra máquina foi logo depois de ter saído uma versão MAJOR do framework que eu utilizava, o que mudou algumas APIs e quebrou todo o código.

Eu perdi um bom tempo debugando *até o Assembly da máquina* pra depois descobrir que era apenas cagada no versionamento do meu package.json. 😄

**Comment by karlprieb** [comment]
Cuidado com utilizar sempre o latest. Utilizavamos latest em um projeto até o dia em que um package alterou a major version e o output de uma dependencia mudou um pouco. Tivemos alguns problemas. Mantivemos aquele package atualizado e adequamos nosso projeto à aquele output. Depois disso começamos a utilizar range de versões para não termos mais problemas.

**Comment by vitorabner** [comment]
Uma coisa a acrescentar é o: npm install plugin@**latest** --save-dev.
Isso instalará a última versão estável do plugin e automaticamente já coloca um range. 

Exemplo: npm install karma-html2js-preprocessor@latest --save-dev 
No seu json irá ficar: "karma-html2js-preprocessor": "^0.1.0".

O próximo dev que baixar o seu projeto pegará esse range e não o latest. Melhor dos mundos.

**Comment by tcelestino** [comment]
@LFeh, depois conta como está sendo sua experiência. Se está usando o Browserify, Webpack ou apenas o gulp.

**Comment by LFeh** [comment]
E se por exemplo eu quiser atualizar todos os pacotes de uma vez para a versão mais estável, como rodo no npm?

**Comment by karlprieb** [comment]
@LFeh https://www.npmjs.com/package/npm-check-updates

**Comment by kazzkiq** [comment]
@LFeh Infelizmente o npm não oferece uma alternativa pra isso *out-of-the-box*. A solução é usar alternativas como a do @karlprieb

**Comment by karlprieb** [comment]
@kazzkiq O npm oferece sim, mas não é tão boa quando o npm-check-updates. É o npm outdated. Ele te diz se o teu package esta outdated dentro do range que tu setou no packages.json, mas não atualiza o teu packages.json automaticamente. https://docs.npmjs.com/cli/outdated

**Comment by kazzkiq** [comment]
@karlprieb Então, mas ele não atualiza os packages nem o package.json, né? Ele serve só pra dizer se tem alguma versão nova pros packages, correto? (to perguntando mesmo, pq nunca tinha ouvido falar dele hauhaua)

**Comment by karlprieb** [comment]
@kazzkiq sim... ele só diz se tem versão nova :(

**Comment by LFeh** [comment]
Valeu @karlprieb, testei aqui e funciona perfeitamente =D

**Comment by letanure** [comment]
e sobre definir versoes, ja fui obrigado a usar o `npm shrinkwrap` pra fazer um freeze de versões.

no meu caso tive problemas com npm + vagrant que estava se perdendo em versoes

**Comment by yuricamara** [comment]
"recebendo somente fix e minor, que garante correção de alguma falha, mas também garante que não irá quebrar". Eu não aposto nisso não, @willianjusten ! Já li um artigo falando disso e com exemplos negativos. 

Criei um .npmrc com save-exact=true já que eu trabalho como Node tb e não quero ter problemas com minhas dependências.

**Comment by yuricamara** [comment]
E nas devDependencies eu coloco o ^

**Comment by barbier** [comment]
+1 no @willianjusten, inclusive já ouvi de um amigo que nessa de manter o "latest" num projeto Rails, uma gem atualizou e o sistema quebrou. Com ele eu aprendi a sempre escolher a versão das libs que vamos usar.

**Comment by ribeiroevandro** [comment]
Não sei se seria aqui o melhor lugar para comentário... Mas uma coisa que tenho problema recorrente quando tem babel no meu Workflow e quando rodo o Gulp sempre tenho esse retorno no terminal e demora muito pra rodar as tasks...
```
[00:18:26] Failed to load external module babel-register
[00:18:26] Requiring external module babel-core/register
```

**Comment by yuricamara** [comment]
@ribeiroevandro  você instalou o package babel-register né?

A task demora pra rodar quando você usa o babel-preset-es2015
Veja que ele tem uma [lista de plugins](http://babeljs.io/docs/plugins/preset-es2015/)
Então eu uso só os plugins que preciso e não o preset

Exemplo:
```js
//.babelrc
{
  "plugins": [
    "transform-es2015-destructuring",
    "transform-es2015-parameters"
  ]
}
```
Isto aí é pra eu poder usar ES6 no Node 4.
Fica muito mais rápido pro Gulp trabalhar. E outra grande vantagem é que ele só transforma pra ES5 o que você de fato precisa. Ao contrário do preset que de fato, ES6 que é bom vai ser só o que você digitar no editor.
Bom, se você tem que dar suporte pra IE9/IE10 você vai ter que usar Babel pra tudo. hehehe. Mas aí faz uma task separada no gulp pra testes no IE e pra depois mandar pra prod.

Enfim, espero ter te ajudado se é que já não fez isso tudo. hehehehe!
