### ISSUE TITLE
CSS Level 4

### ISSUE THREAD

**Issue by nazarepiedady** [frontendbr/forum#1220]
## CSS LEVEL 4
É talvez esse assunto não seja novo nas comunidades de front-end, mas a uma duvida que paira no ar quanto a adesão a essa nova maneira de escrever as folhas de estilos em cascata, que agora deixou de ser enumerada ou nomeada como antes, e que atualmente está na versão denominada *CSS LEVEL 4*.
.
O CSS LEVEL 4 já está a ser usado atualmente em produção?

**Comment by thismarcoantonio** [comment]
Depende, visto que ele é composto por muitas features. Já vi coisa sendo usada sim, como o seletor `:not` (sei que já tinha no CSS level 3, mas foi melhorado no 4), mas acredito que maior parte das features ainda estão sem suporte.
