### ISSUE TITLE
Imposto de renda e Paypal

### ISSUE THREAD

**Issue by RonaldBolado** [frontendbr/forum#1221]
Olá, vim parar aqui no fórum pelo Google e gostaria de tirar uma dúvida sobre imposto de renda. Eu não sou programador, mas vou começar a trabalhar pela internet e vou receber pelo Paypal algo em torno de 200 dólares todo mês. Não entendo nada sobre imposto de renda e não sei se é esperado que eu declare esse valor ou não, mesmo estando bem abaixo do valor mínimo. São muitas regras e cada hora eu leio algo diferente na internet. Eu sei que é um valor baixo e a pergunta pode ser meio estúpida, mas eu sei que até dividendos de ações por menores que sejam têm que ser declarados, então eu não sei o que concluir.

Como sei se posso receber esse valor sem me preocupar com declarar? Obrigado.

**Comment by luizbills** [comment]
Até onde eu lembro, por lei você só é obrigado a declarar imposto de renda se sua renda anual passar de 28.000 e uns quebrados.

**Comment by RonaldBolado** [comment]
> Até onde eu lembro, por lei você só é obrigado a declarar imposto de renda se sua renda anual passar de 28.000 e uns quebrados.

Não tem uma lei que te obriga a declarar se você mandar o dinheiro que está no Paypal para uma conta bancária?

**Comment by viniciusbarretobr** [comment]
É uma pergunta bem técnica da área contábil. Acredito que seja um valor baixo para se preocupar, mas caso você esteja interessado em estar 100% correto perante as leis tributárias do Brasil, acredito que seria mais seguro você postar esta pergunta em um fórum contábil (https://www.contabeis.com.br/forum/) ou até mesmo no Jusbrasil (https://www.jusbrasil.com.br), para ver se algum advogado tributarista se dispõe a ajudar nesta dúvida.
Receber como empresa talvez envolveria coisa sobre "exportação de serviço" e então complicaria mais, e, só valeria a pena se essa valor recebido fosse multiplicado por 100 ou 1000.

**Comment by LFeh** [comment]
Veja se ajuda #124

**Comment by RonaldBolado** [comment]
Bom, liguei para um escritório de contabilidade, falei com um contador e ele disse que desde que não bata os ~R$28.000,00 anuais, não tenho que declarar nada a ninguém, independente da moeda. Espero que ele esteja correto.

Obrigado a todos.
