### ISSUE TITLE
Migrando para IA 

### ISSUE THREAD

**Issue by silvaMatheus** [frontendbr/forum#1223]
Pessoal alguém esta migrando para a área de IA ou pensa nessa possibilidade ?

**Comment by phsantiago** [comment]
Penso bastante mas é algo para longo prazo. Tenho juntado alguns materiais e estou bem curioso quanto a esse curso https://github.com/Avik-Jain/100-Days-Of-ML-Code

**Comment by didiraja** [comment]
Minhas possibilidades futuro a longo prazo são Data Science, Blockchain e brincar um pouquinho com Arduino em casa.
