### ISSUE TITLE
Custom Elements (Web Components) - em produção

### ISSUE THREAD

**Issue by virginiarcruz** [frontendbr/forum#1224]
Pessoal, 

Recentemente o Github anunciou que [removeu jQuery do Front-end](https://githubengineering.com/removing-jquery-from-github-frontend/) e está utilizando Custom Elements. Apesar de ainda não ter sido implementado para todos os browsers.

Alguém mais tem utilizado Custom Elements ou Web Components de um modo geral, nos projetos em produção? Qual Polyfill, vocês têm utilizado?

**Comment by caioincau** [comment]
Invoco @afonsopacifer  e @larissaabreu

**Comment by klarkc** [comment]
Já brinquei bastante, mas não uso mais tanto, então posso estar desatualizado. Mas usava o webcomponents-lite e o Polymer. Em produção usei uma ou duas vezes. É bem complicado achar uma oportunidade de uso, porque geralmente o time quer algo bem mais fácil e mastigado com o Vue, Angular ou React.

Outro problema que os Web Components ainda possuem é o empacotamento (exigindo que vc use polyfills ou bundlers para empacotar javascript e HTML). Infelizmente ainda não se chegou a um padrão de pacote de web componentes ([veja html imports](https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports)).

**Comment by LarissaAbreu** [comment]
Fala galera, beleza? Então... A gente utiliza Web Components na empresa e é tranquilo. Vou comentar sobre alguns pontos que vi aqui na discussão 😊

- **Sobre polyfill**: A gente não faz os componentes em si com nenhum polyfill. Porque o certo é deixar quem for utilizar os componentes decidir se quer utilizar polyfills na aplicação ou não. Dessa forma, caso eu queira simplesmente utilizar meu componente em um navegador que já suporta eu não carrego nada à toa xD

- **Sobre a questão dos imports**: Para os componentes que fizemos com Polymer 2 utilizamos um loader do webpack. Porém já faz um tempo que não precisa mais de nada pois o Polymer 3 funciona com o ES Modules (tanto que os novos arquivos são .js e não mais .html). Dessa forma não depende mais de webpack ou nada do gênero.

Aqui o suporte de ES Modules atualmente:

![captura de tela 2018-09-26 as 13 56 03](https://user-images.githubusercontent.com/16037749/46095866-f5068a80-c193-11e8-9d21-2ba715cb28b4.png)

- Apenas um detalhe... o Polymer não é um polyfill e sim uma biblioteca que nos ajuda a criar web components xD

Para entender melhor como o Polymer 3 surgiu existe esse artigo aqui que é antigo (pois o Polymer 3 já saiu rs) mas muito bom e explica tudo direitinho https://medium.com/@afonsopacifer/desmistificando-um-futuro-chamado-polymer-3-ae0476cf8c0a

- Sobre empacotar os templates... Web Components resolve com a tag nativa `<template>`
![captura de tela 2018-09-26 as 14 04 48](https://user-images.githubusercontent.com/16037749/46096379-685ccc00-c195-11e8-9b7e-bcda56b12d05.png)

O Polymer 3 usa template literals
![captura de tela 2018-09-26 as 14 05 56](https://user-images.githubusercontent.com/16037749/46096357-59761980-c195-11e8-8004-0340be89f579.png)

- Ps.: O Vue usa a mesma tag `<template>` nativa dentro do Single File Component

**Comment by afonsopacifer** [comment]
Eu ia falar o que a @LarissaAbreu falou.

Complementando: 
Os componentes que usamos na empresa são Open Source, assim como alguns generators (Yeoman) para componentes de polymer 2 e 3:

Está tudo aqui <3
https://github.com/valleweb

PS: Seguindo Atomic Design: Usamos eles como atomos e moleculas, porém compomos nossos organismos e templates com React usando os web components  (afinal é apenas HTML nativo) dentro do JSX, chegando nas single pages apps.

Lembrando que usar web components não influencia na decisão de usar Vue, React, Angular, nada, etc...

**Comment by klarkc** [comment]
Massa bem legal saber q o suporte está bem melhor, a dica do @afonsopacifer é bem legal, deixar os componentes atomicos para web components e usar um framework para fazer as moleculas. Assim a biblioteca de componentes fica livre para ser reutilizada em frameworks diferentes

**Comment by virginiarcruz** [comment]
@afonsopacifer massa a ideia de seguir o Atomic Design e seguir construindo os componentes com o framework.
Minha preocupação ainda está nas versões do IE e do Safari.

**Comment by LFeh** [comment]
@LarissaAbreu e @afonsopacifer mitaram 👏👏 👏

**Comment by yanmagalhaes-ir** [comment]
No local onde trabalho, todos os produtos web utilizam web componentes (utilizamos Polymer 1, então conseguimos dar suporte a todos os browsers, incluindo IE11). Como a @LarissaAbreu e o  @afonsopacifer já falaram, você passa a responsibilidade do uso do Polyfill pra quem esta consumindo o web component, para dar o suporte que você precisa

**Comment by ninetails** [comment]
Aproveitando a thread, por um acaso alguém tem alguma solução pra SSR com web components?

Sei que é a idéia totalmente contrária do Shadow DOM, mas alguém já chegou a fazer alguma solução que seja melhor que num rerender apagar o dom gerado do server e reescrever no shadow?

**Comment by klarkc** [comment]
N sei como q está isso no Polymer, mas tem esse cara aqui q o Google desenvolveu https://github.com/GoogleChrome/rendertron

**Comment by afonsopacifer** [comment]
@ninetails Da para usar (teoricamente) os web components normalmente no SSR, mas se usar um virtual DOM no client ja ajuda bastante no re-render... de qualquer forma no fim das contas quando vc metrifica o render do shadow DOM ele nao pesa tanto o quanto parece :)

**Comment by evertonthepaula** [comment]
Galera! Estou voltando a me atualizar sobre Web Components e aparentemente existe agora uma nova implementação consistente para modules, que acredito pode sobreviver ao tempo, basicamente é uma tag link com rel= "import". Criei um scritpt bem simples para usar HTML Imports/Modules, que demonstra como fazer download: https://github.com/evertonthepaula/MapHtmlImports. Estou brincando com isto atualmente e atualizando minhas anotações sobre o assunto.
