### ISSUE TITLE
Web Accessilbity

### ISSUE THREAD

**Issue by nazarepiedady** [frontendbr/forum#1228]
# Os obectivos desta issue é:
* Enumerar os diversos problemas de acessibilidade que encontramos durante o **Markup**.
* Citar os pontos importantes que os devs iniciantes devem ter muita atenção ao fazer **Markup** no que converge em acessibilidade.
* Recomendar posts, artigos e livros onde é possível aprimorar os conhecimentos acerca desse aspecto importante da web que é a **acessibilidade**.
* Partilhar experiências reais e pessoais sobre o assunto, para alertar os devs iniciantes.

**Comment by luizbills** [comment]
Eu não sou pro em acessibilidade, mas sempre tento lembrar de umas regas:
- um link de *skip to content*;
- `alt` nas imagens
- `title` nos links ou outros elementos que possa ser util
- usar "boas" combinações de cores ([exemplo de ferramenta](https://webaim.org/resources/contrastchecker/))
- não ficar usando tamanho de fontes pequenos (para mim o limite minimo é `14px`)
- não usar fontes muito finas para textos pequenos (`font-weigth` maior ou igual 400 nesses casos)
- Usar texto um pouco maior quando o conteudo tem muito texto (font-size 18px ou maior) e aquele `line-height` generoso (1.5 por exemplo).

Algumas dicas ali são mais voltadas a leitura. Se alguém quiser se aprofundar mais em acessibilidade é bom estudar sobre [ARIA](https://developer.mozilla.org/pt-BR/docs/Web/Accessibility/ARIA).

**Comment by didiraja** [comment]
Isso aí que o @luizbills falou, o macete é ler sobre as WAI-ARIA. Entender como o leitor optico de deficientes visuais, ajuda a escrever seu código com melhor acessibilidade.

**Comment by tarciozemel** [comment]
https://guia-wcag.com/
