### ISSUE TITLE
Recrutamento por Robos

### ISSUE THREAD

**Issue by rubenmarcus** [frontendbr/forum#1231]
Galera voces receberam um e-mail do Ifood recrutando todos devs frontend? Sei que é meio anti-etico isso ,mas o robo, ou e-mail mandou a lista pra todo mundo e eu to lendo o topico de todos devs, inclusive varios aqui, que conheço. 

Porque que as empresas fazem isso? Eu já recebi de RH e Consultorias, vagas pra mesma empresa que eu trabalho, no mesmo cargo!! Esse pessoal não pensa no desrespeito com os devs?

**Comment by luizbills** [comment]
Po ifood não me enviou nada. Acabaram de perder um usuário kkkkkkkkkkk
