### ISSUE TITLE
Sobre receber ordem de pagamento do exterior

### ISSUE THREAD

**Issue by pedrohenri** [frontendbr/forum#124]
Pessoal, sei que vários aqui da comunidade prestam serviço ou são contratados de empresas do exterior. Pela experiência de vocês, qual a melhor forma de receber o pagamento?

Costumava receber via Paypal e esse mês decidi fazer direto pelo Itau já que as taxas eram menores (R$ 100,00 + IOF). Em compensação, para minha surpresa eles converteram o dólar a R$ 3,28 (hoje o dólar comercial está a R$ 3,60) e ainda tenho que enviar documentação para análise!

Pela minha experiência e pelo que pesquisei segue uma comparação entre os dois serviços:

**Paypal**
Taxa sobre valor total em dólares: 6%
Câmbio: cerca de 3,5% abaixo do dólar comercial
Simulação de $ 3000,00 com dólar à R$ 3,60 = R$ 9785,40

**Itau**
IOF: 0,38%
Câmbio: cerca de 9% abaixo do dólar comercial
Taxa fixa: R$ 100,00 
Simulação de $ 3000,00 com dólar à R$ 3,60 = R$ 9690,66

Temos alternativas melhores?

**Comment by viniciusdocanto** [comment]
Caixa Econômica também tem taxa fixa, acho que é a menor, quando eu recebia era uns 50R$ +/-.
Só que todo recebimento infelizmente é muito ruim, você tem que ir na agência assinar um contrato, a não ser que tenha um bom relacionamento com o seu gerente.

**Comment by LFeh** [comment]
Existe um serviço chamado [Xoom](https://www.xoom.com/) que é bem interessante.

**Comment by robsontrevizani** [comment]
Gostei muito do modelo oferecido pela BitWage
<https://www.bitwage.com/>. Talvez
seja a opção mais vantajosa nos dias de hoje e, caso precisasse, seria
minha escolha.
Tem esse vídeo de um brasileiro fazendo um overview/publicidade do produto:
https://youtu.be/0v3Oe7spihs

On Tue, Apr 19, 2016 at 12:23 PM, Felipei Fialho <notifications@github.com>
wrote:

> Existe um serviço chamado Xoom <https://www.xoom.com/> que é bem
> interessante.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/frontendbr/forum/issues/124#issuecomment-211976795>
>



-- 
*Robson Trevizani*
+55 41 8819 0995

Google Certified Professional
<https://www.google.com/partners/#i_profile;idtf=100182646801149025808;>

**Comment by kazzkiq** [comment]
Uma possível alternativa seria o [**BitGold**](https://www.bitgold.com/). **Apenas 1% por transação.**

Ele é uma empresa Canadense que trabalha com pagamentos e recebimentos em ouro. Imagine uma espécie de Banco de Ouro ao invés de dinheiro. Você compra ouro pela cotação atual, e aquilo vira crédito na sua conta, que você pode usar com um cartão internacional (ou pedir a retirada em Ouro puro).

Eu estou estudando a migração para ele a um tempinho já, pelo que eu entendi da plataforma até agora os passos seriam:

1. Criar uma conta;
2. Pedir um cartão internacional;
3. Usar o gateway de pagamento deles para receber o salário das empresas (**1% de taxa**);
4. Usar o cartão internacional para gastar o dinheiro no Brasil e ser feliz. :)

É claro que ao usar o valor aqui no Brasil você vai estar pagando impostos e tudo mais, mas pelo menos vai se livrar das taxas abusivas dos bancos e instituições tradicionais.

Vale a pena dar uma olhada.

**Comment by willycamargo** [comment]
Mais de 1 ano e gostaria de ressuscitar a thread para saber se alguém tem mais alguma dica de serviço ou método para receber pagamentos do exterior

**Comment by pedrohenri** [comment]
Estou usando os serviços da Husky (husky.io) há 3 meses e só tenho elogios. Taxa fixa de 3,5%, o mais competitivo que já experimentei.

**Comment by kazzkiq** [comment]
Pra quem tem perfil mais *early-adopter*, ainda existe a alternativa de receber diretamente em criptomoedas.

Ripple e Litecoin efetuam transações em questão de **segundos** ou **minutos**, respectivamente. E são moedas onde a troca por Real é quase tão simples quanto o próprio Bitcoin.

Sendo assim, o processo seria:

1. Definir com a empresa qual criptomoeda seria usada;
1. Criar uma carteira nesta criptomoeda;
2. Pedir recebimento via esta moeda;
3. Transferir o valor recebido para uma exchange para sacar em reais, trocar com algum usuário **confiável** via p2p, ou ainda usar um cartão de crédito recarregável em criptomoedas para fazer o gasto do valor em reais.

Lembrando que ao usar criptomoedas, toda a parte burocrática de declarar os valores recebidos de fora do país fica por conta das partes envolvidas (tanto a empresa enviando, quanto você recebendo). Então é preciso lembrar que existe esse trabalhinho extra também.

**Comment by doug2k1** [comment]
Não sei se enquadra no mesmo caso, mas para recebimento de ordens de pagamento do Google Adsense eu uso o [Banco Rendimento](http://www.rendimento.com.br/5601/google/como-receber.html) faz alguns anos.

Não é preciso ter conta e o processo é todo online. O Google faz o pagamento e no mesmo dia o valor em Reais está na minha conta, e eles mandam um comprovante por e-mail com os detalhes. As taxas cobradas são as mais baixas dentre os vários bancos que pesquisei.

**Comment by lucasdaiki** [comment]
Eae pessoal, vocês já conhecem o https://www.remessaonline.com.br/ ? :)

**Comment by willycamargo** [comment]
@lucasdaiki mas seria para enviar dinheiro para o exterior, né!?

Encontrei o https://transferwise.com e estamos avaliando a possibilidade de usar ele.

**Comment by lucasdaiki** [comment]
@willycamargo Acabou de lançar a feature de recebimento :P hahaha

**Comment by lucasbento** [comment]
@willycamargo: uso o transferwise.com, funciona muito bem, dinheiro vai e volta rapidinho.

**Comment by eliseumds** [comment]
Alguém tá usando borderless accounts da TransferWise?

**Comment by evansantos** [comment]
@willycamargo o remessa faz envio e recebimento

**Comment by willycamargo** [comment]
Estamos usando Payoneer e, apesar de uma demora inicial para validar a documentação, não tivemos problemas com o serviço.

Cobra 1% de taxa, o que é baixo se comparado com outros serviços, mas a cotação deles esta sempre um pouco abaixo de outros serviços.

Não entendo muito sobre tudo isso e não tenho total decisão de escolha, mas no geral sei que esta melhor do que usar paypal por exemplo.

**Comment by clmadrazo** [comment]
@willycamargo como declaras a receita os valores recebidos?

**Comment by willycamargo** [comment]
@clmadrazo tenho empresa (ME) aberta. Após o recebimento na conta PJ eu gero uma nota fiscal com o valor em reais e depois disso todo o fluxo é normal.

A vantagem é que exportação de produtos e serviços não são aplicados alguns impostos, então pago menos impostos, mas Imposto de Renda continua a mesma coisa.

Utilizo o Contabilivre para me auxiliar com contabilidade.

**Comment by eliseumds** [comment]
@willycamargo esse 1% que a Payoneer cobra já inclui a transferência pro Brasil? Depois disso você perde mais um tanto pra converter pra reais, não?

**Comment by willycamargo** [comment]
@eliseumds esse 1% é cobrado assim que o valor cai na plataforma.

Depois, ao pedir transferência para conta do brasil eles tem uma cotação deles que sempre esta uns 5 centavos abaixo da cotação de mercado. O valor cai em reais na conta no brasil e não tem IOF ou outros impostos.

Ainda é mais vantajoso do que enviar remessa direto para conta do itau. As taxas cobradas seriam bem mais altas.

**Comment by clmadrazo** [comment]
Alguém tem usado as operações de câmbio do Banco Inter? Será que oferecem melhores condições que o payoneer?

**Comment by pedrohenri** [comment]
Galera, tô voltando aqui pra reforçar que até agora o serviço da Husky continua muito bom e cada vez mais competitivo. Acabei de receber um email do novo app deles, que vem com um sistema de indicação que dá 10% off para indicados e pode até zerar a taxa de quem indica.

O cupom que dá 10% off vitalício na taxa deles, que vai de 3,5% (o que eu pago hoje) para 3,15%:
**H-16042**

[Husky.io](https://husky.io)

Completo um ano esse mês e nunca tive dor de cabeça. Então acredito que pra quem entrar agora vai ser ainda melhor.

**Comment by rafaelwinter** [comment]
@pedrohenri O problema da Husky é que demoram vários dias para te pagar. Meu salário deste mês foi enviado no dia 6/9 às 7:50 da manhã, e a Husky transferiu para minha conta no dia 11/9 (ontem).

Fiz uma simulação na Payoneer e deu uma diferença de R$ 80. O que eu vou pagar de juros em todos boletos que tive que atrasar por causa da demora da Husky com certeza vai ser mais mais do que 80 reais. A diferença é que na Payoneer o cara recebe no dia seguinte.

Estou pensando seriamente em sair da Husky e migrar para Payoneer ou Transferwise.

**Comment by pedrohenri** [comment]
@rafaelwinter realmente, tem que ter uma certo planejamento devido a essa demora. Meu pagamento costuma cair no dia que vence minha fatura do cartão de crédito, então é algo que não posso contar, por que se atrasar um dia babou, hehe

**Comment by willycamargo** [comment]
@rafaelwinter nada garante que você irá receber no dia seguinte com a Payoneer. Normalmente é dentro de 2 dias, mas esse mês eles demoraram 5 dias úteis (prazo máximo) para transferir meu pagamento. 

O segredo é manter uma organização financeira que não te prejudique caso precise esperar o prazo desses serviços. Infelizmente estamos reféns do prazo deles.

**Comment by hugomaiavieira** [comment]
Estou usando o Remessa Online para recebimento faz 5 meses e estou gostando **bastante**. Eles usam o cambio comercial e o spread é de 1,300%.

Criando a conta por [esse link](https://remessaonline.com.br?utm_voucher=hh112) (meu link de referência) ganha 20% de desconto no spread da primeira transferência.

O depósito é feito em sua conta em até 3 dias após a solicitação.

O suporte deles é bem bom também.

**Comment by lcguida** [comment]
Eu verifiquei com o **Transferwise** e eles ainda não estão aceitando trasnferências direto para conta PJ no Brasil (conta Business), mas estão trabalhando nisso.

Existe sempre a possibilidade de verificar com o contador se você receber na conta pessoal e transferir para a PJ se é legal (não tenho conhecimento quanto à isso).

Sobre o **Payoneer** se o a empresa que te paga tiver conta lá, esse 1% não é cobrado. Nesse caso, o taxa deles fica em 2% (para transferir da sua conta Payoneer para  a sua conta bancária no brasil).

Não sei como é a taxa de conversão deles (spread).

**Comment by mcbs1981** [comment]
Boa tarde a todos. Alguém aqui usa o Transferwise para receber salários do exterior? Como vcs fazem? Vcs passam o o número wire?

**Comment by enyamada** [comment]
@pedrohenri Usei seu cupom pra me inscrever no Husky, obrigado pela dica.

Ainda não usei e pra falar a verdade estou estudando outras alternativas. O Husky não é o de menor custo, mas parece ser o menos burocrático (e está no Brasil). 

Uma coisa que me preocupa é o fato da conta de depósito que me forneceram não estar no meu nome (e sim da própria Husky). É o seu caso também? Se sim, vc saberia dizer o que impediria eles (numa situação meio que extrema) de simplesmente embolsar o dinheiro pra eles próprios? abs

**Comment by pedrohenri** [comment]
@enyamada Tem certeza que não tem nada no seu nome? Eu consto na minha como "Beneficiary". É no Banco Paulista S/A.

Sinceramente não sei explicar bem o que lhe daria essa segurança, o que posso dizer é que o que me tranquilizou no início foram o reconhecimento e prêmios que a startup estava conquistando e também o bom atendimento, que é bem direto e pessoal. Você pode perguntar essas coisas diretamente a eles também. 

Hoje minha confiança vem da experiência. Já recebi quase 20 pagamentos por meio deles que somam um valor bastante considerável e nunca tive problemas. Pensando nessa situação extrema (e tem que pensar mesmo) não vejo muitas chances deles embolsarem nossa grana pois parece que o negócio deles é bem sólido e não valeria a pena.

**Comment by felipechalreo** [comment]
Eu uso bastante o Xoom.

*Felipe Chalreo*
Freelancer Web Developer
*m:*+5512996162942
*w:*www.chalreo.com

**Comment by carlosiqueira** [comment]
O Banco BS2 está com uma solução de conta internacional que salva a vida nesses casos.

**Comment by brunolm** [comment]
[Husky](https://husky.io/quanto-custa/)
- 4%
- dolar do Google
- aceita conta PJ
- aceita pagamento em batch


E é possivel reduzir o custo convidando outras pessoas para plataforma.

> Meu cupom é H-236C8: https://husky.app.link/?%24identity_id=553966345881327018
