### ISSUE TITLE
Pessoal na opinião de vcs qual a melhor IDE Atom ou VSCode? e pq?

### ISSUE THREAD

**Issue by ghost** [frontendbr/forum#1240]
Pessoal na opinião de vcs qual a melhor IDE Atom ou VSCode? e pq?

**Comment by Mendrone** [comment]
@Bruno413 Tomei a liberdade de editar o conteúdo da issue porque o anterior era só o que sugerimos na template, ok?

**Comment by Bruno413** [comment]
ok :+1:

**Comment by MarcoWorms** [comment]
O VSCode pra mim funciona bem parecido com o atom apesar de eu não usar nenhum dos 2, mas dado que o VSCode é da microsoft e ela comprou o Github (que fazia o atom) creio que a longo prazo o VSCode tem uma vantagem aí

**Comment by Bruno413** [comment]
Verdade, tinha esquecido que a Microsoft comprou o github, o Atom pertence ao github logo também é da microsft, será que vão manter as 2 IDE?

**Comment by AlexandreRStos** [comment]
Acredito que manterá sim!  pois quem mantem a IDE são as comunidades!  Uma dela so sumira caso a comunidade não queira mais assim como tantas outras IDE

**Comment by tcelestino** [comment]
> pode ser, as 2 são bem parecidas e tem o mesmo dono poderiam se juntar

Ao meu ver, o Atom e o VSCode possuem propostas diferentes, mesmo a MS apostando na integração com o Github no VSCode, acho que o Atom está mais integrado. Sem contar que... parece que o Atom é bem pior em performance em relação ao VSCode, devido a isso acho bem "difícil" a MS juntar o core dos dois. Pode ser que um fique mais popular que o outro (o que já vem acontecendo hoje em dia).

**Comment by leandrocunha** [comment]
Antes do VSCode eu era muito fã do Atom, só que de fato usei bem pouco pq ele comia muita memoria do meu macbook e fica inviavel desenvolver com isso usei por muito tempo o Sublime.

Hoje depois de muita resistencia mudei pro VSCode e realmente o trabalho que os caras estão fazendo é incrível, em termos de performance, intelisense, integrações e extensões o VSCode ganha fácil dos outros.

Mas tb temos que levar em conta que o Atom e o Sublime são editores e o VSCode é uma IDE mesmo.

**Comment by phenriqueleao** [comment]
> Sem contar que... parece que o Atom é bem pior em performance em relação ao VSCode, devido a isso acho bem "difícil" a MS juntar o core dos dois.

Esse é o motivo de eu usar o VSCode, tentei usar Atom e achei a performance bem ruim no meu PC.

**Comment by LFeh** [comment]
Acho o VSCode simplesmente espetacular, mantém as qualidades do Sublime: Simplicidade e performance, e adiciona features incríveis como o terminal integrado.

Além disso a biblioteca de plugins é enorme e com atualizações constantes.

Dificilmente trocaria hoje.

**Comment by thismarcoantonio** [comment]
Acredito que o que eu acho melhor no VSCode é a facilidade de personalizar tudo, javascript é maravilhoso <3

Outra coisa que me chama bastante atenção é a constante melhoria do mesmo, claro, tem algumas coisas que sempre vão desagradar, mas sempre dá pra desativar, só pesquisar um pouquinho (como aquela recente adição onde mostrava os imports não utilizados em uma opacidade mais leve).
