### ISSUE TITLE
Qual é a Diferênça entre Front-End Developer e o Front-End Designer?

### ISSUE THREAD

**Issue by nazarepiedady** [frontendbr/forum#1248]
# Objetivos destá issue:
* Procurar esclarecer aos iniciantes as diferenças entres esses dois profissionais.
* Explicar o que cada um faz
* Como podemos diferenciar o trabalho de cada um.

**Comment by mikejavier** [comment]
Segue um artigo que aborda isso. 

https://medium.com/@amitmojumder/front-end-engineer-differs-from-front-end-developer-68efe13fce7b

**Comment by victornery** [comment]
Acredito que todos sejam _Front-end Developers_, porém, cada um com seu foco: 
## Front-end Designer
- Especialista em layout, ou seja, focado em Pixel Perfect. É aquele cara com o toque mais _artístico_.
- Geralmente, desenrola em JavaScript, mas não tem o mesmo como seu foco.
- Ás vezes, são os Front-end Designers que produzem o layout.

## Front-end Engineer
- Especialista em JavaScript.
- A versão mais back-end do front-end.
- _Se garante_ em lógica de programação.

**Comment by LFeh** [comment]
Linkando: #428 #815 #415 #32

**Comment by kvnol** [comment]
Sou claramente Front-end designer, mas queria ser os dois.

**Comment by adeonir** [comment]
Pois é, sou Front-end com foco em UI, então também sou claramente Front-end Designer.

**Comment by evertonthepaula** [comment]
Eu costumo pensar em engenheiro um de software que é front-end ou designer com skills para trabalhar no front. Vou colocar mais um item nessa sopa, baseado no [front-end-handbook](https://frontendmasters.com/books/front-end-handbook/2018/practice/types-of-front-end-dev.html) me percebi muito mais próximo ao Front-end Ops.

**Comment by e200** [comment]
Sou ambos.

**Comment by xteoos** [comment]
**Front End Designer** 
 

-    Grid;
-     Interface para Mobiles (responsive, adaptativo, user behaviour etc);
-     Arquitetura de Informação;
-     Teoria e uso das cores;
-     Motion design;
-     User Experience / Research;
-     Design de Interfaces / User Interface;
-     Funil e fluxos de usuários;
-     Design systems;
-     Prototyping e suas ferramentas;
-     Atomic Design e outros conceitos;
-     Manipulação de SVG seja para fazer animação ou exibição de ilustrações;
-     Manipulação de WebGL, talvez não profundamente, mas entende suas manipulações;
-     Ferramentas como Sketch, Photoshop, Illustrator, Studio…

**O Front-end engineer**


Algumas responsabilidades e interesses desse perfil:

-     Lidar com o back-end a fim de definir padrões da API;
-     Definir arquitetura de client-side;
-     Definir as regras de negócio e lógica pelo lado do client;
-     Responsável por gerenciar a segurança e comunicação entre client e servidor;
-     Testes unitários, testes end-to-end, testes testes testes e suas ferramentas;
-     Bancos de dados;
-     Servidor e suas particularidades;
-     Containers;
-     Continuous Delivery/Integration;

Peguei no artigo: https://medium.com/tableless/frontend-design-engineer-parte2-498bada72d84 
Que inclusive é um ótimo artigo para agregar a discussão

**Comment by tarciozemel** [comment]
"Two front-end developers are sitting at a bar. They have nothing to talk about."

https://css-tricks.com/the-great-divide/
