### ISSUE TITLE
Compartilhar variáveis entre pipes no gulp

### ISSUE THREAD

**Issue by yuricamara** [frontendbr/forum#125]
Quem manja de compartilhar variáveis entre pipes? Usando uma variável no escopo da função da task não funciona!

Trecho do código:

``` javascript
.pipe(plugins.intercept(function(file){
  var content = JSON.parse(file.contents.toString());

  cssTimestampStored = content.css

  return file;
}))
.pipe(plugins.rename('ionic.app.' + cssTimestampStored + '.min.css'))
```

No caso, a variável em questão é a  cssTimestampStored

**Comment by tcelestino** [comment]
@yuricamara ver se isso te ajuda - http://stackoverflow.com/questions/22026389/passing-variables-between-pipes-in-gulp

**Comment by yuricamara** [comment]
@tcelestino Obrigado pelo link. Eu tentei as sugestões dele sem sucesso. Acabei resolvendo meu problema de outra forma mas continuo querendo aprender a fazer isso.

**Comment by tcelestino** [comment]
@yuricamara qual foi a solução que você deu? Compartilha pra gente! :)

**Comment by yuricamara** [comment]
Eu trabalhei isso com [Node fs](https://nodejs.org/api/fs.html).
Pra incluir o code num pipe eu usei o [gulp-callback](https://www.npmjs.com/package/gulp-callback)

**Comment by yuricamara** [comment]
Ficou gambiarra. O objetivo de todo o código era:
1.Verificar se meus assets tinham sido modificados
2.Se modificado criar um arquivo minificado e concatenado com um novo timestamp.
3.Se não modificado criar um arquivo minificado e concatenado com um timestamp armazenado num JSON.
Isso para aproveitar o cache quando nenhum arquivo foi modificado e não usar o cache quando algum arquivo foi modificado.

Tá funcionando mas o code tá tão gambeta que dá vergonha de comparilhar. heheheh!

**Comment by yuricamara** [comment]
Discussão sobre o objetivo principal de todo o código em #138

**Comment by LFeh** [comment]
Valeu @yuricamara ;)

**Comment by yuricamara** [comment]
@LFeh , acredito que eu tenha te confundido. A questão deste tópico não foi respondida. O que abri não é uma resposta. É só uma relação ao código de exemplo. Talvez seja melhor eu apagar o comentário "Discussão sobre o objetivo principal de todo o código em #138" né? E pode reabrir o tópico, por favor?

**Comment by LFeh** [comment]
Sorry :), confundi mesmo, haha.
