### ISSUE TITLE
Configuração de Magnolia (JAVA CMS) em Docker

### ISSUE THREAD

**Issue by Fabot7** [frontendbr/forum#1251]
Prezados(as),

Após ter pesquisado por um CMS baseado em JAVA, que seja Open Source e License Free, encontrei o Magnolia, em sua versão Community Edition. Então, utilizei um repositório do GitHub, a partir do hub.docker.com (nicolasbarbe/magnolia-base).

Utilizei esse repositório para configurar localmente dois containers (aplicação e banco de dados). Consigo subir ambos os containers e eles se comunicam entre si, porém não consegui acessar a aplicação na porta que configurada (localhost:8080). Eu entro no container da aplicação e vejo os registros de log, capturando as tentativas de acesso na porta 8080, mas com retorno Not Found (Erro 404).
Assim, gostaria de saber onde configurar para acessar a aplicação remotamente, até mesmo configurando um endereço, FQDN, IP, ou o próprio localhost na porta 8080. Outra dúvida é saber qual é o diretório web raíz do Magnolia ou seu repositório de conteúdo, para que eu possa abrir esses volumes localmente no servidor?

**Comment by LFeh** [comment]
@Fabot7 Sugiro postar aqui -> https://github.com/backend-br/forum :)
