### ISSUE TITLE
Sobre Performance

### ISSUE THREAD

**Issue by baltazarparra** [frontendbr/forum#126]
Lendo o artigo [a faster ft.com](http://engineroom.ft.com/2016/04/04/a-faster-ft-com/) me bateu uma curiosidade:

- O que vocês andam fazendo para otimizar o desempenho?

Além dos ótimos tópicos abordados no projeto [Browser Diet](https://browserdiet.com/pt/)
quais práticas mais, podem ser úteis no dia-a-dia.

**Comment by Mendrone** [comment]
Acho que a Issue #43 pode ajudar a responder parte da sua pergunta :grin:
