### ISSUE TITLE
React.js && Vue.js && Angular.js ?

### ISSUE THREAD

**Issue by nazarepiedady** [frontendbr/forum#1260]
# Está issue tem os seguintes objetivos:
1 - Partilhar experiências com as tecnologias mencionadas.
2 - Indicar um ponto de partida aos iniciantes de cada tecnologia.
3 - Saber qual delas tem a curva de aprendizado mais curta.
4 - Indicar bons livros para se aprender cada tecnologia.
5 - Explicar aos iniciantes onde é possível aplicar cada tecnologia.

**Comment by kavalcante** [comment]
Sobre o item 5, eu escrevi um artigo um tempo atrás pra ajudar um pessoal aqui no trampo, talvez seja útil: https://medium.com/trainingcenter/descomplicando-spas-caa8f57bdbf3

**Comment by danielosasp** [comment]
Como Coloco este java em meu site ?  https://fazerdinheiroonline.net.br/renda-extra/
--
