### ISSUE TITLE
Vue.js - Casa do Código

### ISSUE THREAD

**Issue by ghost** [frontendbr/forum#1262]
Pessoal,

estou iniciando os estudos em Vue.js. Gosto bastante de estudar com livros, inclusive tenho 2 da Casa do Código, que comprei por recomendação e foram muito bons. Porém, gostaria de saber se alguém já adquiriu ou pretende adquirir este **[livro](https://www.casadocodigo.com.br/products/livro-vue)** aqui (**Vue.js - Construa Aplicações Incríveis**). Recomenda?

Além disso, quem tiver materiais (vídeos, cursos, artigos, etc) em inglês ou português e puder compartilhar, fico agradecido!

**Comment by Gpaula95** [comment]
Eai @GuimaraesJean  beleza ? 

cara o VueJS é meu framework preferido, portanto sou suspeito em falar bem dele kkk, porém eu particularmente aprendi muito com a documentação do Vue. A Doc e muito auto explicativa, até porque o Vue é bem intuitivo, recomendo que você leia a documentação e siga os passos do Livro, ja vai te dar uma base legal. Recomendo tambem estudar o Vuex, Axios (Requisições API) e VueRouter.

Espero ter ajudado, fico a disposição para eventuais duvidas, Abraço !

**Comment by GuimaraesJean** [comment]
@Gpaula95, realmente me parece muito boa, bem completa. Vou ler de cabo a rabo pra pegar os detalhes :D 

Vou chamar pra tirar umas dúvidas sim! hahahaha 
Muito obrigado e abraços!

**Comment by evertonthepaula** [comment]
E não se esqueça de ficar atento a versão 3 , pois diferente de uns cara aí Vue não fica quebrando seu projeto de 6 em 6 meses, pq Vue é amor <3 .

https://medium.com/the-vue-point/plans-for-the-next-iteration-of-vue-js-777ffea6fabf

**Comment by didiraja** [comment]
@evertonthepaula #indiretasdobem

**Comment by hhalmeida** [comment]
Bom dia! 
@GuimaraesJean , Man, primeiro olhe a documentação do Vue, ela e muito boa.
Faz um projetinho standalone ( só um arquivo) e step-baby faz funcionar, não se preocupe se está bom o código ou não, depois você vai refatorando ( refactoring is live ) e implementando mais coisas.

Um bom lugar para se ver coisas de vue, é procurar os videos do Vendovelli no youtube e do Tony Lampada ( http://evolutio.io ).

E jamais tenha medo de perguntar, estamos aqui para apoia-lo, e bora vuelizar o mundo.! rsrs

@evertonthepaula temos que vuelizar tudo!! rsrs

**Comment by GuimaraesJean** [comment]
Valeu pelas dicas, galera! 😄
