### ISSUE TITLE
Procuro freelancers ou desenvolvedores para compartilhar espaço ocioso em servidores

### ISSUE THREAD

**Issue by ricalamino** [frontendbr/forum#1267]
Olá! 

Sou desenvolvedor front-end e tenho 2 servidores Ubuntu com fácil configuração que pouco utilizo mas acabo pagando por eles. Eu tinha uns sistemas já desativados e tenho alguns sites pessoais. Procuro freelancer ou desenvolvedor que queira diminuir/compartilhar custos e queira hospedar qualquer site ou sistema nos servidores. Crio usuário senha e qualquer recurso adicional que possa ajudar... Tenho bons conhecimentos em configuração de servidor.

Se alguém tiver interesse, basta entrar em contato. Não sei se tem um local mais apropriado para compartilhar isso, mas estou colocando aqui. Se não for apropriado podem apagar... 

Obrigado!﻿

**Comment by theandersonn** [comment]
Uma seção que não temos aqui na Org é **Classificados**.
@frontendbr/admins Conseguimos amadurecer uma ideia nessa direção?

**Comment by diogomoretti** [comment]
> Uma seção que não temos aqui na Org é **Classificados**.
> @frontendbr/admins Conseguimos amadurecer uma ideia nessa direção?

Estamos para abrir um repo chamado Freelas, acho que vai atender a essa demanda =]

**Comment by ricalamino** [comment]
Obrigado pessoal!

**Comment by LFeh** [comment]
Fechando
