### ISSUE TITLE
Angular - Kendo PDF

### ISSUE THREAD

**Issue by Vitor-Felipe** [frontendbr/forum#1269]
Fala galera!!
Seguinte, eu estou utilizando o [Kendo](https://www.telerik.com/kendo-angular-ui/components/pdfexport/) para exportar alguns relatórios no formato PDF. Porém muitos desses relatórios estão em grids com paginação e mesmo declarando a propriedade: 

> _allPages="true"_

Não consigo exportar todas as paginas do meu grid, apenas a primeira é gerada no pdf!
Exemplo do meu código:

[kendo.zip](https://github.com/frontendbr/forum/files/2553284/kendo.zip)

PS: Não consegui mostrar o código de maneira clara aqui no post, segue o zip com o mesmo.

**Comment by LFeh** [comment]
@Vitor-Felipe Coloca seu código no [plnkr](https://plnkr.co/) pra facilitar :)

**Comment by Vitor-Felipe** [comment]
Desculpa a demora para responder...
Acabei utilizando o jspdf no lugar do Kendo e funcionou, obrigado por tudo :+1:
