### ISSUE TITLE
[Frameworks Js] - SEO e Marketing, Quando usar (ou não) um framework js

### ISSUE THREAD

**Issue by Gpaula95** [frontendbr/forum#1271]
Minha ideia é levantar uma discussão sobre: é realmente viável ou necessario criar tudo com framework Js ? Uma landing page por exemplo, qual a melhor forma de trabalhar o SEO e o marketing com components criados aleatoriamente com os frameworks ? 

PS. caso já exista uma issue com essa discussão me avisem (pesquisei enão achei)

**Comment by kavalcante** [comment]
Necessário não é. Viável, depende bastante de caso para caso. Um caso que me lembro, de remoção foi na Netflix:

https://twitter.com/netflixuie/status/923374215041912833

Aqui na empresa, nós usamos Nuxt (Vue com SSR), e para nós, faz sentido mantermos nossas landings e páginas públicas em Vue, pelos seguintes motivos:

- Manter tudo na mesma stack
- Possibilidade reutilizar componentes que utilizamos dentro da aplicação principal
- Único projeto, o que torna mais fácil dar manutenção (já que não temos muitos desenvolvedores)

Além disso, nossa performance não sofre TANTO impacto (é mais lento, mas não tanto). Então, por enquanto faz sentido mantermos nesse modelo. Porém, como tudo na vida, pode ser que deixe de fazer sentido amanhã ou depois, por algum motivo...
