### ISSUE TITLE
UX & UI Design

### ISSUE THREAD

**Issue by nazarepiedady** [frontendbr/forum#1272]
# Objetivos da issue:
1 - Concientizar os iniciantes da importância de se aprender ou conhecer essas áreas.
2 - Para que serve cada área.
3 - Porquê um profissional em **front-end** 'deve' aprender ou conhecer cada área.

**Comment by lcs11v4cs** [comment]
Eu não sei se entra nos objetivos da Issue (qualquer coisa eu deleto), mas eu gostaria de recomendar alguns sites que eu acompanho, que falam sobre UX e UI Design. Eu também sou programador front-end e pego várias dicas e referências nesses sites.

_https://medium.muz.li
https://brasil.uxdesign.cc
https://uxplanet.org_

Espero que seja útil! :)

**Comment by luizbills** [comment]
Vou recomendar umas leituras:

- [7 regras para criar belas UIs](https://github.com/frontendbr/forum/issues/1272#issuecomment-437582890)
- [Uma coleção de detalhes que melhoram uma UI](https://twitter.com/i/moments/880688233641848832)
- [Um guia super simples para quem tem dificuldade em escolher cores](https://www.smashingmagazine.com/2016/04/web-developer-guide-color/)

**Comment by vicainelli** [comment]
Eu simplesmente **amo** as dicas do Steve Schoger, estão em inglês, mas da pra entender bem.

- [Design Tips](https://twitter.com/i/moments/994601867987619840)
