### ISSUE TITLE
Sites com testes de Dev Front-end e Back-end.

### ISSUE THREAD

**Issue by marcusvcribeiro** [frontendbr/forum#1273]
Uma vez vi no forum uma issue(Que nao achei mais) de alguns sites que continuam testes de admissão de front-end e back-end. Alguem sabe alguns desses sites para compartilhar novamente com a galera?

**Comment by Dborah** [comment]
Aqui tem uns testes de front-end: https://github.com/LFeh/frontend-challenges

**Comment by mariorodeghiero** [comment]
@marcusvcribeiro Caso ajude, Neste repositório [Interview Questions](https://github.com/h5bp/Front-end-Developer-Interview-Questions) contém varias questões relacionado a Front End. ✌️
