### ISSUE TITLE
Service Work Angular 6

### ISSUE THREAD

**Issue by grodrigues** [frontendbr/forum#1277]
Estou desenvolvendo um pwa em Angular com Service Work foi feito o cache da imagens mais não consigo carregar quando estou no modo offline. O que pode haver de errado ?

**Comment by LFeh** [comment]
Na aba `Network` do seu DevTools, verifica se as imagens de fato estão sendo cacheadas/fornecidas via service worker.

**Comment by grodrigues** [comment]
![captura de tela de 2018-11-14 14-02-51](https://user-images.githubusercontent.com/3936016/48498949-13911580-e816-11e8-8a07-1cade666bc76.png)

**Comment by grodrigues** [comment]
![captura de tela de 2018-11-14 14-06-17](https://user-images.githubusercontent.com/3936016/48499136-826e6e80-e816-11e8-8c38-bf8f1dd1f4db.png)

**Comment by grodrigues** [comment]
![captura de tela de 2018-11-14 14-07-46](https://user-images.githubusercontent.com/3936016/48499226-ba75b180-e816-11e8-8a93-183a3fda68b5.png)

**Comment by grodrigues** [comment]
Como no print acima ele mostra nas imagens (From disk cache)

**Comment by grodrigues** [comment]
https://stackoverflow.com/questions/52162290/angular-6-pwa-service-worker-not-serving-content-offline

**Comment by grodrigues** [comment]
Esse link é o problema que estou passando.

**Comment by LFeh** [comment]
Também uso Angular e não tive esse problema.

Já viu se essa questão já foi apontada no próprio repositório do Angular? De repente na versão 7 foi corrigido.

**Comment by grodrigues** [comment]
@LFeh não vou dar uma olhada. Obrigado

**Comment by LFeh** [comment]
Atualiza a gente se chegar numa solução.

**Comment by grodrigues** [comment]
Sim, deixa comigo que aviso.

**Comment by grodrigues** [comment]
Atualizei para a versão 7 do Angular mais não funcionou

**Comment by grodrigues** [comment]
Agora a minha situação é que ele fiquei Offline First e que não está acontecendo. Ele faz o cache online e quando fica offline ele se perde.
