### ISSUE TITLE
SEO em Aplicações Reactivas

### ISSUE THREAD

**Issue by nazarepiedady** [frontendbr/forum#1283]
# Objetivos da issue:
1 - Compartilhar experiências boas e más com o SEO em aplicações reactivas
2 - Compartilhar links sobre artigos que ajudam a resolver alguns problemas
3 - Fazer algumas recomendações para os desenvolvidores reactivos iniciantes.

**Comment by luizbills** [comment]
SSR (server side rendering) já resolve praticamente todos os problemas.

**Comment by allansduarte** [comment]
@luizbills SSR ajuda bastante, mas não resolve tudo, precisamos ser mais exatos aqui para o pessoal, então vou compartilhar o que eu sei para poder ajudar.

1- Desenvolver um HTML semântico é o primeiro passo;
2- Canonical tags ajudam;
3- external nofollow e external dofollow em links externos no seu site também ajudam a manter sua integridade;
4- Dados estruturados desenvolvido com json-ld ajudam muito, pois dão significado as suas informações para o buscador.

Acredito que essas são dicas básicas para qualquer aplicação não apenas aplicações reativas, tendo mais informações é só compartilhar pessoal.

**Comment by LFeh** [comment]
Uma má prática muito comum é o uso de tags não semânticas pelo fato dos componentes ficarem abstraídos. Isso é péssimo.

Como o @allansduarte disse:

> Desenvolver um HTML semântico é o primeiro passo;

**NÃO DEIXEM** de usar tags semânticas nos componentes, fazer tudo com `<div>`, ou pior, com tags criadas por você, é um erro. 

Depois não adianta culpar o coitado do SPA pela falta de SEO.

**Comment by didiraja** [comment]
Complementando o que o @LFeh disse, nunca envelopem seus componentes com div ou span. No caso do React, usem o [React.Fragment](https://tableless.com.br/utilizando-fragment-react16/). Ele é feito exatamente para isso. 

Agora uma dúvida, não tem nenhuma opção pra renderizar o html para SEO, sem ser SSR/Isomorfico? Nos projetos pessoais, por enquanto, queria evitar.

**Comment by wkrueger** [comment]
@didiraja eu ouvi falar por aí é que o google até executa o seu site com js, mas demora mais pra atualizar ou ate pode dar um score mais baixo. (É bom verificar no console do google a visão que o crawler esta tendo da sua página)

Independentemente de boatos, o SSR reduz o “time to first display”, o que dá pontos de SEO. Por exemplo o next.js literalmente precompila um HTML estático. Vc pode aí escolher carregar os dados depois ou no servidor, cada um com suas vantagens (aí tem que testar).
