### ISSUE TITLE
doação de livros

### ISSUE THREAD

**Issue by relaie44** [frontendbr/forum#1289]
boa tarde galera , venho hoje aqui , porque acho que está minha iniciativa é bastante importante , para nossa comunidade , vamos ajudar pessoas que não têm como comprar livros de programaçao caros , proponho  que colocarmos alguns pdf de diversos livros aqui, como  o livro postado a baixo:

[JavaScript O Guia Definitivo_v2.pdf](https://github.com/frontendbr/forum/files/2613568/JavaScript.O.Guia.Definitivo_v2.pdf)

daqui a um tempo estarei postando o livro de php-gtk do pablo dall'oglio, e  diversos outros livros que tenho  , como os da serie use a cabeça 
agradeceria se ajudassem com a causa!!

**Comment by LFeh** [comment]
@relaie44 Entendo sua boa intenção, mas esse livro é um livro pago, e fornece-lo gratuitamente configura pirataria.

Sendo assim, não podemos manter aberto.

Sugiro que participe desse [nosso repositório de livros](https://github.com/frontendbr/doe-um-livro), na qual pode postar livros gratuitos ou doar e receber livros fisicos.
