### ISSUE TITLE
Design Patterns com frameworks JavaScript

### ISSUE THREAD

**Issue by nazarepiedady** [frontendbr/forum#1290]
# Objectivos da issue:
1 - Esclarecer a importância dos design patterns no uso de framewoks JavaScript.
2 - Fazer recomendações de design patterns para iniciantes.
3 - Mencionar tanto os beneficios e maleficios de usar design patterns.

**Comment by rafaelvianna** [comment]
Recomendo esse livro: https://addyosmani.com/resources/essentialjsdesignpatterns/book/

**Comment by HenriqueSilverio** [comment]
E para iniciantes (ou nem tão iniciantes também xD), vale **reforçar** isso que escrito no repositório "Design patterns for humans" citado acima: 

> "Be Careful. Design patterns are not a silver bullet to all your problems... so don't overthink."
