### ISSUE TITLE
Em projetos desenvolvidos, quais browsers vocês estão dando suporte?

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/forum#1298]
Como vocês procedem na questão de suporte a browsers?
Notificam o cliente sobre isso? Tipo no briefing.

Algum causo de suporte a browser antigo? Como foi?

**Comment by luizbills** [comment]
Só estou dando suporte ao IE quando solicitado e somente ao IE11. Mas ultimamente o safari está dando mais trabalho.

**Comment by luizbills** [comment]
@theandersonn Sei não. Comigo quase sempre o primeiro bug de frontend vem de um iphone usando safari.

**Comment by theandersonn** [comment]
Beleza, obrigado pelo feedback.

**Comment by LFeh** [comment]
Aqui apenas as versões mais modernas de cada um: Edge, Firefox, Safari, Chrome, etc...

**Comment by theandersonn** [comment]
@LFeh Que legal conseguiram abolir o IE.
