### ISSUE TITLE
Avaliação Boilerplate - React&Redux

### ISSUE THREAD

**Issue by SrVieira** [frontendbr/forum#1300]
Boas pessoal,

Sou ainda um newbie no **_React_**, mas to me esforçando para aprender cada vez mais e com isso compartilhar com a comunidade um pouco deste conhecimento obtido. 
Venho trabalhando á alguns dias em meu boilerplate para desenvolvimento de **_web applications_**, escolhi o **_React_** pois além de ser uma das tecnologias mais utilizadas possui uma grande aceitação do mercado.

Tive a idéia de montar este boilerplate estes tempos quando estava montando um projeto para estudos pessoais, encontrei vários na rede, mas nenhum destes sanava minha dor, com isso montei este simples boilerplate. 

**Ele utiliza as seguintes ferramentas/libs:**

React, Babel, Webpack, ESLint (Utilizando o padrão do Airbnb), SASS, Redux e ReduxForm.

É um boilerplate simples, limpo e de fácil entendimento. Para quem está começando deixei algumas descrições em cada parte do projeto. 

Então gostaria da opinião de vocês sobre o boilerplate, oque mudariam, críticas construtivas são bem vindas, tudo na vida precisa de um feedback e conto com vocês para isso.

https://github.com/SrVieira/react-redux-boilerplate

**Comment by linconkusunoki** [comment]
Cara é legal criar um boilerplate, mas acho que o uso dele vai muito do gosto de cada um, por exemplo, Sass é legal, mas para trabalhar com React tem uma galera que adora Styled Components outra que curte CSS em módulos e tem também quem use Functional CSS...

A estrutura do Redux acaba virando um tradeoff muito grande hoje, ainda mais com a chegada do React Hooks, talvez valeria a pena criar um boilerplate usando Hooks (?) kkk

O que eu adicionaria ainda neste boilerplate seria o Prettier, Jest, Enzyme, PropTypes, Env's, Husky, Axios, EditorConfig e alguma config de CI

**Comment by SrVieira** [comment]
> Cara é legal criar um boilerplate, mas acho que o uso dele vai muito do gosto de cada um, por exemplo, Sass é legal, mas para trabalhar com React tem uma galera que adora Styled Components outra que curte CSS em módulos e tem também quem use Functional CSS...
> 
> A estrutura do Redux acaba virando um tradeoff muito grande hoje, ainda mais com a chegada do React Hooks, talvez valeria a pena criar um boilerplate usando Hooks (?) kkk
> 
> O que eu adicionaria ainda neste boilerplate seria o Prettier, Jest, Enzyme, PropTypes, Env's, Husky, Axios, EditorConfig e alguma config de CI

Sim sim, por este motivo até criei este para uso pessoal. Pois nenhum dos existentes me atraia haha, mas achei interessante as dicas, em relação aos componentes de testes eu já estou até implementando hahaha. vlws manito

**Comment by SrVieira** [comment]
@edit 

havia esquecido de colocar o link do boilerplate

https://github.com/SrVieira/react-redux-boilerplate

**Comment by thismarcoantonio** [comment]
@linconkusunoki Qual a verdadeira utilidade do Prettier? Vejo muita gente usando, mas n vejo uma utilidade real.

**Comment by linconkusunoki** [comment]
@thismarcoantonio o prettier garante que o código fique formatado conforme as regras que é aplicado no projeto.
Imagine que você está contribuindo para algum projeto open source, se tem o prettier você não precisa se preocupar com a formatação do código, no code review pelo menos isto não será um problema :)

Dai você pode estar se perguntando, mas o ESLint já não faz isso?
https://github.com/prettier/prettier-eslint/issues/101#issuecomment-313233479

**Comment by thismarcoantonio** [comment]
@linconkusunoki entendi agora, faz sentido.

**Comment by herberthenrique** [comment]
Gostaria de fazer uma leva provocação aqui. 
Mas por favor não me leve a mal, não estou criticando o trabalho de ninguém 😅 

É realmente necessário pensarmos em Redux nos dias de hoje?
Há algum tempo, muitos devs já abandonaram e eu particulamente não uso há um tempo por causa da API de [Context](https://reactjs.org/docs/context.html) do React.
Ela solucionou praticamente todos os casos onde Redux seria a antiga solução.

**Comment by herberthenrique** [comment]
E sobre o boilerplate eu tenho uma pergunta (ou sugestão) ☝️ 

Você tem os seguintes packages em dependencies:
- clean-webpack-plugin
- html-webpack-plugin
- webpack-merge

Eles não deveriam estar em devDependencies?  

Enquanto isso, você tem `redux` e `react-redux` em devDependencies, sendo que deveriam estar em dependencies?
