### ISSUE TITLE
Erro no Vue.js

### ISSUE THREAD

**Issue by GuiRamos7** [frontendbr/forum#1304]
E aí pessoa, beleza, estou aqui estudando Vue.js quando me deparo com um ""Erro""

O erro em questão é quando eu uso o `v-for`: [http://prntscr.com/lqr6mj](url) *(link do código.)*

Está funcionando normalmente, a duvida é, por que está ocorrendo isso?

**Comment by mikejavier** [comment]
Ta faltando a diretiva `key`.

Se quiser saber mais ao respeito disso segue o link da DOC
https://vuejs.org/v2/guide/list.html#key

Para resolver esse problema especifico pode fazer algo do tipo

```
<ul>
<li v-for="(foto, index) in fotos" :key="index"></li>
</ul>
```

Detalhe a ser observado... a diretiva `v-for` esta no `<li>` pois esse sera o elemento que vai ser rederizado N vezes.

**Comment by GuiRamos7** [comment]
Vlw mano, ajudou muito aqui 👍
