### ISSUE TITLE
Roadmap de tecnologias

### ISSUE THREAD

**Issue by nazarepiedady** [frontendbr/forum#1306]
# Objectivos desta issue:
1 - Falar da importância de se ter um roadmap no aprendizado de uma tecnologia.
2 - Clarear os pros e contras sobre os roadmaps
3 - Como fazer roadmaps.
4 - Onde podemos encontrar bons roadmaps?

**Comment by HmmerHead** [comment]
Encontrei esse Roadmap a um tempo atrás, e não sei se ele é usado ou já foi mencionado pelo pessoal. 
Ele atualiza com um certa periodicidade.

Seria interessante, inclusive debater sobre ele, e quem sabe, criarmos novos "caminhos".

[https://github.com/kamranahmedse/developer-roadmap](url)

**Comment by luizbills** [comment]
@HmmerHead o link está apontando para uma url errada.

**Comment by HmmerHead** [comment]
Desculpa, Segue o link...
https://github.com/kamranahmedse/developer-roadmap

**Comment by SrVieira** [comment]
> Encontrei esse Roadmap a um tempo atrás, e não sei se ele é usado ou já foi mencionado pelo pessoal.
> Ele atualiza com um certa periodicidade.
> 
> Seria interessante, inclusive debater sobre ele, e quem sabe, criarmos novos "caminhos".
> 
> [https://github.com/kamranahmedse/developer-roadmap](url)

Este roadmap citado pelo @HmmerHead é bem interessante, já seguia ele, mas com o advento de novas tecnologias, ferramentas e padrões é sempre bom manter-se atualizado. Creio que o uso de um bom roadmap é imprescindível para quem trabalha com tecnologia, pois te ajuda a ter um norte de qual caminho seguir, mas nada te impede de sair um pouco da caixinha. 

Uma dica que deixo, e estou me atualizando, é buscar por tecnologias/tools que estejam em top trends ou tenham maior número de adeptos, é sempre bom conhece-las pois não sabemos qual sera a próxima evolução na área de desenvolvimento.

Eu sempre me mantenho atualizado no medium.com, existem 'n' blogs com conteúdos interessantes e que me ajudam a manter o fluxo do meu aprendizado.

**Comment by Edvan27** [comment]
Eu acho bem útil esse "mapa", é praticamente obrigatório da uma lida antes de começar a estudar, seguindo os caminhos citado, uma hora ou outra o gafanhoto irá ter conhecimento que existem outras tecnologias que pra ele pode ser interessante.

**Comment by klarkc** [comment]
Uma boa fonte que eu uso para traçar metas de longo prazo é o https://stateofjs.com/, no último relatório (deste ano) eles fizeram um gráfico de [correlação de tecnologia, quase um mapa](https://2018.stateofjs.com/connections/), do que você pode estudar além da tecnologia alvo.

**Comment by LFeh** [comment]
[A Recap of Frontend Development in 2018](https://levelup.gitconnected.com/a-recap-of-frontend-development-in-2018-715724c9441d), vale a leitura.

Fiz uma [tradução livre](https://twitter.com/LFeh/status/1072838228267462657).

- WebAssembly começa a ser mais aproveitado
- React continua lider, mas Vue e Angular vão crescer
- O CSS-in-JS pode se tornar o padrão em vez de CSS simples
- Desempenho continua no foco de desenvolvimento
- PWAs e code splitting se tornam norma
- PWA mais nativos e com mais recursos em experiencia desktop/mobile 
- Crescimento de frameworks e ferramentas de CLI, abstraindo partes tediosa na criação de apps
- Devs concentrados na produção de recursos
- GraphQL aumenta adoção e passa a ser utilizado em mais empresas
- Mais empresas adotando soluções mobiles com base de código unificada, como React Native ou Flutter
- Conteinerização (Docker, Kubernetes...) mais predominante no desenvolvimento frontend
- TypeScript começa a ser opção em relação ao JavaScript padrão
- Realidade virtual avança com libs como A-Frame, React VR e Google VR
