### ISSUE TITLE
Não é possível devolver o projeto da versão 4.21.1 para 4.19.2

### ISSUE THREAD

**Issue by asfe-0k** [frontendbr/forum#1309]
Eu estou tentando voltar da versão 4.21.1 para a 4.19.2 devido ao bug de replicação extrema no modo multiplayer, bugs na malha mover na janela de exibição, então eu instalei a versão 4.19.2 e fui no visual studio 2017 e recompilei o projeto, mas agora quando eu abri-lo eu não posso carregar qualquer nível e nenhum plano, então eu tentei desfazer o processo, retornando a 4.21.1 e agora uma mensagem de aviso aparece na versão 4.21.1: (extensão desconhecida .uasset) I tentei criar um projeto em ambas as versões e arraste os arquivos para eles, mas agora todos os blueprints não são mais reconhecidos em nenhuma versão.

**Comment by asfe-0k** [comment]
<span class="IssueLabel d-inline-block v-align-middle" style="background-color: #bfe5bf;">
  <a class="lh-condensed-ultra" href="/frontendbr/forum/labels/Acessibilidade" style="color: #000000;">Acessibilidade</a>
</span>

**Comment by LFeh** [comment]
Recomendo postar no @backend-br
