### ISSUE TITLE
Carreira Front End

### ISSUE THREAD

**Issue by woliveiras** [frontendbr/forum#132]
Galera, quero fazer um compilado sobre Carreira Front End [nesse repositório](https://github.com/woliveiras/front-end-career).

1 - Primeiro preciso identificar quais os requisitos (técnicos) para os diferentes níveis:

* Júnior
* Pleno
* Sênior

É sempre complicado falar de carreira Front End devido a diversidade relacionada com Design e Desenvolvimento de Software (o tal do Engineer). Quero tentar colocar por essa separação também.

2 - Em seguida vou adicionar as diferentes formas de contratação:

* CLT
* PJ
* Outra que tiver

3 - Depois vou listar alguns sites de Jobs na área.

Gostaria de saber a opinião de vocês quanto a esses assuntos para enriquecer o conteúdo que vou listar no repositório.
Quem puder compartilhar alguns links de apoio para tal, eu fico mais que contente pela ajuda!

**Comment by danilovaz** [comment]
@woliveiras Acho super válido cara!

**Comment by woliveiras** [comment]
Valeu mano! :D

**Comment by LFeh** [comment]
#32 \o

**Comment by Marcelosilva10** [comment]
:) tamojunto!
