### ISSUE TITLE
Favicon no Netlify

### ISSUE THREAD

**Issue by igorpinhh** [frontendbr/forum#1322]
Pessoal tenho um site teste no netlify bem normal, porém n consigo adicionar um favicon ao site.
Funciona normalmente no arquivo local, mas não funciona quando coloco no ar, alguém o que pode ser?
link: https://igorpinhh.netlify.com/

**Comment by luizbills** [comment]
Aqui está com favicon

![image](https://user-images.githubusercontent.com/1798830/50308755-6304da00-0483-11e9-861b-9f7afbfef7e8.png)

**Comment by LFeh** [comment]
Aqui ta com favicon também, você deve ter guardado cache de algum favicon quebrado hehe

**Comment by igorpinhh** [comment]
@LFeh era isso mesmo, obrigado!!!

**Comment by kaiossoares** [comment]
> Aqui ta com favicon também, você deve ter guardado cache de algum favicon quebrado hehe

Estou com o mesmo problema, como posso resolver o problema do cache?
