### ISSUE TITLE
Iniciando a carreira como engenheiro de software

### ISSUE THREAD

**Issue by emersonlopxs** [frontendbr/forum#1330]
Boa noite pessoal! 

Bem, eu começei a aprender programação no fim de 2016 e hoje me considero um desenvolvedor junior, embora ainda duvide das minhas habilidades.

Eu sei Javascript, CSS/Sass, HTML5, React, Node, Mongo, SQL e algumas outras coisinhas. O que importa é que eu sei construir coisas, talvez não da melhor maneira ou mais rapidamente mas eu sei.

No meio do ano eu comecei o curso de Sitemas de Infomação em uma universidade publica, nesse mesmo periodo eu consegui meus primeiros jobs como freelancer. 

Eu trabalhei como freela pra uma empresa durante uns 6 meses, e terminei 2 projetos, no último eu não tava trabalhando tantas horas por semana e eles resolveram terminar o contrato. Na real eu não tava trabalhando tanto porque me sentia cansado e muitas das vezes não entendia o codigo (que outro desenvolvedor escreveu) e tbm estava no fim do semestre na universidade.

Eu peguei algums outros projetos no upwork tbm, mas bem mais simples. Sempre que eu tento aplicar para novos projetos eu consigo algumas entrevistas mas não passa disso (as vezes por falta de experiencia ou por não poder trabalhar 30+ por semana). O que eu tiro disso é que eu sou bom o suficiente para conseguir chegar nessas entrevistas.

Então, por que eu to falei tudo isso? 

Eu não necessariamente preciso trabalhar agora, mas tenho o feeling que seria legal para minha carreira. Por outro lado tem a universidade, em que materiais relacionadas a programação, por enquanto, são tranquilas para mim, só levo pau em matematica e no mundo js tem sempre um monte de coisas novas para aprender. 

O que vcs me aconselham a fazer? Me dedicar mais aos estudos, tanto na universidade quanto sozinho, fazendo projetos pessoais e tals para aprender mais a fundo sobre programação ou meter as caras no mercado e construir projetos reais (se eu conseguir algum) ?

Ps: Como eu disse eu me sinto confiante com js mas ainda bate o sentimento de que eu não sou tão bom, eu senti isso especialmente quando eu tava trabalhando, mas tbm sentia que eu era foda quando conseguia fazer algo.

E aí? Estudar? Trabalhar? Projetos pessoais ? Fazer os 3 ao mesmo tempo?

**Comment by camillodev** [comment]
Se você não consegue trabalhar mais de 30hs por semana e ta fazendo faculdade, foca nas vagas de estagio e dependendo do periodo rola trainee também. 
Além disso você citou que as vezes não se acha bom o suficiente. Da uma olhada nesse [post aqui](https://willianjusten.com.br/sou-bom-o-suficiente/) do @willianjusten . 
Ele também fez um [post ](https://willianjusten.com.br/coisas-que-eu-nao-sei-em-ti/) recentemente falando das coisas que ele não sabe, e acho que é um otimo complemento. 

Sobre conseguir chegar até as entrevistas, significa que seu curriculo ta bom, agora foca em se preparar para as entrevistas. Qual parte que você não passa, na conversa com RH, nos testes tecnicos? E foca mais nisso. Tem um curso gratuito da Udacity de [preparação para entrevistas de Front End](https://www.udacity.com/course/front-end-interview-prep--ud250)
