### ISSUE TITLE
Engenharia de Software adicionada ao CONFEA e regulamentada pela resolução 1100

### ISSUE THREAD

**Issue by teyman1341** [frontendbr/forum#1332]
Finalmente, nós engenheiros de software, temos um conselho federal para resguardar nossos direitos profissionais, e separar o joio do trigo.
Nunca foi justo para nós engenheiros de software disputar empregos com profissionais aventureiros, a maioria sem faculdade, com comportamento ridículo e agressivo, do tipo "diploma não vale nada, criação de software deve ser livre", e outras baboseiras mais.

**Comment by teyman1341** [comment]
Não vejo a hora de ir ao CREA me registrar, e tomara que as fiscalizações comecem o mais rápido possível, visando afastar profissionais que enganam empresas e a sociedade.

**Comment by luizbills** [comment]
Sai dessa, colega. A única mudança vai ser a mensalidade que você vai pagar pro crea. E, caso você não saiba, isso nunca trouxe benefício nenhum para os engenheiros.

**Comment by teyman1341** [comment]
Luiz, digo o contrário, entra nessa.
Foi só eu terminar o curso, já estão chovendo propostas boas, inclusive do exterior.
Verifica em sites de empregos, como o trabalhabrasil.com.

Eu trabalhava como analista de sistemas nos EUA, com um terço do salário de engenheiros de software americanos. Fiquei com raiva disto, e para fazer os cursos lá saia muito caro, voltei pro Brasil, só para fazer o curso de Eng Soft, e valeu muito a pena.

Eu já sabia desde 2017 que Engenharia de Software seria incluída no CONFEA entre 2017 até 2019.

**Comment by onlurking** [comment]
@Mendrone, @LFeh, não sei se vocês acompanharam de perto a thread sobre [regulamentação](https://github.com/frontendbr/forum/issues/1207), mas acredito que o @teyman1341 está ferindo os 3 pontos da [COC](https://github.com/frontendbr/forum#c%C3%B3digo-de-conduta).

**Comment by teyman1341** [comment]
onlurking, não sei de onde imaginas isto, neste forum estou comemorando uma decisão de um conselho, visando proteger a sociedade, os profissionais verdadeiros e a informa´tica em geral.
O que queres? jogar pedra no CONFEA, por ter adicionado uma engenharia? Então vá e faça, se tem alguém ferindo totalmente a conduta, é você.
Mas fique tranquilo, este forum serve para comemoração, conscientização.
Conscientize-se que as coisas mudaram, e Engenharia de Software pertence agora ao CONFEA.
Graças a Deus.
