### ISSUE TITLE
.

### ISSUE THREAD

**Issue by NicholasKuchiniski** [frontendbr/forum#1337]
Na opinião de vocês, vale mais a pena fazer uma faculdade pública por causa do peso no diploma ou uma faculdade particular, reconhecida, como a FIAP, por causa do networking e das metodologias ?

As instituição de ensino que eu tenho em minha lista são:
- USP
- FIAP

Dessas opções, qual irá me trazer melhores oportunidades profissionais (não só no quesito de arranjar emprego, networking e convivência com pessoas da área pra mim é o mais importante) ?

**Comment by lhbzr** [comment]
Eu fiz Sistemas de Informação na FIAP e trabalhei lá como Front End até o ano retrasado cuidando de toda a parte de Front End dos produtos deles.

Acho que isso vai depender do que você quer para a sua carreira, se o seu foco for 100% Front End Development tanto faz de qualquer uma que você escolher, porque de qualquer forma 99% do que você aprender vai ter que ser correndo atrás sozinho de qualquer forma.

A FIAP é uma ótima faculdade, mas para mim em outras áreas, em relação a Front End eu não aprendi absolutamente nada mesmo. Pelo menos no meu curso, as aulas eram bem "HTMLzinho", "CSSzinho" e nada de JavaScript at all, só tive no 1º ano uma matéria relacionada a Front End que era tipo "Desenvolvimento Web e Games", no resto do curso vai ser só C#, Java e as paradas de gerenciamento e etc tipo COBIT, PMP e etc.

Já no curso de Tecnólogo de Análise e Desenvolvimento de Sistemas é um bem diferente, pelo que eu lembro tem muito mais matérias focadas em Front End e eu lembro de um professor falando que ensinou Angular, Node e mais umas paradas assim. O problema é ser um tecnológo e não um bacharel.

Qualquer coisa mais específica que você quiser saber só avisar! 😄

**Comment by GuilhermeLessa** [comment]
Mais ou menos isso que o @lhbzr. Faculdade não vai te garantir ser um bom desenvolvedor por exemplo, isso depende do seu empenho em correr atras, meter a cara na frente do PC e estudar. A faculdade so serve pra ter o diploma mesmo. Mas isso vale mais para a area técnica né, depende o que você quer.

**Comment by lhbzr** [comment]
Exatamente o que o @GuilhermeLessa falou, os melhores desenvolvedores que eu conheço em WebGL fizeram: UFPR, PUC e UNIP. 😂 Uma outra coisa que é bom de frizar é que para trabalhar fora do Brasil, é mais fácil de conseguir Visa com uma faculdade do que sem.

**Comment by deppbrazil** [comment]
## Meu ponto de vista, 😃 ##
> #### Sou formado em Design pela Unip e no 4º ano de Engenharia de Computação na Anhanguera ####

### Sobre faculdades ###
> Faculdade é bom para você desenvolver outras habilidades como: comunicação, apresentação de trabalhos, trabalhos em grupos, network com professores da área, em questão de conteúdo ainda vivemos em modelo de educação de 200 anos atrás voltados completamente para área acadêmica e não para o mercado de trabalho

### Em questão de conhecimento técnico ###
> Melhor fazer cursos de especialização como: Alura, Udemy, Cousera, Udacity, etc.... 

### Em questão de networking e mentoria ###
> É muito importante participar de comunidades no Github, Slack, Discord, e também ser ativos no Github e Stackoverflow

### Sobre trabalhar em outro País ###
> Neste ponto se você tem um Bacharel isso ajuda pois há 2 formas de comprovar experiência no exterior, ou graduação (que contam a cada 1 ano 3 de experiência) ou 10 a 12 anos de experiência na área sem graduação, então se você não tem um Bacharel e quer trabalhar no exterior terá que comprovar uma baita experiência, pelo menos foi que aprendi nesse podcast - [Carreira de programação no exterior](https://hipsters.tech/carreira-de-programacao-no-exterior-hipsters-69/)

**Comment by NicholasKuchiniski** [comment]
> mas para mim em outras áreas, em relação a Front End eu não aprendi absolutamente nada mesmo. Pelo menos no meu curso, as aulas eram bem "HTMLzinho",

Obrigado pela resposta cara, e parabéns, os sites da FIAP são insanos!. Não mencionei no tópico, mas já trabalho na área tem uns 2 anos e ja tenho um conhecimento bem avançado de javascript, então para mim, oq eles vão ensinar durante o curso todo, muito provavelmente eu já séi. Eu estava mais interessado na parte de gestão e documentação dos sistemas (a área mais relacionada a engenharia de software, o curso que vou fazer na usp ou na fiap é SI) então acredito que não vai ser o problema o fato de eles ensinarem só o básico.

> Mais ou menos isso que o @lhbzr. Faculdade não vai te garantir ser um bom desenvolvedor por exemplo, isso depende do seu empenho em correr atras, meter a cara na frente do PC e estudar. A faculdade so serve pra ter o diploma mesmo. Mas isso vale mais para a area técnica né, depende o que você quer.

Obrigado pela resposta, praticamente a mesma coisa que eu respondi acima. Eu sei que faculdade não da emprego. Estou mais interessado no networking que posso criar e nas metodologias que a faculdade vai me proporcionar para o aprendizado de determinadas matérias.

> duação (que contam a cada 1 ano 3 de experiência) ou 10 a 12 anos de experiência na área sem graduação, então se você não tem um Bacharel e quer trabalhar no exterior terá que

Obrigado pela resposta, justamente isso que eu busco em uma faculdade mesmo.

**Comment by lhbzr** [comment]
@NicholasKuchiniski, muito obrigado! Atualmente é outra equipe que está tocando as coisas por lá, mas ainda tem alguns pedaços remanescentes na parte institucional. 😄

Nessa parte de Engenharia de Software com toda a certeza a FIAP é bem mais superior a USP mesmo, e se você levar o TCC (Startup One) a sério você também tem chances de criar um produto interessante que atraia investidores no final do curso, pois a faculdade em si tem bastante foco em formar empreendedores e funcionários para grandes empresas. O único problema é investir os quase 1.800 reais que a mensalidade da FIAP custa, como eu era funcionário eu tive uma bolsa integral enquanto eu estava lá. 😅 

Acho que o maior problema com a USP é que a grade é bem obsoleta e você vai encontrar umas matérias bem random mesmo, mas tem empresas que ~geralmente~ só contratam pessoas formadas em federais por causa da base teórica.

**Comment by ninetails** [comment]
Não recomendaria USP (IME/Poli) caso seu foco esteja em trabalho e network na nossa área (frontend).

Porém desconheço o curso de Sistemas da Informação (EACH-USP) ou alguém que tenha feito.

**Comment by NicholasKuchiniski** [comment]
> Esse ano começo a estudar na FIAP vou fazer Sistema da informação

@silvaMatheus Eu também cara, vou fazer na aclimação (acho que só tem lá), quem sabe "nois se cruza"

**Comment by rogerpolvr** [comment]
"O problema é ser um 'tecnológo' e não um bacharel." , disse o colega. 

Não tem problema nenhum você ser tecnólogo, aliás, hoje em dia não tem problema nenhum em você não ter um diploma. O que importa é quem você é como ser humano e o quão aberto você está para conhecer pessoas e absorver conhecimento.

Eu terminei meu primeiro ano na FIAP em 2018, estou cursando ADS EAD pq moro em Porto Alegre. O material e a metodologia de ensino são muito bons. O primeiro ano foi focado em Web, a gente desenvolveu vários projetos (o curso é bem hands on, estilo "from zero to hero") e atuamos em todas as roles de um time, inclusive nas partes gerenciais, contudo, na maioria do tempo você fica como desenvolvedor Fullstack. Então se você já desenvolve e quer algo que vá direto ao ponto recomendo para FIAP, caso você queira seguir uma carreira mais focada em pesquisa e desenvolvimento, recomendo ir para uma federal por conta do background cientifico. 

Mas nada é regra, até pq eu estudo na FIAP e trabalho com pesquisa ;)

**Comment by lhbzr** [comment]
> "O problema é ser um 'tecnológo' e não um bacharel." , disse o colega.
> 
> Não tem problema nenhum você ser tecnólogo, aliás, hoje em dia não tem problema nenhum em você não ter um diploma. O que importa é quem você é como ser humano e o quão aberto você está para conhecer pessoas e absorver conhecimento.

Ok, deixei uma brecha para essa frase ser mal interpretada. O que eu quis dizer com "problema" é que caso você tenha interesse em trabalhar nos Estados Unidos, o processo de conseguir um visto H-1B fica um pouco mais complicado, pois para esse visto em específico é necessário ser formado em bacharel, tecnólogos nesse caso não poderiam e teriam que provar experiência na área equivalente. É isso.

**Comment by rogerpolvr** [comment]
> > "O problema é ser um 'tecnológo' e não um bacharel." , disse o colega.
> > Não tem problema nenhum você ser tecnólogo, aliás, hoje em dia não tem problema nenhum em você não ter um diploma. O que importa é quem você é como ser humano e o quão aberto você está para conhecer pessoas e absorver conhecimento.
> 
> Ok, deixei uma brecha para essa frase ser interpretada como fazer tecnólogo ser algo negativíssimo, desculpe. O que eu quis dizer com "problema" é que caso você tenha interesse em trabalhar nos Estados Unidos, o processo de conseguir um visto H-1B fica um pouco mais complicado, pois para esse visto em específico é necessário ser formado em bacharel, tecnólogos nesse caso não poderiam e teriam que provar experiência na área equivalente.

Sim, você está correto, neste caso você tem que compensar os "anos restantes" com experiencia no mercado, porém dificilmente alguém vai fazer um tecnólogo aqui e ir direto pros estados unidos. O que eu quis dizer é que, bom, a gente tem que quebrar essa cultura que algumas empresas ultrapassadas ainda tem aqui no Brasil.

Se a Google retirou a graduação dos requisitos mínimos de suas vagas, quem é a fabrica de software lá da cidade de Joãozinho da Serra pra exigir alguma coisa? Além de que (No Brasil) Tecnólogo tem o mesmo nível de Bacharelado e Licenciatura. Pelo que me recordo existe uma confusão em relação o grau, algumas pessoas pensam que Graduação Tecnológica é tipo  Associate degree que é uma graduação de 2 anos que existe lá fora, porém, o equivalente ao tecnólogo é o Bachelor of Technology, que é um curso de 3+ anos, focado em hands on.

Por favor, podem corrigir qualquer informação errada. Obrigado.

**Comment by didiraja** [comment]
> Se a Google retirou a graduação dos requisitos mínimos de suas vagas, quem é a fabrica de software lá da cidade de Joãozinho da Serra pra exigir alguma coisa?

Cara, eu concordo plenamente, mas na vida real não é assim, infelizmente. Todas as empresas que passei, o diploma (independente da área) era pré-requisito não-oficial pra ingressar. Todas as entrevistas que fiz antes do emprego atual diziam a mesma coisa. Inclusive, patrão adora usar isso como desculpa pra não promover ou pagar menos alguém.

Hoje mesmo tive uma conversa parecida no almoço, enquanto Pós não é exigida para vagas (até agora nunca vi isso, mas nunca fui pro alto escalão de TI) eu não vejo a menor necessidade de ter formação. Nem na nossa área, nem em design. Essas outras graduações pra mim só fazem sentido no âmbito acadêmico.

A fábrica e software lá da cidade de Joãozinho da Serra é antiquada e não tá nem aí pro Google, por isso pedem diploma.

**Comment by deppbrazil** [comment]
# Aííí... #
Só colocando meu ponto de vista sobre a parte do @rogerpolvr e @didiraja de quando mencionam a Google em comparação a fábrica de software lá da cidade de Joãozinho da Serra, 

Assim, tendo em vista que empresas nesse nível tem um peso de marca muito forte no mercado no qual todos os devs, desginers, etc sonham em trabalhar lá, então elas ditam a tendência, ou seja por mais que elas não exijam formação acadêmica o processo seletivo é bem fodão e digo bem fodão mesmo e um ponto muito importante é a cultura, não adianta vc ser um dev fodástico se não está alinhado a cultura e visão da empresa, acho que seria essa a mensagem que elas querem passar sobre "graduação" e não simplismente falar "ah foda-se a formação, vamos contratar agora galera sem diploma apenas que saiba fazer" então por mais que ela não olhe mais a graduação ela vai continuar contratando profissionais bons do mercado, falar tipo quem é a fabrica de softaware da cidade do Joãozinho para exigir alguma coisa acho meio injusto, pois essa fabrica de software não tem o mesmo poder de atração de uma Google, não tem o mesmo processo seletivo e cultura e talvez para o essa fabrica de software faça sentido sim ver a graduação, tudo vai do modelo de negócio não podemos generalizar tendência de gigantes da tecnologia e meio que colocar como obrigação que a fabrica de software xpto seja igual e siga as mesmas diretrizes, 

Então na minha humilde opinião não faz muito sentido essa comparação!
# 😄 #

**Comment by SidneyyCesar** [comment]
Fala galera
desculpa ressuscitar o tema mas ele me foi útil e eu queria pode e enriquecer ainda mais o debate com uma dúvida.

Sou desenvolcedor e tenho 10 anos de carreira, gostaria de fazer uma pós para ter um overview mesmo do mercado e tudo mais.
gostaria de fazer FIAP ou PUC mas acho caro demais
aí pensei em fazer um EAD da vida em um SENAC mesmo.
5x mais barato rs

O que vcs acham dessa abordagem?

não acho q valha a pena investir quase 30mil em um curso q por mais que seja bom talvez não faça diferença alguma em questão de carreira futura

obrigado rapaziada !

**Comment by willycamargo** [comment]
@SidneyyCesar se ja é formado e não estiver focando em seguir carreira acadêmica eu recomendo cursos como [Alura](https://alura.com.br), [Frontend Masters](https://frontendmasters.com), [Coursera](https://www.coursera.org/) ou outros do tipo.

Acho que esses cursos serão mais focados na prática e te darão uma perspectiva mais próxima do mercado para o que for aprender.

Agora se for realmente necessário uma pós, também estou curioso para saber quais o pessoal recomendam.

**Comment by jezzipan** [comment]
Estudo ADS na FATEC e recomendo, tendo em vista que educação presencial e de qualidade esta se tornando um artigo de luxo, infelizmente. Provavelmente, na Fatec, os professores não vão te ensinar   frameworks e tendencias da moda ( e na boa, isso a pessoa aprende fazendo um nanodegree, cursos a parte), mas ali vc vai aprender os conceitos, como interpretar e analisar algoritmos e problemas, a interação entre sociedade e TI, escalabilidade e um dos poucos lugares em que vc pode conhecer e até aplicar algoritmos mais complexos.  É um curso mais rápido do que a USP e com uma excelente qualidade. 

Eu falo isso por estar envolvida com essa instituição. Empresas no Brasil ainda tem o pensamento mesquinho de avaliar e etiquetar a qualidade de um profissional por conta da sua instituição (se é de publica deve ser bom...zzZZ) Mas olhando as propostas que recebia antes e depois de ter esta instituição no me CV eu não abriria a mão do estudo formal jamais (por mais chato e sem sentido naquele momento que seja), até porque a maiorias dos DEVs que reclamam e acham inútil faculdade de TI curiosamente tem um diploma de formação na área. Bons estudos.

**Comment by marcelovelame** [comment]
O problema é o Brásil, aqui sempre querem pagar menos, qua tô menos melhor e quanto mais lucro melhor

**Comment by FerreiraCoder** [comment]
Galera desculpem fazer um "necro" no tópico mas vamos lá:
Conheço bem a Fiap, professores excelentes e aulas fenomenais.
Agora estou na Fatec (mesmo curso)  e embora a instituição tenha muito renome, as metodologias são maçantes e algumas vezes sem sentido, como comentado acima.
Estou entre uma e outra instituição, e mesmo sabendo que a Fiap é excelente para quem está começando gostaria de saber sobre se existe alguma negatividade em ter um curso feito numa instituição privada (Fiap) e tendo alguns certificados em Java (meu interesse) em relação a alguém que estudou numa instituição pública.
Sinto que na Fatec estarei perdendo tempo pois os conteúdos são muito defasados (Fatec SP)
Meu interesse não é pesquisa, quero ir pro back end e estou estudando por conta própria.
Valeu!

**Comment by eliseumds** [comment]
Vai depender das suas aspirações. Se quiser trabalhar num país mais restrito como os EUA ou Japão, um diploma é necessário em 99% das vezes. Ou se quiser seguir carreira acadêmica. Salvo isso, acredito que um curso técnico como FATEC ou algo online como Rocketseat, ou até um bootcamp se você puder pagar, vão te trazer mais retorno. Networking pode ser mais eficiente em grandes empresas e conferências, e até presença online.

Eu comecei na USP há uns 7 anos atrás mas larguei no terceiro semestre. Tava aprendendo mais na empresa. Não me arrependo. Consegui visto de trabalho na Alemanha e na Austrália.

@SidneyyCesar acabei de tomar café com uma amiga coreana que fez um bootcamp em San Francisco (a la Lamda School e LeWagon) de uns 3 meses, gastou uma bela grana financiada mas pagou de volta em somente um ano e hoje faz mais de 100k dólares por ano em Sydney.

@marcelovelame esse hate ao Brasil não colabora com a discussão. Coloque-se no lugar dos empresários de vez em quando. A verdade é que a qualidade da mão-de-obra é muito baixa, na média, e a complexidade logística e do nosso sistema tributário é insana. Há empresas que pagam bem, mas elas vão pagar bem se verem que você vai trazer valor. É simples.

**Comment by danilosilvadev** [comment]
@eliseumds man sofro com isso. Eu tbm parei a faculdade e quero ir morar no exterior. Não quero EUA ou Japão por enquanto, aceito netherlands, england, Germany, qualquer um dos bons e velhos europeus. Foco em aprendizado por autodidatismo, e por mais que reconheça valor em faculdades(algumas) não queria gastar 4 anos da minha vida aprendendo algo que eu não decidi que vale realmente apena. Meu sonho é sair do Brasil, mas já tropecei nessas barreiras do não ter nível superior. Atualmente trabalho como sênior react e to na luta pra encontrar uma oportunidade que compreenda meu potencial, independentemente de ter o diploma ou não.

**Comment by eliseumds** [comment]
@danilosilvadev pelo que eu sei, ao menos na Alemanha, Holanda e Bélgica, é possível ter work permit sem diploma, mas vai depender principalmente da vontade da empresa. Se você for solteiro e tiver cartas de recomendação, melhor ainda. A Austrália tem um sistema de pontos e cinco anos de experiência contam como um diploma, e eles vão ligar pra todos os seus ex-employers, onde quer que estejam no mundo.

99% das pessoas falam merdas incorretas sobre vistos, de todos os tipos, então não deixe isso te desanimar. O melhor jeito é um bom advogado de imigração.

Boa sorte na sua jornada!
