### ISSUE TITLE
CPBR12 - Campus Party

### ISSUE THREAD

**Issue by NicholasKuchiniski** [frontendbr/forum#1340]
Olá a todos, tenho planos de ir na CPBR12 e gostaria se possível de participar de um hackaton, tenho 17 anos e sou emancipado. Lendo regulamentos antigos a parte onde diz que só pode se inscrever quem tem 18 anos é bem clara, alguém sabe se para todos hackatons isso é uma exigência ?

**Comment by ninetails** [comment]
Creio que o melhor lugar pra perguntar seria diretamente à organização por um canal oficial.

Caso quiser um canal mais informal, tenta no grupo do Facebook. Geralmente tem mais "Staffs" (voluntários do evento) lendo por lá, alguém pode avisar alguém de conteúdo ou mídias sociais também... Também tem o [Twitter deles](https://twitter.com/campuspartybra) que parece ser bastante utilizado e pode ter uma resposta rápida.

**Comment by Juuhz** [comment]
@NicholasKuchiniski,

Eu tive alguns problemas no meu ingresso e mandei e-mail para:
help@campus-party.org

Eles me responderam bem rápido, no mesmo dia consegui resolver meu problema. 

Abraços.

**Comment by LFeh** [comment]
@NicholasKuchiniski Mantém as dúvidas da CP desse ano na issue #1334 :)

**Comment by NicholasKuchiniski** [comment]
Continuando em #1334
