### ISSUE TITLE
Principais eventos de tecnologia 

### ISSUE THREAD

**Issue by vNNi** [frontendbr/forum#1347]
Na opinião de vocês quais são os melhores eventos de tecnologia nacionais e internacionais?
Levando em conta: 

- Conteúdo das palestras (se tiverem); 

- Estrutura;

- Local;

**Comment by rsmelo92** [comment]
A Jusbrasil tem um repositótio de eventos, tem alguns interessantes já mas estão sendo adicionados mais aos poucos, quem quiser pode cotribuir tb
https://github.com/jusbrasil/tech-calendar

**Comment by rodineicosta** [comment]
@rsmelo92, enviei um PR no repo do JusBrasil com informações do **FLISOL Castanhal 2019**, que ocorrerá em abril no estado do Pará.

**Comment by erickmajor** [comment]
Poderíamos aproveitar o comentário do @vNNi e criar um calendário unificado (Google Calendar, p.ex.) de eventos da área de programação.

O que acham?

**Comment by isacmoura** [comment]
@erickmajor acho uma boa. Bem mais prático, ao meu ver. Podemos unir as informações dos repositórios desta issue num só Calendar.

**Comment by LFeh** [comment]
Dentro do @frontendbr temos uma página de [eventos com a temática Front-end](https://eventos.frontendbr.com.br)
