### ISSUE TITLE
Dicas de sites e métodos para aprender inglês?

### ISSUE THREAD

**Issue by Alexsandra127** [frontendbr/forum#1349]
Boa noite! 
Sabendo da importância de se aprender inglês, estou criando essa Issues. Estou estudando sozinha e fico perdida e confusa de como aprender um novo idioma. Por favor, mandem dicas e sites que vocês recomendam!

**Comment by onlurking** [comment]
Eu diria que o primeiro passo é aumentar o contato com a linguagem, mude o idioma do seu celular e computador para **inglês**.

Aplicativos que ajudam muito no começo é o [Duolingo](https://pt.duolingo.com/) e o [Clozemaster](https://www.clozemaster.com), recomendo fortemente instalar eles no celular e praticar.

Depois disso é acostumar a assistir vídeos, filmes, tudo o que for possível com **legendas**, no começo pode ser legendas em português, mas eventualmente é legal fazer a transição para lengendas em **inglês** e depois de um tempo tente assistir tudo sem legenda.

Uma ótima maneira de treinar é assistir algumas [TED Talks](https://www.ted.com/talks).

Sobre canais de desenvolvimento em inglês, eu recomendo alguns: [FreeCodeCamp](https://www.youtube.com/channel/UC8butISFwT-Wl7EV0hUK0BQ), [Crash Course](https://www.youtube.com/user/crashcourse/playlists?flow=grid&view=1) tem vídeos para todos os assuntos que você imaginar, o de computação é bem maneiro, [Luke Smith](https://www.youtube.com/channel/UC2eYFnH61tmytImy1mTYvhA) para Linux, [Derek Banas](https://www.youtube.com/channel/UCwRXb5dUK4cvsHbx-rGzSgw), [Fun Fun Function](https://www.youtube.com/channel/UCO1cgjhGzsSYb1rsB4bFe4Q) para Javascript, e o canal de [CS50](https://www.youtube.com/channel/UCcabW7890RKJzL968QWEykA) de Harvard tem bastante coisa de ciência da computação.

Quando você quiser treinar o **listening** na cara dura, eu recomendo consumir podcasts, tem alguns [ótimos de desenvolvimento](https://github.com/rShetty/awesome-podcasts) como o Software Engineering Radio, e o The Changelog.

**Comment by onlurking** [comment]
Já abriram algumas issues a respeito do inglês também: #838, #643, #478, #109
[e tem algumas dicas jogadas aqui](https://github.com/frontendbr/forum/issues/456#issuecomment-279579443) na issue #456

**Comment by mtsalcova** [comment]
Boas dicas @onlurking!! só acrescentaria na parte de treinar o **listening**, o Lyrics Training, site bem legal pra treinar o listening com letras de musicas: https://lyricstraining.com/

**Comment by ViniciusGularte** [comment]
Segue nas dicas do @onlurking  que você consegue, atualmente to focando todos meus estudos na pronuncia minha que era bem ruim, além de fazer mais ou menos o que o @Mendrone  disse, to usando um app chamado ElsaSpeak(Ele é pago, mas é barato) que corrige minha pronuncia em tempo real e diz aonde errei / aonde melhorar,  ele tem milhares de exercicios de conversação desde palavras simples a conversas  complexas, pra mim ele ta valendo muito a pena por te dar um roteiro completo .

**Comment by adrianoavelino** [comment]
Eu costumo acessar o https://www.free4talk.com/, lá sempre tem pessoas dispostas a conversar o site utiliza o seu usuário do Hangout (Google) para criar ou participar de uma sala.Tem até uma opção de criar uma Brand, o que não deixa as pessoas da sala ter contato com o seu perfil das redes sociais do Google. Tem também o Discord,  exatamente esse server: https://discord.gg/RtuAAmv, sempre tem alguma pessoa para falar no canal de voz e até mesmo no canal de texto. Também uso uma extensão para o chrome do site Linguoleo: https://chrome.google.com/webstore/detail/lingualeo-english-transla/nglbhlefjhcjockellmeclkcijildjhi?hl=pt-BR com ela eu posso adicionar as palavras que não conheço para estudar depois e até utilizar o seu dicionário para tradução e outros recursos mais. Gosto desse app: https://play.google.com/store/apps/details?id=com.toniferreirasantos.jscourse&hl=en_US  para estudar inglês com base em textos (listen, speaking e até writing com base nos audios).

**Comment by LFeh** [comment]
Linkando: #109 #643 #1185

**Comment by Alexsandra127** [comment]
Obrigada a todos pelas dicas!
