### ISSUE TITLE
Vou ganhar um macbook pro i7, vendo ou uso ?

### ISSUE THREAD

**Issue by romulosardinha** [frontendbr/forum#1350]
Um cliente meu me deve a um tempo, como trabalha com importação ele me pagou com um macbook pro i7 16GB 512GB SSD, sempre usei linux e pc, então ainda estou na dúvida se fico de vez com o mac e migro ou vendo...

vou ter realmente muita vantagem com um macpro? meu trabalho é focado em react, react native.

**Comment by lhbzr** [comment]
Como você trabalha com React Native, acho que seria uma ótima ideia começar a utilizar ele para desenvolver, pois você vai poder testar e gerar a versão iOS dos aplicativos com muito mais facilidade.

A diferença entre o Linux não é muito grande também, então acho que você vai se adaptar bem mais rápido do que imagina.

**Comment by fabianoschaefer** [comment]
Vende e investe a grana em um fundo de investimento de renda variável (Alaska Black por exemplo) ... 

Brincadeiras a parte, você poderia testar por uns dois meses o Mac pra ver se você se adapta ao SO. Se gostar mantém, senão passa pra frente.

**Comment by rmlSardinha** [comment]
@fabianoschaefer ai fico rico depois dos investimentos e viro empreendedor de palco ! kkk

**Comment by rmlSardinha** [comment]
@lhbzr to pensando nisso mesmo, esperando não levar um tranco grande com a mudança

**Comment by rmlSardinha** [comment]
@Juuhz hum... boa ideia essa ai de revenda né. ele não desvaloriza rápido.

**Comment by israelcena** [comment]
@rmlSardinha, Amigo,
Imagina que você é piloto profissional, e um cliente que lhe deve lhe da uma Ferrari como forma de pagamento. 
Você já tem um "Prisma" pra correr, mas agora tem uma Ferrari. 
Você vende a Ferrari porque você já corre super bem com o Prisma ou usa a Ferrari para correr mais e competir ainda melhor nas corridas ?

**Comment by rmlSardinha** [comment]
@israelcena  kkkk adorei a comparação, se chamar o team pc de usuários de prismas vai gerar hate kk

**Comment by vNNi** [comment]
Nunca tinha usado um mac, até ano passado... agora falo com muita certeza que é algo muito difícil de ficar sem e o mais importante, não é difícil de migrar!

**Comment by rmlSardinha** [comment]
@vNNi legal, esse tipo de experiência de causa que estou procurando, bom ... ele deve chegar daqui a duas semanas, vamos ver se vicio mesmo

**Comment by grsabreu** [comment]
Você vai fazer muito mais grana com o Mac do que a grana de vender ele, vai por mim. Melhor investimento que já fiz, tenho um Macbook Pro com as mesmas specs que as suas.

**Comment by rmlSardinha** [comment]
@grsabreu , esse hardware no mac rende mais do que o mesmo hardware em um pc ? ouvi falar isso, é verdade ?

**Comment by grsabreu** [comment]
é verdade @rmlSardinha , o gerenciamento de recursos e o próprio OS e tooling de dev para o Mac é infinitamente superior ao do Linux e Windows. As coisas apenas funcionam de primeira.
Eu não acreditava nisso tb até usar um Mac.

**Comment by israelcena** [comment]
Pessoal que critica os "produtos mac", em sua maioria, se dividem em dois grupos:

1. Os que nunca usaram 
2. Os que não criaram coragem ainda para investir em um (Dizem também que "não tem dinheiro").

**Comment by nandomoreirame** [comment]
Ótimo argumento @israelcena vou usar sempre kkkk

**Comment by onlurking** [comment]
Mac é um `BSD` de pelúcia, é unix-like o suficiente pra ter uma tooling de desenvolvimento absurda(capaz de competir com distros Linux de certa forma), e ao mesmo tempo é relevante o suficiente no mercado pra ter aplicações de escritório e design, como Office, Suite Adobe e o [Sketch](https://www.sketchapp.com).

Fora aplicações excelentes como [Things](https://culturedcode.com/things), [CodeKit](https://codekitapp.com/) e o [Alfred](https://www.alfredapp.com) com suas [integrações](https://github.com/zenorocha/alfred-workflows#alfred-workflows).

Ele tem o melhor dos dois mundos, entretanto eu particularmente nunca usaria um Mac por causa do sistema ser extremamente fechado e possuir uma assistência muito cara no Brasil(e sou meio paranóico com esse papo de [obsolescência programada](https://www.google.com/search?client=firefox-b-ab&q=apple+planned+obsolescence+lawsuit)).

É o que a galera falou aí acima, use ele por um tempo, se lhe atender melhor que teu notebook atual(com Linux) fique com ele.

**Comment by rmlSardinha** [comment]
@israelcena kkkk rapaz, o que tem de gente q me cerca que odeia mac kk, se eu falar q é pq nunca usaram vão me crucificar kk

**Comment by rmlSardinha** [comment]
@onlurking  pois é , essa semana isso será definido finalmente. se ocorrer tudo como quero posto a foto do setup
