### ISSUE TITLE
Código desenvolvido dentro da empresa

### ISSUE THREAD

**Issue by Juuhz** [frontendbr/forum#1351]
Pessoal,

Estou com uma dúvida trivial e gostaria de uma ajuda de vocês:

- Na empresa que estou, tinha um processo que demorava horas, coisa de 3 h para alguém já com experiência executar. Eu fiz uma automatização ( por conta própria ) que matava esse processo em 1 botão e você esperava 10m até o processo finalizar. 

- Essa automatização eu fiz por conta própria e usei meu tempo livre ( em casa ) e parte do meu tempo livre ( no job ).

- Atualmente estou me desligando da empresa e gostaria de saber ( em termos legais ):

1) Esse código é 100% meu, tendo em vista que utilizei um pouco do meu tempo livre no trabalho? 
2) Caso eu tire ele do ar, a empresa pode me cobrar? 

OBS: Os scripts estão hospedados no meu servidor pessoal, porquê a empresa não tem um próprio, isso foi sinalizado quando comecei o meu micro-serviço. 

Abraços.

**Comment by luizbills** [comment]
Geralmente no contrato de trabalho fala que tudo que você faz dentro da empresa é da empresa. Leia seu contrato de trabalho.

**Comment by onlurking** [comment]
* Tudo o que você faz dentro do ambiente de trabalho geralmente pertence a empresa, recomendo você entregar o código fonte do projeto a eles.
* Você pode desligar o servidor sim já que é você que mantém ele e não terá vínculo com a empresa, mas tem que ter um aviso prévio e possívelmente auxiliar eles(deixar uma documentação, etc).

Fazendo essas coisas creio que você não terá nenhum problema.

**Comment by rogerpolvr** [comment]
Você deve entregar o código fonte à eles, realizar uma breve documentação do mesmo e disponibilizar um período de tempo (15 a 30 dias) para que eles possam subir o próprio servidor, aí então você desliga o seu.

Eu não sei nada sobre leis, mas acredito que dialogando, essa seja uma maneira bacana para ambos os lados, mesmo que a experiencia na empresa não tenha sido legal.

**Comment by vagnerlandio** [comment]
Lembrei do caso que aconteceu na série de TV Silicon Valley, onde o protagonista trabalhava em uma empresa e durante as horas vagas ele estava criando um outro produto/startup.

Aconteceu uma vez dele utilizar um dos computadores da empresa para alterar um único bloco de código e essa alteração por ter sido feita nos computadores da empresa e em horário de trabalho, o código passou a pertencer a empresa.

Sei que a série é ficção, mas ela retrata problemas que os desenvolvedores passam na vida real e me fez refletir se em casos como este, a empresa ao invés de ter direito sobre todo o código, ter direito apenas de um 'diff' do código anterior com o código atual.

**Comment by expalmer** [comment]
Seja legal e responsável! Como os colegas disseram acima.
Não queime as pontes que você passou!
Seu nome será lembrado de forma positiva.

**Comment by Juuhz** [comment]
Pessoal,

Obrigado pelos insights, agradeço todos vocês <3.

**Comment by LFeh** [comment]
@Juuhz Prefere que eu exclua a issue?

**Comment by Juuhz** [comment]
@LFeh, por favor. Obrigado.
