### ISSUE TITLE
[Landing Pages] - Unbounce

### ISSUE THREAD

**Issue by LucasBSC** [frontendbr/forum#1352]
Olá, pessoal!

Tudo certo?

Estamos precisando fazer um site institucional para os produtos da empresa e gostaríamos de ter diversos subdomínios para cada produto. Gostaríamos de ter uma solução fácil de manipular e que possibilite acompanhamento de todo processo de Inbound Mktg.

Esbarramos nessa solução chamada **Unbounce**, que nos parece bastante completa, alguém já teve experiência com essa ferramenta? Entendemos que essa solução não envolve necessariamente codificação, mas de repente se alguém tiver experiência com landing page para inbound, gostaria de saber um pouco mais como é o processo.

Abraços!

**Comment by SrVieira** [comment]
Opa Lucas beleza?

Aqui onde trabalho utilizamos o Unbounce, é uma ferramenta bem interessante. Ela é basicamente uma ferramenta drag-in-drop para a criação das LPs/Campanhas, te permite também a criação de alguns scripts/js para manipulação da mesma. Ela é ótima caso também queira ter informações/métricas de acesso a suas LPS. Hoje nosso processo é o seguinte:

1 - Fazemos o desenho do Layout e dividimos tudo em layer;
2 - Colocamos cada elemento na página conforme layout;
3 - Publicamos a LP.

Outro ponto positivo é a possibilidade de criação de A/B Tests para suas Lps. Se for algo estático é uma ótima ferramenta <3

**Comment by LucasBSC** [comment]
Muito obrigado @SrVieira!

Bacana saber que está servindo para vocês. Devemos fazer o trial!

**Comment by tarciozemel** [comment]
Lembrando que há outras opções, tais como:

- https://instapage.com/
- https://klickpages.com.br/
- https://www.leadpages.net/
- https://www.launchrock.com/

E também algumas ferramentas mais completas de marketing que têm essa função embutida:

- https://www.activecampaign.com/
- https://www.campaignmonitor.com/
- https://pt.sendinblue.com/
- https://convertkit.com/
- https://www.getresponse.pt/
- https://www.sendx.io/

Dependendo das necessidades, de repente vale a pena considerar.
