### ISSUE TITLE
Primeiro layout solo

### ISSUE THREAD

**Issue by grsilva11** [frontendbr/forum#1358]
Fala pessoal!

A um tempo atrás postei uma dúvida de como inciar os estudos como front-end. Bom comecei a pouco tempo na Caelum e esse é meu primeiro layout, escolhi um mais simples, mas gostaria de saber como está o código.

Desde já, obrigado.
[pratica_layout.zip](https://github.com/frontendbr/forum/files/2801003/pratica_layout.zip)

**Comment by nathpaiva** [comment]
Olá @grsilva11, melhor do que colocar o `.zip` para download, é você subir or arquivos no `github`.

Caso você não saiba, esse curso pode te ajudar! [Curso de Git e Github](https://www.udemy.com/git-e-github-para-iniciantes/)
