### ISSUE TITLE
Primeiro Layout

### ISSUE THREAD

**Issue by grsilva11** [frontendbr/forum#1360]
Segunda tentativa... 😅

A um tempo atrás postei uma dúvida de como inciar os estudos como front-end. Bom comecei a pouco tempo na Caelum e esse é meu primeiro layout, escolhi um mais simples, mas gostaria de saber como está o código.

Desde já, obrigado.

https://github.com/grsilva11/grsilva11.github.io
https://grsilva11.github.io/index

**Comment by rafaelangical** [comment]
Faz deploy no heroku ou gh pages, fica melhor pra galera ver e dar feedback. Abraço.

**Comment by NicholasKuchiniski** [comment]
Escreva o nome das váriaveis css, nome de pastas e etc em inglês.

**Comment by nathpaiva** [comment]
parabéns @grsilva11 ficou bacana a estrutura!

Mas o que o @NicholasKuchiniski falou é verdade, tente se habituar a escrever os nomes em inglês, como no trabalho usamos assim, você se acostumando dessa forma vai se sentir mais a vontade quando tiver trabalhando em empresas.

**Comment by tapmorales** [comment]
Uia. Eu quase nunca entro nesse blog. Entrei pra ver se conseguia ajudar alguém e me deparo com o projeto que desenvolvi pro meu curso web Fundamentos.

Interessante kkkk. De onde vc pegou o modelo? Se não se importar em responder, claro!

Bom, com relação ao ingles que o @NicholasKuchiniski comentou. Eu ministrei javascript presencial e em uma turma ministrei pra um dos fundadores da totvs. E programa em sala de aula tudo em ingles e ele me falou algo que achei interessante: Quando voce ensinar uma linguagem nova especialmente para iniciantes, use nome de variaveis e funções em portugues, pois fica claro pra quem está começando o que faz parte da linguagem (ingles) e o que nao faz (portugues).
Desde então adoto essa estratégia especialmente para quem está no inicio da caminhada.

**Comment by grsilva11** [comment]
Obrigado pelo feedback!

@tapmorales Eu assinei o seu cursono Udemy, ai peguei esse primeiro layout pra fazer sozinho e depois ver como vc fez, mas queria um feedback. Desculpe qualquer coisa.

**Comment by tapmorales** [comment]
Opa. tranquilo @grsilva11 foi só curiosidade mesmo. Não há nenhum problema e não precisa se desculpar. Vc está certíssimo em praticar. E tb está certíssimo em querer feedback do pessoal aqui do fórum. parabens pela iniciativa. Prometo que vou olhar seu código com calma amanhã sem falta. Por hj já fechei a lojinha rs

**Comment by vNNi** [comment]
O código está muito clean, parabéns ! as tags estão bem usadas (<main>, <figcation>), continue assim, mantendo a semântica do HTML, coisa que hoje se perde muito !

**Comment by LFeh** [comment]
Fala @grsilva11, tudo bem?

Primeiro, parabéns por se colocar a disposição de um feedback. 

Vi que em outra issue, adicionou o .zip, e após dica da @nathpaiva você rapidamente aprendeu a subir os arquivos no Github.

Você fez bom uso das tags HTML, gostei. Vale adicionar um nome do `<title>` (agora está Dociment) e sempre manter suas classes em inglês.

Não se preocupe com técnicas e libs avançadas agora, indico pegar o layout de grandes portais, como a globo.com, e tentar "reescrever", é um bom exercicio.

**Comment by didiraja** [comment]
Ficou legal mano, mas é aquilo, se você tá preocupado com layout, procure se informar mais sobre design objetivamente e deixe o código pra viabilizar seu layout
