### ISSUE TITLE
Discussão: banco de dados client-side usando IndexedDB

### ISSUE THREAD

**Issue by GuilhermeLessa** [frontendbr/forum#1362]
Criei um pouco de código para automatizar e abstrair os dados client-side com IndexedDB usando Angular 7. Gostaria de opiniões para amadurecer os padrões e as funcionalidades.

https://github.com/GuilhermeLessa/AngularIndexedDBService

https://developer.mozilla.org/pt-BR/docs/IndexedDB

**Comment by adamfoerster** [comment]
Nunca usei IndexedDB mas parabéns pela iniciativa!
