### ISSUE TITLE
Utilizando o Credential Management API

### ISSUE THREAD

**Issue by raphaguasta** [frontendbr/forum#1364]
Pessoal! Tudo bem?

A [Credential Management API](https://developers.google.com/web/fundamentals/security/credential-management/?hl=pt-br) do Google parece bem legal, e vários sites já utilizam. Pra quem não conhece, vale dar uma olhada.

Finalmente resolvi testar essa WebAPI! Porém, estou apanhando de verdade pra fazer funcionar, ainda não consegui!
Aparentemente nem o [exemplo](https://developers.google.com/web/fundamentals/security/credential-management/save-forms) deles funcionou na minha máquina local.

Alguém já testou? Já fez um projeto pra valer? Sabem alguma peculiaridade que precisa ser configurada? Se alguém tiver um boilerplate, seria muito útil!! ;)

Valeu!

**Comment by joelson-c** [comment]
A API só funciona caso a pagina for disponibilizada utilizando HTTPS.

**Comment by luizbills** [comment]
@raphaguasta seja mais especifico... No que exatamente você está tendo problemas?

**Comment by raphaguasta** [comment]
@joelson-c Certo. localhost tbm né? Estou testando no local, deveria funcionar certo?

@luizbills Ao obter as credentials sempre recebo `null`. Para gravar, o `navigator.credentials.store` nāo dá erro, mas tbm nāo grava.

**Comment by raphaguasta** [comment]
@joelson-c Show!! Está habilitado aqui no chrome sim...

Vc tem algum boilerplate que funciona, pra eu descobrir qual o erro aqui??

**Comment by joelson-c** [comment]
Na hora que tu for criar a credencial tu vai ter que ao invés passar o formulário como parâmetro você vai ter que passar um objeto e nele tu vai poder especificar a URL do avatar (iconURL).

[Fonte](https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/create)

**Comment by raphaguasta** [comment]
@joelson-c Shoow. Mandou muito, obrigado!! :)
