### ISSUE TITLE
[Dúvida] [Estudo] Tabela não centralizando com o layout no dispositivo móvel

### ISSUE THREAD

**Issue by Tvitor** [frontendbr/forum#1365]
Amigos, estou criando essa issue porque criei um blog no github usando  um template Jekyll.  E aproveitei um botão do index para criar um menu utilizando uma tabela ( inseri ele 3 vezes numa tabela colocando cada um em `<td>` e cada botão com o seu  `<a href >`  )

Acontece que, no computador, o menu aparecia ok. Mas no celular, um botão subiu em cima do outro. Ou quando  coloco na horizontal, o botão sai do centro do layout.
Não tenho bom dominio de CSS ainda, podem me ajudar a resolver isso?

Apesar desse código da tabela ai capenga, já fiz de várias outras formas diferentes, e esse ai é apenas exemplo. Inclusive ja tentei por uma tabela dentro de outra maior e no css  usei magin 100% na primeira(absolute)

obs: não encontrei no forum e desculpe se caso tenha feito a issue de forma errada, é primeira vez hehe. 

link do codepen: https://codepen.io/tvitor/pen/BMpBZO
se preferir do github: https://github.com/Tvitor/tvitor.github.io
resultado: https://tvitor.github.io

**Comment by igorthurow** [comment]
Fala @Tvitor , tudo bem?

Na minha opinião, você poderia remover essa tabela, e utilizar Flexbox.

Coloca estes 3 botões dentro de um div com `display:  flex` e adicionar neste div o atributo `flex-wrap: wrap`. 

Acredito que resolve teu problema.

**Comment by Tvitor** [comment]
Era isso mesmo que eu precisava. Eu cheguei a tentar usar o display mas pelo visto ter tirado da tabela fez muita diferença. Vou focar em estudar um pouco esse conteúdo agora com calma. Obrigado @igorthurow , me ajudou muito!
