### ISSUE TITLE
Progressive Enhancement e Graceful Degradation

### ISSUE THREAD

**Issue by grodrigues** [frontendbr/forum#1370]
Boa Noite vocês utilizam os conceitos de Progressive Enhancement e Graceful Degradation nos projetos desenvolvidos ?

**Comment by grodrigues** [comment]
Estava lendo algumas coisas sobre css Cross Broswer e me lembrei desses conceitos de extrema em importância no desenvolvimento e o conteúdo que encontrei na internet estava com o ano de 2014, 2013 e ninguém mais falou nada sobre isso por isso fique com essa dúvida.

**Comment by evertonthepaula** [comment]
Eu costumo avaliar quais browsers o usuário final vai utilizar, e então deixo o trabalho duro para os pré-processadores, compiladores, transpiladores e geradores de bundle! :D

**Comment by gss-patricia** [comment]
Meu modus operandi é igual ao do @evertonthepaula :D

**Comment by LFeh** [comment]
Essa é a melhor abordagem mesmo @evertonthepaula
