### ISSUE TITLE
Serviço SMS no envio de formulário

### ISSUE THREAD

**Issue by goldsteinr** [frontendbr/forum#1375]
Olá pessoal.

Alguém utiliza algum serviço de envio de SMS que funcione apenas pelo front? Quando o usuário insere o número e confirma o form um SMS customizado é disparado.

Vi o serviço da [twilio](https://www.twilio.com/sms) mas gostaria de saber outra opções.

E como esconder no front, de forma segura, as keys utilizadas para o serviço?

obrigado!

**Comment by tcelestino** [comment]
Já fizemos um serviço de disparo de SMS utilizando o [Zenvia](https://www.zenvia.com/produtos/messaging/sms).

O API's deles é bem de boa para implementar e a disponibilidade é bem "estranha", já que eles garantem que não tem limites de _request_ para a API de disparo.

**Comment by goldsteinr** [comment]
Vou dar uma olhada neles!
thx
