### ISSUE TITLE
Dúvidas e bugs programação em C++. Programa básico

### ISSUE THREAD

**Issue by zilk0ne** [frontendbr/forum#1380]
Boa noite,
Meu objetivo era criar um programa que pegasse o preço e tamanho da peça e desse desconto sobre a mesma conforme tamanho.
porém tenho algumas dúvidas e bugs para sanar/corrigir.

Se eu digito o valor e qualquer uma das variaveis declaradas o programa funciona normalmente.
Porem quando eu digito "GG" que era pra ser uma variavel fora do scop o programa responde como fosse "g" pq o char capta apenas 1 variavel.
se eu digito uma variavel qualquer por exemplo "F" o meu programa nao demonstra valor final.
Não cheguei a testar com preço negativo.

#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

using namespace std;

int main(int argc, char *argv[])
{
    char tamanho;
    float preco;
    float P, p;
    float M, m;
    float G, g;

    printf("insira o preço da sua camiseta. E aperte ENTER. \n""Depois insira o tamanho da camiseta. P, M ou G. \n");
    scanf("%f\n" , &preco);
    scanf("%c" , &tamanho);

    P = preco - (preco * 0.3);
    M = preco - (preco * 0.2);
    G = preco - (preco * 0.1);
    
    if(tamanho == 'P' || tamanho == 'p'){
        printf("O preço da camiseta será de: %f\n", +P);
    }else if(tamanho == 'M' || tamanho == 'm'){
        printf("O preço da camiseta será de: %f\n", +M);
    }else if(tamanho == 'G' || tamanho == 'g'){
        printf("O preço da camiseta será de: %f\n", +G);
    }else{
        printf("Não temos descono para esse tamanho.\n O preço da camiseta será de: ", +preco );
    }
    system("pause");
    return 0;
}

**Comment by felipefialho** [comment]
Amigo, essa dúvida vai ser melhor atendida no @backend-br :)
