### ISSUE TITLE
Syntax error usando o Atlaskit (Atlassian) com o typescript

### ISSUE THREAD

**Issue by NicholasKuchiniski** [frontendbr/forum#1386]
Olá pessoal, tenho um [boilerpate](https://github.com/NicholasKuchiniski/typescript.app) em Typescript que me ajuda a criar aplicativos usando o próprio Typescript e o React.
Estou migrando (tentando) um [aplicativo](https://github.com/NicholasKuchiniski/leaf)  meu que é escrito em Javascript para o Typescript (além de melhorar o código, que é da época que eu estava no começo da minha jornada pelo javascript), porém estou tendo um problema ao implementar a bliblioteca que eu usava para construir o front-end.
A bliblioteca em questão é o [Atlaskit](https://atlaskit.atlassian.com/). O problema é que eu não consigo de jeito nenhum importar os componentes da bliblioteca e usar nesse meu [boilerpate](https://github.com/NicholasKuchiniski/typescript.app), sempre da um erro de unexpected token export, por isso creio que seja algo no babel e/ou webpack.
Não consigo de modo algum encontrar suporte para essa questão no google e nem no repositório oficial (pesquisei até em aramaíco) dai vim recorrer ao fórum.

Esse é o código de exemplo que eu aplico no arquivo index.tsx

```jsx
import * as React from 'react';
import Button from '@atlaskit/button';

export interface IndexProps {
}

export interface IndexState {
}

class Index extends React.Component<IndexProps, IndexState> {

  public render() {
    return (
      <div>
        <h1>Hello World</h1>
        <Button>Teste</Button>
      </div>
    );
  }

}


export default Index;
```

e esse é o erro que eu recebo

```javascript
Unhandled Rejection (SyntaxError): Unexpected token export
```

```javascript
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
```

```javascript
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
```

**Comment by felipefialho** [comment]
@willianjusten pode ajudar aqui?

**Comment by RatoX** [comment]
Opa eai @NicholasKuchiniski qual a versão do Atlaskit que ce tá usando? Pergunto isso por cause que tivemos um problema com as dist de uma versão especificas e não estavamos compilando para cjs só para es2015

**Comment by willmendesneto** [comment]
@NicholasKuchiniski provavelmente a versão que você está utilizando fez o drop do `CJS` no nosso bundle. Então vc vai ter que fazer algumas alterações na sua configuração do babel ou de webpack, rollup, etc. caso queira continuar utilizando este package.
E.G. https://babeljs.io/docs/en/babel-register#ignores-node-modules-by-default

Estamos usando ESM e ES2015 para os packages agora devido a algumas necessidades que encontramos nos nossos produtos.

**Comment by antoniopresto** [comment]
Tive um problema idêntico em um projeto e acabei caindo aqui. 
No meu caso um downgrade para o typescript 3.2 resolveu. 

Atlaskit é legalzinho no começo, mas depois de um tempo estou louco pra me livrar dele. Eles nem olham os PRs, não da pra personalizar sem gambiarra e muito menos tem github rs. Quem puder, se livre.

**Comment by antoniopresto** [comment]
Seria legal montar um espelho no github, só não sei das implicações legais, porque muita coisa está disponível no NPM mas não tem a licença publica ou usa pacotes fechados internamente.
