### ISSUE TITLE
O que vocês acham destes projetos visuais?

### ISSUE THREAD

**Issue by pedroguilhermelima** [frontendbr/forum#1387]
**Olá! Como estão?**

O que vocês acham destes projetos visuais?
https://pedroguilhermelima.github.io/

_**Quero saber a opinião de vocês para melhorar ou se necessário mudar certas coisas.**_  Utilizo issues, mas não achei resposta alguma para essa pergunta um tanto pessoal-profissional. 

_**Esses trabalhos são minha última seleção. Sou exigente nas questões: originalidade, esforço, criatividade, cor, código limpo, prazo para mim mesmo. É que apago e sempre volto com novos projetos tentando superar esses, outros.  Sou perfeccionista com alguns toques, rs.**_ 

Valeu, as pessoas que ajudarem ^^

**Sobre os projetos, Briefing**

> O primeiro projeto visual é uma logo pessoal com animação 'efeito: para frente, para atrás'. Essa logo foi inspirada em várias pesquisas e gostos.  A logo 'Ré.Lís' é para uma empresa fictícia do mesmo nome que compra e vende antiguidades. Ao mesmo tempo, concentra com o design moderno em sua loja, website. Já a logo 'Marcell' seria para um estilista famoso de mesmo nome. Deixando essas histórias de lado, o último projeto visual 'haiku' se refere a um projeto cultural. Seria usado para exibir, informar, procurar os principais poetas e poemas haicai. Não teria banco de dados seria só o arquivo .json.

**Comment by rubenmarcus** [comment]
Do ponto visual são bonitos, mas como desenvolvedor, não sei te dizer o que representa o que.

estou tentando refazer meu portfolio e identidade visual https://www.rubenmarcus.com/ , que foi feito em 2014, mas não tenho arrumado tempo. Espero que saia ainda no primeiro semestre desse ano!!

**Comment by pedroguilhermelima** [comment]
> Do ponto visual são bonitos, mas como desenvolvedor, não sei te dizer o que representa o que.
> 
> estou tentando refazer meu portfolio e identidade visual https://www.rubenmarcus.com/ , que foi feito em 2014, mas não tenho arrumado tempo. Espero que saia ainda no primeiro semestre desse ano!!

Valeu... vou pensar em algo novo. PS: São projetos visuais dentro da  linguagem WEB. Vou fazer algo de diferente... realmente, para desenvolver novos projetos e outras funções.

**Comment by pedroguilhermelima** [comment]
_**Pensamento/História dos projetos visuais**_
>  
Gosto de coisas simples que falam ou se conectam por si só. Alan Fletcher é um exemplo, minha referência para ótimos/bons trabalhos visuais.  Olha esses trabalhos feitos por ele ^^

**IoD, Reuters e V&A**
![logo](https://designersbrasileiros.com.br/wp-content/uploads/2011/03/alanfletcher-300x106.jpg)


_**Um outro exemplo e referência,  Sagi Haviv / Chermayeff & Geismar**_

**Sagi Haviv**
![logo](https://designersbrasileiros.com.br/wp-content/uploads/2011/03/sagihaviv-300x106.jpg)

**Chermayeff & Geismar**
![logo](https://designersbrasileiros.com.br/wp-content/uploads/2011/03/chermayeff-geismar-300x106.jpg)

> O que estou fazendo?
> Estou buscando compreender isso e traduzir para a linguagem WEB. Por isso, alguns projetos visuais não são para desenvolvimento e sim só para 'artes/beleza/estética' que é parte essencial de um bom Web Design.

**Comment by pedroguilhermelima** [comment]
> Do ponto visual são bonitos, mas como desenvolvedor, não sei te dizer o que representa o que.
> 
> estou tentando refazer meu portfolio e identidade visual https://www.rubenmarcus.com/ , que foi feito em 2014, mas não tenho arrumado tempo. Espero que saia ainda no primeiro semestre desse ano!!

Valeu... vou pensar em algo novo. PS: São projetos visuais dentro da  linguagem WEB. Vou fazer algo de diferente... realmente, para desenvolver novos projetos e outras funções. O que eu preciso para fazer algo tão bom, excelente, ótimo? Vi seus projetos e eles são incríveis. ^^

**Comment by rubenmarcus** [comment]
@pedroguilhermelima  eu não desenvolvi a parte visual da maioria, eu fiz só a parte de front mesmo. Acho que voce pode procurar referencias no behance, um desenvolvedor e ótimo ui/ux que acompanho é o @bukinoshita

https://www.behance.net/gallery/77335431/Discovery
https://www.behance.net/gallery/72960139/Campus-go-app-design
https://www.behance.net/gallery/77525503/Words-Match-App

Lá tem um monte como esses..

eu piro. Mas é muito trabalho. Ou vc faz o front ou vc faz o design. os dois leva muito tempo.

**Comment by pedroguilhermelima** [comment]
> @pedroguilhermelima eu não desenvolvi a parte visual da maioria, eu fiz só a parte de front mesmo. Acho que voce pode procurar referencias no behance, um desenvolvedor e ótimo ui/ux que acompanho é o @bukinoshita
> 
> https://www.behance.net/gallery/77335431/Discovery
> https://www.behance.net/gallery/72960139/Campus-go-app-design
> https://www.behance.net/gallery/77525503/Words-Match-App
> 
> Lá tem um monte como esses..
> 
> eu piro. Mas é muito trabalho. Ou vc faz o front ou vc faz o design. os dois leva muito tempo.

ok
