### ISSUE TITLE
Plataformas de teste A/B

### ISSUE THREAD

**Issue by goldsteinr** [frontendbr/forum#1389]
Olá.

Estou pesquisando algumas plataformas de testes A/B e formas de trabalhar com testes e gostaria da opinião de vocês.

- Utiliza alguém ferramenta de teste A/B? Qual?

- Como funciona o processo de testes na sua empresa? Como surgem as ideias e como elas são escolhidas?

Obrigado :)

**Comment by tcelestino** [comment]
Usamos o Google Optimize, que é bem completo. Se estiver usando todo o pacote Google (Google Analytics, Google Dataflow, etc...) a integração é bem legal. Mas também já foram usados o OptinMonster e o Instapage. Esses dois últimos, posso dizer que é bem "truncado" em relação ao Optimize.

Aqui existem muitos times (são vários de verdade rs) que fazem MVP de pequeno/médio/grande impacto, por isso é frequente ver intervenções em diversos produtos da empresa. O mais interessante é que no final (geralmente) quando os testes são finalizados, existe o compartilhamento dos resultados.

Também é preciso fazer algumas estrategias de como será distribuidos esses testes. Então, no Google Optimize você consegue otimizar bastante esse tipo de divisão, porém, existem outros casos que é preciso consultar informações nos bancos de dados (são milhões de usuários) e que ai precisa ser escrito "rotinas" para fazer sorteios desses dados para serem usados em ferramentas internas.

**Comment by goldsteinr** [comment]
@tcelestino Legal! Como fazem o levantamento de ideias para os testes? E como decidem qual ideia vai ser testada?

**Comment by tcelestino** [comment]
> @tcelestino Legal! Como fazem o levantamento de ideias para os testes? E como decidem qual ideia vai ser testada?

A empresa está adotando OKR, dai fica mais "simples" de entender os contextos de cada squad/time e definir quais serão as estratégias. Fazemos algumas dinâmicas a partir do _baseline_ do OKR no qual vão surgindo ideias. Depois, com a participação do pessoal de marketing, BA (business analytics) e BI decidimos quais as ideias possuem mais potencial de alcançar os _key results_. As que trazem maiores resultados e que possam ser testadas de maneira forma mais rápida é que atacamos. Às vezes nem precisa de desenvolvimento, já que podemos usar as ferramentas que citei e outras para prototipar a ideia, validar e depois ver se faz sentido incorporar ao negócio.

É um resumo, espero ter respondido. :crab:

**Comment by goldsteinr** [comment]
@tcelestino muito bom, cara!

obrigado pela resposta e atenção :)

**Comment by eduardojmatos** [comment]
Aqui no GetNinjas usamos o Abba.js pra fazer testes no client side
