### ISSUE TITLE
Trigger para o firestore, acessar uma subcoleção

### ISSUE THREAD

**Issue by MuriloRS** [frontendbr/forum#1396]
Olá a todos, estou tento criar uma trigger para quando for adicionado um documento em uma subcoleção do meu firestore através de uma cloud function.
Atualmente estou tentando fazer dessa forma, eu preciso que essa trigger pegue o momento em que um documento é adicionado dentro da colução filhos, que é uma subcoleção de users, porém dessa forma não está funcionando, alguém sabe o que está errado?

const functions = require('firebase-functions');
const admin = require('firebase-admin');

admin.initializeApp();

exports.payments_app = functions.firestore
    .document('users/{userId}/filhos/{filhosId}').onCreate(() => {
        // perform desired operations ...
 });

**Comment by adamfoerster** [comment]
se não me engano as funcionalidade de subcoleção do firestore só estão ativadas para a biblioteca JAVA por enquanto.

**Comment by MuriloRS** [comment]
> se não me engano as funcionalidade de subcoleção do firestore só estão ativadas para a biblioteca JAVA por enquanto.

Sabe onde posso ler sobre isso?

**Comment by adamfoerster** [comment]
Não encontrei a referência na documentação (talvez porque já implementaram). O formato seria:
db.collection('users').doc(userId).collection('filhos').doc(filhosId)
Mas enfim, sub-coleções ainda são desaconselhadas por não terem cascateamento de delete e por não serem visualizaveis quando consultamos o pai.
https://howtofirebase.com/firestore-sub-collections-2e23c998540d

**Comment by MuriloRS** [comment]
> Não encontrei a referência na documentação (talvez porque já implementaram). O formato seria:
> db.collection('users').doc(userId).collection('filhos').doc(filhosId)
> Mas enfim, sub-coleções ainda são desaconselhadas por não terem cascateamento de delete e por não serem visualizaveis quando consultamos o pai.
> https://howtofirebase.com/firestore-sub-collections-2e23c998540d

Valeuuu Adam.
