### ISSUE TITLE
Build Local vs Build Servidor

### ISSUE THREAD

**Issue by oguhpereira** [frontendbr/forum#1398]
Ola,

Gostaria de levantar uma discussão aqui, sobre fluxo de trabalho de um dev front.

Hoje em dias há mutos projetos front precisam dos "famosos build" :

`npm build`
`yarn build`

Enfim, atualmente vocês acham mais vantajoso, fazer o build local e subir para servidor ou deixar que o servidor faça o build?

**Comment by vitocaio** [comment]
Eu curto fazer Local, ai eu só entrego minha pasta Build no servidor, geralmente eu crio uma rotina que ja roda o npm run build e faz esse trabalho de jogar no servidor em um Jenkings por exemplo, pq se o servidor mudar, não corro o risco de ter q fazer tudo novamente.

**Comment by vNNi** [comment]
Em projetos de estudo e etc, eu faço local mesmo, menos arquivos no servidor, melhor, só a pasta de build, mas pra projetos além do estudo, ou pra subir em algum lugar mais bonitinho, da pra tentar usar alguma ferramenta de CI, que faz o build e o deploy pra você, tem umas free bem legais, gosto do [Travis](https://travis-ci.org/) !

**Comment by eduardojmatos** [comment]
Pensando em aplicações rodando em containers (docker), essa tarefa pode ser executada via RUN do Dockerfile, deixando que o “servidor” rode pra vc. Lembrando que o ambiente precisa estar igual ao seu, ou seja, não é má ideia rodar o Docker tanto na sua máquina como em produção :)

**Comment by ViniciusGularte** [comment]
Nos ultimos projetos meu estava usando o [Travis](https://travis-ci.org/) que posso deixar tudo automatizado, só dava o push pro repositorio do git e ele ja validava os testes e criava o build pro servidor, pra quem tem interesse deixo o [Link](https://docs.travis-ci.com) da docs dele(que é bem grande e detalhada)

**Comment by NicholasKuchiniski** [comment]
Servidor, assim sempre que tiver um novo push na master é só mandar ele executar o build novamente e entregar a nova versão
