### ISSUE TITLE
reviewreact

### ISSUE THREAD

**Issue by pedroguilhermelima** [frontendbr/forum#1403]
Aqui a gente comenta e se diverte com o Review React. É minha forma de contribuir com o grupo 

Já enviei um reviewreact, amanhã terá outro

**Comment by felipefialho** [comment]
Não entendi mano

**Comment by pedroguilhermelima** [comment]
Pessoal, gostaria de contribuir com o grupo seja entre iniciantes ou avançados por meio de um review_react sobre websites. Com isso, podemos comentar, sugerir ou reagir nas diferentes posições (mudanças) do desenvolvimento, design, frontend entre outros.


Exemplo, website: radioalternativa.org.br 

*Momento review*

Problema:
Layout quebrado. 

Causas/Descrição: 
1- Falta responsividade. 
2- Não é adaptável. 

Solução/Descrição: 
Boostrap ou qualquer framework que faça, melhore isso.

*Momento react*

Comentário:

 "Devemos melhorar a interwebs".  kkkk ( risos ) Isso parece aquele pão com muita coisa dentro que fica sobrando pelos lados. Daí você tenta dar uma mordida na lateral e cai. Na outra, também. Daí tem que usar os dedos ou uma colher para comer o que caiu do prato.



Exemplo, website: brasilvexado.com.br 

*Momento review*

Problema: Cor.

Descrição: 
Verde não combina com amarelo e vermelho. 

Causas:
Onde esse problema é visto? Resposta: Colocaram a identidade visual "logo" num banner verde.

*Momento react*

Comentário:

Verde tá sem graça, fora de moda. Até parece que o Brasil Vexado faz comida ecológica. 

Exemplo, site:
pediaki.com.br

*Momento review*

Problema: 
Falta funcionalidade nos sections.

Descrição: As áreas com  content "contéudo". Por exemplo, 

1- "Veja esses restaurantes".
2- "Escolher o prato". 
3- "Pagar o produto".  
4- "Escolher opção, prato".
5- "Acompanhar o pedido". 

Observação
São textos com ícones referentes. 😁  

Efeito/Causa:
Pela falta de interatividade  1- Os novos usuários podem antes de fazer o login, acompanhar o pedido ou cadastro deixar de lado.

Nota
Você precisa voltar ao topo da page "página" pra isso. É "non-sense" "sem noção" por causa que o cliente deseja que o website seja igual ao App. Afinal, pode usar o notebook ou pc  pra isso. 

*Continuação* 

Nessa parte... pediaki.com.br /cliente 

Problema: Muito border.

Solução: 
1- Eu colocava border_bottom:1px solid black. 2- Daí só seria uma borda abaixo e não para cima, esquerda, direita. 3- O celular iria fazer o render melhor. 4- Meu celular parece que o box fica com as laterais curtas. 5- O botão sair e continuar estão engraçados.

Problema: 
Falta fluidez. E, isso o "o bom e velho design" faria. Se fosse "aplicado a WEB" e não a um programa.

Solução:
Eu colocaria o x de sair quando o mouse clicasse em qualquer area 1 vez. Ou continuar duas vezes com o click.  A parte describe de cada box colocava dentro do box com uma cor quase apagada. Usaria font com vw pra ela ter um tamanho e tornar próxima ao celular.  Exemplo

$( "#target" ).click(function() {

alert( "vc tá saindo da page, volte sempre" );

});

Ler api.jquery.com /click

*Momento react*

Comentário: 
Você compra uma calça que não tem bolso, mas o bolso é desenhado.  Daí você usa e esquece que não pode colocar o celular num desses bolsos. Talvez nessa brincadeira você pode esquecer o celular em algum lugar ou perder dinheiro ou mesmo o troco do pão.

**Comment by kivervinicius** [comment]
o cara ta passando por todos tópicos antigos e dando um up rs

**Comment by nandomoreirame** [comment]
🤔

**Comment by pedroguilhermelima** [comment]
> o cara ta passando por todos tópicos antigos e dando um up rs

Eu vou ajudar de outras formas, é só um ponto geral do formato de mídia review_react kkkk

**Comment by pedroguilhermelima** [comment]
O que voçês acham? Tá bom  ou  que precisa ser melhorado?
