### ISSUE TITLE
Transparência de doações

### ISSUE THREAD

**Issue by mikaelhadler** [frontendbr/forum#1406]
Olá pessoal tudo bem ? A pouco tempo estou por trás da iniciativa do @valorizevidas, que tem por objetivo atual auxiliar entidades filantrópicas.

Vou tentar ser bem objetivo, a pouco abrimos uma campanha no apoia.se para custear despesas do projeto e conseguimos atingir a meta do mês passado! Sendo assim, recebi o valor das contribuições na minha conta pessoal, pois atualmente não temos cpnj, nem conta bancária do projeto.

Acho que muitos já ouviram falar sobre problemas com ongs, gestão de recursos e uso indevido das doações.

Pois bem, quero ser transparente com todas contribuições feitas para o projeto. 

E por isto gostaria de saber, como vocês fazem para divulgar gerir com transparência recebimentos e compras dos seus projetos open? 

Como no comprovante bancário vem as minhas informações como número de conta e cpf, não sei se seria uma boa deixar meus dados expostos, o que acham ?

**Comment by vhfmag** [comment]
Parabéns pela iniciativa, @mikaelhadler! Não sei se se aplica ao seu caso de uso específico, mas o [OpenCollective](https://opencollective.com/) tem o conceito de pedido de orçamento, especificando a que se destina e permitindo que os membros da organização aprovem ou reprovem um dado pedido (ex: [pedidos de orçamento do Webpack](https://opencollective.com/webpack/expenses)). [Dá até pra usar de graça](https://opencollective.com/pricing), desde que vocês mesmos gerenciem a grana.

De novo, parabéns pela iniciativa, precisamos muito de mais delas!

**Comment by mikaelhadler** [comment]
@vhfmag Cara, que dica mais sensacional! Perfeito para o nosso caso, nele você pode realmente ser transparente. Muito interessante mesmo, já criei a conta pro @valorizevidas. Agora só precisamos alcançar 100 stars no github para poder registrar-se como coletivo.

Se puderem nós ajudar, de aquele star maroto <3

Muito obrigado pelas felicitações, orgulho demais de poder levantar a bandeira \o

**Comment by vhfmag** [comment]
Já curti! :blush:

**Comment by dmchiodini** [comment]
Ja deixei a estrela. Parabéns pela inciativa 👏🏼

**Comment by mikaelhadler** [comment]
Acreditem se quiser, alcançamos a meta de 100 stars <3. O com orgulho que digo que o @valorizevidas ja esta no Open Collective. Obrigado demais galera!

Como atendeu ao esperado, issue closed. : ]

**Comment by fritzcapra** [comment]
Sacaneou minha caixa de entrada.

Enviado do meu iPhone

Em 6 de nov de 2019, à(s) 17:00, Felipe Fialho <notifications@github.com> escreveu:

﻿

Closed #1406<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffrontendbr%2Fforum%2Fissues%2F1406&data=02%7C01%7C%7Cae907f67201544bc82f208d762f3ed0e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637086672093411720&sdata=1wm1sxV5NA7LF3lvLMoeeN7OKYVZJ3bBoXeniXYWdto%3D&reserved=0>.
