### ISSUE TITLE
[ Curiosidade ] - No Angular na atualização do componentes são chamados alguns métodos duas vezes? 

### ISSUE THREAD

**Issue by tosipaulo** [frontendbr/forum#1408]
Galera, me surgiu uma curiosidade/dúvida.

Por que os métodos: 

* ngDoCheck, 
* ngAfterContentChecked, 
* ngAfterViewChecked 

São chamados duas vezes na atualização de seu componente.  Talvez esteja pensando completamente errado sobre os ciclo de vidas dos componentes, mas criei um exemplo no Stack Bliz, para perceberem que no `console.log()` ambos métodos serão executados duas vezes:

[Link StackBlitz Exemplo:](https://stackblitz.com/edit/angular-bmmyns)

**Comment by Rodrigo54** [comment]
isso aconteceu porque os eventos se propagaram do componente pai pro componente filho, mas eu sou só um Padawan por isso invoco meus mestres Jedi @loiane e @willgm pra explcar melhor isso.

**Comment by loiane** [comment]
Quando o componente é inicializado, existe a ordem que as verificações são feitas.
Caso você atualize o template - com interpolação por exemplo, são feitas outras verificações do ciclo de vida, e aí tem outro console.log.

Por isso que quando vc clica no link, vc tem saída de alguns console.log - o componente está sendo inicializado, e as verificações são feitas.
Quando é carregado a info e faz a interpolação no template, rodam mais algumas verificações e vc tem mais saída do console.log.

Nesse vídeo explico quando cada verificação é disparada: https://youtu.be/4Z543sAKmBA 

Se você colocar um botão na tela pra fazer alguma mudança no template novamente, vai executar algumas verificações de novo.

**Comment by tosipaulo** [comment]
Nossa @Rodrigo54 muito obrigado por dar um start nesse bate papo, @loiane e @William Grasel sou fã de vcs, um grande prazer ter minha dúvida respondida por vcs! 

Obrigado pela explicação =D

**Comment by wkrueger** [comment]
Vindo do react, que tem um ciclo de render bem explícito, fico um tanto curioso com relação ao caso do Angular (que comecei recentemente). Sabemos que todas as major frameworks usam algum tipo de algoritmo baseado em virtual DOM com várias similaridades entre si, mas os detalhes parecem mais obscuros. Me parece que o angular, além de adicionar observers nas propriedades do componentes, também avalia a estrutura do template pra saber o que mais observar, e ele de alguma forma consegue identificar alterações mutáveis como Array#splice, mas nem sempre.
