### ISSUE TITLE
[Dúvida] Introduzir múltiplas tarefas no gulp (desenvolvimento, produção, teste).

### ISSUE THREAD

**Issue by thallesmarchetti** [frontendbr/forum#1410]
Olá galera!

Pois bem, eu tenho um [boilerplate](https://github.com/thallesmarchetti/Marchetti-boilerplate) para facilitar o meu worflow para o desenvolvimento. Meu boilerplate faz todas as tarefas simples para que preciso, mas eu quero introduzir uma tarefa ex: 'gulp-dev' que rode todos os arquivos para uma pasta temp separados do build de produção. Atualmente ele roda o watch e o browser-sync para a pasta do build, e eu queria justamente separar essas tarefas. Fiz pesquisas na internet e não achei algo que eu conseguisse assemelhar bem o que eu gostaria de fazer. Se alguém conseguir me dar dicas ou qualquer outro tipo de ajuda seria de grande valia. Outro detalhe que não sei se consigo usar o Webpack para substituir o Gulp.

Obrigado!

**Comment by simaodeveloper** [comment]
Olá @thallesmarchetti tudo bom?

creio que você precise passar argumentos para seu arquivo gulp, veja este tutorial te ajuda: 
https://stackoverflow.com/questions/28538918/pass-parameter-to-gulp-task

qualquer coisa me chama!

**Comment by simaodeveloper** [comment]
Seguindo esse tutorial que te passei, eu utilizaria algo semelhante ao que webpack faz:

`gulp watch --mode=production` ou `gulp watch --mode=development`

dentro do meu gulp file eu faria o seguinte:

```javascript
const isProduction = argv.mode === 'production';
```
Assim eu posso setar diferentes paths, plugins e outros. utilizando diferentes comandos de produção e desenvolvimento. Caso queira abstrair isso pode usar NPM Scripts como `npm run dev` e `npm run prod`

**Comment by thallesmarchetti** [comment]
Olá, @simaodeveloper blz??

Eu dei uma olhada no link que voce me passou e não consegui entender tão bem... será que você conseguiria exemplificar pra mim?? Coloquei o gulpfile [aqui](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4A5AFc4MAARxiAJwjViYgNwAdNFqHyZAIwW0A7tIUBlAJ5pqMgLwyFMAI4SITgBRjDJswFo4a2oxAEoKLRlImSFqDGJ7Rxc3TzEAcwkoAAc-GLjQ8LQomXSshKdXdxgvEsz8iKiSMiwIQody5Kq0jOzGqGa0OsKoiCwMVJh+sqTK6u6-EbGJlsGitAk0XglqAGs4ACUmABMYBSmKlJq-NY2t3b8nNGOFFajMqAksfROzjtmsvzeHy+zzC9Ui8ks7zgPxmXX+EKhL0ijAUZhhFzmKLMoU0aAA9AAqLQAHz8ZPJFMpVOpNNpdPpNJJMgAcutNjtoQAVDBwXYkhkCwVC4UUrQEvFaGr4Yg87Zea7s3ZiCgyDwhewAPhkwDBiWIEgUhSlcAU1C8GEymUJRFIUFCuqK+EyEEyVUBnxOapCDqiTpdVQVt32R09wBkmTihEQMmQYgtVoAbhAYKY8WIALoyVghb1DIqRP2ujy9foeMN0KBQC3SADqhAgjDgEeoMGjigksmzufzvudRalx3kXkyEn0UGUaZzuOzuMJ-JFC8Xi6Z5mIkKkMm5vLg86Xe-3tLFErQUplvK8CKkytV6rsWp1eeK3XwJrNGhA8bxl7geNGLRfa5QO+3Y9jIhZuu8HoKF6PoFn2VTfmW0S0FgmROHAcBtgoHZZjmsFgfBHgDvAxAeO+I5jhO1AYcBITTnRWhzmgpIHqxbF+EyACqqTjmAlgyBgjwyAAwvQsTxAAUuYu7sbJC5HpKz5nnKYi8BgCY8tQSiZKoKpqpq2q6k4+qGk+WQvqa5qWniakaXAWkusQhLigS+D8Paj6OoR7rAjBnm9v6HhYp6eH+XBgW5KRYgtMcAAeblwKEIE9uBRHPoOUUUeO1A2YloUzoxRLMXJJUikyACSozjFyso7sVpUNQyCknkpspeAs1XXvpd6GY+xqWXG1kdfAzmEh5oEEYFPkhcl+apcNpZhi0KJVi2hxYR2KpobQqToXAEAJq2MjtjAKq0DpIwQAAXnEED0AAMjAh1QNGABMuGzV5gXEUOYhZROw15QxaAFfiRUsY1kPUkyNZxNQ9YnputUyVDqMccxTKcoQMD8VAtC0NsMhgLQpzENjRPQPA0SEIJ1UCUJ2FoNC+huFAhwtKkx21fgMMwGITgyMYcMI5zMAYPDMiHChGAtPThyJHQqHQBzcgwBGxlQJYTLE6cXzECi4YnDrow2DAPMY2g4qKeZyleELxDw11t73rqUr2-DVlWgSLk2mQ16xoGHIZsDRRu8LntfoBUija5CL+2I37B7iofPu7hAR7ZmnaU53vWu5Kqxpn9nZ0nrup+Hg1WoDMf4MAvCZKkFCZCeFCpBAYCsPHC3LOmwOg0xENo6jTIAEJGKY8BBCjQ+NSSo-j2YVg2HLcgygoxDQhgMh47EUCELQejHM9504Aw+AiShzqwIc2uU5vAu0BIxAjvrMDy8ttAyAABv91Bf5LlQVAk0sCqOAn9jCyAwE4JkjBKwqzHr4E4S9bDEE-lIWQDYBKbwMDyM2c9LbHlPG1bwC8TgBCCE7AyD4ii6HiJAWA0IHDIHwn9Uc2Ua69GVCw3+eJqI-lzq5PhXCwoyFYZRHK1cBHCImmI9h-Aa7uV1OmXEuofATwsEEMs+F6HwGjLGfAeIeECPwASDMBQJqZBJsQaMAAOAADA48xoEzCHQUNGahE0oj6FwQAEXcNGMQBieFiHwqwXUoN+7gxnmjJkxwwAYAyPEZS09oklWakQ88Yg4kJKgLpGMYhA5KhVAnKOiVilFwcjpa80UqrwGqWnapaj-CBBsKXMGKTUmyViWrPGWt6qdIauk1qmSWbQEOPHQpZTRGJ3KepLOjlqmAzaZQEA0hYAqDukzPAABGXZiA7FsA4CATAOA8D4D4SsoQjBmA8DYOmKgJzuAgBqDotgQA)

Obrigado pela ajuda!

**Comment by simaodeveloper** [comment]
Veja se consegue entender o que eu fiz  e testa ai para ver se funciona [gulpfile](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4A5AFc4MAARxiAJwjViYgNwAdNFqHyZAIwW0A7tIUBlAJ5pqMgLwyFMAI4SITgBRjDJswFo4a2oxAEoKLRlImSFqDGJ7Rxc3TzEAcwkoAAc-GLjQ8LQomXSshKdXdxgvEsz8iKiSMiwIQody5Kq0jOzGqGa0OsKoiCwMVJh+sqTK6u6-EbGJlsGitAk0XglqAGs4ACUmABMYBSmKlJq-NY2t3b8nNGOFFajMqAksfROzjtmsvzeHy+zzC9Ui8ks7zgPxmXX+EKh+SiYJkjAUZhhFzmaLML0iKIA9ASZBhDsoIPQYBAZPA4BhoYcJPSZMdMkcAFc2CD0lEYBSpABumM6lj5qTgoXwYoFBSKNQgYGFf2yCtCmiG+LQBIAVPUAIpMx60GkADxg1AkxD5WFo0IwUHSWGitFGRuK3RZMAFE1tMhaYFoClGpw+JP5HxExsyfIwMhtZMgsVOaFtdPqdIAt4cMBQZGh4IxTRM3saBdhfZboBAAF58mTGsURhjGsTxmBiGkyaNwOmnbNyGDpFqFgNBjCIer1WJwY0ARkQA7zAGOo-Te3mmIRQ42cM2afJy9CRm9yVbd4X-YHXYdjcaajJXLJH04bXB6sb9G4oIdPZ7pGgBVoKABRGSNJyGadjQAJgXaQuzXa1fVXBRYwbcNzxbNsO1Le1AxkMRMiMRkVApAZc2fH1oUfes81TD8v0OdMYF4WNji7IiJAAc5XXNaAkAcWPIiRZDoKBaGo30+QqQDoUweCD3wzIJH0KBlHUcDIhgM0sBLeCUL-JhAOA0DmwXDT3VKPw-DbOxjm9MTMnPep72MOJqEIGQrJsuyYAcpyhnvT9oB-LzaGOWyvV82hHJEcy+PMmpnI9VziHcpLSiC79zK04sxL02NCLCriVzMoZ0syTzrLCmA7EK4jiFI8qZBS9zKpsuqtga+gmsykKqvCjqSO6tBtQJFEdHoPRDPcehzwSaV8DbGQAB9lvwny-JEdSbEm+IIDgAAFDihtaGkAJmtA5rsa7FOOrqBnVCa0D0aNiEIaEHGAdM+IUagYAXL6NRkXoF2QFFIjEDBMkyHUiFIKAxFlKIAF0kfBYhIXgUHwZkDQQChmGESkAlRhafAETxtGZFRlE4GoJRMmIOBsaBiGCYJFiyzphniB1UbtXwfhEZRGmgYWcZmZkMHWfw9nxfgPnYeAXhMlSChMjQNXUgVVhhaB5H6nYepBvugGURBxTlNU6gCT1ooESx3GQCUlTlAJage0p2n6YgRnmYIq23aFqn5clgPXZt0OxENpGNui88zaBi2Id622qYdyW8dTj230ob2ef91Pg5RUOF28BiCSjmOmIUb0WaKcPrcVgXejtqJG7dnPm-wHO24hl2m9D5u+8tiOObgbuhfqA20FYLQtB1LRlqslfV7X9eN83rft53rel5kAA5dZNh2aEABV6V2Jfd5v2+7-v1etFGrQanwK04G2LxrhP3ZEZkDwQj2AAHwyEBkUJwxAJAKEKK-OAv0PCvXeuTH6f04ZkBCDjSI+BMi+yqICT4JwAEYJllgnBbIPDf1uPsI4hDgDwTeqDSG0MCQgRgKYW2yMZCsBCMQooRRsG4I8PKMAHh9pHSKidXMvR+geDoaJKAUNpAAHVCAQEYHAaMf0FyKGElwnhvC+GkMEa-Y48gEFxHesgaaRhLoiGRmgqAPD1TcPVIvNAy8H6eK8V4-e5gMZQhkBfD+b53HeLCeEneT8xqa26G-S+XgiYSlzAA4BoCUSwPgYguAyCoGoIzgYwxAjyH4OBEQzBMgilVGEaIw6d1SK5kSbI50OknA9m0QoXR3CGn+KkEQgpfDKlCNiaY4g5i3pwCsedGx557H5JCM4+ZC9dShIiastZfh94AFVUiqTAJYEkjwZAAGF6CxHiAAKXMNfdZNzvFRJfrE9+n8xCc3pD7Rmf8Ul2BAWAqIECoEwNiXA6gYykEzlyTAcm7ymb9P4WQvB7wCEKDKSQip8KhlZAVDU8R9V6mohOGYPp5TBm5FGWIFoxwTSCwlDw4l6KTEFlBRM6xs07FQoLrS2eiytTLI8bc-ld994AElRgS0CZfEJfKBXSu3vcmJWQ4kfy8FHZJgDvlpKBhkkFWScm-UhaHWFURBklMIZywxRjyHVLEXU+guZ5YyLocOE4Ci-qHHacJXMhVUitLgBAOuqIOkwF4ozEYNY4ikQADKRSgAuKCeizXmsGQysxWTJkgWmWyg13KXFLOuTK-NG995KLcqozW4rgl5oLVWqyS995n0IDAfZYlaDbBkKOVEDa23QHgNEQgGBNY9v7T+Dpz0DAMRaKkVEEr8BFvbE4ZqJaJ00gwK1G8pNChDsSHQHSVYy3SGjBAqAlh97tq+MQNEXYTijldKg2tI1omvyeV4FqhBPlqp+ek2JL6mW6tQb0XMyAxCUNPmIZG3K5RfpLT+8Feryb+PgABsQiTQPgaiK-b9OqYN5OhXARDrzua+1UGB9UEGFUYYsdkrD+rRUIaluSmj-QUMLNcby6tbGNnuJkAAISMKYeAQRK3sZlXetaPHfAnCsDYA5P4DwKCZiSGQYlYhQEILaeIccYoMHwMcl0ODYCMU45AWAdp518WIEpc9MAfzDmNAAAwHsoWzLJKgqEDJYBpxpjCyD5DAfejAoCqTLWJvjFggiomNFIWQaiSR2gMPSSFd7n7ysyIq55PgQsBCCG+1JgMUTpbMJJkFvzDFGcdoB-ABIHM221PzfA2pQNUyKJkQMxAFwAA4AAMXXGtRDMN6BQidzV8P0PFgAIu4MuFWqu23KXPIGOauUscE0JgV+9jhgAwBkeITzlsrduXKx98SxDrc21AVQiHgO-1zEhnpST8L4ehX-ejiw7tiBfU9-LJxMs2CY7mlZe3pVrZgCWY9-2Af8oO48o7vU-6Acu695D12Hs8ye1HYjWhKAgGkLAE6CAeCzgAMyIAACxsA4CATAOA8A9x7JjoQjBmA8DYKjCnXA8A1FK2wIAA)

**Comment by thallesmarchetti** [comment]
Opa, @simaodeveloper !

Então, fiz os testes aqui, funcionou e no meu package.json eu defini os scripts.
`"build": "gulp --mode=production",`
`"local": "gulp --mode=development"`

Ficou da maneira que eu estava imaginando mesmo e agora vou dar uma atualizada no meu [boilerplate](https://github.com/thallesmarchetti/Marchetti-boilerplate). Se vc quiser dar um pull request com a sua ajuda que me passou fica a vontade e até por acaso melhorar alguma coisa que vc ache que não esteja legal.

Muito obrigado pela sua ajuda!

**Comment by simaodeveloper** [comment]
Opa com certeza, será o minha primeira PR, que legal que te ajudei, @felipefialho pode abrir a issue por gentileza, o Thalles não deve estar acostumado e fechou a mesma.

**Comment by simaodeveloper** [comment]
@thallesmarchetti PR realizada https://github.com/thallesmarchetti/Marchetti-boilerplate/pull/1
