### ISSUE TITLE
Como executar um código do GitHub?

### ISSUE THREAD

**Issue by vineplaysttt123** [frontendbr/forum#1413]
Olá, sou novo por aqui e estou com problemas, tem esse código de um conversor de arquivos, mas não faço a menor ideia de como utiliza-lo. 
https://github.com/bodymovin/bodymovin-to-smil

**Comment by jbbn** [comment]
fala @vineplaysttt123 beleza?

man eu fiz um teste aqui, mas o JSON que eu peguei de exemplo do bodymovin devia ter coisas não suportadas por essa lib de conversão, pois o SVG final ficou meio bugado, apesar de fazer algumas coisas.

Talvez por que a lista de suporte deles seja apenas:

> It supports basic animations:
    * masks (additive and intersect)
    * shapes
    * solids
    * texts
    * precomps
    * transforms
    * opacity

Eu usei o JSON fornecido neste post, com a palavra "Amazing": https://blog.truthlabs.com/bodymovin-complex-animations-simple-implementation-a26830343507

Anexei o resultado final aqui: [animation.svg.zip](https://github.com/frontendbr/forum/files/3092273/animation.svg.zip)

Pra você rodar aí é assim:
* Faça clone do repositório
* Instale as dependências utilizando `yarn` ou `npm i` (escolha de sua preferência)
* Extraia o zip `example.zip` ; esse aqui: [example.zip](https://github.com/frontendbr/forum/files/3092276/example.zip)
* Entre na pasta example e rode o comando `node index.js`

O resultado final é um `animation.svg`.

Edite arquivo `data.json` para realizar testes diferentes (imagino que você tenha o plugin Bodymovin no seu After, então pode gerar outros JSONs para o que você está tentando fazer)

Qualquer dúvida, me chama :fire:

**Comment by vineplaysttt123** [comment]
Opa. Obrigado por responder. Não conheço nada de programação, mas instalei o node e o yarn. Não entendi as partes de fazer um clone do repositório e como entrar na pasta example e rodar o comando. Obrigado, pela ajuda. Acabei me envolvendo nisso e estou buscando uma solução para essa conversão.

**Comment by jbbn** [comment]
tranquilo.. essa é uma maneira legal de aprendermos coisas diferentes.

## Clone

* Instale o git na sua máquina
* Abra o bash (se for Windows, quando instalou o git, foi instalado o GitBash também)
* No bash abra uma pasta sua de projetos
* Comando: `git clone https://github.com/bodymovin/bodymovin-to-smil.git` (vai pedir seu usuário e senha do github)
* Depois que terminar o clone, é só seguir os passos do meu comentário anterior ;)

(Para abrir uma pasta no bash, basta da o comando `cd` com o nome da pasta que quiser abrir.. [se você não tiver experiência com linha de comando, vai ter que criar a pasta na mão.. então se ela já existir melhor rs])

**Comment by jbbn** [comment]
pensando aqui @vineplaysttt123 .. se tiver utilizando Windows ou Mac, pode facilitar sua vida utilizando o [GitHub Desktop](https://desktop.github.com/) ;)

**Comment by vineplaysttt123** [comment]
Consegui abrir as pastas, mas ao utilizar o comando node index.js apareceu seguinte erro:
$ node index.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'xml'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\gxixx\bodymovin-to-smil\src\index.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by jbbn** [comment]
Você esquece de dar o comando `yarn` na pasta raiz (fiz isso na primeira vez que executei o projeto também kkkk

**Comment by vineplaysttt123** [comment]
Consegui instalar o módulo xml, obrigado por tudo. Valeu!

**Comment by vineplaysttt123** [comment]
hahaha na verdade eu dei mas não estava na pasta

**Comment by jbbn** [comment]
tranquilo.. qualquer coisa é só falar :)

Se quiser pode dar um follow em mim no github pra ficar mais fácil de nos falarmos ;)

**Comment by vagner531** [comment]
Alguém pode me ajudar ? não sei como executar esse código ?
https://github.com/chapeupreto/sinesp

abrir no navegador localhost, mas a tela fica em branco.
