### ISSUE TITLE
Seria a divisão entre frontend e backend um antipattern?

### ISSUE THREAD

**Issue by woliveiras** [frontendbr/forum#1415]
Galera, li um artigo interessante e gostaria de ouvir (ler, no caso) a opinião de vocês sobre isso.

Eu tenho uma opinião formada, mas não quero enviesar sua resposta, então comenta ae o que pensa sobre esse assunto:

[Dividing frontend from backend is an antipattern](https://www.thoughtworks.com/insights/blog/dividing-frontend-backend-antipattern)

***P.S.**: muito provavelmente o autor não quis ofender ninguém com seu texto*

**Comment by Alecell** [comment]
Eu não li por cima, mas...

A divisão front e back nasceu decorrente de uma necessidade e não de uma mera vontade. 

A grande diferença do front e do back cuja não vi ser abordada na postagem é o HTML e o CSS. O front deve saber lidar com isso de forma semantica se preocupando com UI e UX. Este é um conhecimento diferenciado por si só.

O back e o front na parte "Quem programa de verdade" são iguais, complexidade de zonas são as mesmas hoje, mas em situações diferentes. (o back lida com um servidor legado e o front tem de dar suporte a IE8)

A grosso modo e ao meu ver, ambos são igualmente capazes como desenvolvedores, trabalham juntos para determinar como a aplicação vai prosseguir, entretanto, o back vai se preocupar com o servidor e o front com o browser.

**Comment by aicouto** [comment]
não existe divisão entre back-end e front-end, existe apenas linguagens diferentes.

atualmente é comum desenvolvedores se identificarem como fullstack developer ou usarem frameworks isomórficos em javascript que não separam o código em front-end e back-end.

o problema está nos códigos legados e na especialização: a grande maioria dos sites ainda usa linguagens diferentes no front-end e no back-end, por isso requer profissionais mais especializados em uma ou outra linguagem para manter uma boa qualidade e rapidez de desenvolvimento.

```
o back-end é ruim de dba e front-end
o dba é ruim de back-end e front-end
o front-end é ruim de back-end e dba
o fullstack é ruim de back-end, dba e front-end
Conclusão: todo mundo é ruim em alguma coisa
```
sou otimista, acredito que com o tempo as diferenças entre as linguagens tendem a diminuir diminuindo assim distância entre o front e o back.

**Comment by aicouto** [comment]
> A grosso modo e ao meu ver, ambos são igualmente capazes como desenvolvedores, trabalham juntos para determinar como a aplicação vai prosseguir, entretanto, o back vai se preocupar com o servidor e o front com o browser.

@Alecell só por que é isso que é feito atualmente na maioria dos casos não significa que é o que "vai" necessariamente continuar acontecendo. na prática, com a popularização do SaaS o front-end ficará cada vez mais dependente do back-end e o back-end cada vez mais dependente do machine learning. 

no final ambos vão perder o emprego para a IA, mas o back-end deve ter uma morte mais tranquila e suave do que o front-end que vai continuar sendo lentamente devorado vivo pelo back-end.

**Comment by ninadream** [comment]
hello from Deer Baudin (jackTheRipper) and his old cunt @irinaks1 ;)
