### ISSUE TITLE
Dicas sobre como se preparar para um processo seletivo internacional - Hangouts gratuito

### ISSUE THREAD

**Issue by leandrooriente** [frontendbr/forum#1417]
Opa pessoal, tudo certo?

Me chamo Leandro Oriente e sou desenvolvedor na DAZN em Amsterdam. Recentemente fizemos uma hackathon no Brasil e contratamos 5 brasileiros para se juntar ao nosso time!

Estou organizando um bate papo para trocar ideias sobre processos seletivos. Tenho uma boa experiência tanto entrevistando, quanto sendo entrevistado e queria passar esse conhecimento adiante de forma mais eficiente. 

A ideia é fazer um hangouts e tocar em pontos como inglês, conhecimento técnico, live coding, como lidar com falha ou falta de conhecimento em algum tópico, como se vender bem e etc.  Já tenho feito isso individualmente com algumas pessoas e gostaria de testar esse novo modelo com vocês.

Você pode se inscrever [nesse link](https://leandrooriente.typeform.com/to/CmG2NQ) e pode ficar tranquilo que é 100% gratuito. Só fique atento as datas e não se inscreva se não for participar de fato.

Você encontra todas as informações sobre o bate papo no link acima. Se tiver qualquer outra dúvida é só comentar aqui :) 

Ahh, não tenho mais Facebook, então não vou divulgar nos grupos de lá, mas caso queira passar a palavra adiante, fique a vontade de compartilhar em qualquer canto. Fico super grato :) 

Forte abraço!

=========
**Moderação**

Não achei nenhuma informação a respeito desse tipo de divulgação. Entendo que posso de alguma forma estar infringindo as regras e caso esteja podem fechar a issue sem problemas ou ressentimento algum.

**Comment by felipefialho** [comment]
@leandrooriente Que isso mano, puta parada da hora, valeu por postar!

**Comment by didiraja** [comment]
@leandrooriente qual link da exibicao desse hangouts?

**Comment by leandrooriente** [comment]
Opa @didiraja, infelizmente já fechei o grupo. Se tudo der certo vou passar a fazer esse evento periodicamente e volto a postar aqui.
