### ISSUE TITLE
Blog em React

### ISSUE THREAD

**Issue by Juuhz** [frontendbr/forum#1425]
Fala Devs, beleza?

Ajudem o pai aqui, estou com uma dúvida em um direcionamento e gostaria da opinião de vocês, caros senhores da oceania. 

Estou reformulando meu site pessoal, que atualmente está em NextJS ( React ), antes ele era uma Landing Page, mas agora, quero criar algumas páginas extras, e uma delas é o blog, onde irei escrever dicas em português para ajudar a enriquecer a comunidade brasileira.

Mas me deparei com a seguinte dúvida: 

- Como irei escrever meus artigos e depois pega-los no front ( via api ) ?

-----

A princípio eu pensei no seguinte esquema:

1) Teria meu site em React, normal.
2) Teria outro ambiente, onde instalaria um Wordpress e lá eu escreveria meus artigos.
3) Faria uma API em Node para consumir o banco do Wordpress e me entregar os dados no front ( react ).

----

Mas não sei se esse é o melhor caminho, oque acham ? 

Abraços.

**Comment by felipefialho** [comment]
@Juuhz Tem alguma razão de você querer usar React na construção do seu blog?

Particularmente acho que existem soluções mais fáceis e interessantes nesse sentido, como o (Harp.js)[http://harpjs.com/) e o [Jekyll](https://jekyllrb.com/).

Mas entendo totalmente você usar React caso queira aproveitar para estudar essa lib/framework.

**Comment by Juuhz** [comment]
@felipefialho eu quero usar uma lib/framework no lado do cliente, para deixar a experiência mais fluída e performática para o usuário, exemplo: no blog, o usuário navegaria entre os posts e nem iria ver o reload da página. Acredito que as ferramentas que você indicou também façam isso, inclusive dei até uma olhada, mas acho que elas não resolvem 100% meu problema. 

Com o Harp e Jekll (pelo oque eu entendi), para criar posts, por exemplo, eu teria que criar arquivos estáticos e escreve-los em markdown, mas acaba sendo ruim, porquê sempre que eu precisar atualizar um post, tenho que fazer um deploy, sem falar que escrever um conteúdo em código, acaba sendo mais trabalhoso. 

Eu queria uma solução, que eu pudesse escrever de forma limpa, tipo essa caixinha de comentário do git, onde tenho as opções de formatação para me auxiliar, e depois, consumir esse conteúdo do lado do cliente.

**Comment by guibfo** [comment]
Eu estava querendo fazer algo parecido, e achei o [Gatsby + Netlify CMS](https://www.gatsbyjs.org/docs/sourcing-from-netlify-cms/) uma boa opção, acho melhor que hospedar um Wordpress só pra usar ele como API, e o Gatsby é bem legal (o reactjs.org é feito em Gatsby)

Tem um demo da Netlify CMS em https://cms-demo.netlify.com/#/collections/posts

**Comment by fdaciuk** [comment]
@Juuhz, hoje estou usando Hexo no meu blog, que gera tudo estático, mas estou migrando ele para Gatsby :) 

Como o @guibfo comentou, Gatsby + Netlify CMS vai te ajudar com o que você precisa:
- Aproveitar o melhor da componentização ao desenvolver com React;
- Ter uma SPA para uma navegação mais fluída;
- O primeiro render que o Gatsby gera é estático, então você tem SEO tanto para buscadores quando para compartilhar conteúdos em redes sociais;
- E o Netlify CMS te dá uma experiência "parecida" com o WP, mas sem precisar de um servidor específico para hospedar PHP :)

Ainda estou vendo se vou usar Netlify CMS na nova versão do meu blog, mas é uma possibilidade, apesar de eu gostar de escrever Markdown na mão mesmo xD

**Comment by lucianobarauna** [comment]
@fdaciuk interessante saber sobre o Netlify CMS não conhecia esse cara hein ;-)

**Comment by felipefialho** [comment]
Também não conhecia, muito foda e até pensei em refatorar meu site (e quem sabe atualizar mais depois), hahaha 😄

**Comment by nandomoreirame** [comment]
o meu foi feito com React / Gatsby ... recomendo!

https://nandomoreira.dev/blog

**Comment by Juuhz** [comment]
Irado @guibfo e @fdaciuk, não conhecia o Gatsby, acredito que irá me servir bem. Irei começar aqui os trabalhos \o/ 

@nandomoreirame, parabéns pelo blog, ta irado e lindo. 

@felipefialho, tópico resolvido ;)

**Comment by nandomoreirame** [comment]
@Juuhz  é nóis 🤜🏼🤛🏾 

🤘

**Comment by mutheusalmeida** [comment]
> o meu foi feito com React / Gatsby ... recomendo!
> 
> https://nandomoreira.dev/blog

Olá, Nando.

Eu estou tentando fazer o deploy do meu blog no subdiretório "/blog" usando Gatsby e Netlify, mas não estou conseguindo. Pelo o que pesquisei, o Netlify não suporta subdiretórios, apenas redirects. Como você resolveu esse problema?

**Comment by nandomoreirame** [comment]
> > o meu foi feito com React / Gatsby ... recomendo!
> > https://nandomoreira.dev/blog
> 
> Olá, Nando.
> 
> Eu estou tentando fazer o deploy do meu blog no subdiretório "/blog" usando Gatsby e Netlify, mas não estou conseguindo. Pelo o que pesquisei, o Netlify não suporta subdiretórios, apenas redirects. Como você resolveu esse problema?

@mutheusalmeida  O projeto inteiro é um build no Netlify, `/blog` é só mais uma rota (página) que lista meus posts... não são projetos separados.

**Comment by mutheusalmeida** [comment]
Entendi. Obrigado!

**Comment by felipefialho** [comment]
Só fazer minha "mea culpa".

Não conhecia soluções como o Gatsby, ótimas pra blog e baseadas em React, por isso meu comentário no começo da issue. Tive o primeiro cheiro sobre Gatsby aqui e o convencimento final depois do @willianjusten refazer o blog dele.

Estou adorando, então tô passando pra agradecer as sugestões dadas aqui 😄
