### ISSUE TITLE
Rehoc - Novo gerenciador de estado para React

### ISSUE THREAD

**Issue by Wpdas** [frontendbr/forum#1426]
Olá galera. Estive trabalhando nos últimos tempos com muitos projetos React. Então começei a desenvolver uma nova ferramenta que não fosse tão complexa (no quesito entendimento e manuseio) quando o Redux mas que ao mesmo tempo pudesse fazer o gerenciamento de tarefas de forma fácil e prático. A algum tempo alguns outros projetos começaram a usar ele e estou tendo feedbacks aos poucos. Gostaria de deixar aqui o esse post para quem estiver interessado, usá-lo também e ir enviando feedbacks.

Rehoc foi construído para atender diretamente à lib React. Ou seja, é compatível com ReactJS e React Native apenas.

Agradeço o interesse "D. 

Link NPM: https://www.npmjs.com/package/rehoc
Link Github: https://github.com/Wpdas/rehoc

**Comment by ninadream** [comment]
hello from Deer Baudin and his old cunt @irinaks1 ;)

**Comment by ninadream** [comment]
hello from Deer Baudin (jackTheRipper) and his old cunt @irinaks1 ;)
