### ISSUE TITLE
Continuous Integration, qual serviço vocês recomendam?

### ISSUE THREAD

**Issue by Rodrigo54** [frontendbr/forum#1429]
Recentemente eu encontrei essa [lista awesome](https://github.com/ligurio/awesome-ci) com vários serviços de CI e eu vim aqui perguntar qual vocês usam em projetos privados com pequenas equipes.

**Comment by DiegoWesselka** [comment]
Sou adepto do Jenkins. Possui um pipeline agradável com o OceanBlue

**Comment by nandomoreirame** [comment]
Drone CI é muito foda, feito em React <3 
https://github.com/drone/drone

**Comment by willycamargo** [comment]
Utilizamos Drone self-hosted aqui na empresa.

Mas ja utilizei Codeship, CircleCI, Bitbucket Pipeline e recentemente testei o Cloud Build do google cloud.

Desses o que não recomendo por enquanto é o Cloud Build que esta bem cru ainda e bem pouco flexível. O resto é tudo bem parecido.

**Comment by didiraja** [comment]
Qual dos citados serve para projetos pequenos? Desde que conheci o mundo do CI amei, mas sempre me parece uma ferramenta robusta que não combina com meus projetos pessoais.

Falo de coisas pequenas como exercícios em create-react-app ou sites institucionais

**Comment by felipefialho** [comment]
@didiraja não tenho uma explicação racional pra isso, mas uso o TravisCI para meus projetos pessoais, haha

**Comment by allangrds** [comment]
Além do CircleCI gosto do (Buddy)[https://buddy.works/]

**Comment by willycamargo** [comment]
> Qual dos citados serve para projetos pequenos? Desde que conheci o mundo do CI amei, mas sempre me parece uma ferramenta robusta que não combina com meus projetos pessoais.
> 
> Falo de coisas pequenas como exercícios em create-react-app ou sites institucionais

Acredito que se for para projetos estáticos em frontend o [Netlify](netlify.com) resolve muito bem. Tanto para CI quanto para hospedagem.

Tem um curso do Willian Justen sobre Netlify: https://www.youtube.com/watch?v=a1cIjP1bueM
(não fiz, mas o rapaz é bom demais então acredito que seja ótimo)

**Comment by allangrds** [comment]
Boa @willycamargo!

Uso o [Zeit](https://zeit.co/now) também para estáticos, e é bem bacana.

**Comment by Rodrigo54** [comment]
eu preciso compilar algumas coisas no windows e eu andei pesquisando e acho que vou usar o [azure pipelines](https://azure.microsoft.com/pt-br/services/devops/pipelines/) alguém já usou?

**Comment by NicholasKuchiniski** [comment]
Bitbucket Pipelines para projetos privados
TravisCI para projetos públicos no Github
