### ISSUE TITLE
[Angular] Cache de requisição Http

### ISSUE THREAD

**Issue by magnolemos** [frontendbr/forum#1432]
Galera, bão?

Estou trabalhando com Angular versão 7 e preciso fazer cache de algumas requisições http.
Cache em memória mesmo. 

Qual abordagem vocês utilizam?  

Na documentação do angular, além de ser um pouco confuso, me parece que se eu definir que um endpoint é cachable, de qualquer lugar que eu requisitar o endpoint ele ficará em cache, o que nao me parece o ideal.

outra solução foi usar o shareReplay do rxjs. O que me parece menos mal, mas por hora, não vejo como usar ele com um interceptor. ( gostaria de algo genérico ). Eu tenho um list-base e um form-base para cruds, mas em qualquer outro cenário, teria que copiar o código.

Sendo assim, gostaria de saber qual estrategia voces utilizam.

Valeu demais galera, sempre que venho aqui fico surpreendido!!

**Comment by adamfoerster** [comment]
Olá Magno, quais os critérios para que uma requisição seja mantida em cache são importantes na aplicação que você está fazendo?
Existem diversas formas de cachear no angular, mas tem que ver bem a necessidade porque, como dizem, os dois maiores problemas na programação são:
- dar nomes pras coisas,
- invalidação de cache.

**Comment by magnolemos** [comment]
Oi Adam, certamente!

Então, é um wizard gigante que o usuário pode ficar indo e voltando. Em alguns steps do wizard, faço requição de 2, 3 endpoints. Sendo que alguns trazem um json grande. A motivação seria ele poder voltar nos steps sem fazer a requisição novamente. 

Nesse caso, pensei em colocar um timeout para manter o cache ou uma quantidade q ele pode ir e voltar.

**Comment by adamfoerster** [comment]
Já fiz um wrapper para observable para cachear certas reqs http no localStorage, mas era um problema bem simples que eu estava querendo resolver. O seu caso parece que vc precisa de um pouco mais de controle, certo?
Veja se esta solução resolve no seu caso:
https://hackernoon.com/angular-simple-in-memory-cache-service-on-the-ui-with-rxjs-77f167387e39

**Comment by felipefialho** [comment]
@magnolemos Você precisa salvar essas informações só em tempo de execução ou garantir que elas continuem acessíveis caso a página seja atualizada?

No primeiro caso, vale criar um serviço no próprio rxjs, salvar tudo que precisa e deixar acessível em toda aplicação.

No segundo caso, de repente vale gravar no localstorage e remover quando essa informação não precisar mais ser utilizada.

**Comment by magnolemos** [comment]
@adamfoerster, fiz um serviço baseado no artigo que vc mandou. Nos testes que realizei aqui, parece ótimo. Obrigado pela ajuda e pela disponibilidade! 

@felipefialho, apenas em tempo de execução mesmo.Fiz um serviço para compartilha o cache onde for necessário e, nos testes que realizei, parece ótimo para o meu problema.  Valeu demais pela a ajuda =).
