### ISSUE TITLE
Posso múltiplos Arquivos JSON com Nodejs?

### ISSUE THREAD

**Issue by wburlani** [frontendbr/forum#1433]
Criei o Arquivo abaixo Server.js e declarei na terceira linha dois arquivos JSON porém apenas consigo realizar consulta em um deles, já testei também com && lógico e apenas consigo realizar leitura de um:

```
const hostname = '127.0.0.1';
const port = 3000;

const jsonServer = require('json-server')
const server = jsonServer.create()
const router = jsonServer.router('db_1.json' || db_2.json)
const middlewares = jsonServer.defaults()
 
server.use(middlewares)
server.use(router)
server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

**Comment by felipefialho** [comment]
@wburlani Usando o operador `||`, você está dizendo que caso o primeiro `json` não exista, ele deve usar o segundo.

Para funcionar do jeito que você espera (pelo que entendi), você precisa mergear as informações dos dois `json` antes de passar para o `jsonServer.router`.

**Comment by wburlani** [comment]
@felipefialho OK ... sou bem leigo no assunto, teria algum exemplo de como posso fazer isto, através do próprio arquivo de JS

**Comment by felipefialho** [comment]
Você quer que as propriedades dos dois `json` estejam disponíveis no mesmo lugar, concatenando tudo, ou que os `json` continuem separados?

**Comment by wburlani** [comment]
Os arquivos JSON separados

**Comment by wburlani** [comment]
a ideia é que o servidor JSON com um única porta disponível possa servir clientes distintos arquivos de JSON que não estejam relacionados.

**Comment by felipefialho** [comment]
Certo, veja se funciona:

### db.js

```js
import firstJson from './json1.json';
import secondJson from './json2.json';
import thirdJson from './json3.json';
import fourthJson from './json4.json';

module.exports = () => {	
  return {
    firstJson,
    secondJson,
    thirdJson, 
    fourthJson
  };
};

```

### server.js

```js
import jsonServer from 'json-server';

const server = jsonServer.create();
const router = jsonServer.router('./db.js');
const middlewares = jsonServer.defaults();

server.use(middlewares);
server.use(router);
server.listen(3000, function () {
  console.log('JSON Server is running');
});
```

**Comment by wburlani** [comment]
Este apresentou o sequinte erro:
---------------------------------------------------------------------------------------

PS C:\NewProject> node server.js
C:\NewProject\server.js:1
(function (exports, require, module, __filename, __dirname) { import jsonServer from 'json-server';
                                                                     ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
PS C:\NewProject>

**Comment by fdaciuk** [comment]
@wburlani o `import` ainda não foi liberado no Node.js sem flag. Troque os `import` por `require` que esse erro vai sumir :)

**Comment by felipefialho** [comment]
Com `require`:

### db.js

const firstJson = require('./json1.json');
const secondJson = require('./json2.json');
const thirdJson = require('./json3.json');
const fourthJson = require('./json4.json');

module.exports = () => {	
  return {
    firstJson,
    secondJson,
    thirdJson, 
    fourthJson
  };
};

### server.js
 
const jsonServer = require('json-server');

const server = jsonServer.create();
const router = jsonServer.router('./db.js');
const middlewares = jsonServer.defaults();

server.use(middlewares);
server.use(router);
server.listen(3000, function () {
  console.log('JSON Server is running');
});

**Comment by wburlani** [comment]
Obrigado @felipefialho || @fdaciuk de syntax sumiu, porém mesmo assim não esta em correto funcionamento:
Neste caso tentei reinstlar nodejs e o npm mesmo assim persiste o erro:


PS C:\node.js>node  server.js
internal/modules/cjs/loader.js:626
throw err;

Error: Cannot  find module 'json-server'
requeri stack:
C:\nodejs\server.js

**Comment by fdaciuk** [comment]
@wburlani agora tem que instalar o módulo json-server no seu app :)
Rode `npm init -y` pra criar o package.json e depois `npm i --save json-server`, e tente rodar novamente o projeto :)

**Comment by wburlani** [comment]
syntaxErrror: Malformed JSON ind file ./db.js
Unexpected token c in  JSON at position 0

**Comment by felipefialho** [comment]
Uhmm tenta assim (não estou rodando a aplicação):

### server.js
 
```js
const jsonServer = require('json-server');
const db = require('./db.js');

const server = jsonServer.create();
const router = jsonServer.router(db());
const middlewares = jsonServer.defaults();

server.use(middlewares);
server.use(router);
server.listen(3000, function () {
  console.log('JSON Server is running');
});
```

**Comment by wburlani** [comment]
Error: Cannot find  module ' ./json1.json'
require stack:
- C:/nodejs/db/db.js
- C:/nodejs/db/server.js

**Comment by fdaciuk** [comment]
@wburlani sobe o seu projeto aqui no GitHub em um repositório, pra gente ver o que você está fazendo. Vai ficar mais fácil ajudar :)

**Comment by wburlani** [comment]
**Repositório
wburlani/JsonServer**

Somente o que tem são este arquivos db.js, server.js, package.json e package-lock.json 

Além do diretório node_modules que é tem muita coisa quando instalado

**Comment by willycamargo** [comment]
@wburlani você precisa entender melhor o conceito de import/require do Node (E também de outras linguagens, já que é tudo bem parecido).

Nesse caso específico os arquivos que estão sendo importados (`json1.json`, `json2.json` etc..) não existem no caminho pelo qual a aplicação está tentando importa-los. Portanto retorna o erro que não foi possível encontrar o "módulo" (módulo nesse caso seriam os arquivos json em sí)

**Comment by wburlani** [comment]
@willycamargo, @fdaciuk  e @felipefialho
Obrigado pela paciencia de vcs ...
Acabo de conseguir vou continuar agora desenvolvendo e apreendendo mais sobre node e javascript

**Comment by felipefialho** [comment]
Tranquilo mano, valeu!

**Comment by audreyspency** [comment]
> @willycamargo, @fdaciuk e @felipefialho
> Obrigado pela paciencia de vcs ...
> Acabo de conseguir vou continuar agora desenvolvendo e apreendendo mais sobre node e javascript

Gracias
