### ISSUE TITLE
Podemos criar um "fórum de verdade" - Olhem essa ferramenta https://utteranc.es/

### ISSUE THREAD

**Issue by pglapds** [frontendbr/forum#1437]
Objetivo:

1. Podemos criar um **"fórum de verdade"** - Olhem essa ferramenta: https://utteranc.es/
2. Geralmente, os acessos são feitos via mobiles. Então, seria legal se a gente tivesse um site frontendbr.github.io/forum onde as issues apareciam. 

Esclarecimentos:

1. Acessar via desktop com issues é bom. Mas, o site seria melhor ainda.
2. Essa ferramenta poderia ajudar nesse processo.

**Comment by felipefialho** [comment]
@pglapds Pode botar la no https://github.com/frontendbr/sugestoes?

Tentei migrar mas não consegui 😢

**Comment by munizart** [comment]
@pglapds acho que inclusive existe uma sugestão pra usar o utterances já https://github.com/frontendbr/sugestoes/issues/27
