### ISSUE TITLE
Docker Toolbox funciona legal no Windows Server 2012 R2?

### ISSUE THREAD

**Issue by wburlani** [frontendbr/forum#1445]
Tem um Servidor Windows Server 2012 R2 em Núvem, preciso trabalhar com o Docker, na documentação : 
https://docs.docker.com/docker-for-windows/install/

Fala que o Docker for Windows funciona somente a partir do 2016, como alternativa tem Docker Toolbox 

Alguém já realizou testes e funcionou bacaninha?

**Comment by adrianoavelino** [comment]
Eu uso ele no Windows 7 Professional e funcionou legal nos meus estudos e testes aqui no trabalho. A diferença é que não acesso os container por localhost, mas por um IP de uma VM do VirtualBox fornecido pelo próprio Docker Toolbox.

**Comment by wburlani** [comment]
Ok obrigado vou instalar e realizar alguns testes em meu servidor

**Comment by lucasctd** [comment]
@wburlani Tu não vai usar isso em produção né?
Eu pensei em pegar um VPS Windows Server 2016 pq queria usar o Azure DevOPS (Docker) no meu host.
Ao pesquisar o que mais encontrei foi gente desaconselhando pois mesmo o Docker CE, ainda roda os containers linux em VM (Hyper V) no Windows.

**Comment by wburlani** [comment]
Como meu ambiente em nuvem é apenas a versão 12 (ambiente corporativo), e para atualizar para 16 terei complicações internas, então vou ter que testa-lo mesmo no 12 se rodar Aleluia se não paciência
