### ISSUE TITLE
Como Utilizar a Função "IMPORTXML" no site "fundamentus.com.br"

### ISSUE THREAD

**Issue by Harley8** [frontendbr/forum#1446]
Eu criei uma planilha pessoal e gostaria de importar informações do site fundamentus de acordo com o código da ação.
Acessando o link "http://www.fundamentus.com.br/detalhes.php?papel=B3SA3" eu gostaria de importar um dos indicadores fundamentalistas em uma célula do Google planilhas, como por exemplo o P/L de 31,09. Porém, eu não estou conseguindo importar apenas um valor para a célula.

Qual seria a fórmula e com quais parâmetros para eu importar esse valor direto do site?

**Comment by fabianoschaefer** [comment]
Comprei essa ação hoje =).  Só observando o desenrolar da thread.

**Comment by willycamargo** [comment]
1. Essa URL que enviou não é um XML, então acredito que qualquer coisa que importe XML não funcione com essa URL.

2. Acho que a comunidade do google docs deve te ajudar melhor com isso:
https://support.google.com/docs/community

**Comment by Mendrone** [comment]
Fechando por se tratar de um tema de pouco interesse para comunidade de Front-end.
