### ISSUE TITLE
Métodos Ageis

### ISSUE THREAD

**Issue by vinicastroo** [frontendbr/forum#1457]
Boa noite! Meu nome é Vinicius Castro da Costa, atualmente estou cursando o curso de Sistemas de Informação(UNIDAVI/ Rio do Sul - SC), na minha matéria de Engenharia de software surgiu um trabalho sobre metedos ágeis, preciso de 20 respostas, se alguém tiver interesse e souber sobre essa area, o link está abaixo https://forms.gle/3RyaGXnxo2HxNCUb9

**Comment by aranhaagency** [comment]
O ideial é você documentando, toda vez que cria um componente. Geralmente fazemos assim, criamos um component e quando vamos criar os tests documentamos. Temos uma estrutura parecida com essa aqui [gatsby](https://www.gatsbyjs.org/docs/)
