### ISSUE TITLE
Como estruturar um projeto React + Boostrap? 

### ISSUE THREAD

**Issue by romulo2735** [frontendbr/forum#1459]
Estou em um projeto no React.js, usando o Boostrap, Jquery e Popper.js.
Minha duvida sobre a componetização no React é assim:

Caso 1 - Teria um `Componente Master` onde tenho uma `<div className="container" > </div>`
```
function App() {
    return (
        <div className="container">
            // Insiro os componentes
        </div>
    );
}
```

Caso 2 - Cada componente tem sua propria `<div className="container"> </div>`

Qual seria o melhor "padrão" para criar interface com React e Bootstrap?

**Comment by felipemfp** [comment]
Dá uma olhada no https://reactstrap.github.io/.

**Comment by salatielq** [comment]
@romulosousa27 Se você ainda poder usar uma biblioteca de componentes do bootstrap para o react como o @felipemfp falou acima é melhor pois todo o trabalho de componentes ja foi feito e testado. 

Mas se não da para usar aconselho você criar components para cada parte do bootstrap que você for mais usar. Exemplo criar um `<Container />` em vez de usar uma div com class `container`.

Mas pensa que isso precisa de ajudar. Não crie um componente só por criar, se for util e você for re-usar crie! caso só vá usar em só um lugar acho válido usar as class do bootstrap.

**Comment by romulosousa27** [comment]
Entendi, valeu! @salatielq e @felipemfp

**Comment by AdrianoLupossa** [comment]
Actualmente estou usando o React bootstrap e é óptimo, porque além de não precisar do jQuery, nem do Popper e é super reutilizável.

https://react-bootstrap.github.io

A única desvantagem é que não se pode usar com styled components.

**Comment by felipemfp** [comment]
> Actualmente estou usando o React bootstrap e é óptimo, porque além de não precisar do jQuery, nem do Popper e é super reutilizável.
> 
> https://react-bootstrap.github.io
> 
> A única desvantagem é que não se pode usar com styled components.

Ele depende do Popper por causa do react-popper. O ruim do `react-bootstrap` é que ainda tá em beta o suporte ao Boostrap 4. Por isso preferi o `reactstrap`.
