### ISSUE TITLE
Salarios injustos para dev front-end?

### ISSUE THREAD

**Issue by fernandoRj** [frontendbr/forum#1467]
Pessoal boa tarde, gostaria de saber a opiniao de vcs referente ao salario da nossa classe de dev front-end, sera que estamos sendo explorados ou os salarios estao justos de acordo com a oferta e a demanda da mao de obra?

em uma breve pesquisada na internet, vi que salarios de  cargos para pessoas formadas em administração e advogado, variam entre 2 mil e 4 mil reais, sendo que a oferta para essas vagas sao muito maiores do que para devs front-end, sem contar o fato de que para vc entrar no mercado de trabalho vc nao precisa de tanta experiencia como nos front-end onde vc so é de fato contratado apos passar por 1 processo seletivo e mostrar que vc tem experiencia, msm sem antes nunca ter atuado no mercado, isso se da ao fato da classe nao ser regulamentada e nao exigir um nivel superior para exercer a profissao?

**Comment by evertonthepaula** [comment]
Siga esse cara: https://www.youtube.com/watch?v=Qb5b8ZE9tIY&list=PLdsnXVqbHDUc7htGFobbZoNen3r_wm3ki&index=2

**Comment by adamfoerster** [comment]
Salários variam bastante de cidade para cidade. Normalmente cidades menores ou menos desenvolvidas tem salários mais baixos. O custo de vida na cidade também influencia diretamente.

Em Curitiba, após olhar no LoveMondays (atualmente Glassdoor) acredito que o salário de um dev front iniciante fica na faixa de R$ 3500, no mínimo. Um dev experiente consegue o dobro fácil. Tem muita empresa oferecendo menos que isso, mas o mercado está aquecido. Se oferecerem menos vai pra próxima.

E quanto as empresas não contratarem profissionais sem formação superior, acredito ser verdade somente em empresas muito engessadas e retrógradas. Já trabalhei com muitos colegas sem formação superior em três empresas diferentes.

**Comment by kivervinicius** [comment]
Cara, aqui no MT é diferente, as cidades do interior pagam melhor que as da capital, tipo no mínimo aqui um dev bom (front-end) ganha 7k fácil, eu mesmo ganho bem mais q isso

**Comment by barraponto** [comment]
Depende da oferta tb. Se vc se especializa no framework da época (angular, react, vue) vc ganha mais do que se vc se especializa no wordpress.
