### ISSUE TITLE
Discord Svelte Brasil

### ISSUE THREAD

**Issue by adamfoerster** [frontendbr/forum#1472]
Olá pessoal.

O framework Svelte tem rapidamente conquitado os corações da galera com sua sintaxe elegante e sua velocidade ultra-rápida.

A comunidade em torno da lib se reune num canal do Discord chamado Svelte. No entanto este canal tem discussões apenas em inglês, e devido ao rápido aumento da popularidade da versão 3 do Svelte, o número diário de mensagens tem sido muito alto.

Pensando em meus colegas lusófonos criei um canal para a comunidade brasileira se ajuntar. 
[Svelte Brasil](https://discord.gg/heuYm7)

**Comment by felipefialho** [comment]
Tenho olhando esse framework com bastante atenção 👀

**Comment by didiraja** [comment]
Na Stone Co, o framework usado pra fazer os apps é o Svelte 2. Só ele foi suportado na maquininha que usamos.

Foi feito teste com React, Vue e Preact mas o Svelte venceu com folga pela performance.

**Comment by adamfoerster** [comment]
O convite que mandei acima expirou. Criei um novo que não expira [Svelte Brasil](https://discord.gg/Xf9zzW9).

**Comment by rodrigocode4** [comment]
A sintaxe é realmente incrível, estava olhando a doc e adorei o esquema de tutorial que é na mesma pegada do freeCodeCamp
