### ISSUE TITLE
Codificaçao e cannabis

### ISSUE THREAD

**Issue by fernandoRj** [frontendbr/forum#1483]
Acabei de assistir a um documentário chamado Grass is Greener na Netflix. Fala sobre as coisas que rodeiam a cannabis. Como os políticos demonizaram, apesar das evidências científicas.

No entanto, ao longo do documentário, ouvimos muitos testemunhos de vários artistas, como músicos de jazz, artistas de hip-hop e rap e compositores. Diferentes gerações de artistas se vêem mais criativos quando estão em chapados. Obviamente, a pergunta deve ser feita:

Você já codificou enquanto estava chapado? Qual foi o resultado?

Por favor, não fale de politica sobre este assunto. Minha pergunta diz respeito ao efeito sobre a cannabis em sua produtividade como desenvolvedor. Suas opiniões sobre se a cannabis deve ser legalizada ou não são irrelevantes aqui. Obrigado :)

**Comment by fernandoRj** [comment]
eu tenho mt problema de ansiedade entao tem vez que quando vou programar alguma coisa fico mt inquieto me distraindo facilmente, quando fumo um, eu fico mais relex, minha mente foca so em um assunto e a tarefa que eu estou realizando fica mais prazerosa, mais e claro eu nao fumo pra ficar de cara torta mega chapado, pq se isso acontecer vc provavelmente n vai ter uma boa experiencia quando for programar. e atualmente estou trabalhando em freelas, nao trabalho em nenhuma empresa obviamente que posso ficar mais a vontade dentro de casa sem ter que lhe dar com regras empresariais

**Comment by rafaelcavalcante** [comment]
Costumo perder o foco com um pouco mais de facilidade, mas quando isso não acontece me sinto produtivo.

Boa sorte com o lance de não colocarem política no meio, rs.

**Comment by didiraja** [comment]
Se tiver pouco chapado dá pra ajudar com o foco né, já teve momentos que ajudou a me debruçar sobre o código.

Mas a maioria da vezes foi como o rafael disse, acabei preferindo estar completamente sóbrio pra garantir que trabalharia com agilidade para exercutar as tarefas.

Com projetos pessoais, talvez seja divertido por permitir fazer algo que você gosta e no seu ritmo.

**Comment by mateussmohamed** [comment]
Comigo não funciona. As únicas vezes em que fui produtivo codando após o uso de cannabis, foi quando utilizei alguma espécie indica. No geral eu gosto de trabalhar sóbrio, e após o trampo eu faço o uso.

**Comment by felipefialho** [comment]
@fernandoRj não vejo problema em manter a issue aberta.

**Comment by gustavokozlowski** [comment]
Amo codar chapado e estudar tbm pois parece que a matéria ganha vida e se torna mais incrivel.  Mas se chapar demais eu fico meio perdido rsrs
