### ISSUE TITLE
Como criar paginas Web automaticamente de acordo com quantidade de equipes no banco de dados? Faça

### ISSUE THREAD

**Issue by MatheusCoxxxta** [frontendbr/forum#1485]
Boa noite, preciso tirar essa dúvida urgente para dar continuidade no meu TCC. O projeto é basicamente um sistema php dividido em duas partes, usuário comum e administrador. A ideia do projeto é gerir e divulgar dados de uma competição esportiva da seguinte forma: O administrador cria um novo campeonato e indica a quantidade de equipes. Com o evento criado, será criada uma pagina para editar informações de cada equipe.

As informações registradas pelo administrador (nome do novo evento, quantidade de equipes) serão adicionadas a um banco de dados.

Como faço para criar as paginas php automaticamente de acordo com a quantidade de equipes indicadas pelo administrador (que já estão inseridas no banco de dados)?

Informações importantes:

- A pagina que será criada automaticamente deve conter alguns textos como "Nome da Equipe" que serão editáveis pelo administrador;

- Será utilizado banco de dados MySQL.

**Comment by rwerlich** [comment]
Bom dia.

Faça um cadastro para as equipes respeitando a quantidade de equipes da competição.

Para exibir as equipes você cria um rota /equipe/{id} onde pelo id você faz a busca no banco e gera a página com os dados daquela equipe.

**Comment by MatheusCoxxxta** [comment]
Bom dia, obrigado pela atenção.

Não entendo como gerar multiplas páginas automaticamente de acordo com id. Pode exemplificar com código (php) para mim?

**Comment by diego-lang** [comment]
Bom dia @MatheusCoxxxta.
Acho que você está fazendo algum tipo de confusão mental sobre a geração de páginas, o @rwerlich já explicou como deve ser feito, mas vou tentar deixar mais didático para você:
Você terá na sua aplicação uma rota (url) para o campeonato criado e dentro do campeonato você terá a listagem das equipes participantes. Ao clicar no nome da equipe você terá uma outra rota que trará as informações dela cadastrada, para você obter essas informações você terá que passar o id através da rota, como citado pelo colega acima (rota /equipe/{id}).
As página irá ser gerada de acordo com o id que você solicitar, elas não serão geradas todas de uma vez. Não tenho certeza, mas aparentemente essa é a confusão que está fazendo.

**Comment by vmnog** [comment]
Como iniciante e estudante de php, vou tentar explicar de forma mais próxima do que  a gente entende.

Vamos ao exemplo:

Na home:
-localhost/index.php // aqui vai ter o formulario perguntando as informacoes
input: nome do campeonato?
input: qtd equipes?
input: submit >> 

quando for feito o submit:
-localhost/{id_campeonato}/equipes.php // aqui vao ser listados as equipes geradas de acordo com o numero

quando voce clicar pra editar uma dessas equipes voce vai ser redirecionado pra outro link
-localhost/{id_campeonato}/equipes.php/equipe={id_equipe}

// nessa pagina vao ser listadas as informacoes da equipe que foi passada o seu id pelo {id_equipe}
-
-
-
Enfim, eu sou aprendiz tambem, e avaliando sua duvida acredito que tambem seja, com certeza tem diversas outras maneiras de se fazer isso, mas caso eu fosse fazer este projeto eu tentaria assim por se tratar de algo simples a principio.

**Comment by MatheusCoxxxta** [comment]
Muito obrigado galera. Não estou totalmente esclarecido, já que não testei nada do que me recomendaram ainda, mas me ajudaram muito. Obrigado mesmo :)
