### ISSUE TITLE
Mover scrollbar para fora da div com CSS

### ISSUE THREAD

**Issue by matheusberns** [frontendbr/forum#1488]
Boa tarde,

Preciso mover a scrollbar de uma div pra fora dela, no caso dar uma "margem" pra esquerda para que eu possa esconder ela e aumentar a mesma, com o intuito de adicionar dois botões em cima do scroll para que funcionem como botões de scroll.

**Segue o exemplo de o que quero fazer:**

![SCROLLBAR](https://user-images.githubusercontent.com/52710907/61137911-cea0aa00-a49c-11e9-9434-c899ee8068f3.PNG)

**Abaixo o protótipo que estarei montando logo após mover o scroll para fora da div:**

![Capturar](https://user-images.githubusercontent.com/52710907/61137957-eb3ce200-a49c-11e9-9a8d-faff8fae40b9.PNG)

Agradeço desde já!

**Comment by Juuhz** [comment]
http://jsfiddle.net/suvngL84/

Fiz um exemplo aqui para você, qualquer coisa, me fala que explico linha a linha. 

OBS: O segredo para esconder seu scrollbar é o `overflow: hidden;`.

Abraços dev.
