### ISSUE TITLE
Job para SP: Frontend/Webmaster para projeto pontual para as olimpíadas

### ISSUE THREAD

**Issue by leandroruel** [frontendbr/forum#149]
estou repassando uma vaga que recebi, caso tenham interesse em saber mais, liguem: 11 3044-7633.

a pessoa irá atuar em Alphaville de segunda à sexta, horário comercial até o mês de julho.

**Comment by viniciusdocanto** [comment]
Não vai rolar uma descrição da vaga, pra pessoa não ligar atoa?

**Comment by leandroruel** [comment]
pronto @viniciusdocanto :smile:

**Comment by LFeh** [comment]
Cara, posta no Vagas ;) 

https://github.com/frontendbr/vagas

**Comment by leandroruel** [comment]
@LFeh mals
