### ISSUE TITLE
Solucoes baratas/free para URL Preview

### ISSUE THREAD

**Issue by camillodev** [frontendbr/forum#1493]
Oi, galera. 
To precisando pegar dados de um link qualquer, como imagem da origem do site. E nao queria fazer na mao. To procurando uma solucao ja usada.
Um exemplo é o que o whatsapp faz quando voce posta o link em uma conversa, ele gera um titulo, imagem e um pouco da origem. 
To procurando algumas opcoes escalaveis para esse problema, caso possam me ajudar. 

Ja achei a opcao da Microsoft, porem é um pouco cara somente para a URL Preview.

**Comment by vhfmag** [comment]
Tem o metascraper (https://metascraper.js.org/). É uma lib, não um serviço, então não sei se atende seu caso. De qualquer maneira, é bem simples e não deve ser complicado fazer um microsserviço pra isso no glitch.com.

**Comment by camillodev** [comment]
Super obrigado, é exatamente isso.

**Comment by vhfmag** [comment]
Massa! :)
