### ISSUE TITLE
Trabalho no exterior, como é?

### ISSUE THREAD

**Issue by Juuhz** [frontendbr/forum#1495]
Fala Devs, 

Sou desenvolvedor a cerca de 6 anos, tenho bastante experiência agregada e agora com a ascensão do mercado com os Front-Ends, venho recebendo bastante proposta no linkedin de empresas que buscam desenvolvedores para alocar nas Europas. 

Gostaria de levantar uma discussão para troca de figurinhas e experiências.

Você trabalha no exterior? Onde? Como é? Vale a pena? Dicas? Conta aê pra nós. 

Abraços.

**Comment by hmilena** [comment]
Vê: [](https://github.com/frontendbr/forum/issues/56)

**Comment by Juuhz** [comment]
Valeu @hmilena, mas é Início de 2016, hoje, em 2019 o mercado mudou bastante.

**Comment by hmilena** [comment]
@Juuhz eita, verdade! Mas tem muita info muito massa lá, ainda relevante.

**Comment by Juuhz** [comment]
Sim sim, dei uma lida e peguei bons feedbacks.

Em sex, 19 de jul de 2019 17:22, Mia <notifications@github.com> escreveu:

**Comment by felipefialho** [comment]
Pelo tamanho e importância da outra issue, acho interessante concentrar a discussão lá :)
