### ISSUE TITLE
Array.includes(Array)

### ISSUE THREAD

**Issue by JorgeBaes** [frontendbr/forum#1496]
Eu estou aprendendo a programar, e estou com um projeto bem simples de IA no jogo da velha. É um tipo de IA diferente e bem simples. Porém, estou com um problema e não consigo resolvê-lo.
Como eu programei, primeiramente esta IA em python, e em python este recurso era possível, achei que em javascript funcionaria também, mas não funcionou.
O problema é o seguinte: eu tenho uma array1 dentro de uma array2, e preciso verificar se a array 1 está dentro da array 2. Pra isso eu recorri ao método Array.includes(element), que retorna true ou false, porém não funciona. O que me surpreendeu também é que em javascript, comparações de arrays dentro de arrays não funcionam também. Veja o código:

a = [ [1,2,3] , [0,0,0] ]
console.log(a[0]==[1,2,3])
// RETORNA false

console.log(a.includes([1,2,3]))
// TAMBÉM RETORNA false

Também tenho o mesmo problema com o método Array.indexOf(element).
Alguém saberia me dizer se há algum método que resolva isto, ou se isto é impossível em javascript (acredito que não)? 
Obrigado pela ajuda!!

**Comment by vhfmag** [comment]
Isso acontece porque em Javascript, quando ambos os operandos são objetos, os operadores `===` e `==` não comparam seus valores, mas se ambos são referências ao mesmo valor. 

Então se você criar uma nova variável (`arr2`) que aponte pra variável original (`arr1`), `arr1 === arr2` é `true`:

```js
const arr1 = [1, 2, 3];
// arr2 é uma referência para o valor de arr
const arr2 = arr1;
console.log(arr1 === arr2); // true
```

Mas se você instanciar um novo array a nova variável (`arr3`) vai apontar para um valor novo (digamos que pra um novo endereço na memória), se referindo a um valor diferente da variável original, e sendo por isso diferente (`arr3 !== arr1`):

```js
// arr3 é uma referência a um novo valor
const arr3 = [1, 2, 3];
console.log(arr1 === arr3); // false
// ou ainda
console.log(arr1 === [1, 2, 3]); // false
console.log([1, 2, 3] === [1, 2, 3]); // false
```

**Comment by vhfmag** [comment]
Sobre ser possível fazer isso em Javascript, você pode usar uma função, como essa:

```js
function arrayEqual(arr1, arr2) {
  return arr1.length === arr2.length && arr1.every((el, i) => el === arr2[i]);
}

const arr1 = [1, 2, 3];

const arr2 = arr1;
console.log(arrayEqual(arr1, arr2)); // true

const arr3 = [1, 2, 3];
console.log(arrayEqual(arr1, arr3)); // true

console.log(arrayEqual(arr1, [1, 2, 3])); // true
console.log(arrayEqual([1, 2, 3], [1, 2, 3])); // true

// valores diferentes
console.log(arrayEqual([1, 2, 3], [1, 2, 4])); // false
// tamanhos diferentes
console.log(arrayEqual([1, 2, 3], [1, 2, 3, 4])); // false
```

E você poderia usar ela com `.findIndex` pra substituir `.includes` e `.indexOf`:

```js
const arr1 = [1, 2, 3];
const arrArr = [[1, 2, 3], [0, 0, 0]];

// includes
console.log(arrArr.findIndex(el => arrayEqual(el, arr1)) != -1); // true
console.log(arrArr.findIndex(el => arrayEqual(el, [1, 2, 3])) != -1); // true
console.log(arrArr.findIndex(el => arrayEqual(el, [1, 2, 4])) != -1); // false

// indexOf
console.log(arrArr.findIndex(el => arrayEqual(el, arr1))); // 0
console.log(arrArr.findIndex(el => arrayEqual(el, [1, 2, 3]))); // 0
console.log(arrArr.findIndex(el => arrayEqual(el, [0, 0, 0]))); // 1
console.log(arrArr.findIndex(el => arrayEqual(el, [1, 2, 4]))); // -1
```

**Comment by JorgeBaes** [comment]
Muito Obrigado Vitorr!! Valeu mesmo. Funcionou direitinho, obrigado pelo aprendizadoo!
