### ISSUE TITLE
Problema de performance em uma aplicação em lottie

### ISSUE THREAD

**Issue by susymartinelli** [frontendbr/forum#1498]
Olá galera, 

O meu time está com um problema de performance. Eles criaram uma aplicação web com o background em PNG, e as animações em lottie em SVG. 
A aplicação se trata de um mapa animado, que contém popups e um quiz, onde faz escalação para ter uma sensação de zoom de uma cena a outra para identificar cada ponto no mapa, e fazemos isso para toda a aplicação. E toda vez que fazemos a transição de uma cena para outra, as vezes acaba ficando com tela preta ou branca. Além disso, demora para carregar, tivemos que colocar um loading no início. 
E com o background em SVG a aplicação tornou-se mais pesada e a performance caiu. 
Portanto, cada navegador responde essa performance de uma maneira diferente, assim como cada máquina, dependendo se ela é boa ou não, também tem um comportamento diferente. 
Já usou a solução de colocar uma imagem estática com blur entre as transições para melhorar e performance, mas mesmo assim, ainda aparece as telas pretas. 
Tentou também fazer a transição apenas com o background estático, mas sem o lottie, e a performance ficou pior. 

O que podemoos fazer?

**Comment by lhbzr** [comment]
O loading acaba fazendo parte de uma aplicação com Lottie mesmo, geralmente os JSONs chegam a pesar quase 2 MB em alguns casos então não tem jeito.

Mas acho que a otimização nem sempre tá no lado do Front End, o Designer que está fazendo as animações no Illustrator também precisa remover alguns elementos extras e alguns tipos de animações.

Notei que você comentou sobre blur, geralmente esse tipo de animação é uma das mais pesadas para serem processadas pelo browser, então se vocês removerem talvez tenha um ganho de performance muito grande.

Não sei se pode ajudar, mas o último projeto em Lottie que trabalhei foi esse [TIAA Quiz](https://quiz.tiaa.org/), então talvez usar de base para arrancar alguns efeitos possa ajudar.

**Comment by susymartinelli** [comment]
Não posso compartilhar, por termos de confidencialidade, mas se pudesse visualizar mentalmente, uma animação com carrinhos em movimento, trens, aviões e prédios estáticos ao fundo, uma cidade mesmo, e entre as transições ou fica com tela preta ou muito lenta a aplicação. E quando passamos de um ambiente para outro, aparece popups com explicações. 
Mas sobre as transições com blur, elas aparentemente ficaram melhores que as transições sem blur, pois as transições sem blur, tinham movimentações, e a imagem com blur era estática, dando a sensação de zoom entre uma cena e outra.

**Comment by lhbzr** [comment]
Entendi, acho que a quantidade de elementos também pode estar prejudicando um pouco a animação, será que vocês conseguem separar em vários JSONs diferentes e posicioná-los na tela para ter a mesma sensação? Talvez possa ajudar um pouco, pois um JSON muito grande acaba ficando muito pesado para o Lottie gerenciar.
