### ISSUE TITLE
FEMUG-SP #32 - Meetup de front-end em São Paulo sobre 'RAIL Performance Model'

### ISSUE THREAD

**Issue by marcelgsantos** [frontendbr/forum#150]
No dia 19/05, quinta-feira, vai acontecer o FEMUG-SP *#*32 na [Caelum](https://www.caelum.com.br/) a partir das 20h, perto do metrô Vila Mariana.

Nesta edição o @sergiolopes falará sobre [RAIL Performance Model](https://developers.google.com/web/tools/chrome-devtools/profile/evaluate-performance/rail). O limite é de **60 pessoas**, então corra para garantir sua vaga! 

Mais informações em https://sp.femug.com/t/femug-sp-32-caelum/6991.

Abração e vejo vocês lá! :wink:

**Comment by LFeh** [comment]
Fala Marcel,

Posta o evento aqui \o https://github.com/frontendbr/eventos
