### ISSUE TITLE
[React] - react-testing-library ou enzyme ?  qual vocês acham melhor ?

### ISSUE THREAD

**Issue by mayconbalves** [frontendbr/forum#1501]
Até o momento fiz testes usando o `chai` há algum tempo, atualmente utilizo o `enzyme` , mas muitas pessoas estão recomendo uma nova lib chamada `react-testing-library` que está sendo muito bem aceita pela comunidade no geral, gostaria de saber a opinião de vocês e experiências com essa nova lib.

**Comment by lucasbento** [comment]
+1 pra `react-testing-library`, o foco é você testar o app do jeito que o seu usuário usa ao invés de testar implementações.

Eu trabalho bastante com React Native e com `enzyme` rola muita coisa de ter que chamar o método da classe diretamente usando `instance()` e isso vira algo muito complexo quando você precisa refatorar seu component.

**Comment by ninetails** [comment]
+1 `react-testing-library`

(São opiniões pessoais)

Para mim fez muito sentido quando comecei a usar. É meio que baseado num movimento (vulgo _hype_) que diz que é mais eficaz [testar _comportamento_ que testar _implementação_](https://lmgtfy.com/?qtype=search&q=test+behavior+not+implementation), junto com o ["Escreva testes. Não muitos. Mas mais de integração"](https://medium.com/@sergioamjr91/escreva-testes-n%C3%A3o-muitos-mas-mais-de-integra%C3%A7%C3%A3o-7ebebf225516). E _shiftar_ o pensamento que unidade de teste não necessariamente precisa ser de código (classes, métodos, funções), e sim unidade da aplicação.

Gostei da lib pois é praticamente um _e2e_ pra componentes mas sem ter que abrir um browser (ele usa `jsdom` por trás direto no _Jest_) e dependendo do componente, acaba praticamente sendo de integração pois algumas vezes certos testes podem ficar redundantes fazer num componente pai e depois quebrar o mesmo teste pra cada componente filho. Fora que testar comportamentos me faz muito mais sentido atualmente que testar o que cada função faz (ex: mais fácil dizer "teste clicando nesse botão tem que adicionar um texto específico numa div" que ter que testar cada um individualmente, ou seja, testando implementação).

E mesmo todo mundo falando pra não dar muita importância pra _coverage_, este acaba se tornando um indicativo de que falta teste ou é código desnecessário, e muita das vezes acabava sendo o segundo (claro, falando específicamente de React, não de "módulos" vanilla), o que não era tão visível quando testava usando **shallow** <sup><sub>~now e juntos~</sub></sup> **render** do `enzyme` já que com ele eu testava de tudo.

Pra ajudar a escrever testes comportamentais, tem os _matchers_ do [jest-dom](https://github.com/testing-library/jest-dom) (_matchers_ do tipo `toHaveTextContent` 😃 ).

> [Talks do Kent C. Dodds sobre o assunto](https://applitools.com/blog/confident-react-kent-c-dodds-speaks-about-frontend-testing)
