### ISSUE TITLE
Rolar a página com CSS, ou JavaScript

### ISSUE THREAD

**Issue by JorgeBaes** [frontendbr/forum#1504]
Eu tenho uma div, que ao passar o mouse em cima ela aumenta sua altura,. O efeito visual é que ela expande para baixo. Porém eu queria que ao passar o mouse em cima, a div expandisse para baixo e a página desse scroll para baixo para acompanhar a expansão da div.

```
div#exp:hover{
            height: 560px;
            background: rgb(81, 133, 245);
}
```

Tem como criar isto com CSS, ou JavaScript?

**Comment by AdrianoLupossa** [comment]
Sim, tem. Você pode adicionar um scroll na página, com js.

Com Javascript: 

document.querySelector("div#exp").addEventListener("hover", function() {
   document.body.scrollTo (0, 500);
});

Explicação: Quando você passar o mouse em cima do elemento div#exp, o javascript vai activar o scroll vertical(Y) da página.
Recomendo fazer o efeito todo em javascript.

Documentação do método ScrollTo: (ScrollTo)[https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo]

**Comment by JorgeBaes** [comment]
Obrigado, deu certo. Só uma correção, que sua sintaxe não está correta. Na sintaxe do addEventListener não há hover.  Tem de usar mouseenter, ou mouseover
Também o que eu achei que deu certo foi window.scroll, ou window.scrollTo.

 Então no caso, o certo seria 
document.querySelector("div#exp").addEventListener("mouseenter", function() {
            window.scroll({top:1400,behavior: 'smooth'});
});
]////////////////////////////////OUU////////////////////////////////////////
document.querySelector("div#exp").addEventListener("mouseenter", function() {
           document.getElementById("exp").scrollIntoView({behavior:"smooth"});
});

Eu achei melhor usar o scrollIntoView() porque ele arrasta direto para o elemento selecionado, e não precisa dar a altura ou a posição, e o  scrollIntoView({behavior:"smooth"}); deixa o scroll menos 'agressivo'.

Valeu pela resposta. Aprendemos muito com esta dúvida

**Comment by felipefialho** [comment]
@JorgeBaes pra facilitar a visualização do código, tenta usar o `md` ` ``` ` para criar os blocos ;)
