### ISSUE TITLE
Um passo atrás para dar dois a frente? [JS]

### ISSUE THREAD

**Issue by renanlbl** [frontendbr/forum#1508]
Fala galera, sou desenvolvedor front-end Júnior em uma empresa que ainda utiliza Jquery, RequireJS em seus sistemas e atualmente na plataforma em que trabalhamos (MOODLE) é muito dificil implementar o babel, então basicamente é sintaxe do JQUERY + ES5...

* Mas blz, que que tem?

Então, antes de conseguir esse emprego, eu já tinha estudado  Jquery e ES5; 
E depois que me senti confortável fui pro ES6 e logo em seguida fui pro ReactJS e VueJS e fiz alguns projetos com essas tecnologias, tudo por treino, porque o que eu mais via era vaga de Front-end que manjasse de ReactJS e VueJS... 

E agora que estou trabalhando com uma versão mais antiga do JS, eu vi que não manjava tanto de Javascript quanto parecia, tudo que esses frameworks facilitam, é mais dificil reproduzir lá... (Spa, Modularizar... etc) 

* E o problema? 

Visando o mercado futuramente, eu vejo que cada vez mais as empresas vão optar por novas tecnologias, frameworks, librarys... e eu não quero perder a crista da onda e ficar pra trás... mas eu cegamente acabei optando por estudar o ES5 afundo pensando que isso me ajudará a entender as novas tecnologias e tal, mas fico pensando que seria perca de tempo, pois já consigo fazer alguns sistemas utilizando ReactJS e VueJS e se for parar pra ver o create-react-app já vem com webpack/babel configurado e o vue-cli também já vem com o babel configurado... **então afinal até que ponto estudar ES5 afundo vai me ajudar a entender melhor essas novas tecnologias?**

**Comment by bernardodiasc** [comment]
@renanlbl as empresas pedem conhecimento e experiencia em frameworks pq, bem, são uteis. Mas o que importa pra ser um bom profissional é dominar os fundamentos. Voce não vai estar de modo algum perdendo tempo estudando JS vanilla, ES5, etc. Na verdade vai ser tornar um desenvolvedor muito mais capaz quando conseguir fazer um app funcional sem usar nenhum framework, pq só assim vai entender os propósitos das ferramentas, alem de que vai dominar a linguagem e conceitos de arquitetura.

**Comment by danilovaz** [comment]
Partilho da visão do @bernardodiasc . Não seja dominado pelo framework, você deve dominar ele. É bem coach hauahuhua mas é real, cara.

Você pode até entender React, Vue, Angular, Ember etc agora, mas em algum momento você vai precisar tomar alguma decisão técnica que vai exigir um melhor conhecimento do JavaScript e não das abstrações do Framework.

Framework é só uma abstração. Por trás é tudo JavaScript. Então nunca pare de estudar o JavaScript em si. E aí cada vez mais você vai estar confortável em trabalhar tanto em projeto legado quanto em novos projetos.

> então afinal até que ponto estudar ES5 afundo vai me ajudar a entender melhor essas novas tecnologias?

Sem estudar o JavaScript (é legal estudar ES5, ES2018, ES2019 whatever, mas estude independente da versão) você será sempre refém das abstrações dos frameworks e nunca vai entender o que tá rolando de baixo dos panos.

Eu indico esse livro: https://github.com/cezaraugusto/You-Dont-Know-JS

**Comment by renanlbl** [comment]
Muito obrigado senhores, @bernardodiasc, @danilovaz...

Eu tô estudando ES5 afundo mas estava nessa dúvida se seria válido ou não, mas agora tenho crtz que valerá a pena xD

E esse livro ta nos planos @danilovaz, logo após eu terminar de fazer o curso Js ninja do Fernando daciuk eu vou estudar com esse livro...

**Comment by danilovaz** [comment]
@renanlbl Oxi, só com o curso do @fdaciuk não precisa de mais nada ❤️ 

Bons estudos, cara 🚀 👊

**Comment by fernandoRj** [comment]
galera vcs n acham perca de tempo estudar o es5? ele esta obsoleto nenhum projeto hoje em dia e feito em es5, ainda mais com os frameworks, se for para vc gastar tempo e energia aprendendo uma versao obsoleta do javascript nao seria melhor logo estudar o es6?

**Comment by bernardodiasc** [comment]
@fernandoRj é perda de tempo usar ES5 em projetos de produção, **aprender não é** pois mesmo o ES6 nada mais é que abstrações em cima do ES5, entende? Aprender não é perda de tempo, é importante que a diferença em trabalho e estudo fiquem bem definidas nas suas práticas. Vai no site do Babel e na caixinha que tem logo no inicio manda um código com ES6 lá, digamos usando destructuring, vai ver que o código transpila pra ES5, se quer dominar a linguagem precisa conseguir entender o código transpilado, naturalmente.

**Comment by fdaciuk** [comment]
@fernandoRj 
o @bernardodiasc disse tudo!
ES6 não é uma nova linguagem, são apenas ADIÇÕES em cima do que já existe na linguagem (a base é o ES5) :)
