### ISSUE TITLE
Internacionalização em vue 

### ISSUE THREAD

**Issue by mateusortiz** [frontendbr/forum#1509]
Opa Galera,

_Me apresentando rapidamente sou frontend dev de inovação de uma startup em Curitiba_, e estamos pensando em internacionalização(i18n), o produto é um erp na núvem, e precisamos deixar fácil esse controle da internacionalização no nosso painel administrativo do sistema, para qualquer pessoa conseguir alterar esse localização de idioma.

Sei que já existe uma pergunta aqui sobre internacionalização, mas queria ver os pontos usando o vue, e se faz mas sentido no backend ou no frontend

**Comment by brunosantanarj** [comment]
[Aqui](https://nuxtjs.org/examples/i18n) tem um exemplo de internacionalização e Server Side Rendering com Vue. 

Há uns 2 anos atrás usei essa abordagem de SSR com Nuxt e um dos requisitos era a internacionalização, funcionou bem na época.

Se faz mais sentido fazer isso no backend ou frontend pode depender de qual padrão está usando para renderizar suas páginas.

**Comment by nandomoreirame** [comment]
acredito que qualquer formatação visual para o cliente (seja linguagem, datas, moedas, etc) fica sob responsabilidade do front-end... é que depende bastante de como tá estruturada a aplicação tbm, mas não acho certo fazer requisições na API para traduzir textos... pensando em aplicações que usam MVC (RoR, Laravel, e outros) o i18n fica sob responsabilidade da View, mesmo sendo renderizada no server-side 😄 

#meus10centavos

**Comment by nelsonmfinda** [comment]
> acredito que qualquer formatação visual para o cliente (seja linguagem, datas, moedas, etc) fica sob responsabilidade do front-end... é que depende bastante de como tá estruturada a aplicação tbm, mas não acho certo fazer requisições na API para traduzir textos... pensando em aplicações que usam MVC (RoR, Laravel, e outros) o i18n fica sob responsabilidade da View, mesmo sendo renderizada no server-side 
> 
> #meus10centavos

@nandomoreirame Pelo que entendi, seria uma boa opção implementar ***internacionalização*** via ***i18n*** no _frontend_ certo?

**Comment by alvarengathomas** [comment]
Temos diversos projetos em Vue e todos eles tomam conta da internacionalização sem depender do backend, utilizamos [vue-i18n](https://github.com/kazupon/vue-i18n)

**Comment by kavalcante** [comment]
Galera, em aplicações de grande porte. Vocês ainda lidam com a internacionalição via arquivo JSON? O vue-i18n já lida com implementações buscando em BD?

**Comment by eliseumds** [comment]
Eu recomendo utilizar alguma biblioteca com suporte à sintaxe ICU onde você pode formatar plurais, data, tempo e números com uma API só. Infelizmente não conheço uma solução completa pra Vue com extração automática das mensagens. De fato, parece que todas bibliotecas são imaturas :S

@kavalcante num mundo ideal a extração seria automática via BabelJS. É o que eu faço mas uso React.

**Comment by eliseumds** [comment]
@kavalcante sim, via arquivos JSON (gerados a partir dos arquivos PO devolvidos pelos tradutores). Se a aplicação for mesmo gigante, a ideia é acoplar as mensagens aos componentes (mesmo esquema de CSS files) e fazer lazy-load desses arquivos JSON que seriam gerados automaticamente. Claro que essas mensagens podem ser carregadas do servidor também, mas aí você tem que garantir a versão correta e definir se vai carregar tudo de uma vez no começo e carregar em chunks.

**Comment by lucasferreiralimax** [comment]
> Galera, em aplicações de grande porte. Vocês ainda lidam com a internacionalização via arquivo JSON? O vue-i18n já lida com implementações buscando em BD?

Creio que o vue-i18n sempre foi agnóstico com a forma que implementa os arquivos, seja eles em formato json, object js ou em uma requisição no BD.
