### ISSUE TITLE
Como criar atalhos de teclado combinados com eventos de click do mouse?

### ISSUE THREAD

**Issue by renedocket** [frontendbr/forum#1511]
Olá pessoal, tudo bem?

Eu estou com dificuldade de montar atalhos de teclado e combiná los com eventos de clique do mouse, procurei como fazer em JS Vanilla mas não encontrei muitos conteúdos que pudessem me ajudar. 

Gostaria por exemplo de combinar a tecla **CTRL + Click**, você já passaram por algo do tipo e como fizeram pra resolver?
 
Agradeço desde já! :)

**Comment by felipemfp** [comment]
O `MouseEvent`, o que é recebido no seu listener, tem propriedades que indicam quando o <kbd>Ctrl</kbd>, <kbd>Shift</kbd> ou <kbd>Alt</kbd> estão pressionado.

Documentação: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent
Exemplo: https://codepen.io/felipemfp/pen/XWrdqza

**Comment by renedocket** [comment]
Fala felipe! Funcionou cara o que estava querendo fazer, muito obrigado! :+1:
