### ISSUE TITLE
Alguém fez ou está fazendo o bootcamp da Rocketseat? É bom mesmo?

### ISSUE THREAD

**Issue by MaiconJordan** [frontendbr/forum#1512]
Estou começando no front-end estudando muito JavaScript e não quero perder o embalo, alguem que ja fez ou está fazendo o curso da Rocketseat tem algum testemunho para dar sobre esse curso? Pois os que eu vi na Udemy são muitos superficiais, getalmente os "professores" da Udemy são programadores e não professores então eles nao tem uma didática muito boa, os cara sabem programar mas não sabem ensinar. Quero adotar um framework e vi que React está em alta hoje em dia. 

- [ Duvida ]

**Comment by will3g** [comment]
É um ótimo curso!
A didática é enxuta e direta, fica bem fácil de você fazer alguns resumos das aulas para relembrar quando for preciso. A Stack da Rocketseat é massa demais, e os projetos que você vai aprender a fazer no decorrer do curso são melhores ainda. Pena que ontem foi o último dia de inscrição.

Em 16 de ago de 2019 1:05 PM, Maicon Jordan <notifications@github.com> escreveu:

Estou começando no front-end estudando muito JavaScript e não quero perder o embalo, alguem que ja fez ou está fazendo o curso da Rocketseat tem algum testemunho para dar sobre esse curso? Pois os que eu vi na Udemy são muitos superficiais, getalmente os "professores" da Udemy são programadores e não professores então eles nao tem uma didática muito boa, os cara sabem programar mas não sabem ensinar. Quero adotar um framework e vi que React está em alta hoje em dia.

**Comment by adeonir** [comment]
O curso é muito bom e vai direto na prática. Assiste os vídeos do Starter, é um material gratuito... uma prévia do bootcamp.

**Comment by gabriel-hahn** [comment]
Eu curti bastante o bootcamp, te da uma visão bem boa da stack e sobre as ferramentas utilizadas no mercado, focando na prática. Legal é que depois de completar o curso e ter uma base mais completa do assunto, tu pode ver os vídeos que a Rocketseat disponibiliza no Youtube falando sobre outras tecnologias e conteúdos mais avançados sobre alguns tópicos, te deixando ainda mais preparado para lidar com a stack ReactJS, React Native e Node. Não é um bootcamp que explora até as partes mais avançadas da tecnologia em todos aspectos, mas vai te dar uma base sólida para continuar estudando e evoluindo. Resumindo, se tu tem ideia de começar a trabalhar com React e cia, o investimento vale a pena.

**Comment by deppbrazil** [comment]
### Super recomendo o curso! :) ###

* E o legal é que tem a comunidade nos [Discord](https://discordapp.com/invite/gCRAFhc), ai da pra trocar muitas experiências... 

### Outros 2 na mesma pegada que indico também são: ###

* [CollabCode](https://collabcode.training/) Prof. [Marco Bruno](https://twitter.com/marcobrunobr)
* [DevPleno](https://www.devpleno.com/) Prof [Túlio Faria](https://twitter.com/tuliofaria)

**Comment by ViniciusGularte** [comment]
Pessoal vale a pena pra quem já trabalha a um tempo com a stack do curso? eu tava afim de comprar mas tava com medo de só rever conteúdo que já sei, ele é um curso mais iniciante, ou ele traz tópicos avançados dentro do mesmo?

**Comment by deppbrazil** [comment]
@ViniciusGularte Vale muito a pena mano, trás muitos tópicos avançados e o curso é atualizado com muita frequência. Os criadores do curso também fazem live com profissionais referências do mercado.

**Comment by lufemas** [comment]
Qual o valor dos cursos deles quando lançam?

**Comment by wilsonneto-dev** [comment]
Vale muito a pena, já fiz o Bootcamp, se não me engano paguei R$ 2,997 ou R$ 2,497, vale muito a pena!

Outro muito bom e com investimento mais baixo, e focado em React, é o Dev Pleno que sai por R$ 697,00:
Link dev pleno: [Curso Dev Pleno](https://go.hotmart.com/T14343972J)

Primeiro eu fiz do devpleno, e assim que consegui passar de backend para fullsstack investi no da Rocketseat para ficar mais afiado, mas ainda reviso muito ambos os cursos.

Inclusive estou fazendo esta semana omnistack.

Abraço, bons estudos e sucesso!

**Comment by lufemas** [comment]
> 
> 
> Vale muito a pena, já fiz o Bootcamp, se não me engano paguei R$ 2,997 ou R$ 2,497, vale muito a pena!
> 
> Outro muito bom e com investimento mais baixo, e focado em React, é o Dev Pleno que sai por R$ 697,00:
> Link dev pleno: [Curso Dev Pleno](https://go.hotmart.com/T14343972J)
> 
> Primeiro eu fiz do devpleno, e assim que consegui passar de backend para fullsstack investi no da Rocketseat para ficar mais afiado, mas ainda reviso muito ambos os cursos.
> 
> Inclusive estou fazendo esta semana omnistack.
> 
> Abraço, bons estudos e sucesso!

Obrigado pela resposta wilsonneto-dev,

E valeu pela outra indicação também. Você sabe ou já ouviu falar algo dos cursos da Danki Code? Está R$ 697 todos o pacote com todos os cursos do site deles.

Também estou fazendo essa semana o omnistack, por isso perguntei do preço, tenho certeza que deve ser excelente o material deles que irão vender depois. Mas nessa faixa de valor não vou conseguir.

**Comment by everton4292** [comment]
Entendo muito pouco de programação, bem iniciante, comecei a fazer esse desafio da omnistack e tenho aprendido bastante, mesmo sem muito conhecimento prévio, principalmente em JS. A questão é que sem nenhum conhecimento prévio é muito fácil errar a sintaxe e pegar um erro que te faz passar 2 horas procurando uma solução, quando o problema era um typo ou um ponto e vírgula. Acredito que depois vão fazer um bootcamp mais detalhado.

**Comment by adeonir** [comment]
@everton4292 no começo é assim mesmo, importante é não desistir!
Sobre a semana omnistack, ela funciona como uma prévia do que vai ser o bootcamp. Cada módulo do curso tem várias aulas explicando tudo que foi usado na semana...

**Comment by everton4292** [comment]
@adeonir então, como sou bem novo na área também não sei como funciona o bootcamp, sei que é um curso bem mais aprofundado mas pelo o que o cara falou ali achei o preço meio salgado, daí não sei se conseguiria me dedicar/aprender no mesmo nível em que estaria pagando. Tô fazendo alguns cursos no youtube, tal como os do cursoemvídeo, comprei e guardei o de javascript da udemy (pra depois), e tenho tentado me apropriar da linguagem que é utilizada no meio, que era uma das coisas que mais me deixava perdido.

**Comment by wilsonneto-dev** [comment]
Fala galera,
a aula do servidor, concluída, segue repositório caso alguém esteja com dificuldades:
https://github.com/wilsonneto-dev/Semana_Omnistack_9_Server_Node

Abraços!

**Comment by aglayrton** [comment]
Pessoal, estou fazendo o curso gratuito, é bem bacana, mas tipo, no pago da rockeseate, aprendemos a criar projetos como por exemplo, um site todo gerenciado, apps e por ai vai?

**Comment by expalmer** [comment]
Pensa assim, se você aprender algo no curso que custa R$ 3.000,00...tu vai pegar um JOB que te paga R$ 2.000,00 no mínimo, em 2 meses tu paga o curso...
Ou seja, vale

**Comment by luka-rmar** [comment]
Meu camarada, vale muito apena. O curso aborda do backend até o front. Há curso de Adonis, geolocalização, flex box e muito mais. Eu juntei uma grana e paguei a vista. Paguei R$1.7500. mas o curso não passa de R$2.000. 
Eles dão flexibilidade para pagamento. O projeto final e foda irmão. Vale muito à pena. Pode cair dentro.

**Comment by onlurking** [comment]
Estou fazendo o bootcamp da Rocketseat atualmente, finalizando o terceiro desafio no momento, cara, vou dar a minha opinião de pessoa extremamente chata.

Pra ter uma visão do ecossistema do React e pra entrar no mercado, o curso deles é ótimo sim e vale o investimento, fora a comunidade que é excelente!

Mas vamos a partes ruins:

### Qualidade de código

Não sei se é cruel esperar isso de um bootcamp, entretanto o Diego passa conceitos absurdamente errados, não apenas no curso Starter, mas como no Bootcamp inteiro na parte de nodejs. 

Eu geralmente não ligo tanto pra isso pois é normal cursos passarem por cima de conceitos de boas práticas para simplificar as coisas, entretanto, ele **advoca** em usar práticas erradas, como colocar toda a lógica da aplicação no Controller:<br>
![WhatsApp Image 2019-10-21 at 23 08 20](https://user-images.githubusercontent.com/10618352/68824108-7eb53800-0674-11ea-84a5-59b6eb1d94aa.jpeg)

E que o Controller também é responsável pelo CRUD:<br>
![WhatsApp Image 2019-10-21 at 23 12 58](https://user-images.githubusercontent.com/10618352/68824835-deacde00-0676-11ea-93f7-1e7505546de4.jpeg)

**A boa prática**: O *Controller* deve ser a parte mais simples de toda a aplicação, eles só são responsáveis em passar informação de uma view pra uma model, e vice-versa, elas devem apenas formatar dados, não devem possuir nenhuma lógica:
> In a well-designed MVC application, controllers are often very thin, containing probably only a few dozen lines of code; while models are very fat, containing most of the code responsible for representing and manipulating the data. - [Best MVC Practices](https://www.yiiframework.com/doc/guide/1.1/en/basics.best-practices#controller)
> 
> But the controller is in no way responsible for any form of business logic. If it was, it would mean, that you have a leaking abstraction, because the structures of presentation layer would be doing work, which should be in the model layer. - [Having MVC controllers light and models heavy](https://stackoverflow.com/questions/12012817/having-mvc-controllers-light-and-models-heavy)

Sobre linters, ele desativa várias rules do eslint durante o curso também(que são recomendadas), como o [no-param-reassign](https://eslint.org/docs/rules/no-param-reassign) e [class-methods-use-this](https://eslint.org/docs/rules/class-methods-use-this), a minha maior preocupação é ele ensinar a maneira mais conveniente que é desativar as regras e não ensinar a maneira correta.

### Didática (opinião pessoal :warning: )
Eu diria que o pessoal confunde boa dicção com didática, o Diego possui uma excelente dicção, mas os cursos deles não são tão acessíveis assim para iniciantes pois ele fala **muitos** termos técnicos, de maneira exagerada, todo o material da rocketseat é lotado de buzzwords.

Eu particularmente tenho um pouco de dificuldade de acompanhar os videos por causa disso, se você buscar material de fora pra entender o que ele fala você vai perceber que as explicações dele são bem razas, mas enfim, é um bootcamp rápido, então não sei até que ponto esse argumento é válido.

Vale a pena, vai sem medo, mas não se contente apenas com o material do curso, principalmente quando o assunto é qualidade de código.

**Comment by aglayrton** [comment]
Obrigado galera, estou pensando em seriamente em fazer o curso para criar projetos como CMS  e apps, até mesmo se ele tiver essa aula de consumir(O app consumir dados do site gerenciável) dados de um para o outro. Vou esperar o novo bootcamp.

**Comment by Marcelosilva10** [comment]
Eu estava com a mesma dúvida deles esses tempos, eu peguei um curso da Udemy, do Fernando Daciuk de Javascript, e estou achando um excelente conteúdo também. Tem muitos canais ótimos no Youtube mas com o Idioma em Inglês.

**Comment by malltapps** [comment]
Concordo em partes o que o onlurking falou, eu venho do curso javascript ninja do daciuk que é bem didático, e ainda assim fiquei meio perdidao, o diego tem boa oratório sim, mas ele usa sim muitos termos tecnicos e criou o bootcampo muito na experiencia pessoal dele, tipo eu acho meio dificil voce sair do bootcamp e aplicar o codigo do jeito que ele fez, pois a experiencia de codigo dele é muito avançada pra quem ta começando, outra coisa é que o backend que ele cria pro app é muito massante, da pra fazer um backend daquele nivel mais enxutinho e mais prático com mongodb, estou fazendo ainda o bootcamp mas em paralelo fazendo outros cursos de node, dessa forma pude perceber isso que citei, enfim  vai de cada um, claro que o curso é excelente, mas não é definitivo pra sua carreira, como falei, tem coisa que é bastante maçante que se voce nao estievr aberto a procurar solucoes mais simples voce acha que aquilo que voce viu ali é a unica fonte de verdade. Sucesso

**Comment by bbertolani** [comment]
Estou no bootcamp da Rocketseat tb.
@onlurking resumiu bem, mas acho que consumir conteúdo extras é normal, eu assisto algumas aulas, toma varias notas, pesquiso muito pra entender todo o conceito que ele está usando e muitas vezes tento entender porque foi feito daquela maneira, acho muito importante esse processo tanto quando o curso em si. Mas não vou negar algumas vezes a gente apanha um pouco, mas é por uma boa causa.

**Comment by aleemerich** [comment]
Oi pessoal. Eu caí aqui ao pesquisar valores para RocketSeat, mas acho que tem algumas coisas citadas aqui que posso ajudar como alguém já a um bom tempo no mercado de sistemas. 

Primeiro, quando falamos de MVC, há "versões" a se pensar. Por exemplo, o Java a 20 anos foi o pioneiro a aplicar a primeira versão do padrão de desenvolvimento MVC de forma que vc era (e é) obrigado a usar para poder programar. Isso, como tudo em TI, evoluiu e hoje estamos no MVC 3, 4 ou até dizem que há a versão 5 dependendo da corrente seguida.

Outra questão importante é que a boa prática citada aqui é um MVC para PHP (vide o site de referência) e segundo essa mesma página, no início:

> In this section, we describe some general guidelines on how to better follow MVC when developing a Yii application.

Nesse caso, o framework cita as boas praticas para o uso do MVC nele. Porém não mecessariamente isso quer dizer que é assim que todo MVC deve ser aplicado.

Quando falamos de React, Node.JS ou front-end é back-end, temos que entender que além tecnicamente não temos View e Controler para humanos no back-end, dado que tudo é feito via API, o front-end passa a também fazer um MVC usando a API como Model ou um misto de API e regras locais usando cache interno e até pequenos db locais.

Se usar o cenário do framework Yii aqui de forma direta, começa a perder sentido ou ficar muito complexo chegar em algo que se encaixe no React, Node e afins, mas não necessariamente um ou outro estão errado, podem somente estarem em versões diferentes de abstração.

Outra questão bem interessante é que, de uma maneira macro, compara-se a Rocketseat com a DevReactJS mas é possível ver que a grade oferecida (quantidade de coisas que vai aprender), a didática (a forma de como vai se passar) e outro pontos (canais de atendimento e etc.) são diferentes, então corremos o risco de estar comparando "mamão com maçã" (embora o assunto seja React, cada um fornece um jeito e escopo diferente), ou seja, perde um pouco o sentido de comparação por acabar não sendo do mesmo tipo. 

De resto, agradeço as postagem porque me informou bastante coisa interessante. 

Abrs.

> Estou fazendo o bootcamp da Rocketseat atualmente, finalizando o terceiro desafio no momento, cara, vou dar a minha opinião de pessoa extremamente chata.
> 
> Pra ter uma visão do ecossistema do React e pra entrar no mercado, o curso deles é ótimo sim e vale o investimento, fora a comunidade que é excelente!
> 
> Mas vamos a partes ruins:
> 
> ### Qualidade de código
> Não sei se é cruel esperar isso de um bootcamp, entretanto o Diego passa conceitos absurdamente errados, não apenas no curso Starter, mas como no Bootcamp inteiro na parte de nodejs.
> 
> Eu geralmente não ligo tanto pra isso pois é normal cursos passarem por cima de conceitos de boas práticas para simplificar as coisas, entretanto, ele **advoca** em usar práticas erradas, como colocar toda a lógica da aplicação no Controller:
> 
> ![WhatsApp Image 2019-10-21 at 23 08 20](https://user-images.githubusercontent.com/10618352/68824108-7eb53800-0674-11ea-84a5-59b6eb1d94aa.jpeg)
> 
> E que o Controller também é responsável pelo CRUD:
> 
> ![WhatsApp Image 2019-10-21 at 23 12 58](https://user-images.githubusercontent.com/10618352/68824835-deacde00-0676-11ea-93f7-1e7505546de4.jpeg)
> 
> **A boa prática**: O _Controller_ deve ser a parte mais simples de toda a aplicação, eles só são responsáveis em passar informação de uma view pra uma model, e vice-versa, elas devem apenas formatar dados, não devem possuir nenhuma lógica:
> 
> > In a well-designed MVC application, controllers are often very thin, containing probably only a few dozen lines of code; while models are very fat, containing most of the code responsible for representing and manipulating the data. - [Best MVC Practices](https://www.yiiframework.com/doc/guide/1.1/en/basics.best-practices#controller)
> > But the controller is in no way responsible for any form of business logic. If it was, it would mean, that you have a leaking abstraction, because the structures of presentation layer would be doing work, which should be in the model layer. - [Having MVC controllers light and models heavy](https://stackoverflow.com/questions/12012817/having-mvc-controllers-light-and-models-heavy)
> 
> Sobre linters, ele desativa várias rules do eslint durante o curso também(que são recomendadas), como o [no-param-reassign](https://eslint.org/docs/rules/no-param-reassign) e [class-methods-use-this](https://eslint.org/docs/rules/class-methods-use-this), a minha maior preocupação é ele ensinar a maneira mais conveniente que é desativar as regras e não ensinar a maneira correta.
> 
> ### Didática (opinião pessoal  )
> Eu diria que o pessoal confunde boa dicção com didática, o Diego possui uma excelente dicção, mas os cursos deles não são tão acessíveis assim para iniciantes pois ele fala **muitos** termos técnicos, de maneira exagerada, todo o material da rocketseat é lotado de buzzwords.
> 
> Eu particularmente tenho um pouco de dificuldade de acompanhar os videos por causa disso, se você buscar material de fora pra entender o que ele fala você vai perceber que as explicações dele são bem razas, mas enfim, é um bootcamp rápido, então não sei até que ponto esse argumento é válido.
> 
> Vale a pena, vai sem medo, mas não se contente apenas com o material do curso, principalmente quando o assunto é qualidade de código.

**Comment by wilsonneto-dev** [comment]
Concordo com @aleemerich e concordo em partes com outros comentários acima, claramente o Diego passa por cima de alguns padrões, mas o curso de fato ensinado Node, react e react-native que é a proposta. 

Se pensarmos a fundo sobre padrões, talvez o MVC por si só já não seria o padrão mais interessante também, se pegarmos o DDD e respeitá-lo, MVC entra apenas nas camadas de UI e de Aplicação, estão longe de serem as mais importantes, o Domain que vai ter a lógica, os Services, as camadas de Infra, Cross Cutting, a camada de Repositories... O conceito de Model cai e vem os conceitos de Services e Entities, o desacoplamento levado a sério. Enfim, um curso focado em DDD por exemplo teria de pegar uma galera experiente e levaria bem mais tempo que o bootcamp. 

O que quero dizer é que ele ensina o que se propõe e ensina bem, de fato você já tem que ter a lógica e uma boa noção de js, no mais o curso cumpre com a promessa. Abordar padrões a fundo, iria comprometer bastante para o pessoal iniciante e com pouca experiência...

Minha opinião...

**Comment by andrebonfim** [comment]
Eu estou fazendo a Launchbase da Rocketseat! Melhor escolha que já fiz!

Obs.: comentei aqui em outra discussão!! [https://github.com/frontendbr/forum/issues/1682#issuecomment-582701499](url)

**Comment by eliseumds** [comment]
Eu não fiz o curso mas pelo que li acima, parece-me que o curso tenta explicar conceitos básicos para que os alunos possam botar a mão na massa com NodeJS. Ensinar arquitetura e DDD/MVC/CQRS/etc é algo extremamente difícil e leva-se tempo, você vai ter que pagar 50x mais por cursos de imersão com especialistas nestas áreas, ou seja, tente absorver os conhecimentos que ele passa sobre React e React Native, que são bons, e o resto você vai aprendendo com o tempo.

**Comment by rCattoni** [comment]
> Eu estou fazendo a Launchbase da Rocketseat! Melhor escolha que já fiz!
> 
> Obs.: comentei aqui em outra discussão!! [1682](https://github.com/frontendbr/forum/issues/1682#issuecomment-582701499)

@andrebonfim Qual o valor investido no  LaunchBase?

**Comment by felipe-b-oliveira** [comment]
> Eu não fiz o curso mas pelo que li acima, parece-me que o curso tenta explicar conceitos básicos de backend para que os alunos possam botar a mão na massa com NodeJS/React. Ensinar arquitetura e DDD/MVC/CQRS/etc é algo extremamente difícil e leva-se tempo, você vai ter que pagar 50x mais por cursos de imersão com especialistas nestas áreas, ou seja, tente absorver os conhecimentos que ele passa sobre React e React Native, que são bons, e o resto você vai aprendendo com o tempo.
> 
> Só pra se ter uma ideia, eu fiz workshops de DDD com caras como Vaughn Vernon que custam mais de 10 mil reais por dois dias e, na boa, eu ainda tenho muito chão pra andar.
> 
> Eu começo a ver problemas quando leio que "A boa prática" é chamar uma model diretamente do controller. Como tudo na nossa área, as coisas são relativas. Pra mim, MVC em geral é uma má prática, mas eu fui entender isso depois de muito tempo. Eu diria que um controller nunca deve chamar um model pois elas devem ser stateless, um ValueObject somente, assim as coisas podem ficar melhor separadas. Um controller deve chamar um repository que aí sim retorna uma model (ou lista delas). Business logic fica nas aggregate roots e command validators. O buraco é mais em baixo, e no caso de cursos como os da RocketSeat, o nome já diz tudo: **bootcamp**, é um pontapé inicial.

Tenso, indo pesquisar os termos que você citou, já senti uma diferença com o MVC + Serviços, na faculdade só vimos o MVC basicão, ainda estou tentando me acostumar.

**Comment by felipe-b-oliveira** [comment]
> > Eu estou fazendo a Launchbase da Rocketseat! Melhor escolha que já fiz!
> > Obs.: comentei aqui em outra discussão!! [1682](https://github.com/frontendbr/forum/issues/1682#issuecomment-582701499)
> 
> @andrebonfim Qual o valor investido no LaunchBase?

Também tenho a mesma dúvida.
Mas acho que o LauchBase não é para mim, no momento eu preciso mesmo da base em Javascript puro a partir da mudança que teve o ES6, é muito diferente, o Javascript antigo já me é mais familiar por já ter estudado Java na faculdade (as funções são parecidas, a construção delas), agora as arrows functions me dão estranheza embora eu saiba da praticidade das mesmas.

**Comment by CarolineSantosAlves** [comment]
Tenho feito o master class do Rodrigo Branas e estou gostando bastante , pois o que me falta é essa base do JavaScript. Futuramente estou pensando no bootcamp do RocketSeat me parece interessante.

**Comment by KNan-L** [comment]
> > > Eu estou fazendo a Launchbase da Rocketseat! Melhor escolha que já fiz!
> > > Obs.: comentei aqui em outra discussão!! [1682](https://github.com/frontendbr/forum/issues/1682#issuecomment-582701499)
> > 
> > 
> > @andrebonfim Qual o valor investido no LaunchBase?
> 
> Também tenho a mesma dúvida.
> Mas acho que o LauchBase não é para mim, no momento eu preciso mesmo da base em Javascript puro a partir da mudança que teve o ES6, é muito diferente, o Javascript antigo já me é mais familiar por já ter estudado Java na faculdade (as funções são parecidas, a construção delas), agora as arrows functions me dão estranheza embora eu saiba da praticidade das mesmas.

Oi, o bootcamp Lanchbase é exatamente isso, você vai aprender do zero o javascript, html e css, e ao longo do curso vai sendo mostrado como era feito antes no javascript e como é feito no ES6, é um ótimo curso pra iniciante mesmo, esse é o propósito dar a base pra quem não tem e quiser fazer o bootcamp gostack, entreguei ontem o desafio final do Launchbase e com certeza comparando o que eu sabia antes com o que eu sei agora, foi um dinheiro muito bem investido. Você sai do curso com o conhecimento de backend e frontend.

**Comment by wilsonneto-dev** [comment]
Eu seguiria na linha que falei em outro tópico agora a pouco, se eu estivesse começando eu focaria em JS puro, mas sem cursos pela w3school ou por documentações. Logo que ok entendendo e fazendo alguns prototipos com js, html e css, partiria para o curso do Dev Pleno focado em React JS, o [http://bit.ly/reactjs-dev-pleno](http://bit.ly/reactjs-dev-pleno). Após o curso focaria em lapidar o front e entrar no mercado, estando no mercado focaria em absorver o máximo das situações do dia a dia e depois partiria para o Go Stack para me aprofundar em RN e Node. Eu fiz todos os cursos citados, mas hoje atuo mesmo com ReactJS e .Net Core, uso RN e Node em meus projetos pessoais, mas preferi seguir a linha do .Net com React JS por questões pessoais.

Espero que ajude alguém...
Forte abraço!

---
Wilson Neto
Linkedin: [https://www.linkedin.com/in/wilsonnetobr/](https://www.linkedin.com/in/wilsonnetobr/)

**Comment by aminsales** [comment]
> > > Eu estou fazendo a Launchbase da Rocketseat! Melhor escolha que já fiz!
> > > Obs.: comentei aqui em outra discussão!! [1682](https://github.com/frontendbr/forum/issues/1682#issuecomment-582701499)
> > 
> > 
> > @andrebonfim Qual o valor investido no LaunchBase?
> 
> Também tenho a mesma dúvida.
> Mas acho que o LauchBase não é para mim, no momento eu preciso mesmo da base em Javascript puro a partir da mudança que teve o ES6, é muito diferente, o Javascript antigo já me é mais familiar por já ter estudado Java na faculdade (as funções são parecidas, a construção delas), agora as arrows functions me dão estranheza embora eu saiba da praticidade das mesmas.

@felipe-b-oliveira para entender bem o ES6 recomendo a formação de javascript do site freecodecamp.org(é gratis). Eu programava em java e também achei estranho alguns conceitos do ES6. Estou fazendo o bootcamp GoStack da Rocket Seat para ter uma visão geral da stack e a formação de JS do freecodecamp para entender JS mais afundo.

**Comment by nastari** [comment]
O lance é a facada dos 3K que o curso tá agora , manda mensagem no linkedin se alguém animar dividir a conta porque o acesso dura 2 anos né, pelo menos volta alguma grana

**Comment by nastari** [comment]
O lance é a facada dos 3K que o curso tá agora , manda mensagem private se alguém animar dividir a conta porque o acesso dura 2 anos né, pelo menos volta alguma grana

**Comment by wilsonneto-dev** [comment]
@nastari, acho que vai do ponto de vista, nos lançamentos é cerca de R$ 1.690,00 se não me engano, fazendo uma analogia, é mais ou menos o valor de um celular normal que geral usa... Só que o curso te traz retorno e um celular não... foi apenas uma analogia para, educação e conhecimento é um dos investimentos e bens mais valiosos que existe. Ligo bem mais para qualidade, e é excelente, e para ser sincero vale muito a pena e está dando e dará bastante retorno por um bom tempo. Digo isso apenas para pensar em cursos como investimento. Existem "n" outras maneiras além de cursos, mas para mim cursos de qualidade aceleram bem a curva.

Quanto a dividir o login, me coloco no lugar de quem fez o curso, e seria injusto de alguma forma revender/piratear, seria como alguém comprar a licença de meu software e sair revendendo sem permissão aquela 1 licença... Eu tenho um trampo bom para fazer as coisas funcionarem, nada mais justo que receber as licenças de quem usa aquilo que fiz, pelo preço que achei ser o que paga meu serviço...

E bom, se posso dar duas dicas é isso, cursos são investimentos, mas tbm há outros caminhos.

Um curso bem mais em conta e tão bom quanto é o do devpleno que citei: [http://bit.ly/reactjs-dev-pleno](http://bit.ly/reactjs-dev-pleno). O da rocketseat apesar de um valor mais elevado, gosto demais de ambos e indico sempre.

Abraços!

**Comment by malltapps** [comment]
A segunda versão do bootcamp já é obsoleta agora o bootcamp esta com uma duração umas 3x mais e o conceito não é mais MVC o foco é design patterns usando princípios de SOLID e DDD Eu diria que pra quem tá começando ficou praticamente impossível esse bootcamp agora fica bem obrigatório passar pelo lauchbase antes. O que eu percebi é que o bootcamp agora se preocupa em passar muitos conceitos avançados de software em um curto espaço de tempo, tem suas desvantagens mas a longo prazo Acredito que seja possível assimilar.

**Comment by wilsonneto-dev** [comment]
Sim, estou refazendo o bootcamp, está muito avançado msm, estou curtindo demais, mas para que ta começando hj sempre indico mais o curso do devpleno para depois ir para um mais avançado como da rocketseat. O do devpleno que foi o meu primeiro contato com react e foi muito bom foi: [http://bit.ly/reactjs-dev-pleno](http://bit.ly/reactjs-dev-pleno).

**Comment by lesimoes** [comment]
O "problema" é que a proposta do curso é ser básico e introdutório, porém é vendido como avançado, e como já comentaram aqui está longe disso. Trabalhei em um projeto grande que infelizmente usaram a arquitetura do curso e posso dizer que é uma péssima arquitetura, manutenção custosa, queries iguais espalhadas pelo código, controller grandes, não existe um padrão para dependências (qual camada se comunica com qual). 

Minha dica, quer aprender com o curso? Tudo bem! Mas tenha em mente que aquilo ali tá longe de ser algo bom para projetos um pouco maiores. Quem quiser ir mais fundo recomendo o livro Arquitetura Limpa (Uncle Bob) ou cursos do Erick Wendel e Túlio Faria (DevPleno).

**Comment by wilsonneto-dev** [comment]
Concordo em partes com o @lesimoes, realmente não fui tão a fundo, mas penso que o problema do projeto citado não foi por causa da arquitetura do curso... DDD e TDDD a risca pra um projeto pequeno é uma péssima, "Smart UI" (termo do próprio uncle bob) ou apenas um MVC padrão para projetos grande é uma péssima idéia... A arquitetura boa existe somente no contexto do projeto, TDD e DDD é lindo e dá vontade de colocara té naquele CRUD de 5 horas q vc precisa fazer, mas se for fazer estas 5h vão virar 30h e tudo vai ser tão simples q implementar a arquitetura e os testes darão mais trabalho do que o projeto e a manutenção q talvez nem exista nunca...

O curso ensina no mínimo 3 arquitetura diferentes, é citado SOLID, TDD e DDD, aborda patterns como Command Handler que é muito massa quando trabalhamos com micro serviços e filas, também há um foco legal na camada de serviços, assim como tbm é mostrado DDD, arquitetura em camadas, Smart UI e atualmente nem tem mais MVC cru no curso. Mas arquiteturas não tem bala de prata, cabe aos devs decidir a que vão usar e usufruir das facilidades ou não advindas de suas decisões certas ou erradas... 

Não existe um ou dois padrões de arquitetura, de infra, de design patterns e etc, não exista a melhor nem a pior, o importante é conhecer muitas e saber o contexto para cada uma, assim como para os design patterns e etc.

**Comment by lesimoes** [comment]
> mas penso que o problema do projeto citado não foi por causa da arquitetura do curso...

No caso que eu citei foi sim...

**Comment by alaelcio** [comment]
cara Estou fazendo é muito bom, eu já fiz curso na udemy mas não gostei.

**Comment by wilsonneto-dev** [comment]
Sim, o GoStack eu fiz em 2018 e agora refazendo a nova versão com foco em TS, está bem mais profundo em arquitetura e testes, muito bom mesmo...

Outro também que já fiz e tem um custo mais tranquilo para quem está começando e é muito massa são os cursps FullStack e o ReactJS do DevPleno: [http://bit.ly/reactjs-dev-pleno](http://bit.ly/reactjs-dev-pleno)

O Fullstack do DevPleno e o GoStack abrem turmas a cada 2~3 meses, já o reactjs do dev pelno é muito bom e está sempre aberto, recomendo os três, ams um por vez para não desfocar rs 

---
Wilson Neto
Linkedin: [https://www.linkedin.com/in/wilsonnetobr/](https://www.linkedin.com/in/wilsonnetobr/)
