### ISSUE TITLE
Quais os melhores cursos online para desenvolvedores?

### ISSUE THREAD

**Issue by djteix** [frontendbr/forum#1515]
Olá a todos, estou começando essa caminhada para me tornar um desenvolvedor, estou me guiando pela curiosidade, no momentos estou estudando, HTML5, CSS3, JS e NodeJS. Não está fácil! Vi algumas plataformas online de cursos como udemy, alura, etc. Poderiam me indicar as melhores em metodologia e que os certificados tenham algum respeito no mercado. Obrigado.

**Comment by yuritoledo** [comment]
Cara, dá uma olhada no site do freecodecamp.org

Lá tem tudo o que você precisa pra começar, como Css html, js, bootstrap, node, react, algoritmos e mais um monte de coisa

Fora que tem uns desafios pra você praticar 

E tem uns certificados também!

**Comment by renedocket** [comment]
Olá djteix, tudo bem? 

- **Rocketseat** - https://rocketseat.com.br/starter)
- **DevPleno** - https://www.devpleno.com/
- **Collabcode** - https://collabcode.training/ o curso deles é voltado para front-end, que além de abordar o básico HTML5 / CSS3 / JS tem mais alguns adicionais, acompanhe pela comunidade que fica mais fácil de saber quando abre as inscrições. 
- **Alura** é bem interessante eu aprendi muito com os cursos básicos deles, e consegui um trampo por meio desses conhecimentos, acredito que é uma boa se manter nele.

Espero ter ajudado! :)

**Comment by ThiagoHs1** [comment]
A **alura** parece ser muito bom, planejo comprar quando tiver um desconto

Recentemente comprei o **pacote full stack da danki code** recomendo bastante, to aprendendo um monte de coisa, ele dá um monte de projetos para tu aprender junto enquanto faz - https://cursos.dankicode.com/

Outra plataforma de cursos que vejo as pessoas recomendarem e sendo bem falado é a origamid, acho que vale a pena dar uma olhada ---> https://origamid.com/planos/

**Comment by mdandrade** [comment]
Só uma dica no JavaScript. Pode parecer muito difícil no começo pra quem não é da área de programação, mas tenha há paciência que vai ficar fácil depois.

Minha caminhada foi assim:
- w3chools
- freeCodeCamp
- Origamid

Paciência e constância que vai.

**Comment by viniciusreiss** [comment]
Cara eu assinei alura por 1 ano, olha os cursos tem uma qualidade boa, porém alguns estavam muito desatualizados e com uma didática ruim como o de React por exemplo. A udemy é uma execelente opçāo pois os cursos sāo baratos, recomendo olhar os da Cod3R.

**Comment by TL-Developer** [comment]
Udemy também é uma boa hein ;), mas comecei pela Alura.

**Comment by alecrs** [comment]
Sei que o assunto já tem um mês de forum, mas acho importante a diversidade de opiniões, então deixo como dica a plataforma de estudo que uso até hoje: Devmedia. Conteúdo bom, completo e orientado para que possa ser estudo passo a passo, do básico ao avançado.
www.devmedia.com.br

**Comment by jotepauder** [comment]
Pessoal, tudo bom com vocês? 

Tiveram pessoas aqui que assinaram a Alura, e eu assinei também só que o seguinte, eu 
não consegui aprender com a metodologia deles para o curso básico de HTML E CSS, ele é dividido 
em duas partes, nessa primeira parte começa com um pouco de Html e depois é só CSS, mesmo 
estudando todo dia, sinto que não conseguir aprender um pouco pelo menos, terminei a primeira parte do curso hoje, eu não sei se o problema sou eu, kkkkk!

**Comment by willycamargo** [comment]
Fala @jotepauder , tudo certo?

Minha namorada também assinou Alura e sente dificuldades com a metodologia no mesmo curso. Para complementar eu tenho ensinado algumas coisas para ela e tento esclarecer os assuntos que ela fica confusa.

Em contrapartida, caso você não tenha problemas com inglês, parece que a metodologia do freecodecamp é muito boa.

Não muito atual, mas os cursos do "curso em vídeo" do Gustavo Guanabara também tem uma didática bem objetiva e foi muito bom para alguns amigos meus.

Além desses com certeza existem outros que não conheço. Mas ficam as dicas.

Abrs e continue estudando.

**Comment by jotepauder** [comment]
Tudo sim @willycamargo , e com você?

Ah, que bom em pensar que não sou eu que sinto isso, kkkk! Eu tenho até começado o 
freecodecamp, mas assinei a Alura mais por isso, o meu inglês ainda não é muito bom. E vejo que tem bastante material em inglês muito bom. Eu fiquei em migrar pelo menos essa parte para o curso em Video, ali eu consigo entender e muito bem diversos assuntos que o Gustavo Guanabra fala, é muito foda, eu acho que pra lá e depois eu volto para Alura, mesmo assim muito obrigado pela ajuda o//

Abraço, continuarei sim o/

**Comment by ninetails** [comment]
Respondendo a pergunta original, o melhor (e já que não perguntou de preço) que ouvi falar, das gringa (inglês somente) é o **Frontend Masters**. Tem só cara pica ministrando curso.

**Comment by 45lailson** [comment]
Udemy tem cursos excelentes tbm
