### ISSUE TITLE
Como conciliar responsabilidades + nova área profissional e suas dificuldades

### ISSUE THREAD

**Issue by lnascim** [frontendbr/forum#1517]
Pessoal, é o seguinte:

 Faço ADS de manhã numa faculdade aqui em SP e trabalho no período tarde/noite em uma área que nada tem a ver com tecnologia. Meu salário é R$ 2k (+ benefícios), e com ele pago meu aluguel e outras contas (moro por minha conta mesmo). 
  Daqui uns semestres (uns 3), vou precisar fazer um estágio. Tô vendo muito estágio por aí oferecendo R$800, R$ 1,2k, R$2k (mais raros). Tô esquentando a cabeça porque sinto uma baita insegurança em trocar meu CLT que não paga muito (mas é confortável e paga minha comida e teto rs) por um estágio que vai me pagar o valor do aluguel e olhe lá. Estou me programando para criar uma reserva de emergência pra essa época, mas tenho receio de demorar pra arrumar estágio, não me efetivarem, ou só achar estágio de suporte, sei lá. Estágio de suporte tem até que tem, mas tenho medo de pegar um desses por desespero mesmo e me lascar pra ir pra área de DEV. Além disso tem aquelas vagas de "estágio" que só faltam pedir que você seja um Cavaleiro Jedi, aí me confunde mais ainda. 
  ADS é minha primeira faculdade, estava há um bom tempo sem estudar e sinto que tenho uma baita defasagem, aquele ferrugem mesmo, até porque temos a combinação (aluno defasado + faculdade puxada).

(Dá pra ver que tenho uma baita ansiedade e sofro por antecipação sim, mas por sobrevivência mesmo - _tentativa de me justificar pra vocês ficarem com pena haha_)

***

 Me interesso por Front-End, estou pensando em fazer cursos na área (talvez nas férias, porque queria fazer presencial). Mas estou com uma baita dificuldade na faculdade por coisa bem idiota mesmo, como lógica de programação. Eu sei que é a base de tudo e eu preciso me aplicar mais, mas até pensei em fazer algum curso por fora (e dar um pause na facul, dependendo MUITO da situação - apesar que não é algo que eu realmente queira fazer) pra ver se consigo absorver melhor. Tentei fazer aulas online, mas ainda não tenho muita disciplina, confesso. Não sei se o problema é comigo (estou em busca da melhor forma pra desempacar) ou com a metodologia, mas eu gosto da área e não vou largar o osso até dar certo.

**Enfim, desculpe pelo textão, tô aceitando dicas e conselhos... Valeu!**

**Comment by yuritoledo** [comment]
A situação é bem delicada :(

Acredito que para entrar no mercado mesmo, o que pesa é você saber codar, saber lidar com problemas, "se virar". Curso superior não pesa muito ... eu mesmo, não sou formado na área de software (fiz redes/segurança) e nas 2 empresas que trabalhei com desenvolvimento, nenhuma questionou, apenas perguntaram se eu sabia fazer as paradas. 
Aprendi o que sei fazendo curso online e por conta mesmo. 

Para você poder pegar o certificado, vai ter que fazer esse estágio ou comprovar alguma equivalência (pelo que mencionou do curso, acho que você cursa fatec! ) ... Não sei a região que mora, mas estágio costuma pagar bem pouco mesmo e ainda tem chance de não efetivar, o que no seu caso, nem é opção.

O que eu posso sugerir (na minha humilde opinião) : Dar uma pausa na faculdade, fazer cursos online (a não ser que ache algum curso presencial MUITO bom), fazer alguns projetinhos  no tempo vago e subi-los no github para dar um "portfólio", depois tentar entrar na área. Quando conseguir entrar, você pode voltar no curso (espero que tenha no período noturno) e pedir a equivalência, pois você já está na área e não precisa fazer o estágio mais.

**Comment by theandersonn** [comment]
Passei por algo bem parecido, trabalhei em Restaurantes por 15 anos e decidi mudar de área. Na época tinha medos e ansiedades bem similares.

A primeira coisa que fiz foi zerar as contas, cartões etc;
Depois pedi demissão do trabalho, pra minha felicidade consegui estágio, depois de 06 meses fui efetivado e as coisas foram fluindo... levei um tempo para o salário passar o valor que eu ganhava no restaurante.
Tive que ser paciente, na parte financeira e nos estudos tbm.
Fui aprendendo muito na agência, na faculdade e em cursos online.
Teve um momento que tive que trancar a faculdade por 01 ano e depois voltar para concluir.

Hoje já conclui a faculdade. Continuo me esforçando em aprender no dia a dia, em cursos online.
E está fuindo de boa.

Se planeje. 
Pelo que vc falou precisa se disciplinar nos estudos. Faça isso. 
A empresa que você for trabalhar vai te cobrar isso. Temos que aprender coisas novas o tempo todo, cumprir prazos e entregar demandas.
