### ISSUE TITLE
Iniciante no Front-End

### ISSUE THREAD

**Issue by marcelafreire** [frontendbr/forum#1518]
Oi pessoal!

Sou designer, e sempre amei código, porém acabei seguindo mais pelo caminho do design. Agora, gostaria de investir no que realmente gosto, que é o front-end. Porém, só conheço o básico do HMLT e CSS e sei que tenho muito o que aprender. Minha dúvida é: Será que consigo ingressar no mercado front-end? Tenho medo de sair do meu emprego atual para me dedicar ao fornt-end e não conseguir nada na área. Também gostaria de saber em quanto tempo vocês acham que eu consigo aprender o suficiente para ingressar na área?

**Comment by will3g** [comment]
Se você gosta disso, então estude. Está tendo bastante vagas, tanto de estágio quanto CLT e etc... 
Recomendo estudar o básico de Java Script pelo site da Rocketseat (https://rocketseat.com.br/starter). A Alura também têm a formação front-end que pode te ajudar bastante (com bônus como CSS grid e etc...). O tempo depende de quanto você se dedicar aos estudos... Acho que no máximo três meses você já tenha aprendido bastante.

**Comment by Inovassist-dev** [comment]
Pelo que vejo a área fica meio que entre designer-front e programador-front. Você pode aprender js puro, algumas coisas que auxiliam como sass,  e tentar ingressar na área como front-end mais focado em design/ux. Assim seu ingresso no mercado vai ser mais rápido.

**Comment by gersoncjlima** [comment]
Vc já tem o melhor dos dois mundos rsrs, para um próximo degrau é apenas um passo, como os brows comentaram acima, dedicar-se bastante e já, já vc estará num outro patamar. Success!!

**Comment by glauberm** [comment]
Te recomendaria dar uma olhada em sites como o [Codrops](https://tympanus.net/codrops/) e o [Codepen](https://codepen.io/popular/pens/) que têm muito conteúdo que orbitam entre o design e o código.

**Comment by theandersonn** [comment]
@marcelalala Sim! Possibilidades são reais totalmente alcançáveis, depende apenas de você.

Hoje os processos de Front-End seguem rotinas com tarefas automatizadas, build que são excelentes, mas trazem complexidade que podem confundir quem está iniciando.

Foque inicialmente na raiz, HTML, CSS e JavaScript.

Fontes de estudo que recomendo:
https://www.udemy.com/
https://www.origamid.com/
https://www.schoolofnet.com/
https://www.alura.com.br/ 

Quanto ao tempo, depende de quanto você estudar. Creio que um período para maturar as informações é entre 06 meses a 2 anos. Você estará realizando tarefas com confiança.

Profissionais que conseguem reunir skills de designer e front são altamente requisitados no mercado de trabalho.
