### ISSUE TITLE
Popular array no estado da aplicação com useState hook.

### ISSUE THREAD

**Issue by AnakinRibeiro** [frontendbr/forum#1519]
Fala galera, estou com uma duvida/problema em código.
Consiste em uma aplicação para fazer upload de imagens.

Estou tentando definir o estado da aplicação como um array vazio e ir adicionando as imagens a ele, para no futuro fazer o upload para o servidor.

Segue o código: 

```
const [uploadedFiles, setUploadedFiles] = useState([]);

  const handleUpload = files => {
    const uploadingFiles = files.map(file => ({
      file,
      id: uniqueId(),
      name: file.name,
      readableSize: filesize(file.size),
      preview: URL.createObjectURL(file),
      progress: 0,
      uploaded: false,
      error: false,
      url: null
    }));
    setUploadedFiles([...uploadedFiles, uploadingFiles]);
  };
```

Gostaria de saber qual a melhor forma para popular esse array no estado.
Pois por esse método que tentei utilizar a aplicação retorna o estado (que é um array), com  outro array dentro contendo as imagens selecionadas. Então a cada imagem que eu tento adicionar ele cria outro array dentro do estado contendo a imagem.

**Comment by eliseumds** [comment]
Fora de contexto, mas o nome da variável *uploadedFiles* pode causar confusão, afinal, ela contém também objetos que ainda não foram enviados. Algo como *filesToBeUploaded*, ou *uploadQueue* seria mais fácil de entender.
