### ISSUE TITLE
Terá FrontIn Ceará? 

### ISSUE THREAD

**Issue by amandatavares** [frontendbr/forum#152]
Hey guys! Alguém sabe me informar se terá o evento FrontIn no Ceará, Fortaleza? Ou qualquer outro evento de Front?

**Comment by LFeh** [comment]
Olá @amandatavares, consegue reabrir sua issue no [repositório de Eventos](https://github.com/frontendbr/eventos)? 

Obrigado :smile:

**Comment by cjpatoilo** [comment]
@amandatavares @LFeh Temos um grupo no FB para trocar ideias, compartilhar conhecimento, tirar dúvidas, divulgar eventos, meetups, cursos.. https://www.facebook.com/groups/fortalezadevelopers/ 

Sobre o FrontInFortaleza, haverá sim, será em novembro. ;)
