### ISSUE TITLE
qual a melhor forma de instalar o mysql sem bugs?

### ISSUE THREAD

**Issue by igorpinhh** [frontendbr/forum#1520]
depois de formatar o pc algumas vezes por causa de bugs sem solução e mal funcionamento do mysql eu queria saber a opinião de vocês se existe alguma forma segura/simples de se usar mysql a fim de manter o bom funcionamento dele...

**Comment by MarcosEllys** [comment]
Olá @igorpinhh , cara existe algumas formas de instalar o mysql, se for pra desenvolvimento e você for programar com PHP e Mysql vai de [XAMP](https://www.apachefriends.org/pt_br/download.html) pois eu ainda considero a opção mais fácil.

**Comment by eliseumds** [comment]
Usa Docker, mas não esquece de definir um volume pra não perder todos os dados caso o container vá pro saco.
