### ISSUE TITLE
Qual é a melhor maneira de medir a performance em Javascript?

### ISSUE THREAD

**Issue by renedocket** [frontendbr/forum#1521]
Olá pessoal, tudo beleza?

Eu gostaria de saber como que é feito a análise de performance em questão de processamento, carregamento do JS. Tem ferramentas que é possível visualizar se um código não está performático ou algo do tipo?

**Comment by eliseumds** [comment]
Primeira e mais essencial pergunta: você tá enfrentando problemas de performance?

Se estiver falando de web development (ou mobile), mais importante é medir *perceived performance* do que focar em trechos específicos de código (a não ser que você esteja lidando com coisa muito grande). Ferramentas como [web.dev](https://web.dev/measure) podem ajudar.
