### ISSUE TITLE
Conseguir vaga em outro estado como Junior

### ISSUE THREAD

**Issue by lucasmoore2k** [frontendbr/forum#1535]
CONTEXTO:
Fiz 26 anos esse ano e durante alguns anos de minha vida fiz universidade federal em uma das engenharias clássicas com isso morava com parentes em outra cidade,contudo no inicio do ano acabei mudando de instituição e de curso(fui para eng computação) e acabei voltando pra casa dos pais.

O problema é que além de já ter enjoado de morar com os pais,eu saturei completamente da região onde vivo,não que seja ruim,mas a cultura,o clima,a violência,o mercado de trabalho super limitado da área me desanimam tanto,que de tanto pensar em sair daqui,já estou ficando depressivo.

O mais lógico seria terminar a universidade(faltariam uns 2 anos),mas sinto que se continuar aqui até me formar além de estar me limitando em termos de oportunidades de carreira e estudo,acho que a quanto mais tempo passar na casa dos pais,pior será  em termos de maturidade e se virar sozinho.

QUESTÃO:
**Com um conhecimento básico em JAVA e SQL sem experiência existiria possibilidade de achar emprego como ANALISTA DE SISTEMAS JR em outro estado que dê para se virar(pagar contas,aluguel,lazer eventual)?**

Estados em mente: SP,MG ou qualquer um da região SUL

**Comment by theandersonn** [comment]
Tem que considerar por partes:

1. Definir a sua formação e área de atuação.
Porque vc foi mudando de curso? Está certo que o curso atual é o que você se formará?

2. Pesquise a média de salário para desenvolvedor jr na área que você deseja trabalhar e calcule se sobre as despesas com moradia, alimentação e etc...

3. Certifique-se que você tem o conhecimento necessário para aplicar para a vaga
Como sabe? Essa questão é delicada, porque varia de empresa para empresa. Mas de uma forma geral pesquise por vagas e os requisitos, pergunte para outros desenvolvedores como é a stack, rotina na empresa x, y z...

Tenha em mente que o conhecimento aplicado no dia a dia numa empresa é diferente do acadêmico, na empresa é "conhecimento orientado a resolução de problemas de clientes".

Sugestão:

Termine a faculdade. (2 anos passa rápido)
Nesses dois anos falta, dê passos para a mudança, escolha uma cidade, visite, veja como é custo de vida... dia a dia mesmo, padaria, supermercado etc...
Vá a eventos, é uma excelente forma de construir networking que lhe ajudará nessa mudança.

Enfim.... se é possivel?
As chances são reais. Só depende de você.

**Comment by felipefialho** [comment]
@lucasmoore2k Uma vantagem da área que atuamos é a possibilidade de "provar" seus conhecimentos com testes feitos remotamente. Então, caso se candidate pra alguma vaga, a qualidade de seu teste / processo de entrevista, vai determinar a possibilidade de mudar de estado.

Tenha isso em mente na hora que se aplicar, você estar em outro estado geralmente não importa muito.

**Comment by TecladistaProd** [comment]
Eu também estou pensando em tentar uma vaga para mudar, mas no meu caso é para mudar de país kkkkk. Mas é um pouco mais difícil, sem contar que muitos lugares e empresas presam o “perfect English”, acho isto uma porcaria :s, mesmo por que participei de uma fase de teste (1 mês +/-), para uma startup americana, me virando com o inglês seja na vídeo com eles ou via texto, consegui passar, mas não tinha o visto e eles acabaram não me ajudando com o mesmo :’( kkkkk. Mas concordo com o amigo acima, termine a faculdade e neste período vá colocando novos projetos no GitHub e mostrando que está se desenvolvendo e aprimorando.

**Comment by lucasmoore2k** [comment]
Valeu a todos!
