### ISSUE TITLE
Fazer a UI "na unha", Material UI ou React Suit? Como decidem?

### ISSUE THREAD

**Issue by wilsonneto-dev** [frontendbr/forum#1536]
Fala galera!

Bom, estou iniciando um projeto e na dúvida se faço os componentes de UI na unha, se uso um framework tipo o Material UI ou se uso outro... 

Tenho domínio de html e css, grid style, flex e etc, faria tranquilo codificando, mas minha dúvida maior aqui é, qual a vantagem em usar um framework de UI ou de não usar?

Sei que o framework vai diminuir o prazo, mas vai aumentar o tamanho do js gerado e arquivos ao final do desenvolvimento... mas além disso, quais vantagens em cada caso vocês veem? Qual vocês usam? 

Muito obrigado, abraços!

**Comment by eliseumds** [comment]
Aqui na empresa escrevemos todos componentes primitivos do zero, e chegamos a uma API muito similar à do [Styled System](https://styled-system.com).

Para componentes mais complexos como date pickers e modals, eu usaria libs prontas, a não ser que o time seja grande e a galera seja muito experiente com web development. Criar estes componentes do zero vai consumir muito tempo e a gente sempre acaba sub-estimando detalhes de accessibilidade e principalmente inconsistências entre diferentes browsers (sim, isso ainda existe e muito). Outra opção para estes componentes é escolher bibliotecas que oferecem somente o comportamento e você monta a UI, como:

* [Downshift](https://github.com/downshift-js/downshift) para autocompletes, selects e multi-selects
* [React Table](https://github.com/tannerlinsley/react-table) que usa hooks

**Comment by kavalcante** [comment]
Se você tiver um time de designers que faça os componentes pra você, acho que beleza. Mas do contrário, acho totalmente desnecessário a principio.

Na minha opinião, se baseia em um set de componentes que seja do estilo que a empresa precisa/gostaria, e constrói os componentes com base neles.

Quando você tiver (se ainda não tiver) uma equipe grande, que precisa manter a ordem acima de tudo e a consistência entre os projetos. Aí vale a pena fazer um styleguide de vocês com regras que só sua empresa vai utilizar.

No meu caso, eu utilizo Vue e escolhemos o Element UI que é baseado em desktop (90% dos nossos usuários são do desktop) para criar a aplicação. Aproveitei muito do que essa lib me fornece e construi vários componentes em cima dele. 

As vantagens disso, é que muita coisa tá pronta e você "só" precisa juntar tudo. O lado ruim disso, é que você fica "refém" da equipe que está desenvolvendo esses componentes. Porém, trabalho em uma startup, então o objetivo é entregar coisas em produção e provar o modelo de negócio, não manter uma identidade e construir uma marca só nossa. Não nesse momento, pelo menos.

**Comment by wilsonneto-dev** [comment]
Show, muito obrigado @eliseumds, não conhecia estas bibliotecas, muito obrigado!
@kavalcante valeu pela opinião e ponto de vista, realmente para validar um mvp ou projetos menores não vou fazer, pegar a React Material UI e mandar bala com ela, vou estudando enquanto isso e criando alguns componentes para um projeto que está validado aqui na empresa e com certeza este já estamos pensando em uma vida longa do software e distanciar a próxima necessidade de refazer a UI, então vamos focar em fazer os nossos e desacoplarar de muitas libss externas.

Valeu!!

**Comment by lucas-moraes** [comment]
Tenho experiência com React Bootstrap, Material UI e agora estou estudando Styled Components e minha sugestão é que depende do seu tempo de projeto para entregar.

- Material UI FRAMEWORK - Já vem com tudo desenhado, só montar, muito bom para quem tem pouco tempo disponível no projeto e não tem design já pronto.
- React Bootstrap framework - Idem o de cima porém eu acho ele mais abaixo na qualidade.
-  Styled Components Make Yourself - Estou curtindo muito essa tecnologia, pois deixa você livre para modelar o projeto, e se tiver Layout já pronto melhor ainda, e eu sinto o sistema mais rápido também, deve ser pq não precisa carregar tudo que tem um "framework completão" e para você que escreveu que manda bem no CSS, cara se vc conseguir desenrolar desenhos no CSS é estouro...

**Comment by wilsonneto-dev** [comment]
Show @lucas-moraes, muito obrigado, vou fazer isso, pelo que vi minha preferência ficou por desenhar o projeto no Adobe XD ou o pessoal de UX me mandar e eu fazer em Styled Components... Já quando o prazo for apertado e for só pra entregar logo e tocar pro próximo projeto vou de React Material UI mesmo e boa.

Aliás, esta semana o pessoal aqui da equipe estava vendo esse carinha: https://rsuitejs.com/en/ também... Vou dar uma estudada e ver se qual será o nosso framework defaul para projetos rápidos, se este ou Material UI...

Muito obrigado, forte abraço!

**Comment by ninetails** [comment]
A parte do "como decidem?" creio que depende muito de certos fatores e muitas vezes não cabe a nós desenvolvedores.

Creio que um _workflow_ básico seria: ver com quem é responsável pelo _design_ se há alguma _guideline_. Dependendo do produto, segue uma _guideline_ de terceiro (ex.: Material Design) daí o segundo passo seria decidir com o time qual _lib de UI_ utilizar e que seja pertinente ao _design_ proposto. Aí a adoção vai de pensar em achar alguma _lib_ que mais ajude que atrapalhe: às vezes não cabe ter uma lib que tenha dependência em _sass_ por adicionar mais uma complexidade ao projeto caso os desenvolvedores preferirem _CSS-in-JS_ por exemplo.

Caso contrário, fazer na mão quando nada faz-se pertinente ao proposto para desenvolvimento (o _design_ proposto por exemplo tiver uma _identidade visual_ única e se tem tempo para desenvolver cada componente/módulo.

**Comment by vitinhohnz** [comment]
No projeto que estou trabalhando estamos usando as libs do Element.io (https://element.eleme.io/#/en-US) e do Uikit (https://getuikit.com/docs/introduction). Como muitos disseram ai em cima, o maior benefício foi a questão do tempo, usar algo que está pronto e não ter que ficar fazendo do 0. Mas agora, com o projeto e equipe crescendo já não está mais sendo viável, pois os components prontos nos limitam em algumas features que queremos desenvolver. Estamos com planos de formar um time para desenvolver um Material Design interno.

**Comment by freitasrachal734-afk** [comment]
Crie um script delta executor para mim por favor Brookhaven RP hub de administrador
