### ISSUE TITLE
Para um iniciante por onde começar Node ou PHP?

### ISSUE THREAD

**Issue by brunoak** [frontendbr/forum#1537]
pessoal estou estudando html e css, e já consigo fazer uma página, agr vou para o próximo passo, vejo que a maioria dos sites usam PHP, mas vejo muitas pessoas falarem do Node também.
Para um iniciante qual seria o caminho mais "facil" em relação a vagas e salario?

**Comment by rafaelangical** [comment]
Recomendo Node, pois já aprende Javasript, dai fica mais fácil aprender os frameworks front-end mais usados hj em dia com React, Vue, Angular, etc
.

**Comment by lucasferreiralimax** [comment]
Para iniciante todo conhecimento é válido.

Eu indico uma Stack JavaScript se for seguir a carreira de Front-end Developer

Se já domina o básico da linguagem JavaScript, comece a aprender os frameworks de trabalho que padroniza o desenvolvimento para suas aplicações.

//Front-end
[Vue.js](https://vuejs.org)
[Angular](https://angular.io)
[React.js](https://pt-br.reactjs.org)

Node.js é essencial para um bom Front-end vai te ajudar muito, oode começar conhecendo os pacotes npm e como usa-los

// WorkFlow
[Webpack](https://webpack.js.org)
[Gulp.js](https://gulpjs.com)

// Back-end
[Express.js](https://expressjs.com)

De inicio já é bastante conteúdo para estudar e aprender

Tem esse projeto bem legal mostrando uma trilha de conteúdo para Front-end, Back-end e DevOps.
[Developer Roadmap](https://github.com/kamranahmedse/developer-roadmap)

Bons estudos

**Comment by HmmerHead** [comment]
Dou razão ao o que o pessoal diz, mas veja PHP também. Como disseram a pouco, conhecimento nunca é demais, e inclusive pode ser útil em alguma vaga de emprego por ex. Vejo diversas vagas pedindo os dos inclusive. Aquela que mais te interessar, você vai se aprofundando, porém, não deixando e lado a outra.

**Comment by Vitor-Felipe** [comment]
Concordo com o @HmmerHead e o que o pessoal disse sobre conhecimento, porém no inicio eu acredito que o melhor que você pode fazer é focar em uma linguagem para entender os processos e não a linguagem em si.
Digo isso porque no meu inicio eu estudava varias coisas ao mesmo tempo e acabava tendo um baixo retorno em relação a conhecimento, pois acabava aprendendo os mesmo processos porém em diferentes sintaxes e também me confundia entre elas.

Em relação as linguagens/tecnologias citadas:

PHP:
- Tem muito mercado no Brasil (Não sei como está o mercado fora do Brasil)
- Tem MUITO conteudo na web
- Tem muitos sistemas na web utilizando PHP (tem reportagens que fala que 80% da web tem PHP)
- Curva de aprendizado mais facil que Node.js

Node.js:
- Tem muito mercado no Brasil e fora
- Utiliza JavaScript
- Tem bastante conteudo na web
- Tu consegue utilizar para uma aplicação simples como um to do list, até mesmo um streaming estilo netflix
- Curva de aprendizado maior em comparação com PHP

Minha opnião:
Eu escolheria Node, pois como o @lucasferreiralimax disse você vai estar trabalhando com JS em todas as partes do seu sistema, o que faz com que você aprenda mais rapido e reutilize tecnicas de js no front e back :)

**Comment by brunoak** [comment]
@rafaelangical @lucasferreiralimax  @HmmerHead @Vitor-Felipe Obrigado pelas respostas.
Eu faço curso técnico, e nesse semestre estou vendo PHP, mas aquele bem basicão, e por fora estou vendo JS, e o motivo dessa issue foi bem o que o @Vitor-Felipe  disse, estudar php e js a fundo ao mesmo tempo poderia atrapalhar, seguido o comentario de vcs acho que o momento é focar no JS mesmo

**Comment by maurosergio2112** [comment]
Estou pensando em focar em desenvolvimento Backend também, escolhi Javascript e PHP e estou pensando em estudar as linguagens para depois passar para os frameworks. Quais os tópicos vocês julgam essenciais para estudar ??(já tenho um conhecimento inicial sobre lógica de programação em Java).
