### ISSUE TITLE
Erro ao gerar relatório PHPjasper

### ISSUE THREAD

**Issue by marcosmarcie** [frontendbr/forum#1539]
Olá amigos, tenho 2 relatórios feitos com jasper studio, um deles não preciso de um sub relatorio, que funciona perfeitamente, já o segundo que necessito de um sub relatorio ele me retorna esse erro:

Erro fatal : PHPJasper \ Exception \ ErrorCommandExecutable não detectado: Seu relatório possui um erro e não pôde ser processado! \ Tente gerar o comando usando a função `output ();` e execute-o manualmente no console. em C: \ xampp \ htdocs \ API DOCTOR \ gerador de relatórios \ fornecedor \ copam \ phpjasper7 \ src \ PHPJasper.php: 215 Rastreio de pilha: # 0 C: \ xampp \ htdocs \ API DOCTOR \ gerador de relatórios \ index.php (78 ): PHPJasper \ PHPJasper-> execute () # 1 {main} lançado em C: \ xampp \ htdocs \ API DOCTOR \ gerador de relatórios / fornecedor \ copam \ phpjasper7 \ src \ PHPJasper.php na linha 215

script
```

require __DIR__ . '/vendor/autoload.php';

use PHPJasper\PHPJasper;
$input = __DIR__ . '/rel_exame.jasper'; 
$output = __DIR__ . '/';

$options = [
    'format' => ['pdf'],
    'locale' => 'pt_BR',
    'params' => ['id_consulta' => '127'],
    'db_connection' => [
        'driver' => 'mysql',
        'username' => 'u4642256565593_999',
        'password' => '12234566',
        'host' => 'sql223.main-hosting.eu',
        'database' => 'u464254459593_000',
        'port' => '3306',
     
    ]
];

$jasper = new PHPJasper;

$jasper->process(
    $input,
    $output,
    $options
)->execute();
```

**Comment by felipefialho** [comment]
Posta a dúvida no @backend-br
