### ISSUE TITLE
Owl Carousel / Carousel em geral em React...

### ISSUE THREAD

**Issue by wilsonneto-dev** [frontendbr/forum#1544]
Galera, passando um site para react, nele consta alguns carousels usando jquery e owl carusel...

Como vocês fazem estes movimentos usando react? usam jquery com React?

Acham melhor eu criar um componente caroussel? Fazer a parte de movimento no css e os posicionamentos nos states do componente?

É considerado certo usar jquery no react? Ou melhor não utilizar enm mesmo seus plugins?

Obrigado!

**Comment by glauberm** [comment]
Não acho uma boa usar jQuery com React, não. Você deu uma olhada no [repositório deles](https://github.com/OwlCarousel2/OwlCarousel2)? Lá está bem claro que não é mais um projeto ativo, e eles recomendam o uso do [Tiny Slider](https://github.com/ganlanyuan/tiny-slider). Por eles recomendarem, talvez a migração seja mais tranquila. Outra solução bem popular pra React é o [react-slick](https://github.com/akiran/react-slick), que é bem simples de implementar.

**Comment by wilsonneto-dev** [comment]
Show, muito obrigado!
