### ISSUE TITLE
A popup na navegação, como fazer?

### ISSUE THREAD

**Issue by wilsonneto-dev** [frontendbr/forum#1545]
Galera, fiz o site, aparecem as capas dos filmes... tranquilo até ai, a navegação ta ok...

Porém ao clicar na capa de um filme abre um popup com os dados dele, mas isso era para ser uma rota diferente mas com popup... Como faria isso?

A popup não estaria carregada ainda, ao clicar em uma capa que ela abriria, se não tiver como usando rota, como faço para criar um componente na tela pelo react?

Muito obrigado, abraços!

**Comment by glauberm** [comment]
Você está usando o [`react-router`](https://github.com/ReactTraining/react-router) eu imagino, né? Dá uma olhada [nesse exemplo](https://reacttraining.com/react-router/web/example/modal-gallery) na documentação deles.

**Comment by wilsonneto-dev** [comment]
Isso @glauberm, usando o rect-router, vou ver, valeu!!

**Comment by wilsonneto-dev** [comment]
Na verdade olhando novamente a documentação, está ali escrito popup mesmo... mas aqui ele abriu normal, sem ser popup... Lendo a documentação
