### ISSUE TITLE
Como contribuir para projetos open sources?

### ISSUE THREAD

**Issue by wilsonneto-dev** [frontendbr/forum#1546]
Fala pessoal,
desculpa tantas dúvidas hoje rs

Mas esta é mais por curiosidade, como posso encontrar projetos open source para contribuir?

Tem algum projeto brasileiro legal?

Minha stack é:
.Net framework / Core, Node (intermediário), ReactJS, e web geral: HTML, CSS, JS...

Como vocês encontram projetos para contribuir?

**Comment by felipefialho** [comment]
Dá uma olhada no https://github.com/frontendbr/open-source
