### ISSUE TITLE
Loadings e eventos que envolvem vários componentes... Redux ou Hooks?

### ISSUE THREAD

**Issue by wilsonneto-dev** [frontendbr/forum#1547]
Fala pessoal, blz?

Ainda em meu site institucional hehe resolvi usar um loading entre as requisições, criei meu componente e tal... Ele tá lá no meu componente App pai de todos, as páginas estão dentro de um routers dentro dele, o que eu queria era que quando uma página estivesse esperando seus dados do servidor esse loading ficasse visídel....

Bom, já usei redux/reducers e actions em alguns projetos de estudos, usar ele aqui seria uma boa?
Vou usar estados compartilhados apenas neste e em alguns outros poucos casos... Como seria uma solução legal usando Hooks?

Alguém tem um exemplo que se encaixaria aqui? Ou uma dica? Ou uma outra implementação?

Muito obrigado!

**Comment by lucas-moraes** [comment]
**Fala Wilson beleza ?** 
Cara, no mês passado eu participei de um projeto que implementamos ReactJS Hooks (UseState e  UseEffect) para loading, usamos Material UI Skeleton para loading, tipo o do youtube.
Segue link abaixo:
[https://github.com/lucas-moraes/Getpet/blob/master/src/components/petCard/index.js]

Espero que ajude ! E se precisar de ajuda no projeto chama nóis !

**Comment by wilsonneto-dev** [comment]
Shoow @lucas-moraes, mais uma vez muito obrigado!

**Comment by eliseumds** [comment]
Recomendo mover a lógica de data loading para um hook separado (composto), como:

* [react-fetching-library](https://github.com/marcin-piela/react-fetching-library)
* [@apollo/react-hooks](https://www.apollographql.com/docs/react/api/react-hooks/) se estiver usando GraphQL

**Comment by ninetails** [comment]
Falaria para usar Redux somente se vc não estiver confortável em usar Hooks. Para aplicações grandes, falaria para cogitar o uso de Redux somente se vc precisar de um estado da aplicação centralizado.

Sendo coisa nova (dizendo: não legado pq titio Dan Abramov recomenda que para Hooks, deixe o que tá funcionando lá de boas), **Hooks** é uma maravilha. Faça composição entre Hooks criando hooks personalizados. Não dá pra usar hooks dentro de hooks mas dentro de um custom hook dá pra vc agregar toda lógica referente a uma implementação (lembre de _Single Responsability_). Encapsule um 
_useState_ e controle dentro de um _useLayoutEffect_ ou mesmo ao _triggar_ eventos como cliques etc.

Se não me engano o [curso sobre React Hooks do Kent C. Dodds no egghead](https://egghead.io/courses/simplify-react-apps-with-react-hooks) deve ser free.

**Comment by wilsonneto-dev** [comment]
Opa, vou ver esse curso, valeu pela opinião!
