### ISSUE TITLE
React + React Native vs React Native Web

### ISSUE THREAD

**Issue by Fiorim** [frontendbr/forum#1549]
Fala pessoal, tudo bom?

Qual estratégia vocês me indicariam pra desenvolver um app web e mobile usando React?

Minha equipe já optou por usar React e pelo que vi, tem diversas formas de compartilhar código entre a versão web e mobile.

A questão é: esse "compartilhamento" é recomendável ou é melhor ter 2 apps completamente independentes pra não dificultar a manutenção e perder em performance?

Alguma opinião sobre o  Reactive Native Web?

Obrigado!

**Comment by wilsonneto-dev** [comment]
Aqui na empresa a gente está adotando React, mas pelo que vimos vamos compartilhar apenas o conceito, estrutura e dinâmica do react/es. A escrita vai ser personalizada pra cada, até porque tem muito componente e feature no native que no browser não daria certo, além da experiência do usuário que muda bastante também.

**Comment by sbvorpagel** [comment]
Não me aprofundei no assunto, mas na minha visão, é bem complicado compartilhar exatamente o mesmo código, componente, entre plataformas.
Primeiro, um usa componentes básicos em html, outro o nativo. Então, de cara já me parece complicado fazer isso e possivelmente, ineficiente.
Caso o native não seja obrigação, poderia usar algo para gerar a versão mobile via código html/js/css, por exemplo o capacitor https://capacitor.ionicframework.com/docs/getting-started#adding-capacitor-to-an-existing-web-app (Se for usar ele, vai precisar mudar o diretório de origem, pois ele por padrão busca do www e no react é um diretório build, mas pesquisa na net que acha).

**Comment by Fiorim** [comment]
> Aqui na empresa a gente está adotando React, mas pelo que vimos vamos compartilhar apenas o conceito, estrutura e dinâmica do react/es. A escrita vai ser personalizada pra cada, até porque tem muito componente e feature no native que no browser não daria certo, além da experiência do usuário que muda bastante também.

Valeu pela resposta @wilsonneto-dev , pelo que estou vendo não parece ser muito comum misturar web e mobile.

**Comment by wilsonneto-dev** [comment]
Isso, verdade @gss-patricia, aqui também não reescrevemos tudo, tentamos sempre colocar a lógica totalmente desacoplada, assim vamos mudar mesmo componentes de UI / UX, e alguns reaproveitamos também.

Mas reescrevemos praticamente 85% rs
