### ISSUE TITLE
Iniciando carreira como Desenvolvedora

### ISSUE THREAD

**Issue by tnazevedo** [frontendbr/forum#1550]
Bom dia! 
Pessoal, sou nova na comunidade, atualmente estudo desenvolvimento para web com javascript, estou terminando um conteúdo de ES6 no site da alura.
Hoje eu trabalho com infraestrutura de t.i. e quero mudar de área, vocês que já são mais experientes tem alguma dica para iniciar a carreira como programadora,
Estou bem interessada em stack com JS,  que é uma linguagem muito massa. 

Vocês recomendam o bootcamp rocketseat ?

Tem alguma sugestão de curso ?

Eu quero começar a desenvolver mas me sinto ainda um pouco tímida com a linguagem.

**Comment by felipefialho** [comment]
@tnazevedo Faz o JavaScript Ninja do @fdaciuk, sobre JS, curso melhor não tem 🎉

**Comment by evertonthepaula** [comment]
Eu vou te dar algumas recomendações para a vida como desenvolvedora JS:

1 - Estude a base da linguagem JS; 
2 - Estude a base de programação;

Agora vamos aos links.

O melhor lugar do universo para pegar referências sobre desenvolvimento WEB:
https://developer.mozilla.org/pt-BR/docs/Aprender
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide
https://developer.mozilla.org/pt-BR/docs/Aprender/JavaScript

siga este Cara, você vai querer saber a opinião dele:
https://www.youtube.com/user/AkitaOnRails/videos

Acesse esse repositório:
http://cerebrobr.github.io/cerebro/

Leia estes livros:
https://github.com/braziljs/js-the-right-way
http://braziljs.github.io/eloquente-javascript/
https://github.com/cezaraugusto/You-Dont-Know-JS

Obs.: São só referencias, não esqueça de ajudar o autor :) 

Acho que pra começar já é bastante material :) , espero ver vc no fórum em breve!

**Comment by eliseumds** [comment]
Conheço pessoas que curtiram muito o bootcamp da Rocketseat e conseguiram os desejados empregos logo após o término do curso. Se o inglês ainda não estiver afiado, eu recomendo dedicar bastante energia pra ele pois vai expandir suas oportunidades enormemente.

**Comment by ninetails** [comment]
Adicionando, se na tua cidade tiver _meetups_ de _fronts_, participe. Mesmo o de iniciantes.

Ver o que a galera anda fazendo talvez te dê inspiração ou curiosidade para tentar fazer algo ou motive a querer brincar mais com algo voltado a JS.

Resposta mais relacionada a timidez. Acho que perder a timidez viria mais fácil ao ir atrás de alguma motivação que tentar saber mais sobre a linguagem. Digo isso pq pessoalmente acho gratificante fazer algo que sai legal e aprendo muito mais durante a jornada mas mesmo assim quanto mais aprendo, mais existe coisa para aprender. Não espere ter coragem pra fazer algo quando achar que sabe bem (não que eu siga isso que digo 😅).

**Comment by tnazevedo** [comment]
> ### Roadmaps
> Ter um roadmap de quais caminhos seguir é sempre válido, semana passada escrevi [esse artigo, falando sobre coisas que precisamos saber](https://www.felipefialho.com/blog/o-que-front-end-developers-precisam-saber/), tem muita referência legal, pode te ajudar nisso.
> 
> ### MDN
> Vale muito, muito, muito, você consultar o [MDN](https://developer.mozilla.org) de tempos em tempos, de uma qualidade enorme de informações e super acessível para entender.
> 
> ### Sobre cursos:
> Faz o JavaScript Ninja do @fdaciuk, sobre JS, curso melhor não tem 🎉
> 
> (_agora consegui melhorar a resposta, haha_)

rsrs Ajudou muito !! parabéns pelo post.

**Comment by tnazevedo** [comment]
Pessoal, obrigada a todos pela resposta, ajudaram muito muito muito... 
Graças a vocês consegui tomar um rumo, 
Vou fazer o  JavaScript Ninja do @fdaciuk;
Montar alguns projetos pessoais, e frequentar meetups , me inscrevi em um de Javascript para os próximos dias;

Logo mais apareço no forúm novamente rsrs.

**Comment by felipefialho** [comment]
Boa sorte @tnazevedo!
