### ISSUE TITLE
Transformar uma planilha Excel em APP

### ISSUE THREAD

**Issue by ogahga** [frontendbr/forum#1552]
Fala galera, tudo certo? Sou novo no fórum, e novo na programação (se é que da pra dizer que estou dentro, realmente comecei os estudos essa semana).

Eu preciso transformar uma planilha excel, que tem algumas funções como busca em banco de dados e contas razoavelmente simples, em um aplicativo (pode ser web, mas gostaria que rodasse offline). 

Comecei a estudar lógica de programação e JS, por recomendação de um amigo. Gostaria da opinião dos amigos se estou indo pelo caminho certo. Abraço!

**Comment by ogahga** [comment]
*Pelo caminho certo para solucionar o meu problema inicial... 

E se há alguém que faça esse tipo de projeto. Tentei encontrar algum profissional que fizesse e não encontrei.

**Comment by nandomoreirame** [comment]
pra rodar offline só se for PWA amigo, ou fazer um projeto para desktop usando [electron.js](https://electronjs.org/) e deixar tudo local o "conteúdo" do app e instalar nas máquinas.

**Comment by eduardojmatos** [comment]
Tem essa ferramenta aqui que pode te ajudar: https://sheetsu.com/

**Comment by ogahga** [comment]
> Tem essa ferramenta aqui que pode te ajudar: https://sheetsu.com/

Obrigado! Mas esse tipo de ferramenta não serve. Tanto pelo custo quanto pela função mesmo. A planilha que desenvolvi tem algumas funções bem específicas que esse tipo de ferramenta não resolve. Até por que meu interesse é pra fins comerciais. Já comercializo a planilha, mas queria fazer virar app para ter maior controle. 

E não achei um dev ainda que resolva rs

**Comment by ogahga** [comment]
> pra rodar offline só se for PWA amigo, ou fazer um projeto para desktop usando [electron.js](https://electronjs.org/) e deixar tudo local o "conteúdo" do app e instalar nas máquinas.

Vou pesquisar item por item pra entender o comentário. rs Obrigado de qualquer foma!

**Comment by nandomoreirame** [comment]
> > pra rodar offline só se for PWA amigo, ou fazer um projeto para desktop usando [electron.js](https://electronjs.org/) e deixar tudo local o "conteúdo" do app e instalar nas máquinas.
> 
> Vou pesquisar item por item pra entender o comentário. rs Obrigado de qualquer foma!

é nóis 🤜🏼🤛🏾
