### ISSUE TITLE
Como vocês fazem para controlar as requisições assíncronas com Javascript?

### ISSUE THREAD

**Issue by renedocket** [frontendbr/forum#1554]
Olá pessoal, tudo bem com vocês?

Eu estou com uma duvida, recentemente fui implementar um job usando Js vanilla e todas ações da tela são assíncronas. 
Ex: se eu clicar em um botão mais de uma vez ele vai fazer a mesma a requisição várias vezes.

Tem como contornar essa situação fazendo com que a requisição seja feita apenas uma vez a partir do momento que eu clicar no botão?

**Obs:** _Estou usando fetch para as requisições_.

**Comment by wilsonneto-dev** [comment]
O ideal seria desenhar sau estrutura de maneira a ter uma variável, método ou propriedade em alguma classe em que você faça este controle, enfileirando ou apenas setando as requisições como já estando em curso uma, assim antes de chamar outra verifique esta variável...

Consegui ajudar?

Abraços!

**Comment by salatielq** [comment]
Não sei se entendi bem, mas você poderia bloquear o click do botão até a requisição acabar. 
No inicio da requisição você bloqueia quando acabar habilita de novo.

**Comment by victorferreira** [comment]
Pelo que eu entendi, a solução seria implementar algum tipo de _debounce_ pra que, mesmo que o usuário clique várias vezes no botão, apenas uma requisição seja feita num intervalo de tempo. 

Dá uma olhada no debounce do lodash: https://lodash.com/docs/#debounce

**Comment by kvnol** [comment]
@renedocket, o que eu costumo fazer é adicionar o `disabled`no botão. Por exemplo:

```js
clickButton() {
	button.setAttribute('disabled', 'disabled');
	// começa requisiçao
		.then() {
			button.removeAttribute('disabled');
		}
		.catch() {
			button.removeAttribute('disabled');
		}		
}
```

**Comment by ninetails** [comment]
Como disseram, já que é uma ação controlada, ideal seria usar _debounce_ ou mesmo avisar visualmente pro usuário não permitindo fazer novas requisições e bloqueando envios (_disabled_ ou deixando um _loading_).

Caso o problema for requisição fora de ordem (tipo o segundo envio chegar antes do primeiro, aí o primeiro é resolvido e dá ruim), aí vc pode usar o [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController#Examples).

**Comment by renedocket** [comment]
Muito bacana pessoal, obrigado pelas respostas! Vou verificar todas essas possibilidades :)
