### ISSUE TITLE
(Javascript) - Como posso remover a ocorrência de evento duplicado

### ISSUE THREAD

**Issue by Sup3r-Us3r** [frontendbr/forum#1568]
Boa noite pessoal, estou aprendendo JavaScript e resolvi criar esse layout para testar alguns conhecimentos, criei uma tabela e um modal para adicionar usuários a tabela.

Estou criando a parte de **editar** os usuários, e para isso, cada usuário inserido na tabela tem um botão de **editar**, então pensei em adicionar um **evento de click** para que quando o usuário clicar no botão de editar, ele possa executar as regras que preciso.

O problema que estou tendo é o seguinte, ele adiciona o evento de clique normalmente, só que a cada novo usuário inserido na tabela, ele está duplicando o evento de click, e isso não pode ocorrer.

No exemplo abaixo, tenho 3 usuários inseridos, e quando cliquei no botão de editar no primeiro usuário, ele disparou o evento de click 3 vezes.

![erro](https://i.stack.imgur.com/QDU9C.png)

O código que fiz para testar é esse, onde possui um método chamado **editUser**:

    editUser() {
        let editButton = [...document.querySelectorAll('[data-edit]')];
        editButton.forEach((element) => {
            element.addEventListener('click', () => {
                console.log('Cliquei!');
            });
        });
    }

Esse dataset chamado **data-edit** ele está presente em todos os botões de editar, uso ele para localizar esses botões e aplicar o evento de clique.

Gostaria muito de resolver esse problema tentei contornar por esse outro meio mas não funcionou:

    editUser() {
        let fn = (event) => {
            console.log('Cliquei', event);
        }
        
        let arr = [];
        for (let i of [...document.querySelectorAll('[data-edit]')]) {
            arr.push(i);
        }

        for (let i of arr) {
            i.addEventListener('click', fn);
        }

        for (let i of arr) {
            i.removeEventListener('click', fn);
        }

        for (let i of arr) {
            i.addEventListener('click', fn);
        }

    }

Acredito que o problema seja que esse método, está sendo chamado sempre que adiciona um novo usuário na tabela, mas não consegui contornar esse problema, alguém poderia me ajudar? desde já agradeço.

Caso alguém quiser o código aqui está:
hmtl: https://pastebin.com/vRK6XhZj
index: https://pastebin.com/m42pj29S
Código da class: https://pastebin.com/33WXMaZ6

**Comment by expalmer** [comment]
Dá uma olhada nesse projeto, vê se te ajuda [AQUI](https://github.com/expalmer/todo-list-vanilla-js)

**Comment by Sup3r-Us3r** [comment]
@expalmer  obrigado, eu até já suspeitava qual era o problema, pois a cada novo usuário estava repetindo o mesmo evento, enfim, pensei em outra abordagem e parece ter dado certo, fiz o seguinte, fiz a localização dos elementos pelo **id**, e salvei a localização deles em um **array**, após isso usei o método **forEach()** para percorrer cada elemento, e usei o condicional **if** para verificar se aquele elemento possui um **dataset** chamado **editar** se possuir faça nada, se não possuir crie esse **dataset** e adicione o **evento de click** nesse elemento.

**Comment by fdaciuk** [comment]
@Sup3r-Us3r, acredito que você já resolveu, mas existe uma forma bem simples de resolver, e que não precisa de condicional:

Cada item que vai ser renderizado na sua tabela deve ter algum identificador único. Você poderia usar esse identificador na linha da tabela que será removida, ao clicar no botão, e também nos boões de **editar** e **excluir**.

Dessa forma, ao clicar em algum desses botões, você só precisa pegar o dataset do botão que contém esse ID, e então usar o `querySelector` para selecionar a linha da tabela que tem o mesmo ID.

Para o clique no botão de editar, vc faz o processo necessário de edição, e para o clique no botão de excluir, você simplesmente remove o evento dos botões com o mesmo dataset, e então remove a linha da tabela :)

Seria mais ou menos algo assim:

No HTML:

```html
<table>
  <tr data-id="1">
    <td>1</td>
    <td>
      <button data-id="1" data-edit>Editar</button>
      <button data-id="1" data-del>Excluir</button>
    </td>
  </tr>

  <tr data-id="2">
    <td>2</td>
    <td>
      <button data-id="2" data-edit>Editar</button>
      <button data-id="2" data-del>Excluir</button>
    </td>
  </tr>
</table>
```

Essa seria a marcação base no HTML, setando o mesmo `data-id` para a `tr` e os dois `button`, e em cada `button`, um dataset específico para a sua ação (`data-edit` e `data-del`).

O JS ficaria assim:

```js
const editButtons = document.querySelectorAll('[data-edit]')
const deleteButtons = document.querySelectorAll('[data-del]')

deleteButtons.forEach(($button) => {
  $button.addEventListener('click', handleDelete, false)
})

editButtons.forEach(($button) => {
  $button.addEventListener('click', handleEdit, false)
})

function handleDelete (e) {
  const $deleteButton = e.target
  const id = $deleteButton.dataset.id
  const $tr = document.querySelector(`[data-id="${id}"]`)
  const $editButton = document.querySelector(`[data-id="${id}"]`)

  $editButton.removeEventListener('click', handleEdit)
  $deleteButton.removeEventListener('click', handleDelete)
  $tr.remove()
}

function handleEdit () {
  // ...
}
```

Basicamente isso! Você "conecta" os botões com a `tr` à partir do ID :)

**Comment by expalmer** [comment]
A coisa mais legal é o que fez, tentar fazer por si mesmo e enfrentar problemas...daí você se depara com alguma dificuldade e vai atrás...parabéns.
E para se tornar bom, segue e faz o cursos do mestre @fdaciuk aeee :)

**Comment by eduardosoareszup** [comment]
Talvez colocar o evento `onclick` no html seja mais simples e de fácil entendimento

```
<td>
      <button onclick="editUser()">Editar</button>
      <button onclick="deleteUser()">Excluir</button>
</td>
```

Outra coisa interessante é colocar um `id` nos objetos, porque provavelmente quando você for integrar com uma `API` você terá de utilizar.

```
<button onclick="editUser(id)">Editar</button>
```

**Comment by Sup3r-Us3r** [comment]
@fdaciuk Muito obrigado, pela explicação e por ter mostrado um método alternativo para contornar essa solução, gostei muito da sua abordagem, realmente é excelente, obrigado pelo seu tempo!

<hr>

@expalmer Muito obrigado, estou começando com Desenvolvimento Web e comecei por HTML e CSS e só determinei que iria seguir em diante quando eu realmente aprendesse HTML e CSS então me desafiei a criar 2 layouts que jugo ser difíceis que é o do Twitter e Facebook de forma responsiva: [repositório com os layouts](https://github.com/Sup3r-Us3r/tailwind-layouts)

E agora estou aprendendo Javascript, e só quando eu aprender o Javascript puro mesmo que irei seguir para algum Framework ou Biblioteca (React e React Native).

Prefiro quebrar a cabeça e só quando tiver muito difícil que pergunto, mas não deixo de tentar continuar a tentar.

<hr>

@eduardosoareszup Obrigado por mais uma alternativa, realmente é um outro meio mais simples de resolver o problema!

**Comment by felipefialho** [comment]
@Sup3r-Us3r Quero elogiar inclusive a abertura da issue em si, bem detalhada sobre qual o problema precisava resolver e com exemplos de código no pastebin.

Parabéns 👏

**Comment by Sup3r-Us3r** [comment]
@felipefialho muito obrigado, é minha primeira publicação aqui no fórum, achei um máximo usar as issues do GitHub para servir de dúvidas da galera, pessoal muito prestativo, com vontade de ajudar o próximo isso é incrível, é raro achar uma energia tão boa quanto essa, obrigado por tudo galera!
