### ISSUE TITLE
Como criar máscaras dinâmicas no angular 8?

### ISSUE THREAD

**Issue by PabloFerreiraB** [frontendbr/forum#1569]
Estou utilizando o **ngx-mask** e não consegui fazer com que a mascara seja aplicada de acordo com o texto digitado.

Ex: Input de telefone com 10 ou 11 dígitos.

Telefone fixo: **(99) 9 9999-9999**
Celular: **(99) 9999-9999**

Se alguém souber e tiver um exemplo, agradeço!

**Comment by lucasferreiralimax** [comment]
Olá Pablo tudo bem?

Você pode fazer de diversas formas
A mais recomenda é utilizar um pipe para transformar seu valor

Veja mais sobre Pipes na documentação
https://angular.io/guide/pipes

Com Pipe você vai pegar o valor e tratar do jeito que deseja criando incrementando e manipulando da forma que quiser com JavaScript.

Veja outros exemplos nessa questão no Stack

https://stackoverflow.com/questions/36895431/angular2-pipes-how-to-format-a-phone-number

Tem até um exemplo usando slice direto no valor que eu não recomendaria por ser difícil a manutenção porém é possível.

Se fizer mais pesquisas e estudos irá encontrar muitas outras formas, mas a mais recomenda é usar o Pipe com sua modificação no próprio Angular.

Abraços, espero ter ajudado e bons estudos.

**Comment by gabriel-hahn** [comment]
Você pode tentar utilizar o pipe ou a propriedade _mask_ da mesma maneira que a documentação do ngx-mask informa:

`<input type='text' mask='{here comes your mask}' >`
ou
`<span>{{phone | mask: '(000) 000-0000'}}</span>`

De qualquer maneira, tu pode criar teu próprio pipe e tratar o valor do jeito que achar melhor através do @ Pipe do @ angular/core, assim como o @lucasferreiralimax citou.

**Comment by PabloFerreiraB** [comment]
@lucasferreiralimax , @gabriel-hahn teria algum exemplo de implementação?
Não achei nada concreto que atue dinâmico,também não consegui reproduzir algo assim.
Obrigado!

**Comment by gabriel-hahn** [comment]
O pipe já irá funcionar dinamicamente, por exemplo:

```
<p>{{ description | uppercase }}</p>
<input [(ngModel)]="description">
```
Esse código já seria o suficiente para refletir a alteração no description e com o pipe de uppercase conforme o usuário vai digitando no input. Neste caso o uppercase é um pipe default no Angular.
A vantagem de usar o ngx-mask é não se preocupar em criar uma pipe manualmente e utilizar as regras das máscaras existentes na documentação.

Caso ainda restar dúvidas, posta a parte do teu código que tu precisa implementar a máscara.

**Comment by PabloFerreiraB** [comment]
@gabriel-hahn obrigado pela explicação. Ainda sim, não entendi como aplicar a mask em um input apenas. Para duas condições de Telefone Fixo (10 dígitos) ou Celular (11 dígitos).

Segue meu html com a Mask.
` <input type="text" name="telefone" id="telefone" class="form-control" formControlName='telefone'
            mask="(00) 0000-0000">`

Dessa forma aplica apenas uma mask. Pra mim que teria que ter alguma função ou condição tipo *ngIf para setar a Mask de acordo com o tanto de caracteres dígitados.

Obrigado!

**Comment by gabriel-hahn** [comment]
Para uma máscara dinâmica no input e usando o ngx-mask, fiz uns testes aqui e funcionou da seguinte maneira:

**Input:**
`<input [ngModel]="phoneNumber" mask="{{ phoneMask }}" (ngModelChange)="phoneNumber=$event; onPhoneChanged()" type="text" />`

- Criei a variável **phoneMask** para conter a máscara a ser aplicada. Utilizei desta maneira para alterar a máscara dinamicamente.
- O **onPhoneChanged** será o método que irá validar quando aplicar a máscara correta.

**Componente:**

Constantes (máscaras):

```
const CELLPHONE = '(00) 0 0000-0000';
const LANDLINE= '(00) 0000-0000';
```

Propriedades do componente e método de validação:

```
phoneMask = LANDLINE;
phoneNumber = '';
previusLength = 0;
```
- Criei a variável **previusLength** para validação ao mudar a máscara no último caractere. Como a máscara inicial é um número menor que a máscara de número de celular, não seria possível adicionar este 11º número.

Método **onPhoneChanged**:

```
onPhoneChanged() {
   if (this.phoneNumber.length <= 10 && this.phoneMask === CELLPHONE) {
     this.phoneMask = LANDLINE;
   }
   else if (this.phoneNumber.length === 10 && this.phoneMask === LANDLINE && this.previusLength === 10) {
     this.phoneMask = CELLPHONE;
   }

   this.previusLength = this.phoneNumber.length;
 }
```

Neste método, só adicionei algumas validações a respeito de alteração do tamanho do número digitado para então alterar a máscara.

Não tive tempo de validar todas situações, ver se existe algum bug ou um jeito melhor hehe mas basicamente eu iria por esse caminho, já que tu precisa de algo que altere a máscara de um input enquanto o usuário digita o telefone dele.

Espero ter ajudado :)

**Comment by PabloFerreiraB** [comment]
Vou aplicar seu modelo amanhã! Muito obrigado!.

**Comment by natanlf** [comment]
Achei um bug mas usando keyup e recuperando o valor digitado pelo formGroup funcionou.
O problema foi após digitar, começando a apagar valores para voltar ao telefone ao invés do celular, assim pegou a máscara errada.

**Comment by adelinoreis** [comment]
Olá,

Usando o ngx-mask, é só você colocar os dois valores no seu input:
 <input type="text" mask="(00) 0 0000-0000 || (00) 0000-0000">

**Comment by adelinoreis** [comment]
Olá,

Usando o ngx-mask, é só você colocar os dois valores no seu input: 
```<input type="text" mask="(00) 0 0000-0000 || (00) 0000-0000">```

**Comment by MatheusSchreiner** [comment]
Ao utilizar um FormControl você consegue utilizar o método dele chamado valueChanges que é igual um addEventListener puro do JavaScript, nisso ele fica ouvindo todas as mudanças feitas no seu input que esta com a variavel telephone

  public telephone = new FormControl();

  public teste = this.telephone.valueChanges.subscribe((value: string) => {
    const CEL = "(00) 0 0000-0000";
    const TEL = "(00) 0000-00009";
    this.CEL_TEL = value.length == 11 ? CEL : TEL;
  })

no HTML

<input type="text" formControlName="telephone" [mask]="CEL_TEL" />

dessa forma sempre que você escrever no seu input ele irá setar com a mascara do seu ternário, o número 9 na variavel TEL é necessário para que você consiga digitar o ultimo numero e ao digitar o ternário irá setar a marcara de 11 dígitos
