### ISSUE TITLE
Como conseguir um estágio? Como montar um portfólio para conseguir um estágio?

### ISSUE THREAD

**Issue by kaiomazziero** [frontendbr/forum#1574]
Oi pessoal, tudo bom? Espero que sim!

Então, eu iniciei meus estudos em Front End a mais ou menos uns 3 meses (eu sei que é bem recente ainda), só que até então eu tava só na teoria e alguns exercícios, só que agora eu gostaria de começar a montar um portfólio com projetos pra tentar começar a procurar um estágio. Eu gostaria, se possível, algumas dicas de como montar um portfólio quais projetos seria interessante colocar. E algumas dicas também sobre onde procurar estágios, eu cheguei a ler algumas coisas em alguns sites sobre como conseguir um estágio (principalmente em inglês), mas acho que por ser principalmente tudo em inglês, não sei se isso se aplica aqui ao BR. Uma das coisas que me deixou um pouco assustado, é a quantidade de coisas que se pedem pra um estagiário, algumas vagas até com experiência. Como eu consigo experiência sem ter trabalhado com as tecnologias Front End?
O que eu estava estudando até então é HTML, CSS e JS. 
E outra dúvida, eu estava pensando em comprar o curso FS da Danki Code, alguém tem recomendações positivas ou outras recomendações de cursos (principalmente de CSS, esse trem é muito dificil)?

Muito obrigado.

**Comment by hirvin-faria** [comment]
Olá mazziero, tudo bem.
Eu também sou iniciante com desenvolvimento. Acho que uma boa maneira de conseguir experiencia é continuar estudando e aplicar oque aprendeu em pequenos projetos. Pode começar a fazer pequenos projetos de páginas web estáticas usando HTML e CSS, também pode aplicar o bootstrap nelas, além de poder estudar posteriormente como aplicar JS ou fazer pequenas aplicações que mostre a manipulação no DOM. Acho uma boa para aplicar conceitos básicos e montar pequenos projetos de para portfolio.
Não recomendaria ter vários projetos como portfólio, as vezes e legal ter um projeto bem estruturado do que vários projetos pequenos. E assim pode disponibilizar eles no github para outras pessoas acessarem.
Até mesmo acho uma boa idea fazer uma página de currículo online ou site para o GitHub Pages.

Sobre o curso da Danki Code eu não posso falar muito sobre pois nunca cursei. Mais para fazer cursos online eu recomendaria fazer os cursos na Alura, pois lá você tem trilhas bem definidas de aprendizagem e além de ver conteúdo de front end pode ver outros conteúdos também caso precise.
Eu também recomendaria alguns cursos da Udemy, alguns conteúdos são muito bons e você pode encontrar cursos por valores bem baratos. Mais é bom sempre ficar de olho nas avaliações do curso, e no conteúdo deles, muitos tem algumas aulas gratuitas que você pode assistir, assim pode ver se ira gostar do método do professor do curso.

Cursos que recomendaria da Udemy são:
- https://www.udemy.com/course/web-completo/
- https://www.udemy.com/course/curso-web/

São dois cursos que eu fiz e achei muito bons.

Além disso eu também te recomendo para se aprofundar em javascript o livro: JavaScript: O Guia Definitivo do David Flanagan

Sobre a questão do CSS eu lhe recomendo a procurar um pouco sobre como organizar o código do CSS, e olhar projetos de outras pessoas para ter exemplos. Assim pode ver como elas fazem as definições de classes, e organizam cada conteúdo. Mais acredito que o melhor seja você mesmo aplicar oque aprendeu, mesmo que errado, e posteriormente pesquisar como outras pessoas resolveram algum problema, assim você ira refinar suas habilidades com o tempo.

Um site que pode lhe ajudar tanto com HTML, CSS e JS é o https://developer.mozilla.org/pt-BR/.

**Comment by ninetails** [comment]
Não querendo ser o chato e sim apontando recursos, tem muita coisa já conversada em threads mais antigas aqui sobre carreira, vale dar muita olhada ;D

Então, portifólio é interessante caso vc tenha o que mostrar. Falaria para priorizar antes de tudo teu LinkedIn e subir mais coisa que vc tá estudando no GitHub (este último eu digo não para empregabilidade e sim pra vc, bate na madeira mas imagina perder tudo o que vc fez que tá no teu PC).

**Comment by theandersonn** [comment]
Sobre CSS: Domine as propriedades, entenda como elas funcionam e como aplicar atributos para que funcionem isoladas e em grupo. 

Esse é um ponto sensível no CSS, um <p>, <span>, <h1>, <a>, <div> são bem comportados sozinhos, mas quando temos que agrupa-los para diagramar um site, são travessos.

É importante também entender sobre o universo float, uma era tenebrosa que ainda nos assombra, presente em muitos projetos legados.

Incompatibilidade entre browsers.
Diagramação moderna com flexbox e grid layout.

Tem também o universo dos builders, automatizações, onde estão presentes jóias como stylus, sass, pug, Handlebars ... ferramentas que facilitam o trabalho no dia, mas é espinhento, tem que ir com calma.

Aplique o que aprende em projetos aqui github.

**Comment by wilsonneto-dev** [comment]
Indico dar uma olhada em Gulp para automatizar as coisas com o Babel e com o SASS/SCSS, e até para criar builds de páginas simples otimizando com compactação, remover comentários e até diminuir tamanhos de imagens...

Uso o gulp em projetos com Html + CSS + JS simples para automatizar as coisas + build,
já na maioria dos casos estou usando React então vou de webpack, mas me agrada mais o gulp rs

Abs

**Comment by igorthurow** [comment]
Mano!

Da uma olhada nessas issues MINHAS, certeza que são pertinentes pra você! [Aqui](https://github.com/frontendbr/forum/issues/968) e [aqui](
https://github.com/frontendbr/forum/issues/1016)

Te indico estudar o suficiente de HTML e CSS para criar um site pessoal. 
Registra um domínio com seu nome, isso passa credibilidade. 

Neste projeto mostre que se preocupa com responsividade, boas praticas e SEO, assim você já sai na frente de 90% dos devs que irão competir com você.

**Comment by felipefialho** [comment]
@mazziero Artigo novinho saindo do forno :) 

https://www.felipefialho.com/blog/como-estudar-praticar-e-conseguir-oportunidades-como-front-end-developer/
