### ISSUE TITLE
Error --- npm run build --------npm-start---->webpack

### ISSUE THREAD

**Issue by evertonProgramadorCriativo** [frontendbr/forum#1579]
eu  ja fiz de tudo , ja baixei  BuildTools_Full , ja renicie o pc  e essta dando esse error  quando eu dou npm run build

estou usando node v10.16.3

-----------------------------------------------/-------------------------------------------------
Projeto link ----> https://github.com/evertonProgramadorCriativo/bootstrapGaleria
--------------------------------------------------------/-----------------------------------------

![web1](https://user-images.githubusercontent.com/55323538/67578877-bdad3900-f719-11e9-8187-d085b399c64d.png)
![web2](https://user-images.githubusercontent.com/55323538/67578878-be45cf80-f719-11e9-92b1-e1cfc362c93e.png)
![web3](https://user-images.githubusercontent.com/55323538/67578879-be45cf80-f719-11e9-9214-74cd227d8c57.png)
![web4](https://user-images.githubusercontent.com/55323538/67578881-be45cf80-f719-11e9-819a-a7abfb27c902.png)
![web5](https://user-images.githubusercontent.com/55323538/67578882-bede6600-f719-11e9-9e3e-be93735892ed.png)

**Comment by simaodeveloper** [comment]
Parece que você copiou e colou o css de outra formatação e ele não esta reconhecendo o caracter inválido

**Comment by ninetails** [comment]
aparentemente falta configurar o loader para fontes
