### ISSUE TITLE
ola amigos  , estou procurando projetos para eu poder contribui no github  

### ISSUE THREAD

**Issue by evertonProgramadorCriativo** [frontendbr/forum#1581]
deixe aqui os link dos projeto para eu poder contribui

**Comment by felipefialho** [comment]
Fala mano, dá uma olhada no [frontendbr/opensource](https://github.com/frontendbr/opensource)

**Comment by MrS4w** [comment]
Só uma corrigida, @felipefialho 
https://github.com/frontendbr/open-source
