### ISSUE TITLE
Como avançar no Front-End e começar a trabalhar?

### ISSUE THREAD

**Issue by luanpanno** [frontendbr/forum#1582]
Boa tarde pessoal, eu gostaria de começar a fazer freelas como front-end mas estou travado. Já sei HTML, CSS e JavaScript e consigo criar sites com layouts interessantes, mas não consigo mais avançar a partir daqui, não sei o que começar a aprender depois disso. Além disso, gostaria de saber como funciona um freela, por exemplo; eu mando os arquivos pra pessoa que me contratou? eu mesmo crio o site? estou realmente perdido nisso. Se puderem me clarear um pouco, eu agradeço demais!

**Comment by igorthurow** [comment]
Oi Luan, tudo bom?

Quando eu estava estudando, tive a sorte de conseguir um freela para a empresa de um amigo. 

Eu fiz todo o processo: Registro de dominio, direcionamento de DNS, subida de arquivos no FTP e finalmente entreguei o site completo.

Neste processo você vai além do desenvolvimento front-end, você vai aprender outras coisas da atmosfera de criar um site (tipo .htaccess), o que vai ser muito útil e diferenciado, visto que poucos devs fazem o processo do zero a entrega completa assim.

Sobre o que estudar agora: Começa a desenvolver um projeto de site REAL, e você vai quer que no caminho irão surgir duvidas sobre semântica, CSS, JS, responsividade, acessibilidade, SEO.. 
Você provavelmente vai ver a necessidade de aprender um pouco sobre task runner pra automatizar parte do teu trampo braçal e por ai vai... Um projeto REAL do zero, tem muito a te agregar e vai te mostrar que muita coisa que voce aparentemente sabe, na verdade pode melhorar. 

Estudar é excelente mas os projetos irão ajudar a fixar o que voce aprendeu e a solucionar duvidas comuns que todos devs terão ou ja tiveram um dia.

Abraco!

**Comment by felipefialho** [comment]
@luanpanno Escrevi um artigo que endereça um monte de issues abertas na última semana e acredito que pode ser seu caso, saca só 😄 

[Como estudar, praticar e conseguir oportunidades como (Front-end) Developer](https://www.felipefialho.com/blog/como-estudar-praticar-e-conseguir-oportunidades-como-front-end-developer/)

**Comment by thmachado** [comment]
Tive esse mesmo problema que você no início, o que me incomodava era a falta de criatividade para alavancar e testar minhas skills, não sabia como tentar forçar esse "aprendizado".

O que me ajudou muito foi seguir por desafios constantes, seja nos projetos reais na qual estou inserido, onde simplesmente não existe a possibilidade de dar errado, ou por projetos individuais.

Caso você não consiga encontrar freela, não consiga uma oportunidade mais concreta, tenta desafiar cada vez mais seus conhecimentos de outras formas, seja pelos Challenges do Front-End BR (que me ajudaram muito) ou de outros projetos. 

Acho que estamos inseridos em um contexto em que você enxerga tantas possibilidades, que não sabe por qual possibilidade seguir. Seja em questão de linguagem ou até mesmo, com essa cacetada de frameworks existentes. Mas fica suave, de verdade.

Por fim, posso garantir pra você que proatividade, comunicação e acima de tudo, criatividade, são pontos muitos relevantes, talvez, em alguns casos, posso ousar em dizer sendo até mais importantes do que saber de tudo.

Como o monstro Fabio Akita diz: Apenas coda, coda, e coda. É assim que se aprende.

**Comment by tnazevedo** [comment]
@luanpanno  Blza ? 

Então eu tive a mesma dúvida que você, eu aprendi Html css JS mas ai tipo não sabia mais o que fazer e para onde ir, no meu caso parceiro, eu senti que precisava melhorar minha prática ai resolvi aprender react e react native,  acabei entrando no bootcamp da rocketseat, e até o momento foi a melhor coisa que fiz, 
Mudou minha cabeça e abriu para várias possibilidades, 

-  Fazer desafios.

-  Participar de Eventos e Palestras

- Treinar e copiar apps e sites.

-  Fazer novas amizades,  relevantes na área (esse ultimo ajuda muito quando a gente está travado).

**Comment by evertonProgramadorCriativo** [comment]
ola amigo luanpanno !!! para completa o que os meus colegas já disseram , vai olhando a documentação e tenta fazer o layout do facebook , Youtube , Mercado Livre e esses projetos que você fizer vai servi como experiencia para você e vai  poder apresenta para empresa , eu acho que vai conta bastante ponto !!! E para finalizar o melhor aprendizado na minha opinião e a pratica , ser você tem 2 horas para estuda durante o dia (30 minutos teoria , 1:30 de pratica ) ser você nao soube fazer algo dar uma pesquisa no Youtube ou no google , mas der preferência aos vídeos por que sao mas didáticos , depois que você ter realizado essa duas 2 tapas , para fecha com chave de ouro , depois de ter feito esses {3 layout (facebook , You... ,Mercado livre) em sass ou css puro } faça eles denovo agora com React js Por que a principal idea do react js e fazer bloco reutilizáveis conhecidos como componentes , estou compartilhando uma experiencia de vida com voce ,espero ter ajudado , ser preocupa a fazer mais projetos do que a teoria , nao ser preocupa em grava código isso vai vim com o tempo , isso que eu falei e para a programação entra na sua cabeça , depois quando voce entra para um emprego voce vai aprender muito mais !!!

**Comment by luanpanno** [comment]
Obrigado a todos pelas respostas!! Nessas férias de dezembro vou focar em estudar front-end, fazer desafios e criar alguns projetos e replicar layouts pra estudo, e ano que vem já começo a procurar trabalhos (estágio, freelas ou ser contratado mesmo) pois acredito que já estarei preparado. Novamente, obrigado pessoal!
