### ISSUE TITLE
Há um espaçamento inconsistente entre os botões. Preciso de ajuda para identificar a causa desse problema

### ISSUE THREAD

**Issue by gabrielclaudino** [frontendbr/forum#1597]
Estou fazendo um pequeno projeto que simula a visualização em árvore. É algo bem simples: você consegue criar e excluir itens, além de poder transformá-los em uma espécie de pasta com  a possibilidade criação de sub-itens dentro delas. [Link para testar no CodePen](https://codepen.io/gabrielclaudino/pen/pooVzmV)

Durante o desenvolvimento, acabei esbarrando em um problema insólito. Os botões estão tendo um espaçamento inconsistente, como o print mostra:

![Imagem da tela](https://user-images.githubusercontent.com/26636890/68327498-3c0bc280-00ac-11ea-9c2c-684327ad2fea.png)

Normalizei o CSS dos componentes para ver se resolvia, mas problema persistiu e ficou até mais evidente:

![Imagem da tela](https://user-images.githubusercontent.com/26636890/68327644-783f2300-00ac-11ea-8464-9e0d31edee36.PNG)

Testei em vários navegadores e o erro continua. O único padrão que notei, é que esse distanciamento estranho acontece quando o botão de minimizar é adicionado ao lado de um elemento já existente. Quando os dois botões são gerados via Javascript, o espaço é consistente.

**Comment by glauberm** [comment]
O espaço entre os botões a partir do terceiro nível, se não estou enganado, está vindo da sua própria regra `margin: 0.25rem`. Para o espaço dos botões que estão no segundo nível, dá uma olhada [nesse artigo](https://css-tricks.com/fighting-the-space-between-inline-block-elements/): a boa é você envolver os elementos em uma flexbox.

**Comment by lucianobarauna** [comment]
eu reparei isso também mais fiquei meio perdido na explicação @glauberm

**Comment by gabrielclaudino** [comment]
Obrigado pelas dicas glauberm, vou ler! Só o que me deixa mais confuso foi isso:

![test](https://user-images.githubusercontent.com/26636890/68330788-9ad43a80-00b2-11ea-98f5-5a55532cd31b.gif)

Se eu troco de rem para px, fica assim:

![test1](https://user-images.githubusercontent.com/26636890/68331181-4b423e80-00b3-11ea-9008-6905d113ff8b.gif)

**Comment by glauberm** [comment]
@lucianobarauna Basicamente a quebra de linha entre os `<button>` no HTML se converte em espaço visual.

@gabrielclaudino Mas você tá mudando o `font-size` para `px` em qual elemento? Imagino que role do espaço gerado pela quebra de linha aumentar com o `font-size` de um elemento pai...

**Comment by vhfmag** [comment]
@gabrielclaudino acho que achei o problema: um espaço em branco :sweat_smile: https://codepen.io/vhfmag/pen/yLLjYyq?editors=1000

O problema parece ser que os elementos que já vem no html tem um espaço entre a span do `new item` e o botão de deletar. Ao chamar `element.firstElementChild.insertAdjacentElement('afterend', btn);`, o botão de colapsar é inserido imediatamente depois do span e, portanto, antes do espaço. Já os `new item` criados via js não tem o espaço, por isso o espaçamento muda.

**Comment by gabrielclaudino** [comment]
Caramba, 😮 era uma coisa besta. Muito obrigado, @vhfmag! Valeu tb, @glauberm o post que vc me mandou foi muito bom

**Comment by lucianobarauna** [comment]
Sim to ligado @glauberm
