### ISSUE TITLE
Como controlar duas teclas com a função 'window.addEventListener('keydown')'

### ISSUE THREAD

**Issue by JorgeBaes** [frontendbr/forum#1607]
window.addEventListener('keydown',kd)

function kd(e){
   var key = e.keyCode

   if(key === UP){ /*jogador 1 anda para cima*/}
   if(key === W){ /*jogador 2 anda para cima*/}
}

O código é basicamente isto: quero mover dois jogadores simultaneamente com o teclado.
Isto é possível??
O que acontece é que deste modo que está ai não é possível mover os dois ao mesmo tempo,
se um está em movimento e clica-se para mover o outro, o que está em movimento para e o outro
começa a se mover. Então minha dúvida é : tem como controlar teclas simultaneamente??

**Comment by eliseumds** [comment]
Todos os eventos serão registrados mesmo se outras teclas já estiverem pressionadas. O jogador vai reagir *enquanto* a tecla estiver pressionada, e pra detectar isso, você vai combinar keydown (pressionada) + keyup (solta). Exemplo: https://www.w3schools.com/code/tryit.asp?filename=G08VUWUY1MU4
