### ISSUE TITLE
Alguém sabe aonde tem projetos Open Sources para serem colaborados?

### ISSUE THREAD

**Issue by Marcelosilva10** [frontendbr/forum#161]
Bom dia a todos, sou iniciante em Front end vi que tem muitos ninjas aqui, algum de vocês sabem aonde pode colaborar com projetos Open muitas vagas de emprego pedem para ter um portfólio ou algo do gênero.

**Comment by dleitee** [comment]
Fala @Marcelosilva10,

Aqui tem um repositório que fala justamente disso: [https://github.com/frontendbr/open-source](https://github.com/frontendbr/open-source).

**Comment by LFeh** [comment]
Valeu @dleitee ;)

Tem essa issue também -> https://github.com/frontendbr/forum/issues/5
