### ISSUE TITLE
Alguém estuda FIAP EAD?

### ISSUE THREAD

**Issue by bartier** [frontendbr/forum#1626]
Pessoal, tudo bem?

Alguém faz o curso de Técnologo em Desenvolvimento de Sistemas ou Sistemas de Informação na FIAP?

Ambos cursos tem a opção EAD e como já estou na 'área' acho que seria uma boa opção já que poderia otimizar meu tempo e tudo mais...

[Sistemas de Informação EAD - Bacharelado](https://www.fiap.com.br/online/graduacao/bacharelado/sistemas-de-informacao/)

[ADS - Tecnólogo](https://www.fiap.com.br/online/graduacao/tecnologo/analise-e-desenvolvimento-de-sistemas/)

Aproveitando a discussão, gostaria de saber se vocês acham que faz muita diferença cursar Tecnológo/Bacharel pensando especificamente no processo de imigração do Canadá, alguém teria experiência para contar? 

Desde já obrigado =)

**Comment by felipefialho** [comment]
Seguem links: #564 #1441
