### ISSUE TITLE
Algum projeto para contribuir?

### ISSUE THREAD

**Issue by francysreymer** [frontendbr/forum#1635]
Ola pessoal,

eu estou no mercado de desenvolvimento ha mais de 10 anos principalmente com PHP. Recentemente, me tornei gestor de projetos e desenvolvedor de uma empresa no qual trabalho com CodeIgniter e ParseQuery (este em Nodejs). Porem, ainda me considero iniciante em javascript...linguagem no qual quero me especializar com forca.

Alguem sabe de algum projeto, pode ser open source ou nao, para que eu posso contribuir gratuitamente?

**Comment by kvnol** [comment]
@francysreymer obrigado pela disponibilidade, temos vários aqui: https://github.com/frontendbr/open-source/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
