### ISSUE TITLE
Acer i5 8GB-gforce de 2GB ded-Ssd 128Gb, tela TN-Consigo trabalha com frontend?

### ISSUE THREAD

**Issue by antoniofantoni** [frontendbr/forum#1642]

**Comment by willycamargo** [comment]
Resposta curta?
Sim.

Resposta longa?
Claro que sim.

**Comment by antoniofantoni** [comment]
Obrigado !


Em 30/12/2019 15:06:58, Willy Camargo escreveu:
> Resposta curta?
> 
Sim.> 
> Resposta longa?
> 
Claro que sim.> 

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, > view it on GitHub> , or > unsubscribe> .> 




-- 
​Antonio Braga Fantoni
DIAC- Divisão de Auditoria e Conformidade



ramal. 8693
DIT\SUGS\DEGO\DIAC
Cosme Velho - 3º andar

**Comment by willycamargo** [comment]
Se for sair por ai pesquisar, encontrará inúmeras fontes indicando máquinas muito melhores que essas. Mas não se deixe intimidar por isso.

Deve existir uma configuração mínima para poder estudar/trabalhar, mas eu desconheço ela.

Garanto, por experiência própria, que com as configurações que você citou é possível trabalhar e qualquer coisa além disso se resume em produtividade e conforto, e não em conseguir ou não trabalhar.

Uma máquina melhor pode significar mais produtividade, principalmente se for necessário rodar programas de edição (adobe, figma, etc) ou a stack de desenvolvimento backend na mesma máquina. (banco, servidor, docker etc)

**Comment by antoniofantoni** [comment]
Valeu Willy! Tinha esse feeling, agora estou mais seguro na compra que fiz, aguardando chegar o brinquedo novo. :>)
tks
