### ISSUE TITLE
Abri o código de um portfólio que foi Site of The Day no Awwwards.

### ISSUE THREAD

**Issue by lhbizarro** [frontendbr/forum#1657]
Fala pessoal, tudo bem? Não sei se essa informação chegou para muitos de vocês, mas estou criando essa issue com esse objetivo. 😄 Ano passado eu criei um site para um designer chamado [Bruno Arizio](https://brunoarizio.com/) com o objetivo de ganhar um Site of The Day no Awwwards e nós conseguimos isso no dia [25 de Novembro de 2019](https://www.awwwards.com/sites/bruno-arizio-portfolio).

Depois de um tempo fomos convidados pelo Codrops para criar um artigo explicando como foi a implementação do código desse site e ficamos tão entusiasmados que decidimos abrir o código do portfólio para todos terem a chance de ver como ele foi criado.

Acho que é uma maneira de tentar fazer a comunidade brasileira fazer mais parte de competições como essa e também de inovar um pouco mais em alguns aspectos, pois muito poucos sites brasileiros são premiados lá.

**Enfim, [o portfólio está disponível aqui no GitHub](https://github.com/lhbzr/bruno-arizio) para quem tiver interesse. 🤘** Se vocês quiserem alguma ajuda para tentar rodar o projeto na máquina de vocês, me mandem uma mensagem que eu tento responder o mais rápido possível.

**Comment by fabionascimento1** [comment]
Fiz instalação dos packages....  yarn

criei arquivo .env  mas da erro PRISMIC_ENDPOINT  que seria url https://xxx.cdn.prismic.io/api/v2 ??

poderia me ajudar?
