### ISSUE TITLE
Sobre idade e carreira

### ISSUE THREAD

**Issue by jotepauder** [frontendbr/forum#1667]
Boa tarde pessoal, 

Sei que aqui é focado em front-end, mas é um dos melhores 
foruns para se tirar dúvidas e até fazer grandes amizades, mas 
eu tenho dúvida e é a seguinte, que foi teve até um tópico recente
sobre começar mesmo na área depois dos 26 em diante, hoje estou 
com 28 e estou em um estágio, que trabalho como full-stack
no back usamos Java e Spring, e no front é Javascript e Angular, 
eu já sei com o que eu quero trabalhar que é com Android nativo, 
mas também gosto da parte web, e gostaria de trabalhar na parte 
mobile utilizando frameworks Javascript, mas eu acho que o meu 
interrese pela parte na web é mais por não conseguir ainda trabalhar
com Android nativo, para vocês é possível conciliar os estudos dos
dois, sendo que eu migrei de área, era do suporte e comecei com 
programação agora, as vezes bate uma bad por causa da idade, 
desculpe o texto grande.

**Comment by SibilaSabrina** [comment]
Olá! Então, completo 38 este ano, já trabalho com web desde 2006 mas quero entender de vez todo este lance de stack JavaScript, que eu sempre olhei de longe por puro medo. Sempre que eu acho que tô velha pro rolê eu lembro do grande dino Maujor, que depois de aposentado e já com 56 foi ver qualé das CSS. Foca nos teus objetivos e dá-lhe =)
