### ISSUE TITLE
ERRO - TypeScript não está carregando

### ISSUE THREAD

**Issue by Al3xFlores** [frontendbr/forum#1668]
**Olá! 
Estou estudando TypeScript para posterior passar a estudar angular, porem no primeiro teste apareceu o seguinte erro;** 
O arquivo C:\Users\alexm\AppData\Roaming\npm\tsc.ps1 não pode ser carregado porque a execução de scripts foi desabilitada neste 
sistema. Para obter mais informações, consulte about_Execution_Policies em https://go.microsoft.com/fwlink/?LinkID=135170.
No linha:1 caractere:1
+ tsc type.ts
+ ~~~
    + CategoryInfo          : ErrodeSegurança: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

Alguém já teve esse problema ou tem conhecimento de como resolver?

**Comment by wilsonneto-dev** [comment]
Acredito que se você executar "Set-ExecutionPolicy AllSigned" vai resolver.

O problema ai é políticas de acesso do powershell, nem chegou na parte do Typescript pra dar o erro ai...

Ou, executa pelo cmd/prompt mesmo.

Depois posta se ajudou, abraços!

**Comment by Al3xFlores** [comment]
Bom dia Wilsonneto, obrigado por respondeu meu tópico. 
Esse comando  "Set-ExecutionPolicy AllSigned" não está sendo possível executar no CMD

**Comment by Al3xFlores** [comment]
Wilsonneto encontrei a solução em um vide-o, vou estar compartilhando para quem tiver o mesmo problema; https://www.youtube.com/watch?v=J30n3lMyvbY
