### ISSUE TITLE
Qual é a diferença entre Função, Classe e Metodo

### ISSUE THREAD

**Issue by Marcelosilva10** [frontendbr/forum#1670]
Boa tarde, estou especificamente estudando Typescript para melhorar minhas skills com Angular 8.
Mas veio um seguinte duvida que para alguns pode ser boba mais despertou interesse em saber.

Qual é a diferença entre um função, uma classe e um método nesse universo web, sei que é muito usada nas linguagens como JAVA e .NET?

Desde de já agradeço a todos.

**Comment by waldemirflj** [comment]
@Marcelosilva10 em poucas palavras seria isso.

Classe
Definição de um objeto.

Métodos
O conjunto de funcionalidades de uma classe em sí.

Função
Bem semelhante ao método, porém não necessita ser instanciando.
