### ISSUE TITLE
Erro TS1005 Angular ?

### ISSUE THREAD

**Issue by Al3xFlores** [frontendbr/forum#1672]
Olá! 
Comecei a estudar angular e estou enfrentando o seguinte problema ao salvar o arquivo "app.module.ts"
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { MeuPrimeiroComponent } from './meu-primeiro/meu-primeiro.component';
@NgModule({
  declarations: [
    AppComponent
    MeuPrimeiroComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
`
ao salvar aparece o seguinte erro; ERROR in src/app/app.module.ts:10:5 - error TS1005: ',' expected.

10     MeuPrimeiroComponent
ja coloquei a virgula e não está resolvendo.

**Comment by kadurodrigues** [comment]
Fala @Al3xFlores blz!

Entao, como declarations eh um array de components, esta faltando uma virgula entre AppComponent e o MeuPrimeiroComponent.

**Comment by Al3xFlores** [comment]
@kadurodrigues  vlw, no caso eu já havia colocado a vírgula no MeuPrimeiroComponent e não deu, vou colocar a vírgula também no AppComponent e verificar, assim que chegar em casa kkkkk

**Comment by jass2125** [comment]
Resolveu @Al3xFlores ?

**Comment by Al3xFlores** [comment]
Resolveu sim @jass2125 , vlw.
