### ISSUE TITLE
Requisição não está sendo enviado ao servidor

### ISSUE THREAD

**Issue by guilhermecostalopes** [frontendbr/forum#1673]
Com este import do angular, a requisição não chega no servidor, e com este método:

import { HttpClient, HttpHeaders } from '@angular/common/http';

    login(user: User) {
        let header: HttpHeaders = new HttpHeaders();
        header = header.append('Content-Type', 'application/json');
        return this.http.post(`${USUARIOS_API}/api/auth`, user, {headers: header});
    }

![headers](https://user-images.githubusercontent.com/24395029/72972866-f4433000-3daa-11ea-8b42-49f3d7c58ea0.png)

--------------

Com esta importação e com este método a requisição vai ao servidor:

```
    private headers = new Headers({
        'Content-Type': 'application/json'
    });

    import { Http, Headers, Response } from '@angular/http';

    login(usuario: Usuario): Observable<boolean> {
     this.http.post(this.base, JSON.stringify({login: usuario.login, senha: usuario.senha}), {headers: this.headers});
    }
```

Além de um ser **Http** e outro ser **HttpClient**, porque um chega e outro não ?

**Comment by MarcosEllys** [comment]
Olá @guilhermecostalopes com o HttpClient você pode utilizar o pipe para "tratar" sua resposta quando processada, isso pode ser visto em um exemplo na própria documentação do angular nesse [link da documentação](https://angular.io/api/common/http/HttpClient#jsonp-example) o seguinte exemplo

```typescript
// PATCH one of the heroes' name
patchHero (id: number, heroName: string): Observable<{}> {
const url = `${this.heroesUrl}/${id}`;   // PATCH api/heroes/42
 return this.httpClient.patch(url, {name: heroName}, httpOptions)
   .pipe(catchError(this.handleError('patchHero')));
}
```

Dentro do **pipe** a gente utiliza operadores rxjs para tratar a requisição, no exemplo acima só foi utilizado o operador **catchError**

PS: você importa os operadores no começo do arquivo com a seguinte linha

```typescript
import { catchError } from 'rxjs/operators';
```

**Comment by guilhermecostalopes** [comment]
@MarcosEllys , fiz assim:

```
import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { User } from '../model/user.model';
import { headerJson, USUARIOS_API_LOGIN } from './usuarios.api';
import { catchError } from 'rxjs/operators';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class UserService {
  handleError: any;

  constructor(private http: HttpClient) {}

  login(user: User): Observable<{}> {
    const url = `${USUARIOS_API_LOGIN}`;
    return this.http.post(url, user, {headers: headerJson})
      .pipe(
        catchError(
          this.handleError('patchHero')
        )
      );
  }
}
```
Deu outros erros, no console do navegador.

> LoginComponent.html:1 ERROR TypeError: this.handleError is not a function
>     at UserService.push../src/app/services/user.service.ts.UserService.login (user.service.ts:21)
>     at LoginComponent.push../src/app/components/security/login/login.component.ts.LoginComponent.login (login.component.ts:30)
>     at Object.eval [as handleEvent] (LoginComponent.html:1)
>     at handleEvent (core.js:23107)
>     at callWithDebugContext (core.js:24177)
>     at Object.debugHandleEvent [as handleEvent] (core.js:23904)
>     at dispatchEvent (core.js:20556)
>     at core.js:22046
>     at SafeSubscriber.schedulerFn [as _next] (core.js:13527)
>     at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:196)

**Outro erro**:

 

>  | View_LoginComponent_0 | @ | LoginComponent.html:1
> -- | -- | -- | --
>   | proxyClass | @ | compiler.js:18239
>   | push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError | @ | core.js:24139
>   | push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError | @ | core.js:15777
>   | dispatchEvent | @ | core.js:20560
>   | (anonymous) | @ | core.js:22046
>   | schedulerFn | @ | core.js:13527
>   | push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub | @ | Subscriber.js:196
>   | push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next | @ | Subscriber.js:134
>   | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next | @ | Subscriber.js:77
>   | push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next | @ | Subscriber.js:54
>   | push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next | @ | Subject.js:47
>   | push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit | @ | core.js:13499
>   | push../node_modules/@angular/forms/fesm5/forms.js.NgForm.onSubmit | @ | forms.js:4433
>   | eval | @ | LoginComponent.html:1
>   | handleEvent | @ | core.js:23107
>   | callWithDebugContext | @ | core.js:24177
>   | debugHandleEvent | @ | core.js:23904
>   | dispatchEvent | @ | core.js:20556
>   | (anonymous) | @ | core.js:21003
>   | (anonymous) | @ | platform-browser.js:993
>   | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask | @ | zone.js:423
>   | onInvokeTask | @ | core.js:17290
>   | push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask | @ | zone.js:422
>   | push../node_modules/zone.js/dist/zone.js.Zone.runTask | @ | zone.js:195
>   | push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask | @ | zone.js:498
>   | invokeTask | @ | zone.js:1744
>   | globalZoneAwareCallback | @ | zone.js:1770


Conseguiu ajudar ?

**Comment by guilhermecostalopes** [comment]
Alguma sugestão ?

**Comment by jass2125** [comment]
Quando você usa o HttpClient, o método que chama esse login deve fazer o subscribe, você tá fazendo isso?

**Comment by guilhermecostalopes** [comment]
Método do componente que chama o service.

  ```
login() {
    this.mensagem = '';
    this.uerService.login(this.formulario.value).subscribe((userAuthentication: CurrrentUser) => {
      this.shared.token = userAuthentication.token;
      this.shared.user = new User('', userAuthentication.login, '', userAuthentication.nome, userAuthentication.autorizacoes);
      this.router.navigate(['/']);
    }, (err: any) => {
      this.shared.token = null;
      this.shared.user = null;
      this.mensagem = 'Erro';
    });
  }
```

**Comment by jass2125** [comment]
Você implementou o método handleError()? No log que mostrou diz q não é uma função.

**Comment by guilhermecostalopes** [comment]
Na verdade depois que eu vi que percebi.

Não consegui implementar. Pode me ajudar ?

**Comment by jass2125** [comment]
Na documentação tem um exemplo, se liga nesse [link](https://stackblitz.com/angular/perlgrobkgb?file=src%2Fapp%2Fheroes%2Fheroes.service.ts)

**Comment by guilhermecostalopes** [comment]
Implementei o exemplo que vc passou.

Ficando assim:

```
import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { User } from '../model/user.model';
import { USUARIOS_API_LOGIN } from './usuarios.api';
import { Observable, throwError } from 'rxjs';
import { catchError } from 'rxjs/operators';
import { HttpErrorHandler, HandleError } from '../http-error-handler.service';

const httpOptions = {
  headers: new HttpHeaders({
    'Content-Type':  'application/json',
    // tslint:disable-next-line:object-literal-key-quotes
    'Authorization': 'my-auth-token'
  })
};

@Injectable({
  providedIn: 'root'
})
export class UserService {

  private handleError: HandleError;

  constructor(
    private http: HttpClient,
    private httpErrorHandler: HttpErrorHandler) {
      this.handleError = httpErrorHandler.createHandleError('UserService');
    }

  login(user: User): Observable<{}> {
    return this.http.post<User>(`${USUARIOS_API_LOGIN}`, user, httpOptions)
      .pipe(
        catchError(this.handleError('user', user))
      );
  }
}
```
Ao entrar na página de login, eu coloquei breakpoint e fui no console do navegador e e digitei **httpOptions** e apertei enter. Pelo que entendi ele não colocou as informações no Header:
'Content-Type':  'application/json', e 'Authorization': 'my-auth-token'. Olhe a imagem.

![httpOptions](https://user-images.githubusercontent.com/24395029/73124761-e85b9780-3f7d-11ea-82b7-d417068a7b67.png)

O problema não pode ser este ?

**Comment by jass2125** [comment]
Você tentou testar inicializar a variavel httpOption dentro do próprío método de login()? Só pra testar se é isso mesmo

**Comment by guilhermecostalopes** [comment]
@jass2125 do mesmo jeito

**Comment by ninetails** [comment]
Posso estar falando besteira pois não uso **angular** mas só por curiosidade, a sua API está no mesmo servidor onde seu client está sendo servido?

Busquei por cima, ressaltando: posso estar enganado, mas o **http** não é uma abstração em cima do **XMLHttpRequest** e o **httpClient** em cima do **fetch** e por isso não poderia ser algo relacionado a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)?

Não quero confundir mas muitas vezes fazia chamada que funcionava localmente e não em produção pq quando é problema de CORS, a requisição não chega a gerar erro porém também não chega a dar _hit_ além do **OPTIONS**.

**Comment by guilhermecostalopes** [comment]
Meu backend é em JAVA

O CORS está assim: 

```
import lombok.extern.apachecommons.CommonsLog;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import javax.servlet.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

import static org.springframework.core.Ordered.HIGHEST_PRECEDENCE;

@Component
@Order(HIGHEST_PRECEDENCE)
@CommonsLog
public class SmpleCORSFilter implements Filter {

    @Override
    public void init(FilterConfig filterConfig) throws ServletException {
        log.info("Sistema de usuários | SmpleCORSFilter início");
    }

    @Override
    public void doFilter(ServletRequest req,
                         ServletResponse resp,
                         FilterChain chain) throws IOException, ServletException {
        HttpServletRequest request = (HttpServletRequest) req;
        HttpServletResponse response = (HttpServletResponse) resp;
        response.setHeader("Access-Control-Allow-Origin", "*");
        response.setHeader("Access-Control-Allow-Methods", "POST, GET, OPTIONS, DELETE, PUT");
        response.setHeader("Access-Control-Max-Age", "3600");
        response.setHeader("Access-Control-Allow-Headers", "x-requested-with, authorization, Content-Type, Authorization");
        if ("OPTIONS".equalsIgnoreCase(request.getMethod())) {
            response.setStatus(HttpServletResponse.SC_OK);
        } else {
            chain.doFilter(req, resp);
        }
    }

    @Override
    public void destroy() {
    }
}
```
Tudo por enquanto está sendo testado localmente.

Quando testo pelo **http** o sistema chega ir no **CORS** com o **httpClient** não.

Pelo que entendi, você está dizendo que está faltando algo no código do back ?

**Comment by guilhermecostalopes** [comment]
@ninetails pode ser um pouco mais especifico, pois não entendi o que vc quis dizer.

**Comment by guilhermecostalopes** [comment]
Resolvido.

O problema que a variável de que chama o servidor estava assim: **localhost:8090** devendo ficar assim **http://localhost:8090**.

Agora esta chamando o **backend**.

**Comment by guilhermecostalopes** [comment]
Obrigado a todos
