### ISSUE TITLE
Não consigo redimensionar o Background Color

### ISSUE THREAD

**Issue by DevMarcos71** [frontendbr/forum#1679]
Olá, estou começando no front-end e tô tendo dificuldade para criar um box com texto dentro, esse é meu código: https://codepen.io/devmarcos71/pen/VwYOyjV 
Agora está assim: 
![before](https://user-images.githubusercontent.com/58784661/73371454-7b554400-4294-11ea-86af-a8dca6c533d2.JPG)

Quero deixar a caixa como a dessa foto:
![after](https://user-images.githubusercontent.com/58784661/73371257-30d3c780-4294-11ea-92b9-616dc27a680c.JPG)

Quem puder me ajudar, desde já agradeço.

**Comment by carlosviniciusananias** [comment]
@DevMarcos71 Você precisa ter uma div como relative e dentro dela o o texto, aí nele aplicar um absolute e fazer os posicionamentos conforme sua necessidade.

Seria mais ou menos desta forma: https://codepen.io/carlosviniciusananias/pen/xxbNWYq

**Comment by salatielq** [comment]
`background-size: 100%`

**Comment by borghettinho** [comment]
Acho que pra complementar, vale umas informações sobre o `position`:

- `position: static` como o nome diz, é um elemento estático na tela acompanhando o fluxo do teu documento. Por causa disso não podemos definir nada relacionado à posição dele, como `top, left, right, bottom` ou `z-index`. Dizemos que esse é um elemento não posicionado. Esse é o padrão de todos os elementos.

- `position: relative` a primeira vista se comporta como `static`, ele respeita o fluxo dos elementos, ou seja, não sobrepõe os vizinhos, mas aceita as propriedades `top, right, bottom, left e z-index`. Um elemento com `position: relative` é um elemento "posicionado".

- `position: absolute` como o nome diz tem posição **absoluta** que depende do seu **container**. A principal diferença das anteriores é que ela ignora o fluxo do documento, ou seja, se sobrepõe a outros elementos. Uma coisa que confunde no começo é entender quem é o **container**, o que na verdade é bem simples: o `absolute` respeita o primeiro elemento pai que estiver posicionado, ou seja, possui `position: relative, absolute ou fixed`. Este elemento também é dito "posicionado".

Por exemplo:

```
	<section style="position: relative;">
		<div style="position: static;"> // isso é o padrão
			<h1 style="position: absolute;">Quem será meu container?</h1>
		</div>
	</section>
```

Nesse caso o container do `h1` é a `section`, mesmo estando um nível acima, pois é o primeiro elemento pai a estar posicionado, sendo que o mesmo valeria se no lugar de `relative` tivéssemos `absolute` ou `fixed`

Outro exemplo:

```
	<section style="position: relative;">
		<div style="position: relative;">
			<h1 style="position: absolute;">Quem será meu container?</h1>
		</div>
	</section>
```

Nesse outro caso o `h1` vai estar posicionado de acordo com a div, pois ela é o primeiro elemento posicionado logo acima dele. Se ele ir subindo e não achar nenhum, ele se posiciona de acordo com o `documento`.

Por último:

- `position: fixed` lembra o `absolute`, o elemento **ignora o fluxo dos elementos** porém suas propriedades `top, right, bottom, left` são relativos sempre ao **documento**

**Comment by cassiodourado1** [comment]
@DevMarcos71 tudo bem? ví o seu codepen e seu código está um pouco confuso.  sugiro que dê uma estudada no flex-box do css, vai te ajudar bastante no que está precisando.
Você não vai precisar ficar usando posição absoluta pra controlar o posicionamento dos elementos na tela 
eu editei algumas coisas em seu código e comentei alguns pontos que pensei ser relevantes, veja aqui: 
https://codepen.io/cassiodourado/pen/yLymOrq

qualquer dúvida pode perguntar que o que eu poder ajudar, ajudarei. abraço!

**Comment by DevMarcos71** [comment]
Resolvido! Obrigado pessoal!
