### ISSUE TITLE
Qual a melhor opção para uma "tradução" async no Angular?

### ISSUE THREAD

**Issue by vmagalhaes** [frontendbr/forum#1685]
Estou com uma dúvida,
No meu código eu estou fazendo uma transformação de um valor para um "traduzido"
Tipo: {request.name} -> 'Hello Word'

Existe toda uma lógica da tradução desses dados, e o que eu fico pensando é:
Eu uso deste jeito (exemplo):
_example.html_
`{{ transformKey(key) }}`

_example.component_
```
transformKey(key) {
   // toda a logica
   return translation;
}
```

Ai eu tenho três dúvidas, a primeira seria se sendo assincrono esse metódo fica executando sem parar loucamente? Que se você colocar um console.log, ele fica ali mostrando loucamente.

A segunda pergunta seria: Um pipe tem uma melhor performance para uma solução desta?

E a terceira seria: Existe uma solução mais performática para isso? Ou um jeito melhor para a execução disso?

Todas as dicas serão bem-vindas.

Desde já agradeço,
Victor Magalhães.

**Comment by maicongodinho1** [comment]
Aconselho você utilizar o i18n do próprio angular. É bem simples de utilizar e configurar.

Segue a documentação: https://angular.io/guide/i18n

**Comment by portothree** [comment]
Também penso que o i18n seja a melhor opção, no projeto atual se iniciou a criar um pipe de tradução que mapeia as strings correspondentes de uma língua para outra e é difícil de se manter com o crescimento da app.

**Comment by vmagalhaes** [comment]
Valeu pelas respostas galera, faz um tempinho essa pergunta, desde então eu uso realmente o i18n do Angular mesmo.
