### ISSUE TITLE
VS Code vs Webstorm

### ISSUE THREAD

**Issue by renangasperi** [frontendbr/forum#1687]
Eu sou um usuário do VS Code desde quando comecei a programar e, ultimamente, tenho visto algumas pessoas utilizando o Webstorm(JetBrains) e gostando bastante. Já vi alguns posts de blogs sobre o assunto e vou deixar embaixo para quem tiver interesse.
Mas o que vocês acham? Já tentaram ou tem interesse em migrar pro Webstorm?

Links que encontrei:
https://dev.to/mokkapps/why-i-switched-from-visual-studio-code-to-jetbrains-webstorm-939
https://www.slant.co/versus/5980/5982/~webstorm_vs_visual-studio-code

**Comment by fabianoschaefer** [comment]
Acredito que sejam ferramentas distintas. O VS Code é um editor de texto, e o Webstorm uma IDE.
 
Em termos de recursos computacionais o VS Code tende a consumir menos (para mim que uso um microondas com linux faz diferença). Mas se para você isso não for um problema acredito que vale o teste.

Outro ponto é o fato do VS Code ser open source (mas não são todos que levam isso em conta e tudo bem).

**Comment by italosilva01** [comment]
Olha. Eu acredito que o vscode sai ganhando. Tudo bem que vscode é só um editor de texto e Webstorm é uma IDE, porém o VS code tem a proposta de evoluir junto com o programador. O VS code faz isso por meio de plugins. Assim, uma hora ou outra o VS Code irá fazer a mesma coisa que uma IDE robusta faz, se tornando uma IDE customizada.

**Comment by AlexandroWillianHervis** [comment]
Concordo com o @italosilva01, vscode pode evoluir com você, ou seja, você só vai instalar aquilo que realmente vai usar, não que o webstorm seja ruim, mas pode ser uma ferramenta com muita coisa que você pode nunca usar.

**Comment by wilsonneto-dev** [comment]
Eu já usei por pouco tempo, mas gostei muito do VS Code, a customização, consigo usar para todas as linguagens que trabalho e tal... Minha preferência é VS Code frente a qualquer editor de textos e IDEs...

**Comment by eliseumds** [comment]
O VSCode não é um simples editor de texto. Tem integração com Git (plugin GitLens), debugging, refactoring, formatting (Prettier), terminal e code analysis pode ser feita com ESLint e outros plugins. Eu já usei os dois e voltei pro VSCode.

WebStorm vem com muito mais ferramentas instaladas por padrão mas você paga o preço em lentidão.

**Comment by mustafahamandosh** [comment]
sem duivida Webstorm é melhor.

**Comment by wilsonneto-dev** [comment]
sem dúvidas webstorm é maias lento

**Comment by vitebo** [comment]
atualmente eu to utilizando o webstorm, mas antes eu utilizada o vscode, então vou deixar aqui os pontos que eu gostei e não gostei de cada um, pode ser que acabe ajudando.

Antes de utilizar o vscode eu utilizava o neovim, e tanto no vscode quanto no webstorm eu tenho um plugin pro vim, o que eu gosto bastante. Ambos os plugins são muito bons, mas eu consigo customizar muito mais o plugin do vscode. Um exemplo é quando eu to navegando no diretório de pastas do meu projeto, no vscode eu consegui remapear para me movimentar no diretório através das teclas `h-j-k-l`. No webstorm ainda não consegui fazer isso. _(caso alguém saiba uma maneira de fazer isso eu ficaria feliz)_.

Atualmente eu trabalho em um projeto que é um monólito de [elixir](https://elixir-lang.org/) com [vue](https://vuejs.org/).
Em ambos os casos eu precisei adicionar um plugin para ter o highlight da syntaxe. No webstorm foi meio chato de fazer isso, porque eu sou obrigado a adicionar o path do sdk do elixir, se não fica uma msg de erro no editor que não pra tirar. O único problema disso é porque eu rodo a aplicação inteira dentro de um container docker, então eu não precisaria ter o elixir instalado na minha maquina, mas precisei instalar só por causa do webstrom. Com o vscode eu não tive esse problema, foi muito mais simples, contudo pelo fato do webstorm ter acesso ao sdk do elixir, as sugestões do plugin são muito mais completas.

Eu senti o suporte para o vue no webstorm muito melhor do que no vscode _(eu usava o plugin do [Vetur](https://github.com/vuejs/vetur))_. No webstorm eu consigo ter autocomplete dos componentes no template, e ele ja me diz quais são as props que aquele componente aceita. Eu consigo extrair um pedaço de um componente para um novo componente apenas com uma ação. No vscode apesar deu ter um suporte bom, eu não tenho essas funcionalidades mais avançadas.

Para debugar eu gosto mais do webstorm, tanto os testes da aplicação quanto a aplicação rodando no browser tbm. Eu achei muito mais simples de fazer as coisas. No vscode tbm tem plugin pra isso mas eles nunca funcionaram muito bem cmg.

Por ultimo uma função que eu gosto muito do webstorm, é que ele consegue gerar um [diagrama mostrando todas a dependências do seu modulo](https://www.jetbrains.com/help/webstorm/module-dependency-diagram.html#js_ts_module_dependency_diagram_analyze).
Isso é muito legal para documentar, ou colocar em um PR para exemplificar melhor oque foi feito. Eu ainda não consegui encontrar nenhuma ferramenta externa que consiga fazer isso. 

Em um resumo geral, eu acho o webstorm mais completo e menos flexível, e o vscode mais flexível e customizável. Hoje eu to no webstorm porque eu to testando bastante coisa e eu tenho a licença de estudante que me garante acesso a todos os produtos da jetbrains free, mas para desenvolvimento web frontend eu não sei se eu pagaria o valor cheio nessa ferramente, sendo que eu tenho o vscode que é tão bom quanto, e é free.

Só lembrando que eu não sou nenhum tipo de expert em nenhuma dessas ferramentas, pelo contrário, eu sou só um charlinho que gosta muito de fuçar :laughing:

**Comment by mustafahamandosh** [comment]
@wilsonneto-dev haha concordo com ti não ha o melhor.
Eu já utilizei os dois, mas o webstorm é mais inteligente.
Eu defendo o webstorm versão pago e não o gratuito.
O gratuito um é ruim de mais, mas o pago é perfeito.
Eu uso a minha conta de estudante e o jetbrains me da acesso de dois anos gratuitamente.
