### ISSUE TITLE
Testes no Jest - Como eu mocko window.PerformanceObserver fora do escopo do teste?

### ISSUE THREAD

**Issue by igorthurow** [frontendbr/forum#1693]
Oi amigos! Boa tarde!

Estou tentando testar uma função que fica em outro arquivo em relação ao meu teste, e que tem uma validação no início, tipo este exemplo:

```
const a = window.PerformanceObserver
	? (a, b, c) => {
		//logica com window.PerformanceObserver

		return () => observer.disconnect()
	}
	: () => () => undefined
```

O problema é que na versão do Jest que estou usando, o `window.PerformanceObserver` não existe, e portanto este ternário cai sempre no `else`. 

Eu preciso controlar quando a implementação no `window.PerformanceObserver` no arquivo da função existe/não existe, para que consiga cair no primeiro caso do ternário ou no segundo de forma controlada.

Tentei controlar o `window` no arquivo de testes, mas não refletiu no escopo do arquivo da função.

Alguém que manje mais, me ajuda?

**Comment by simaodeveloper** [comment]
Estou no trem agora então não consigo ajudar muito, mas da uma olhada nesse teste aqui e veja se ajuda https://github.com/Zizzamia/perfume.js/blob/master/__tests__/perfume.spec.ts

**Comment by ninetails** [comment]
Tem o `jest.spyOn` porém como acho que não é algo implementado no `jsdom`, creio que talvez seja necessário atribuir o `PerformanceObserver` no `global`, _mockando_ antes e removendo depois do teste:

```js
describe('existe PerformanceObserver', () => {
  beforeEach(() => global.PerformanceObserver = jest.fn())
  afterEach(() => delete global.PerformanceObserver)

  // testes do else
})
```

**Comment by igorthurow** [comment]
Obrigado amigos! Resolvido!

Aos interessados, explicação:

Da forma que estava o código, eu não consegui testar como esperado.

O problema é que a validação era feita na atribuição da função, e ao importá-la, essa validação já havia sido resolvida no contexto em que ela estava.

Acabei por remover esta validação na atribuição da função.
Fiz um `if guard` na primeira linha da função, assim garantindo que só vai haver essa validação ao chamar esse cara. 
Agora no arquivo do teste eu seto o membro que falta no `window` e chamo a função depois.

Antes: 
```
export const a = window.PerformanceObserver
	? (a, b, c) => {
		//logica com window.PerformanceObserver

		return () => observer.disconnect()
	}
	: () => () => undefined
```
Depois:

```
export const a = (a, b, c) => {
		if (!(PerformanceObserver in window) {
				return () => undefined
			}

			//logica com window.PerformanceObserver

			return () => observer.disconnect()
		}
```
