### ISSUE TITLE
Grupo JavaScriptBrasil

### ISSUE THREAD

**Issue by DevSouza** [frontendbr/forum#1698]
# Relato comunidade JavaScriptBrasil

![Screenshot_20200216-133153](https://user-images.githubusercontent.com/24610869/74611245-c6ff4e80-50d8-11ea-9755-dca5f708d439.png)

#### Mais um caso de admin abuse 

Eu realmente não entendo qual é o tesão do ser humano em colocar fatores políticos em qualquer assunto... Mas,
Qual é a dificuldade de manter o grupo sem a intervenção de política???

Após o posto de um dos administradores do grupo JavaScriptBrasil eu fiz a seguinte publicação:

"Achei que o grupo era de JavaScript, não sobre política"

Fui chingando e banido kkkkk... O jeito é ir para comunidade gringa.

**Comment by reginaldoholyfield** [comment]
Vou apenas deixar esse link no tópico: https://github.com/frontendbr/forum/issues/634

**Comment by felquis** [comment]
Lock this issue comments @felipefialho 

![](https://media1.giphy.com/media/XpGuc2E2lEBeU/giphy.gif?cid=6104955e3576fa9d0aca1617c97e94a531920add9f2cb65c&rid=giphy.gif)

**Comment by DevSouza** [comment]
> Vale a pena a busca no grupo https://www.facebook.com/groups/javascriptbrasil/search/?query=bolsonaro&epa=SEARCH_BOX e uma analíse critica dos resultados.
> 
> Lock this issue comments @felipefialho
> 
> ![](https://camo.githubusercontent.com/506b6aa141c018cf306494034aed13b3a169f9d6/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f58704775633245326c454265552f67697068792e6769663f6369643d363130343935356533353736666139643061636131363137633937653934613533313932306164643966326362363563267269643d67697068792e676966)

O problema é esse, qual é o sentido de abrir um grupo sobre JavaScript e ficar fazendo discussões sobre Politica.

Eu não sou e não quero ser ligado a politica, se eu quisesse ouvir/ler sobre politica eu entrava em grupos com esse foco.

**Comment by felipefialho** [comment]
Esse grupo não tem qualquer associação com grupos do Facebook ou outras comunidades. Portanto issue fechada.
