### ISSUE TITLE
NPM exibindo mensagem de warn 'deprecated graceful-fs@3.0.8' ;(

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/forum#170]
Quando instalo as depências pro Gulp, tá rolando mensagem de warn 'deprecated graceful-fs@3.0.8'.

`npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please
o graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please
o graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please
o graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!`

Fiz algumas pesquisas, mas ainda não consegui entender o por que e como remover essas mensagens e principalmente se elas interferem no funcionamento das tasks.

Acontece o mesmo aí com vcs?

**Comment by fdaciuk** [comment]
O Gulp usa essa dependência, por isso aparece essa mensagem: https://github.com/gulpjs/gulp/blob/master/package.json#L47

=)

**Comment by fdaciuk** [comment]
Só pra deixar registrado: já tentaram enviar PR. Aqui tem mais informações sobre: https://github.com/gulpjs/gulp/pull/1555

**Comment by theandersonn** [comment]
@fdaciuk valeu! Vi agora esse tópico:
https://github.com/gulpjs/gulp/issues/1485
