### ISSUE TITLE
Front end ou Data Science?

### ISSUE THREAD

**Issue by tiagocruz85** [frontendbr/forum#1701]
Senhores(as),
Estou em busca de ingressar no mercado de tecnologia e estou em dúvida em 2 áreas.
A área de Web Dev e Data Science...
Venho pesquisando sobre o futuro de ambas e gostaria de explicações e algumas dicas assim como onde poderia estudar...
Sou formado em engenharia civil e Logística e busco voltar para o mercado rápido...
Sei que terei de dedicar me aos estudos e isso demanda tempo, mas o quanto antes conseguir uma recolocação, melhor...
Agradeço

**Comment by fabianoschaefer** [comment]
Como seu objetivo é entrar rapidamente no mercado provavelmente a área de desenvolvimento web ofereça mais oportunidades (levando em consideração que você não possui conhecimento prévio).

Se possuir capital para investir recomendo fortemente o bootcamp da Rocketseat, você vai economizar tempo. Eles possuem dois bootcamps, o LaunchBase que é voltado para iniciantes na área da programação (provavelmente é o seu caso) e o GoStack que é mais avançado e no momento não possui vagas abertas.

Essa semana está rolando a [MaratonaDev](https://rocketseat.com.br/maratonadev/aulas/3.0?aula=1) e abriram inscrições para o LaunchBase. O conteúdo ficará disponível até 23:59h de quinta feira e você terá tempo suficiente de fazer as duas aulas e entender se vale a pena investir no bootcamp ou não. Na terceira aula tem o detalhe de como irá funcionar o bootcamp e o valor.

Se não possuir capital para investir você pode optar pela [freeCodeCamp](https://www.freecodecamp.org/) que é sucesso também (e 0800 :smiley:). Eles possuem um canal no YouTube também vale a pena dar uma olhada.

Falando em YouTube existe uma série de canais que vale a pena acompanhar. Alguns dos quais sou inscrito são:
- Rocketseat (os mesmos caras do bootcamp);
- Filipe Deschamps;
- Code Drip (em Inglês);
- Lucas Montano;
- Fábio Akita (o nível do conteúdo dele é fora de série).

Para Data Science acredito que o [kaggle](https://www.kaggle.com/) seja a porta de entrada.

**Comment by tiagocruz85** [comment]
> Como seu objetivo é entrar rapidamente no mercado provavelmente a área de desenvolvimento web ofereça mais oportunidades (levando em consideração que você não possui conhecimento prévio).
> 
> Se possuir capital para investir recomendo fortemente o bootcamp da Rocketseat, você vai economizar tempo. Eles possuem dois bootcamps, o LaunchBase que é voltado para iniciantes na área da programação (provavelmente é o seu caso) e o GoStack que é mais avançado e no momento não possui vagas abertas.
> 
> Essa semana está rolando a [MaratonaDev](https://rocketseat.com.br/maratonadev/aulas/3.0?aula=1) e abriram inscrições para o LaunchBase. O conteúdo ficará disponível até 23:59h de quinta feira e você terá tempo suficiente de fazer as duas aulas e entender se vale a pena investir no bootcamp ou não. Na terceira aula tem o detalhe de como irá funcionar o bootcamp e o valor.
> 
> Se não possuir capital para investir você pode optar pela [freeCodeCamp](https://www.freecodecamp.org/) que é sucesso também (e 0800 ). Eles possuem um canal no YouTube que vale a pena dar uma olhada.
> 
> Falando em YouTube existe uma série de canais que vale a pena acompanhar. Alguns dos quais sou inscrito:
> 
> * Rocketseat (os mesmos caras do bootcamp);
> * Filipe Deschamps;
> * Code Drip (em Inglês);
> * Lucas Montano;
> * Fábio Akita (o nível do conteúdo que ele produz é fora de série).
> 
> Para Data Science acredito que o [kaggle](https://www.kaggle.com/) seja a porta de entrada.

Muito obrigado pelas dicas, Fabiano...
Vou dar uma olhada no curso que vc indicou....
