### ISSUE TITLE
Desenvolvedor front-end: Começar com web design ou HTML+CSS+JavaScript?

### ISSUE THREAD

**Issue by vilsonsampaio** [frontendbr/forum#1703]
Fala, pessoal!

Estou cursando o último ano de um curso técnico em Informática num IF da minha cidade, e nele tive matérias de lógica de programação, banco de dados (MySQL - professor tinha uma didática péssima) e linguagem de programação (Java). Como me destaquei e curti muito a área, comecei a considerar bastante a área da programação, e, a longo prazo, pretendo me tornar um desenvolvedor full-stack e, quem sabe, mobile.

Vi alguns vídeos no YouTube que me recomendaram iniciar pelo front-end, pelo fato de todo serviço/negócio precisar mais de um site do que de um sistema. De início, penso em pegar projeto de desenvolvimento de sites simples, sem integração com um banco de dados (sites institucionais simples, apresentações de cursos, etc.), fornecendo do design do site à codificação a fim de conseguir mais clientes. Comecei a estudar um pouco da tríade HTML+CSS+JavaScript e tenho algumas noções de PhotoShop, mas estou com dúvida se é melhor eu começar com a parte do design ou codificação. O que vocês indicariam? 

Estou à procura de cursos acessíveis e com um bom conteúdo também, se tiverem alguma indicação, eu iria adorar saber.

Abraços!

**Comment by ojvribeiro** [comment]
Eu, particularmente, iniciei já mexendo (de forma bem simplista) com código, mas acredito que vá muito de gosto pessoal seu.

Por exemplo, a primeiríssima coisa que fiz na minha vida de desenvolvedor (isso quando ainda estava dando meus primeiros passos) foi tentar recriar a tela de login do Facebook. Não entendia absolutamente nada de conceitos de design para a web e, naquela época (10 anos atrás), quase nem se falava de responsividade, então tinha "menos" coisa pra me preocupar em aprender.

Hoje em dia tudo está mais bem definido, com a chegada do CSS3 (a flexbox junta dele), guidelines como a do [Material Desgin](https://material.io/). Enfim, eu sempre fui apaixonado por desenvolvimento web, mas também tenho uma quedinha por web design e, ultimamente, tenho dado bastante atenção a esse último.

Se decidir começar com a codificação, foque no HTML+CSS+JavaScript (nessa ordem, apenas pule pro JS quando tiver uma base de HTML e CSS). Recomendo muito o canal [Curso em Vídeo](https://www.youtube.com/channel/UCrWvhVmt0Qac3HgsjQK62FQ), do Gustavo Guanabara. Aqui em baixo eu vou listar alguns dos cursos que podem ser bons pra você:
* [HTML+CSS+JS](https://www.youtube.com/watch?v=epDCjksKMok&list=PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o): esse curso é de 2013, mas vai te dar uma base bem sólida dos recursos mais importantes dessas linguagens que valem até hoje;
* [JavaScript e ECMAScript para Iniciantes](https://www.youtube.com/watch?v=BXqUH86F-kA&list=PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1&t=0s): esse curso é mais recente e vai te levar pro próximo nível do JavaScript, com recursos mais atuais, mas também abordando o mais básico. Mas eu recomendo iniciar com o primeiro item dessa lista.

Já se quiser começar pela parte do design, recomendo deixar o Photoshop um pouco de lado e conhecer o [Adobe XD](https://www.adobe.com/br/products/xd.html), um programa gratuito que possui ferramentas próprias pra web design.

Não conheço cursos de web design pra poder te indicar, mas deve ter aos montes no YouTube. Importante procurar sempre por **cursos** e não apenas tutoriais.

Se você tiver um domínio razoável do inglês, recomendo dar uma olhada nas [guidelines do Material Design do Google](https://material.io/design/introduction/) voltado pra web design. Isso vai te ajudar a dar atenção na parte de UX (experiência do usuário).

Não é obrigatório, mas é bem recomendável você saber como o HTML+CSS funcionam antes de começar no design, pois você vai pelo menos saber o que não fazer.

Espero ter ajudado de alguma forma.

**Comment by vilsoneto** [comment]
> Eu, particularmente, iniciei já mexendo (de forma bem simplista) com código, mas acredito que vá muito de gosto pessoal seu.
> 
> Por exemplo, a primeiríssima coisa que fiz na minha vida de desenvolvedor (isso quando ainda estava dando meus primeiros passos) foi tentar recriar a tela de login do Facebook. Não entendia absolutamente nada de conceitos de design para a web e, naquela época (10 anos atrás), quase nem se falava de responsividade, então tinha "menos" coisa pra me preocupar em aprender.
> 
> Hoje em dia tudo está mais bem definido, com a chegada do CSS3 (a flexbox junta dele), guidelines como a do [Material Desgin](https://material.io/). Enfim, eu sempre fui apaixonado por desenvolvimento web, mas também tenho uma quedinha por web design e, ultimamente, tenho dado bastante atenção a esse último.
> 
> Se decidir começar com a codificação, foque no HTML+CSS+JavaScript (nessa ordem, apenas pule pro JS quando tiver uma base de HTML e CSS). Recomendo muito o canal [Curso em Vídeo](https://www.youtube.com/channel/UCrWvhVmt0Qac3HgsjQK62FQ), do Gustavo Guanabara. Aqui em baixo eu vou listar alguns dos cursos que podem ser bons pra você:
> 
> * [HTML+CSS+JS](https://www.youtube.com/watch?v=epDCjksKMok&list=PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o): esse curso é de 2013, mas vai te dar uma base bem sólida dos recursos mais importantes dessas linguagens que valem até hoje;
> * [JavaScript e ECMAScript para Iniciantes](https://www.youtube.com/watch?v=BXqUH86F-kA&list=PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1&t=0s): esse curso é mais recente e vai te levar pro próximo nível do JavaScript, com recursos mais atuais, mas também abordando o mais básico. Mas eu recomendo iniciar com o primeiro item dessa lista.
> 
> Já se quiser começar pela parte do design, recomendo deixar o Photoshop um pouco de lado e conhecer o [Adobe XD](https://www.adobe.com/br/products/xd.html), um programa gratuito que possui ferramentas próprias pra web design.
> 
> Não conheço cursos de web design pra poder te indicar, mas deve ter aos montes no YouTube. Importante procurar sempre por **cursos** e não apenas tutoriais.
> 
> Se você tiver um domínio razoável do inglês, recomendo dar uma olhada nas [guidelines do Material Design do Google](https://material.io/design/introduction/) voltado pra web design. Isso vai te ajudar a dar atenção na parte de UX (experiência do usuário).
> 
> Não é obrigatório, mas é bem recomendável você saber como o HTML+CSS funcionam antes de começar no design, pois você vai pelo menos saber o que não fazer.
> 
> Espero ter ajudado de alguma forma.

Muito obrigado pelas dicas, Victor! Me ajudou bastante!

Já conheço o trabalho do Gustavo Guanabara e vi algumas aulas do curso dele de JavaScript para Iniciantes. Pensei em fazer o de HTML+CSS+JS primeiro, mas fiquei com medo de ele ser desatualizado, devido a data de lançamento. Mas, vou voltar a primeira opção de curso que você indicou, obrigado!
