### ISSUE TITLE
Tamanho variado de ícones

### ISSUE THREAD

**Issue by LuanDc** [frontendbr/forum#1705]
Boa tarde, Devs. 

Atualmente trabalho lado a lado com a equipe de designs da nova empresa que estou desde Novembro. Em muitas atividades tive que criar pack de ícones no Iconmoon. **Minha dúvida é, como vocês fazem pra escalar os mais diversos tamanhos de ícones dentro do seu código?** geralmente eu crio classes separadas pra setar cores, mas tamanho nunca é padrão, varia muito de componente pra componente.

**Comment by willycamargo** [comment]
Se o design system, por mais simples que for, estiver bem organizado e padronizado, então haverá tamanhos padrão para os ícones, tipografia, botões etc.

Sempre que vou fazer setup de ícones, sento por algum tempo com o designer responsável e explico que precisamos definir alguns padrões de tamanhos para trabalharmos.

**Comment by eliseumds** [comment]
A viewBox tem que ser a mesma sempre, do contrário vai virar uma bagunça. Os tamanhos são controlados via CSS depois. Os nossos seguem o mesmo padrão dos tamanhos das fontes pois usamos o mesmo componente (`<Text>`) por baixo.

**Comment by LuanDc** [comment]
Alguns ícones variam em larguras e alturas, geralmente depende muito do formato e do desenho do próprio ícone. Mas você me deu uma ideia interessante, de criar classes específicas pra cada ícone, tendo tamanho padrão e usar multiplicadores pra setar tamanhos sm, md e lg :)
