### ISSUE TITLE
Desenvolvedor: começar sendo freelancer ou CLT?

### ISSUE THREAD

**Issue by vilsonsampaio** [frontendbr/forum#1707]
Fala, pessoal. Tudo bem?

Pra quem tá começando agora, fazendo cursos online e querendo adquirir experiência, vocês indicam entrar no mercado de trabalho sendo freelancer ou estagiário em uma empresa? 

Penso muito em trabalhar como freelancer ou remoto no futuro, devido a flexibilidade tanto de horários quanto de localidade, que é uma coisa que eu adoraria. Mas, antes, pensei em fazer um estágio em uma empresa, pra ganhar experiência na área e networking. Só que a grande maioria das vagas de CLT exigem uma formação superior na área de Desenvolvimento (coisa que eu não quero fazer por agora).

O que vocês acham? Devo iniciar como freelancer ganhando experiência na marra ou entrar em uma graduação para conseguir um estágio? Fiz meu ensino médio integrado a um Técnico em Informático em um IF da minha cidade, mas não sei se é o suficiente para arranjar um estágio que contrate desenvolvedor sem experiência e graduação na área.

**Comment by LuanDc** [comment]
No seu caso acredito que projetos práticos sejam a única forma de conseguir experiência. Estágio geralmente as empresas dão oportunidades a quem esta cursando algum curso na área da tecnologia. Faz algum projeto prático e joga no teu Github, se você puder ganhar grana com isso (freelancer), melhor ainda.

**Comment by Beam2232** [comment]
Eu já estou com uma pequena experiência, seguindo cursos e etc.
Fui tentar criar projetos e acabei travando. Então, decidi que o melhor a fazer é começar a montar projetos básicos e ir aprofundando. Me inscrevi no sistema de freelancer e vamos ver no que dá.

**_Resumindo_**: Começarei desenvolvendo pequenos projetos, artigos e etc. E ao mesmo tempo, tentando pegar alguns frellas.

Enquanto pego alguns freelas, aprendo fazendo o freela e ainda ganho uma graninha. 

Tem um [vídeo](https://www.youtube.com/watch?v=fYR9L2ZmodM&t=1s), no canal do [Deschamps](https://www.youtube.com/channel/UCU5JicSrEM5A63jkJ2QvGYw). Q_ue mostra 10 projetos para fazer_, peguei uns 7 para me desenvolver melhor. Tenho certeza que pelo menos um tu vai pegar.

> Faça seus próprios projetos, crie portfólio e depois faça freela.
