### ISSUE TITLE
DUVIDA EM DESENVOLVIMENTO DE PROGRAMA

### ISSUE THREAD

**Issue by davihtz** [frontendbr/forum#1715]
Olá, estou iniciando no mundo de programação e eu gostaria de saber como eu faria para resolvr o seguinte situação:

Como inserir 2 arquivos em uma pasta substituindo outros 2 com o mesmo nome. 
Ex: 
(Pasta): arquivo1 , arquivo2
O programa vai inserir e substituir arquivo1 e arquivo2 por arquivos de mesmo nome, arquivo1, arquivo2. Porém, o arquivo em si, não será o mesmo, apenas o nome.

Ou, poderia ser um renomeador de arquivo, que vai meio que dar um SWAP no nome dos dois arquivos, fazendo com que o arquivo1 fique como arquivo2 e o arquivo2 como arquivo1 quando eu desejar. 

Qual linguagem eu poderia utilizar? Alguem me dá um norte.

Algo que no final resulte em uma interface com um botão escrito SWAP NAMES, e os arquivos irão inverter os nomes automaticamente. Espero que tenha conseguido deixar um pouco claro.

Grato.

**Comment by NicholasKuchiniski** [comment]
Se eu entendi, da para fazer isso com qualquer linguagem que rode fora do browser imagino (ou até dentro, se você quiser baixar os arquivos ao invés de substituir direto no sistema de arquivos).

Da para fazer isso de várias formas, usando vários algoritmos diferentes, eu pegaria o conteúdo do arquivo 1 e do arquivo 2 guardaria na memoria, depois salvaria com os nomes atualizados e conteúdos trocados.

**Comment by felipefialho** [comment]
@davihtz Por favor, altere seu titulo de um jeito que fique claro e objetivo.

**Comment by developerfred** [comment]
@felipefialho falou tudo, quando fui ler o titulo minha mente já tratou como um grito.
