### ISSUE TITLE
Implementar multiplas telas de login num projeto Angular

### ISSUE THREAD

**Issue by portothree** [frontendbr/forum#1717]
Estou em um projeto Angular onde temos clientes de diferentes organizações e precisamos de uma tela de login diferente para cada um, com cores e logo diferentes.
Todo o resto do projeto é igual, mas estão em diferentes dominios e servidores.
Descobri que o que fazem é um template de login gigante com as diferentes versões e comentam o que não é usado, fazem build e deploy da versão de cada cliente em cada servidor.

Eu achei bizarro, mas é a primeira vez que estou contribuindo num projeto Angular não tenho conhecimento sobre algo como theme provider.

Como vocês implementariam isso?

**Comment by glauberm** [comment]
Eu tentaria colocar essas informações que mudam (código hexadecimal, endereço das imagens) em variáveis de ambiente, mas acho que assim ainda teria que fazer o build de cada cliente. Talvez mudar essas informações dinamicamente através do domínio, mas parece uma solução propensa a erros...

**Comment by LuanDc** [comment]
@glauberm interessante sua abordagem, mas não teria nenhuma forma de usar as variáveis de ambiente pra setar o component na config do modulo? 

**exemplo**
```
const routes: Routes = [
    { path: 'home', component: <VARIAVÉL> }
];
```

**Comment by portothree** [comment]
> 
> 
> Eu tentaria colocar essas informações que mudam (código hexadecimal, endereço das imagens) em variáveis de ambiente, mas acho que assim ainda teria que fazer o build de cada cliente. Talvez mudar essas informações dinamicamente através do domínio, mas parece uma solução propensa a erros...

Sim, também acredito que a aplicação não deve se basear no dominio pra alterar algo, mas esse é o unico fator diferente em cada um. Eu só queria ter uma união de build

**Comment by maucrvlh** [comment]
Para um problema parecido usei uma solução simples:

- Deixo no meu DB as configs de cada cliente com a chave sendo o subdomain
deste cliente (cliente1.domain.com, cliente2.domain.com) ..
- Na tela de login, requisito do db/cache as configs e aplica-os on the fly
na tela de login que é padrão p todos. No meu caso, o que precisei deixar
dinâmico foram cores de fundo e logo do cliente.

Em qui., 5 de mar. de 2020 às 10:33, Gustavo Porto <notifications@github.com>
escreveu:

**Comment by eduardosoareszup** [comment]
Você pode configurar um build diferente para cada cliente no `angular.json` e determinando um `environment` para cada, com as informações que mudam (Logo, cores e etc):

```
...
fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.cliente-brabo.ts"
                }
...
```
Configurado isso e você tendo uma configuração de CI/CD acredito que resolveria o problema. O único problema é que vai demorar um bom tempo o build/deploy automatizado do seu projeto, porque ele vai realizar um para cada cliente. Mas ai tem que ser feito de todo jeito mesmo kkk.

**Comment by portothree** [comment]
Obrigado pela ajuda a todos. Acabei por ter uma configuration diferente no `angular.json` pra cada build e também env files. Não foi possivel unificar as builds pois cada vez mais cada cliente havia diferentes features.
