### ISSUE TITLE
Problemas com position fixed

### ISSUE THREAD

**Issue by ribeiroevandro** [frontendbr/forum#172]
Pessoal, boa tarde! 
Estou com um problema parece ser relativamente simples e bobo, mas já estou quebrando a cabeça com isso e não acho uma solução, vou tentar descrever e desculpas se por acaso não souber me expressar. 

A questão é a seguinte, tenho dois elementos na página `content` e `sidebar` que preciso fixar eles quando chegar a determinada altura da página. Isso foi relativamente simples e funciona, porém está quebrando o meu layout, segue print que ilustra a situação.

Nessa primeira imagem mostra os elementos `content` e `side` antes de receberem a class que com `position: fixed`
![screenshot 2016-05-26 04 16 08](https://cloud.githubusercontent.com/assets/943553/15614954/ead906cc-2411-11e6-813d-89bdd0c0dad2.png)
Nessa segunda imagem mostra os elementos `content` e `side` após de receberem a class que com `position: fixed`
![screenshot 2016-05-26 04 16 26](https://cloud.githubusercontent.com/assets/943553/15614953/ead6a882-2411-11e6-8ed2-d4a874487354.png)

Após receberem a classe eles perdem o tamanho, estou usando o LostCSS para o grid.

**Comment by evansantos** [comment]
@ribeiroevandro tem algum lugar pra dar uma olhada no código

**Comment by ribeiroevandro** [comment]
Qual parte do código quer ver, porque não tem nada de mais, side e content foram feitas assim
```
.content
    lost-column: 8/12
    min-height: 1000px
    background: #ccc
    lost-utility: clearfix

.sidebar-content
    lost-column: 4/12
    min-height: 1000px
    background: #ccc
    lost-utility: clearfix
```

E que recebe quando atinge uma altura especifica.
```
.fixed
    position: fixed
    top: 60px
```

**Comment by Mendrone** [comment]
@ribeiroevandro Alterei o título, tudo bem?

**Comment by ribeiroevandro** [comment]
@Mendrone perfeito man, já ia te agradecer...

**Comment by LFeh** [comment]
@ribeiroevandro Consegue jogar o código no JSFiddle?

**Comment by nvrossett** [comment]
Ai @ribeiroevandro , pega aee
https://jsfiddle.net/aoed9voe/1/

Só adaptar a lógica (quando fica vermelho é que ele ta fixo)

**Comment by Mendrone** [comment]
@ribeiroevandro a solução do @nvrossett ajudou? Da um toque se resolveu o problema pra podermos marcar como resolvido! :grinning:

**Comment by ribeiroevandro** [comment]
@Mendrone estou fechando aqui, tive que fazer umas adaptações no JS para tirar o jQuery... Depois de muito bater cabeça, agora está funcional... Muito obrigado ao @nvrossett e os demais que tentaram ajudar... Devagar eu chego lá o/
