### ISSUE TITLE
Criação de projeto para ajudar as pessoas a se manterem em casa

### ISSUE THREAD

**Issue by matheus-vieira** [frontendbr/forum#1735]
Olá pessoal, não muito uma discussão porém mais uma ajuda.

Criei o repositório [Solicitação de compra](https://github.com/matheus-vieira/solicitacao-compra)

E preciso de ajuda para finalizar.

Como diz no readme qualquer ajuda é bem vinda.

Obrigado.

Obs: se não for permitido esse tipo de postagem, desde já me desculpo.

**Comment by felipefialho** [comment]
Coloca no https://github.com/frontendbr/open-source 😄

**Comment by matheus-vieira** [comment]
Já coloquei, obrigado @felipefialho
