### ISSUE TITLE
Uso de Task-runners e Pré-processadores em 2020

### ISSUE THREAD

**Issue by matheusbronca** [frontendbr/forum#1746]
Olá pessoal, tudo em paz? Eu espero que sim!

Estou iniciando meus estudos sobre front-end e gostaria de saber como está o uso de ferramentas como Gulp e SASS, o uso ainda é amplo no mercado (2020)? Existem novas tecnologias que vieram para substituir com ganhos relevantes?  

Estou perguntando pois só acho conteúdo antigo quando pesquiso no google, se alguém puder me nortear eu fico imensamente agradecido. Obrigado.

**Comment by portothree** [comment]
Em projetos vanilla js ainda costumo utlizar gulp, que inclusive a versão 4 está muito boa.
Tenho um boilerplate de exemplo: https://github.com/portothree/kowka
Peço desculpas pelo README pouco (nada) claro, acabei nunca melhorando. Se tiver qualquer duvida quanto as tasks posso ajudar sem problemas. Abs!

**Comment by tarciozemel** [comment]
O uso está amplo. A eficiência/tempo de vida de um Gulp da vida ainda vai demorar para esvanecer.

Como disse o colega @portothree , a versão 4 trouxe muitas melhorias: é possível usar com sintaxe moderna de JS, dividir as tarefas em arquivos, geração nativa de sourcemaps, enfim, a coisa tá fina.  :)

Se quiser estudar uma implementação mais robusta, esse repo é bem interessante: https://github.com/jr-cologne/gulp-starter-kit

**Comment by matheusbronca** [comment]
Obrigado pelas respostas pessoal, vou pegar firme nos estudos então.

Vou deixar a issue aberta por mais um período, caso outra pessoa queira colocar sua opinião, será muito bem vinda. o/

**Comment by borghettinho** [comment]
Também tenho um boilerplate de gulp 4 pra adicionar às opções https://github.com/borghettinho/gulp-boilerplate mas faz um tempinho que não mexo.

Agora, se o projeto for super simples não vejo necessidade de não usar o parceljs.org, é vapt vupt e o projeto ta rodando.

Uma coisa que eu to pra fazer faz tempo mas não arranjo tempo nem ânimo é iniciar um projeto do 0 com webpack, pois é muito mais completo. Então fica aí a dica caso tenha mais disciplina que eu.

**Comment by matheusbronca** [comment]
Clonei para usar nos meus projetos @borghettinho , foi uma mão na roda, obrigado!
