### ISSUE TITLE
Vue ou JQuery para projeto

### ISSUE THREAD

**Issue by adolfomoro** [frontendbr/forum#1747]
Então galera, estou fazendo um site, mais especificadamente um subdomínio administrativo, onde vou controlar meus clientes, cadastros, edições, enviar emails, pagamentos, controle de licenças...
Antes comecei a fazer em Jquery, dai conheci o Vue, comecei a refazer o projeto do zero, já fiz uma boa parte, mas ao longo do caminho encontro varios problemas q com o jquery seria mais fácil resolver, tipo mascaras dinâmicas, validações, requisições, e assim vai.. o q acham? devo voltar para o jquery? (Mas n deixar o Vue de lado para projetos futuros)

**Comment by ninetails** [comment]
Só falaria para voltar pro jQuery se prazo for um limitante, que no caso não parece. Como vc já sabe fazer em jQuery, ficaria mais rápido para entregar fazendo nele.

Mas se você se dispôs a fazer em Vue e tempo não é limitante, eu aconselharia a vc a continuar apanhando porém aprendendo. Tenta ir atrás de lib pronta, pra máscara e validação de formulário, devem ter. Já requisição, é seguir a documentação...

Pessoalmente digo que vale a pena estudar essa troca de paradigma, saindo do jQuery e ir para algum framework de componentização. E nada melhor que estudar colocando algo em produção e tendo dores da vida real ;D

Qualquer dúvida tem o forum aqui e [a comunidade no Telegram](https://t.me/vuejsbrasil) que são bem inclusivos (no sentido de acolhedores para quem tá aprendendo).

**Comment by adolfomoro** [comment]
> mponentização. E nada melhor que estudar

Então, teria q ser rápido, pq já estou a um tempo fazendo e queria terminar logo, na questão de ter libs prontas, tem sim! mas nelas n tem coisas q eu preciso, como por exemplo, o de validação não tem a função de focar no campo quando o mesmo esta com erro, então adaptar coisas q eu preciso nas libs demoraria muito, você sabe que demora hahah

**Comment by ninetails** [comment]
Se ainda tiver vontade de continuar e estiver saindo legal o front, tenta então uma solução "híbrida", mas tente escrever do jeito mais desacoplado possível e mapeado para no futuro remover do jQuery.
