### ISSUE TITLE
Vagas potencialmente abusivas, como proceder?

### ISSUE THREAD

**Issue by fernandocamargo** [frontendbr/forum#1760]
@felipefialho, acho que aqui é mais adequado ter esse tipo de discussão, certo?

Eu estava escrevendo esse post aqui e nem tinha me atentado que a issue tinha sido fechada, então colei aqui como ponto de partida.

Como a comunidade pode emitir opinião a esse respeito? Qual a melhor maneira de fazê-lo? Ao contrário do que foi assimilado, a idéia não é confrontar quem postou a vaga em questão e muito menos impedi-lo de fazê-lo (mudei de idéia depois do seu [comentário](https://github.com/frontendbr/vagas/issues/3084#issuecomment-613433032)), mas ter um jeito de levantar o questionamento sobre a autenticidade do que essa vaga oferece de maneira a favorecer membros com pouca experiência, iniciantes ou até em situação de vulnerabilidade financeira.

Eu acho que o que a gente menos precisa nesse momento é de uma nova ferramenta/plataforma que potencializa exploração de trabalho. E isso não é altruísmo/filantropia/empatia. É basicamente uma maneira de preservar a nossa profissão da precarização.

Postar um tópico por vaga aqui nesse fórum não vai atingir a audiência mais interessada no assunto, por isso gostaria de começar a discussão afastando a possibilidade de manter as issues livres de discussão. Tal medida iria facilitar a vida de quem quer (eventualmente) tirar proveito da comunidade.

Já sobre o respeito, que deveria logicamente ser mantido a quase qualquer custo, deve-se levar em consideração a violência simbólica (falar sobre trabalhar 12 horas por dia, por exemplo) mesmo sem conter agressão verbal expressa, como um xingamento.

Quero me apoiar no seu mesmo argumento que fala sobre a fragilidade deixar isso restrito ao seu julgamento. Se você confessa não ter autoridade pra decidir/julgar qual vaga é ou não abusiva - o que eu definitivamente concordo, pra todos os sentidos - acho estranho que possa dizer onde uma discussão mais acalorada se torna de fato ofensiva. Como poderíamos deixar isso menos subjetivo? Eu acho que eu tenha aumentado a animosidade no que escrevi, mas não sinto que tenha de fato cruzado a linha do respeito. E ainda que alguém cruze, quem intermedia isso? E como?

_Obs.:_ você pode ignorar aquela thread - não se trata da discussão dela em específico ou tampouco da anterior, mas como proceder em casos semelhantes?

> Pô, se você ler atentamente, o autor da issue foi o primeiro a [elevar o tom](https://github.com/frontendbr/vagas/issues/3090#issuecomment-613626636).
> 
> Confesso que na outra thread eu descambei pro deboche primeiro, mas nessa aqui não tinha sido o caso.
> 
> Será que você pode ser mais específico sobre qual a política sugerida pela org em questões como essa? Postar no fórum não deveria ser uma possibilidade, visto que a maioria das pessoas sequer vai chegar entrar lá pra ler qualquer coisa referente as vagas postadas aqui.
> 
> Como ficou claro, outras pessoas se importam com vagas potencialmente abusivas. Seja nas condições, seja na remuneração, seja pela própria reputação do contratante. Talvez ninguém tenha levantado tanto a questão até então ou com tanta frequência, mas as coisas mudam e resguardar a própria comunidade deveria ser umas das prioridades.
> 
> Acho que você deu uma resposta bem eloquente na outra issue sobre não poder se envolver/julgar, mas alguma orientação tem que partir de você (ou qualquer outra pessoa que esteja encabeçando isso).

**Comment by felipefialho** [comment]
Sem problemas mano, aqui é um lugar melhor pra esse tipo de debate sim, até porque remove um pouco da vaga em si e torna a discussão mais ampla.

Entendo perfeitamente quando você diz que se sentiu ofendido antes de xingar (que foi a sua maneira de lidar com isso no calor da discussão), mas existem vários pontos de vista em qualquer situação as pessoas podem dar argumentos (que podem naturalmente serem contra argumentados) para defender o ponto de vista que elas considerem adequados. 

Porém considero como limite justamente uma ofensa direta (na qual na nossa sociedade convencionamos designar como xingamentos), pode ser apenas minha interpretação, porém é a que se faz necessário fazer papel de moderador. E por que? Porque é um parâmetro bem definido e inclusive exposto no nosso código de conduta.

Já julgar uma vaga e definir como boa suficiente ou não para estar aqui, foge completamente da minha alçada, não tenho nenhuma autoridade (nem moral) para decidir isso.

Eu só arbitro quando a vaga é de uma área diferente ou está completamente fora dos padrões, nesse caso excluo ou fecho e por que? Porque está nas regras expostas no README do projeto, de forma clara e objetiva.

Já houveram diversas discussões como as que você levantou, em várias das vagas postados do longo do tempo, isso não é novidade.

Você está livre para postar sua opinião, para levantar debates e essa é a graça, as coisas ficam abertas.veu realmente curto o debate saudável.

A issue foi fechada única e exclusivamente pela discussão ter se tornado acalorada a ponto de ter xingamentos e ofensas de nível pessoal (e sim, das duas partes, desculpa por ter marcado apenas você).

Caso tivessem mantido o debate em um tom mais ameno, ela ainda estaria aberta.

**Comment by fernandocamargo** [comment]
Tá certo, faz sentido. Vou tentar manter o nível mínimo de civilidade quando aparecer uns Dória Jr. nas issues. Valeu, @felipefialho e mantenha o bom trabalho aí mantendo a comunidade. 👍
