### ISSUE TITLE
Usuários abusivos, como proceder?

### ISSUE THREAD

**Issue by vrgimael** [frontendbr/forum#1761]
Gostaria de expressar aqui meu profundo descontentamento com a discussão ocorrida nessa thread [aqui](https://github.com/frontendbr/vagas/issues/3090), que vocês provavelmente já devem ter visto... 

Se vocês querem manter essa comunidade sã, deveriam fazer alguma coisa pra evitar que pessoas como @fernandocamargo atrapalhem a vida dos outros.

Basicamente, o usuário @fernandocamargo ficou tumultuando a conversa na issue da vaga que eu postei... segundo ele, o salário seria muito baixo e a vaga seria "abusiva" mesmo apesar de outros comentarem que achavam a vaga uma boa oportunidade.

É patético. Chega alguém oferencendo até R$ 10 mil por mês pra alguém trabalhar de casa, mais do que a média dos sênior na cidade mais cara do país e o infeliz vem dizer que é exploração...

Claro, entendo que há margem pra discussão especialmente considerando que é esperado Inglês, mas chamar de exploração é além de abusivo... Mais importante, a issue não era pra ser lugar de discutirem isso, e os comentários que @fernandocamargo fez no inicio da discussão fazem um grande desserviço pra comunidade.

Ao contrário do que ele disse, foi ele quem iniciou a agressão dizendo que a vaga era uma "eventual exploração", e eu mantive a conversa sem agressividade, xingamentos ou acusações ad-hominem até os últimos comentários, quando o chamei de "idiota" pois literalmente não tinha mais o que dizer. Não retiro minhas palavras. Leia a conversa e tire suas próprias conclusões.

**Ao longo da discussão, @fernandocamargo me xingou de diversas coisas, e brigou comigo e com outros na conversa. Ele deduziu e fez acusações falsas graves pessoais (novamente, minha e de outros usuários) e mentiu compartilhando imagens como se eu tivesse postado coisas racistas em mídias sociais. Pura mentira.** Esse tipo de fraude provavelmente deve ser considerado um crime... no mínimo mostra que:

Essa pessoa é de mal caráter, mal intencionada e não quer o bem da comunidade e seus membros. Sua participação na discussão foi uma absoluta perda de tempo e só acaba prejudicando quem quer de forma séria encontrar um programador e de quem quer encontrar um emprego.

Sugiro que repensem a forma com que as issues são moderadas, ou podem apostar que menos gente vai querer postar vaga aqui...

**Comment by fernandocamargo** [comment]
Além de tudo é burro.

**Comment by fernandocamargo** [comment]
E se for pra evitar que sanguessugas que nem você postem, que caia a quantidade e aumente a qualidade.

**Comment by fernandocamargo** [comment]
E por fim, não entende o que é ética porque é um playboy safado acostumado com privilégio.

**Comment by fernandocamargo** [comment]
[![Marilene Chauí](https://img.youtube.com/vi/OsvhFMrJLT8/0.jpg)](https://www.youtube.com/watch?v=OsvhFMrJLT8)
> "A classe média é uma abominação política, porque ela é fascista. Ela é uma abominação ética, porque ela é violenta e ela é uma abominação cognitiva porque ela é ignorante. Fim."

**Comment by fernandocamargo** [comment]
Um arrombado desse que cresceu pagando lanche pros outros no colégio pra não apanhar no recreio acha que com dinheiro faz o que quiser e compra o mundo.

![not on my watch](https://user-images.githubusercontent.com/232828/79333476-e40c9e00-7f1e-11ea-9052-60f8df7ecfce.gif)

**Comment by fernandocamargo** [comment]
E aposto que a sua família também ficou puta quando tiveram que pagar direitos trabalhistas para as empregadas domésticas. 😆

**Comment by felipefialho** [comment]
@vrgimael A melhor moderação que existe é o fato de que todos os comentários feitos por aqui vão ficar disponíveis pra posteridade. Partimos do principio de que todos são adultos e deveriam ser conscientes da sua postura em uma rede social profissional e aberta como essa.

E exatamente pelo fato de ser aberto, os usuários são livres para levantar os debates que acharem pertinentes, inclusive em issues de vagas. Faz parte do jogo, ao mesmo tempo que uns podem não curtir e até queiram discutir sobre o tema, outros vão gostar da oportunidade (como de fato aconteceu, aposto que recebeu vários CVs).

Ele considerou sua vaga abusiva (opinião **dele**) e você defendeu. A discussão se manteve em bom nível até partirem para ofensas pessoais, obviamente ferindo o código de conduta. Por que não houve intervenção antes? Porque eu não fico o dia inteiro observando o que acontece por aqui, repito, parto do principio que todos deveriam ser conscientes da própria postura.

E sinceramente, falando de adultos na média de 25~30 anos, chega a ser inacreditável que outro adulto precise aparecer para moderar uma discussão.

Também respondi o @fernandocamargo na #1760. Por motivos óbvios vou fechar as duas issues, se tiverem mais questões pessoais para debaterem sugiro se adicionarem em alguma rede social e continuarem por lá.

E se tiver qualquer outra ofensa ou retomada desse assunto de qualquer uma das partes, infelizmente vou precisar banir da organização.
