### ISSUE TITLE
Atualizar uma página no GIT IO 

### ISSUE THREAD

**Issue by reynaldobarrosjr** [frontendbr/forum#1766]
Uma dúvida básica de git IO pages. Eu fiz um fork de um projeto que utiliza apenas html e js. Fiz as edições e comitei. Tudo usando a interface do Github mesmo. Nada de terminal. O problema que estou enfrentando é que a página não atualiza. Não vejo os itens que eu alterei sendo refletidos. 

https://github.com/reynaldobarrosjr/agile-skills

Alguém pode me dar uma ajuda?

**Comment by glauberm** [comment]
Você está commitando as alterações na branch `gh-pages`? [O GitHub hoje mais cedo estava bem instável](https://news.ycombinator.com/item?id=22935941), pode ser por isso.

**Comment by reynaldobarrosjr** [comment]
Pois é.. eu alternei entre as branches e rolou. Obrigado @glauberm ... tô conseguindo tocar o trabalho.
