### ISSUE TITLE
[GULP] Minificar JS com ES6 sem passar por compiladores

### ISSUE THREAD

**Issue by yuricamara** [frontendbr/forum#177]
Pessoal,
Como estão fazendo para minificar código JS com ES2015 SEM passar pelo Babel ou outro compilador? 
Não está rolando nem com gulp-minify e nem com gulp-uglify. Eles não conseguem fazer o parse.

**Comment by yuricamara** [comment]
Resolvido em 
[Issue with Babel, ES6 and Uglify - terinjokes/gulp-uglify
](https://github.com/terinjokes/gulp-uglify/issues/146#issuecomment-223767031)

**Comment by rafaelcamargo** [comment]
Acabei de usar [gulp-babili](https://www.npmjs.com/package/gulp-babili) com esse propósito e funcionou muito bem.
