### ISSUE TITLE
Não consigo atualizar meu branch principal

### ISSUE THREAD

**Issue by LuisMatheus-dev** [frontendbr/forum#1771]
**Hi Devs** , Tenho um repositório, para organizar sua estrutura, criei uma pasta e movi meus arquivos para lá, commitei as mudanças no meu master-backup (secundário), mas quando fui fazer  a união com o meu  master (principal), as alterações não são aplicadas , nele minha pasta esta vazia , enquanto o master-backup esta correto.O pior é que ele não retorna nenhum erro . Como devo proceder

**Comment by deppbrazil** [comment]
@LuisMatheus-dev  seria esse [repo](https://github.com/LuisMatheus-dev/Gama-Academy)?

O que aconteceu foi que vc criou uma branch **`master-backup`** com isso seu repo fica então com a branch **`master`** + **`master-backup`** quando vc deu o push foi para a **`master-backup`** no remoto, com isso não vai apresentar erro mesmo, vc apenas precisa fazer o merge passando o conteúdo da branch **`master-backup`** para a **`master`** através do terminal mesmo vc consegue fazer o merge da **`master-backup`** com a **`master`** (lembrando de fazer o merge via command-line estando dentro da branch `master`),

* Isso [aqui](https://github.com/deppbrazil/git/blob/master/commands/branchs.md) vai te ajudar fazer via command-line😃 

* Ou se preferir vc consegue fazer isso abrindo um Pull Request da **`master-backup`** para a **`master`** pelo próprio Github.

### Espero ter ajudado mano! 👍

**Comment by LuisMatheus-dev** [comment]
@deppbrazil Cara me ajudou a entender melhor, mas eu até tentei fazer `$git merge master-backup ` dentro do master mas ele apenas diz que tudo já esta atualizado, só que não havia pensado em fazer o pull request vou tentar aqui

**Comment by LuisMatheus-dev** [comment]
Ele diz que meus branchs são totalmente diferentes  não há o que comparar, o que é verdade, mas existe uma outra forma de fazer ?

**Comment by theandersonn** [comment]
@LuisMatheus-dev Tá fazendo esse processo na sua máquina? Se não tiver fazendo, faça.

Eu fiz essa documentação abrangendo vários processos com git, essa parte em especifico aborda as branchs.
https://github.com/theandersonn/comandos-git/blob/master/comandos/branches.md

Leia e veja se te ajuda.

Esteja ciente que não pode ter commits pendentes e alterações pendentes. veja isso com `git status`

**Comment by LuisMatheus-dev** [comment]
@theandersonn Sim amigo estou

**Comment by deppbrazil** [comment]
@LuisMatheus-dev fiz o fork do seu projeto e analisei,

Ficou bem confuso de entender qual foi a lógica que vc usou para criar a **`master-backup`** pois o histórico de commits dela está completamente diferente da **`master`**, isso não pode acontecer pois basicamente todas as branches teoricamente derivam da master,

Dessa forma, como criou essa branch **`master-backup`**?

### O problema:
* Os branches **`master`** e **`master-backup`** tem históricos .git completamente diferentes, portanto comparando os 2 branchs os commits iniciais são totalmente diferentes em cada branch, de fato não conseguirá dar o merge,

### A Solução:
* Neste caso fiz um teste forkando seu projeto e entrando na branch **`master`** e renomeando-a para **`master-del`** com isso renomeei sua **`master-backup`** para **`master`** deletei sua **`branch-del`** local e remotamente, criei uma branch **`develop`** sincronizada com **`master`** para usar como branch de desenvolvimento com isso ambas tem mesmo histórico, porém agora estando em **`master`** eu precisava arrumar o **push.default** para ele entender que meu HEAD agora era **`master`** e não mais **`master-backup`**, então rodando **`git branch --unset-upstream`** e o próximo push passando **`git push --set-upstream origin master`** os demais apenas com **`git push`** já rodam normal agora, se quiser dar uma olhada ta [aqui](https://github.com/deppbrazil/Gama-Academy)
* Outra solução a se fazer é vc entrar dentro de **`master`** e copiar cada commit e seu respectivo conteúdo da branch **`master-backup`** e depois deleta essa **`master-backup`** local e remoto, com isso vc tem o respectivo conteúdo de **`master-backup`** em **`master`** a partir disso crie outra branch ramificando de master para não acontecer o que aconteceu.

**Comment by LuisMatheus-dev** [comment]
@deppbrazil Cara obrigado pela sua paciência,e agradeço pela sua ajuda.
Eu fiz o  **$git rebase master-backup** e tudo estava correto mas quando fui fazer o push , o git me pediu para fazer o pull ,agora eu tenho o meu repositório dentro do repositório kkk
<img src='https://i.imgur.com/pdgXudO.png'> 

 Como posso corrigir e fazer o push sem acontecer isso ?

**Comment by deppbrazil** [comment]
@LuisMatheus-dev que isso cara estamos ai para se ajudar, fico feliz em poder contribuir para seu aprendizado, 

Bom vamos lá precisaria entender mais a fundo como vc fez o **`rebase´** e dentro de qual branch, pois tem várias formas para executa-lo, é um comando um pouco mais avançado, acho que essa [doc](https://www.atlassian.com/br/git/tutorials/rewriting-history/git-rebase) pode te ajudar a entender pq um repositório ficou dentro do outro..rsrs, 

Aproveita e da uma lida nessas outras tb [Como reescrever o histórico](https://www.atlassian.com/br/git/tutorials/rewriting-history) e [Mesclagem vs. Rebase](https://www.atlassian.com/br/git/tutorials/merging-vs-rebasing)

Isso vai te ajudar a entender quando cair em situações como esta, 

Teste ai e conta pra gente se deu certo 😃

**Comment by LuisMatheus-dev** [comment]
Eu fiz dentro do meu branch **master** eu dei uma conferida depois com o **$git log** todos os commits tinham sido atualizados como pode ver [aqui](https://github.com/LuisMatheus-dev/Gama-Academy/commits/master) , para tentar reverter ele antes do push eu execultei o **$git reflog** para encontrar a alteração e depois execultei o **git reset --hard** para alterar tanto no staging quanto no diretório mas mesmo assim ele continua lá

**Comment by deppbrazil** [comment]
@LuisMatheus-dev entendi, 

Cara assim ficou bem confuso entender o que de fato vc fez...rsrs

Meu conselho é: 
* Siga um dos 2 passos que sugeri ali em cima e tente não repetir esse tipo de problema na criação dos seus branches, caso contrário vc vai perder mais tempo tentando consertar problema no seu flow do que desenvolvendo,
* Dê uma estudada em git, não aplique comando avançados sem entender a fundo o que ele está fazendo por trás.
* Aplique Gitflow no seu flow de desenvolvimento, isso vai te ajudar a não cair nesse tipo de situação.

**Comment by LuisMatheus-dev** [comment]
@deppbrazil Eu estudei sobre antes , fiz um curso de git pela Platzi , mas como ainda faltava experiencia não soube estruturar esses arquivos antes ,e virou essa salada, mas valeu ,consegui movendo direto pelo master na realidade quando fui movendo as pastas levei junto o arquivo .git :) 
Cara mais acabei de aprender muito com você ,vlw msm
