### ISSUE TITLE
Discord do Frontend Brasil

### ISSUE THREAD

**Issue by kvnol** [frontendbr/forum#1772]
Abri essa discussão, pois não sei se já existe e também não quero criar algo sem falar com os admins sobre a ideia.

Seria interessante demais (pelo menos na minha cabeça) se o Frontend Brasil estivesse no Discord, com código de conduta, canais separados para frameworks tecnologias, podendo ter canais de áudio para live codings e talks, salas onde as pessoas possam estudar juntos um determinado curso e já trocar ideia na hora sobre a aula.

Na minha cabeça é algo interessante, não sei o que vocês acham...

c/c @frontendbr/admins

**Comment by fdaciuk** [comment]
Opa! Vou deixar minha opinião sobre o assunto: comunidades são independentes. Não existe donos de comunidades, e sim pessoas que criam algum canal para que outras possam discutir assuntos do mesmo interesse.

Estou falando isso pois a impressão que eu que tenho ao ler esse post - e acredito que também seja a de outras pessoas - é de que tudo o que for feito relacionado à "FrontEndBR" precisa estar ligado a essa comunidade específica do GitHub, e precisa sempre ter as mesmas pessoas por trás dessas novas iniciativas.

No caso do Discord, particularmente eu não uso. Mas nada impede de você criar uma comunidade "FrontEndBR" lá e cuidar dessa comunidade, com outras pessoas que também gostem do Discord e compartilhem das mesmas ideias, saca? :)

Quando o @felipefialho teve a ideia de criar a comunidade FrontEndBR no GitHub, não foi pra centralizar as coisas nas mesmas pessoas, ou colocar "donos" ou "responsáveis" pela comunidade. Muito pelo contrário: existem várias comunidades FrontEndBR em canais diferentes, muitos que nós nem conhecemos, e nem por isso elas deixam de ser comunidades :)

Como todos nós estamos aqui no GitHub, então esse GitHub é nossa responsabilidade manter, já que aceitamos a responsabilidade de fazê-lo. Mas a comundiade não é nossa. Isso aqui é só mais um canal no meio de tantos outros :)

Então a minha recomendação é: se você acha que faz sentido ter uma comunidade no Discord, crie, e fique à vontade para divulgar por aqui para que as pessoas que tenham o mesmo interesse também participem! :)

**Comment by kvnol** [comment]
@fdaciuk pode crer, a ideia de marcar os admins daqui é mais pra ver o que acham da ideia e se a galera participaria. Eu criei o server no Discord e estou organizando os canais: https://discord.gg/eBNX94

**Comment by felipefialho** [comment]
Sem muito a acrescentar depois desse belíssimo texto do @fdaciuk (❤️). 

A ideia é que iniciativas orgânicas sempre surjam a partir dessa, gosto de descentralização e por isso brinco que não sei de várias coisas que acontecem a partir daqui, haha. Só confio em vocês pra manter o nível de respeito e bom senso em todas as novas iniciativas.

Também não uso Discord, mas se achar que vale a pena manda ver e pode adicionar o link no README assim como temos do Slack 😄

**Comment by rafaelnogueira1** [comment]
Cara se tu busca um grupo no Discord por curtir mais lá, estou em um que o pessoal tá cuidando bem dele, montou uns canais, as vezes rolam umas lives. 
Quanto mais gente melhor. Vou deixar o link aqui, caso não possa deixar eu removo galera https://discord.gg/WTgs9Rh

**Comment by kvnol** [comment]
Tem também o canal do CollabCode Br: https://discord.gg/FP5UaAG
