### ISSUE TITLE
Iniciar carreira Dev FRONT PJ em 2020

### ISSUE THREAD

**Issue by Marilzon** [frontendbr/forum#1783]
Olá amigos, estou com muitas duvidas, pretendo **iniciar como PJ** e li vários artigos sobre o assunto, mas no final não fica um bom entendimento, para eu iniciar como PJ, logo:
 - Eu deveria contratar um _contator_ ou _empresa do ramo_ para tratar de assuntos burocráticos referente a impostos e declarações? 
 - Precisaria de Inscrição municipal
 - Onde eu me apoiaria ou que plataforma conseguiria ter orientação sobre o assunto?
 - Impostos iniciais e taxas?

Tenho bastante duvidas, o que vocês me indicam e para que lado devo caminhar e me direcionar sobre este assunto!?

**Comment by heliomsolivas** [comment]
Eu sempre trabalhei CLT, porém o meu atual eu sou PJ (MEI) e o processo até que foi simples, só tirava algumas dúvidas com o contador da empresa.

Mas no meu caso fiz tudo praticamente sozinho, a inscrição municipal acho que varia da cidade de onde você mora.

No caso do MEI fiz tudo por aqui: [http://www.portaldoempreendedor.gov.br/](http://www.portaldoempreendedor.gov.br/) e você paga uma mensalidade de +- 50 e poucos reais que é o DAS MEI.

**Comment by Marilzon** [comment]
@heliomsolivas Que legal, eu tinha informações de que Desenvolvedor não era permitido ser **MEI**, vou acessar este site e verificar todas informações importantes e atualizadas!

**Comment by felipefialho** [comment]
Opa @Marilzon recomendo fortemente que veja essas discussões: #28 #471
