### ISSUE TITLE
Usar Yarn ou NPM?

### ISSUE THREAD

**Issue by wilsonneto-dev** [frontendbr/forum#1790]
Galera, 
além e culturas e costumes, há de fato vantagens e desvantagens entre NPM e Yarn? Quais vocês usam? O que vocês veem de diferenças?

**Comment by felipesuri** [comment]
Eu não sei se realmente existe vantagem (maquinaria) entre um ou outro.

Mas utilizo o Yarn, vejo ele de uma forma mais bonita, não gostei muito de como o NPM me retorna no console, preferi o Yarn mesmo.

Esse é o motivo pelo qual utilizo o Yarn, mesmo que comprovado que o NPM é mais rápido, pensaria bastante antes de utilizar.

**Comment by waldemirflj** [comment]
@wilsonneto-dev tem mais haver com preferência e familiaridade. Eu utilizo o NPM, já utiliza ele antes do Yarn... hehehe

**Comment by rodrigodiasnoronha** [comment]
Ah, ai vai da sua preferência. Eu gosto do Yarn, mas gosto ainda mais do NPM.

**Comment by ninetails** [comment]
Ambos são bons, ambos tem vantagens e desvantagens (se comparar as versões atuais). Mas com a chegada do [berry](https://github.com/yarnpkg/berry) comecei a gostar menos do Yarn.

**TL;DR** Yarn pra monorepos (e/ou Yarn Plug'n'Play, pq o Tink vai ter um plug'n'play mas será diferente... ainda não fui atrás), npm pro restante.

### Por que Yarn pra _monorepos_?

[Workspaces](https://classic.yarnpkg.com/en/docs/workspaces/). Ele unifica dependência de todos os pacotes do _monorepo_ em um só _node_modules_ (ou _cache folder_ no PnP), inclusive fazendo _dedupe_. Claro, precisa ativar o _Yarn Workspaces_ pra funcionar na v1.x, mas ainda sim tem muita coisa que se repete entre pacotes: lint & seus configs, babel & configs, jest etc...

---

Tirando isso, só se quiser algo bem mais específico do Yarn, tipo [Offline Mirror](https://classic.yarnpkg.com/en/docs/offline-mirror/). Ou [npm audit](https://docs.npmjs.com/cli/audit) no caso do npm.
