### ISSUE TITLE
Soma em Loop com Função declarada e variável fora de for

### ISSUE THREAD

**Issue by cruzmah** [frontendbr/forum#1799]
Olá, boa noite.

Estou utilizando uma plataforma onde posso simular a programação e no momento estou com muita dificuldade em um exercício de loop. Segue:

"Escreva uma _função_ **somar5MoedasDe25Centavos**, que adiciona o valor de 5 moedas de 0,25 centavos e retorna o resultado. Utilizar a palavra reservada **return** ao invés de console.log"

Tentei dessa maneira:

function somar5MoedasDe25Centavos() {
    for (let i = 0; i < 6; i++) {
        return somar5MoedasDe25Centavos = somar5MoedasDe25Centavos + 0.25;
    }
}

A mensagem de erro foi: "A função somar5MoedasDe25Centavos deve retornar 1.25".

No material do curso diz: "Se quisermos manter o valor fora de cada iteração, devemos fazer com que essa variável seja global para o for. Conseguimos isso de maneira simples, declarando a variável fora do for."

Então tentei:

let somar5MoedasDe25Centavos;

function somar5MoedasDe25Centavos() {
    for (let i = 0; i < 6; i++) {
        return somar5MoedasDe25Centavos = somar5MoedasDe25Centavos + 0.25;
    }
}

A mensagem de erro foi: "Identifier 'somar5MoedasDe25Centavos' has already been declared".

Resumindo: tenho que fazer que a cada iteração o valor de 0.25 permaneça e adicione mais 0.25 até que retorne 1.25. Para isso devo declarar uma variáel e uma função com for.

**Comment by NicolasMatheus** [comment]
```js
let somarMoedas = 0;

function somar5MoedasDe25Centavos() {
  for (let i = 0; i < 5; i++)
    somarMoedas += 0.25;
  return somarMoedas;
}
```
Poderia assim?

**Comment by NicolasMatheus** [comment]
> Olá, boa noite.
> 
> Estou utilizando uma plataforma onde posso simular a programação e no momento estou com muita dificuldade em um exercício de loop. Segue:
> 
> "Escreva uma _função_ **somar5MoedasDe25Centavos**, que adiciona o valor de 5 moedas de 0,25 centavos e retorna o resultado. Utilizar a palavra reservada **return** ao invés de console.log"
> 
> Tentei dessa maneira:
> 
> function somar5MoedasDe25Centavos() {
> for (let i = 0; i < 6; i++) {
> return somar5MoedasDe25Centavos = somar5MoedasDe25Centavos + 0.25;
> }
> }
> 
> A mensagem de erro foi: "A função somar5MoedasDe25Centavos deve retornar 1.25".
> 
> No material do curso diz: "Se quisermos manter o valor fora de cada iteração, devemos fazer com que essa variável seja global para o for. Conseguimos isso de maneira simples, declarando a variável fora do for."
> 
> Então tentei:
> 
> let somar5MoedasDe25Centavos;
> 
> function somar5MoedasDe25Centavos() {
> for (let i = 0; i < 6; i++) {
> return somar5MoedasDe25Centavos = somar5MoedasDe25Centavos + 0.25;
> }
> }
> 
> A mensagem de erro foi: "Identifier 'somar5MoedasDe25Centavos' has already been declared".
> 
> Resumindo: tenho que fazer que a cada iteração o valor de 0.25 permaneça e adicione mais 0.25 até que retorne 1.25. Para isso devo declarar uma variáel e uma função com for.

Você sobre escreve a própria função, e a [função](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Fun%C3%A7%C3%B5es) para de executar quando encontra a palavra chave ```return```

**Comment by cruzmah** [comment]
> ```js
> let somarMoedas = 0;
> 
> function somar5MoedasDe25Centavos() {
>   for (let i = 0; i < 5; i++)
>     somarMoedas += 0.25;
>   return somarMoedas;
> }
> ```
> 
> Poderia assim?

Quando eu crescer, quero ser que nem você. Me salvou mais uma vez. Obrigado!!!
