### ISSUE TITLE
Somar pares em loop for com Função declarada

### ISSUE THREAD

**Issue by cruzmah** [frontendbr/forum#1800]
Olá, novamente, boa noite.

Estou utilizando uma plataforma onde posso simular a programação e no momento estou com muita dificuldade em um exercício de loop. Segue:

"Defina a _função_ **somaDosPares(x)** que retorna a soma total de todos os números que são pares, ou seja, divisíveis por 2 obtendo resto 0. Desta forma: 0 + 2 + 4 + 6 + 8 + 10 + ..... X. Sabemos que usamos i++ para incrementar em uma unidade o i a cada iteração. Mas se tentarmos incrementar o i em duas unidades a cada iteração? Experimente utilizar i+=2 e veja o que acontece."

Tentei da seguinte maneira:

let soma = 0;

function somaDosPares(x) {
  for(let i = 0; i < x; i++) 
  if (i % 2 == 0) {
    soma + i+=2;
     return soma;
  }
 }
somaDosPares(10);

Tentei também:

function somaDosPares(x) {
  let soma = 0;  
  for(let i = 0; i < x; i++)
  if (i % 2 == 0) {
    soma = soma + i+=2;
  }
  return soma;
}
somaDosPares(10);

O erro que retorna em ambos foi: "Invalid left-hand side in assignment".

Em nenhum lugar informa para utilizar condicionais, mas não sei se há outra maneira do exercício ser feito.

Estou com bastante dificuldade porquê é um curso de graça, sem presença de professor e sem materiais complementares.

**Comment by ninetails** [comment]
Sobre o erro: "Invalid left-hand side in assignment" é dado provavelmente nestas duas linhas

```js
soma + i+=2;
// e
soma = soma + i+=2;
```

Quando você usa o operador `+=` é necessário ter uma variável à esquerda, no caso acima em ambas as linhas, tem uma expressão e não uma variável (`soma + i` e `soma = soma + i` respectivamente).

Recomendo dar uma lida na documentação da MDN que fala sobre [Expressões e operadores](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Expressions_and_Operators). Aliás, recomendo o site da MDN em si para utilizar como leitura de apoio quando tiver dúvidas sobre a sintaxe JavaScript. Talvez seja difícil de achar a dúvida no começo, mas a galera do forum tá ae pra ajudar tb em dúvidas conceituais.

**Comment by gabriel-hahn** [comment]
Acrescentando ao que o @ninetails comentou, acredito que o `i += 2` foi citado pois tu iria iterar pelo número passado por parâmetro (10 no caso) e já pegar os números pares automaticamente ao invés de usar o i++ no FOR e validar cada número, pois sabemos que os números pares são de 2 em 2, ficando algo como `for(let i = 0; i < x; i += 2)`.

Sobre o código, acredito que tem alguns pontos para analisar:
Está faltando um `}` para fechar o escopo da sua função e você está somando os valores nesta linha `soma = soma + i+=2;` que pode ser substituída por `soma += i;`. Ou seja, somente considera os números que forem pares e adiciona ele no contador (seu `i` nesse caso). Cuidado aqui pois você estava atribuindo dois valores ao mesmo tempo e causando o erro que você citou (atribuindo com o `=` conforme já explicado). 

Se você quiser iterar até o número 10 e incluí-lo na conta, você pode utilizar o FOR dessa maneira: `for(let i = 0; i <= x; i++)`, fazendo com que ele considere o último número também na operação, e não somente números menores (e não iguais) a 10 que foi o parâmetro passado ao chamar a função.

**Comment by cruzmah** [comment]
@ninetails e @gabriel-hahn 

Muito obrigado pela ajuda. Segui a orientações de vocês e consegui passar pelo exercício dessa maneira:

function somaDosPares(x) {
  let soma = 0;
  for (let i = 0; i <= x; i+=2) {
    if (i % 2 == 0) {
      soma += i;
    }
  }
  return soma;
}
somaDosPares(10);

**Comment by gabriel-hahn** [comment]
Show de bola! Mais uma dica seria remover o IF dentro do FOR. Incrementar o `i` por 2 em `i += 2` já faz você obter todos os números pares até chegar ao número passado por parâmetro, no caso a validação do IF fica redundante.

**Comment by cruzmah** [comment]
> Show de bola! Mais uma dica seria remover o IF dentro do FOR e somente somar o `i` ao `soma`. Incrementar o `i` por 2 em `i += 2` já faz você obter todos os números pares até chegar ao número passado por parâmetro, no caso a validação do IF fica redundante.

Eu fiquei me questionando sobre isso mesmo. Mas como em alguns exercícios anteriores tive que fazer o IF e em todo lugar que pesquisava na internet usavam, achei que talvez fosse obrigatório. De qualquer forma, obrigado mais uma vez.
