### ISSUE TITLE
Erro  git push --set-upstream origin master

### ISSUE THREAD

**Issue by mayaemerson** [frontendbr/forum#1806]
Boa noite, estou com um erro ao realizar o push, aparece esse erro, segue o erro  
git push --set-upstream origin master,  alguém pode me ajudar nesse erro.

**Comment by KlausDevWalker** [comment]
Falta você mandar a imagem pra termos um pouco mais de contexto a seu problema.

**Comment by lucasferreiralimax** [comment]
> Boa noite, estou com um erro ao realizar o push, aparece esse erro, segue o erro
> git push --set-upstream origin master, alguém pode me ajudar nesse erro.

Você esta tentando fazer um push remoto? Tem direitos sobre o projeto?
As vezes pode ser permissão do projeto ou então o upstream com endpoint errado

**Comment by mayaemerson** [comment]
![Captura de Tela 2020-06-01 às 15 16 22](https://user-images.githubusercontent.com/57040825/83827952-dae5b500-a6b5-11ea-9241-4beac92c6e12.png)
![Captura de Tela 2020-06-01 às 15 15 39](https://user-images.githubusercontent.com/57040825/83827953-dc16e200-a6b5-11ea-972f-af05972f2cc6.png)
 Segue print do erro, o projeto é meu eu estava realizando normal o push, mas apareceu esse erro agora, já fiz um pull mas não resolveu.

**Comment by KlausDevWalker** [comment]
A mensagem tá dizendo que seu repo local tá atrasado com relação ao remoto. Por acaso você mexeu em algo pela UI do GitHub depois de ter clonado ele na sua máquina?

**Comment by mayaemerson** [comment]
Não,

**Comment by mayaemerson** [comment]
Resolvido.
