### ISSUE TITLE
Elemento criado via DOM não renderiza

### ISSUE THREAD

**Issue by rodrigonoma** [frontendbr/forum#1807]
Monto uma div via DOM utilizando o Javascript(createElement, AppChild), aparece na tela, porém quando clico com o botão direito e vou em visualizar código fonte, ele não foi renderizado.
O que poderia ser?
Obrigado.

**Comment by portothree** [comment]
Quando acessa `view-source:URL` voce estara a ver apenas o markup e não os elementos criados apos ser carregado pelo navegador, para isso pode acessar as propriedades no **DOM and Style Inspector** que podes acessar com Ctrl+Shift+C na maioria dos navegadores.

**Comment by kazzkiq** [comment]
Estendendo o que o @portothree pontuou corretamente:

- **Visualizar código fonte:** Mostra o código recebido diretamente do servidor (ou seja, é como se mostrasse o texto estático recebido, sem ser executado pelo navegador);
- **Inspetor (Devtools)**: Mostra o código HTML **após** ser executado pelo navegador, já na árvore DOM (DOM tree), com todas as modificações que forem feitas em tempo real.

Para acessar o código fonte: `Clique direito` > `Ver Código Fonte`
Para acessar a árvore DOM (seu caso): `Clique direito` > `Inspecionar`

**Comment by rodrigonoma** [comment]
OK pessoal, obrigado pela ajuda!
