### ISSUE TITLE
Loop For para Multiplicação

### ISSUE THREAD

**Issue by cruzmah** [frontendbr/forum#1808]
Tenho que fazer com que a função me retorne `15` se o parâmetro for `2`, e `5` se o parâmetro for `1`.

O exercício: "Crie uma função chamada caloriasDeTrote(), que recebe por parâmetro o número de voltas representado por um valor numérico e retorne a quantidade de calorias que será consumida.
Por exemplo:

`caloriasDeTrote(2)`

Deveria devolver 15 onde 5 calorias são da primeira volta (5 * 1) mais 10 calorias da segunda (5 * 2)."

Quando faço:

function caloriasDeTrote(x) {
  let calorias = 0;
  for(let i = 0; i <= x; i++) {
    calorias += 5;
  }
  return calorias;
}
caloriasDeTrote(1);

Quando uso `2` como parâmetro, me retorna corretamente o `15` , mas quando uso o `1` como parâmetro, me retorna `10`, quando queria retornar `5`.

Se eu uso `i < x` em vez de `i <= x`, a lógica se inverte. `2` como parâmetro, me retorna `10`, quando queria retornar `15` e `1` me retorna corretamente `5`. Deveria usar condicional?

**Comment by LuisMatheus-dev** [comment]
Olá Tudo bem ? 
Como você colocou no enunciado a cada volta será `5 * i` , e não apenas somar +5 a cada volta a função correta ficaria:

function caloriasDeTrote(numeroVoltas) {
    var calorias = 0;
    for(var i = 1; i <= numeroVoltas; i++) {
        calorias += 5 * i; 
    } 
    return calorias;
}
caloriasDeTrote(2) ;

**Comment by cruzmah** [comment]
> Olá Tudo bem ?
> Como você colocou no enunciado a cada volta será `5 * i` , e não apenas somar +5 a cada volta a função correta ficaria:
> 
> ```
> function caloriasDeTrote(numeroVoltas) {
>     var calorias = 0;
>     for(var i = 1; i <= numeroVoltas; i++) {
>         calorias += 5 * i; 
>     } 
>     return calorias;
> }
> caloriasDeTrote(2) ;
> ```
> 
> Espero ter ajudado 👍

@LuisMatheus-dev muito obrigado! Ajudou muito. Eu havia tentado com`*=5 ` e como obviamente não deu certo, tentei dessa maneira porquê até então era o que menos dava errado. XD
