### ISSUE TITLE
Erro: Maximum call stack size exceeded ao iniciar projeto React 

### ISSUE THREAD

**Issue by LuisMatheus-dev** [frontendbr/forum#1811]
Hi Coders ! 
Estou seguindo o projeto da Semana Next Level Week da Rockseat porem como se costume , estou tropeçando em erros no npm, ao tentar instalar a biblioteca react para o typescript.
O comando que estou execultando é:
`$ npx create-react-app web --template typescript`
Que me retorna este erro:
```
npx: installed 98 in 11.33s
Creating a new React app in /mnt/c/Users/Administrador/Desktop/Luis/Estudo Pessoal/Javascript/Projetos/Next Level Week/web.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template-typescript...

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/luis/.npm/_logs/2020-06-07T18_32_26_960Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts cra-template-typescript has failed.

Deleting generated file... node_modules
Deleting generated file... package.json
Deleting web/ from /mnt/c/Users/Administrador/Desktop/Luis/Estudo Pessoal/Javascript/Projetos/Next Level Week
Done.
```
Já pesquisei este erro , mas não consigo achar a solução , porque cada caso eles execultaram passos diferentes:
Estou utilizando o WSL com Ubuntu.
Versão Node: 12.18
Versão NPX: 6.14
Ubuntu : 20.04

**Comment by theandersonn** [comment]
@LuisMatheus-dev 
Tente:
```
create-react-app <nome_do_projeto> --template=typescript
```

Substitua <nome_do_projeto> pelo nome do _app_ que será criado.

**Comment by portothree** [comment]
Provavelmente seu cache do npm esta cheio, tente `npm cache clean --force`

**Comment by ninetails** [comment]
Também acho que poderia ser cache. Rodei aqui com a última versão e não tive problemas, inclusive reforçando pegar somente as últimas versões:

> npx create-react-app@latest <project name> --template typescript@latest

Também recomendo por desencargo: atualizar o Yarn e limpar o cache do Yarn pois o _create-react-app_ usa ele para instalar as dependências.

Vc tb pode passar uma flag para o _create-react-app_ utilizar o npm ao invés do Yarn:

> npx create-react-app <project name> --template typescript **--use-npm**

**Comment by LuisMatheus-dev** [comment]
Ainda não testei a dica do @theandersonn porque não estou no meu computador , mas já efetuei a limpeza de cache antes e nada... 
@ninetails sou novo nessa questão de pacotes , o yarn não vem com node ?
Falo isso porque na outra vez que tentei, vi que na instalação, o npm não foi instalado em conjunto

**Comment by ninetails** [comment]
@LuisMatheus-dev explicando:

[npm](https://www.npmjs.com/) e [Yarn](https://classic.yarnpkg.com/lang/en/) são dois gerenciadores de pacotes. O primeiro vem com o **Node.js**, o segundo vc instala separado. Como o segundo também é um produto da equipe de engenharia do **Facebook** que abriu pra _Open Source_ assim como o React, o _create-react-app_ por padrão atrela sua instalação usando o Yarn.

Não sei se o _create-react-app_ instala o Yarn quando vc roda sem ele na máquina, ou se utiliza somente o npm caso não encontrar o Yarn.

Pra saber se está instalado e qual versão, seria rodar:

```sh
$ yarn --version
```

(a atual é a v1.22.4)

E pra saber onde está instalado:

```sh
$ which yarn
```

este varia dependendo da forma como foi instalado. Também não sei se é instalado como dependência do node caso não tiver anteriormente instalado.

---

Aliás... como o pessoal falou, vc pode instalar sem usar **npx**, mas precisaria instalar antes globalmente:

```sh
$ npm install --global create-react-app
```

E daí usar sem o `npx` na frente.

---

Também tente atualizar o npm

```sh
$ npm install --global npm
```

ou se possível atualizar o Node se for algo fácil, caso tenha instalado usando [nvm](https://github.com/nvm-sh/nvm).

---

Se o erro persistir, talvez precisemos ver o conteúdo do log:

> /home/luis/.npm/_logs/2020-06-07T18_32_26_960Z-debug.log

Se puder depois das tentativas acima e lendo o log não conseguir resolver, retire os dados sensíveis do log (não sei se tem, mas é sempre bom ressaltar esse passo) e cole aqui.

**Comment by LuisMatheus-dev** [comment]
@ninetails SHOWW , funcionou no final das contas eu não tinha o yarn instalado , depois seguei a dica do @theandersonn e foi sucesso
