### ISSUE TITLE
Arrey: quantidade de meses com lucro e saldo dos meses com lucro

### ISSUE THREAD

**Issue by cruzmah** [frontendbr/forum#1821]
Olá, pessoal.
Estou com dificuldade em dois exercícios. 
Nesse primeiro tenho que fazer com que a função retorne a quantidade de meses que houveram lucro, ou seja, `2`. Entretanto, ele está considerando o número `0`, acredito eu, e está retornando `3`.

```
function quantidadeDeMesesComLucro(umPeriodo) {
  let quantidade = 0;
  for (let mes = 0; mes < umPeriodo.length; mes++) {
    if (umPeriodo[mes] > 0) {
    quantidade = mes;
    }
  }
  return quantidade;
}
console.log(quantidadeDeMesesComLucro([0, 3, -1, 5]));
```

Já neste segundo exercício, tenho que fazer com que a função retorne o saldo dos meses em que foram positivos, ou seja `[3, 5]`. Entretanto, ele está considerando todos os meses, independetemente do saldo, ou seja `[0, 3, -1, 5]`.

```
function saldoDeMesesComLucro(saldo) {
  let lucro = 0;
  for (let mes = 0; mes < saldo.length; mes++) {
    if (saldo[mes] > 0) {
    lucro = saldo;
    }
  }
  return lucro;
}
console.log(saldoDeMesesComLucro([0, 3, -1, 5]));
```

Não sei o que estou fazendo de errado, tendo em vista que a condicional está programada para considerar apenas os números acima de `0`.

**Comment by rjcjunior** [comment]
Olá, @cruzmah.

Então no primeiro código, o problema é que vc está atribuindo a posição do array na variável "quantidade". Ou seja, qnd ele passa pelo numero 5 que se encontra na posição 3 do array, ele atribui o valor 3 para a variável quantidade. Uma forma de resolver isso é trocar o "quantidade = mes" pela sentença "quantidade += 1". Portanto, cada vez que ele entra na condição, ele vai somar o valor 1 na quantidade.

No segundo código, o problema é que na condição vc atribui o retorno ao array passado pelo parâmetro, portanto ele sempre vai retornar o array original. Uma forma de resolver isso é transformar a variável lucro em um array vazio e cada vez que entrar na condição vc dá um push do saldo[mes] no array lucro.

**Comment by cruzmah** [comment]
> Olá, @cruzmah.
> 
> Então no primeiro código, o problema é que vc está atribuindo a posição do array na variável "quantidade". Ou seja, qnd ele passa pelo numero 5 que se encontra na posição 3 do array, ele atribui o valor 3 para a variável quantidade. Uma forma de resolver isso é trocar o "quantidade = mes" pela sentença "quantidade += 1". Portanto, cada vez que ele entra na condição, ele vai somar o valor 1 na quantidade.
> 
> No segundo código, o problema é que na condição vc atribui o retorno ao array passado pelo parâmetro, portanto ele sempre vai retornar o array original. Uma forma de resolver isso é, inicialmente, declarar a variável lucro como um array vazio e cada vez que entrar na condição vc dá um push do saldo[mes] no array lucro.

Olá, @rjcjunior obrigado pela ajuda e esclarecimentos. Consegui resolver o primeiro código exatamente da forma como me orientou. Entretanto, ainda estou com dificuldade no segundo código, não sei se consegui pegar o raciocínio. De qualquer forma, fiz da seguinte forma:

```
function saldoDeMesesComLucro(saldo) {
  let lucro = [];
  for (let mes = 0; mes < saldo.length; mes++) {
    if (saldo[mes] > 0) {
    lucro = lucro.push(saldo[mes]);
    }
  }
  return lucro;
}
console.log(saldoDeMesesComLucro([0, 3, -1, 5]));
```

Como estou usando a plataforma de um curso, a mensagem de erro que aparece é: `lucro.push` is not a function"

**Comment by felquis** [comment]
Eu resolveria isso com [filter](https://youtu.be/pC_I2So6KV4?t=70)
```js
function saldoDeMesesComLucro (saldo) {
  return saldo.filter(x => x > 0)
}

saldoDeMesesComLucro([0, 3, -1, 5]) 
// retorna [3, 5]
```
Mas compreendo a necessidade de se aprender for loops.

>  lucro.push is not a function"

O motivo deste erro, é que Array.push(1) [retorna o length do array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push#:~:text=Return%20value). Se você usa o push vc não pode reescrever o array original como vc fez dentro do if, só usar o push já basta em seu caso.
```js
if (saldo[mes] > 0) {
    lucro.push(saldo[mes]);
}
```

Você também tem a alternativa de fazer assim: [spread operator](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/Spread_operator#:~:text=Um%20literal%20array%20mais%20poderoso)
```js
if (saldo[mes] > 0) {
    lucro = [...lucro, saldo[mes]];
}
```

👍 boa sorte.

**Comment by rjcjunior** [comment]
@cruzmah 
Isso, o problema é exatamente o que o @felquis  comentou.

Uma dica usando javascript é que qualquer navegador roda ele. Então mesmo usando a plataforma desse curso, uma alternativa para vc ir testando seu código é abrir o console do navegador e rodar seu código por ele. Para entender melhor como ele funciona vc pode colocar alguns pontos de debugger ou criar alguns snippets com o navegador para colocar breakpoints em partes especificas.

Segue alguns conteúdos, explicando como fazer:

https://developers.google.com/web/tools/chrome-devtools/javascript/breakpoints?hl=pt-br
https://www.devmedia.com.br/depurando-javascript-com-google-chrome/28367
https://developers.google.com/web/tools/chrome-devtools/javascript/snippets?hl=pt-br
https://developers.google.com/web/tools/chrome-devtools/javascript?hl=pt-br

**Comment by cruzmah** [comment]
@felquis e @rjcjunior, vocês são fodas (se não puder palavrão me avisem que eu edito rs). Resolvi exatamente como o Felx disse, usando apenas o push.

```
function saldoDeMesesComLucro(saldo) {
  let lucro = [];
  for (let mes = 0; mes < saldo.length; mes++) {
    if (saldo[mes] > 0) {
    lucro.push(saldo[mes]);
    }
  }
  return lucro;
}
console.log(saldoDeMesesComLucro([0, 3, -1, 5]));
```

Mais uma vez muito obrigado pela ajuda e orientações.
