### ISSUE TITLE
PHP 7 Dúvida  ? Socorro  !!!

### ISSUE THREAD

**Issue by evertonProgramadorCriativo** [frontendbr/forum#1823]
Eu estou precisando de ajuda , por que eu baixei o projeto do curso para comparar com o meu , e o projeto do professor está dando vários erros , eu gostaria que alguém testa_se o projeto em sua máquina, para eu ter certeza que o problema é a minha máquina ou o projeto do professor

https://github.com/hcodebr/ecommerce

**Comment by djhanlj** [comment]
opa Everton baixei na minha maquina e na tela inicial já encontro esses erros!

![image](https://user-images.githubusercontent.com/4240212/84578572-e1062080-ad9c-11ea-8e1c-4840380e80cd.png)

**Comment by evertonProgramadorCriativo** [comment]
Na minha tela também

**Comment by djhanlj** [comment]
Não investiguei a fundo mas acredito que está faltando algo, verifica com o professor do seu curso, desculpa ae por não ajudar muito.

**Comment by evertonProgramadorCriativo** [comment]
O professor do curso da Hcode , eu estou perguntando isso a 1 ano e ele nao responde  a pergunta  sobre o funcionamento do ecommerce   , ja falei para ele que o projeto esta com defeito,  e o professor falou que esta tudo certo , o professor demora  de 1 semana a 2 semanas para responde as minhas perguntas agora !!!! e quando responde !!! ai vai ter gente que vai falar que e por que tem muitas perguntas e por isso ele demora  , ser for assim normal   demora quase 2 semanas para responde  , que o projeto final  que o professor fez esta com erros   e todo bugado 
 , os outros cursos responde no mesmo  dia , eu comprei esse curso php 7 HCode  na udemy

**Comment by felipefialho** [comment]
@evertonProgramadorCriativo O foco aqui é bem Front-end ou stacks aproximadas envolvendo JavaScript. 

Sobre PHP sugiro perguntar no grupo @backend-br, vão poder ajudar melhor.
