### ISSUE TITLE
Alteração de CSS do html5up

### ISSUE THREAD

**Issue by brauliocaleb** [frontendbr/forum#1833]
Olá. Estou personalizando um Layout baixado do html5up, mas estou preso em um problema. No footer não consigo usar mais do que duas colunas. Já fiz alterações no CSS original e não consegui. Já criei um CSS a parte para tentar e nada. Segue a baixo trechos do html e css. Agradeço a ajuda
HTML:

				<section id="footer" class="wrapper">
					<div class="title">xxx</div>
					<div class="container">
						
						<div class="row">
							<div class="col-12 col-12-medium">

								
									<section class="feature-list small">
										<div class="row">
											<div class="col-6 col-12-small">
												<section>
													<h3 class="icon solid fa-home">xxx</h3>
													<p>
														xxx<br />
														xxx<br />
														xxx
													</p>
												</section>
											</div>
											
											<div class="col-6 col-12-small">
												<section>
													<h3 class="icon solid fa-comment">xxx</h3>
													<p>
														<a href="xxx">xxx</a><br />
														<a href="xxx">xxx</a><br />
														<a href="xxx">xxx</a>
													</p>
												</section>
											</div>
											<div class="col-6 col-12-small">
												<section>
													<h3 class="icon solid fa-envelope">xxx</h3>
													<p>
														xxx
													</p>
												</section>
											</div>
											<div class="col-6 col-12-small">
												<section>
													<h3 class="icon solid fa-phone">xxx</h3>
													<p>
														xxx
													</p>
												</section>
											</div>
											<div class="col-6 col-12-small">
												<section>
													<h3 class="icon solid fa-heart">xxx</h3>
													<p>
														xxx<br />
														xxx<br />
														xxx<br />
														xxx
													</p>
												</section>
											</div>
										</div>
									</section>
								

							</div>
						</div> 
						<div id="copyright">
							<ul>
								<li>&copy; Cxxxx</li><li>xxxx</li>
							</ul>
						</div>
					</div> 
				</section>

		</div>

CSS:
/* Feature List */

	.feature-list {
		max-width: 58em;
		margin-left: auto;
		margin-right: auto;
		position: relative;
		top: 0.75em;
	}

		.feature-list section {
    border-top: solid 1px #eee;
    padding-top: 3em;
    padding-left: 5em;
    position: relative;
		}

		@media screen and (min-width: 981px) {

			.feature-list > .row > :nth-child(-n + 2) > section {
				border-top: 0;
				padding-top: 0;
			}

		}

		.feature-list h3 {
    color: #e97770 !important;
    margin: -0.35em 0 0.75em 0;
    font-size: 1.15em;
    letter-spacing: 0.05em;
		}

			.feature-list h3:before {
				display: block;
				color: #fff;
				background: #2f333b url("images/overlay.png");
				border-radius: 2.5em;
				text-align: center;
				width: 2.5em;
				height: 2.5em;
				line-height: 2.5em;
				margin-right: 0.75em;
				position: absolute;
				left: 0;
				margin-top: -0.5em;
			}

		.feature-list.small section {
    padding-left: 3.5em;
		}

		.feature-list.small h3:before {
			font-size: 0.8em;
		}

**Comment by theandersonn** [comment]
@brauliocaleb No css que você incluiu não o referente as colunas do grid.

Exemplo:
col-6 col-12-small

Partindo do principio que o grid tem 12 colunas e você a col-6 então tem 2 divisões, se você colocar três seções como col-4, não consegue por exemplo dividir em três partes?

**Comment by brauliocaleb** [comment]
> @brauliocaleb No css que você incluiu não o referente as colunas do grid.
> 
> Exemplo:
> col-6 col-12-small
> 
> Partindo do principio que o grid tem 12 colunas e você a col-6 então tem 2 divisões, se você colocar três seções como col-4, não consegue por exemplo dividir em três partes?

Consegui resolver eliminando os <section></section>. Valeu!
