### ISSUE TITLE
 Aplicação JavaScript no console do Chrome para automação de sites

### ISSUE THREAD

**Issue by Felipetrevizam** [frontendbr/forum#1835]
Estou tentando aplicar um código em um site que contem uma box com um numero que fica variando e dois botões. Preciso de um código que leia o que esta na box e após isso aperte um dos botões.

**Comment by theandersonn** [comment]
@Felipetrevizam Para facilitar o entendimento da sua dúvida e que mais pessoas possam lhe ajudar. Por favor poste o código que você está com a dúvida e em que ponto específico você ficou travado.

**Comment by Felipetrevizam** [comment]
var precos = [];
var i;

while (true)

for (i = 0; i < 5; i++)
{
precos[i] = **document.querySelectorAll('.strike-button-price');**
}
      
    if (precos[0] = precos[1] + '1')
        {
       if (precos[1] = precos[2] - '1')
          {
            if (precos[2] = precos[3] + '1')
            {
            if (precos[3] = precos[4] - '1')
                {
                **document.querySelector('.strike-button-price');**
                    {
                if (**item.inneText == precos[4]**)
                  {
                        **document.querySelectorAll('.deal-buttons-up');**
                            {                       
                  **item.click();**
                            }
                }
                        else                         
                        {
                        **document.querySelectorAll('.deal-button-down');**
                            {
                            **intem.click();**
                            }
                        }
                    }              
                }            
            }             
          }        
        }


Essa foi a lógica que eu criei, creio que esteja errado as partes destacadas.
strike-button-price é a box onde o número fica variando.
deal-button-down e deal-button-up Sao os botoes.

**Comment by felquis** [comment]
[Essa página ](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events) explica como criar eventos customizados, ou emitir um evento nativo como o click entre outros.

Para pegar o texto de um elemento, é melhor usar o [textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent)

Algo que eu faço para interar sobre todos os elementos do [querySelectorAll](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll) é usar o [Array.from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from)

Um exemplo hipotético
```js
let todosOsElementos = Array.from(document.querySelectorAll('.strike-button-price .single-price'))

let todosOsPrecos = todosOsElementos.map((elemento) => {
  let price = elemento.textContent

  // faz algo com o price, exemplo emitir o click para o elemento

  return price
})

// todosOsPrecos agora contem apenas o texto de cada elemento selecionado pelo seletor na linha 1
```

Algo que você pode tirar vantagem é o [parentElement](https://developer.mozilla.org/en-US/docs/Web/API/Node/parentElement) e também uso bastante o [console.dir](https://developer.mozilla.org/en-US/docs/Web/API/Console/dir) quando preciso analisar o prototype de algo.

Outra técnica boa, é dividir o código em partes pequenas, para garantir que cada parte dele está fazendo o que você quer que seja feito.

Espero que isso te de alguma ajuda 👍
