### ISSUE TITLE
Duvida com axios e async await

### ISSUE THREAD

**Issue by jrosetim** [frontendbr/forum#1842]
Bom dia, tenho um interface, e um useState com o tipo dessa interface,
quando estou utilizando o setUserDataApi, não consigo recuperar o valor que preciso
estou usando o axios para buscar os dados de uma API própria!
segue abaixo um pouco do código!

```
interface userData{
  useremail: string,
  userpassword: string
}

const [userDataApi, setUserDataApi] = useState<userData>();

  async function handleSubmitLogin(event: FormEvent) {
    event.preventDefault();

    await api.get(`/users/${userEmail}`).then( (resolve) =>{
      setUserDataApi({ ...resolve.data });
      
      console.log(resolve.data) // aqui funciona, tem o ibeto json com os valor que preciso usar
    });

    // mesmo usando o setUserData as linhas abaixo não mostram valor, ficam como undefined
    console.log(`email ${userDataApi?.useremail}`)
    console.log(`password ${userDataApi?.userpassword}`)
  };

```

**Comment by highlabs** [comment]
Se não me engano, como você esta usando o `.then` no axios, não precisa do async/await:

```
  async function handleSubmitLogin(event: FormEvent) {
    event.preventDefault();

    const resolve = await api.get(`/users/${userEmail}`)

    setUserDataApi({ ...resolve.data });

    // mesmo usando o setUserData as linhas abaixo não mostram valor, ficam como undefined
    console.log(`email ${userDataApi?.useremail}`)
    console.log(`password ${userDataApi?.userpassword}`)
  };
```

Acho que o problema pode estar aqui: `setUserDataApi({ ...resolve.data });`
se o seu useState esta assim: `const [userData, setUserData] = useState(null)`, pode poderia testar fazer somente um: `setUserDataApi(resolve.data);`

Pois o seu `data` já deve ser um `object`. Pra tirar essa dúvida, faz um:

```
  async function handleSubmitLogin(event: FormEvent) {
    event.preventDefault();

    const resolve = await api.get(`/users/${userEmail}`)

    setUserDataApi({ ...resolve.data });

    console.log(resolve) // pra verificar o retorno do axiso
    console.log(userDataApi) // para verificar o que esta gravado no seu state
  };
```

**Comment by gabriel-hahn** [comment]
Fala @jrosetim. Complementando o que o @highlabs comentou, acredito que o problema maior é você atualizar o state e já querer acessar o valor do `userDataApi` em seguida, pois como a atualização do state é assíncrona, esse valor não vai estar disponível para você logo em seguida no corpo da função. Uma dica seria utilizar o valor retornado da API para as validações que você quer fazer e deixar a atualização do state por último para então renderizar teu componente sem problemas e com o valor correto.

**Comment by jrosetim** [comment]
@highlabs  testei o que vc me passou e continuou igual, mas intendi o que acontece coma explicação do @gabriel-hahn realmente eu estava querendo fazer o que ele disse, acessar a informação logo após passar o valor, mas como ele explicou o setState é assincrono, então não tenho esse valor. consegui intender o funcionamento do setState com essa sua explicação @gabriel-hahn 

Muito Obrigado pela Ajuda @gabriel-hahn  @highlabs
