### ISSUE TITLE
Alterar o Texto HTML Usando JavaScript

### ISSUE THREAD

**Issue by brozmado** [frontendbr/forum#1843]
Olá, estou tentando alterar um texto (Televendas) Para (Contato) incorporado no HTML com DOM Javascript mas sem sucesso!! segue abaixo a estância do que eu fiz:

```
if(document.querySelector(".header-links .container div.col-sm-6 col-xs-12: a")){
    //ALTERA TEXTO TELEVENDAS PARA SIA
    document.querySelector(".header-links .container div.col-sm-6 col-xs-12: a").innerText = "CONTATO";
}
```

![codigo](https://user-images.githubusercontent.com/67505980/85921862-bc5a8000-b855-11ea-850c-65f7214e15c3.png)

Alguém pode me dá uma luz..

**Comment by brozmado** [comment]
`/** Codigo Html **//
<div class="header-top">
            <div class="container">				
             <div class="row">				
             <div class="col-sm-6 col-xs-12">
           <div class="header-links">
            <ul class="nav navbar-nav pull-left hidden-xs">
             <li id="template_menuMinhaConta">
             <a href="http://vulcaodaborracha.softsystem.net/identificacao/minhaConta/minhaConta.jsp#areaParceiros">
                <i class="fa fa-user" title="" data-original-title="Minha Conta"></i>
                  <span> Minha Conta </span>
                     </a>
                        </li>
                          <li id="template_menuCadastreSe">
                             <a href="http://vulcaodaborracha.softsystem.net/identificacao/pessoa.jsp#areaParceiros">
                                <i class="fa fa-unlock" title="" data-original-title="Cadastre-se"></i>
                    <span>Cadastre-se</span>
                     </a>
                        </li>
                         <li id="template_menuLogin">
                           <a href="http://vulcaodaborracha.softsystem.net/identificacao/login.jsp#areaParceiros">
                            <i class="fa fa-lock" title="" data-original-title="Login"></i>
                  <span>Login</span>
                     </a>
                      </li>
                      </ul>									
               </div>
           </div>		
                <div id="template_foneTelevendas" class="col-sm-3 col-xs-12 header-fone hidden-xs header-links">
              <i class="glyphicon glyphicon-phone-alt"></i> <a href="tel:06130128750">Televendas: &nbsp;<span>61 3012-8750</span></a>
                </div> 
                <div id="template_foneSAC" class="col-sm-3 col-xs-12 header-fone hidden-xs header-links">
                 <i class="glyphicon glyphicon-phone-alt"></i> <a href="tel:06133513322">Fale Conosco: &nbsp;<span>61 3351-3322</span></a>                                                                
               </div> </div> </div> </div>

/** Codigo Html **//
`

**Comment by lucasferreiralimax** [comment]
Olá tudo bem?
Você poderia reduzir esse seletor e também fazer a seleção apenas uma vez

```javascript
let linkContato = document.querySelector("#template_foneTelevendas a");

if(linkContato){
  linkContato.innerText = "Contato:";
}
```

Exemplo rodando online - https://jsfiddle.net/lucaslimax/hf8yaojs

E o erro do seu selector talvez seja a classe de coluna sem o ponto e os dois pontos após a mesma classe.

**Comment by felquis** [comment]
- Use o JavaScript no final do arquivo HTML conheça o [DOMContentLoaded](https://developer.mozilla.org/pt-BR/docs/Web/Events/DOMContentLoaded)
- Certifique-se de que está encontrando o elemento no DOM com [console.dir](https://developer.mozilla.org/pt-BR/docs/Web/API/Console/dir)
- Sempre uso [textContent](https://developer.mozilla.org/pt-BR/docs/Web/API/Node/textContent) para alterar textos.
