### ISSUE TITLE
Lentidão ao execultar projetos React 

### ISSUE THREAD

**Issue by LuisMatheus-dev** [frontendbr/forum#1866]
Olá , estou iniciando no react , e sigo alguns projetos e tutorias utilizando ele, e algo que sempre me deixou em dúvida é porque meus projetos React não seguem o mesmo dinamismo que os videos que vejo, sempre que executo uma alteração preciso reiniciar o server ,e inicia-lo novamente e nesse meio tempo demora no minimo 3 minutos , embora meu computador seja básico , não faz sentido demorar tanto , as vezes é uma frase ou letra e o processo é o mesmo kkk 
Alguma sugestão para melhorar essa performance ?

**Comment by gabriel-hahn** [comment]
Buenas @LuisMatheus-dev . Tu usou `create-react-app` para criar este teu projeto? Ou configurou todos os arquivos do zero? Realmente você não deveria esperar tanto tempo após uma alteração não, pois na maioria dos casos (mesmo em computadores mais antigos/lentos) a atualização é quase instantânea após subir o projeto uma primeira vez em modo desenvolvimento. Consegue passar mais detalhes de como o projeto está estruturado? O `package.json` também. Abraço.

**Comment by ninetails** [comment]
Em modo de desenvolvimento, o React fica "olhando" os arquivos que mudam para atualizar no navegador. Também é necessário estar rodando um servidor só pra esse desenvolvimento e acessá-lo via navegador. Normalmente chamado de _DevServer_ e a funcionalidade, _Live Reload_ ou as variações como _Hot Module Replacement_, _Hot Reloading_....

Como o @gabriel-hahn falou, caso seja `create-react-app` vc tá rodando o comando de `start` e depois acessando o teu site no navegador pela URL passada, geralmente `http://localhost:3000/`? É necessário ter o `Node.js` instalado na máquina para rodá-lo.

**Comment by LuisMatheus-dev** [comment]
@gabriel-hahn Para instala-lo utilizei o create-react-app, @ninetails estou rodando localmente mesmo, pelo server que vem configurado na instalação, deixo abaixo meu _ package.json_
```
{
  "name": "streamdev",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "styled-components": "^5.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```
Algo que não me mencionei é que o reload não funciona de maneira alguma não só no react , em qualquer projeto node ,seja nodemon, live-server e etc 
Ele só inicia a primeira vez e como citei preciso sempre reiniciar para as mudanças

**Comment by ninetails** [comment]
@LuisMatheus-dev Rola algum erro ao deixar o _DevServer_ do _create-react-app_ rolando? Supondo que esteja no Linux, [algo como **ENOSPC**](https://stackoverflow.com/questions/22475849/node-js-what-is-enospc-error-and-how-to-solve)?

Ou algum outro erro? Se não for o erro acima, não saberei muito ajudar mas...  está rodando em algum SO específico? Seu usuário tem permissão de leitura e escrita na pasta? Qual a formatação do drive que c tá utilizando? Pq em teoria o SO deveria notificar alterações realizadas em disco... ou gerar um erro.

**Comment by LuisMatheus-dev** [comment]
@ninetails não há problema ou erros apresentados ele simplesmente não atualiza meus arquivos quando modificado

**Comment by ninetails** [comment]
@LuisMatheus-dev vc está no Windows, certo?

Tem uma thread rolando sobre isso que talvez seja pertinente (e ainda não tem resolução)

> https://github.com/microsoft/WSL/issues/4739

Se vc tá desenvolvendo rodando o VSCode pelo Windows, diria pra tentar instalar e rodar uma instância do VSCode direto do WSL

Aí se isso não for a resolução, não faço muito idéia de como ajudar...

**Comment by LuisMatheus-dev** [comment]
@ninetails Talvez eu nunca saberia que o WSL que estava causando a lentidão, se não fosse por você kkk , 
Dei uma lida na discussão do link que você colocou ([aqui](microsoft/WSL#4739)) , e um dos comentarios serviram para achar a resposta , [nesse post](https://github.com/microsoft/WSL/issues/4739#issuecomment-656551450), 

simplificando eu movi a minha pasta de Projetos para o sistema de arquivos no linux `\\wsl$` você consegue abrir esse diretório entrando na `$HOME` no terminal linux e digitando` explorer.exe .` (**com o ponto**)  

Aumentando a performance de 3 minutos para 30 segundos , o que para min mudou da aguá para vinho , porque além disso consigo ter as modificações dos arquivos dinamicamente, vlww denovo @ninetails 

Deixo o [post ](https://docs.microsoft.com/pt-br/windows/wsl/compare-versions) detalhado da microsoft sobre os passos citados

**Comment by guilhermesantoss** [comment]
Bom saber que conseguiu resolver seu problema, realmente o WSL veio para transformar o desenvolvimento com o SO Windows, mas tem muita coisa a ser melhorada.

@ninetails é fera demais

**Comment by ninetails** [comment]
Opas, boas! Melhor ainda que conseguiu integração usando o _Remote WSL_ :D

E deixo os parabéns pro @LuisMatheus-dev por ter deixado a explicação pra caso alguém ache esse tópico num futuro (ou dependendo, até lá podem ter resolvido essa _issue_ rs)

@guilhermesantoss tamos ae na comunidade pra se ajudar po auehuaeha mas tem galera bem mais fera por aqui rs... E se n fosse esse o erro tb nem saberia como ajudar, como citado lá em cima :\

E mesmo se for pegar desenvolvimento js, sempre tem momentos que a gente esquece de usar [cross-env](https://www.npmjs.com/package/cross-env) ou ferramentas semelhantes que auxiliam tal portabilidade para quem está desenvolvendo no Windows... mas concordo que "até que enfim" veio o WSL uaehuaehueah mesmo que ainda esteja em desenvolvimento... e a gente acaba sempre assumindo erroneamente que a galera tá no Linux/macOS.

**Comment by LuisMatheus-dev** [comment]
@guilhermesantoss realmente foi uma sacada ótima da microsoft, o motivo de não ter instalado simplesmente o linux como SO principal , foi porque utilizo muito os softwares da Adobe e outros que só tem suporte para windows e mac, e instalar uma maquina virtual pra min não era nada pratico. @ninetails Que isso kkk, mas realmente tem muito a ser trabalhado

**Comment by wellerychaves** [comment]
Cheguei a conclusão de que o React no Windows é lento graças ao Windows Defender e/ou Windows Search, CRA cria milhares de arquivos e o Windows Defender e/ou Windows Search analisa um por um, o que deixa o processo lento até para atualizar um detalhe na página.
A solução mais fácil é fazer CRA **dentro** do disco virtual pois o Windows Defender não analisa o que está acontecendo.
Recomendo WSL caso não queira usar o SO linux por completo.

**Comment by theolivertree** [comment]
Só queria vir aqui deixar o meu agradecimento a todo mundo que ajudou. Estou aprendendo React e agora ele atualiza instantaneamente por causa da solução de vocês. Obrigado galera!
