### ISSUE TITLE
Emissão de Nota Fiscal para o exterior

### ISSUE THREAD

**Issue by tioola** [frontendbr/forum#1880]
Olá Pessoal,

Estou trabalhando remotamente para o exterior e emitindo notas através da empresa que abri no Brasil, porém estou tendo divergência de informações com relação a meu contador e o contador de outros desenvolvedores que estão na mesma situação. Gostaria de saber se vocês emitem a nota fiscal juntamente com a invoice ou somente no recebimento pelo serviço? Caso seja juntamente com a invoice como vocês lidam com a diferença cambial?

Muito obrigado desde ja!

**Comment by juliovedovatto** [comment]
Já deu uma olhada aqui @tioola ? 

https://github.com/DyegoCosta/trabalhando-remoto/issues

Acabou virando um repositório de informações sobre trabalho remoto.

**Comment by tioola** [comment]
Muito obrigado, Julio

Acredito que este link seja um local melhor para minha pergunta.

Valeuu!!
