### ISSUE TITLE
Ajuda com Python Opencv

### ISSUE THREAD

**Issue by Kauan589** [frontendbr/forum#1883]
Pessoal, sou novo em programação e estou tentando criar um programa para detectar cores de uma imagem utilizando opencv. Eu gostaria de selecionar o range da cor a ser detectada através de trackbars. Eu consegui criar as trackbars, porém quando eu vario os valores das trackbars, nada muda na máscara que eu criei. Segue meu código:

 import cv2
import numpy as np

def nothing(x):
    pass

img = cv2.imread("Escala.PNG")

hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

cv2.namedWindow('trackbars')

cv2.createTrackbar('lb', 'trackbars', 0, 255, nothing)
cv2.createTrackbar('lg', 'trackbars', 0, 255, nothing)
cv2.createTrackbar('lr', 'trackbars', 0, 255, nothing)
cv2.createTrackbar('ub', 'trackbars', 0, 255, nothing)
cv2.createTrackbar('ug', 'trackbars', 0, 255, nothing)
cv2.createTrackbar('ur', 'trackbars', 0, 255, nothing)

while (True):
    lb = cv2.getTrackbarPos('lb', 'trackbars')
    lg = cv2.getTrackbarPos('lg', 'trackbars')
    lr = cv2.getTrackbarPos('lr', 'trackbars')
    ub = cv2.getTrackbarPos('ub', 'trackbars')
    ug = cv2.getTrackbarPos('ug', 'trackbars')
    ur = cv2.getTrackbarPos('ur', 'trackbars')

    lower_range = np.array([lb,lg,lr])
    upper_range = np.array([ub,ug,ur])

    mask = cv2.inRange(hsv, lower_range, upper_range)

    cv2.imshow('Imagem', img)
    cv2.imshow('Mask', mask)

    if cv2.waitKey(1) & 0xFF == ord('s'):
        break

cap.release()
cv2.destroyAllWindows()

**Comment by felipefialho** [comment]
Obrigado pela ajuda @gustavocarmoh, mas essa é uma dúvida de linguagem backend @Kauan589, sugiro postar no @backend-br
