### ISSUE TITLE
Duvida com condição if

### ISSUE THREAD

**Issue by L43RC10** [frontendbr/forum#1900]
Pessoal, estou com um problema nesse if.. quero fazer um programa q faça a média de notas trimestrais de um ano.. a ideia é q a condição só deixe passar o código se os 4 inputs estiverem preenchidos, mas o if esta deixando passar com apenas 1 input preenchido e o restante vazio... a baixo segue o cód.

Estou começando os estudos com javascript agr pessoal, as questões q vou postar aqui serão bem basicas msm por um tempo, se puderem me ajudar serei realmente grato

`
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exercicio 006</title>
    <style>body{font: normal 15px arial;}</style>
</head>
<body>

    <h1>Exercicio 006</h1>

    <input type="number" placeholder="Primeiro" name="bim1" id="bim1">
    <input type="number" placeholder="Segundo"  name="bim2" id="bim2">
    <input type="number" placeholder="Terceiro"  name="bim3" id="bim3">
    <input type="number" placeholder="Quarto"  name="bim4" id="bim4">
    <input type="button" value="Calcular" onclick="calc()">

    <div id="res"></div>
    
    <script>
        function calc(){
            let pri = document.querySelector('input#bim1');
            let seg = document.querySelector('input#bim2');
            let ter = document.querySelector('input#bim3');
            let qua = document.querySelector('input#bim4');
            
            if(pri.value.length == '' && seg.value.length == '' && ter.value.length == '' && qua.value.length == ''){
                res.innerHTML = 'Digite um valor válido para todos os campos!';
            } else {
                res.innerHTML = 'Teste Ok!';
            }    
        }
    </script>
</body>
</html>
`

**Comment by Rafa-MKR2** [comment]
Olá, fiz algumas correções que funcionaram, basicamente vc teria que colocar nome real dos Id's nos metodos querySelector 
  na hora de capturar elemento. Outro detalhe importante substituir operador logico && para || pois este serve para verifica cada 
  condição separadamente caso uma delas retorne true dispararia evento em questão.  Espero ter ajudado qualquer duvida 
  retorne contato. Bons estudos !!

<h1>Exercicio 006</h1>

    <input type="number" placeholder="Primeiro" name="bim1" id="bim1">
    <input type="number" placeholder="Segundo"  name="bim2" id="bim2">
    <input type="number" placeholder="Terceiro"  name="bim3" id="bim3">
    <input type="number" placeholder="Quarto"  name="bim4" id="bim4">
    <input type="button" value="Calcular" onclick="calc()">

    <div id="res"></div>
    
    <script>
        function calc(){
            let pri = document.querySelector('#bim1');
            let seg = document.querySelector('#bim2');
            let ter = document.querySelector('#bim3');
            let qua = document.querySelector('#bim4');
            
            if(pri.value == '' || seg.value == '' || ter.value == '' || qua.value == ''){
                res.innerHTML = 'Digite um valor válido para todos os campos!';
            } else {
                res.innerHTML = 'Teste Ok!';
            }
            
        }
    </script>
</body>

**Comment by L43RC10** [comment]
Perfeito Rafa, funcionou certinho agr
Muito obrigado pela ajuda!

**Comment by Rafa-MKR2** [comment]
Fico feliz em ajuda, não esqueça de fechar aqui sua duvida. :)
