### ISSUE TITLE
Duvida com redirecionamento: window.location.href = "login.html";

### ISSUE THREAD

**Issue by L43RC10** [frontendbr/forum#1903]
**Boa noite, estou com problemas com o recurso de redirecionamento de pagina ao usar o window.location.href = "login.html";**

`
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sistema de login</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <style>
            *{box-sizing: border-box;}
            body{margin: 0; padding: 0; background-color: #333;}
            .login-form {
                width: 350px; 
                background-color: #F8F8FF; 
                margin-top: 120px; 
                border-radius: 5px; 
                padding: 20px;}
            button{width: 100%;}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <form class="container login-form">
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Email">
                        <small id="emailHelp" class="form-text text-muted">Nunca compartilharemos seu e-mail.</small>
                    </div>
                    <div class="form-group">
                        <label for="pass">Senha</label>
                        <input type="password" class="form-control" id="pass" placeholder="Senha">
                    </div>
                    <div class="form-group form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Check me out</label>
                    </div>
                    <button onclick="logar()" id="btn" class="btn btn-primary">Login</button>
                </form>
            </div>
        </div>

        <script>
            function logar(){
                var email = document.getElementById('email');
                var pass = document.getElementById('pass');

                console.log(email.value+pass.value);

                if(email.value == "admin@admin.com" && pass.value == "admin"){
                    alert('Logado!');
                    localStorage.setItem("acesso", true);

                    window.location.href = "login.html";
                } else {
                    alert("Usuário ou senha inválidos!");
                }
            }
        </script>
    </body>
</html>
`

**Quero que ao ser efetuado o login, o usuario seja redirecionado para a pagina abaixo, que esta intitulada como 'login.html':**

`
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sistema de login</title>
    </head>
    <body>
        
            <h1>LOGADO!</h1>
    
    </body>
</html>
` 

**Se puderem me ajudar com essa questão serei muito grato**

**Comment by iaurg** [comment]
E ai @L43RC10 beleza?

Qual o link que você usa para acessar sua página normalmente? Apresenta algum erro quando você tenta fazer esse redirect?

**Comment by L43RC10** [comment]
Tranquilo @iaurg,
então quando eu faço o login com os dados corretos ao invés de direcionar para o arquivo index.html ele recarrega a pagina atual, q é a do arquivo login.html.. Tirando isso o devtools não aponta erro nenhum, o alert aponta q foi realizado o login, o único problema é q não esta direcionando para a o arquivo index.html

**Comment by Rafa-MKR2** [comment]
Olá, tudo bem? 
Pra resolver esse problema do formulário recarregar a pagina antes da execução do do seu evento, você deve adicionar esse trecho de código na sua Tag de formulário 


  <form  onsubmit="return false;">

com isso você estará impedindo que formulário continue á executar esse evento padrão de recarregar pagina. 
Espero ter ajudado. qualquer duvida retorne contato  :)

**Comment by L43RC10** [comment]
E ae @Rafa-MKR2, só de boas,
o jeito q vc falou funcionou mano..  eu pesquisando achei uma outra forma tb de colocar o return false no onclick no button, ficando assim:
`<button onclick="logar(); return false" id="btn" class="btn btn-primary">Login</button>`

então na vdd o problema estava no form, seria isso msm?

**Comment by yEuzy** [comment]
> Olá, tudo bem? Pra resolver esse problema do formulário recarregar a pagina antes da execução do do seu evento, você deve adicionar esse trecho de código na sua Tag de formulário
> 
> ` <form onsubmit="return false;">`
> 
> com isso você estará impedindo que formulário continue á executar esse evento padrão de recarregar pagina. Espero ter ajudado. qualquer duvida retorne contato :)

cara vc me ajudou pra crl
