### ISSUE TITLE
Sobre o GraphQL 

### ISSUE THREAD

**Issue by leocavalcante** [frontendbr/forum#191]
O que o pessoal de front-end acha do [GraphQL](http://graphql.org/)?
Interessante essa abordagem de trazer uma query language pro client-side?
Ruim? Trará uma sobrecarga pras respondibilidades no front-end?
Ou é interessante ter esse controle e flexibilidade sobre a estrutura de dados no lado da UI?

**Comment by rafaelverger** [comment]
Summon @rodrigopr

**Comment by leonardoelias** [comment]
Acho muito valido toda essa 'sobrecarga' que está tendo, antes se via muito 'cada um cuida do seu', hoje está muito mais, time. Acho que todo mundo sai ganhando com esse tipo de abordagem.

A minha duvida seria, o quanto e performático o GraphQL.

**Comment by evansantos** [comment]
Alô Alô @igorapa, ajuda nois

**Comment by leocavalcante** [comment]
Tenho dois pontos sobre performance, mais sobre o roundtrip client-server do que a implementação do GraphQL.

1. Com um controle maior da estrutura na UI, você pode eliminar campos que não estão sendo mais utilizados e diminuir o tamanho do documento JSON, reduzindo o stress na network.

2. Dados linkados podem ser obtidos num único roundtrip pro server ao invés de fazer um pra pegar um ID e depois fazer outro pra pegar os detalhes.

Claro que por uma camada de GraphQL no client e no server significa mais processo, mas não acredito que a implementação venha a ser o gargalo numa aplicação. Geralmente é network ou query (no caso do GraphQL um resolver que ainda é responsabilidade do dev, não da biblioteca) não otimizada.

**Comment by leocavalcante** [comment]
:eyes:

**Comment by didiraja** [comment]
3 anos depois. E aí galera, quais suas visões?

**Comment by fdaciuk** [comment]
Esse ano eu comecei a olhar mais a fundo o GraphQL com Gatsby, e curti bastante!

É uma coisa a mais pra aprender? É. Mas é bem mais simples pra galera de front aprender a fazer requests - já que tem uma base parecida com JSON - do que de fato configurar um server GraphQL pra se comunicar com seu banco ou qualquer que seja sua fonte de dados =)

Então só vejo vantagens =)

**Comment by leocavalcante** [comment]
Closed due inactivity.

**Comment by brunooomelo** [comment]
👀

**Comment by leocavalcante** [comment]
![](https://media.giphy.com/media/T5P7bGGVbunmM/giphy-downsized.gif)

**Comment by felipemfp** [comment]
@leocavalcante, issues no forum não são fechadas, man. A não ser que quebrem as regras, etc

**Comment by leocavalcante** [comment]
Isso não faz muito sentido, já fazem 3 anos que a issue foi aberta o GraphQL já nem é mais o mesmo, mas o pior: a issue não tem atividade nenhuma, manter ela aberta não tá contribuindo pra isso mudar.
Numa área tão volátil quanto a nossa, discussões de anos atrás, ainda mais quando se tratam de tecnologia, quanto estão contribuindo para o forum?
Pra não ficar só expondo problema: não seria muito melhor ter uma label GraphQL e ir tagueando as issues referentes? Assim as pessoas encontrariam diversas discussões que podem acontecer de forma granular ao invés de concentrar tudo numa issue só.

Outro ponto, que é o que me faz voltar aqui na verdade, é que as pessoas usam a issue list do GitHub pra organizar suas tarefas; e agora eu tenho uma "tarefa" que nunca mais vai sair da minha lista de tarefas, mesmo que ela esteja velha e sem nenhuma atividade.

**Comment by evertonthepaula** [comment]
> Isso não faz muito sentido, já fazem 3 anos que a issue foi aberta o GraphQL já nem é mais o mesmo, mas o pior: a issue não tem atividade nenhuma, manter ela aberta não tá contribuindo pra isso mudar.
> Numa área tão volátil quanto a nossa, discussões de anos atrás, ainda mais quando se tratam de tecnologia, quanto estão contribuindo para o forum?
> Pra não ficar só expondo problema: não seria muito melhor ter uma label GraphQL e ir tagueando as issues referentes? Assim as pessoas encontrariam diversas discussões que podem acontecer de forma granular ao invés de concentrar tudo numa issue só.
> 
> Outro ponto, que é o que me faz voltar aqui na verdade, é que as pessoas usam a issue list do GitHub pra organizar suas tarefas; e agora eu tenho uma "tarefa" que nunca mais vai sair da minha lista de tarefas, mesmo que ela esteja velha e sem nenhuma atividade.
> 
> [Edit]
> E agora eu acho que tem mais conteúdo sobre fechar a issue do que sobre o tema da issue rsrs

Abra uma issue sobre isso

**Comment by leocavalcante** [comment]
Eu tô tentando fechar essa, você quer que eu abra mais uma? rsrs
Notei também que a discussão sobre REST foi normalmente encerrada, por exemplo: https://github.com/frontendbr/forum/issues/465
