### ISSUE TITLE
DÚVIDA SOBRE HTML E JS / innerHTML usado com FOR substitui o valor na hora da apresentação em div

### ISSUE THREAD

**Issue by samuelpyerry** [frontendbr/forum#1911]
Olá, boa tarde. Preciso de ajuda com algo que está me tirando a paciência. Preciso resolver a seguinte questão:

### **Dentro da div com o id 'resultado', escreva 20x ('Repetição'). De preferencia usando o FOR**
______

Novamente, falando, preciso de ajuda para resolver o seguinte problema acima... Porem quando uso o for, utilizo o .innerHTML para atribuir a div, o valor 'Repetição', eu vi que o for funciona, mas quando atribui o valor a div, ele substitui o valor anterior, ou seja, meio que o valor fica por cima do outro. Vou mandar alguns prints.

O código:
![Screenshot_11](https://user-images.githubusercontent.com/70605944/97190687-cac59380-1784-11eb-96c3-b2e3452cf602.jpg)

O que aparece na div quando executo o código:
![Screenshot_12](https://user-images.githubusercontent.com/70605944/97190689-cbf6c080-1784-11eb-999c-2067b981a1bf.jpg)

E aqui, comprova o que eu disse, que o laço estar funcionando, mas quando o valor estar sendo passado para a div, esse valor é substituído pelo próximo, assim fica apenas um "resultado" na div.
![Screenshot_13](https://user-images.githubusercontent.com/70605944/97190690-cc8f5700-1784-11eb-8200-4238e8556e3f.jpg)

Alguém pode me ajudar? Ou a recriar o código, ou mostrar o erro? Desde já agradeço.

**Comment by RicardoWEBSiTE** [comment]
troca = por += para incrementar e atribuir o valor, da forma que vc esta
fazendo esta em todo laço setando o valor

—



Em seg., 26 de out. de 2020 às 12:17, samuelpyerry <notifications@github.com>
escreveu:

**Comment by samuelpyerry** [comment]
Opa cara, valeu. Ajudou muito.
