### ISSUE TITLE
Materialize no ReactJS 

### ISSUE THREAD

**Issue by Al3xFlores** [frontendbr/forum#1913]
Hello Devs!

Galera estou fazendo meu portfolio em ReactJS e utilizando o Materialize, estou enfrentando algumas dificuldades durante o projeto.

A minha primeira duvida é em relação aos componentes em React, gostaria que cada componente utilizasse 100vh, porem quando eu coloco essa propriedade na classe Container do Materialize acaba sendo utilizado 100vh em tudo que tenha a classe Container em meu projeto, até o footer está ficando com 100vh, só que não é isso que eu quero e tbm não sei o porque está acontecendo isso, sendo que os componentes **home, sobre, tecnologias etc** são separados em pastas individuais.

Segunda duvida, estou querendo mudar as cores dos botões do materialize, porem quando faço isso  acaba perdendo a estilização que vem e nos botões do materialize e os efeitos.

E por ultimo  e não menos importante é os feedbacks do código que estou construindo , gostaria de opiniões e criticas construtivas para eu poder melhorar e me desenvolver, desde já agradeço a quem ler esse post.  

**LINK DO PROJETO:** https://github.com/Al3xFlores/Portfolio-em-React

**Comment by lucasferreiralimax** [comment]
Olá Alex, analisando seu projeto não consegui ver onde esta essa classe  com container 100vh

Mas basicamente se esta sobrescrevendo **.container** será aplicado em todos mesmo
Para evitar isso você pode criar uma de suporte classe **.full-vh** aplicando onde deseja

Espero ter ajudado e bons estudos pra ti

**Comment by Al3xFlores** [comment]
> Olá Alex, analisando seu projeto não consegui ver onde esta essa classe com container 100vh
> 
> Mas basicamente se esta sobrescrevendo **.container** será aplicado em todos mesmo
> Para evitar isso você pode criar uma de suporte classe **.full-vh** aplicando onde deseja
> 
> Espero ter ajudado e bons estudos pra ti

Fala Lucas, blz man?

Eu retirei a classe **.container** do CSS, devido estar aplicando os estilos globalmente, só que eu gostaria de saber alguma forma de impedir esse comportamento.

Você diz para criar uma classe de suporte, teria como me explicar como fazer isso no meu projeto ?

**Comment by Al3xFlores** [comment]
Conseguir resolver quebrando a cabeça!!

Quem tiver esse problema com o Materialize, a solução é só colocar a **section com classe**  e não atribuir nenhuma outra informação na DIV, e tbm colocar o **section** antes do container que dá certo.

**Comment by lucasferreiralimax** [comment]
> > Olá Alex, analisando seu projeto não consegui ver onde esta essa classe com container 100vh
> > Mas basicamente se esta sobrescrevendo **.container** será aplicado em todos mesmo
> > Para evitar isso você pode criar uma de suporte classe **.full-vh** aplicando onde deseja
> > Espero ter ajudado e bons estudos pra ti
> 
> Fala Lucas, blz man?
> 
> Eu retirei a classe **.container** do CSS, devido estar aplicando os estilos globalmente, só que eu gostaria de saber alguma forma de impedir esse comportamento.
> 
> Você diz para criar uma classe de suporte, teria como me explicar como fazer isso no meu projeto ?

A classe de suporte que indiquei para não sobrescrever os estilo do **.container** a aplicação seria assim criar a classe **.full-vh** globalmente e utilizar onde deseja

`<div className='container full-vh'></div>`
