### ISSUE TITLE
Oq faz esse código do Rupture?

### ISSUE THREAD

**Issue by thiamsantos** [frontendbr/forum#192]
Eu estava dando uma olhada no código do rupture, e não entendi bem direitinho o que esse código faz https://github.com/jescalan/rupture/blob/master/index.js

Deve ser alguma coisa boba mas alguém me explica?

**Comment by leonardoelias** [comment]
Inclui o rupture no style do documento.

**Comment by thiamsantos** [comment]
@leonardoelias faz sentido, obrigado.   Mas de onde veio aquele objeto style?  É alguma coisa do stylus?

**Comment by leonardoelias** [comment]
Ele importa esse aquivo : https://github.com/jescalan/rupture/blob/master/rupture/index.styl
Para quando você usar alguma função do rupture no seu aquivo styl, ele busque nesse aquivo.

: )

**Comment by LFeh** [comment]
Rápido :smile:

**Comment by thiamsantos** [comment]
Valeu @leonardoelias vc eh o cara :)
