### ISSUE TITLE
Erro ao inserir o endereço no Git do Github, o que fazer?

### ISSUE THREAD

**Issue by andrejs400** [frontendbr/forum#1924]
Boa tarde pessoal.

Estou fazendo um curso inicial de Git e Github, porém na hora de eu inserir o endereço do repositório do github no git da a seguinte mensagem:

$ git push origin master
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/andrejs400/livro-receitas.git'

o que eu devo fazer? 

Obrigado pela ajuda!

**Comment by renedocket** [comment]
Fala @andrejs400 , beleza? Depois que você criou o repositório você seguiu as instruções do github?

**Comment by andrejs400** [comment]
Opa @renedocket , me perdoe, mas estou um pouco perdido, pois estou iniciando hj... Olha como está 👍 

$ ls
READM.md  receitas/

André@DESKTOP-GH8F576 MINGW64 /c/workspace/livro-receitas (master)
$ git remote add origin https://github.com/andrejs400/livro-receitas.git

André@DESKTOP-GH8F576 MINGW64 /c/workspace/livro-receitas (master)
$ git remote -v
origin  https://github.com/andrejs400/livro-receitas.git (fetch)
origin  https://github.com/andrejs400/livro-receitas.git (push)

André@DESKTOP-GH8F576 MINGW64 /c/workspace/livro-receitas (master)
$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   READM.md
        new file:   receitas/stogonoff.md.txt


André@DESKTOP-GH8F576 MINGW64 /c/workspace/livro-receitas (master)
$ git push origin master
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/andrejs400/livro-receitas.git'

André@DESKTOP-GH8F576 MINGW64 /c/workspace/livro-receitas (master)
$ git push origin master
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/andrejs400/livro-receitas.git'

André@DESKTOP-GH8F576 MINGW64 /c/workspace/livro-receitas (master)
$ git remote add origin https://github.com/andrejs400/livro-receita.git
fatal: remote origin already exists.

André@DESKTOP-GH8F576 MINGW64 /c/workspace/livro-receitas (master)
$ git push origin master
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/andrejs400/livro-receitas.git'

André@DESKTOP-GH8F576 MINGW64 /c/workspace/livro-receitas (master)
$

**Comment by ninetails** [comment]
Opa André, tenta rodar

> git push --set-upstream origin master

**Comment by mstuttgart** [comment]
@andrejs400 pelo que vi (posso estar enganado), parece que a sua branch ainda não possui nenhum commit feito. Isso deve estar causando o problema na hora do push. Os comandos abaixo irão adicionar os arquivos.

* git add READM.md receitas/
* git commit -m "Initial commit"
* git push origin master
