### ISSUE TITLE
Dicas Sobre React Native. Formas de praticar a codar e sobre testes. 

### ISSUE THREAD

**Issue by Kapeite1** [frontendbr/forum#1926]
###Formas de praticar

Fala devs, me considero em um estágio de conhecimento com a biblioteca React Native intermediária, já desenvolvi alguns apps utilizando o mesmo, como por exemplo um app para delivery de uma lanchonete e outro para controle de financias. 
O problema é que me sinto estagnado, não estou sabendo praticar, ter ideias para conseguir desenvolver e me esbarrar com problemas, gostaria de dicas e assuntos para estudar, aprofundar e finalmente conseguir entrar no mercado utilizando React Native.

###Testes

Os testes para mim é algo novo, ainda não peguei para estudar, gostaria de dicas e qual escolher, alguem poderia me ajudar?  Jest, mocha, chai, teste unitario, tdd, de integração, end to end? 

Obrigado a todos pela colaboração.

**Comment by victorferreira** [comment]
Se inglês não for um problema, o canal do [William Candillon](https://www.youtube.com/user/wcandill) tem muita coisa bem legal sendo implementada com RN.
