### ISSUE TITLE
problema na rota com Reactjs

### ISSUE THREAD

**Issue by jaimeveneri** [frontendbr/forum#1928]
Boa noite,

poderiam me ajudar?

Estou com problema na rota, onde se digito no navegador: URL/artigo apresenta o erro: Cannot GET /artigo,

e se eu uso o onClick={() => navigate('/artigo')} de um botão ele funciona.

Código da rota esta abaixo:

import React from 'react';
import Artigo from './pages/Artigo';
import { BrowserRouter, Routes, Route, Redirect } from 'react-router-dom';

function App() {
return (
<-BrowserRouter>
<-Routes>
<-Route path="/artigo" element={} />
<-/Routes>
<-/BrowserRouter>
);
}

export default App;

ignorem o - nas tags coloquei pois bugou a exibição aqui
agradeço desde já

**Comment by victorferreira** [comment]
Eu chutaria que o seu servidor web não está redirecionando todas as requisições para a sua aplicação React. Como o React é um framework SPA, todas as requisições precisam ser enviadas pro seu _index_ e roteamento acontece no _client side_.

**Comment by ojvribeiro** [comment]
**[off]** Só uma dica... para escrever código com a syntaxe usando o markdown, coloque três vezes a crase, seguido da linguagem (`js`) e o código na próxima linha. Aí é só fechar com mais três crases.

Mais ou menos assim:
![image](https://user-images.githubusercontent.com/8026741/101060241-f69b1c80-356d-11eb-93f2-359ac7f82065.png)

O resultado é esse:
```js
function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/artigo" element={} />
      </Routes>
    </BrowserRouter>
  );
}
```
