### ISSUE TITLE
Clonar seu próprio projeto do GitHub em uma máquina diferente

### ISSUE THREAD

**Issue by ValdirCezar** [frontendbr/forum#1929]
Olá, pessoal!

Estou iniciando os estudo com Git e GitHub e tenho uma dúvida que não consegui encontrar na documentação ou em fóruns.

1 -> Eu tenho 2 computadores, o pessoal e o de trabalho.
2 -> Iniciei um projeto no GitHub com a máquina pessoal usando GitBash.
3 -> Na máquina de trabalho eu baixei o projeto que criei no GitHub usando a outra máquina.
4 -> Fiz algumas alterações no projeto e quero atualizar no GitHub .

Resumindo: Eu quero baixar meu próprio projeto do GitHub em outra máquina e salvar a atualização realizada.

Podem me ajudar?
vlw!

**Comment by felquis** [comment]
Essa é justamente a mágica do GIT mano o/

Após criar o repositório no GitHub, em cada computador, vc vai fazer um `git clone`. Caso seja um repositório privado, vc terá que cadastrar chaves ssh de cada computador no GitHub (Ex: estou presumindo que vc usa o mesmo usuário do GitHub em 2 computadores, então nessa conta vc terá 2 chaves ssh salvas no GitHub.)

A sincronização do código entre os computadores não acontece automáticamente como um dropbox, vc terá que usar comandos como:

No computador 1, vc usa os três comandos `git add`, `git commit` e `git push` para enviar arquivos modificados para o servidor.

No computador 2, vc faz `git fetch` e `git pull` para trazer atualizações do servidor.

Espero que outras pessoas possam passar o link de tutoriais mais bem ilustrados e simplificados para ajudar tbm. Qualquer dúvida manda ai nos comentários.

**Comment by felquis** [comment]
3 -> Na máquina de trabalho eu baixei o projeto que criei no GitHub usando a outra máquina.

Esse processo de "baixar" em outra maquina, a gente chama de clone.

4 -> Fiz algumas alterações no projeto e quero atualizar no GitHub .

Depois de fazer o clone, vc só vai conseguir fazer push de alterações para o servidor se vc tiver com a chave ssh configurada corretamente no computador, https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

Essa chave, vc deve pegar a publica dela, e salvar no seu profile do GitHub https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account

Veja se isso te ajuda
