### ISSUE TITLE
Sobre o Angular 2

### ISSUE THREAD

**Issue by mandado** [frontendbr/forum#193]
Fala galera recebi email da codeschool sobre o curso de deles de angular2 que foi lançado hoje rs, dei olhada nos slides do curso e gostei do que vi sobre o angular2.

E vocês que estão achando do angular2 ?

**Comment by diessica** [comment]
Veja a discussão #174.

**Comment by LFeh** [comment]
@frontendbr/admins Fecha essa né?

**Comment by eduardojmatos** [comment]
@mandado dá uma olhada no que a @diessica recomendou! =D

@LFeh acho que sim!

**Comment by mandado** [comment]
thanks galera :D
