### ISSUE TITLE
Funções como Valores ou Notação por Declaração?

### ISSUE THREAD

**Issue by kelciocajueiro** [frontendbr/forum#197]
Oi gente, venho do Java e estou querendo me aprofundar bem no JS. Comecei a estudar mas ainda estou no começo mesmo.

Minha dúvida é sobre funções, estou lendo o Eloquent JavaScript e vi que há duas formas de declaramos uma função: Como valores ou por declaração. O que os devs usam mais nos projetos?

**Comment by matmarsiglio** [comment]
Eis um lugar onde tem essa informação bem completa: http://pt.stackoverflow.com/questions/13364/qual-a-diferen%C3%A7a-entre-as-fun%C3%A7%C3%B5es-var-name-function-e-function-name

**Comment by kelciocajueiro** [comment]
Opa, valeu pela resposta @matmarsiglio

**Comment by lnfnunes** [comment]
@kelciocajueiro no JS, existe _hoisting_ nas declarações **var**.
Então por exemplo, um código assim:
```javascript
fn();
var fn = function() { return true; }
```
Vai gerar o erro:  // Uncaught TypeError: fn is not a function

Esse é o fator _hoist_ q comentei, onde oq acontece em tempo de execução é:
```javascript
va fn;
fn();
fn = function() { return true; }
```

Já quando vc utiliza da forma abaixo, não possui esse fator de _hoisting_:
```javascript
fn();
function fn() { return true; }
```

**Comment by kelciocajueiro** [comment]
Olá @lnfnunes, eu entendi bem os conceitos e diferenças de cada tipo de declaração de função. Minha dúvida é se existe algum padrão ou boa prática que define qual é a melhor opção, ou se isso vai de cada dev. Sacou?

**Comment by ortizvinicius** [comment]
Se não me engano o JavaScript Patterns do Addy Osmani trata disso também?
Não?

Em 30 de junho de 2016 16:12, Kelcio Cajueiro <notifications@github.com>
escreveu:

> Olá @lnfnunes <https://github.com/lnfnunes>, eu entendi bem os conceitos
> e diferenças de cada tipo de declaração de função. Minha dúvida é se existe
> algum padrão ou boa prática que define qual é a melhor opção, ou se isso
> vai de cada dev. Sacou?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/frontendbr/forum/issues/197#issuecomment-229759344>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABUQ3nF0O2P96VJNLSEJ2V967kH8fEuHks5qRBUjgaJpZM4JCcOp>
> .
>



-- 
Vinicius Ortiz | Ortiz Agência Web
vinicius@ortizagenciaweb.com.br
(43) 3339 1879
www.ortizagenciaweb.com.br

**Comment by douglascorrea** [comment]
@kelciocajueiro vai depender do style guide da equipe/projeto que vc estiver trabalhando. Muita gente segue o style guide da @airbnb, e a aqui ele descreve a [recomendação](https://github.com/airbnb/javascript#functions) para sua pergunta

**Comment by kazzkiq** [comment]
@kelciocajueiro Eu imagino que isso vá de cada dev ou pattern que a sua equipe usa.

Eu particularmente prefiro usar *function declarations* por alguns motivos:


- É o padrão da linguagem (o nome *function* foi reservado com o objetivo de criar funções):
```js
// Se você tem a palavra function reservada pra fazer isso:
function minhaFunc() {}

// Porque então fazer isso?
var minhaFunc = function() {}
```
- Mais fácil de identificar e debugar em caso de erros (você é obrigado a dar um nome pra função):
```js
var minhaFunc = function () {} // difícil de debugar
function minhaFunc () {} // nome da função (que é obrigatório) irá aparecer no stack trace
```
- Só de bater o olho no começo da linha você já sabe se aquilo é uma função ou não (`var` fica reservada para ... variáveis):
```js
// ... em um arquivo com milhares de linhas

function myFunc() { // é mais fácil de identificar que isso é uma função...
   //...
}

var myFunc = function() { // do que isso
 //...
}
```
-  Evita escrever mais código (se você for declarar uma função usando variáveis, é interessante dar um nome à ela de forma que fique mais fácil debugar a função posteriormente, isso significa que você teria que escrever o nome duas vezes:
```js
var minhaSuperFuncaoBacana = function MinhaSuperFuncaoBacana() {} // pra que escrever isso...

function minhaSuperFuncaoBacana() {} // ...se você pode escrever isso?
```

Lembrando que essa é apenas a minha opinião, pode ser que alguém tenha outra visão sobre o uso de expressões de função no lugar da declaração convencional.

**Comment by kelciocajueiro** [comment]
@douglascorrea Massa! Vou dar uma lida nesse guia da @airbnb.
@kazzkiq Concordo inteiramente com você, também prefiro utilizar _function declarations_ de cara ja percebi que esse método facilita muito mais a reusabilidade de código. Valeu pela explicação!

**Comment by kazzkiq** [comment]
@kelciocajueiro Apenas lembrando que atualmente, com a nova especificação JavaScript (ES6) também é possível trabalhar com classes, módulos e herança no JavaScript de forma muito mais parecida com o que ocorre no Java. E isso facilita muito a vida de quem tá vindo de outras linguagens pro JavaScript.

Então enquanto antigamente você simularia "classes" no JavaScript usando algum dos inúmeros [design patterns ](https://addyosmani.com/resources/essentialjsdesignpatterns/book) baseados no conceito de *prototypes* e objetos, hoje em dia você já pode usar uma sintaxe muito mais parecida com outras linguagens existentes, sem deixar de aproveitar os recursos que o JavaScript proporciona.

Pra dar um exemplo prático, no ES5 você estenderia uma "classe" assim:
```js
function Shape() {
  this.x = 0;
  this.y = 0;
}

Shape.prototype.move = function(x, y) {
  this.x += x;
  this.y += y;
};

function Rectangle() {
  Shape.call(this);
}

Rectangle.prototype = Object.create(Shape.prototype);
Rectangle.prototype.constructor = Rectangle;
```

Enquanto no ES6, você poderia usar essa sintaxe:
```js
class Shape {
  constructor() {
    this.x = 0;
    this.y = 0;
  }

  move(x, y) {
    this.x += x;
    this.y += y;
  }
}

class Rectangle extends Shape {

}
```

No segundo caso, o código fica muito mais limpo e parecido com linguagens populares fora do meio web.

Apesar do código ser diferente, o "core" da linguagem continua o mesmo, essa nova sintaxe veio apenas como uma forma de simplificar (e padronizar) a forma de escrever código OO no JavaScript.

Obs.: Como essa nova sintaxe faz parte do ES6 (que é uma especificação recente), browsers antigos não rodarão esse código corretamente. Nesse caso, você pode usar compiladores para portar seu código ES6 para ES5 (como o [Babel](https://babeljs.io/) ou [Traceur](https://github.com/google/traceur-compiler), por exemplo).

**Comment by LFeh** [comment]
O @kazzkiq é um monstro :)

**Comment by kelciocajueiro** [comment]
Oi @kazzkiq, obrigado pela resposta, muito esclarecedora!
