### ISSUE TITLE
Treeview recursivo

### ISSUE THREAD

**Issue by vitocaio** [frontendbr/forum#205]
Olá caros colegas do Frontendbr, venho até vocês pedir ajuda, ainda sou novo no mundo da programação, sinto que minha logica ainda não esta afiada, então venho até vocês pedir ajuda para uma tatarinha. Tenho que desenvolver uma treeview recursiva, ou seja. estou recebendo um Objeto que contem o seguinte formato.

```
{
  "fields": [1,2],
  "groups": [{
      "fields": [1,2],
      "groups": [{
          "fields": [1,2],
          "groups": [
            ... 
          ]
      }]
  }]
};
```

Em fim, este objeto pode conter varios groups, eu precisava transformar isso em uma treeview sem o uso de frameworks e deve ser recursivo.

agradeço a ajuda e espero que tenha ficado claro, obrigado!

**Comment by mtsalcova** [comment]
Olá @vitocaio, veja se isso te ajuda:


```
var json = '{"fields": [1,2],"groups": [{"fields": [3,4],"groups": [{"fields": [5,6],"groups": []}]}]}',
      rs = JSON.parse( json );

var createTreeView = function( obj ) {

      if( obj ) {          
          console.log( "fields => "+obj.fields );
          createTreeView( obj.groups[0] );
      }

}
        
createTreeView(rs);
```

No console vai resultar em:
"fields => 1,2"
"fields => 3,4"
"fields => 5,6"

Espero ter ajudado, valeu! :)
