### ISSUE TITLE
Precisamos falar sobre o Code In The Dark

### ISSUE THREAD

**Issue by ravanscafi** [frontendbr/forum#206]
Na sexta feira ocorreu a primeira edição do Code In The Dark Brasil, seguindo o modelo do homônimo gringo. Não tenho dúvidas de que o evento tenha sido um sucesso para todos os participantes. 

O tema era relevante, em um local que talvez seja o sonho de muito desenvolvedor conhecer, com o pessoal influente da área que talvez muitos não tiveram chance de conhecer e somente acompanham pela internet. Uma oportunidade ótima de interagir com essa galera e de troca colocar os conhecimentos à prova, mesmo que somente acompanhando da torcida.

Mas para alguns, isso não foi realidade. Talvez não todos tenham ficado sabendo, mas rolou uma certa confusão com o e-mail do eventick que **todos** receberam antes, que dizia que a presença estava confirmada:
![image](https://cloud.githubusercontent.com/assets/6104262/16567077/24053644-41f1-11e6-8983-bf32339a8ef9.png)

Na verdade, esse era um e-mail de _pré-confirmação_, porém **muitos** (e quando digo muitos aqui, digo em torno de 40 pessoas, que, considerando o tamanho do evento, é uma parcela considerável), assim como eu, não ficaram sabendo disso até serem barrados na portaria do prédio do Google, sem entender nada. O que aconteceu na verdade foi que rolou um sorteio dos participantes devido à alta procura pelo evento. Até aí, nenhum problema, nada mais justo que fazer um sorteio para democratizar o acesso ao evento (salvo casos de pessoas que os próprios organizadores convidaram por conta, não vem ao caso aqui quão justo ou não isso é). Quem recebeu o segundo e-mail avisando que foi sorteado, ok, porque pôde perceber que o primeiro e-mail de nada valia e como estava sorteado, poderia ir tranquilamente. Agora o problema é: quem **não recebeu** o segundo e-mail, **não recebeu mais nada** e, a não ser que acompanhasse o facebook do evento, saberia que não estava na verdade sorteado.

Teve gente que saiu mais cedo do trabalho. Teve gente que além disso faltou na faculdade. **Teve gente que comprou passagem de avião, reservou um hotel em sampa, tudo pra participar do evento**. Imagina o tamanho da frustração, desespero e raiva que isso pode ter gerado nas pessoas que passaram por isso. Ao descobrir o ocorrido, pedi para amigos meus que tinham entrado, para pedirem um posicionamento dos organizadores. Os mesmos não desceram para dar uma satisfação pelo período de duas horas (!!!) para os que estavam frustrados lá embaixo, somente mandaram informações. Para mim pelo menos, o evento acabou ali e, frustrado, avisei pessoas que estavam a caminho para confirmarem os e-mails e voltarem pra casa, coisa que eu fiz também.

Um dos organizadores, segundo se pode ver pelos comentários na própria página do facebook, desceu após essas duas horas e afirmou que "não tinha que se explicar de nada". Mesmo colocando pra dentro grande parte da galera que insistiu até o último minuto que teriam que entrar, não foi legal o que rolou.
Não teve nenhum tipo de pedido de desculpas público, não teve nada. Foi simplesmente abafado e ficou por isso mesmo.

Pensem que nem todos estavam curtindo a página do facebook do evento, ou seguindo no twitter, ou tinha algum dos organizadores do evento entre os amigos nas redes sociais, ou se inscreveu em algum RSS, ou assinaram algum serviço de notificação por sms, ou o que seja, e puderam acompanhar todas as notícias. Os inscritos chegam ao site através das mais diversas maneiras e seu único canal de comunicação é o e-mail que recebem ao se inscreverem e, possivelmente (possivelmente mesmo), o site, que podem voltar a acessar depois para confirmar programação/local.

Se as pessoas compareceram ao evento por engano, quem errou não foram elas e sim os organizadores que falharam ao comunicar de forma clara, e pelos canais de comunicação corretos, se elas deveriam comparecer ou não. Se a sua única forma de notificações com os participantes é o facebook, **deixe isso claro como água**. Tenha cuidado com as plataformas que utilizam para o evento, conheçam-a de antemão, para evitar problemas bobos como o ocorrido.

Na minha humilde opinião, faltou planejamento, compreensão, humildade e, principalmente, empatia, como faltou empatia.
Ao organizar um evento, se coloque no lugar dos participantes, pensem em problemas que os mesmos podem encontrar e tente evitá-los, afinal, o evento é feito justamente para os participantes, não? Qual era o custo e complexidade de reforçar a questão do sorteio por e-mail? Ou ao menos enviar um e-mail para os não sorteados?

Não venho por meio desse issue tentar causar polêmica, pelo contrário, quero só que quem for organizar um evento daqui pra frente, possa se conscientizar das causas de se fazer um evento e focar totalmente nos participantes (e não-participantes, quando houverem).

Por favor, peço que entendam o ponto de vista de quem ficou de fora, frustrado. Pensem em todo o planejamento que rolou para poder atender ao evento. Pensem nos sentimentos que se passam ao descobrir que na verdade aquilo que era dado como certo à semanas, na verdade foi um engano seu.

Obrigado.

(PS: pensei em postar no frontendbr/eventos porém acho que lá é mais pra divulgação, então postei aqui, mas posso portar pra outro lugar se estiver errado.)

**Comment by eduardojmatos** [comment]
Oi @rscafi tudo bem cara? Fiz parte da organização do evento e posso responder alguns itens que você citou.

Eu realmente entendo sua crítica e queria agradecer pelo seu feedback. Foi o primeiro evento que realizamos nesses moldes e é importante colher todas as possíveis avaliações pra melhorarmos na próxima vez!

Sobre a questão de confirmação de presença e sorteios, nós soltamos uma nota via email agora à tarde esclarecendo alguns pontos relacionados a isso.

Adiantando por aqui, nós fizemos o evento pensando na diversão e network da comunidade front-end. E pra isso, o modelo de sorteio foi escolhido desde o início. Se você olhar a página de inscrição temos lá o item:

> * Se ultrapassarmos 150 inscrições, iremos realizar um sorteio. Fique ligado no seu email! Iremos enviar uma mensagem para os ganhadores pedindo a confirmação de sua presença. Se houver demora na confirmação, a organização pode liberar a sua vaga para outros participantes.

Além disso fizemos vários posts via Facebook e Twitter avisando sobre o sorteio e a confirmação de presença. Exemplo:

![screen shot 2016-07-04 at 15 12 17](https://cloud.githubusercontent.com/assets/1279783/16567861/cc13062e-41f9-11e6-88a5-771efe15aad4.png)


Eu entendo seu ponto sobre pessoas não estarem em algumas redes sociais, mas não podemos descartar nesse caso que o aviso estava dado na página de inscrição.

Infelizmente, o que não consigo entender é que, nem todas as pessoas são educadas como você foi, e acabam se exaltando ou até mesmo ofendendo alguns dos organizadores e até patrocinadores (mandando "se foder", chamando de "escroto", entre outras baixarias).

![screen shot 2016-07-04 at 13 43 00](https://cloud.githubusercontent.com/assets/1279783/16567998/49c6ee7c-41fb-11e6-84a7-24c6f402c126.png)

![screen shot 2016-07-04 at 13 44 31](https://cloud.githubusercontent.com/assets/1279783/16567914/61094a4a-41fa-11e6-80ec-2f660374c764.png)

![screen shot 2016-07-04 at 13 44 59](https://cloud.githubusercontent.com/assets/1279783/16567934/ac21a8ce-41fa-11e6-8f61-b3eff4e2e867.png)

No próximo evento iremos melhorar nosso site e nossa comunicação via email pra não termos nenhum tipo de problema.

Só lembrando que, fizemos o evento sem nenhuma intenção em lucro ou qualquer coisa do tipo. O que queríamos era diversão e passarmos um tempo juntos, conhecendo novas pessoas e oportunidades. Fizemos uma parte do investimento do próprio bolso, e não, isso não justifica nossos erros, mas só pra deixar claro que não fizemos por nada mais do que paixão pela comunidade.

Falhas vão acontecer sempre, pois somos como vocês que participam de eventos, desenvolvedores, e não especialistas em organizar esses eventos.

Qualquer coisa estamos aí pra conversar, e se tiver mais feedbacks, manda pro nosso email também: codeinthedarkbr[at]gmail.com.

**Comment by diogomoretti** [comment]
Grande esclarecimento @eduardojmatos =] Creio que se você quer mesmo ir a um evento, nada mais justo que acompanha-lo nas redes.

=]

**Comment by eduardojmatos** [comment]
@diogomoretti tbm acho 😃

**Comment by danilovaz** [comment]
Não faço parte da organização e nem tenho vínculo com ninguém que organizou. Sou alguém que se inscreveu para participar, assim como você @rscafi , acho saudável esse tipo de feedback para o evento; realmente esse e-mail do Eventick causou dúvidas em muita gente (inclusive eu fiquei com essa dúvida). 

Só que como o @eduardojmatos bem colocou, eles avisaram pelas redes sociais do evento sobre isso. E foram vários posts, tanto que no meu caso eu nem cheguei a perguntar diretamente aos organizadores sobre essa dúvida porque o próprio post foi bem objetio: "A primeira inscrição não garante a entrada/participação no evento caso ultrapasse 150 inscrições". Logo depois disso, lembro que postaram que haviam passado de 400 inscrições e que por isso todos os participantes seriam escolhidos mediante o sorteio. Eu deixei uma aba do Facebook do evento e do Twitter aberta no meu navegador, diretão. Porque pra eu sair de SJC e pegar busão de 1:30h + trem/metrô e chegar na portaria e ver que eu não tinha aceito a inscrição ou entendido o formato, eu ia ficar muito chateado, mas comigo mesmo.

E realmente cara, é triste saber que uma galera teve essa dor de cabeça, porque o que eu pude ver e sentir participando do evento é que esses caras deram o sangue pra fazer um evento muito maneiro. Desde o local, como você bem disse, ser o sonho de qualquer desenvolvedor pisar lá até os layouts criados para a competição, DJ, comes e bebes; cara...seria injusto dizer que o pessoal que organizou não teve preocupação com quem iria participar ou de informar corretamente quem se inscreveu. Até a camiseta que recebemos lá tem mais qualidade do que muita camiseta de evento que eu já comprei por aí.

Mas obviamente, todo esse acontecido fica como aprendizado tanto para quem organiza quanto para nós que participamos. E seu relato é de extrema importância para todos os envolvidos. Nós também temos que sempre estar atento às informações dos eventos que vamos, afinal, somos as partes mais interessadas.

No mais, vamos apoiar e incentivar e parabenizar esses caras por trazerem um formato de evento tão foda e lindo de se participar. E que ano que vem tenha mais um e que nós participantes e organizadores possamos trabalhar junto pra mais um evento foda :smiley: :heart:

**Comment by eduardojmatos** [comment]
@danilovaz boa cara, é o que tbm acho. Sempre teremos alguns problemas e dificuldades pra resolver, não dá pra ser perfeito. Além do mais, ninguém é profissional nessa área, estamos aprendendo com o feedback de todos. O que nunca vai faltar de nós é paixão por organizar esses eventos. É muito gratificante fazer uma parada desse tipo e ver todo mundo contente, até mesmo os que tiveram problema no dia e entraram depois. É essa atmosfera de viver em comunidade que queremos potencializar com os eventos =D

**Comment by tcelestino** [comment]
Vários meses de aviso,  não havia necessidade de ter chegado ao nível relatado de casos isolados de pessoas "sem noção".
