### ISSUE TITLE
Olá amigos!

### ISSUE THREAD

**Issue by DevCleverton** [frontendbr/forum#2061]
Olá amigos!

Gostaria de compartilhar com vocês uma ideia que tive recentemente (ontem pra ser mais exato haha), que é criar um repositório semelhante a este só que voltado ao mundo do back-end. 

Pesquisando pelo github eu encontrei uma organização chamada [Back-end Brasil](https://github.com/backend-br), só que ao contrário desta comunidade que estamos, não sinto que é ativa e que existe ajuda entre os membros. Qual a opnião de vocês sobre isso?

Se quiserem passar por lá para contruirmos juntos esta comunidade, todos serão muito bem vindos.

Link: https://github.com/backendbr/forum

Ps: Eu me baseei muito neste repositório, se tiver algum problema por favor me avisem que apago o repositório.

_Originally posted by @rhuangabrielsantos in https://github.com/frontendbr/forum/discussions/2016_

**Comment by felipefialho** [comment]
Estamos usando a aba de [Discussions](https://github.com/frontendbr/forum/discussions) agora mano :)
