### ISSUE TITLE
Sugestão: Repositório com Agenda de Eventos

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/forum#21]
Rola um repositório com datas de eventos, meetups, hackatons?

**Comment by eduardojmatos** [comment]
@theandersonn olhae, excelente ideia! Rola sim, eu topo 100% :smile: 

* * * 

@frontendbr/admins e aí? Mais um repo pra org? Tá rápido demais isso tudo! hehehe

**Comment by theandersonn** [comment]
Que massa!
Uma ideia; acho que uma lista em ordem de data com algumas informações básicas sobre o encontro, cada novo commit segue a ordem de data para manter a agenda organizada :)

**Comment by eduardojmatos** [comment]
@theandersonn sim sim, boa! Eu acredito que um gh-pages com essas datas tbm resolveria.

Só definirmos um template, igual foi feito no repo de https://github.com/frontendbr/vagas, pra galera poder contribuir de forma padronizada.

**Comment by mvfsilva** [comment]
@theandersonn e @eduardojmatos existe esse projeto https://github.com/guilouro/devent abram issues lá e vamos contribuir

**Comment by eduardojmatos** [comment]
@mvfsilva parece interessante... mas tem issues abertas e não resolvidas desde ago/15 :scream: 

E olhando o código do projeto, vejo que a ideia foi pegar eventos com tags específicas do Eventick, via scraping. Acredito que a ideia do @theandersonn  é colocar mais eventos além desses, tipo meetups, etc. e outros que não estejam atrelados diretamente a um site específico.

*apesar disso que falei, gostei da ideia de automatizar esse processo :+1: . Só fica ruim pra fazer curadoria disso, mas facilita pra add numa lista

**Comment by Mendrone** [comment]
Que ideia ótima. Seria excelente ter agenda de eventos, meetups, cervejadas, role de skate, etc. Hahahaha :smile:

Vamos criar esse repo @frontendbr/admins iae pessoal, concordam?

**Comment by eduardojmatos** [comment]
@theandersonn @mvfsilva @Mendrone 

Tá lá: https://github.com/frontendbr/eventos

Podem postar por enquanto as issues. Mais tarde vamos começar a planejar a page :grimacing:

**Comment by theandersonn** [comment]
Opa showww ! :)

**Comment by LFeh** [comment]
Ótima ideia. 

Alias, para facilitar as sugestões e discussões sobre a org, não seria interessante a gente criar um repo só para isso? Assim, evita de se misturar com as discussões gerais.

@frontendbr/admins

**Comment by eduardojmatos** [comment]
@LFeh sim, ou criar uma label aqui não? 

O bom do repo é que fica focado no assunto num lugar separado do fórum, que tem assuntos diversos. O bom da label é que não precisaria criar um novo repo.

E agora? hehehe

**Comment by LFeh** [comment]
Eu sou a favor de um repo, até para usar para qualquer sugestão ou discussão sobre a org em geral. :p. Assim a gente deixa os outros repositórios livres para suas respectivas funções.

**Comment by YanMagale** [comment]
Esse repo dos eventos vai ser show. Sinto muito essa falta de um lugar único, para a concentração de todos estes eventos. Um projeto que parece estar bem ativo neste quesito é o [Saia de Casa](https://github.com/saiadecasa/saiadecasa.github.io)

**Comment by LFeh** [comment]
Está criado ;) 

https://github.com/frontendbr/eventos

**Comment by eduardojmatos** [comment]
:clap: :clap: :clap:
