### ISSUE TITLE
Nomeclatura de classes

### ISSUE THREAD

**Issue by marcosabb** [frontendbr/forum#211]
Para vocês, qual seria a melhor forma de nomear classes?

```html
<header class="header">
    ...
    <h1 class="header-title"><h1>
    <h2 class="header-description"></h2>
    ...
</header>
```
ou
```html
<header class="header">
    ...
    <h1 class="title"><h1>
    <h2 class="description"></h2>
    ...
</header>
```

**Comment by woliveiras** [comment]
Olá @marcosabb.

Eu sigo o primeiro estilo de código.

Sendo mais específico, hoje, utilizo o esquema do [BEMCSS](https://www.smashingmagazine.com/2012/04/a-new-front-end-methodology-bem/).

Eu curto essa metodologia porque o CSS fica bem modularizado e acontece uma boa separação dos componentes sem ter que forçar um pouco com especificidade para estilizar `grandes` aplicações.

**Comment by LFeh** [comment]
Opa, #83 :dancers:

**Comment by Mendrone** [comment]
Boa, @LFeh, eu não lembrada dessa issue.

**Comment by LFeh** [comment]
Mudei o nome pra facilitar.
