### ISSUE TITLE
O uso da função de discussions não tem integração com o Slack

### ISSUE THREAD

**Issue by felquis** [frontendbr/forum#2138]
Olá, no Slack temos um canal chamado #forum que parou de funcionar recentemente com a transição para a função de Discussões do Microsoft GitHub

Aparentemente não há mais integrações deste tipo, pois nós recebíamos via Slack novas issues + comentários nas issues com links para abrir o GitHub.

Estou postando aqui apenas para reportar um possível "side effect" que não foi visível para mim de imediato quando vi a migração acontecer.

Se alguém souber de algum slack bot que funciona da mesma forma de issues, porém com discussions para por no Slack, mande links. Obrigado.

Paz! Flws.

**Comment by vitebo** [comment]
Existe um webhook de discussions em beta: 
- https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#discussion

Tem uma issue no repo do slack tbm sugerindo essa integração:
- https://github.com/integrations/slack/issues/1134

Acho uma boa a gente acompanhar esses caras

**Comment by felipefialho** [comment]
@felquis @vitebo  Não acompanhei mais, sabem se esse webhook do discussions tá mais maduro?

**Comment by felquis** [comment]
Melhorou sim,

- canal #forum recebe novas discussões criadas, só não recebe os comentários
- canal #vagas recebe novas vagas criadas no frontend/vagas, mas lá é issues.
