### ISSUE TITLE
Sites com Múltiplos Idiomas

### ISSUE THREAD

**Issue by mtsalcova** [frontendbr/forum#216]
Fala galera,

Gostaria de saber qual ferramenta/maneira vocês utilizam para criar sites Multi-Línguas?

**Comment by barbier** [comment]
Sugiro ver como implementar o i18n na sua stack

**Comment by luisfmsouza** [comment]
Boa @barbier !

A gente usa i18next aqui e atende muito bem!

http://i18next.com/

**Comment by mtsalcova** [comment]
Opa, vou dar uma olhada, obrigado @barbier @luisfmsouza! :)
