### ISSUE TITLE
Campos * Formulário

### ISSUE THREAD

**Issue by ghost** [frontendbr/forum#230]
Olá Pessoal , preciso validar um formulário `PHP ou HTML` mas estou com alguns problemas.
1. Tenho o formulário bonitinho, más dentro de "Value" tenho "nome" -> Value="nome"
2. Como faço para deixar o campo obrigatório com o valor lá dentro ?  
3. Pois como tem um valor lá (obviou) não fica obrigatório.

**Comment by williamcosta** [comment]
@lucasbicalleto16 esse `value="nome"` seria para fazer um placeholder no input?

**Comment by hevertoncastro** [comment]
Como o @williamcosta disse, pelo que entendi você quer o texto como uma explicação do que aquele campo deve receber. Pra isso ao invés de `value="nome"` você usará `placeholder="nome"`.

**Comment by lucasbicalleto16** [comment]
Então amigos uso o `value="nome"` para dar um texto dentro do  `<input> `

**Comment by williamcosta** [comment]
Então a solução é use o atributo de `placeholder` e não `value`. Provavelmente seu input ficará assim:

`<input type="text" placeholder="Nome" value="" />`

**Comment by lucasbicalleto16** [comment]
@williamcosta isso cara muito obrigado os 2 amigos :) Close :D 

Satisfeito +1 vez

**Comment by lucasbicalleto16** [comment]
Opa Pessoal rapidinho aqui ,amei o resultado gostaria de saber se é possível o seguinte.

se a pessoa tentar enviar os dados sem preencher o formulário do Google, na mesmas página ele acusar erro de formulário não preenchido. ?

**Comment by LFeh** [comment]
@lucasbicalleto16 Não feche as issues :)

**Comment by lucasbicalleto16** [comment]
@LFeh  Não sabia amigo , sou novo.

**Comment by AdrianoCahete** [comment]
Só adicionando que, se for validar o form, faça em ambos, não só no cliente ou no servidor.

No cliente facilita a resposta pro usuário, mas no servidor precisa ter a mesma validação, por questões de segurança.
