### ISSUE TITLE
Bower x NPM [Dúvida] 

### ISSUE THREAD

**Issue by IgorCorp** [frontendbr/forum#235]
Pessoal para instalar pacotes de desenvolvimento FrontEnd vale a pena usar o Bower ou o NPM?

**Comment by wmartins** [comment]
Cara, essa é uma ótima questão. Da minha experiência onde trabalho, recentemente resolvemos parar de usar o bower e usar somente o npm como nosso gerenciador de pacotes. Os motivos "simples" disso foram, primeiro, que tinhamos que instalar um outro gerenciador de pacotes com o teu gerenciador de pacotes atual (`npm install -g bower`). Segundo, de uns tempos pra cá, quase todas as dependencias que vimos estão no npm (as que não estão, muitas vezes nem consideramos usar).

Enfim, nada é escrito em pedra, mas eu acho mais "saudável" gerenciar pacotes com somente um gerenciador. Mas vai mais do teu workflow e de como tu gosta de trabalhar. Passamos a usar somente o npm aqui e até então não nos arrependemos nem um pouco.

Também tem uma *thread* bem bacana rolando sobre deixar o bower *deprecated*, acho que vale dar uma olhada lá, tem um monte de argumentos bem fundamentados, tanto para o lado de usar o bower quanto para o lado de usar somente npm:

https://github.com/bower/bower/issues/2298

Por fim, acho que tu pode testar, cria algum projetinho que use bower, e outro que use só npm, e vê qual parece mais "natural" e se encaixa melhor no teu *workflow*. Particularmente falando, sempre me pareceu "estranho" ter que rodar `npm install` e depois `bower install`.

**Comment by wmartins** [comment]
Não sendo "tendencioso", mas tem umas respostas interessantes nessa *thread* no quora:

https://www.quora.com/Why-use-Bower-when-there-is-npm

**Comment by IgorCorp** [comment]
@wmartins atualmente eu utilizo ambos gerenciadores e estou pensando em ficar somente no npm.
OBS: Você citou um ponto bem interessante, que é ter que instalar um gerenciador para poder instalar outro gerenciador.

**Comment by LFeh** [comment]
Fala @IgorCorp , beleza?

Tivemos um tópico gigante sobre isso #17. Conseguem participar lá?
