### ISSUE TITLE
.gitignore separado por remote

### ISSUE THREAD

**Issue by adeonir** [frontendbr/forum#236]
Ae pessoal, tudo certo?

Tenho um git remote de produção e um remote no bitbucket.
Minha dúvida é se tem como separar usando gitignore. No bitbucket vou subir todos os src e na produção somente o dist.

**Comment by bruno-schmidt** [comment]
Tu pode também usar git hook. Toda vez que o repositório "produção" que tu mencionou receber um commit/push, ele executar o hook. Nesse hook tu pode iniciar o processo de build, seja usando um software pra isso ou um simples script, vai depender do teu problema.

Uma vez eu precisei fazer isso e pesquisei exatamente a mesma coisa: como usar um gitignore para "remotes" diferentes xD e acabei achando essa solução. Na época usei git hook + phing.

Só deixando essa ideia também, pode ser útil pra alguém! :smile:
