### ISSUE TITLE
Problema com gulp e o plugin Browser Sync

### ISSUE THREAD

**Issue by akfzambrana** [frontendbr/forum#246]
Boa tarde, pessoal

Estou trabalhando em um novo projeto e estamos trocando o grunt pelo gulp, pelos motivos já conhecidos (velocidade, facilidade, etc). 

Neste projeto, temos algumas necessidades específicas pois estamos evoluindo somente algumas partes do front, sem poder alterar na arquitetura de pastas e tudo mais.

No nosso workflow, precisamos de duas tasks diferentes, uma pra desenvolvimento e outra pra produção e elas precisam ser 100% independentes, pois a task de produção vai ter mais coisas alem do básico (copiar arquivos e compilar o sass).

Ate o momento, conseguimos fazer praticamente tudo que precisamos, no entanto, o plugin browser-sync esta nos dando dor de cabeça. Pode ser (tenho certeza q deve ser) que estejamos configurando algo errado pois é a primeira vez que vamos trabalhar com gulp em um projeto grande da empresa e não temos tanta prática e conhecimento como para garantir que o erro não seja culpa nossa hehe

Criei um **[projeto de teste](https://github.com/akfzambrana/gulp-test-project)** simulando o cenário e arquitetura do projeto ja que não podemos mostrar o projeto original :flushed: ele esta simulando bem, inclusive o erro, fiquem a vontade para clonar
## Necessidade

Nossa necessidade, até o momento, é a seguinte:
### Desenvolvimento

Precisamos que rode as tasks:
- Limpa a pasta dist
- Copiar arquivos nas pastas necessárias
- Gerar o sprite
- Compilar o sass
- Enviar pro browser
- Ficar watch nos arquivos js, html e scss
### Produção

Precisamos que rode as tasks:
- Limpa a pasta dist
- Copiar arquivos nas pastas necessárias
- Gerar o sprite
- Compilar o sass
- Minificar todos os CSS
- Otimizar as imagens
## O que está acontecendo efetivamente

Até agora, tudo que precisamos fazer em desenvolvimento está acontecendo, ta lindo e atualiza o browser muito bem. Vimos que tem como colocar a task de watch dentro da task do browser-sync, no entanto ainda não melhoramos isso ai.
## O problema

A questão é q agora que estamos tentando configurar a task de prod, percebimos que o browser-sync roda de qualquer jeito, esteja ou não no run-sequence da task build:prod.
## O que já tentamos

1.- Imaginamos que parte do problema seja pq estamos chamando o browserSync.reload na task de sass e na de copy, mas se tirarmos isso, o browser-sync para de atualizar os arquivos. E mesmo tirando a task de browser-sync de ambas tasks, ele continua rodando em prod.
2.- Encontramos uma solução que chama as tasks de watch dentro do browser-sync, não precisando colocar o reload dentro da task de sass e copy, mas desse jeito o plugin tb não atualiza corretamente as coisas, apenas atualiza o sass.
3.- Depois de varias tentativas, percebimos que mesmo não chamando a task browsersync dentro de nenhuma outra task, mesmo assim ele continua rodando, então acreditamos que exista um erro na configuração da task en sí.

Por favor, se algum de vcs, que obviamente tem muito mais conhecimento de gulp que nós, puder fazer sugestões ou tentar achar onde estamos errando seremos profundamente gratos.

Obrigada!

**Comment by renatogalvones** [comment]
@akfzambrana perdão se entendi errado, mas acredito que na parte do BrowserSync vc pode tentar utilizar o **browserSync.stream**

Dá uma olhada nessa issue:
http://stackoverflow.com/questions/31163754/browser-sync-does-not-refresh-page-after-changes-with-gulp

PS: Parabéns pela issue completada e detalhada. :metal:

**Comment by akfzambrana** [comment]
@renatogalvones Acabei de tentar, o problema do plugin estar sendo chamado sempre permanece. 
A maior parte dos workflows que tenho visto na internet utilizam sempre o browser-sync, não separam os tipos de builds, tal vez por isso nunca tiveram esse tipo de problemas. :disappointed:

**Comment by akfzambrana** [comment]
Acabei de resolver o problema, o único que tive que fazer foi colocar um return na função browserSync, ela ficou assim:
```
var gulp = require('gulp');
var browserSync = require('browser-sync');
var config = require('./config.js');
var argv = require('yargs').argv;

gulp.task('browserSync', function(){
    browserSyncTask(argv.app, argv.brand)
});

function browserSyncTask(app, brand) {
    return browserSync({
        port: 3000,
        server: {
          baseDir: config.env.buildDir + '/' + app + '/' + brand
        }
    })
}
```
Ja to fechando a issue :smile:
