### ISSUE TITLE
Menu of Canvas

### ISSUE THREAD

**Issue by lucasanthony** [frontendbr/forum#260]
Opa pessoal blz?

Tenho um famoso " Menu of Canvas " e gostaria de saber se é possível, quando o usuário entrar ele aparecer de cara , e não ficar escondido esperando ele clicar.. ?

PS: Agradeço desde já, e antes que falem não consegui achar em algum lugar postei em forúns.

**Comment by williamcosta** [comment]
Esta usando algum plugin?

**Comment by lucasanthony** [comment]
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="js/custom.js"></script>

**Comment by williamcosta** [comment]
Então presumo eu que você está fazendo do zero, certo?

**Comment by lucasanthony** [comment]
Sim :+1:

**Comment by williamcosta** [comment]
Cara, tem diversas maneiras de fazer isso.

Você pode ter uma class para abrir e fechar o seu menu. Como um `menu--open`. Acho que pesquisando um pouco mais você consegue fazer ainda mais usando jQuery. Ou você pode usar alguma lib que já tenha callbacks para isso como por exemplo: [Mango - Slideout](https://mango.github.io/slideout/)

**Comment by lucasanthony** [comment]
@williamcosta , tenho um exatamente igual , irei postar os código veja se é possível.
https://www.sendspace.com/file/lfun4i

**Comment by williamcosta** [comment]
@lucasanthony, cara desculpa estou tentando te ajudar, mas não vai ser me enviando código que isso vai acontecer (isso porque não foi nem um Codepen, para pelo menos eu ver o que está acontecendo).

Não é a comunidade fazendo código para você que vamos ter ajudar a evoluir na área.

E assim como o @willycamargo já falou em outra issue sua e colocou no readme, o @LFeh já falou e outras issues.

> Apesar de nem todos os usuários estarem ativos da mesma forma no forum estamos todos dispostos a ajudar. Porém, antes de fazer perguntas por aqui vale dar uma pesquisada no Google antes. Eu acredito que saber pesquisar é uma das maiores qualidades de um desenvolvedor, principalmente iniciante.
> 
> Dicas:
> 
> Pesquise em inglês, nem que pra isso precise recorrer ao translate
> Dê preferência para documentações e forum especializados (MDN/StackOverflow ou invés de yahoo answers)
> Acho que é isso =)

Me desculpa de verdade, porém não é assim que as coisas funcionam.

**Comment by diessica** [comment]
Se for pesquisar em inglês, o termo correto é **Off-canvas** menu.

**Comment by LFeh** [comment]
Pelo nome é o mesmo mano que estava querendo código pronto em outras issues e excluiu a conta. Além de tudo está apagando as respostas.

> PS: Agradeço desde já, e antes que falem não consegui achar em algum lugar postei em forúns.

Postar a dúvida em fórums não é pesquisar.

**Comment by LFeh** [comment]
@lucasanthony Só mais uma coisa, esse é um fórum rodeado de profissionais importantes na área, e o Github é uma ferramenta aberta.

Você só está se prejudicando agindo dessa maneira :wink:

**Comment by williamcosta** [comment]
@LFeh eu tinha comentado com uma amiga a mesma coisa sobre ser a mesmo usuário de outras issues que excluiu a conta.

**Comment by LFeh** [comment]
É o mesmo nome, enquanto ele continuar querendo que façamos o trabalho por ele, não se deem ao trabalho. 

Pelo jeito ainda é garoto, logo logo ele aprende.

**Comment by bernardodiasc** [comment]
@lucasanthony Voce precisa instalar Wordpress com Bootstrap no seu projeto pra conseguir fazer o que quer. Sem isso é impossível fazer qualquer coisa hoje em dia!!!
