### ISSUE TITLE
Migrar de área não sendo mais junior

### ISSUE THREAD

**Issue by rpaggi** [frontendbr/forum#261]
Galera, a alguns anos venho enfrentando este paradigma, hoje trabalho como analista de sistemas com a linguagem Cobol, sim COBOL, porém a anos tenho o sonho/desejo de migrar para área de web, mas especificamente com back-end, mas o X da questão aqui é, como migrar de área, trabalhar com outra linguagem, sendo que hoje já estou nesta área a 6 anos, com um nível de Pleno, ganhando um salário acima da média e as minhas contas não me possibilitam ganhar muito menos do que ganho hoje. 
Qual a dica/opinião de vocês em relação a este meu impasse. Alguém aqui já passou por isso e possa me dar uma luz.

**Comment by douglascorrea** [comment]
Olá @rpaggi, eu enfrentei/enfrento o mesmo problema que vc. Trabalho com Siebel (Pacote CRM da Oracle) há 10 anos, sou consultor senior e também com um salário muito bom.

Há uns 3 anos eu decidi que queria mudar, pois o trabalho em com Siebel em si não é dos mais atrativos: muita repetição, não há muita novidade e o conhecimento é muito específico.

Então desde 2013 eu venho fazendo freelas, projetos pessoais, tentando ajudar em algumas startups e com isso aprendendo.

Vim montando um portfólio (também usando sites como Upwork pra pegar freelas e fazer um perfil bacana).

Hj ainda trabalho com Siebel, mas já tenho freelas que me pagam o mesmo valor (em dólar) do que eu ganho com minha atividade principal.

A minha dica aqui é começar devagar e ir montando um portfólio em paralelo. E focar no mercado externo já que vc tem a oportunidade de ganhar em dólar e, normalmente, o valor de júnior/pleno é mais alto que junior/pleno no Brasil.

Dessa forma você consegue fazer uma transição mais "suave". O duro é que vc terá que trabalhar o dobro durante um tempo pra levar os freelas e seu trabalho principal.

**Comment by cmpereirasi** [comment]
Fantastico @douglascorrea 👏
