### ISSUE TITLE
Acessibilidade - Leitores de tela

### ISSUE THREAD

**Issue by eptaccio** [frontendbr/forum#267]
[Estava vendo um vídeo bem legal da google](https://www.youtube.com/watch?v=Lktz1KXbTOU) que envolvia acessibilidade / leitores de tela, acabei pesquisando sobre e não achei muita coisa a respeito (talvez tenha pesquisado errado).
Você tem se preocupado com isso durante o desenvolvimento no dia a dia? Possue algum leitor de telas instalado para ver os resultados finais?

_Agradeço se quiser mandar uns materiais a respeito (:_

**Comment by barbier** [comment]
Excelente palestra da @nathaliabruno sobre o tema no Front in Rio deste ano.

http://pt.slideshare.net/NathaliaBruno/acessibilidade-web-frontinrio-2016

**Comment by LFeh** [comment]
@deividmarques, @talitapagani, @reinaldoferraz

**Comment by reinaldoferraz** [comment]
A palestra da @talitapagani no último FrontInSampa dá ótimas dicas de coisas que você pode fazer e que vai funcionar bem não só para usuários de leitores de tela, mas para todos os usuários, incluindo pessoas com baixa visão, deficiência motora e cognitiva. 
Vídeo: https://youtu.be/4URTZHk6tz0
Slides: http://slides.com/talitapagani/acessibilidade-na-pratica-para-voce-nunca-mais-esquecer#/1

**Comment by Raffesmind** [comment]
O [FrontUX 8](http://frontux.com/testando-interafaces/) tem algumas ferramentas e dicas para trabalhar acessibilidade também, pode ter algumas informações uteis para testar seu processo.

Outra dica seria usar alguma ferramenta como o JAWs ou os próprios leitores nativos do windows para sentir um pouco mais próximo o uso do seu site só com teclado e orelhas.

**Comment by nathaliabruno** [comment]
A @talitapagani tem vários conteúdos super interessantes no slideshare. Ela me ajudou bastante quando estava organizando minha palestra... Tem também algumas palestras do @reinaldoferraz que tem excelentes dicas...

**Comment by nathaliabruno** [comment]
@marcosflorencio Uma ferramenta incrível que foi lançada há pouco tempo é o cli do Adios Mani que lista o que deve ser ajustado seguindo as regras do ARIA https://addyosmani.com/a11y/ Enjoy! :)

**Comment by marcosflorencio** [comment]
Obrigado galera, estou estudando o material. Bem, que bom que essa questão não está "de lado" então :)

**Comment by gabrieldarezzo** [comment]
Eu cheguei a fazer um projeto de adaptação de site/portal institucional do sindicato que eu trabalhava para ter acessibilidade.

O projeto foi bem bacana.
A parte mais 'louca' era fazer o teste / simular. Colocava uma venda nos olhos e tentava navegar.
Ocorreu homologação com deficientes de verdade após o site estar 'ok', e realmente pequenos ajustes fazem a diferença na vida dessa galera.....
O trabalho foi bem elogiado o trabalho,

O Software que eu usava para testar era esse: (tem um trial, apesar de não ser OpenSource)
http://www.virtualvision.com.br/
(Caso alguém souber alguma opção Open bacana posta aí)

Basicamente o projeto era colocar uma ordem lógica o focus da pagina. (autofocus obrigatorio, e ordem racional para leitura do tab, (tag: tabindex)
O restante é só seguir as boas praticas de SEO: alt, title... etc.

```
<!DOCTYPE HTML>
<html lang="pt-br">
<head>
	<meta charset="UTF-8">
	<title></title>
</head>
<body>
	
<a id="link-one" href="site.com.br/index.php" tabindex="1"  title="Link 1">Link 1</a><br />
<a id="link-tree" href="site.com.br/index.php" tabindex="3" title="Link 3">Link 3</a><br />
<a id="link-two" href="site.com.br/index.php" tabindex="2"  title="Link 2">Link 2</a><br />
	
<script type="text/javascript">
	document.getElementById("link-one").focus();
</script>
	
</body>
</html>
```
Observe o focus já vem ativo, e depois você pode navegar pelo tab para frente, ou utilizar o shift + tab para trás...

**Comment by deividmarques** [comment]
@gabrieldarezzo  que legal saber que voce mesmo fez o teste com leitores, isso é fundamental pra desenvolver e testar, mas vale lembrar que é bom ser validado em um usuário real com as condições testadas, pois ele tem outra vivência e dará ótimas feedbacks pra melhorias.

Eu desenvolvo usando Mac então uso o Voice Over, no Windows já testei usando JAWS demo  e NVDA, aproveitando eu fiz uma mini descrição de como usar (NVDA e o Voice Over): http://opensource.locaweb.com.br/locawebstyle-v2/manual/praticas-padroes/acessibilidade/leitores-de-tela/

**Comment by gabrieldarezzo** [comment]
Ahh sim, eu acabei editando o post, rolou homologação com pessoas deficientes mesmo. 
No caso o Voice Over utiliza o title para verbalizar?

**Comment by deividmarques** [comment]
Pelos testes que realizei, só não vou lembrar as versões agora, tanto o **Voice Over** quanto o **JAWS** entendem o `title`, mas o **NVDA** não, e reparei que ambos entendem o atributo `aria-label`

**Comment by brunopulis** [comment]
@marcosflorencio Procure no site do [Paciello Group](https://www.paciellogroup.com/blog/) tem um vasto conteúdo voltado a acessibilidade. E tem o [meu repo](https://github.com/brunopulis/awesome-a11y) que coloquei várias dicas sobre o assunto lá, não me recordo se tem algo em especifico para leitores de tela por agora.

**Comment by talitapagani** [comment]
Opa, estou chegando atrasada à discussão (mals ae, não vi as notificações). O pessoal já deu muitas dicas bacanas aí em cima e tenho algumas considerações com base na minha experiência:
- Tem leitor de tela que funciona melhor com certos navegadores, por exemplo, JAWS com Internet Explorer (não sei quanto ao Edge) e NVDA com Firefox;
- O suporte a certas propriedades é resultado desta combinação leitor de tela x navegador.

O WebAIM tem alguns materiais interessantes, em inglês, sobre o assunto:
- [Como projetar sites para compatibilidade com leitores de tela](http://webaim.org/techniques/screenreader/)
- [FAQ sobre teste com leitores de tela](http://webaim.org/articles/screenreader_testing/)
- [Resultados de uma pesquisa sobre leitores de tela](http://webaim.org/projects/screenreadersurvey6/)

**Comment by francisquete** [comment]
Mas e quanto ao daltonismo, como proceder?

**Comment by talitapagani** [comment]
@francisquete Para daltonismo, tem recursos muito bacanas para o Chrome: a extensão [NoCoffee Vision Simulator](https://chrome.google.com/webstore/detail/nocoffee/jjeeggmbnhckmgdhmgdckeigabjfbddl) e o [ChromeLens](https://chrome.google.com/webstore/detail/chromelens/idikgljglpfilbhaboonnpnnincjhjkd), que permitem simular diferentes condições de deficiência visual ou anomalia de visão, incluindo o daltonismo. Eu utilizo essas duas ferramentas rotineiramente.

**Comment by francisquete** [comment]
@talitapagani não conhecia, vou dar uma olhada, obg :smile:

**Comment by alalbuquerque** [comment]
dá uma olhada nesse [artigo](https://aerolab.co/blog/web-accessibility/), tem algumas dicas e outras ferramentas que você pode usar para testar a acessibilidade do site como a extensão do [ChromeVox](https://chrome.google.com/webstore/detail/chromevox/kgejglhpjiefppelpmljglcjbhoiplfn?hl=pt-BR) que eu sempre uso.

**Comment by lucasjs** [comment]
@francisquete alguem disse daltonismo? 👀 
https://pt.slideshare.net/LucasJSilva1/daltonismo-no-desenvolvimento-web-abc-dev-2017

**Comment by brunopulis** [comment]
@francisquete caso você queira um guia sobre tecnologias assistivas e outros recursos de acessibilidade você pode dar uma olhada num repo que eu criei sobre A11Y o, [Awesome A11Y](https://github.com/brunopulis/awesome-a11y)

**Comment by francisquete** [comment]
obrigado pelas dicas galera :smile_cat:

**Comment by francisquete** [comment]
@lucasjs tenho a impressão de ter visto esse slide no front in vale :eyes:

**Comment by talitapagani** [comment]
Ainda sobre leitores de tela, o blog [Acessibilitó](https://medium.com/@acessibilito) está com uma série interessante sobre o assunto.
