### ISSUE TITLE
Qual a melhor forma de entregar um site para um cliente?

### ISSUE THREAD

**Issue by thiamsantos** [frontendbr/forum#269]
Qual a forma de entregar um site para um cliente totalmente leigo possa editar o conteúdo(texto). Sem eu precisar ter que mudar muito meu workflow, trabalhar com algo próximo com uma template engine.

Quais seriam as opções?

**Comment by alanhr** [comment]
você pode usar algum CMS  tipo:
(Grav)[https://getgrav.org/], (October)[https://octobercms.com/] ou o pior wordpress rss

**Comment by kazzkiq** [comment]
Recentemente eu estava procurando um editor de texto para meu projeto e acabei achando uma biblioteca open-source muito legal que te permite editar o layout da sua página pelo próprio site real!

### [ContentTools](http://getcontenttools.com/demo)

Você clica no ícone vermelho no canto esquerdo da tela e consegue ir clicando e editando os textos do seu layout e já vendo como ficaria em tempo real. Apesar de não ter testado na prática, achei o plugin muito interessante e definitivamente usarei ele para freelas futuros. Espero que seja útil no seu caso. :)

Demo: http://getcontenttools.com/demo
Repositório: https://github.com/GetmeUK/ContentTools
