### ISSUE TITLE
Sugestão: Que tal a criação de um Gitter para o Repositório?

### ISSUE THREAD

**Issue by napalmdev** [frontendbr/forum#27]
O que vc acham de um gitter para o repositório? acredito que evitaria o pessoal flooda as issues com coisas menos importantes, pois ao meu ver, este repo tem o objetivo de manter as discussões em um nível mais sério e profissional e se começarem a floodar isso ae, a coisa vai por água abaixo, além de manter um contato mais próximo entre todos os dev's envolvidos. Um contato em tempo real é algo bem legal de se adicionar e como estamos fazendo uso extensivo do Github, o gitter seria uma ótima, e se o pessoal começar a perguntar muita coisa técnica por lá é só conscientizar eles falando: "Cara, isso dá uma boa discussão, vc já viu se tem alguma Issue aberta la? abre uma issue e vamos discutir isso".  

O vocês que acham?

**Comment by meche** [comment]
Eu acho válido! :) +1

**Comment by felipoliveira** [comment]
Não sei se a criação de um gitter é valido, pois já temos o Slack Frontend Brasil.

**Comment by eduardojmatos** [comment]
@napalmdev meu medo é de as discussões não acontecerem mais aqui, e forem todas pro Gitter.

A intenção das issues é que, pelo menos, a informação tá buscável, aberta e acessível

Nada impede de termos o Gitter, mas temos que ter sempre o mindset de migrar conversas que ficarem mais sérias pra cá, compartilhando conhecimento com todo mundo :grimacing:

**Comment by LFeh** [comment]
Particularmente acho que já tem o Slack da Front-End Brasil como disse o @felipoliveira. 

Acho muito difícil as discussões daqui partirem para "flood", até porque tem diversos outros meios para isso, como Twitter, Slack e o próprio Facebook :)

-----------------

@frontendbr/admins Pessoal, vamos criar aquele repo de sugestões?

**Comment by willianjusten** [comment]
Chat é algo muito "vivo", porém nada nada "indexável". Eu prefiro que não tenha chat e que tudo permaneça aqui, assim as informações são disponíveis a todos e de forma fácil.

**Comment by meche** [comment]
mas a galera poderia add no slack pelo menos né? xD

**Comment by napalmdev** [comment]
@LFeh , @felipoliveira, na moral eu nem sabia q havia slack do Frontend Brasil kkkkk, aliás se puderem add lá ou passar o endereço. @willianjusten, então a ideia não era migrar as discussões pra lá, mas como disse o @eduardojmatos fica difícil controlar isso.

No mais concordo com o @LFeh sobre criar um repo pra sugestões, então se quiserem fechar essa issue, fiquem a vontade.  =D

**Comment by LFeh** [comment]
Vou criar o repo ;)

**Comment by eduardojmatos** [comment]
Sim, pode ser! Eu já uso do FrontendBrasil. É bem ativo inclusive!!

**Comment by LFeh** [comment]
https://github.com/frontendbr/sugestoes

**Comment by eduardojmatos** [comment]
Boa!!! :)
