### ISSUE TITLE
rucksack css alias substituindo valor no content

### ISSUE THREAD

**Issue by rubenmarcus** [frontendbr/forum#295]
Oi, eu e mais um dev aqui na Printi pegamos um problema que não vi ninguem descrever ainda

coloquei no @alias do rucksack, a propriedade : op:opacity

quando em uma classe no css usamos o content para declarar o texto de um elemento, ele converteu pra opacity

Por exemplo : 'Selecione uma das opções"   ele pegou o op de opções e transformou em opacityões 

sabem alguma forma de contornar isso, alem de renomear o alias??
e usar o elemento span no html e mostrar e esconder conforme o hover ( é o que vamos fazer )
valeu!

**Comment by Mendrone** [comment]
@LFeh já lidou com isso no Rucksack?

**Comment by rubenmarcus** [comment]
no nosso gulpfile estamos usando na verdade o gulp-rucksack .. não sei se isso foi resolvido em alguma versão nova do rucksack, que nao foi compilado pro gulp-rucksack

**Comment by LFeh** [comment]
Uhmmm, eles devem varrer todo o CSS, não distinguindo se está dentro de aspas. 

Mas em todo caso, acredito que um melhor pattern para o uso de alias (particularmente não curto usar alais), seria ter um prefixo antes.

````
-op
````
