### ISSUE TITLE
Progressive webapp - alguém já fez algo com ele?

### ISSUE THREAD

**Issue by thierryrene** [frontendbr/forum#303]
Galera alguém já desenvolvou algo focado nas tecnologias PWA e AMP do Google? To dando uma olhada e parece ser uma alternativa muito boa para aplicações simples, além de ter bastante integração com o Android.

**Comment by LFeh** [comment]
#34 :smile:

**Comment by thierryrene** [comment]
Valeu @LFeh já ia fechar, me empolguei lendo o outro tópico sobre rs

**Comment by ngoctrai1997** [comment]
Eu nunca crio o pwa baseado no Google, mas eu costumava usar o Magento, é bom
[https://tapita.io/](url)

**Comment by ngoctrai1997** [comment]
Eu nunca crio o pwa baseado no Google, mas eu costumava usar o Magento, é bom
[https://tapita.io/](url)
