### ISSUE TITLE
Meetup AlphaCoding

### ISSUE THREAD

**Issue by rpaggi** [frontendbr/forum#306]
Pessoal bom dia, não sei nem se aqui é o lugar correto mas estou passando para divulgar um meetup que estou ajudando a organizar aqui em Alphaville(SP) e Região. Ainda não temos nenhum encontro marcado, mas estou divulgando para convidar os devs aqui da região a se juntarem a gente para em breve fazermos nosso primeiro meetup aqui da região.
Então fica aqui meu convite para quem quiser se juntar é só clicar [aqui](https://www.meetup.com/pt-BR/AlphaCoding/) 

Abraços!

**Comment by LFeh** [comment]
Coloca no eventos :)

https://github.com/frontendbr/eventos
