### ISSUE TITLE
Geolocation + HTML + Permissão

### ISSUE THREAD

**Issue by gabrieldarezzo** [frontendbr/forum#307]
Estou apanhando a alguns dias....
Estava estudando algumas coisas a respeito de HTML5 e utilizando os recursos de de localização.....

E encontrei um seguinte caso:
Gostaria de exibir um mapa ao usuário de acordo com sua localização. (Como o GoogleMaps faz no browser mesmo exibindo o PIN/Marker da sua localização atual)

Porem caso o usuário não tenha permitido por alguma razão. (eu mesmo tinha bloqueado e nem sabia kkkkkk )

Não tem como solicitar novamente?
atualmente até consigo 'jogar ele no bloco:
`if(err.PERMISSION_DENIED){  
  /*Solicitar novamente?!*/
}`

Links de apoio que encontrei até o momento:
https://support.google.com/chrome/answer/142065?hl=en
https://developer.mozilla.org/pt-BR/docs/Using_geolocation
http://diveinto.html5doctor.com/geolocation.html   ( Update )

Ahh se alguém tiver algum material bacana sobre HTML5/PWA manda ai to mergulhando de cabeça nesse mundo u.u

Edit2:
Pelo que entendi é uma policita de segurança.
Acredito que caso caia no DENIED, não vai ter muita opção. no máximo explicando como reativar encaminhando para aquele link do Chrome, ou fazer um passo a passo dependendo do Navegador (Personalizar é conversão u.u )

**Comment by LFeh** [comment]
Alguma ideia pessoal @frontendbr/admins ?

**Comment by fdaciuk** [comment]
Quase certeza que não tem como pedir permissão novamente.. é algo que o usuário escolhe: se ele quer que pergunte da próxima vez que entrar no site, ele tem que selecionar manualmente. O máximo que você vai conseguir fazer é deixar um aviso para o usuário, mostrando como ele deve proceder para liberar o acesso a geolocation na sua aplicação.

É o mesmo esquema dos alerts: agora os browsers te dão opção de, após o primeiro alert, não mostrar mais naquele site, pois é algo muito invasivo. O usuário tem que parar toda a navegação dele pra dar atenção para aquela página específica. Isso é bastante irritante =)

**Comment by raphaguasta** [comment]
Pergunta interessante @gabrieldarezzo !! Conseguiu descobrir alguma solução?

**Comment by Lucasktrindade** [comment]
Sobre PWA, você pode consumir os Codelabs da Google, tem umas paradas bem maneiras lá. https://codelabs.developers.google.com/

**Comment by gabrieldarezzo** [comment]
@raphaguasta 
Não seria a solução que eu gostaria, mas é checando em tempo de execução se tem algum erro (err.PERMISSION_DENIED) como o @fdaciuk disse fazendo um passo a passo de como habilitar o mesmo.

Veja mais em:
https://developer.mozilla.org/pt-BR/docs/Using_geolocation
->
Manipulação de erros

Inclusive estou pensando em fazer uma especie de 'plugin-js' de acordo com o Navegador/Device/Versão fazer um passo a passo como habilitar já q é a unica maneira de conseguir a localização caso tenha sido recusado a primeira vez.

Pensando no usuário a navegação Web precisa ser assim mesmo se não vira festa da uva sair pegando localização (vide ads chatos)

@Lucasktrindade que bacana essa iniciativa.
Não conhecia.

Obrigado a todos pelas resposta.
Aquele abraço.

**Comment by LFeh** [comment]
@gabrieldarezzo Resolveu?

**Comment by Mendrone** [comment]
@gabrieldarezzo Reabri a issue pra facilitar a busca e inseri a label [Resolvido], ok?

**Comment by gabrieldarezzo** [comment]
Sem problemas haha
Estava agora mesmo olhando o padrão, e realmente a galera não utiliza o 'Close' xD

De qualquer forma a ideia minha continua no ar para solicitar a permissão de acordo com o navegador.

**Comment by raphaguasta** [comment]
@gabrieldarezzo Achei algo que pode interessar, a Permissions API: [https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API/Using_the_Permissions_API](url)

O suporte não é dos melhores, mas chrome e firefox (sempre) já suportam!
[http://caniuse.com/#search=permission](url)
