### ISSUE TITLE
[Convite/Free] 1º CodePen Meetup Brazil (Sorocaba - SP)

### ISSUE THREAD

**Issue by felipebernardes** [frontendbr/forum#311]
Oi pessoal!

Vim convidá-los a participar do **primeiro meetup oficial** do CodePen no Brasil! :-)

Será dia 22 de outubro, em Sorocaba - uma cidade que fica a 1h20 da capital. A organização vai receber na rodoviária quem vir de fora. O @eduardojmatos e a Keit Oliveira são dois palestrantes já confirmados! :-)

Detalhes e inscrições pro evento [aqui](https://nvite.com/CodePenSorocaba/cbda)

Lembrando que o evento é grátis e todos são muito bem vindos :-)

Valeuuu!

**Comment by LFeh** [comment]
Da hora, boa sorte @felipebernardes :)

**Comment by theandersonn** [comment]
@felipebernardes Temos uma seção focada em eventos, poste aqui :)
https://github.com/frontendbr/eventos/issues

**Comment by felipebernardes** [comment]
opa, valeu @LFeh e @theandersonn . Foi mal! vou fechar aqui e colocar lá.
