### ISSUE TITLE
Google fact-check (aka schema.org/ClaimReview)

### ISSUE THREAD

**Issue by fititnt** [frontendbr/forum#327]
Relacionado: 
- https://github.com/schemaorg/schemaorg/issues/1061
- http://pending.schema.org/ClaimReview
- http://schema.org/ClaimReview
- https://blog.google/topics/journalism-news/labeling-fact-check-articles-google-news/
- https://news.google.com/ (ainda não disponível no Brasil)

--- 

Noticias completas
- [TechTudo, Google anuncia Fact Check; recurso checa se notícia é verdadeira ou falsa](http://www.techtudo.com.br/noticias/noticia/2016/10/google-anuncia-fact-check-recurso-checa-se-noticia-e-verdadeira-ou-falsa.html)
- [Google will now help you fact-check Trump (and other lies)](http://thenextweb.com/google/2016/10/14/google-will-now-help-fact-check-trump-lies/)

---

Exemplo com Schema.org (JSON-LD)

```json
{
    "@context": "http://schema.org",
    "@type": ["Review", "ClaimReview"],
    "datePublished": "2014-07-23",
    "url": "http://www.politifact.com/texas/statements/2014/jul/23/rick-perry/rick-perry-claim-about-3000-homicides-illegal-immi/",
    "author": {
        "@type": "Organization",
        "url": "http://www.politifact.com/"
    "twitter": "@politifact"
    },
    "claimReviewed": "More than 3,000 homicides were committed by \"illegal aliens\" over the past six years.",
    "claimReviewSiteLogo": "http://static.politifact.com/mediapage/jpgs/politifact-logo-big.jpg",
    "reviewRating": {
        "@type": "Rating",
        "ratingValue": 1,
        "bestRating": 6,
    "text": "True",
    "image" : "http://static.politifact.com/mediapage/jpgs/politifact-logo-big.jpg"
    },
    "itemReviewed": {
        "@type": "CreativeWork",
        "author": {
            "@type": "Person",
            "name": "Rich Perry",
      "title": "Former Governor of Texas",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Gov._Perry_CPAC_February_2015.jpg/440px-Gov._Perry_CPAC_February_2015.jpg",
            "sameAs": [
                "https://en.wikipedia.org/wiki/Rick_Perry",
                "https://rickperry.org/"
            ]
        },
        "datePublished": "2014-07-17",
    "sourceName": "The St. Petersburg Times"
    }
}
```

---

**Quem mais aqui tem cliente que é da área de jornalismo ou entusiasta de semântica?** Essa novidade pode afetar muito jornalismo, e pode ser algo que maioria dos jornais do Brasil vão demorar para adotar. **Se mesmo quem tem site menor de notícias ai quiser chegar junto pra fazer testes, creio que rola já deixar algo pronto para quando surgir no Brasil**

**Comment by LFeh** [comment]
Uso muito o schema.org. Interessante isso.

**Comment by fititnt** [comment]
Esse tópico evoluiu para o [Grupo de Pesquisa e Desenvolvimento - Foco conteúdo para Web](https://github.com/webiwg/webiwg-issues/issues/29) coordenado pela @icoffani que, dentre outras coisas, vai nos próximos meses ficar em contato também com jornalistas, e não apenas esse tópico.

Interessados podem entrar em contato direto com a Isadora.
