### ISSUE TITLE
:root vs HTML

### ISSUE THREAD

**Issue by raphaguasta** [frontendbr/forum#335]
Pessoal!

Estava lendo sobre o seletor :root, e como o próprio [MDN](https://developer.mozilla.org/pt-BR/docs/Web/CSS/:root) diz, ele é o elemento de mais alto nível num documento, seja HTML, SVG, etc.

No caso do HTML, quando eu desejo estilizar o elemento mais alto _<html>_, qual seletor vcs indicam? O selector _:root_ ou _html_? Há alguma diferença de performance?

Existe alguma boa prática onde o uso desse elemento faz mais sentido?

Valeu!

**Comment by LFeh** [comment]
@raphaguasta Nunca usei o :root para estilização na verdade, mesmo quando quero definir por exemplo, o `font-size` para usar REM, defino no HTML.

**Comment by Mendrone** [comment]
type selectors tipo html, div, p, etc, são mais performáticos que pseudo-selectors tipo :hover, :after, :before... A lógica seria essa regra se aplicar também ao seletor :root. 

Nunca fiz nenhum tipo de teste. (testar performance de CSS costuma ser um saco)

**Comment by raphaguasta** [comment]
@LFeh Boa, mesma coisa aqui...

@Mendrone Bem lembrado, faz sentido! Se não houver necessidade acredito ser melhor chamar o selector mais alto mesmo (HTML).

Bom, então até agora, ainda não achei nenhuma razão pra utilizar o :root....

**Comment by Mendrone** [comment]
Quando falamos de HTML não faz realmente nenhum sentido utilizar o pseudo-selector :root, acredito que ele tenha sido criado pensando em aplicações do CSS além do HTML, tipo XMLs ou SVGs.

**Comment by afonsopacifer** [comment]
Lembrando que o *:root* é amplamente usado para definir custom properties (variables) no "escopo global" da sua folha de estilo  ;)

exemplo:

```
:root {
--cor: #fff;
}

.exemplo {
background: var(--cor);
}
```

Mains infos sobre custom properties: 
http://tableless.com.br/como-usar-variaveis-no-css-de-forma-nativa/

ps: Lembrando que o suporte para a spec descrito nesse artigo esta desatualizado, hoje em dia tem um suporte bem melhor:
http://caniuse.com/#search=variables

**Comment by leonardoelias** [comment]
@afonsopacifer só um parêntese, hoje você já trabalha com variáveis nativas ? Achei muito grande para escrever toda hora :( Qual sua opinião ?

**Comment by afonsopacifer** [comment]
Eu uso sim @leonardoelias :)
Existe uma grande vantagem em usa-las, que é o fato funcionarem em "run time", ou seja.. diferente de uma variavel de um preprocessor por exemplo, ela nao e compilada local, ela esta presente na sua aplicação em produção e pode ter ser valor alterado e modificar totalmente o seu layout online apenas mudando seu valor... seja com js ou com uma @media.. isso torna seu CSS menos estático e abre portas para uma nova forma de pensar seus estilos...

ou seja.. é puro amor ❤️

**Comment by raphaguasta** [comment]
Legal @afonsopacifer !! Não tinha visto essa possibildade.

Sem dúvida a variável nativa deve ser melhor que dos preprocessors, uma pena o Edge não ter implementado ainda! =(

Legal essa idéia de mudar as variáveis em produção! Lembro daqueles casos de mudar cor de temas de templates e etc.

Aliás, achei ume exemplo bem legal desse caso que citou: https://codepen.io/wesbos/pen/adQjoY
Confere aí tb @leonardoelias

**Comment by leonardoelias** [comment]
Muito legal @raphaguasta.Então, eu usei nos meus últimos projetos, porém o modo que declaramos a variável achei extenso.

**Comment by raphaguasta** [comment]
@leonardoelias Realmente um pouco maior do que no sass/less/stylus. Mas pra mim não acho um problema não, vale o preço.

Pra mim o problema seria suporte.. Vc usou algum posprocessador/fallback? (https://github.com/MadLittleMods/postcss-css-variables)

**Comment by afonsopacifer** [comment]
Geralmente eu escrevo as variaveis de forma progressiva para nao quebrar em browser sem support, ou uso dentro do Polymer (trabalho com polymer rsrs) que tem um Polyfill interno para lidar com isso.

Quando preciso compilar as variaveis locais, uso o [bananacss](https://github.com/bananacss/bananacss), que alem de compilar as variaveis resolve outros problemas chatos ai na minha vida rsrsrrsr

**Comment by raphaguasta** [comment]
Legal @afonsopacifer ! Mas como assim declarar as variáveis de forma progressiva?

Achei um outro link bem legal que fala sobre possibilidades das variáveis, e que tbm mostra o uso do :root como vc disse:
https://css-tricks.com/difference-between-types-of-css-variables/

**Comment by akfzambrana** [comment]
@afonsopacifer e aquela historia de que usar as "funções nativas do CSS" é menos performático, procede?

**Comment by dougaraujos** [comment]
A iniciativa é bem interessante, principalmente no quesito de dinamismo e interação via JS.
Porém, se formos prezar pela performance, entendo que o código final (produção) deve conter o mínimo de processamento em todos os âmbitos, e no caso, um processamento var() é mais custoso (ainda que quase irrisório).

Outrossim, é a questão do fallback. Apesar do processamento abstraído no Polyfill, nem sempre vale à pena o custo.

Acho que a questão a se pesar, é o custo de processamento do dinamismo via JS usando as variáveis CSS.

**Comment by LFeh** [comment]
Poxa pessoal, uma discussão tão foda dessas podiam ter aberto outra issue pra segmentar melhor, haha

**Comment by raphaguasta** [comment]
Bons pontos @akfzambrana e @dougaraujos ... No meu caso, é difícil trabalhar em algum projeto sem algum pré processador. Pra trabalhar com o pré processador + fallback pode dar um trabalho que talvez seja dispensável.

No caso de uma manipulação JS, para algo como mudança de temas, ou etc. Acho que vale a pena.

Agora pensando só na performance... Em um futuro próximo, quando pudermos utilizar o recurso sem fallback, será que vale a pena usar as variáveis nativas, ou continuar utilizando dos pré processadores?

@LFeh Pois é, a discussão acabou se extendendo de um jeito inesperado. Bem legal! hahah

**Comment by afonsopacifer** [comment]
Eu acho besteira se preocupar com a performance de um CSS mais dinamico... quando geralmente de carrega um bundle cheio de paraneus de JS que faz e acontece e ninguém fala nada, pq aceita que JS é para isso... mas a questão é.. CSS agora tbm é assim, é para ser mais dinamico mesmo... acho que vale refletir sobre isso.

@akfzambrana naturalmente quando vc demanda processamento no cliente e deixa de fazer um build local.. mas isso não é menos performático.. é o normal se vc quiser usar CSS como ele é hoje em dia.. até pq usar um préprocessor não é mais performatico, isso pq um préprocessor  é focado em melhorar a vida do Dev.. ele não influencia no código em produção.. já as funções nativas são focadas em tornar algo mais dinamico em produção.... ou seja, não vale a pena usar variaveis nativas e demandar um processamento a mais se vc não for usa-las de forma dinamica.. uma sugestão é escrever elas sempre nativas e usar algo para compilar.. ai vc já se acostuma a sempre usar da mesma forma.. quando compilado ou não.

Sobre Fallback... vc não precisa necessariamente de um Fallback ou Polyfill.... vcs podem criar de forma progressiva... de forma que não quebre onde não é suportado mas que oferece uma melhor experiencia para quem tem suporte (no caso das variaveis garanto que uns 80% dos users tem suporte).. Isso é complicado mesmo, mas vale a pena.. usar o CSS mais novo sempre vai valer apena... engraçado que todo mundo usa ES6 com babel e ninguem questiona se é bom... já CSS sofre um preconceito básico...

**Comment by akfzambrana** [comment]
> não vale a pena usar variaveis nativas e demandar um processamento a mais se vc não for usa-las de forma dinamica
muito interessante, realmente saber quando utilizar as coisas é um dos maiores desafios na nossa vida profissional.

> usar um préprocessor não é mais performatico, isso pq um préprocessor é focado em melhorar a vida do Dev
Verdade... utilizar um preprocessador tem a mesma performance de usar CSS comum, vai depender de como vc fez seu código e separou a componentização. 
Eu sonho com o dia de poder utilizar apenas CSS para fazer as coisas, no entanto, **para projetos muito grandes** e que não terão dinamismo (como você mesmo comentou) acredito que mesmo com o CSS4 a vantagem de utilizar um preprocessador irá permanecer, pois é uma ferramenta que ajuda a aumentar a produtividade do desenvolvimento, é como usar um framework CSS so que sem precisar carregar tudo em produção, somente os "tecos" que você realmente está utilizando.

>no caso das variaveis garanto que uns 80% dos users tem suporte
Neste caso acredito que tem a ver com o perfil do usuario da "aplicação/site" que você está desenvolvendo, muitas empresas como a que eu trabalho, ainda dão suporte a navegadores ultrapassados por conta da necessidade de atender todo mundo. Nós por exemplo, damos suporte para IE9 😢

**Comment by dougaraujos** [comment]
@afonsopacifer @raphaguasta Pois é. Ambientes de desenvolvimento (testing, homologation) é interessante a liberdade de usufruir o máximo de features nativas possíveis, até mesmo para a familiaridade e aprendizado. 

Acho que a questão de "aceitar JS" é relativo a maturidade do desenvolvedor, até porque dinamismo é realidade em CSS faz tempo. (Unidades relativas, media-queries, functions calc(), content(), ...). 

O que mais dificulta é a falta de know-how, maturidade, feeling para resultar melhor experiência aos usuários, escalabilidade, resolução e implementação de soluções em cada realidade/necessidade.

Agora, a questão de performance que citei, foi justamente comparar soluções: O quão melhor seria implementar variáveis CSS e manipular seus valores via JS para resultar no dinamismo, comparando com as soluções já existentes?

**Comment by afonsopacifer** [comment]
@dougaraujos Eu particularmente nunca testei a performance de manipular as variaveis de CSS com JS.. ate pq no meu dia a dia eu as manipulo com @media.. mas vou fazer um teste sobre perf com js VS apenas JS..  e posto os results aqui.. :)

**Comment by dougaraujos** [comment]
@afonsopacifer Opa, seria interessante. Vou aguardar.

Pode parecer irrelevante bater na tecla de performance de uma simples feature CSS, mas eu lembro que o Chrome postergou a implementação de variáveis no início, e uma das razões era justamente performance.

**Comment by raphaguasta** [comment]
Pessoal!

Minha dúvida inicial, acredito que a discussão inicial, que era sobre :root vs <html> foi encerrada.

Transferi nossa discussão sobre variáveis CSS para a issue #342 .

Obrigado à todos que responderam aqui!

Nos vemos lá! :)

**Comment by LFeh** [comment]
👏 👏 👏 👏 👏 👏 👏 👏

**Comment by HackerGaucho** [comment]
Achei confusa a função desse :root. Qual a diferença dele e do *? 
[Exemplo](https://jsfiddle.net/oj99b81c/)

**Comment by fdaciuk** [comment]
@HackerGaucho o `:root` é pra pegar somente o elemento raiz (no caso do HTML, a tag `<html>`), mas no caso de um SVG ou XML, o elemento raiz pode variar. Aí é que entra a importância de usar o `:root` =)

E o `*` serve para **todos** os elementos dentro de um contexto.

Se usar `*` no contexto global, ele vai pegar todos os elementos. Se fizer `div *`, ele pega todos os elementos dentro da `div`, e assim por diante =)

**Comment by HackerGaucho** [comment]
@fdaciuk perfeito, agora entendi, :root = geral e * = contextual :) valeu cara.

**Comment by fdaciuk** [comment]
Isso! Só que o `*` casa com vários elementos. O `:root` só casa com 1 =)
