### ISSUE TITLE
Por que troquei o atom pelo nano

### ISSUE THREAD

**Issue by ghost** [frontendbr/forum#347]
[hackergaucho.com/post/por_que_troquei_o_atom_pelo_nano](http://hackergaucho.com/post/por_que_troquei_o_atom_pelo_nano?via=gitfebr)

**Comment by robsonbittencourt** [comment]
Incrivelmente aqui o VSCode no Ubuntu foi liso e no Windows deu umas travadas...

Uso editores como o nano e o vim (não conheço os detalhes e as diferenças) somente quando estou em algum server e preciso editar algo pontual. 

Sinceramente não consigo me imaginar trocando um editor como Sublime, VSCode ou Atom (interface) por um que seja exclusivo no terminal. Mas sei que assim como você, muitas pessoas fizeram isso e são super produtivas.

**Comment by HackerGaucho** [comment]
@robsonbittencourt  talvez seja o meu desktop, tô usando o [awesome](https://awesomewm.org/) que é mais focado no modo CLI e tal. até o Atom já deu umas travadas nele hehe

**Comment by idlua** [comment]
Achei interessante a decisão pelo nano, nunca cogitei adotar ele como editor principal.

Sobre o ponto que você apontou sobre o Vim no artigo, isso pode ser resolvido com um remap, algo como: `nmap <C-s>w :w!<CR>`. Assim, você consegue salvar o arquivo usando sempre `Crtl` + `S`, como é o mais comum entre os editores.
Caso queira tentar o Vim novamente fica aí a dica! :D

Sobre o ponto sobre o Sublime: também **odeio** isso nele!

Curti bastante a estrutura do seu blog!
