### ISSUE TITLE
Problema ao carregar font-awesome com o SASS

### ISSUE THREAD

**Issue by furabio** [frontendbr/forum#349]
Os ícones ao serem carregados estão bem diferentes. Alguém sabe o que está acontecendo ?

![gg](https://cloud.githubusercontent.com/assets/21022468/19943375/4754cb96-a11e-11e6-9257-1a030c59695d.png)

minha estrutura de arquivos está assim :
```
| css
    main.css
| sass
    | tools
        _vendors.sass
    main.sass
```
estou carregando o font-awesome da seguinte maneira :

_vendor.sass : 

```
// Bootstrap-Sass
@import ../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap

// Font-Awesome
@import ../../bower_components/font-awesome/scss/font-awesome
```

main.sass : 

```
@import settings/variables

@import tools/mixins
@import tools/vendors

@import generic/reset

@import components/header

```

**Comment by Kirmayrtomaz** [comment]
Ele tá indo atrás de um path que não existe, olhando o bower dele. Uma ideia seria vc alterar o arquivo

`bower_components/font-awesome/scss/_variables.scss` 

```
$fa-font-path:        "../fonts" !default;
```
para

```
"/bower_components/font-awesome/fonts" !default;
```

Mas não sei se existe uma solução melhor. =X

**Comment by LFeh** [comment]
@furabio Não vale a pena começar a usar SVG para icones? :)

**Comment by furabio** [comment]
@Kirmayrtomaz muito obrigado funcionou perfeitamente.

@LFeh Sou novo nesse mundo do front-end, me fale mais sobre usar o SVG rsrsrs, qual a diferença dele para os ícones do font-awesome ?

**Comment by LFeh** [comment]
Se liga @furabio:

#77 #10

**Comment by furabio** [comment]
@LFeh muito obrigado vou ler.

**Comment by leandroruel** [comment]
lembrando que agora tem a versao SVG do fontawesome https://www.kickstarter.com/projects/232193852/font-awesome-5?ref=c92610

**Comment by furabio** [comment]
@Kirmayrtomaz quando este problema acontece no _scss_ basta eu trocar na **_variables.scss**, mas e quando estou apenas importando o **css/font-awesome.css** ou **css/font-awesome.min.css** e acontece isso : 

![90b0d83a-a780-11e6-9e3f-32ce1465afb5](https://cloud.githubusercontent.com/assets/21022468/20198857/2b6dbb24-a78e-11e6-9b95-54a59a87227c.jpg)

Onde arrumo ?
