### ISSUE TITLE
@deppbrazil

### ISSUE THREAD

**Issue by deppbrazil** [frontendbr/forum#355]

**Comment by deppbrazil** [comment]
@LFeh 

> Consigo deletar uma issue aberta por acidente? no começo eu era novato aqui e abri essa por acidente e você fechou, porém ela aparece nas minhas Issues aqui e me incomoda porque tenho TOC... kkkkk tem como me ajudar a deletar essa?

**Comment by LFeh** [comment]
Relaxa, deixa fechada, não da pra deletar ;)

**Comment by deppbrazil** [comment]
@LFeh blz então manoo.....valew =)
