### ISSUE TITLE
Especializações na carreira Front End

### ISSUE THREAD

**Issue by raphaguasta** [frontendbr/forum#356]
Pessoal! Pegando inspiração na discussão do #353, resolvi abrir uma outra aqui, falando sobre um ponto que eu estava lendo/pensando semana passada.

O desenvolvimento front end têm crescido muito nos últimos anos, e o nível de skills/ferramentas que precisamos ter é cada dia maior.
Imaginem, um front precisa entender o básico de UI/UX, SEO & Semântica, Acessibilidade, Performance, css, svg, canvas, Programação em JS, frameworks, lógica, testes, web, protocolos (http,ftp), node, task runners, e mais mil tópicos.

Antigamente era perfeitamente aceitável procurar um front expert em html/css e pronto.
Hoje, com essa diversidade de conhecimentos necessários, naturalmente começa a ficar impossível uma pessoa ser expert em tudo isso.

O que parece, é que já surgem algumas divisões dentro da área de front:
(Lista original: [https://www.frontendhandbook.com/practice/types-of-front-end-dev.html](url))

- Front-End Developer/Engineer 
- CSS/HTML Developer
- Front-End JavaScript Developer
- Front-End Web Designer
- Web/Front-End User Interface ou Developer/Engineer
- Mobile/Tablet Front-End Developer
- Front-End SEO Expert
- Front-End Accessibility Expert
- Front-End Dev. Ops
- Front-End Testing/QA

Na prática gostaria de saber de vcs. Onde trabalham existem divisões de especialidades no time de front? Vcs se encaixam em alguma dessas definições?
Existe alguma divisão que está sendo popularmente utilizada? Qual seria o time de front ideal pensando nessa divisão?

Valeu! :)

**Comment by LFeh** [comment]
Tivemos uma discussão enorme sobre isso, se liga #32

**Comment by raphaguasta** [comment]
Opa! Aí sim!!!

Vou consultar lá. Valeu @LFeh!!
