### ISSUE TITLE
Problema com instalação do Virtualbox.

### ISSUE THREAD

**Issue by ranosi** [frontendbr/forum#367]
Pegando carona na issue sobre desenvolver no linux, to com problema pra dar start no Virtual Box. Instala tudo certo mas na ora de rodar dá erro, 'modprobe vboxdrv'. To rodando Google afora mas até agora nada de resolver. Ubuntu 16.04 aqui. Alguem já teve esse problema?

Abraços

**Comment by RatoX** [comment]
Posta a mensagem de erro ai vei.

**Comment by ranosi** [comment]
Vamos lá:
Kernel driver not installed (rc=-1908)

The VirtualBox Linux kernel driver (vboxdrv) is either not loaded or there is a permission problem with /dev/vboxdrv. Please install virtualbox-dkms package and load the kernel module by executing

'modprobe vboxdrv'

as root. If it is available in your distribution, you should install the DKMS package first. This package keeps track of Linux kernel changes and recompiles the vboxdrv kernel module if necessary.

where: suplibOsInit what: 3 VERR_VM_DRIVER_NOT_INSTALLED (-1908) - The support driver is not installed. On linux, open returned ENOENT. 

---------------------------------------------------------------------------------------------------------------------------------
Daí no terminal:
$ virtualbox
WARNING: The character device /dev/vboxdrv does not exist.
	 Please install the virtualbox-dkms package and the appropriate
	 headers, most likely linux-headers-generic.

	 You will not be able to start VMs until this problem is fixed.

Já busquei sobre isso, fiz algumas coisas que indicaram e nada.

**Comment by ranosi** [comment]
Caras consegui resolver por esse tuto. https://forums.kali.org/showthread.php?31306-VirtualBox-DKMS-problems

<code>
>sudo apt purge virtualbox-dkms
>sudo apt purge virtualbox
>sudo sudo mokutil --disable-validation
>reboot
</code>
then, on reboot, disable the secure boot through the GUI
<code>
>sudo apt install virtualbox
>sudo apt install virtualbox-dkms
</code>

Dizem para desativar o Secure Boot, e vi por aí que isso não seria uma opção realmente boa.
http://askubuntu.com/questions/755238/why-disabling-secure-boot-is-enforced-policy-when-installing-3rd-party-modules
https://wiki.ubuntu.com/SecurityTeam/SecureBoot

Cheguei a tentar do modo seguro mas também não funcionou. Pretendo ver isso com mais calma depois, mas por hoje preciso usar dessa forma mesmo.

Fica aí a dica pra quem tiver problemas com VM no Ubuntu 16.
