### ISSUE TITLE
Slack da FrontEnd Brasil

### ISSUE THREAD

**Issue by rickbenetti** [frontendbr/forum#37]
Como faz pra ser convidado?

Como não sou fã do facebook, último lugar que olho é lá e assim para assuntos técnicos tenho transferido ou sido transferido para grupos no slack, e não vi aqui  no github forma alguma de acessar ou ser convidado.

**Comment by LFeh** [comment]
Não sei quem está cuidando disso. @eduardojmatos, você sabe?

**Comment by eduardojmatos** [comment]
@LFeh @rkb81 tem um repositório com todos os slacks BR e como participar, aqui => https://github.com/joselitojunior1/slack-list-brazil

Pra participar do Frontend Brasil => http://frontendbrasil-slack.herokuapp.com/

**Comment by felquis** [comment]
A lista acima funciona até hj, Porém está só um pouquinho desatualizada

Há mensagens de ontem de gente compartilhando informação útil. 

Para entrar no Slack https://frontendbrasil.slack.com/ - **vc deve primeiro** informar seu e-mail neste site http://frontendbrasil-slack.herokuapp.com/

**Comment by felquis** [comment]
De boinha fechar esse tópico
