### ISSUE TITLE
Diferença entre as listas 'dependencies' e 'devDependencies' no NPM

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/forum#397]
Oi! Blz?! :)

Estava olhando os comandos do npm e fiquei com dúvidas quanto à lista 'dependencies' e 'devDependencies'.

```bash
npm install –-save
npm i --saveDev
```

No caso dentro de um projeto eu tenho como ignorar a lista devDependencies?

Exemplo:

Na lista devDependencies ter dependências que eu preciso subir para o servidor e na lista dependencies colocar itens que poderei subir para produção como bootstrap, jquery?

**Comment by renatogalvones** [comment]
Se vc passar como argumento **--production** o objeto de devDependencies não é processado.

Aqui tem mais infos(tá em en): 
http://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies

**Comment by theandersonn** [comment]
Obrigado pelo feedback @renatogalvones :+1:
Vou olhar a referência agora mesmo.
