### ISSUE TITLE
Design Responsivo

### ISSUE THREAD

**Issue by joaopedron** [frontendbr/forum#40]
Galera atualmente como vocês estão trabalhando com imagens responsivas ?

Estão utilizando o `<picture>` `srcset` `sizes` ? ou estão utilizando alguma library JS ?

Abraços.

**Comment by raphaklaus** [comment]
Opa! Acho que tem uma issue sobre isso que pode te ajudar: #6 :smile:

**Comment by joaopedron** [comment]
@raphaklaus foi mal não vi o #6 obrigado!
