### ISSUE TITLE
Sistema web atualizável 

### ISSUE THREAD

**Issue by JoseCage** [frontendbr/forum#400]
Boas pessoal?

Alguém já teve experiência com desenvolvimento de app/sistema web que regularmente receba atualização pelo próprio sistema? Exemplo: tenho um sistema de gestão de documentos para um cliente com as features minimas no primeiro release (instalado no server do cliente) e mais adiante eu adicione novas funcionalidades e pretendo disponibilizar as atualizações para o cliente e que ela possa verificar se há atualizações disponíveis para instalar e consequentemente baixa-la pelo próprio sistema. **Tal como funciona no WordPress**.

Para um caso desses que ferramentas, opções usariam?

PS: No meu caso o sistema seria feito o backend com php, mas de um modo geral a linguagem não importa, quero mais é pegar o conceito..

**Comment by lucassmacedo** [comment]
Cara, não sei qual linguagem/framework voce usa.. mas eu vejo que poderia ser resolvido separado a aplicação em múdulos. Inclusive o Git tem um esquema legal de múdulos.. Mas no meu ponto de vista tudo isso ficaria mais facil de ser desenvolvido se o sistema ficasse em um host seu.. deixar pro client é complicado... mas deve existir uma solução mais prática =) 
#acmpanhando

**Comment by lucassmacedo** [comment]
Vou dizer a minha experiencia. Por exemplo, eu utilizo o Laravel + Forge, o forge faz o deploy da aplicação, só precisa estar configurado junto ao Github ou Bitbucket. Assim voce pode criar um script que lista a quantidade de "commits" ou tags, do git no painel do cliente. E colocar o botão atualizar, rodando um script bash que faz o pull dos arquivos via git, como eu citei no post acima, voce pode usar o git submodules ou como achar melhor. Usando Hooks do GIT você tem  um arquivo Bash para trabalha como quiser antes e depois das ações do Git. Eu fiz um [post](http://lucasmacedo.blog.br/rodando-testes-com-pre-commit-git-hooks-laravel/) usando o pre-commit como exemplo. 
Eu vejo que nesse caminho é possivel fazer algo bem estruturado. Mas claro é o meu ponto de vista. Penso que existem outras formas de fazer.

**Comment by JoseCage** [comment]
Exato @lucassmacedo  Obrigado pelas dicas, opiniões até agora.. 👍

**Comment by JoseCage** [comment]
Mais Feedbacks pessoal?? ❓

**Comment by LFeh** [comment]
@frontendbr/admins

**Comment by fdaciuk** [comment]
Nunca cheguei a fazer isso, mas tenho algumas teorias que podem te ajudar:

- mantenha os arquivos que fazem parte do _core_ da sua aplicação separados de arquivos que o usuário possa, de alguma forma, alterar;
- na aplicação que você vai disponibilizar, crie uma função que deverá ser executada de tempos em tempos, para saber se há novas atualizações. Você pode usar websockets, chamar a função a cada reload de página, a cada x tempo, a cada x requests, usando cron, etc. Fica a seu critério definir qual o melhor momento de buscar por uma atualização. Preferencialmente, de forma assíncrona;
- crie uma API que irá centralizar as versões da sua aplicação. É essa API que será consultada pela função criada acima. Se houver alguma  nova versão (que você pode preencher manualmente, pegar do GitHub ou algum outro repositório, etc), essa API deve conter a informação;
- no momento da atualização, sua aplicação precisa saber, de alguma forma, que essa atualização está acontecendo. O WP cria um arquivo `.maintenance` na raiz da aplicação enquanto uma atualização está sendo feita. Tem seus pontos de falha, mas é uma boa ideia. Assim que a atualização acabar, delete o arquivo.

Bom, se eu precisasse fazer um sistema desse tipo hoje, eu usaria esses passos que citei acima. É apenas uma ideia. Podem existir caminhos melhores, pode estar faltando coisas a se fazer, mas acredito que com essa base você consegue seguir =)

**Comment by JoseCage** [comment]
Muito obrigado pelas dicas @fdaciuk .. Com certeza que valem.. 
Vou estudar um pouco mais e ver qual métodos posso aplicar.. 👍 👍
