### ISSUE TITLE
Estrutura de diretórios com Vuejs

### ISSUE THREAD

**Issue by leandroruel** [frontendbr/forum#408]
Olá galera, estou estudando o Vuejs, para começar a usar num projeto, eu usava o angular antes, agora quero saber como construir e organizar uma estrutura de diretórios com Vuejs, eu andei pesquisando mas encontrei exemplos bem básicos, alguém teria algum exemplo para mostrar?

**Comment by victormiguez** [comment]
Invoco o @luisfmsouza.

**Comment by alexsandro-xpt** [comment]
Ja tentou usaro Vue CLI? ele gera o diretório todo pra voce e possui 5 templates com estrutura de diretorios prontos pra voce https://github.com/vuejs/vue-cli

**Comment by edmolima** [comment]
Uma estrutura que adoto seja vue ou react é:

**app/
  ./assets/
  ./components/
  ./templates/**
  * index.html - aqui basicamente é o html da single page.

_index.js_ (o arquivo principal).

**webpack/**
 * arquivos de configurações do webpack (prod, dev e base).

**bin/**
* tasks (scripts para clean, build, deploy e etc).
webpack.config.js

No geral me atende bem, é bem parecido com a organização de diretórios do RoR! Mas uma sugestão é fazer o que o @alexsandro-xpt citou, usa o Vue-CLI que nele já tem alguns templates predefinidos!

**Comment by felisio** [comment]
Dentro da documentação do Vuex também tem um exemplo de estrutura, baseado no Vue-cli, e tem um projeto de exemplo.

https://vuex.vuejs.org/en/structure.html

**Comment by luisfmsouza** [comment]
Valeu @victormiguez !

A estrutura do Vuex é bem parecida com a que utilizamos hoje. Com a diferença que temos uma separação por páginas(e não um `main.js` que controle tudo) e também não utilizamos `.vue`.

De uma forma simplificada temos:

```
├── pagina-1 // podemos ter várias páginas
│   ├── index.js
├── componentes // podemos ter vários componentes
    └── componente-1
        ├── component-1.js
        ├── component-1.scss
        ├── template.html
```

**Comment by leandroruel** [comment]
@luisfmsouza gostei... mas ai, isso é para um projeto simples?  eu estou trabalhando em refazer todo o sistema de uma faculdade. financeiro, acadêmico, portal do aluno e etc. é isso que me preocupa na estrutura, se ela vai ser escalável e não vai ficar bagunçada

**Comment by luisfmsouza** [comment]
Por enquanto o nosso projeto ainda não está grande. E até por isso já temos algumas mudanças em vista.

Uma opção seria seguir a estrutura que vocês já tem, apenas encaixando o Vue. Ou então começar com uma estrutura simples e ir incrementando conforme a necessidade, afinal tem muitos problemas que vão surgir no meio do caminho e não temos como prever no início.

**Comment by leandroruel** [comment]
estou vendo que o webpack é essencial em projetos com Vue... é mais uma coisa para aprender...

**Comment by felisio** [comment]
@leandroruel trabalho em um erp todo feito em Vue.js e estamos usando a seguinte estrutura

```sh
  src/
    |__ components  # Estrtutura especifica do projeto.
       |__ Area   # a area do software ex: Financeiro, Operacional
          |__ Modulo   # ex: Banco - todos os components referente a Banco
              |__ FormBanco.vue   # nesse caso o component de formulario de cadastro do Banco
              |__ ListBanco.vue   # nesse caso o component que lista os Banco
    |__ assets   # assets do projeto
    |__ commons   # Components Comuns a todos
    |__ graphql # todas as querys do graphql
    |__ helpers # bibliotecas de funções puras em js
    |__ vuex # toda a estrutura do vuex
    |__ mixins # Mixins Vue usado no projeto
```

espero que tenha captado a ideia...

**Comment by leandroruel** [comment]
@felisio agradeço pelo exemplo, já me deu uma boa clareada, vocês usam webpack também?

**Comment by felisio** [comment]
@leandroruel sim estou usando vue-cli com webpack

**Comment by vedovelli** [comment]
Aqui há um starter kit com o qual tive o prazer de colaborar. Talvez ajude!

https://github.com/codecasts/spa-starter-kit

**Comment by leandroruel** [comment]
pessoal, só uma dúvida: é melhor eu configurar o router num arquivo externo ou no próprio componente?

**Comment by filipemerker** [comment]
Se serve como referência, tem um projetinho do próprio [Evan You](https://github.com/yyx990803) que é um clone do hacker news em Vue.
[Ali ele usa algo assim:](https://github.com/vuejs/vue-hackernews-2.0)

```shell
  public/ # assets do projeto, imagens, svgs, jsons, etc...
  src/
    |__ components # componentes do projeto, ex.: comentário, lista se comentários, post,lista de posts, etc... 
    |__ filters # filters que serão utilizados nos components
    |__ router # vue-router
    |__ store  # api utils e vuex store
    |__ views # telas do projeto, ex.: blog, home, etc...
```

Acho excelente essa forma de organizar o projeto e tento sempre me basear nela. Claro que sempre acabo criando um diretório de `utils` para colocar código de terceiros ou helpers.

Outra fonte que pode te ajudar é dar uma lida na [Lista de projetos open source](https://github.com/vuejs/awesome-vue#projects-using-vuejs) do [Awesome Vue](https://github.com/vuejs/awesome-vue). Lá tu pode encontrar uma série de projetos famosos que usam diferentes arquiteturas.

Por fim, lembre que uma estrutura de diretórios só é boa se funciona para você e seu time. Use algo que escale fácil. Esse exemplo do Hacker News clone serve muito bem para pequenos projetos, mas se tu vai desenvolver alguma aplicação de larga escala, certamente você vai ter que reorganizar essa estrutura para escalar melhor.

## Estrutura escalável
Para usar um exemplo pessoal, acho que deixar componentes e views misturados e só separar em um diretório o que for compartilhável funciona melhor para grandes aplicações. Um exemplo do [boilerplate de Vue](https://github.com/filipemerker/vue-boilerplate/) que eu criei para tocar projetos na empresa que eu trabalho:

```shell
  src/
    |__ filters # filters que serão utilizados nos components
    |__ router # vue-router
    |__ store  # api utils e vuex store
    |__ screens # telas do projeto, ex.: blog, home, etc...
        |__ Blog
            |__ Blog.vue # código da tela de blog
            |__ components # componentes restritos ao blog
                |__ Post.vue
        |__ Contact
            |__ Contact.vue
            |__ components
                |__ Form.vue
    |__ shared
        |__ components # componentes que serão compartilhado em diferentes screens
            |__ ListItem.vue
```

Percebe como dessa forma o diretório de componentes não fica sobrecarregado e você sempre consegue ver claramente quem pertence a quem?
Enfim, ao adotar uma estrutura de diretórios para seus projetos, sempre tenha em mente a escalabilidade e o nível de engajamento do seu time. Se funcionar para todos e escalar bem, está ótimo.

Espero ter ajudado.

**Comment by leandroruel** [comment]
@filipemerker Boa filipe! obrigado pela dica!

**Comment by danilovaz** [comment]
@filipemerker caraca, tô começando um projeto em Vue agora e seu comentário já me deu um norte mais organizado pra seguir :beers:

**Comment by x1john** [comment]
Vlw @filipemerker

**Comment by nebenzahl** [comment]
Estou montando uma estrutura, me baseando no que vi em aulas do Prof. Plinio Naves.
Acredito ser bem maleável e pode suportar um projeto gigante. Mantendo uma ordem e coerência. Em um projeto grande, não é nada bom ficar indo e vindo nos diretórios, e examinando arquivos com muitas linhas. Em um diretório está aninhado a maioria das coisas relacionadas a ele. Eu acredito que conforme for usando, vai se aperfeiçoando, mas inicialmente vai ser assim. Estou apenas no inicio.

```
src/
    |__ assets
    |__ axios
    |__ router 
    |__ store  
    |__ components
    |__ mixins
    |__ resources
         |__ cadCliente
               |__ _store 
               |__ _components
               |__ _services
         |__ finReceber
               |__ _store 
               |__ _components
               |__ _services
```

Trabalhamos  em um sistema que trabalha com varias áreas.
A ideia é isolar tudo que é relacionado a um determinado componente em um lugar só, e componentes que forem usados em mais d eum lugar concentrar em < components >, funções e outras coisas que forem usadas em todo o sistema colocar em mixins.
O interessante é colocar em arquivos, oq não se mexe muito como, importar as bibliotecas, e colocar em outro arquivo oque é relacionado ao componente.
