### ISSUE TITLE
Angular componentes

### ISSUE THREAD

**Issue by malaquiasdev** [frontendbr/forum#413]
Fala galera blz?

Estou estudando Angular 2 e estou pesquisando componentes prontos interessantes para utilizar em projetos rápidos, no momento não estou focado em criar componentes e sim em utilizar o framework no dia a dia.

No momento tenho olhado esses dois:

- Angular Material
- PrimeNG - PrimeFaces

Vocês teriam alguma indicação?

**Comment by paulinhapenedo** [comment]
@mmalaquias1 eu estou em um projeto de intranet sendo desenvolvido com Angular 2 e ontem descobri esse repositório com muito material legal [https://github.com/timjacobi/angular2-education](https://github.com/timjacobi/angular2-education). Tem uma seção sobre componentes prontos que é bem bacana. Espero que te ajude!

**Comment by mmalaquias1** [comment]
@paulinhapenedo obrigado pela dica! Já vi aqui... vai me ajudar bastante

**Comment by DaniloAgostinho** [comment]
👍 llinks muito foda... obrigado gente.
