### ISSUE TITLE
Como fazer efeito scroll com JS ?

### ISSUE THREAD

**Issue by adelmojnr** [frontendbr/forum#421]
Fala galeraaa, tudo bem? esses dias eu tô fazendo meu site e estou precisando de um efeito de scroll suave, tipo... eu clico em algum link do menu e ele me leva até uma determinada section, o lance é que não quero fazer isso com JQuery pelo fato de ser um iniciante no JavaScript. 

Será que vocês podem me ajudar?

Desde já, grato.

**Comment by rubenmarcus** [comment]
[JavaScript Smooth Scroll](https://www.google.com.br/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=javascript%20smooth%20scroll&oq=javascript%20smooth&rlz=1C1CHZL_pt-BRBR719BR723&aqs=chrome.1.69i57j0l5.3383j0j7)

**Comment by rubenmarcus** [comment]
Nessa resposta do [Stackoverflow](http://stackoverflow.com/questions/22246796/smooth-scrolling-with-just-pure-css) ele fala que dá pra fazer com CSS puro tambem, isso se o height da div não mudar: [DEMO](http://jsfiddle.net/YYPKM/3)

**Comment by adelmojnr** [comment]
Valeu @rubenmarcus, css<3  é lindo né ? mas aqui só com JS mesmo, mas muito obrigado pela dica xD
