### ISSUE TITLE
"Desafio" CSS - É possível fazer um grid com elementos de tamanhos diferentes orientados pelas linhas?

### ISSUE THREAD

**Issue by renatogalvones** [frontendbr/forum#426]
E ae negada, nos deparamos(@sergiokopplin) com esse cenário e juravamos que o flexbox matava isso sossegado, mas não conseguimos reproduzir nem achar nada parecido.

**Importante: Estamos tentando fazer isso usando somente CSS pra não ficar adicionando lib js à toa no builld.**

Exemplo:
![screen shot 2017-01-31 at 6 56 26 pm](https://cloud.githubusercontent.com/assets/302819/22484081/01a8d226-e7e7-11e6-9d01-098791e29084.png)

![screen shot 2017-01-31 at 7 07 28 pm](https://cloud.githubusercontent.com/assets/302819/22484439/8dd6cb9e-e7e8-11e6-914d-8da0be68f458.png)

Consegui encontrar vários exemplos de como fazer isso usando colunas onde a ordem dos elementos fica por conta da primeira coluna, mas não consigo achar nada que faça essa ordenação horizontal.

Libs que fazem isso:
[Masonry](http://masonry.desandro.com/)
[Salvatore](http://salvattore.com/)

**Comment by LFeh** [comment]
@renatogalvones Consegue soltar o código no jsfiddle pra gente brincar? 😄

**Comment by psicotropicos** [comment]
@renatogalvones Não seria isso [aqui](https://codepen.io/dudleystorey/pen/eAqzk)?

**Comment by renatogalvones** [comment]
É quase isso! rs

Seria mais isso [aqui](https://codepen.io/renatogalvones/pen/apqYLJ) que o direction tá para "row" mas sem esse "stretch" que dá na imagem 3.

Teria que rolar um encaixe tipo desses exemplos que mandei.

![screen shot 2017-01-31 at 7 47 10 pm](https://cloud.githubusercontent.com/assets/302819/22485789/1cf49c98-e7ee-11e6-8553-4d82397ac4bc.png)

**Comment by afonsopacifer** [comment]
Então, o @raphamorim criou uma solução para isso outro dia ❤️ 
http://raphamorim.io/waterfall.js/

**Comment by psicotropicos** [comment]
@afonsopacifer O Waterfall é um chuchuzinho mesmo, mas acho que o @renatogalvones está procurando não usar JS, se não tiver como, dai sim com JS (Recomendo muito o Waterfall).

**Comment by sergiokopplin** [comment]
galera, obrigado pela ajuda! Eu e o galvones procuramos hj mas não havíamos encontrado, mas acredito que esse waterfall atenda as necessidades do projeto!

**Comment by renatogalvones** [comment]
Show de bola @afonsopacifer! Muito legal esse waterfall.

Ainda vou pesquisar mais um pouquinho pra ver se acho alguma solução CSS only, mas é mto bom saber que tem um lib pequena e que faz o trampo sem pesar mto no build nem na execução.

Valeu pela força galera!
Qq novidade mando um update aqui.

**Comment by williamcosta** [comment]
@renatogalvones há um tempo atrás precisei fazer uma grid dessa mesma forma, a primeira coisa que veio na cabeça era que o **flexbox** resolveria essa questão com extrema facilidade.

Depois de um tempo tentando e pesquisando muito, acabei não achando uma solução **CSS Only** e apelei para a lib **Masonry** que você também citou.

Essa lib **waterfall** é coisa linda hein!

**Comment by renatogalvones** [comment]
É então, eu ainda tô tentando ver se é possível só com CSS, mas não tô muito otimista e o tempo que reservei pra isso já tá acabando... hauahuahuahuahua

**Comment by raphamorim** [comment]
Que bacana! :)

Quando eu criei o waterfall eu tinha 2 opções: Masonry e Flexbox
Problema: Masonry precisa do jquery e os dois juntos n sao baratos em termos de page load.
Flexbox é limitado pra formatos dinâmico, precisaria de um servidor entender o formato p poder renderizar corretamente
(acredite eu pesquisei mto sobre isso)

Não queria depender de nada entao comecei a trablhar em im algoritmo de sort de elementos. No final a gente colocou uma versão estável em produção na coca cola e na flag.

Existem outras soluções boas que tomha achado, mas nenhuma tinha 1kb.

Qualquer help que precisarem p implementar tamo ai ( recomendo usar a versão estável do waterfall )

**Comment by sergiokopplin** [comment]
@raphamorim abri uma issue lá pra adicionar umas coisas na documentação. mas a lib é show de bola, parabéns e obrigado.

**Comment by raphamorim** [comment]
irado, verei @sergiokopplin

**Comment by LFeh** [comment]
Acham que a lib do @raphamorim solucionou?

Posso labear como resolvida? :)

**Comment by sergiokopplin** [comment]
sim, resolvido!
