### ISSUE TITLE
Servidor Local para Desenvolvimento Front

### ISSUE THREAD

**Issue by m0ntelo** [frontendbr/forum#436]
Eu ainda uso xampp para criar um serve local. As fezes ele da uns erros inexplicáveis e acaba tomando bastante o meu tempo até que eu resolva.

Eu existe uma solução melhor para que desenvolve front? Pois trabalho com WP, Qual servidor local seria a melhor solução ?

**Comment by psicotropicos** [comment]
Você ja ouviu falar sobre o [Vagrant](https://www.vagrantup.com/)? Acho que é a melhor opção para você. E aqui esta um [box](http://vccw.cc/) para o vagrant com tudo que você precisa pra trabalhar com WP.

✌️

**Comment by williamcosta** [comment]
@WilsonMontelo o que está bastante em alta atualmente é o [Docker](https://www.docker.com/), caso queira aprender alguma tecnologia que pode ser um diferencial na hora de contratação.

E aqui um uma imagem para trabalhar com [WordPress](https://hub.docker.com/_/wordpress/).

**Comment by skyzito** [comment]
Se você quiser servir apenas seus HTML estáticos , basta ir até a pasta do projeto via terminal e executar o seguinte comando:

python -m SimpleHTTPServer 8000

Em MACOS e Linux isso já vem nativo , caso você esteja usando Windows , precisará instalar o python na máquina.

Essa é a forma mais simples que me veio em mente.

**Comment by hugocarreira** [comment]
Bom, creio que depende muito do seu gosto.
Como o pessoal já disse, existe o Vagrant, Docker, opções de server estáticos...

Trabalhei um bom tempo com o Vagrant, ele é pesado, demora pra ligar, mas me atendeu muito bem;
Logo após o Vagrant veio o Docker, apareceu se dizendo maravilhoso em reação ao vagrant. A configuração dele é ~~uma merda~~ complicado, você tem que aprender como ele funciona, vai quebrar muito a cabeça, vai bater de frente com problemas do tipo: estrutura de pastas (dentro do docker/seu pc)... Depois de um bom tempo, consegui domá-lo, porém se for pra escolher entre os dois, ainda prefiro o Vagrant pela sua simplicidade.

Masssssssssssss... Usei esses dois para desenvolvimento de back-end ou full-stack. Hoje em dia estou trabalhando na parte de front-end (node/angular/etc) e para tal tenho utilizado Gulp + Browser-sync e não quero mais nada na minha vida. ABSURDAMENTE simples, rodo todos meus projetos em menos de 1 segundo, live-reload, watch, bla bla e todas essa gracinhas que o Gulp permite.

Você pode escolher o caminho difícil e vai que passar horas para iniciar um projeto simples. Mas pode escolher para de complicar coisas que não precisam ser complicadas. 

Escolha o caminho da simplicidade, você tem que se preocupar (localmente falando) com seu site rodando e você conseguindo desenvolver... não precisa ficar enchendo a cabeça se ela ta rodando na porta XYZW com o IP tal, consumindo X de RAM, bla bla bla... vai por mim, escolha o simples, você vai ser mais feliz e produtivo.

**Comment by LFeh** [comment]
Se quiser rodar projetos estáticos simples em Node, pode usar o [http-server](https://www.npmjs.com/package/http-server), gosto bastante.

**Comment by thulioph** [comment]
O `http-server` me atende atualmente de boa, uso simples, prático e rápido.

**Comment by rubenmarcus** [comment]
Alguem já usou o Easy-Php? Inlcusive ele ja vem com módulos de cms pré-instalados, e pra leigos em Docker como eu, era um .exe q vc instalava e rodava

**Comment by psicotropicos** [comment]
@rubenmarcus Já usei muito, agiliza demais a vida.

Outra solução no mesmo estilo é o [AMPPS](http://www.ampps.com/), acho ele até mais completo que o Easy-Php

**Comment by adrianoavelino** [comment]
Na última vez que trabalhei com PHP usei o browsersync com gulp-conect-php: https://www.npmjs.com/package/gulp-connect-php#use-it-with-browser-sync

Ele funcionou lindamente nessa ocasião, e com livereload que hoje em dia é impossível ficar sem.

**Comment by iagodahlem** [comment]
Uma solução muito simples para quem quer live-reload para rodar projetos estáticos é o [live-server](https://github.com/tapio/live-server).

Basta instalar o live-server localmente ou globalmente com npm, e rodar o comando passando as configurações necessárias, por default ele já fica em watch em tudo:

```
npm i live-server
live-server --port=8080 --host=localhost --open=./index.html
```
