### ISSUE TITLE
Versionamento de projeto AngularJS

### ISSUE THREAD

**Issue by hugocarreira** [frontendbr/forum#442]
Olá pessoal,

Na empresa que trabalho, estou em um projeto que utilizamos AngularJS (sim, o 1.x). Como é empresa grande, tem alguns burocracias chatinhas, e a que venho quebrando a cabeça no momento é a seguinte:

Vamos versionar o projeto no TFS e precisamos, de alguma maneira, setar tag de versão no projeto. 
A empresa utiliza ASP .NET em outros projetos e como o build gera uma dll, eles conseguem tagear o "arquivo" e isso é um padrão em todos projetos... mas é obvio que no AngularJS não temos isso, mas preciso de alguma forma conseguir setar tal tag.

(Já procurei até como colocar aqueles comentários com a versão no header dos arquivos)

Alguem sabe alguma solução?

**Comment by RatoX** [comment]
Não sei se peguei direito seu problema, mas tu pode usar um grunt/gulp/webpack da vida pra gerar um ***.min.js** e tagear esse cara.

Quando usamos o git geralmente tageamos um hash e não um arquivo.

**Comment by herberthenrique** [comment]
Cara, já tive vários problemas com TFS e afins hahaha

Sendo bem honesto, se forem usar o TFVC não vai funcionar bem dependendo da stack que usarem.
1 - Ele colocar todos os arquivos em read-only e isso atrapalha bastante gulp/webpack para watch.
2 - Ele não lida bem com projetos fora do Visual Studio, sério.. não da pra usar fora do Visual Studio.
3 - Complica bastante o uso de npm/bower, por causa de read-only e algumas frescuras do versionamento.

Eu recomendaria vocês trocarem pro GIT e com isso fazerem [tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging).

Agora, na questão do build eu usei o TFS Online para fazer um "build", ele executava um npm install e depois uma task do gulp.
Então realizava o zip da pasta dist gerado pelo gulp e subia pra fazer a questão de release no Azure.
Eu mexi quase nada nessa parte e build, então não posso ajudar muito. :/

Mas a ideia é que o projeto em angular deve ser tratado diferente do asp.net e entender como isso funciona fora do TFVC.  :D

Ah, só lembrando que [TFVC](https://www.visualstudio.com/en-us/docs/tfvc/overview) é o versionamento dentro do TFS e que você optar pelos seus projetos usarem ele ou o git no tfs.

**Comment by hugocarreira** [comment]
Então @RatoX e @herberthenrique, fazemos isso no projeto. Usamos o gulp para gerar o build e subir para produção. 
Porém nosso problema é o versionamento, tem que ser TFS. Tentei implementar o GIT por já ter experiencia com ele e tal, mas não foi aprovado.

O gerente quer apenas que seja tageado e não vi nenhuma maneira de fazer isso no TFS. :/

**Comment by RatoX** [comment]
@hugocarreira Saquei agora cara, tu tem alguns problemas na mão sobre o mais complicado esse [site pode ajudar](http://stackoverflow.com/jobs).

Sobre o TFS o @herberthenrique pode ajudar melhor do que eu o único controle de versão que usei que foi parecido com esse modelo era o Clear Case.
