### ISSUE TITLE
BEMCSS - Componentes aninhados e aplicação de Media Queries

### ISSUE THREAD

**Issue by simaodeveloper** [frontendbr/forum#455]
E ai galera beleza?

Seguinte, estou com dificuldade em entender como é o aninhamento de componentes utilizando o BEM, como devo aplicar isso, o componente filho apenas é modificado dentro do escopo do componente pai? devo adicionar alguma classe no componente filho? como ficam as media queries no componente pai, caso o componente filho tenha seus próprios media queries?

@LFeh @afonsopacifer  @fdaciuk @willianjusten @woliveiras @akfzambrana @JuniorRodrigues

**Comment by thiamsantos** [comment]
Talvez esse artigo responda: [Battling BEM (Extended Edition): 10 Common Problems And How To Avoid Them](https://www.smashingmagazine.com/2016/06/battling-bem-extended-edition-common-problems-and-how-to-avoid-them/).

**Comment by fdaciuk** [comment]
@simaodeveloper talvez mostrando um exemplo de código de como você está tentando fazer fique mais fácil ajudar.. mas hoje eu recomendaria, ao invés do BEM, que funciona muito BEM _badum tssss_, usar CSS Modules e não se preocupar mais com escopos =)

**Comment by leandroruel** [comment]
exemplo:
```html
<div class="carousel carousel--fullwidth">
  <div class="carousel__inner">
  </div>
</div>
```
http://getbem.com/naming/

veja se te ajuda. o componente carousel é o pai, e tem um modificador, que é a classe com "--", ele possui também um componente filho, que é identificado pelo nome do elemento pai + "__" + nome do elemento filho. se houvesse um modificador nesse elemento filho seria:
```html
<div class="carousel__inner carousel__inner--yellow">
</div>
```

**Comment by simaodeveloper** [comment]
@fdaciuk muito legal esse CSS modules, @leandroruel cara é quase isso, seria mais com componentes distintos, como se dentro desse carousel tivesse um button e dentro desse escopo (carousel) o button sofre modificação, sendo que button possui suas próprias classes, por exemplo:

```html
<div class="carousel carousel--fullwidth">
  <div class="carousel__inner">
      <button class="button button__primary"></button>
  </div>
</div>
```

mas como o button vai sobre mutação por estar dentro do escopo do carousel, como devo proceder semanticamente seguindo o BEM no CSS, devo proceder assim:

```css
.carousel__inner__button {}
```

**Comment by thiamsantos** [comment]
@simaodeveloper o artigo que eu linkei ali em cima [aborda essa questão](https://www.smashingmagazine.com/2016/06/battling-bem-extended-edition-common-problems-and-how-to-avoid-them/#4-cross-component-components).

**Comment by leandroruel** [comment]
@simaodeveloper esse artigo que o @thiamsantos falou explica, mas nesse caso, o button é um componente distinto e não há problema em incluir dentro do escopo de outro componente. se sofre uma mutação dentro deste componente, crie modificadores.
 ```html
 <div class="button button--small button--rounded></div>
```

**Comment by marcosabb** [comment]
O que vocês tem a dizer sobre mais de 1 nível de elemento no BEM?
Exemplo:
`.block
.block__element
.block__element__element
`
Isso é considerado uma má prática? Sabendo que as vezes teremos 1 classe parecendo um livro hahaha.

**Comment by tarciozemel** [comment]
@marcosabb Não é preciso usar toda a árvore como nome de classe. 

O propósito da coisa é atribuir classes únicas inequívocas para elementos, então algo como `.body__arm__hand__finger__nail` só é verboso; `.hand__nail` identificaria de igual maneira o elemento.

**Comment by paulinhapenedo** [comment]
@marcosabb ai você começou a aninhar elementos e, na minha opinião, talvez isso seja perigoso para o futuro.

Eu gosto dos exemplos que o Harry Roberts utiliza no seu [CSS Guidelines](http://cssguidelin.es/#bem-like-naming). Pensar em termos de pessoas ou cômodos me ajuda a manter a sanidade na indentação e na nomeação das classes.

**Bloco:** .pessoa
**Elemento:** .pessoa__mao
**Modificador:** .pessoa__mao--direita

Se você precisar criar uma classe para o dedão da mão direita, eu não acho uma boa criar uma .pessoa__mao--direita__dedao (que é o caso que você citou, eu acho)

**Comment by kaisermann** [comment]
Tem uma adaptação do BEM proposta pela Envato chamada BEVM. Costumo usar nos projetos e é 10de10 https://webuild.envato.com/blog/chainable-bem-modifiers/

**Comment by victorsilent** [comment]
Uma dúvida simples, em caso de uso de framework, por exemplo o bulma.io, como proceder com o bem? Eu utilizo o @extend na minha classe, ou mantenho as classes do framework e utilizo as minhas apenas para customização?

**Comment by LFeh** [comment]
Só deixando meus dois cents.

Tento seguir a mesma lógica de **três niveis de aninhamento** (não vou linkar nada, já devem estar cansados de ler sobre) para o BEM também.

Se passar de três blocos é melhor para e repensar o código.
