### ISSUE TITLE
Dica de carreira

### ISSUE THREAD

**Issue by ojonathanleal-zz** [frontendbr/forum#456]
Galera, ultimamente venho com uma dúvida que talvez vocês poderiam me auxiliar. 

Estou querendo muito migrar para área de Front-End ( trabalho com Back-End atualmente ) e estou querendo investir no inglês também. Tem muitos materiais na web e diversos livros, e eu fico em dúvida se eu paro de estudar coisas técnicas e me dedico somente ao inglês ( meu inglês é bem ruinzinho, consigo entender o contexto ) ou eu continuo estudando coisas técnicas em paralelo em português.

O que vocês fariam?

**Comment by woliveiras** [comment]
@jonathanleal, se eu voltasse no tempo eu me dava um tapa na cara por não estudar inglês antes. 

Eu recomendo, se não tiver pressa de migrar para o Front, que estude Inglês primeiro e depois foque em Front End.

E quando estiver com o inglês afiado da até para partir para um [FreeCodeCamp](https://www.freecodecamp.com/). - Não precisa estar ninja no inglês, porém aproveitaria muito mais

A maioria dos livros mais atualizados estão em inglês, tirando os da Casa do Código que tem feito um trabalho muito bom em estimular autores brasileiros a escrever conteúdo, algumas palestras e vídeo tutoriais também, tudo em inglês.

Se tiver com o idioma afiado vai aprender muito mais coisa, muito mais rápido.

**Comment by diessica** [comment]
Uma das maneiras de você estudar inglês é, justamente, aprendendo front-end. Use isso como uma oportunidade e uma motivação para aprender uma nova língua. Você pode com tranquilidade fazer os dois, ainda mais que você disse que já entende o contexto.

Não sugiro que separe. Inglês você só vai ver resultado depois de algum tempo, e "afiado" é relativo. Sua confiança e fluência pode demorar anos ou alguns meses, não dá para saber! Separar atrasaria consideravelmente sua migração para área de front-end.

Só lembre-se de praticar os 4: _listening_, _speaking_, _writing_ e _reading_. (Normal ser melhor em um do que nos outros, mas pratique todos.)

**Comment by kelciocajueiro** [comment]
Concordo com a @diessica. Tente conciliar as duas coisas.

**Comment by woliveiras** [comment]
@diessica, eu gostaria de umas dicas sobre conciliar.

Tipo, eu estudo front/javascript/desenvolvimento no geral em inglês, porém quando me colocam pra conversar com alguém eu não consigo desenrolar.

Faz um ano que consumo a maioria do conteúdo em inglês. Livros, posts, tutoriais, etc. Celular, Sistema Operacional, Ambientes de Desenvolvimento. Tudo em ingreis.

Só que mesmo assim não me sinto confortável no idioma.

Eu até leio coisas não relacionadas com a área que é pra ter mais palavras no dicionário do que somente o que é relacionado com tecnologia, sabe?

cc: @kelciocajueiro

**Comment by diessica** [comment]
Aprender inglês é questão de imersão **absoluta** e tempo.

> Faz um ano que consumo a maioria do conteúdo em inglês. Livros, posts, tutoriais, etc. Celular, Sistema Operacional, Ambientes de Desenvolvimento. Tudo em ingreis.
> Só que mesmo assim não me sinto confortável no idioma.

Mas é claro que você não vai se sentir confortável! Se você observar o que você mesmo disse, vai perceber onde está o seu erro: você é um *consumidor* de conteúdos em inglês. Isso está errado!

Além de entender as mensagens das pessoas, você precisa saber a expressar as suas. Se dedicar a isso. Consumir vai ajudar você a se expressar, claro, mas para desenrolar você *precisa* falar, ou, no mínimo, escrever. Escrever mal, mas escrever. Isso vai colocar você em situações de conjugação de verbos em diversos tempos verbais, flexão de palavras em gênero, número, grau... Coisas normais que você faz com naturalidade em Português, e precisa conseguir em Inglês.

Eu comecei escrevendo (no trabalho, fóruns, documentação, trabalhos, tickets de suporte, blogs, amigos de fora, pesquisas, grupos), e, sinceramente, falar foi consequência. Consequência de gostar de escrever, e do destino que me ajudou colocando umas pessoas que falam inglês na minha vida. E ainda estou melhorando nisso, me comunicar de forma menos repetitiva etc. (Isso você faz DEPOIS de conseguir se expressar. Deixa os retoques e o perfeccionismo para depois!)

Como praticar? [Esta thread daqui do fórum](https://github.com/frontendbr/forum/issues/109) perfeita para isso. 

Falar com pessoas aleatórias em inglês é ousado e vale a pena, mas pode não ser a melhor forma no sentido de que não dá para fazer isso se você começa do zero mesmo, se você não sabe nem montar uma frase sem passar a mensagem errada. Só te dá ansiedade e desconforto, e fica mais complicado de aprender porque ainda tem o *listening* no meio de gramática, sabe? É legal chegar nesse ponto quando você já está mais tranquilo em relação a isso.

É isso, acho. o/

**Comment by woliveiras** [comment]
Excelente! 

Eu já escrevo minhas documentações em inglês e algumas repostas em foruns.

Preciso mesmo é fazer mais disso e menos de consumo de conteúdo!! Show de bola. 

Valeu @diessica! 🙌

**Comment by ojonathanleal** [comment]
@diessica e @woliveiras muito legal a dica de vocês. Muito obrigado. Ler a thread recomendada pela @diessica.

**Comment by laurindo** [comment]
Eu ultimamente dei um tapa na minha cara e resolvi aprender inglês de vez.
Um dos motivos é ver que uns cinco amigos que trabalhei foram trabalhar no
exterior.

Minha meta é daqui a 6 ou 1 ano está falando bem.
Sou da área frontend e na empresa em que trabalhamos o conceito é sempre
escrever documentação, commits, código tudo em inglês.

Com 2 meses de estudo eu já estou buscando conversas com nativos pelo
Skype. Está sendo uma experiência bem positiva.

Já participei de umas entrevistas por telefone e Skype.

A dica que dou é fazer duolingo, escutar texto repetidas vezes, existe uma
técnica chamada "shadowing", depois deem uma olhada. E ficar imerso no
inglês. Tudo em inglês, tudo. Até pensar em inglês.

Tecnologia se aprende rápido, mas inglês exige treino diário, muito
esforço. Aos poucos vai dando certo.

**Comment by yanmagale** [comment]
Como eu sempre digo, este é o melhor fórum do Brasil. Sempre tópicos relevantes.

@ojonathanleal sobre essa questão da migração, vivo uma situação parecida. Dentre o tempo de experiência que tive, grande parte do tempo sempre fui Back-end Developer. Contudo, neste último ano acabei tendo uma imersão maior(se é que posso usar o termo), passando muito mais a escrever códigos em JS do que em qualquer outra linguagem. E também tenho me feito a mesma pergunta, se é o momento para migrar na carreira. 

Não vejo problema nenhum em você ter conhecimentos e habilidades nas 2 áreas, até porque, conhecimento nunca é demais. E segundo, front-end hoje é um ecossistema incrível e cheio de oportunidades, então, se você se sentir confortável, pode ir numa boa. Claro que, pensando-se claro as suas condições de vida, momentos da vida e etc. JS é a linguagem que mais cresce hoje no mundo e so isto ja é um incentivo e tanto.

Quanto a questão do inglês, concordo totalmente com o que as pessoas falaram acima, principalmente a fala da @diessica , quando ela disse que você precisa inserir o inglês em todos os aspectos, não somente como consumo de conteúdo. E claro, como a maioria do conteúdo da web esta disponível em inglês, aprender as tecnlogias de front-end, obrigatoriamente, irá te requerer um aprendizado do idioma.

Também tomei um tapa na cara do idioma essa semana, onde vi alguns gringos na minha cidade tentando aprender e traduzir as gírias locais da minha cidade, e era frustrante conseguir entendê-los, e não conseguir se comunicar, porque na hora de falar, você simplesmente trava. O que eu tenho feito para me ajudar é um curso online (EF) e o uso de um app chamado [https://www.hellotalk.com/#en](Hello Talk), que é justamente para pessoas que querem aprender algum idioma, conversando com os nativos e pessoas que já dominam aquela linguagem.

Mas é isso, espero ter ajudado \o/

**Comment by woliveiras** [comment]
@laurindo, é isso [aqui](http://learnanylanguage.wikia.com/wiki/Shadowing)?

**Comment by kadoohd** [comment]
@woliveiras duas dicas rápidas que me ajudaram um pouco a melhorar a conversação:

1 - Ler textos em inglês em voz alta, vai te ajudar a trabalhar a pronúncia.

2 - Escutar podcasts em inglês diariamente, até em velocidade aumentada pra treinar o ouvido. Também ajuda a pegar alguns tempos verbais, siglas e gírias que o pessoal usa. Acredito que escutar é mais efetivo que ler em muitos casos.

**Comment by laurindo** [comment]
@woliveiras interessante o link, bem detalhado. Eu acabei descobrindo sobre
a técnica, no youtube.

**Comment by laurindo** [comment]
@woliveiras outra dica pra você começar a falar em inglês. Tenta marcar uma conversa pelo Skype pelo menos uma vez por semana. Eu uso o italki. No começo é difícil, mas aos poucos vc vai se soltando, se expressando e pegando confiança. 
A conversação é o que me diz o quanto eu melhorei e preciso melhorar.

**Comment by woliveiras** [comment]
Instalei o Hello Talk e já comecei trocar ideia com o pessoal! kkkk

Vou colocar tudo isso em prática. 👍

**Comment by kadoohd** [comment]
@ojonathanleal não acho uma boa parar de estudar a parte técnica pra melhorar o inglês.

Tudo é questão de gerenciar bem o teu tempo e seguir um processo diário de estudo. 

Acho que o primeiro passo é ter objetivos pequenos e bem definidos. Aprender inglês é algo muito genérico e pode dar até uma desmotivada no começo. Começa com objetivos menores e fáceis de alcançar em pouco tempo. Isso vale pra conteúdos técnicos também. Eu escrevi um artigo [aqui ](http://blog.estagiocomxp.com/2017/02/07/4-dicas-de-como-evoluir-uma-habilidade-tecnica/) que fala mais sobre isso, se quiser dar uma olhada.

Eu dividiria horas do dia pra estudar inglês e pra estudar a parte técnica de front (em pt mesmo, por enquanto) ou um dia da semana pra cada coisa, se não tiver tanto tempo diário.

Nesse meio tempo continua consumindo conteúdo em inglês, seja jogando, vendo filmes, séries e eventualmente tentando ler alguma coisa técnica da nossa área. E como a @diessica comentou, tenta escrever ou ler inglês em voz alta. É importante estar em contato com o inglês diariamente, dá um jeito de tornar isso parte da tua vida daqui pra frente.

É isso, foca em ter um processo e seguir esse processo. O importante é daqui um ano ter a capacidade de medir a tua evolução e não se arrepender de não ter começado isso um ano antes.

Boa sorte! :)

**Comment by ojonathanleal** [comment]
@yanmagale e @kadoohd obrigado pelas palavras. Estou criando uma forma de me dedicar durante a noite, pois é o tempo que possuo atualmente.

**Comment by ojonathanleal** [comment]
Outra dúvida que tenho é sobre a forma de estudar. Geralmente vocês traduzem? eu tento não traduzir, porém as vezes eu busco o significado da palavra em algum dicionário em inglês e não entendo também a explicação do dicionário. Acontece também de eu entrar num ciclo onde eu pesquiso a palavra no dicionário, e no dicionário tem outra palavra que pesquiso e assim em diante.

**Comment by kelciocajueiro** [comment]
@ojonathanleal não tente aprender por palavras isoladas. Tente aprender por contextos / frases / sentenças.

Por exemplo: **Have you been to São Paulo?** (Você já esteve em São Paulo?)
Have you been to... significa se alguém já esteve em algum local e assim você vai conseguir se expressar sem ao menos saber o que significa have / you / been / to

Sacou?

**Comment by Vitor-Felipe** [comment]
@ojonathanleal @woliveiras 
Uma coisa que me ajudou muito a destravar na hora de conversar com alguém em inglês, foi o fato de eu sempre tentar **pensar em inglês** (_naqueles momentos que você viaja pensando no futuro, na vida, naquela apresentação que você tem que fazer..._). E na mesma época eu comecei a assistir tudo em inglês (com legenda), caso achasse uma sentença interessante eu repetia tentando imitar o sotaque do autor(a). 
Ainda cometo muitos erros, pois quando abandonei o curso de inglês, nunca mais pratiquei writing ou prestei muita atenção na conjugação de verbos (vou tentar melhorar isso esse ano ;) )

**Comment by ojonathanleal** [comment]
@kelciocajueiro saquei, boa colocação :D

@Vitor-Felipe legal, assim você não fica traduzindo sempre que pensar em algo.

**Comment by ingridrauany** [comment]
@yanmagale  O curso que você está fazendo é da Education First? Estive olhando aqui e o plano desse site está mais em conta que o da Engoo e gostaria de saber se você está gostando...
