### ISSUE TITLE
Abstrair Jira com o GitHub e vice versa

### ISSUE THREAD

**Issue by felquis** [frontendbr/forum#459]
Olá pessoal, gostaria muito de abstrair o Jira para que os Devs não tenham que olhar para isso, enquanto o Jira é totalmente espelhado para o GitHub e vice versa.

* As issues do GH são como as do Jira
* As sprints são como as milestone
* O backlog é um porre de issues
* Ao criar uma issue no GH ele cria uma issue no Jira e vice versa
* Ao comentar uma issue no GH ele adiciona a issue no JIRA e vice versa.

### Requisitos
1. Ser self-hosted
1. Por ser self-hosted não ter limites de uso, poder escalar para N repositórios e poder ter N interações sem problemas.

Vimos que o zappier tem algumas integrações do tipo que queremos mas não gostei do jeito que ele escala para muitos repos e muitos colaboradores (+100 devs em N projetos)

### Objetivo

Deixar os devs serem felizes no GitHub, enquanto quem precisa do Jira de fato continue com todas as infos, intergrar projetos Open Source ao fluxo de produtos no Jira, pois tudo isso conta.

Vocês conhecem um santo graal de integração entre essas duas ferramentas? Eu estou sonhando demais ou é realmente possível?

Abs.

**Comment by leonardoelias** [comment]
@felquis olha esse cara aqui http://planrockr.com/pt-br/

**Comment by eminetto** [comment]
Valeu @leonardoelias. A integração com o Jira já está em fase de testes em alguns clientes. @felquis se quiser conversar com mais detalhes é só me passar um contato que conversamos. Ou me mandar um e-mail no elton@planrockr.com que vou ter o maior prazer em ajudar

**Comment by abalad** [comment]
Amigo Trabalho com a Solução Completa de Desenvolvimento da Atlassian na empresa que atuo, la consegui fazer integração JIRA( Tanto O Software quanto O HelpDesk ) + BitBucket + Confluence + Bamboo. O Jira tem por padrão tem a comunicação com diversos Repositorios : 
![image](https://cloud.githubusercontent.com/assets/5459282/23168424/dfc75326-f826-11e6-979b-7c52193320ca.png)

No caso vc pode utilizar a Tag De Identificação em seus commits Tanto no BitBucket quanto no GitHub que dentro do jira ele ira aparecer algo assim 
![image](https://cloud.githubusercontent.com/assets/5459282/23168509/2ae59e9e-f827-11e6-9d11-01147f2e4fbe.png)

![image](https://cloud.githubusercontent.com/assets/5459282/23168519/32f9a256-f827-11e6-853b-ce0443e62f93.png)

Não sei seria essa integração que vc busca, mas ele ja tem pelo menos esse tipo de integração.

**Comment by felquis** [comment]
@abalad ótimo, já estamos utilizando estes triggers do Jira, porém quero algo mais zica como na lista que fiz no tópico.

**Comment by LFeh** [comment]
@felquis Não conheço nada que faça isso, mas seria uma boa ideia de produto hein?

**Comment by felquis** [comment]
@abalad são quantas pessoas que usam a solução completa? E como que fica o preço disso tudo?

**Comment by abalad** [comment]
@felquis Entao, utilizamos toda a Suite: Bamboo + Jira Software + Jira HelpDesk + Confluence + BitBucket + HipChat.

Mas como a equipe é pequena(4 Programadores + 2 Suporte + 1 Tester), se enquadramos na maioria dos pacotes de $10 + a adição de alguns Plugins para o Confluence e Jira, pois hospedamos interno dentro de nossos servidores. 

No Total saiu em torno de uns 600 Reais, que é pago uma vez só. Caso você queira as atualizações anuais dai tem que pagar novamente. Caso contrario você somente recebe as ATT durante seu período de compra que é de 1 Ano.

**Comment by felquis** [comment]
Obrigado @abalad
