### ISSUE TITLE
Autorização com JWT no header usando NGINX 

### ISSUE THREAD

**Issue by RatoX** [frontendbr/forum#464]
Negads,

Estou usando o [NGINX](https://github.com/RatoX/marighella-box/blob/master/ansible/nginx.yml) para cuidar do meu frontend. Cheguei no momento mais chato da aplicação autorização/autenticação, para a autenticação eu vou usar OAuth 2.0 usando o github no frontend porém eu preciso validar o código _já que o diabo do github não suporta **implict grant**_. Eu gostaria de autorizar o roteamento no NGINX usando o JWT que vou colocar no header, alguém já fez algo parecido?

**Comment by RatoX** [comment]
GENTE ACHEI,

Na versão 1.11.3 do NGINX foi adicionado um modulo novo chamado [ngx_http_auth_jwt_module](https://nginx.org/en/docs/http/ngx_http_auth_jwt_module.html) que resolve meu problema do jeito que eu quero.

Agora só preciso instalar a porra do NGINX 1.11.10 (stable version) na porra de um Ubuntu trusty.

**Comment by rictorres** [comment]
Talvez isso ajude https://github.com/auth0/nginx-jwt

**Comment by willycamargo** [comment]
Você esta hospedando apenas HTML, CSS + JS em um servidor com NGINX?

Não seria mais saudável (e barato) hospedar ele em um bucket do S3 (AWS)?

**Comment by RatoX** [comment]
@rictorres Cheguei nesse link também, estou dando uma olhada e tentando religar minhas habilidades de Lua.

@willycamargo + ou - é um pouco mais complexo do que isso, sim eu poderia subir tudo pro S3 e tava tudo lindo, porém tem meus serviços de autenticação e coisas rodando no backend que precisam de um processamento customizado.

**Comment by RatoX** [comment]
Só para não deixar em aberto isso aqui:

Resolvi meu problema sem o NGINX :/

Coloquei minha validação do JWT no próprio serviços rodando usando o express e com essa [lib aqui](https://github.com/auth0/express-jwt)

**Comment by LFeh** [comment]
Boa!
