### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by pineladsn** [frontendbr/forum#473]
Bom dia galera, 

eu estou querendo começar a estudar umas coisas diferentes pra ampliar um pouco meus horizontes :))
Então gostaria de saber o workflow de vcs e caso tenham sugestões sobre o que poderia me agregar melhor *em termos de mercado* 

Vlw! Aquele abrç!

**Comment by LFeh** [comment]
Fala @pineladsn, tem algumas issues que podem te ajudar:

#54 
#412 
#456  

:)

**Comment by pineladsn** [comment]
Valeu @LFeh 
Obrigadão cara :D
