### ISSUE TITLE
Onde, quando e como aprender inglês?

### ISSUE THREAD

**Issue by Cleysonlb** [frontendbr/forum#478]
Falae galera, provavelmente já tem uma Issue sobre isso mas queria trazer meu drama...
Passei por todas as escolas de inglês da minha cidade a procura de um lugar que melhor me atende-se para aprender, e enfrentei os seguintes casos, ou era MUITO CARO ou o material era muito fraco e não passou confiança...
Alguém aqui poderia me indicar uma alternativa diferente?
Compartilhar seus próprios casos etc...
Obrigado galerinha vocês são 10! <3

**Comment by luizventurote** [comment]
@Cleysonlb geralmente eu vejo aulas pelo youtube mesmo, vou pesquisando e vou estudando da forma que acho mais produtivo para mim. Dá uma olhada nesses canais, talvez pode te ajudar um pouco:

- https://www.youtube.com/user/engvidenglish
- https://www.youtube.com/channel/UCFhAn8nQds3JDvf21STjeEw
- https://www.youtube.com/channel/UCz4tgANd4yy8Oe0iXCdSWfA
- https://www.youtube.com/channel/UCcpa-I7p5yrtsombKC_8BwQ
- https://www.youtube.com/user/learnexmumbai
- https://www.youtube.com/user/ENGLISHCLASS101
- https://www.youtube.com/channel/UC1Sxq91_kUlptpofl5QaQ9A

Uso o https://www.italki.com/ para fazer aulas com professores nativos de qualquer idioma. Para vocabulário eu uso esse site http://www.fluentu.com/ e também recomendo escutar podcasts de tecnologia ou de qualquer outra coisa que você acha legal.

Bons estudos!

**Comment by fredericksilva** [comment]
@Cleysonlb Acredito que a melhor forma de obter fluencia é convivendo e conversando em inglês, geralmente eu me "forço" a pensar em inglês para tudo, antes de pedir uma informação, ao ler um rotulo de produto no mercado...

E uma coisa que descobri no ano passado foi os meetups de polyglotas ou grupos de conversa do couch surfing foi muito util para acabar com meu medo de iniciar uma conversa por achar que não sou fluente o suficiente.

segue os links:
- https://www.meetup.com/clubepoliglota/events/236761882/ [SP vê se tem um em sua cidade]
- https://www.couchsurfing.com/events

Existe alguns grupos de telegram e whatsapp...

espero ter ajudado em algo :)

**Comment by devigor** [comment]
@Cleysonlb você é dá onde??

**Comment by diogorodrigues** [comment]
Ótimas dicas @luizventurote , vou seguí-las.

Sempre tentei estudar inglês por conta própria, mas nunca consegui avançar muito. Por isso, há alguns anos entrei na wizard e aprendi bastante coisas. 

Ao mesmo tempo comecei a assistir vídeos como esses: https://www.youtube.com/watch?v=NdXPnJLR07E&list=PLhwUb6-mGzbKD2iDp2JtVpcNU6qQCeu3J

Esses vídeos tem me ajudado bastante.

**Comment by kelciocajueiro** [comment]
Pra quem gosta de estudar sozinho:

http://clubedoingles.com/roteiro-de-estudos-para-quem-quer-estudar-ingles-sozinho/
http://clubedoingles.com/rotulo-de-estudo-para-quem-quer-estudar-ingles-sozinho-modulo-2/

**Comment by suissa** [comment]
Quem quer treinar conversação temos um curso focado para Devs!

**[Curso de conversação para programadores](https://github.com/Webschool-io/Curso-de-conversacao-para-programadores)**

**Comment by MendesGabriel** [comment]
Para pronuncia conheci esse site esses dias http://youglish.com/ , você digita a palavra e ele dá vários exemplos de pronuncia no ponto certo do video no youtube.

**Comment by LFeh** [comment]
#109

**Comment by dsoldera** [comment]
Olá @Cleysonlb. Eu acho que estudar inglês não seja tanto como estudar programação e vc ser 100% didático. Na minha experiência você pode sim utilizar de vários recursos online, como videos youtube e outros para ir sempre melhorando seu vocabulário e gramática, mas precisamos sim de um professor pra avaliar nossa escrita e nossa fala.

Eu ja fiz aula particular, já fiz escolas de inglês  e sempre procurei ver videos e dicas de melhorias. Hoje eu estou estudando pelo English Live (antigo English Town). Não é barato mas são professores com inglês nativo e a plataforma é muito boa (inglês online). Eu estudo em casa e por ja possuir um inglês intermediário tenho me dado muito bem com esse método.

Se o seu inglês for Basico eu não recomendo inglês online. Recomendo sim aulas particulares ou escolas mesmo porque se vc tentar economizar muito pode acabar gastando dinheiro e não caminhar com seu aprendizado. 

É isso.. espero que ajude em algo.... Boa sorte.

**Comment by daniloreisba** [comment]
Fui indicado esses dias a fazer esse, a principio estou gostando bastante e achando interessante, creio que seria uma boa dica:

https://www.tandem.net/

**Comment by markcanals** [comment]
Yo os recomiendo la siguiente página dónde encontrarán recursos gratuitos para aprender inglés de gran calidad y todo enfocado a hispanohablantes:

[lewolang.com](https://www.lewolang.com/resources)

Espero que les sirva, ya me comentarán que les pareció.

Un saludo,

**Comment by carloshenriqueribeiro** [comment]
Muito bom man! Ja comecei a seguir é curtir os vídeos.

**Comment by carloshenriqueribeiro** [comment]
@suissa ainda existe ? Lá ta com início dez 2016. Abraço

**Comment by tgmarinho** [comment]
Olá, eu faço curso com www.jacksonrogeridiomas.com.br  (pago) é bem interessante o método, mas é cansativo também, uso Duolingo e algumas outras ferramentas estão aqui:

https://github.com/tgmarinho/english-learning-tools

**Comment by woliveiras** [comment]
Galera, a um tempo atrás eu fiz um artigo sobre os apps que estou usando pra aprender/praticar inglês (de gratis): [Aplicativos para treinar nosso inglês](https://medium.com/trainingcenter/aplicativos-para-treinar-nosso-ingl%C3%AAs-c957d2c6dc9f)

**Comment by Murillofilho86** [comment]
Depois de procurar alguns cursos, descobri que a melhor opção é contratar um professor particular... Faço minhas aulas por skype, na hora que for melhor pra mim, não tive que gastar rios de dinheiro com material, pago mais barato que um curso... Estou indo pro meu terceiro mês e já percebo uma melhora muito significativa... Minha leitura e pronuncia melhoraram bastante, mas ainda tenho dificuldades em formar textos complexos e mesmo assim, estou melhor do que na época em que comecei.
Fica a minha dica, procure um professor particular, mas lembre-se de checar as referencias do mesmo.

**Comment by Marlysson** [comment]
@Murillofilho86 por onde encontrou esses professores particulares? São nativos mesmo ou não-nativos mas com grande experiência no idioma?

E com relação ao preço... tem valores..?

**Comment by mahenrique94** [comment]
Recomendo a [English Live](https://englishlive.ef.com/pt-br/), [Alura Lingua](https://www.aluralingua.com.br/) e [Duolingo](https://pt.duolingo.com/).

Além claro de muita prática, particularmente, tento sempre utilizar o inglês, meu note, celular, programas, sites, projetos, códigos, tudo, praticamente tudo que der eu tento fazer com inglês, assim consigo praticar bastante.

Também gosto de assistir vídeos, séries ou filmes com audio e legenda em inglês (futuramente pretendo deixar apenas audio e sem legenda).

O segredo é praticar bastante, é melhor praticar um pouco todos os dais, do que bastante mas apenas um dia ou outro.

**Comment by Murillofilho86** [comment]
@Marlysson, foi indicação de uma amiga, ela também da aulas de inglês, porém, presencial... E como eu queria online, ela me indicou a prima, que é professora formada, trabalha com isso e tal... 
Ela trabalha com pacotes, os valores vão variar de acordo com a quantidade de horas por semana.

**Comment by eliseumds** [comment]
Se não houver meetups na sua cidade, crie um! Eu falo fluentemente há um tempo mas ainda vou a meetups direto aqui em Sydney pra poder ajudar a galera. Vi o mesmo acontecendo em Sampa. É 200x melhor que qualquer curso, se você encontrar alguém fluente.

**Comment by didiraja** [comment]
@eliseumds meetup de conversacao? nunca tinha ouvido falar, boa ideia.

**Comment by danilocandido** [comment]
Em Fortaleza tem todo sábado a partir das 17:00. Sem falta.
https://www.meetup.com/pt-BR/Clube-Poliglota-Fortaleza/

**Comment by Vasmi238** [comment]
Recomendo o https://languagetools.io/. É um hub bem completo, vc pode ler textos com tradutor e pronúncia automáticos, escrever e ter seus essays corrigidos por professores, participar de chats, enviar threads com dúvidas, participar de discussões, receber dicas e, o melhor, trocar com pessoas de diversas nacionalidades, pois não é exclusivo para quem está aprendendo Inglês, apesar de ser a língua principal por ali. Uso bastante e está sendo muito bom pro meu desenvolvimento!

**Comment by Mauricio-Neviate** [comment]
O canal do Youtube RODGER KOLLER tem um curso sequencial e ele envia o
material das vídeo aulas gratuitamente para quem solicita.

Em sex., 27 de dez. de 2019 às 02:06, Vasmi238 <notifications@github.com>
escreveu:

**Comment by jass2125** [comment]
Tô pensando em fazer o do Mairo Vergara, alguém já fez? Será se vale a pena?

**Comment by CristinaMarin05** [comment]
Gente vcs tem conta na Amazon? Ela disponibilizou um livro super barato e prático auto didático para ficar fluente em 6 meses, comprei o meu nesse link https://www.amazon.com.br/gp/product/B01HJAL6Z6/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B01HJAL6Z6&linkCode=as2&tag=travel0770f-20&linkId=06dc3cc858f7f9eddd5b2313b24e68f2
Espero que ajude quem quiser tb!!

**Comment by diogorodrigues** [comment]
Hello everyone!
Após alguns anos depois que eu postei como eu vinha aprendendo inglês, volto aqui pra dizer como consegui dar um salto no meu aprendizado.

Em 2018 decidi fazer um intercâmbio para o Canadá. Por isso, com o intuito de aprender o máximo possível antes de ir estudar na gringa, comecei a devorar conteúdos sobre gramática e isso me ajudou muito nos 6 meses anteriores à minha viagem. Na escola que estudei lá no Canadá (ILAC - indico muito) há 17 níveis, do básico ao avançado. Quando fiz um teste online eu estava no nível 4. Quando cheguei lá, após os meses de preparação antes de viajar, eu já estava no nível 10. 

O segredo foi assistir bastante vídeos explicando regras gramaticais básicas, porém tudo em inglês (com professores explicando apenas em inglês). 

Os  vídeos desse canal me ajudaram muito (nível bem iniciante): https://www.youtube.com/watch?v=AVYfyTvc9KY&list=PL2IkMHFHWdErN1-V9nAeaxXiSkG7kBtjS

Esse indiano é phoda e aprendi muito com os vídeos dele (um pouco mais avançado): https://www.youtube.com/channel/UCImiNBzWUNuHBm95F8SyMYA

Em seguida vem o pessoal da EngVid que também me ajudaram muito a consolidar meus conhecimentos:
- Ronnie: https://www.youtube.com/user/EnglishLessons4U
- James: https://www.youtube.com/user/JamesESL
- Emma: https://www.youtube.com/user/EnglishTeacherEmma
- Adam: https://www.youtube.com/user/EnglishTeacherAdam
O legal da EngVid é que tem muito mais professores e vocês podem fazer pequenos testes após cada aula pra treinar a fixação (e tudo gratuito e sem login): https://www.engvid.com/

Essa Rachel me ajudou muito a melhorar a pronúncia (tem coisas avançadas, mas também tem muito vídeos básicos): https://www.youtube.com/user/rachelsenglish

Também tive algumas horas de conversação com pessoas diversas do mundo todo através da plataforma iTalk: https://www.italki.com/ (é possível filtrar por preço/hora, escolher pessoas que não sejam brasileiras pra evitar falar em português, assistir o vídeo demo pra ver se o sotaque do "professor" vai ser fácil de entender...)

Bom, e havia muito mais. Muitos aplicativos como Duolingo por exemplo e outros. Fiz do estudo do inglês um hábito diário: estudava todos os dias (anotando as dicas e reescrevendo o que eu lia) e ficava revisando o dia todo. Ficava assistindo vídeos em inglês (de acordo com o menu nível), lia posts em inglês, ficava repetindo as palavras que eu ouvia... E tentei focar apenas no inglês americano, uma vez que eu ia para o Canadá.

Bom, e após 4 meses no Canadá, voltei com o meu objetivo concluído: conseguir consumir conteúdos da área de desenvolvimento em inglês - vídeos, posts, podcasts... Claro que lá eu aprendi muito. A escola era ótima. Me enturmei com pessoas de diversas nacionalidades o que me fez falar muito em inglês. Tive muita sorte com as duas famílias que morei, pois pude aprender muito com eles... Claro que eu também fiz amigos brasileiros e continuamos a trocar mensagens até hoje, inclusive em inglês...

É uma experiência única e se você conseguir ir estudar 2 semanas em algum outro país e focar ao máximo em aprender e praticar enquanto estiver lá, com certeza seu inglês vai decolar ainda mais.

Espero ter ajudado!
Super abraço.

**Comment by abechuate** [comment]
Olá Pessoal, gostaria de convidar-los para um zoom call para falar sobre o assunto aprender inglês. Acredito que vai ser bastante valioso! 
Não sou professor de inglês, não tenho ou represento nenhuma escola, mas tenho uma uma longa e intensa experiência pessoal com o Inglês. Ficaria feliz em poder ajudar.
Quem tiver interesse, por favor, envie um email para englishmastery@liveup2yourdreams.com e agendamos uma data.
Um abraço,
André

**Comment by Mauricio-Neviate** [comment]
Eu gosto do canal Rodger Koller

Em ter., 5 de mai. de 2020 às 20:39, abechuate <notifications@github.com>
escreveu:

**Comment by abechuate** [comment]
Olá Mauricio,

Vou fazer outro webinar muito em breve para apresentar meu programa de
mentoring. Se tiver interesse, deixe-me saber!

Um abraço,
André

**Comment by pedddro** [comment]
> Olá! Dentre os aplicativo gratis eu recomendo o duoling, é muito bom eu já usei. Conheço um outro método também muito bom, (bem ousado) que usa o método Accelerated Learning ( desenvolvida pela Universidade de Harvard ) segue o link: **[Como Aprender Inglês Rápido e Sozinho](https://oradorninja.com/como-aprender-ingles-rapido-sozinho-funciona/)** , espero que seja útil! Abs

Duolingo e Duocards, os dois são muitos bons e gamificam a maneira de aprender; app do duocards: https://apps.apple.com/us/app/duocards-learning-decks/id1508159917
