### ISSUE TITLE
O que vocês acham de certificaçao JavaScript?

### ISSUE THREAD

**Issue by felquis** [frontendbr/forum#491]
Conheci o teste http://certificacao.imasters.com.br/ durante a intercon em 2016, eu nao passei haha e ouvi alguns amigos fazendo algumas criticas, que achei bastante construtivas.

Gostaria de saber de voces que chegaram a testar o que voces acharam dessa certificaçao especificamente, e o que voces acham de certificaçoes at all.

Abs.

**Comment by LFeh** [comment]
Deixei o titulo mais amplo o/

**Comment by MarcoWorms** [comment]
Gostaria de dar minha crítica, fiz e passei no teste mas achei ele completamente falho. ele não avalia nenhuma "good part" do javascript. Não há questões boas sobre closures, nem ES6, grande parte do desafio consiste em pegadinhas com "this". Eu nunca usaria essa certificação como métrica para uma contratação ou ao menos para medir o nível de alguem em JS. Os problemas do mundo real de JS não estão aí.

@LFeh eu acho que o felquis se referiu especificamente a essa certificação pois nós fizemos o teste dela na Intercon e ficamos bastante decepcionados, espero que ninguém leve esse "certificado" em consideração na hora de ponderar candidatos.

**Comment by WandersonAlves** [comment]
Po, não conhecia. É 0800, então talvez seja valido, irei tentar mais tarde e darei uma opinião mais ampla

**Comment by AlexsandroSA** [comment]
@felquis boa noite cara. Conhecia o curso mas nunca cheguei a fazer, também tive essa dúvida.

@WandersonAlves  uma opção 0800 e um pouco mais ampla é o [freecodecamp](https://www.freecodecamp.com/). Inicie essa curso/certificação um tempo atrás e estou gostei muito, sai bem do iniciante(o que pode ser chato no inicio) e vai até o intermediar. 

Tem alguns desfios/projetos [fiz alguns](https://codepen.io/AlexsandroSA/#) tem muito mais veja a [lista de completa de desafios/projetos do curso](https://www.freecodecamp.com/map).  Vale a pena dá uma olhada lá. 

Ele é em Inglês. :)

**Comment by WandersonAlves** [comment]
@AlexsandroSA que show, eu só lia o medium do freecodecamp, nunca parei pra ir no site deles mesmo. Darei uma olhada.

Sobre a prova do iMasters, tirei 60% dos 80% necessários. Muita "casca de banana" na prova, hora de estudar mais!

**Comment by felisio** [comment]
Só para acrescentar existe também a certificação da microsoft em HTML5, Javascript e CSS3

https://www.microsoft.com/pt-br/learning/exam-70-480.aspx
