### ISSUE TITLE
Tradução Livro Front-End Developer Handbook 2017 ?

### ISSUE THREAD

**Issue by Suburbanno** [frontendbr/forum#497]
Alguém poderia traduzir?
https://www.gitbook.com/book/frontendmasters/front-end-handbook-2017/details

![cover](https://cloud.githubusercontent.com/assets/13632826/24226797/7579f1d0-0f47-11e7-9397-6a1e38e0e8b0.jpg)

**Comment by Lucasktrindade** [comment]
Eles permitem traduzir?

**Comment by phenriqueleao** [comment]
Que bacana esse livro! Se eles permitirem traduzir podemos mobilizar a comunidade pra providenciar isso.

**Comment by fabiomirandaa** [comment]
Parece ser um livro aberto, podemos nos mobilizar pra isso.

**Comment by kvnol** [comment]
Eu creio que seja livre para tradução, também. Está no Github e há muitos forks: https://github.com/FrontendMasters/front-end-handbook-2017

Além desse, eu listei diversos outros livros que são free e/ou open source e estão em inglês no repositório: https://github.com/kvnol/frontend-books :metal:

**Comment by LFeh** [comment]
Entrem em contato com o autor e vejam se não tem problema :)

**Comment by Suburbanno** [comment]
@LFeh Liberado

https://github.com/FrontendMasters/front-end-handbook-2017/issues/49

**Comment by calaca** [comment]
Agora que o cartão verde já foi dado podemos começar a tradução.
Caso queiram mais uma ajuda na tradução é só chamar. :smile:

**Comment by carolesteves** [comment]
Oi pessoal, já estão traduzindo? Tenho interesse em traduzir também!

**Comment by Cleysonlb** [comment]
Preciso treinar meu inglês! Tbm estou interessado!

**Comment by kvnol** [comment]
Pessoal, já que ninguém se pronunciou ainda. Forkei o repositório e iniciei com o README.md só com o título (não estou em casa agora): https://github.com/kvnol/front-end-handbook-2017/tree/pt-br/translations/pt_BR :metal:

**Comment by carolesteves** [comment]
Podemos dividir por capítulos entre os interessados e depois trocar as traduções entre nós para revisão.

**Comment by LFeh** [comment]
Galera, sugiro forkar o repositório deles e criar uma pasta `translations` inserindo uma outra pasta `pt-br` lá :)

Depois faz o pull-request pra eles.

**Comment by kvnol** [comment]
Massa, @LFeh. Atualizei lá: https://github.com/kvnol/front-end-handbook-2017/tree/pt-br/translations/pt_BR :metal:

**Comment by LFeh** [comment]
This issue was moved to frontendbr/open-source#23
