### ISSUE TITLE
Ferramenta de "auto invite" do slack está funcionando?

### ISSUE THREAD

**Issue by willianribeiro** [frontendbr/forum#501]
Galera,
Eu utilizei o http://frontendbrasil.slack.com para gerar um convite, mas não recebi no meu e-mail. Conferi na lixeira e no spam, mas nada. 

Alguém sabe dizer se está mesmo funcionando?

**Comment by thulioph** [comment]
Eu lembro que ajudei a por pra funcionar na época que foi criado, não sei se ainda é vinculado a minha conta no Heroku. 

Cc @admins

**Comment by LFeh** [comment]
Cara, na verdade não cuidamos desse Slack. Apenas integramos com ele que já existia.

@eduardojmatos Consegue dar uma força?

**Comment by eduardojmatos** [comment]
@willianribeiro O endereço que você passou já é do slack do frontendbrasil, mas você precisa receber convite antes.

Você precisa entrar [aqui pra receber convite](http://frontendbrasil-slack.herokuapp.com/) :)

**Comment by willianribeiro** [comment]
Ops, eu colei o endereço errado, mas solicitei o convite no endereço certo hahaha (-;

Foi exatamente no http://frontendbrasil-slack.herokuapp.com que eu fiz a solicitação do convite, mas aparentemente a ferramenta de envio de convites não está funcionando :thinking: 

(Já agradeço pela atenção pessoal!)

**Comment by willianribeiro** [comment]
Eita! 
Eu fiz um teste com o [10minutemail](https://10minutemail.com) e funcionou! Provavelmente tem algo a ver com meu e-mail, mas não faço ideia do que seja .-.

**Comment by willianribeiro** [comment]
Bom, de qualquer forma está funcionando! Não faz mais sentido manter a issue aberta.
Vou fecha-la e  entrar em contato com o suporte do Slack. 
Obrigado pela força galera (-;

**Comment by eduardojmatos** [comment]
Blz @willianribeiro!!
