### ISSUE TITLE
Sugestão de label pras issues de vaga

### ISSUE THREAD

**Issue by rafaelassumpcao** [frontendbr/forum#502]
galera estava percebendo aqui uma grande procura por jobs que sejam full remote e as labels das issues de vagas do frontendbr apenas indicam remoto.  o que as vezes frusta quem busca uma vaga full por exemplo tem vagas que tem a label remoto mas é de apenas um dia por semana por exemplo.

Poderia haver uma distinção de labels remoto tipo sei lá algo como
- Remoto Parcial
- Remoto Integral

se  gostarem da sugestão e tiver uma nomenclatura melhor, por favor joga na roda!  @LFeh

**Comment by nandomoreirame** [comment]
@rafaelassumpcao Não seria interessante cadastrar a vaga no repositório de [vagas](https://github.com/frontendbr/vagas)?

**Comment by rafaelassumpcao** [comment]
@nandomoreirame  como assim? não estou cadastrando uma vaga não, era apenas uma sugestão de melhoria das labels pois vi que tinha muita gente buscando job full remoto e não parcial e a label remoto não faz essa dinstinção. ai criei aqui pra ser discutido mesmo.

**Comment by LFeh** [comment]
@rafaelassumpcao Temos um repositório apra sugestões, consegue colocar lá? :)

https://github.com/frontendbr/sugestoes

**Comment by rafaelassumpcao** [comment]
@LFeh  foi mal não sabia
