### ISSUE TITLE
O que vocês esperam de um desenvolvedor Front End tenha?

### ISSUE THREAD

**Issue by camillodev** [frontendbr/forum#503]
Eu recentemente consegui um emprego (finalmente), mas como back end,  e posso agora estudar da forma correta, em vez de me preocupar em dominar as tecnologias de mercado para conseguir uma vaga.  Então eis o meu plano de estudo. Deem uma olhada e me digam o que acham. Opniem também como vocês aprenderam e o que acham mais importante. Agradeço muito. 

Meu plano de estudos:

- Reproduzir layouts do dribble, para pegar experiencia com HTML e CSS, tentando aplicar Sass e aprender arquiteturas de CSS, como BEM, OCSS etc. 
- JavaScript Puro Avançado. Ja estudei Javascript antes, mas ainda tem coisa pra aprender ainda como ES6 e Javascript Orientado a Objetos.
- Grunt ou Bower: Sei começar projetos com eles mas ainda não sei utiliza-los para automatizar tarefas
- React e os conceitos de front end Modular
- Vue.js: por que vejo apenas comentários positivos sobre esse framework e to interessado a muito tempo em conhecer.
- Wordpress: Para futuramente trabalhar como freelancer.
- Open cart: Para trabalhar como freelancer e fazer lojas virtuais.

**Comment by fernahh** [comment]
Sem dúvidas essa é uma das perguntas mais frequentes feitas por quem está começando. Nessa semana saiu um projeto que busca ajudar traçar esse caminho, se chama [web developer roadmap](https://github.com/kamranahmedse/developer-roadmap).

![Introdução](https://camo.githubusercontent.com/e33c230efcad68bd35ec44c5eff5708aecf77d9a/68747470733a2f2f692e696d6775722e636f6d2f5274316f4c6c4d2e706e67
)

![Roadmap](https://camo.githubusercontent.com/aab59f179c70343b2e9ad70cf8520d08b4622502/68747470733a2f2f692e696d6775722e636f6d2f326164764d39572e706e67)

Acho qualquer fonte de conteúdo, não tem como concordar que isso seja 100% o melhor caminho, mas eles resolveram bem como responder tua pergunta.

**Comment by gabrieldarezzo** [comment]
> back end

Seu trabalho atual é de Back End? / PHP? (Você citou WP hehe)

Mergulhar em Orientação a objeto é necessario, 

E conhecer alguns design patterns pode melhorar sua qualidade de código,
Eu separei uma lista que atualmente estudo em cima dela: (Veja se ajuda:

- Factory Method
- Abstract Factory
- Simple Factory
- Bridge
- Builder
- Composite
- Adapter
- Chain Of Responsability
- Strategy
- Proxy
- Dependency Injection
- Singleton

Fica aqui um trecho do vídeo do video do @filipedeschamps

> Nenhum design patterns serve pra o que eu estou tentando resolver.
> O meu problema é único! Deixa eu criar aqui uma solução bem exclusiva, porque vai se encaixar melhor no que eu quero.

https://www.youtube.com/watch?v=oMvwcrPITHM

**Comment by woliveiras** [comment]
Talvez o [Carreira Front End](https://github.com/woliveiras/front-end-career) tenha algum conteúdo relevante pra você se inspirar também, @camillodev 🤘

**Comment by camillodev** [comment]
@fernahh Cara muito obrigado por compartilhar essas informações. Não conhecia esse projeto, vai ser muito util. Brigado mesmo! Vou seguir esse road map.

@gabrieldarezzo meu trabalho atual é back end sim, mas .NET, porém eu já conheço o suficiente pro meu trabalho atual e quero mesmo é trabalhar como front no futuro, por isso o topico. Enquanto trabalho vou focar em estudar front para em breve migrar para front end.  Mas muito obrigado pelas suas contribuições.

@woliveiras o Carreira Front End tem muito conteudo legal sim, além do mais, muita coisa que você escreve, mas nesse caso as informações sobre Front End Engineer Júnior, estão meio fora do que vejo no mercado, por isso esse tópico. mas muito obrigado pela dica, acho que até não fui claro na minha questão. 

Minha duvida maior, além do plano de estudo, é o que esta sendo mais exigido de um front end Junior hoje no mercado. Por que as vezes eu vejo algumas vagas que parecem ser pleno quase senior e não junior.

**Comment by woliveiras** [comment]
Saquei @camillodev

**Comment by LFeh** [comment]
Linkando 

#415 
#32

**Comment by yanmagale** [comment]
O link que o @fernahh mandou e o carreira front-end do @woliveiras vão lhe dar bons auxílios para trilhar o caminho dos estudos. Gostei da parte que tu colocou sobre praticar e reproduzir layouts, a prática é o que realmente nos faz evoluir.

Quanto as tecnologias:
- React e VueJS resolvem o mesmo tipo de problema, tem ecossistemas bem parecidos(pra não dizer iguais), acho que você optar pelo o que você mais gostar ou se desenvolver melhor.
- Sobre o Grunt, eu confesso que não vejo novos projetos com ele. No caso, seria melhor(ou o mais utilizado atualmente) o GulpJS.


Quanto as tecnologias de Back-end
- Se a stack for PHP, além dos design patters e dos princípios solid, recomendo dar uma lida no composer, PSRs e no PHP7. Frameworks, recomendo o Symphony ou o Laravel

**Comment by fititnt** [comment]
Estou começando a ficar preocupado com a autoimagem da comunidade do que é ser desenvolvedor front-end e de que ninguém está falando sobre isso porque não pararam para refletir do ponto de vista geral.

Eu iria ignorar isso em outras situações e seguir em frente, mas depois de ir muito fundo nas ultimas semanas nas questões de aumentar competitividade do Brasil, perceber essa autoimagem e a má influência dela na vida dos novos profissionais e do próprio mercado brasileiro é preocupante.

Um sintoma grave é o seguinte: **simplesmente deixaram de até mesmo citar habilidades como design, experiência de usuário, ou tarefas ao estilo "converter o PSD para HTML" como habilidades básicas.**

Outro sintoma grave: **habilidades básicas estão sendo trocadas por induzir pessoas a usar frameworks ou abordagens que logo estarão em desuso**; notem que não estou acusando ninguém em especial porque no fundo parece que a primeira leva de desenvolvedores incentivou outros a serem _muito melhores_ em programação, mas era para ser desenvolvedor front-end, não programador front-end.

Notem por exemplo que parece que colegas sentem bastante orgulho de dizer que o código dos brasileiros é melhor do que os lá de fora, o que pode ser mesmo verdade. Dai vem a pergunta: isso é necessariamente bom? O que levaria o código daqui ser melhor? Qual dos dois casos gera salário maior e melhora lucro da empresa que paga o salário?

Só lembrando: **não existe apenas concorrência interna no Brasil, mas também de outros desenvolvedores la de fora**. Essa concorrência pode vir até mesmo de plataformas como serviço. Os impostos para pagar mão de obra de fora mais dólar a mais de 3 reais é que pode estar não colaborando para que isso não seja tão percebido. Mas notem que até a [china está pagando salários industriais melhores que os no Brasil](http://epocanegocios.globo.com/Economia/noticia/2017/02/salario-medio-de-setor-industrial-na-china-ja-supera-o-do-brasil.html) porque eles tem força de trabalho bem eficiente.

**Comment by elfiservice** [comment]
Vale a pena da o Check aqui by Udacity    ✅ 
[Habilidades de um desenvolvedor front-end](https://br.udacity.com/checklist-desenvolvedor-front-end?utm_source=vero&utm_medium=email&utm_content=a&utm_campaign=2018-05-25_BR%20Ebook%20Checklist%20de%20front-end&utm_term=Newsletter&vero_id=9572678855&vero_conv=Z3_qSuIADu6XuicUr7QGYTFmricer7zFuSEeuWcIK9ypm1oKh8QgvkP7RZ2b8WFbEjsn_I6R6jnX0dro6zLHbwhrhnDjy4gj)

**Comment by luizbills** [comment]
Sugiro excluir o grunt e o bower para focar mais no webpack.
Também sugiro trocar o opencart pelo WooCommerce, é a plataforma de ecommerce que roda em cima do wp (além de ser a plataforma de ecommerce mais utilizada no mundo).
E não sugiro usar o dribble como exemplo, a maioria lá são layouts nada funcionais. Procure reproduzir exemplos reais e que são sim funcionais.
