### ISSUE TITLE
Por que estudar/usar ES6 hoje?

### ISSUE THREAD

**Issue by ericktatsui** [frontendbr/forum#507]
Comecei a estudar ES6, estou ancioso para usar, tanto no browser quanto no Node. No entanto, o fato de ter que compilar para ES5 me deixa um pouco relutante, quero dizer, compensa usar no browser? Por que tanta gente está usando? É só pela moda ou novidade?

**Comment by xWul** [comment]
Na minha opinião, o ES6 tem algumas features que tornam o seu código menos "verboso", e com isso você pode ganhar uma melhor manutenibilidade e mais eficiência de escrita.
Segue um comparativo de algumas features do ES6 vs ES5.

http://es6-features.org/
https://babeljs.io/

**Comment by matheusml** [comment]
Oi @ericktatsui, beleza?

Então o motivo de se usar ES6 hoje, não é nem por moda nem por novidade.

Na verdade, podemos resumir da seguinte forma:
O motivo de usar o ES6 hoje é o mesmo de você preferir um iPhone 7 ao invés de um iPhone 6.
Ou o Windows 10 em relação ao Windows 8.1.

O ES6 é uma atualização em relação ao ES5, então ela corrige diversos problemas que existiam na linguagem, melhora algumas questões de performance e legibilidade, dentre diversas outras questões. 

A comunidade prefere o ES6 não por modismo, ou por querer novidades. A comunidade simplesmente prefere usar a versão atualizada da linguagem.

**Comment by edmolima** [comment]
@ericktatsui vou te responder em partes e espero que mais pessoas possam contribuir. Mas vou fazer analogia ao Internet Explorer, sempre você reclamou possivelmente por não dar suporte a algumas features certo? Como acha que o mercado vai te ver por não usar ES2015?

Brincadeiras a parte, usar ES2015 (ES6) já não é mais opção, estamos indo para ES2017 (ES8) e saber Javascript moderno é primordial pra sua carreira. Respondendo especificamente você:

**Usar no NodeJS e no Browser**

Sinta-se livre em usar sem transpiler. Mas lembre-se que podemos usar esses transpiles para outras coisas também, não só pra "compilar". Babel por exemplo consegue analisar padrões que você definir através de plugins e tal. Usar webpack por exemplo pra melhorar seu workflow enfim, fique livre pra optar em usar o js com transpile ou não, lembrando que alguns navegadores não suportam 100% a última versão do EcmaScript, mas no geral ES2015(ES6) na maioria dos navegadores é suportado mais do que 90% da syntax.

Sobre sua luta de usar os transpile, pode ficar tranquilo todos acho que passam por isso rs. Mas cara WebAssembly vem ai, e "compilar, transpilar" como queira chamar, cada vez mais será comum. Veja o typescript, isso é normal e não tem problema nisso afinal javascript é rápido o problema está no que ele manipula (DOM) mas ai é outra conversa e quero que você foque no que é "compilado". No fim tudo vira um arquivo `script.min.js` e não muda no que somos acostumados a fazer rsrs.

**É só pela moda ou novidade?**

As features vão além de apenas moda ou novidade. Mudanças nas estruturas baixo nivél também existem. Ou problemas com Tail Call Optimization, Recursive Programming enfim várias coisas do gênero. Mesmo algumas das features sendo syntax sugar, usar as novas features é importante pra qualidade de código e melhorias da própria linguagem em tratar alguns problemas.

**Comment by ericktatsui** [comment]
Legal as respostas até agora.
O que mais me deixa nessa dúvida, é o resultado que temos ao usar features do ES6 que não tem no ES5 e transpilar (eu imagino que algum código "gambiarra" vá substituir a feature no ES5).
Além disso, acabei de dar uma olhada no suporte dos browser para o ES6. Da mesmo para usar dependendo do que estiver sendo desenvolvido, dependendo do foco ou do público alvo. Mas tem que ser uma situação um tanto especifica para isso acontecer, o que torna o uso sem transpiler quase sempre necessário.

**Comment by ericdouglas** [comment]
ES6 não é mais novidade, foi lançado **oficialmente** há 2 anos (Junho 2015), o que nessa área é um bom tempo já.

> compensa usar no browser?

Compensa usar em todo lugar que você puder! Ótimas adições foram feitas.

Com o cenário atual de desenvolvimento de aplicações web clientside, você sempre vai ter um processo de build para otimizar/minificar/etc sua aplicação. O transpiler é só mais um step, então não tem porque deixar isso de fora se você já está com tudo configurado.

Só um projeto extremamente simples não seria necessário essa atenção, tipo uma landing page que vai sair do ar em 2 meses, ou algo do tipo, mas que mesmo assim seria beneficiado desses cuidados com minificação e tudo mais.

**Comment by yanmagale** [comment]
Vale ressaltar que, além dos que as outras pessoas já falaram, é que no dia em que todas as features estiverem implantadas em todos os browsers, em sua totalidade total da spec, não haverá a necessidade de se usar um transpiler(considerando apenas das features da ES6)

**Comment by dleitee** [comment]
@yanmagale na minha opinião, se usarmos uma stack com babel ou qualquer outro transpiler, quando os browsers implementarem as features ES2015, basta o babel parar de transpilar algumas features.
