### ISSUE TITLE
Qual a importância da tag <form> em uma aplicação em AngularJS 1.x?

### ISSUE THREAD

**Issue by StanleySathler** [frontendbr/forum#511]
Oi pessoal, como estão?

Primeiramente, por que "em uma aplicação em AngularJS 1.x"? Porque AngularJS 1.x é um dos poucos frameworks com qual trabalho (é, sou um Front-End Jr. ainda), então é onde posso extrair dúvidas.

Eu trabalho mais ou menos da seguinte maneira: supomos um CRUD. Temos a tela onde adicionamos um novo registro, ou seja, campos de um formulário. Temos também um botão "adicionar/salvar/whatever". Cada campo, uso um ng-model para aplicar o binding com o $scope. No botão de salvar, uso um ng-click() que chama um método que, por sua vez, faz uma requisição usando o $http.post() e enviando o que tenho que enviar.

Até aí, tudo bem. A grande questão é: eu preciso colocar esses campos dentro de uma tag `<form>`? Se sim, por quê? Sei que o Angular possui uma série de esquemas para validações (porque o `<form>` é uma diretiva no contexto do Angular que instancia um FormController). Mas afinal, quais as vantagens de encapsular meus campos dentro de um `<form>`? O `<form>` tem quais importâncias numa aplicação em Angular?

Valeu, meu povo! E de antemão, agradeço pelo tempo de vocês.

**Comment by LFeh** [comment]
c/c @woliveiras

**Comment by felipeuntill** [comment]
Considerando que você mesmo citou os ganhos de validação e acesso ao contexto irei responder de forma prática. 

Basicamente sua duvida implica na decisão sobre qual premissa você prefere abordar, semântica ou praticidade.

Se formos considerar a semântica como base de argumentação, a estrutura do HTML sendo indexavel ou não deve respeitar uma estrutura coerente portanto, mesmo que o envio do formulário não esteja sendo efetuado pelos mecanismos padrões a marcação deverá respeitar o uso stricto do HTML e suas hierarquias conceituais.

Já se você for abordar visando a praticidade tirando os ganhos de validação da tudo na mesma uma vez que o javascript quem irá efetuar o envio dos dados para o servidor.



_Agora levando para o lado pessoal **marcação HTML que não leva a semântica a sério me causa nauseas  🤢**_

**Comment by matheus-vieira** [comment]
Acho que vale a leitura

[Importance of Form Tag in HTML PAge](http://www.c-sharpcorner.com/blogs/importance-of-form-tag-in-html-page)

Apesar do artigo ser de um site de tecnologias Microsoft acho que ajudar a entender um pouco que a importância não é apenas para o Angular (seja qual for a versão) mas para a web como um todo.

**Comment by ericdouglas** [comment]
Usando o `form` você tem a possibilidade de usar o esquema do Angular para ver se um campo já foi "tocado" e mais uma série de outros estados.

[Aqui](https://github.com/ericdouglas/blog-assets/blob/master/source/_pt-br/criando-formularios-com-angularjs.md) tem um resumo de como criar um sistema de forms + validação usando Angular 1. Link para o source no final :smile:

**Comment by StanleySathler** [comment]
Galera, muuito obrigado! Era exatamente isso que eu precisava: opiniões e fatos para poder moldar meu conhecimento acerca do assunto.

Saio desta discussão com um conceito em mente:
- Opte pelo `<form>` porque é semântico e os desenvolvedores preferem aplicações semânticas. Claro que isso não se limita apenas ao fato de os desenvolvedores preferirem; tem sua importância.

Inclusive, estarei reavaliando minhas aplicações, pois nenhuma delas utiliza o `<form>`.

Os links também me ajudaram bastante. Principalmente o postado pelo nosso amigo @ericdouglas, pois me deu uma introdução legal acerca do uso do formulário no contexto do Angular (sabia a teoria, brinquei um pouco, mas ao voltar a utilizar, terei menos trabalho usando este link do que a documentação oficial do Angular, na qual não curto muito).

Valeu mesmo! <3
