### ISSUE TITLE
Sobre estrutura de arquivos e o que versionar

### ISSUE THREAD

**Issue by kvnol** [frontendbr/forum#515]
E aí, galera.

Estou com um dilema há algum tempo, pois estou definindo uma estrutura padrão de projetos que segue mais ou menos essa linha:

```
dist/
  assets/
    css/
      main.css
    js/
      main.js
    index.html
src/
  assets/
    sass/
    js/
    img/
  content/
  partials/
  layouts/
  index.pug
package.json
...
```

E tenho um problema que é sobre se eu devo ou não versionar a pasta **dist**, atualmente ela está ignorada no `.gitignore`, mas se eu deixo ela ignorada não consigo fazer deploy com **git ssh**.

Enfim, a minha pergunta resume-se em duas coisas: vocês ignoram os arquivos _buildados_ e como vocês realizam o deploy destes arquivos?

**Comment by nandomoreirame** [comment]
Eu geralmente não versiono arquivos finais que irão pra produção, vc pode tentar um continuous integration como Travis ou outro similar, onde será executada tarefas para gerar os arquivos do diretório dist e usando git ssh mandar para produção :smiley:

**Comment by nandomoreirame** [comment]
Por exemplo, o [meu site](https://nandomoreira.me) tenho versionado apenas o [Source dele](https://github.com/nandomoreirame/nandomoreirame.github.io) usando Middleman, quando preciso mandar algo pra produção (nesse caso uma branch do github pages) eu uso o [TravisCI](https://travis-ci.org/nandomoreirame/nandomoreirame.github.io) que faz todo o processo de build pra mim e manda pro github ;)

**Comment by theandersonn** [comment]
Vou citar um outro exemplo que pode lhe dar uma luz. _Utilizando Gulp e GitHubPages_.

Neste exemplo ignoro os arquivos de produção, depois termino a aplicação, implementação posso gerar uma versão final e chamar o Gulp pra chamar e pegar somente os arquivos da pasta 'dist' e jogar no github na branch escolhida.

Esse é um exemplo, ainda não testei com outro uso além do GitHub Pages. 

**Referência:** https://medium.com/superhighfives/deploying-to-github-pages-with-gulp-c06efc527de8
**Exemplo de Uso:** https://github.com/training-projects/ikaros

**Comment by eduardojmatos** [comment]
@kvnol Nós optamos por usar parte do ITCSS pra organizar o nosso CSS. Dá uma olhada aqui depois: https://github.com/getninjas/gaiden/tree/master/src/scss

**Comment by kvnol** [comment]
@eduardojmatos atualmente estou utilizando atomic design para organização do SASS, mas curti esse conceito. :metal:

**Comment by kvnol** [comment]
Linkando #165
