### ISSUE TITLE
Curso Tecnólogo

### ISSUE THREAD

**Issue by ojonathanleal-zz** [frontendbr/forum#518]
Bom dia galera, tenho uma dúvida.

Meu intuito é pegar um job remoto ou presencial fora do país.

Estou com vontade de cursar a faculdade e gostaria de saber se vale a pena fazer um Curso Tecnólogo na área? Eu sei que bacharel tem bastante valor para algumas empresas da gringa ;)

**Comment by LFeh** [comment]
Linkando: #509 #39 

Cara, eu fiz tecnólogo. 

Terminei a escola cedo, aos 16. Comecei um tecnólogo e acabei aos 18.

Só vi vantagens. É rápido, não bodeia, vale como curso superior em qualquer lugar, não tem TCC, pode fazer pós graduação depois...

**Comment by ericOnda** [comment]
Cara, acredito que na gringa eles não levem em consideração (claro que depende do Job) o tipo de graduação. No tocante a conseguir visto de trabalho, por exemplo, acredito que não seja relevante, desde que seja curso de graduação. O que é preciso prestar atenção, é que existem muitos cursos tecnólogos meia boca por ai, principalmente em faculdades particulares, pelo fato de ser um curso mais barato de ofertar (mais curto). Comecei Sistemas pra Internet no Instituto Federal, e a qualidade é bem satisfatória. Cheguei a cursas Tecnologo EAD em uma particular, com qualidade bem razoável, tranquei e joguei uma graninha fora.

**Comment by camillodev** [comment]
Em questão de visto, dependendo do pais pode ser um problema sim. Depende muito do pais e das regras sobre a profissão lá. No Canadá por exemplo é super de boa, até curso técnico conta. Já na Australia é um problema, eles pedem em geral Bacharel, por que o curso tecnologo para eles é considerado um Advanced Graduation, se não me engano, que é um nivel abaixo do Bacharelado. 

Entretanto caso você tenha tecnologo, você pode compensar com anos de experiencia, que só começam a contar após a conclusão do curso. Na Australia são necessários cerca de 5 anos de experiencia para o tecnologo, para o Bacharel 3 anos apenas. 

Você também tem a possibilidade de fazer um tecnologo e depois fazer o bacharel caso ache necessário. Se for na mesma instituição será facil, apenas 1 ano, se for em outra provavelmente será em mais tempo, pois precisará ver a equivalencia de matérias.

**Comment by ojonathanleal** [comment]
E os cursos bacharel EAD? tem o mesmo valor?

**Comment by willycamargo** [comment]
> E os cursos bacharel EAD? tem o mesmo valor?

@ojonathanleal ,
Pelo que andei pesquisando os cursos EAD e Presencial tem a **mesma validade** (como se fosse a mesma coisa). Nem tenho certeza se em algum lugar do diploma/certificado é referenciado que foi feito EAD.

**Comment by felipechalreo** [comment]
Sim. Tem o mesmo valor. No diploma não aparece que você fez EAD para evitar situações aonde o aluno EAD é "discriminado" não ter feito presencial.

**Comment by ojonathanleal** [comment]
@felipechalreo legal, isso que queria saber.

Obrigado pessoal.

**Comment by simaodeveloper** [comment]
só um nome FIAP

**Comment by victorkurauchi** [comment]
Fiz tecnológo em Análise e desenvolvimento de sistemas, hoje estou na 2a experiência com job remoto, e em nenhum dos dois eles chegaram a abordar profundamente sobre minha graduação, se foi técnologo/bacharel etc, logo não fez diferença. Mas isso para 2 casos que citei com jobs remotos. 

Já para uma vaga presencial fora do país talvez não consigo afirmar, até porque pode ser muito relativo de empresa pra empresa que você for aplicar.

**Comment by fabianokoseki** [comment]
(Desculpe a desenterrada, é um assunto que estou procurando muito nos últimos dias e gostaria de compartilhar)

Normalmente graduação é muito mais um problema de visto de trabalho, do que da empresa em si. A questão é que na maioria das vezes(se não todas), a empresa estrangeira que for bancar seu visto tem que provar para o governo onde reside, de que ela não achou ninguém capacitado no próprio país para realizar aquele job que você estará preenchendo, e burocraticamente falando o diploma é um perfeito indicativo(para o governo) de que você é capacitado.

Mas pelo menos tempo de experiência também conta bastante. E ai o tecnólogo serve como um empurrãozinho. O melhor cenário possível seria bacharel + tempo de experiência, e ainda mais que na nossa área tão necessitada, você tendo bacharel + experiência a última coisa que você iria se preocupar é com o visto de trabalho.

Para trabalhar remoto, muitas vezes você não necessita de um visto de trabalho para trabalhar remoto, e tenho visto que muitas poucas empresas pedem graduação, se pedem, é para uma futura tentativa de trazer você para o país em si.

E falando novamente dos governos em si, por exemplo o visto de trabalho H1-B dos Estados Unidos exige pelo menos um bacharel. Se não for, a escala fica 1 ano de bacharel = 3 anos de experiência. Isso significa precisar de 12 anos de experiência para ser o equivalente a um bacharel la nos EUA para poder aplicar ao visto H1-B. Com um tecnólogo, você teoricamente conseguiria reduzir 2 anos dessa necessidade, faltando 6 anos de experiência.

Agora, existem outros governos que o diploma de bacharel não é "obrigatório"(como falei nos EUA o H1-B exige o bacharel OU experiência similar), como o Canadá(LMIA), Alemanha(não achei um nome específico) e Holanda(Highly skilled migrant permit ), onde você pode conseguir o visto por tempo de experiência mesmo. Obviamente tendo uma graduação ajuda no processo.

Tudo depende dos seus objetivos. Se ainda entrar no mérito de mudança de país, sugiro quem estiver na decisão tecnólogo x bacharel pensar mais um pouco, visto que bacharel conta mais pontos para o visto de residente permanente em praticamente qualquer país.
