### ISSUE TITLE
Como profissionalizar sendo freelancer

### ISSUE THREAD

**Issue by Cleysonlb** [frontendbr/forum#52]
Fala galera! Alguém aqui é freelancer?! Bom, eu moro em uma cidade pequena onde não tem muita oportunidade, sei que o certo seria sair e tentar a vida em uma cidade maior, mas por alguns fatores ainda não sai nessa aventura, então, estou no caminho de profissionalizar sendo freelancer, alguém tem dicas, ideias, comentários, qualquer coisa que agregue ?

**Comment by LFeh** [comment]
Você diz se profissionalizar em que sentido? Abrir empresa e tudo mais?

**Comment by Cleysonlb** [comment]
Sim @LFeh  formalizar a coisa, se vale a pena etc... Pq aqui onde moro é sem chances...

**Comment by vitorbritto** [comment]
@Cleysonlb temos a _issue_ #28 com este contexto. Participa lá.
