### ISSUE TITLE
Problema com rolagem (scroll) no iOS

### ISSUE THREAD

**Issue by fdaciuk** [frontendbr/forum#520]
Eu e o @pedrogustavo estamos trabalhando em um projeto, e tentando fazer uma versão mobile decente. Acontece que no iOS, o _scroll_ às vezes funciona, às vezes para. Do nada.

Alguém já passou por isso? Não é possível que só esteja acontecendo conosco :joy: :joy: 

Já tentamos algumas "soluções" do tipo:
- adicionar uma div com `height: 101%` e `overflow: hidden` e remover depois de 500ms;
- adicionar um `touchstart` no `body`.

Foram algumas coisas que encontramos, mas nada resolveu :(

**Comment by LFeh** [comment]
Bota isso nos lugares que tem scroll:

```
  -webkit-overflow-scrolling touch
```

👊

**Comment by podrivo** [comment]
Issaqui: https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

**Comment by fdaciuk** [comment]
@LFeh e @podrivo tentamos também, não rolou :(
O problema acontece com scroll no body mesmo, não é nem em um elemento específico :sob:

**Comment by podrivo** [comment]
@fdaciuk rola em todos os devices? por acaso é um 5S?

**Comment by LFeh** [comment]
Ué, estranhíssimo. Isso deveria resolver.

Por desencargo de consciência, coloca para ativar o _hardware acceleration_. Mas não sei se é o caso:

```
-webkit-transform: translate3d(0,0,0)
```

Tem algum stage do projeto que você pode passar o link?

**Comment by pedrogustavo** [comment]
@podrivo Sim é um 5S.

**Comment by podrivo** [comment]
Já tive esse problema, mas só rolava no meu, que é um 5S. Não consegui resolver.
Limpar a gordura da tela ajudava um pouco, hehe.

**Comment by fdaciuk** [comment]
@LFeh com o `translate3d` funcionou! Valeu :dancer: :dancer: :sparkles: :heart:

**Comment by LFeh** [comment]
O touch no iOS tem dessas 😸 

Para saber mais:

[-webkit-overflow-scrolling](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling)
[An Introduction to Hardware Acceleration with CSS Animations](https://www.sitepoint.com/introduction-to-hardware-acceleration-css-animations/)
[Use 3D CSS transforms to take advantage of hardware acceleration](https://coderwall.com/p/rikxpg/use-3d-css-transforms-to-take-advantage-of-hardware-acceleration)

**Comment by K3yboard** [comment]
Estou com um problema parecido. No meu caso, na versão mobile tem um menu que ao ser ativado, ele fica por cima do conteúdo principal. Só que ao simular um scroll no container do menu, ele acaba fazendo o scroll também no container principal. Isso só acontece no Safari mobile. Alguem já passou por isso?

**Comment by tcelestino** [comment]
@K3yboard, a solução que o @felipefialho deu, não te ajuda? Links: https://github.com/frontendbr/forum/issues/520#issuecomment-291599190 e https://github.com/frontendbr/forum/issues/520#issuecomment-291601986
