### ISSUE TITLE
Requisição Ajax com o método Post

### ISSUE THREAD

**Issue by grodrigues** [frontendbr/forum#522]
Estou fazendo uma Requisição Ajax com o método post mas quando o back recebe os dados ele recebe string vazia. Como posso corrigir ?

```
$("#cadastrar").submit(function() {
       var dados = jQuery(this).serialize();
         $.ajax({
           type: "POST",
            url: "url",
            datatype: 'json',
            success: function(data){
                data = $.parseJSON(data);
         }, //END success
            error: function(e){
                alert("Erro: " + e);
           } 

         }); 

     });

**Comment by mikejavier** [comment]
@grodrigues tu colocou name nos campos do formulario ?

**Comment by WandersonAlves** [comment]
Olhando a api do [post](https://api.jquery.com/jquery.post/) do jQuery e teu codigo, não vejo você passando o seu `dados` pelo post.

Não deveria ser isso aqui não?
```
$.ajax({
           type: "POST",
            url: "url",
            datatype: 'json',
            **data: dados**
            .............
```

**Comment by grodrigues** [comment]
@mikejavier coloquei sim.

**Comment by mikejavier** [comment]
@grodrigues como o @WandersonAlves disse estão faltando enviar os dados.

**Comment by gabrieldarezzo** [comment]
> @mikejavier coloquei sim.
@grodrigues não consta no seu código de exemplo


Tenho um passo a passo pratico de como executar um Ajax no git.
https://github.com/gabrieldarezzo/desafiosInternos/tree/master/ajax#guia-definitivo-ajax


De qualquer forma a leitura como informado pelo @WandersonAlves  é fundamental.
https://api.jquery.com/jquery.post/


Só complementando o exemplo :  
```js

//cuidado com o escopo do this
var dados = $('#js-newsletter *').serialize()

$.ajax({
	type: "POST",
	url: "url",
	datatype: 'json',
	data: dados
	....
```

**Comment by grodrigues** [comment]
Está dando agora xhr failed no console

**Comment by mahenrique94** [comment]
@grodrigues tente fazer com javacript puro em vez de utilizar jquery.

[Aqui](http://blog.alura.com.br/preenchendo-formulario-html-automaticamente-com-ajax/) segue um exemplo de como fazer utilizando **GET**, mas não muda muita coisa.

Utilizando o jquery você precisa passar os inputs em formato serializado ou FormData.

**Comment by grodrigues** [comment]
@mahenrique94 Certo. Vou testar

**Comment by grodrigues** [comment]
@mahenrique94 consegui desenvolver. 👍
