### ISSUE TITLE
O que é necessário saber para conseguir um emprego de front end?

### ISSUE THREAD

**Issue by gabrielpaesschulz** [frontendbr/forum#527]
Estou estudando front end a um mês e tenho dúvidas em relação à:

- O que devo saber para ser considerado empregável em alguma empresa?
- O quanto eu devo saber de html/css/javascript para começar a me candidatar a algo?
- O que as empresas esperam de um front end jr?
- Como é o dia-a-dia na profissão?
- Quando conseguiram seu primeiro emprego na área se sentiram meio perdidos em um ambiente profissional?

Qual o caminho que vocês indicam para alguém que quer entrar na área mas se sente um pouco 'soterrado' com a quantidade de informações e tecnologias disponíveis. 

Enfim tenho muito interesse na área mas as vezes me encontro perdido. Estou anexando uma lista contendo um 'caminho' que estou a seguir.

[aprender.txt](https://github.com/frontendbr/forum/files/904351/aprender.txt)

**Comment by kvnol** [comment]
Recomendo a leitura das issues: #38, #270, #503 e #456. :metal:

**Comment by mahenrique94** [comment]
Para começo de conversa você deve no mínimo dominar HTML5, CSS3 e JS, foque primeiro no básico e domine esses três requisitos.

Após ter domínio sobre os mesmos, você pode começar entrar nos frameworks e bibliotecas: Bootstrap, Foudation, Materialize, Angular, React, Vue, jQuery, etc...

Prátique e estude bastante, a prática vai fazer com que você desenvolva e aprenda cada vez mais, durante o começo evite usar bibliotecas prontas, faça as suas.

Abraçooos.

**Comment by LFeh** [comment]
Recomendo ainda uma série de entrevistas com profissionais, que o @woliveiras tem feito. Vão responder muitas das suas dúvidas :)

A minha está aqui: [Como é trabalhar como Desenvolvedor Front-End, por Felipe Fialho
](https://medium.com/trainingcenter/como-%C3%A9-trabalhar-como-desenvolvedor-front-end-por-felipe-fialho-1e3efbadef90)

**Comment by didiraja** [comment]
Estou nesse ponto da carreira também, além das issues que o @kvnol citou. **De maneira sucinta**, o que vejo o mercado pedindo é: _HTML, CSS, JS, Bootstrap, jQuery, GIT, Grunt/Gulp, Less/Sass e Angular/React_.

**Comment by neysimoes** [comment]
Não li as outras issues e por isso estou me baseando apenas na minha visão.

--- 
#### O que devo saber para ser considerado empregável em alguma empresa?
- O básico para ser um desenvolvedor front-end é saber HTML, CSS, JS e GIT.
- Como diferenciais algum pré-processador e uma lib e/ou um framework JavaScript.

---
### O quanto eu devo saber de html/css/javascript para começar a me candidatar a algo?
- Ter feito pelo menos 1 ou 2 sites. Essa é a melhor forma de validar seu conhecimento em front-end.
- Para isso você pode criar algo para você mesmo, ou fazer algo para um parente ou amigo.

---
### O que as empresas esperam de um front end jr?
- Que você tenha mínimos conhecimentos na área. 
- Que saiba onde tirar suas dúvidas (stackoverflow, forums...).
- Pró-atividade, capacidade de aprendizado e que você demonstre interesse nos assuntos da área.
- Uma coisa que também se analiza é perfil. Se você é sociável, ética, comportamento, mas essa parte é subjetiva.

---
### Quando conseguiram seu primeiro emprego na área se sentiram meio perdidos em um ambiente profissional?
- Quem dera que seja só no primeiro,  já estou na 5a empresa na área e sempre me sinto perdidos no ambiente profissional.
- A dica é nunca achar que sabe tudo, não ter medo de perguntar, anotar o que te ensinarem e estudar em casa os assuntos que você tem dúvida no trabalho.

## Dicas
- Ninguém sabe tudo.
- Ninguém precisa saber tudo.
- Você não precisa estudar todas as libs e frameworks do mercado.
- Não se preocupe com AngularJS, React, jQuery, Bootstrap, pré-processadores... nada disso agora.
- Foque em aprender JavaScript puro, CSS puro e HTML.
- Se você souber como funciona o HTML, CSS e JS, os framworks, libs e pré-processadores você vai pegar fácilmente.
- Não existe melhor framework ou lib JavaScript, isso é bullshit. 
- Existe uma linguagem chamada JavaScript e se você aprender ela vai poder trabalhar com qualquer lib ou framework.
- Não existe melhor pré-processador (mentira stylus é amor), aprenda CSS saiba como ele funciona e ai sim aprenda ~um pré-processador~ **stylus**

**Comment by thulioph** [comment]
Sempre tento aplicar um conceito, tanto no meu trabalho como na vida pessoal chamado de **Conhecimento em T**. 

A idéia é você ser "especialista" em uma coisa, porém tendo um conhecimento razoável em uma série de outras coisas que de certa forma fazem parte (ou não) do conhecimento que você escolheu se aprofundar.

- Estude a base da web **HTML**, **CSS** e **Javascript**.

- Escreva bastante código, a prática leva a perfeição.

- Não ponha a carroça na frente dos bois, uma coisa de cada vez.

- Faça por amor, porque se for por grana é melhor nem começar.

---

Se tiver interesse em saber mais sobre o conceito que foi dito:

- https://jorgekotickaudy.wordpress.com/2016/02/15/equipes-ageis-e-profissionais-t-especialistas-com-conhecimento-multi-disciplinar/

- http://www.deboraaquino.com.br/2017/02/se-voce-quer-ser-um-bom-profissional.html

- https://www.google.com.br/search?q=conhecimento+em+T&oq=conhecimento&aqs=chrome.0.69i59j69i60l3j69i57j69i60.1097j0j1&sourceid=chrome&ie=UTF-8

Boa sorte nos estudos e lembre-se sempre, todo mundo começou igual a você, sem saber nada, um pouco perdido, determinação e foco são essenciais.

**Comment by Fabio-Pina** [comment]
> Para começo de conversa você deve no mínimo dominar HTML5, CSS3 e JS, foque primeiro no básico e domine esses três requisitos.
> 
> Após ter domínio sobre os mesmos, você pode começar entrar nos frameworks e bibliotecas: Bootstrap, Foudation, Materialize, Angular, React, Vue, jQuery, etc...
> 
> Prátique e estude bastante, a prática vai fazer com que você desenvolva e aprenda cada vez mais, durante o começo evite usar bibliotecas prontas, faça as suas.
> 
> Abraçooos.

Desculpe mas acho que a pessoa vai cair no loop infinito sendo que HTML, CSS pode ser até relativamente fácil. Porém JavaScript já deve-se ter um conhecimento de Lógica de Programação e é mais difícil que as primeiras citadas. Olha quantas coisas a pessoa já tem de estudar fora as que vocẽ citou. Acho bem complicado esse caminho mas respeito sua opinião.

**Comment by diogorodrigues** [comment]
Ótimas respostas galera. Creio que não há um caminho único para se aprender desenvolvimento front-end. Porém, existem alguns caminhos comuns, que a maioria dos devs percorrem no início.

@Fabio-Pina foi justamente pensando nesse loop que escrevi o artigo [Como se tornar um ótimo desenvolvedor front-end](https://www.diogorodrigues.dev/pt/blog/como-se-tornar-um-otimo-desenvolvedor-front-end) destacando o que estudar durante as três fases no processo de aprendizado: iniciante, intermediário e avançado. Além disso, o artigo leva em consideração o cenário atual do mercado. Espero que ele possa ajudar a dar uma direção na jornada de cada um. 😀

**Comment by luisalms** [comment]
Olá, @dionarodrigues , infelizmente está fora do ar o link, queria ler =/
