### ISSUE TITLE
Procurando o livro O Melhor do JavaScript - Douglas Crockford

### ISSUE THREAD

**Issue by marcosmessias** [frontendbr/forum#531]
Olá pessoal, gostaria de saber se alguém tem o livro O Melhor do JavaScript - Douglas Crockford para doar, vender, trocar.
Sempre ouvir falar muito bem dele, quero lê-lo, só achei o livro em inglês, mas como ainda sei inglês, estou procurando o livro em português. 
Não sei se posso postar isso aqui, se não puder desde já peço desculpas.

**Comment by ericdouglas** [comment]
@marcosmessias manda seu endereço por e-mail que eu te envio o livro. Meu e-mail está [aqui](https://github.com/ericdouglas)

**Comment by mahenrique94** [comment]
compartilha com a galera @ericdouglas

**Comment by marcosmessias** [comment]
O que ele vai me passar é o livro impresso.

**Comment by ericdouglas** [comment]
@mahenrique94 como o Marcos falou, eu tenho o livro impresso, ai vou doar para o colega que abriu a issue.

**Comment by kvnol** [comment]
Pessoal, temos um repositório apenas para doações de livros. Conseguem postar essa issue lá? :metal: 

https://github.com/frontendbr/doe-um-livro/issues

**Comment by marcosmessias** [comment]
Livro não doado.

**Comment by ericdouglas** [comment]
Iria enviar o livro hoje, não tive tempo de fazer antes devido a N fatores.

Peguei o livro para folhear e vi alguns erros de tradução (termos que não deveriam ter sido traduzidos) e o que mostra no livro já está desatualizado. Bom, é um livro de **2008**, então não é de se esperar muita coisa depois das grandes alterações que o ES6 trouxe.

Disse para o colega que simplesmente não vale a pena ter o trabalho de ir no correio e gastar dinheiro + tempo com transporte para um livro que não é relevante mais.

Além disso passei uma lista de materiais gratuitos muito mais relevantes para ele.

:v:

**Comment by NicholasNeto** [comment]
@marcosmessias  @ericdouglas ericdouglas

Vocês tem o livro ainda, estou procurando pra comprar mesmo..

**Comment by phillipecarvalh0** [comment]
Alguém conseguiu o livro??
