### ISSUE TITLE
A Dualidade do Generalista

### ISSUE THREAD

**Issue by Cleysonlb** [frontendbr/forum#532]
Galera, primeiramente iai beleza?!
Então, estou vivendo um dilema profissional, hoje trabalho em uma empresa diretamente como     "full stack" atuando tanto no front quanto no back (ruby on rails), acho mt legal, esta sendo um puta aprendizado!
Mas... o Design e UX sempre me chamou mais atenção, porém, entretanto, nunca atuei de fato na area, então, fico no dilema se foco inteiramente no que estou trabalhando agora ou se vou me aperfeiçoando para no futuro atuar no Design/UX.
Vocês vivem algo parecido?! Me contem suas experiências!

**Comment by fititnt** [comment]
@Cleysonlb sou full stack e comentei um pouco sobre isso em #506.

---

Comentários extras para você:

Olha, eu já incentivei muita gente a crescer rápido e de ultimamente acabei vendo mais sobre metacognição e a forma como as pessoas aprendem e, em vez de ficar dizendo o que é certo e errado, estou vendo que é bem mais interessante procurar algo mais individualizado e focado em o que vai fazer a pessoa usar de fato.

E, para isso, tem forte relação com felicidade e auto realização pessoal, pois ao fazer algo que você não apenas trabalha, mas gosta, você entra mais frequentemente em um estado chamado de flow (fluxo). 

Uma palestra bacana sobre isso em português está aqui https://www.ted.com/talks/mihaly_csikszentmihalyi_on_flow?language=pt-br
