### ISSUE TITLE
Flexbox order e flex item com height

### ISSUE THREAD

**Issue by eduardojmatos** [frontendbr/forum#533]
Pessoal, estou tentando resolver um lance com flexbox usando order. Acontece que um dos itens do container pai tem uma altura mínima definida ou que sempre é maior que as demais.

Eu tenho como objetivos:

1- Fazer com que o _elemento 2_ fique alinhado logo abaixo do _elemento 1_;
2- Não quebrar os próximos irmãos do _container_ que contém esses elementos. Então, não dá pra colocar position absolute ou coisa do tipo;
3- Usar JavaScript pra manipular a ordem é **último caso**.

Fiz um codepen pra ilustrar o problema: https://codepen.io/eduardojmatos/pen/LyPYqy

O print pra quem quiser entender melhor é esse: 
![screen shot 2017-04-10 at 11 11 32 pm](https://cloud.githubusercontent.com/assets/1279783/24889885/12d4faa6-1e43-11e7-9b0a-afecca1fbb37.png)

Tentei resolver aplicando `order: -1` nos elementos 1 e 2, mas ainda não consigo alinhar o 3 no topo do container (https://codepen.io/eduardojmatos/pen/NjKWJo) e print:

![screen shot 2017-04-10 at 11 15 50 pm](https://cloud.githubusercontent.com/assets/1279783/24890003/b618ad5c-1e43-11e7-9a01-1090ad9c81cf.png)

* * *

Alguém já conseguiu resolver esse problema usando alguma abordagem?

**Comment by afonsopacifer** [comment]
Então, flexbox é unidirecional, não foi feito para trabalhar com o conceito de linhas e colunas ao mesmo tempo, por isso esse comportamento. para solucionar você pode usar Grid Layout, vou fazer um exemplo p vc..

**Comment by eduardojmatos** [comment]
@afonsopacifer boa! Mas ainda dou suporte pra IE9 e IE10, além de Android 4+ :(

**Comment by kvnol** [comment]
@eduardojmatos para fazer isso com Flexbox só se você quebrasse com mais uma div, dessa forma: 
![image](https://cloud.githubusercontent.com/assets/3299130/24890467/739e010e-1e46-11e7-8449-56ce1fd3bd5e.png)

**Comment by marcusvcribeiro** [comment]
Uai, flexbox dá suporte para IE9?? Pensei que era somente do 10 pra cima

Em 10 de abr de 2017 23:35, "Eduardo Matos" <notifications@github.com>
escreveu:

**Comment by williamcosta** [comment]
@eduardojmatos Eu ia mandar a mesma sugestão que o @kvnol mandou de quebrar em mais uma container.

**Comment by neysimoes** [comment]
@marcusvcribeiro existe fallback para flexbox IE8/9+ (IE8 parcial), mas não existe para Grid Layout.

**Comment by eduardojmatos** [comment]
@kvnol a ordem volta pra 1, 2 e 3 :/

**Comment by afonsopacifer** [comment]
@eduardojmatos  vc pode usar uns macetes de progressive enhancement, da para fazer fallback de Grid Layout com p próprio flexbox ou float.. usando fault tolerance :)

Talvez não tenha o mesmo resultado nas coisas antigas, mas não vai quebrar.. será uma experiência progressiva de fato...

**Comment by eduardojmatos** [comment]
@marcusvcribeiro estamos usando polyfill pra IE9 usando display block|inline quando não tem suporte pra flexbox

**Comment by eduardojmatos** [comment]
@afonsopacifer tô ligado hehe queria tentar algo sem ter que usar CSS Grid por hora, mas talvez não role mesmo 😭

**Comment by kvnol** [comment]
@eduardojmatos pode crer, edu. então deixa eu entender, o terceiro item terá a posição dois porque sempre que entrar mais um item ele vai para a lista normal e o outro (quarto no caso) fica maior, no lado?
 Não entendi direito o por que do item 3 ser order 2.

**Comment by afonsopacifer** [comment]
@eduardojmatos Voto em você vir p o lado Grid fa força ❤️ 
Mas se não puder mesmo, e se até amanhã não resolver, tento algo p ajudar.. só não dá agora pq tenho que dormir :)

**Comment by kvnol** [comment]
CSS Grid é lindo, @afonsopacifer. Estou tentado e esperando pegar um projeto novo pra meter o CSS Grid em cena.

**Comment by eduardojmatos** [comment]
@kvnol no mobile a ordem vai ser 1, 3 e 2. Falei errado lá em cima né? Mals heheh

**Comment by neysimoes** [comment]
@eduardojmatos ficou fácil depois que vc falou que a ordem é 1 3 2 no mobile.
http://codepen.io/neysimoes/pen/pPzPWd

**Comment by vitormd** [comment]
Tira o order e coloca um `height` fixo no container junto com `flex-direction: column` ao invés de `row`.
Não curto atribuir `width` e `height` fixos, mas já tem um, que mal faz o outro ;) 

![image](https://cloud.githubusercontent.com/assets/2192462/24909731/783da8e0-1e9b-11e7-989a-4eb31798e171.png)

**Comment by eduardojmatos** [comment]
@neysimoes float left com flexbox os puristas vão me matar hauhua

Mas acho que não vai ter jeito...

**Comment by eduardojmatos** [comment]
@vitormd o container não pode ter tamanho fixo e o item 3 tem tamanho variado (o min-height foi só pra exemplificar o problema :/).

Eu pensei nessa solução inicialmente, mas teria que ter JS colocando o tamanho do container 😭

**Comment by neysimoes** [comment]
Sejamos realistas. Grid Layout é lindo e maravilhoso, mas no mundo real as pessoas ainda usam IE e  navegadores desatualizados.
Para ser viável usar precisaria de pelo menos um polyfill com suporte para IE10+.

**Comment by afonsopacifer** [comment]
@neysimoes Sim, mas lembrando que além de um polyfill... dá para fazer progressive. Uma vez que Grid Layout desabilita float por exemplo, ou outras coisas com display..

**Comment by felipechalreo** [comment]
@eduardojmatos  é isso que você quer? 

https://codepen.io/felipechalreo/pen/pPzWOa

**Comment by eduardojmatos** [comment]
@felipechalreo sim, mas preciso que no mobile o nav azul fique entre um dos itens em roxo

**Comment by afonsopacifer** [comment]
@eduardojmatos Promessa é divida ❤️ 
https://codepen.io/afonsopacifer/pen/wdwEVB

Fiz apenas com float, já que vc precisa suportar IEs antigos, se der problema usar float me fala que faco de outro jeito <3

**Comment by eduardojmatos** [comment]
@afonsopacifer <3 boa!! Eu vou seguir com float mesmo. Não vai ter jeito heheh

**Comment by eduardojmatos** [comment]
Ae pessoal, tá no ar o lance que falei aqui.

https://www.getninjas.com.br/reformas-e-reparos/pedreiro/rj/rio-de-janeiro/orcamentos/3174190-furar-buraco-na-parede-para-colocar

Se olharem, o form ficou na esquerda, mas no mobile ele fica logo abaixo do highlight da página (o texto do pedido do usuário).

**Comment by vitormd** [comment]
👏
