### ISSUE TITLE
Dicas para elaborar um portfólio atraente para as empresas

### ISSUE THREAD

**Issue by DaniloAgostinho** [frontendbr/forum#544]
Muito boa tarde pessoal, 

Na opinião de vocês o que as **empresas/pessoas/recrutadores** esperam que um **portfólio** tenha? Não me 
refiro apenas a um alonga lista de **trabalhos** e **diplomas**. Gostaria de criar o meu e não sei bem se uno **portfólio/blog**..

Hoje em dia vcs acham que os **portfolios** estão mais **dinâmicos/animados/estáticos?** Se tiverem ai algum link.. pode ser o seu **portfólio** também, vou adorar saber como, e o que você usou de tecnologia. 

Abrs

**Comment by waldemirflj** [comment]
Cara, eu tenho um .txt explicando cada projeto que participei e qual foi a minha participação. Recentemente fui cobrando por um gestor sobre cronologia, e até então isso não me parecia importante, mas é... :)

**Comment by LFeh** [comment]
Linkando: #509 

Leia essa: #440
