### ISSUE TITLE
Certificados para Devs Front-End

### ISSUE THREAD

**Issue by vitocaio** [frontendbr/forum#549]
Pessoal, gostaria de saber se existe algum certificado que ajuda a dar um verdadeiro UP na carreira na are de Front, sabemos que Java, C#, SQL, etc, tem suas certificações de peso, mas e quem é dev front-end?
existe alguma? qual é e como conseguir? desdê já obrigado.

**Comment by kvnol** [comment]
@vitocaio, recomendo a leitura da issue #509.

**Comment by vitocaio** [comment]
@kvnol èssa issue fala muito sobre carreira e como é importante o conhecimento além da faculdade, mas digo isso para quem tem conhecimento, mas precisa provar que tem em um currículo, entendi?

**Comment by kvnol** [comment]
@vitocaio, sim, sim. Eu marquei a issue só pra não esquecer, mas minha opinião sobre isso é que vale muito a pena ter certificados e não só por conta de currículo, mas pelo aprendizado mais coordenado que temos em cursos.

PS: Fica aqui meu desejo de estudar na Caelum com o @marcobrunobr, mas que estou procrastinando por conta do preço mas que, este ano, ainda farei.

**Comment by HaluDeCassia** [comment]
Bom, a pergunta ainda não foi respondida. Também quero certificações e especializações na área, mas nunca acho algo legal. Alguma dica ou sugestão além da já conhecida "escave tudo que puder sobre o assunto na internet"?

**Comment by calaca** [comment]
A única certificação que me vem em mente agora é a [Mobile Sites Certification](https://www.google.com/partners/#p_mobilesitescertification) da Google. Acho que a Microsoft também dá umas certificações de HTML, CSS e JS de graça, provavelmente pela msdn.

**Comment by HaluDeCassia** [comment]
Essa dica é boa, valeu 😊

-- 
Att, Haluane Amâncio

**Comment by vitocaio** [comment]
Bom o site Aluta tem alguns cursos na área de front todos com certificado no final, será que eles tem um peso no mercado?

**Comment by didiraja** [comment]
> Bom o site Aluta tem alguns cursos na área de front todos com certificado no final, será que eles tem um peso no mercado?

@vitocaio eu vinha perguntar a mesma coisa. eu to acostumado á portfolio valer mais que certificado, mas se os certificados realmente valerem, eu começo a imprimir todos que tenho tirado na Alura.

**Comment by AlexsandroSA** [comment]
@vitocaio tem o [freeCodeCamp](https://www.freecodecamp.org/) é free e bem legal :)

**Comment by phenriqueleao** [comment]
> Bom o site Aluta tem alguns cursos na área de front todos com certificado no final, será que eles tem um peso no mercado?
Também fiquei interessado em saber.

**Comment by edmolima** [comment]
@vitocaio tentando te responder. Existem algumas certificações como [Exame 70-480](https://www.microsoft.com/pt-br/learning/exam-70-480.aspx).  Mas de verdade, eu tenho ela e alguns certificados de cursos e nunca fui cobrado por isso mesmo tendo 6 anos já na area de desenvolvimento web. Nem mesmo as minhas de Java. Talvez pra consultorias seja importante pois elas "vendem" a especialidade de seus funcionários.

O que vale no final é o background com o que tu trabalhou, como tu pode provar isso em conhecimentos básicos. Ter resolvido problemas diferentes na area e principalmente entender bem de padrões de projetos. Se você tiver uma base sólida, isso será suficiente para o up de carreira que tu talvez precisa!

Espero ter te ajudado =)

**Comment by juliok80** [comment]
Acho que os certificados da Alura não tem peso algum no mercado. Conheço um cara onde trabalho que fica dando next > next nos cursos só para ganhar o certificado.
Acho que o que mais vale é a experiência, dedicação, um bom portfólio, ser uma pessoa detalhista e, por fim, um pouco de perfeccionismo não faz mal a nenhum front-end. :)

Abraços!

**Comment by renanlara** [comment]
Como o @kvnol mencionou, Caelum até onde sei é de peso. O @omariosouto pode também falar um pouco mais da Caelum pra gente.

**Comment by peas** [comment]
Oi pessoal. 

Sou um dos responsáveis pela Caelum/Alura e posso ter uma opinião meio biased, mas você vai ver que ela surpreende:

TL;DR: Mostrar que você sabe fazer, que é empenhado, que sabe correr atrás na hora certa, é pra mim bem mais importante que qualquer título, graduação ou certificado. Não que esses últimos não tenham seu valor.

Fiz graduação e mestrado na usp e sei como isso influenciou as minhas primeiras contratações. É fácil falar isso de uma posição privilegiada. Mas, depois de alguns anos, esses certificados, diplomas e faculdades começam a ficar em segundo plano. Onde você trabalhou, o que fez, o que pode fazer e como se relaciona com as pessoas sem dúvida é algo mais forte do que apenas confirmar onde você estudou o que aprendeu.

Eu gosto de certificados, gosto de certificações e não à toa fiz mestrado, mas sem dúvida o que dou destaque na minha vida profissional é a forma que empreguei esses conhecimentos, como resolvi problemas e o que solucionei para as empresas.

Como mostrar isso? Portfolio no github? Textos detalhados no linkedin? Uma boa conversa na entrevista? Um email bem elaborado demonstrando seu interesse pela empresa em questão? Todos são válidos (eu gosto MUITO da última opção, onde você demonstra que quer aquela vaga de forma clara). 

Se um empregador conseguir enxergar que você sabe criar um pequeno projeto, passar pelos diversos problemas e resolvê-los, e colocá-lo em produção, importa bem pouco se você aprender na alura, no concorrente, no blog de um amigo, sozinho ou em grupo.

Como disse o @juliok80, muita gente em curso online fica só no next/next para ter o certificado (por isso criamos as formações com avaliação de projetos finais). Muitas faculdades também a galera faz de um jeito bem duvidoso. Até mesmo certificações difíceis é possível você decorar um monte de regrar e não saber resolver problemas em si. Por isso demonstrar conhecimento é bem mais importante. Lembrando novamente que não é apenas através de github, opensource e eventos/comunidade que dá para fazer isso. (inclusive há uma série de pontos contra o uso do github como forma de descarte de candidatos https://www.benfrederickson.com/github-wont-help-with-hiring/)

Eu hoje lidero uma empresa com 150 colaboradores e posso falar com firmez que certificados e diplomas são a última coisa que olho.

**Comment by joaosantos** [comment]
@peas Oi, Boa noite! Sei que o post é meio velho, mas estava pesquisando sobre o assunto e acabei por aqui, você diz que certificados e diplomas são a última coisa que você olha, então, você teria alguma dica para um front-end júnior que está querendo entrar na área, mas não possui, superior, certificados, só alguns sites no GitHub? Tenho achado bem difícil conseguir algo em Salvador.

**Comment by Thauan** [comment]
@joaosantos Bom dia colega! Eu sou de Salvador também, para CLT sinto dificuldade em vagas aqui, pois o diploma ainda pesa bastante, e eu tranquei por um tempo. Por outro lado estou montando uma agencia digital, para criação de websites, sistemas, produção gráfica, edição de vídeo e fotografia. Então acredito que freelas assim você encontra melhor, até formar um portfólio interessante, assim você consegue ter relevância mesmo sem ter graduação.

**Comment by joaosantos** [comment]
@Thauan Boa tarde Thauan! Recentemente me inscrevi na Workana justamente para ganhar essa experiência e reconhecimento.

**Comment by peas** [comment]
> @peas Oi, Boa noite! Sei que o post é meio velho, mas estava pesquisando sobre o assunto e acabei por aqui, você diz que certificados e diplomas são a última coisa que você olha, então, você teria alguma dica para um front-end júnior que está querendo entrar na área, mas não possui, superior, certificados, só alguns sites no GitHub? Tenho achado bem difícil conseguir algo em Salvador.

@joaosantos eu acho que github ja é legal sim, mas talvez mostrar o que voce consegue resolver, que problemas consegue atacar, é ainda melhor. colocar um site no ar, manter algo em pé, tem mais valor ainda pra mim que um código legal de teste no github. mas é opinião pessoal. certificação tambem pode ajudar num primeiro momento. e mandar um email para as vagas sempre demonstrando real interesse, passando a mensagem de que leu sobre a empresa e os desafios dela.

**Comment by raulen12** [comment]
Obrigado pela informação
