### ISSUE TITLE
Saber quanto tempo até criarem pacote NPM do Code golf do código lindo

### ISSUE THREAD

**Issue by fititnt** [frontendbr/forum#553]
Tive essa ideia por conta da issue #550 do @munizart

A proposta aqui é o seguinte: **Saber quanto tempo até criarem pacote NPM do Code golf do código lindo**

_Menor/melhor código_? Só sabemos [que alguém vai usar regra 34 da programação e criar pacote NPM](https://twitter.com/aleczopf/status/656953700120924164)
_Imprimir_ pode ser qualquer saída a partir de `2017-04-26T04:37:37Z`, como um pacote sobre um pacote a ser criado. Pode não ser JS, de um package manager de outra linguagem. Pode nem ser computador. Pode nem ser.

Eu não vou tentar manter atualizado aqui TOP3, pois a imaginação, aqui como [Pensamento Divergente / emprededorismo](https://www.lingq.com/learn/en/preview/item/151043/) (ou ["zuera/huehuehue"](https://github.com/frontendbr/forum/issues/550#issuecomment-297559840)) não tem limites.

---
Edit: colocado link em "zuera/huehuehue" para [comentário sobre o tema relacionando com potencial inovador](https://github.com/frontendbr/forum/issues/550#issuecomment-297559840).

**Comment by v0idpwn** [comment]
vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. vai tomar no cu. 

obrigado.

**Comment by fititnt** [comment]
## Nome do serviço ou produto: _QuantoTempoAté via Twitter_[1]

O cliente que usa rede social Twitter pode perguntar ao usuário https://twitter.com/fititnt. A interação não requer conhecimento avançado, instalação de software específico, e é humanizada, focada no bom atendimento.

Oferecemos um serviço "Fremium" onde o cliente segue a conta [@fititnt](https://twitter.com/fititnt) e é seguido de volta, podendo ter acesso privado as interações.

Serviço VIP está na nossa lista de planejamento. Possivelmente será entre R$79,99 a R$299,99 (pagamento único) e terá o direito de ser avisado proativamente quando acontecer, e terá um tempo de resposta garantido menor (contas free e fremium podem demorar até 5 dias para resposta)

## Pontos para investidores

- [x] Permite franquias
- [x] Atendimento humanizado
- [x] Ideal para pessoas que não instalariam algo complexo apenas para saber sobre isso
- [x] Disponível para parcerias
- [ ] Escalável [2]
- [ ] Compartilhamento de dados dos usuários (com ou sem pagamento de VIPs, teremos os dados [afinal, o usuário pode ser um produto](http://www.huffingtonpost.com/dragos-bratasanu/you-are-not-the-facebook-user-you-are-the-product_b_7978104.html))
- [ ] Concorrência baixa (infelizmente, poderá haver concorrência, e essa será gratúita)
- [x] Disponibilidade para evoluir ([nossa equipe está preparada para mudar completamente o negócio](http://www.businessnewsdaily.com/8813-successful-startup-pivots.html))



## Comentários extras



1: Estamos em processo de registro da marca no INPI
2: Como nosso foco é atendimento humanizado em um ambiente onde todos costumam receber respostas mais "duras", por estratégia de negócio deverá ser revisto pra escalar. Esta fase é necessária para _aprender sobre o publico alvo_, por exemplo, geramos mais empatia respondendo com anexos de gifs de gatinhos ou de cachorros?
