### ISSUE TITLE
Eventos no RJ de Front-End

### ISSUE THREAD

**Issue by didiraja** [frontendbr/forum#558]
Olá a todos. Estou iniciando no mundo do front-end e além de praticar meu código, ler artigos e participar aqui do fórum, gostaria de começar a frequentar eventos locais sobre o assunto e descobrir conteúdos variados além do meu circuito de estudos. 

Na rápida pesquisa que fiz, a única coisa que achei foi a página do [Front-End Carioca](https://www.facebook.com/frontendcarioca/) mas que não dá sinais de vida depois da edição de 2016.

Poderiam, por favor, recomendar eventos e/ou páginas onde eu pudesse ficar de olho pra saber quando rola algo do tipo por aqui? Claro que não precisa ser algo exclusivo de Front-End, basta ter conteúdo sobre desenvolvimento web.

**Comment by Lucasktrindade** [comment]
Olha, tem rolado alguns meetups no RJ de diversos assuntos de front. Segue abaixo alguns que recomendo e faço parte da organização, sempre temos variados assuntos:
https://www.meetup.com/pt-BR/GDGDuquedeCaxias/, https://www.meetup.com/pt-BR/Google-Developer-Group-GDG-Rio-de-Janeiro/.

Todo mês tem o Rio.JS mas eles fazem uma divulgação no Telegram. E tem esse canal no Telegram que sempre posta sobre vários meetups https://t.me/EventosTI_RJ.

**Comment by yanmagale** [comment]
@didiraja o FEC é anual, geralmente em setembro, outubro

**Comment by theandersonn** [comment]
@didiraja Estamos passando por um período bem morno aqui no Rio, é difícil conseguir locais para meetups, quando consegue-se poucos vão, as vezes pelo horário, pela distância... 

Enfim, alguns grupos que já realizaram eventos e vale a pena ficar de olho:

FEMUG RJ
https://pt-br.facebook.com/femugrj/

Front In Rio
http://frontinrio.com.br/

RioJS (Já realizou meetups bem irados)
https://github.com/riojs-org

PHP Rio (Realiza pequenos encontros num bar da lapa e meetups períodicos, normalmente no senac do centro)
https://www.meetup.com/pt-BR/PHP-Rio/

WP Rio (Meetups regulares, os últimos tem rolado no UVA da Tijuca. Está sendo preparado um para maio)
https://www.meetup.com/pt-BR/wp-rio/

WP Baixada Rio (Já realizou meetups na Estácio de Nova Iguaçu)
https://www.meetup.com/pt-BR/baixada-rio/ 

Aqui na org temos um repositório com varias datas, é atualizado regularmente.
https://github.com/frontendbr/eventos/issues 

E um site lindão:
http://frontendbr.com.br/eventos/

**Comment by didiraja** [comment]
@Lucasktrindade @yanmagale obrigado e principalmente @theandersonn pela caralhada de eventos!!!! É bem o que tava procurando.
