### ISSUE TITLE
gerador de boleto

### ISSUE THREAD

**Issue by leandroruel** [frontendbr/forum#559]
eu sei que não é front, mas, se alguém souber me dizer, alguém conhece uma classe de geração de boleto atualizada, e que possa ser instalada via composer? eu achei essa mas olha a data dos últimos commits, não estou me sentindo seguro em usá-la: https://github.com/CobreGratis/boletophp

**Comment by waldemirflj** [comment]
Fala ai @leandroruel  de boa?

Cara, depois da um olhada nesse serviço da DC http://cobranca.digital/.

**Comment by leandroruel** [comment]
@waldemirflj obrigado pela sugestão, é grátis? gostei do site.
