### ISSUE TITLE
Aprender JavaScript - 2017

### ISSUE THREAD

**Issue by danilogila** [frontendbr/forum#563]
Boa noite pessoal! Defini como meta pessoal aprender Javascript, HTML e CSS nesse ano. O HTML e CSS está sendo fácil achar bons canais mas em relação ao Javascript, a historia é outra.

Toda vez que pego um curso eu sinto que falta algo pra mim. Muitas vezes me sinto perdido por não ter uma noção de um projeto em que eu poderia desenvolver com JavaScript pra de fato consolidar o meu conhecimento. 

O que vocês indicariam? Algum curso? Livro? Exemplos de projetos que eu posso desenvolver? 

Obg, Danilo Gila de Santana.

**Comment by nathpaiva** [comment]
Oi @danilo-santana certinho?

Primeira coisa, boa sorte com seus estudos! Tem bastante conteúdo free para poder aprender! Vou te passar alguns links que acho bacana...

Post no BrazilJs da Aline Bastos que ela passa cursos online
[Os melhores cursos online de JS](https://braziljs.org/blog/os-melhores-cursos-online-para-aprender-javascript/)

Tem um post bacana do @woliveiras de livros sobre JS
[Livros sobre JS](https://woliveiras.com.br/posts/Livros-sobre-JavaScript-do-iniciante-ao-avancado-e-ES6/)

Além disso tem o [training-center](https://github.com/training-center), que ajuda pessoal a aprender!! 

Com certeza tem bem mais coisa mas o pessoal com certeza vai te ajudar!

**Comment by kvnol** [comment]
@danilo-santana ainda não sou expert e estou muito, MUITO, longe de chegar no nível ninja que o @fdaciuk evangeliza (aliás [recomendo o curso](http://blog.da2k.com.br/curso-javascript-ninja/)), mas com as dicas que a galera deu nas issues: #270 e #410 dá pra ver a coisa mais por cima e saber como aprender da melhor forma.

Sucesso!

**Comment by carloschneider** [comment]
O Rodrigo Branas tem uma série bem bacana de Javascript no canal dele no Youtube, segue: https://www.youtube.com/user/rodrigobranas

**Comment by gabrieldarezzo** [comment]
Da uma olhada nesses videos do Zeno sobre o Chrome DevTools (JS/DOM):
https://www.youtube.com/watch?v=XUgfwYzv-WQ&list=PLiGzvgwA5Gmgnq5vPjJxW52hDiX3ndL53

Vale o click:
http://tableless.github.io/iniciantes/
https://pt-br.eventials.com/pinceladasdaweb/javascript-boas-praticas-e-otimizacoes/
http://jstherightway.org/pt-br/#js-code-style
http://jsbooks.revolunet.com/
https://github.com/ryanmcdermott/clean-code-javascript

**Comment by cristofersousa** [comment]
Olar! 

Cara é uma empreitada dificil para quem está começando no JavaScript, não se você já possui algum conhecimento sobre lógica (algoritmos) e alguma outra linguagem de programação, se já possui o caminho da carruagem pode ser menos turbulento. 

Caso está começando do momento zero, pode seguir [esse](https://medium.com/tableless/full-stack-developer-como-me-tornar-um-5c9d23765461), é uma coletânea de links/cursos  para lhe ajudar nessa empreitada JS.

[ ],s

**Comment by diessica** [comment]
Se sabe Inglês, siga o [How to Learn JavaScript Properly](http://javascriptissexy.com/how-to-learn-javascript-properly/) e depois [Learn Intermediate and Advanced JavaScript](http://javascriptissexy.com/learn-intermediate-and-advanced-javascript/).  Use [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide) para referências. *(Alguns artigos da MDN estão disponíveis em Português, caso prefira)*. 

Você pode fazer algumas adaptações como ler os artigos da MDN em vez do livro, por exemplo, embora os livros recomendados sejam 🔝 . Siga o guia sempre pensando no que funciona de verdade para você. O importante é ter a base dos fundamentos do JavaScript, e garanto que seguindo a programação do guia você vai ter um conhecimento sólido deles,  que vai deixar bem fácil para você, no futuro, se atualizar e aprender tecnologias relacionadas à linguagem.

(Gosto muito do método. No meio de tanta informação, sempre recomendo esses aí.)

**Comment by ericdouglas** [comment]
@danilo-santana para seu problema de ficar perdido em como aplicar o conhecimento, você pode estudar alguns [destes materiais](https://github.com/tuvttran/project-based-learning#javascript).

Deixando uma outra sugestão de materiais sobre JavaScript: [link](https://github.com/javascript-society/javascript-path)

**Dica**: Leia **apenas 1 livro**, mais generalista, tipo Eloquent JavaScript ou algum [destes](https://github.com/javascript-society/javascript-path#learn-javascript), e depois vá aplicar isso **criando projetos**.

Não encane de achar que tem que ler tuuudo isso ai não :P

Para ser produtivo, aprenda a usar um `.map`, `.forEach` da vida, algumas features do ES6+ e já está ótimo. Você vai passar muito tempo lidando com API de frameworks/libs, então não precisa saber a fundo JS puro para criar aplicações, você pode ir adquirindo conhecimento aos poucos.

**Comment by expalmer** [comment]
Minha dica é: ousa o @ericdouglas !

**Comment by danilo-santana** [comment]
OBrigado pelos comentários galera! Foi de enorme ajuda e esclarecedor para mim.

**Comment by rubenmarcus** [comment]
Artigos:

https://medium.com/javascript-scene/top-javascript-frameworks-topics-to-learn-in-2017-700a397b711

https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f?source=false---------0&gi=ef239719b83d

https://medium.com/reloading/javascript-start-up-performance-69200f43b201

https://medium.com/@_cmdv_/i-want-to-learn-javascript-in-2015-e96cd85ad225

https://www.quora.com/What-are-the-best-tutorials-for-learning-JavaScript

https://www.quora.com/What-is-the-best-way-to-learn-JavaScript

https://sivers.org/learn-js

https://frontendmasters.com/books/front-end-handbook/2017/learning/javascript.html


Desafios:

https://javascript30.com/

Livro Online:

http://speakingjs.com/es5/index.html


Cursos:

https://www.coursera.org/specializations/full-stack

http://jstherightway.org/

https://tutsplus.com/courses/search/javascript

http://www.tddjs.com/

https://github.com/dwyl/learn-tdd

https://github.com/getify/You-Dont-Know-JS

**Comment by rubenmarcus** [comment]
Esse do Coursera e bem voltado pro mercado. eu recomendo.

**Comment by cristofersousa** [comment]
Outro link para a coleção foi esse do [FreeCodeCamp](https://medium.freecodecamp.com/my-giant-javascript-basics-course-is-now-live-on-youtube-and-its-100-free-9020a21bbc27) que saiu esses dias.

**Comment by octavioviana** [comment]
Eu estou utilizando o "https://www.freecodecamp.com" estou gostando muito, sendo que li o artigo do @cristofersousa no que me ajudou muito. segue o link. "https://medium.com/tableless/full-stack-developer-como-me-tornar-um-5c9d23765461"

**Comment by mahenrique94** [comment]
@danilo-santana gosto bastante de ler e fazer alguns cursos, visitar blogs e artigos pela internet também ajuda.

## Livros:

### Casa do Código
- [ESC6](https://www.casadocodigo.com.br/products/livro-ecmascript6)
- [HTML5 e CSS](https://www.casadocodigo.com.br/products/livro-html-css)
- [Web Design Responsivo](https://www.casadocodigo.com.br/products/livro-web-design-responsivo)
- [Guia Front-End](https://www.casadocodigo.com.br/products/livro-guia-frontend)
- [CSS Eficiente](https://www.casadocodigo.com.br/products/livro-css-eficiente)

### Maujor
- [HTML5](http://livrosdomaujor.com.br/html5/download.php)
- [CSS3](http://livrosdomaujor.com.br/css3/index.php)
- [jQuery](http://livrosdomaujor.com.br/jquery/jq3/index.php)

## Cursos:
- [Alura](https://www.alura.com.br)
- [School of Net](https://www.schoolofnet.com)
- [Udemy](https://www.udemy.com)
- [Udacity](https://br.udacity.com/nanodegree/?gclid=CjwKEAjw9MrIBRCr2LPek5-h8U0SJAD3jfhtG6MbvZ4XwcQDYWm1UsMMmbChfW8xrq4RDZQoEtfeFRoCBUfw_wcB)

## Blogs:
- [Alura](http://blog.alura.com.br)
- [Tableless](https://tableless.com.br)
- [CSS Tricks](https://css-tricks.com)

Além de todo esse conteúdo, praticar é sem dúvida a melhor forma de aprender e evoluir.

Abraçooos.

**Comment by lucianobarauna** [comment]
Alguns links do @mahenrique94  eu vejo mais faltou um nos cursos ali que estou vendo atualmente que é a [TreinaWeb](https://www.treinaweb.com.br/)

**Comment by clucasalcantara** [comment]
@danilo-santana Te aconselho a se fudamentar em Vanilla JS, es6/7 features de fato. O que vejo hoje é muita gente que quer aprender javascript indo direto pra frameworks. Hoje vc pode fazer muita coisa no core sem precisar instalar trocentos modulos npm, ou um modulo pra cada coisa (apesar de facilitar e MUITO tudo o que vc precisa fazer). Eu sou adepto do entender como as coisas funcionam antes de usar caixas pretas que abstraem tudo ou muita coisa pra você.

Sendo assim te indico dois links de cabeceira:
https://github.com/airbnb/javascript
http://ptgmedia.pearsoncmg.com/images/9780132928472/samplepages/0132928477.pdf

E como guia de JS (curso pra investir), um execelente e que me ajudou muito a desenvolver o meu JS, by @willianjusten:
https://www.sympla.com.br/javascript-com-tdd-na-pratica__132385

Abraços e bons estudos cara!

**Comment by AmandaFonseca** [comment]
@danilo-santana Tamo Juntooo kk também estou começando a minha Jornada nesse mundo de front-end, estou estudando pela plataforma online da Alura  https://www.alura.com.br mas é uma plataforma paga.

Fiz esse cursinho básico no Youtube: https://www.youtube.com/watch?v=y3UCKd48FgI&index=1&list=PLV7VqBqvsd_0yDu6TuXeKKBlAurwATwyG o professor é ótimo é legal para começar a treinar.

**Comment by rubenmarcus** [comment]
Pessoal, ressucitando aqui, existem cursos que misturem lógica da programação e JS?

**Comment by didiraja** [comment]
@rubenmarcus são bens comuns, pelo JS estar no navegador é muito comum usarem JS de exemplo pra ensinar Lógica. Na Alura, tem dois módulos de Lógica que ensinam usando Javascript como exemplo.

**Comment by hig200diego** [comment]
Olá Rodrigo! Estou na mesma empreitada que você, amigo. Não se assuste porque você está aprendendo os conceitos básicos de Javascript. Uma vez que você assistiu à todas aulas de um determinado curso de Desenvolvimento Web e ainda há aquela sensação de que não aprendeu nada (como eu), a dica que te dou é pensar em algum projeto pessoal seu. Daí  você começa desenvolvendo aos poucos. Dúvidas?? Surgem aos montes! Não tenha vergonha de perguntar em fóruns. Há sempre alguém que irá te responder. Até mesmo programadores profissionais estacam em alguma parte do projeto e os melhores deles são generosos consigo mesmo e vão pedir ajuda. Esses são os melhores, creio. Minha resposta tá longa, né? Calma.  Eu uso sites como o FreeCodeCamp para revisar conceitos. Atualmente estou estudando pela Udemy. Acredite: todo dia tente fazer algum projeto simples. Vai dar muito certo e aos poucos você vai pegar o jeito da coisa. Um canal muito bom que posso te indicar (em inglês) é o WhatsDev. console.log('Boa sorte!');

**Comment by msouzarunner** [comment]
Boa tarde a Todos !!!

    Depois de garimpar por todos os comentários, comprei o livro da Casa do Código que o mahenrique94 indicou pois é o mais atualizado na minha opinião por tratar de ECMAScript6. O curso do Willian Justen na Udemy eu estou fazendo e é bem intenso pois precisa de um bom conhecimento de NPM e a parte de TDD é ótima.

Valeu as dicas !!!
