### ISSUE TITLE
Livros free da O'reilly

### ISSUE THREAD

**Issue by WandersonAlves** [frontendbr/forum#582]
A O'Reilly liberou alguns dos seus livros de forma gratuita http://www.oreilly.com/free/reports.html

Fica a dica ai!

**Comment by sergiohampel** [comment]
Boa, Popoto!!! \m/

**Comment by WandersonAlves** [comment]
Opa @sergiohampel quanto tempo kkkkkkkkkkk

**Comment by fernandomoraes** [comment]
Bom demais, baixei quase tudo lá (Y)
