### ISSUE TITLE
Quais os métodos para isolar o CSS de um componente?

### ISSUE THREAD

**Issue by heliomsolivas** [frontendbr/forum#584]
Pessoal, recentemente peguei um projeto onde pretendo transformar a maioria das coisas em componentes, a princípio fui separando como includes e chamando com Jquery. Eu queria inserir um framework e estou dando uma estudada no React com o create-react-app, porém na hora de isolar o CSS não consegui entender exatamente como fazer isso, li sobre utilizar CSS Modules mas fiquei perdido nas configurações. Quando eu me deparo com o Vue.js vejo que ele tem o Scoped CSS que acho que era exatamente o que eu queria. 

Não sei se deu para entender a minha dificuldade mas se alguém mais experiente puder me indicar o que pode ser mais fácil para um iniciante começar na criação de componentes ficarei grato :)

**Comment by rubenmarcus** [comment]
@matheusml  e o lance das variavéis por exemplo que você ve no instagram facebook, ele renomeia as classes para lzSZwsWEJwij_aa algo assim

**Comment by LFeh** [comment]
@matheusml Aproveitando a deixa.

E como funcionaria o reaproveitamento de mixins, variáveis ou mesmo a utilização de grid systems ou PostCSS nos arquivos?

Pensei em usar CSS Modules no ng2, mas não cheguei em uma conclusão sobre as dúvidas acima. Por enquanto estou compilando o CSS separadamente em uma stack especifica dele.

**Comment by matheusml** [comment]
@rubenmarcus 
Infelizmente não consegui entender a pergunta.

@LFeh 
Sobre o Grid, Bootstrap, e demais CSS de _libs_ externas, continua funcionando normalmente. Só porque você está usando CSS Modules não quer dizer que o CSS global não tenha mais seu lugar. Pelo contrário, ele ainda é necessário.

O que eu fiz nos projetos recentes, foi configurar o Webpack para que:
- Arquivos que terminam com .css, não usem o CSS Modules
- Arquivos que terminam com .scss, usem o CSS Modules

Ou seja, eu posso ter importado o Bootstrap na aplicação, e usar o grid normalmente, junto com o CSS Modules sem problemas:

```javascript
render() {
  return (
   <div className={styles.container}>
     <div className="row">
      ....
   );
}
```

E sobre as variáveis, mixins e demais formas de se reaproveitar o CSS, eu recomendo usar moderamente. Com CSS Modules, o reaproveitamento do CSS em si não faz mais tanto sentido. A graça é justamente reaproveitar **componentes**.

Imagine que você tenha um botão, com um estilo customizado, que você use por toda a aplicação.
Então ao invés de você criar um CSS global:

```css
.button {
  color: #fff;
  padding: 10px;
}
```

Para ser reaproveitado dessa forma:

```html
<button className="button">Botão</button>
```

Você vai irá criar um componente, já com seus estilos customizados dentro:

```javascript
const Button = () => <button className={styles.button>Botão</button>
```

E usar na aplicação dessa forma:

```javascript
render() {
  return <Button />
}
```

Mas se mesmo assim, existir um cenário que você precise reaproveitar o CSS, recomendo ler um pouco na [documentação oficial](https://github.com/css-modules/css-modules) as seções **Composition** e **Dependencies**.

**Comment by LFeh** [comment]
@matheusml esse conceito de libs externas eu até tinha entendido, e nem é o caso exatamente, porque não faço uso de Boostrap e afins.

A treta maior é com relação a consistência do projeto mesmo:

- Variáveis de espaçamento
- Variáveis de cores
- Variáveis de tipografia
- Variáveis de Media Queries

Além disso, tenho a questão sobre usar coisas em PostCSS como Rucksack, LostGrid, nanoCSS e etc, essas você configura no Webpack?

**Comment by fdaciuk** [comment]
Concordo com o @matheusml! Assim como ele comentou: você deve deixar de pensar em componentizar no CSS, e começar a pensar em componentizar elementos! Agora é o JS que você reaproveita, não mais as classes CSS =)

Então, nesse caso que você precisa aproveitar espaçamentos, por exemplo, você pode criar alguns componentes estruturais que recebam as classes e estilos para o que precisa, e usar esses componentes onde precisar dos espaçamentos específicos.. exemplo:

```jsx
import style from './paragraph-style.css'

const P = ({ children }) => (
  <p className={style.paragraph}>
    {children}
  </p>
)
```

O estilo para esse parágrafo seria algo do tipo (`paragraph-style.css`):

```css
.paragraph {
  line-height: 1.5;
}
```

E agora você tem um parágrafo com `line-height` definido com `1.5` por default, que você pode usar no seu projeto, reaproveitando o componente:

```jsx
import P from 'components/paragraph'

const App = () => (
  <P>Meu texto com 1.5 de line-height</P>
)
```

Assim você começa a pensar em componentizar elementos, com estilos específicos, para reutilizá-los, ao invés de criar classes e usá-las por toda a aplicação.

Outro ponto forte dos componentes é a composição. Á partir desse `<P>` você pode criar outros componentes que precisem de um container com essa estrutura de ter um parágrafo como pai, e line-height de 1.5.

Foi só um exemplo simples, mas acho que deu pra entender xD

**Comment by LFeh** [comment]
Deu sim, é um conceito bem diferente. Mas acho que é o caminho para garantir solidez em grandes aplicações.

**Comment by heliomsolivas** [comment]
@matheusml, @fdaciuk  valeu pela explicação! Agora tudo faz um pouco mais de sentido haha, só acrescentando uma pergunta aqui, em relação a sintaxe, o [Single File Components](https://vuejs.org/v2/guide/single-file-components.html) do Vue em comparação com o React eles fazem a mesma coisa só que o React me parece mais complicado ou é a mesma coisa?

**Comment by fdaciuk** [comment]
@heliomsolivas a diferença básica é que, com React, você trabalha só com JS, nem escreve HTML. O JSX, que parece HTML, na verdade é compilado para uma função, e o retorno é um objeto. 

No Vue você cria o template com HTML, e a parte de dados em um `<script>` separado, e pode ter uma tag `<style>` pra escrever o CSS.

No exemplo que o @matheusml deu do _styled components_, é o mais próximo que você chegar pra manter as duas sintaxes parecidas =)

**Comment by rubenmarcus** [comment]
@matheusml  opa desculpa, formulei mal a pergunta, vi no spec do CSS modules, o nome é style mapping, ele gera classes tipo isso :

> 
> <div class="table__table___32osj">
>     <div class="table__row___2w27N">
>         <div class="table__cell___1oVw5">A0</div>
>         <div class="table__cell___1oVw5">B0</div>
>     </div>
> </div>



mas local é outra classe certo?? qual a vantagem disso? o styled components funciona da mesma forma?

**Comment by matheusml** [comment]
@rubenmarcus 
No final das contas, o CSS continua sendo global, e não tem como não o ser. É a única coisa que os _browsers_ atuais entendem.

A vantagem do CSS Modules, e do styled-components, é ter a segurança de escrever o CSS local. E só na etapa final, o build gera pra você de forma segura, um CSS global não conflitante.

**Comment by bernardodiasc** [comment]
@LFeh voce pode usar PostCSS com CSS Modules tranquilamente. O CSS Modules não manipula o "conteúdo" do CSS, apenas renomeia as classes e retorna um objeto no import do modulo. No caso a cada import de um modulo CSS o PostCSS vai rodar, então, se voce usa por exemplo CSS Vars, vai estar tudo disponíveis em cada arquivo css que voce importar nos componentes. É uma questão de configurar o loader no Webpack apropriadamente.

**Comment by victorsilent** [comment]
Não sei se da treta reviver tópico, mas tenho uma dúvida sobre isso e não queria criar mais um :v

**Comment by LFeh** [comment]
@victorsilent As issues nunca fecham, pode reviver sempre que quiser, 😉

**Comment by vczb** [comment]
Eu quero aprender mais sobre o styled jsx, peguei um exemplo de um [blog](https://github.com/wutali/nextjs-netlify-blog-template), mas olhando parece bem pouco prático na verdade... o que vocês acham ? queria saber sobre boas práticas com [styled jsx](https://github.com/vercel/styled-jsx)

```
import Head from "next/head";
import Navigation from "./Navigation";

type Props = {
  children: React.ReactNode;
};
export default function Layout({ children }: Props) {
  return (
    <div className="root">
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="apple-touch-icon" href="/icon.png" />
        <meta name="theme-color" content="#fff" />
      </Head>
      <nav>
        <Navigation />
      </nav>
      <main>{children}</main>
      <style jsx>
        {`
          .root {
            display: block;
            padding: 4rem 0;
            box-sizing: border-box;
            height: 100%;
          }
          main {
            display: flex;
            min-height: 100%;
          }
          @media (min-width: 769px) {
            .root {
              display: flex;
              flex: 1 0 auto;
            }
            main {
              flex: 1 0 auto;
            }
          }
        `}
      </style>
    </div>
  );
}
```
