### ISSUE TITLE
Conteúdo para iniciantes

### ISSUE THREAD

**Issue by felipeorlando** [frontendbr/forum#591]
Galera, criei um repo para iniciantes e preciso de ajuda para como proceder!

**[Be a Front-End Dev ](https://github.com/felipeorlando/be-a-frontend)** ❤️ 

A minha dúvida é como separar os conteúdos... 🤔

**Comment by felipeorlando** [comment]
**[Be a Front-End Dev ](https://github.com/felipeorlando/be-a-frontend)** ❤️ 

A minha dúvida é como separar os conteúdos... 🤔

**Comment by woliveiras** [comment]
Já ganhou uma estrela pela vontade de ajudar as pessoas a entrarem na nossa área @felipeorlando! 😬 

Uma opinião pessoal: de awesome lists e trilhas de estudos para front end a nossa internet já está cheia... O que está faltando é um guia um pouco mais profundo nos assuntos, que não só diga "você precisa saber HTML, CSS e JS".

No Training Center estamos bolando uma ideia de criar um roadmap (parecido com aquele que ensina os diferentes caminhos do desenvolvimento web), só que queremos algo mais profundo.

Ex.:

*HTML, o que as pessoas precisam aprender?* 

- Tags, Semântica (não HTML, semântica no sentido amplo da palavra mesmo), Acessibilidade, etc.

Para cada um desses assuntos nós vamos colocar mais conteúdo ainda e ir sempre descendo até não ter mais o que falar. 😄 

Se você fizer isso no seu projeto, nem vamos seguir com o nosso para a área de front end, vamos só linkar o seu! HIAHIAH

Como está planejando?

**Comment by woliveiras** [comment]
Ex. no estilo awesome list: https://github.com/woliveiras/front-end-career

Ex's de post: https://www.google.com.br/#q=como+me+tornar+front+end

**Comment by felipeorlando** [comment]
É disso que eu tô falando. Eu queria deixar claro o que de fato é necessário aprender em cada tecnologia...

**Comment by gabrieldarezzo** [comment]
Se quiser incorporar algo relacionado a JS pode contar comigo :+1: 

Fiz um repo recentemente bem focado está iniciando no JavaScript:
https://github.com/gabrieldarezzo/helpjs-ravi

Pretendo refazer nesse estilo ainda esse ano:

1. Introduz um assunto
2. Passa uma listinha de exercícios para fixar... 

Afinal é fazendo que se aprende neh?!


(Ps se você tem raiva de quem usa ```var```, favor nem abrir o link acima)

**Comment by felipeorlando** [comment]
@gabrieldarezzo maneirissimo isso ae, ein! curti a ideia 💯

**Comment by gabrieldarezzo** [comment]
O pessoal do @tableless tem um repo bem bacana tmb:

Repo:
https://github.com/tableless/iniciantes

Demo:
http://tableless.github.io/iniciantes/

----

> No Training Center estamos bolando uma ideia de criar um roadmap   
 
@woliveiras Interessante essa proposta do RoadMap (tanto pra estudo quando para share.)
Tem mais informações?

**Comment by WandersonAlves** [comment]
Vale por experiência pessoal?

Me lembro que cai na área de front-end por puro acaso do destino. Aprendi um framework e sóoooo depois fui aprender JS a fundo, e isso funcionou pra mim.

Ainda tenho guardado alguns resources que usei no aprendizado e posso tentar ajudar!

**Comment by marcelgsantos** [comment]
Caros @felipeorlando e @woliveiras, tudo bem?

Acho **muito válida** a ideia de escrever material para quem está começando na área. Principalmente por que tende ser o _momento mais difícil_ para os desenvolvedores.

Quando criei o meu blog, [Pensando na Web](http://pensandonaweb.com.br/), a minha ideia era fazer uma série de artigos chamado **Começando na Web** para iniciantes em desenvolvimento web. Comecei, escrevi dois artigos e parei. :cry: 

De qualquer forma, ficam os **dois artigos** que escrevi para iniciantes:

- [Como funciona a Internet e a World Wide Web](http://pensandonaweb.com.br/como-funciona-a-internet-e-a-world-wide-web/)
- [Aprendendo HTML, a linguagem da web](http://pensandonaweb.com.br/aprendendo-html-a-linguagem-da-web/)

O primeiro artigo eu republiquei no [Tableless](tableless.com.br) em [Como funciona a Internet e a World Wide Web](http://tableless.com.br/como-funciona-internet-e-world-wide-web/). O **feedback** foi bastante positivo, mas os comentários sumiram de lá. :smiley: 

Pensei em voltar a **escrever novamente**, mas a vida anda um tanto quando corrida. Tenho dois artigos incompletos sobre HTML e CSS no forno. Talvez eu me motive novamente para escrever. :smiley: 

Parabéns pela iniciativa!

**Comment by woliveiras** [comment]
Sucesso demais então @felipeorlando! 🤘 🤘 🤘

**Comment by woliveiras** [comment]
Se for migrar seus posts para o Medium, o Training Center está aberto para recebe-los ein @marcelgsantos! 

Eu já tinha lido esses posts e curti muito!

Na nossa publication já estamos com alguns posts bem legais: https://medium.com/trainingcenter

**Comment by mathvbarone** [comment]
fala @felipeorlando você pretende tocar o projeto? Gostaria de ajudar.
