### ISSUE TITLE
[ Ferramenta ] Integração do forum com o Telegram

### ISSUE THREAD

**Issue by suissa** [frontendbr/forum#595]
Galera eu inicie um forum para os alunos da Webschool e estamos usando o mesmo esquema daqui, utilizando as ISSUES, porém criei um grupo no Telegram [https://t.me/forumwebschool](https://t.me/forumwebschool) onde integrei com um BOT do Github que fica escutando nosso repositório [https://github.com/Webschool-io/forum](https://github.com/Webschool-io/forum) e toda movimentação do repo ele nos avisa e podemos responder uma ISSUE diretamente como uma resposta à uma mensagem no chat do Telegram.

![screen shot 2017-06-12 at 8 52 29 pm](https://user-images.githubusercontent.com/75607/27060296-29443842-4fb2-11e7-810d-989fe3e87bcf.png)

Caso alguém queira testar isso criei um grupo de teste https://t.me/joinchat/AAAAAEQgwS5nIXaoS_6R9A porém algum dos admins precisa entrar e configurar o bot, alguém se habilita??

cc @diogomoretti @fdaciuk @eduardojmatos @LFeh @Mendrone @mtmr0x

**Comment by fdaciuk** [comment]
Da hora hein @suissa! :D
Pra galera que usa bastante Telegram, acho que faz bastante sentido =)

**Comment by LFeh** [comment]
Não uso o Telegram, alguém pode testar? @frontendbr/admins

**Comment by eduardojmatos** [comment]
@suissa bacana mano. Depois a gente pode mover essa issue pro https://github.com/frontendbr/sugestoes/ ? Só pra ficar centralizada lá as novas ideias.

Eu uso, vou testar aqui então!

**Comment by nandomoreirame** [comment]
@woliveiras da pra usar no Telegram do @training-center :)

**Comment by LFeh** [comment]
This issue was moved to frontendbr/sugestoes#19

**Comment by woliveiras** [comment]
Vou ver esse esquema pra gente @nandomoreirame

**Comment by m-a-r-c-e-l-o** [comment]
Celofabiano curtiu seu email
Spark by Readdle
