### ISSUE TITLE
Tags do Git não aparecem

### ISSUE THREAD

**Issue by deppbrazil** [frontendbr/forum#607]
Estou com um duvida com git, quando eu faço um projeto em uma estação de trabalho e uso tag anotada e subo esse repositorio no gitHub quando eu clono ele em outra maquina via ssh os commits todos aparecem mas as tags não.

ou seja, quando eu dou o comando no terminal 
`git tag `
ele retorna nada =s

e se eu dou 
`git log`
ele retorna todos os commits feito no projeto

Porque isso acontece?

**Comment by kvnol** [comment]
Tem que fazer o push das tags:

`git push origin <tag_name>`

**Comment by didiraja** [comment]
ingratidão isso ein, devia ir tudo junto haha

**Comment by dougaraujos** [comment]
Você também pode usar o `git push --tags` para enviar todas as tags locais aos remotos.

**Comment by deppbrazil** [comment]
@didiraja poxa verdade, eu quebrando a cabeça aqui... pior que procurei em tudo e não achei nada falando sobre... 
@kvnol deu certo mas usando desta forma `git push origin nomeDaTag`
@dougaraujos deu certo o comando `git puhs --tags` valeww =) 

ambos comandos tenho que puxar essas tags em outra máquina com o comando `git pull` apenas.

Valew galera... =)
