### ISSUE TITLE
Travar um sorteio em Java (dúvida de leigo)

### ISSUE THREAD

**Issue by ghost** [frontendbr/forum#610]
Participo de um sorteio de um site que gera um cupom de desconto toda vez que se roda a roleta dele (tem que ser cadastrado pra girar) https://otakumode.com/shop/special/otaku-prize-spin
Notei que a aplicação dessa roleta foi feita em Java e gostaria de saber se há alguma forma de travar o sorteio num determinado número pois se trata de descontos em dólar pra se gastar neste site.
Existe alguma forma de burlar esse sorteio e fazer com que a roleta gire e pare no valor específico?

**Comment by muniz95** [comment]
Sugiro perguntar em algum fórum dedicado a Java, esse daqui é mais para questões sobre front-end.
Sugiro também elaborar melhor sua questão, só o título não diz praticamente nada.

**Comment by kvnol** [comment]
![image](https://user-images.githubusercontent.com/3299130/27749164-cbc0b0ec-5da8-11e7-8c5e-c1be30723b34.png)

**Comment by kivervinicius** [comment]
cara, pelo que entendi você quer se beneficiar através de uma possível falha? haha, meche  com isso não tenho certeza que ninguém aqui vai te ajudar a fazer coisas erradas. De corrupção já basta em Brasilia.

**Comment by Rxon7** [comment]
eu ajudo se noix dividir a bolada. hehe

**Comment by munizart** [comment]
Acredito que você esteja confundindo Java e Javascript...

Pra poder "burlar" a roleta terias que entender melhor os detalhes de implementação.
Talvez seja útil descobrires, por exemplo, como a aplicação diferencia um usuário que já rodou a roleta de um que ainda não rodou...

De toda forma, se encontrares algo que te ajude a burlar o sistema pode ser mais recompensador [avisar o site](https://en.wikipedia.org/wiki/White_hat_(computer_security)) do que se aproveitar da brecha.
Boa sorte
