### ISSUE TITLE
GIMP ou PHOTOSHOP

### ISSUE THREAD

**Issue by romulo2735** [frontendbr/forum#611]
Queria a opnião de vocês sobre qual deles usar. Alguns me dizem que o PHOTOSHOP é melhor e outros o GIMP. Sou iniciante em edição de imagens, qual desses é o mais "recomendado"?

**Comment by kvnol** [comment]
A galera mais hardcore do open-source prefere o Gimp pelo motivo de ser open-source com argumentos de que o Gimp já faz o que o Photoshop faz e tal. Eu já tentei utilizar o Gimp diversas vezes mas confesso que, após estar acostumado em usar o Photoshop, é complicado com todas as diferenças de funcionalidades, nomes e interface. É como aprender tudo do zero.

Eu vou de Photoshop, mas vale o teste. Não há o mais recomendado recomendado, pois é aquele ditado, né:

> Software não faz profissional.

**Comment by Rxon7** [comment]
Eu penso dessa forma? se nao der para fazer no gimp nem vale a pena ser feito. hehe

**Comment by didiraja** [comment]
Pra mim, quem fala que o Gimp substitui o Photoshop, ou não sabe usar o Photosohop ou nunca precisou substituir de verdade um pelo outro.

Colocamos Xubuntu nos notebooks de quem não é criação la na agência e a simples tarefa de colocar a imagem em um template se tornava uma tarefa hercúlea. A ferramenta de redimensionamento dele é contra-produtiva, nem o skin de photoshop ajudou.

Pra piorar, o Gimp não abre os PSD de maneira correta. Transforma texto em pixel, não compreende máscara de camada do PS e tem vezes que ele troca as cores (?) mesmo se mantendo no padrão RGB.

Tentamos fazer a integração PS + GIMP mas é impraticável. Tanto de um lado como o outro. Sem contar que GIMP não tem metade dos filtros e funções do Photoshop.

Xubuntu é um SO muito bacana e por mim eu migrava em definitivo, mas o GIMP é terrível. Quem sabe, no dia que a Adobe fizer uma versão nativa pra Linux.

**Comment by Rxon7** [comment]
@didiraja tenho que discordar de vc meu truta, conheço uma pessoa que tem grafica e trabalha com GIMP e Inkscape, claro se a parada for feita no Photocú ele nao vai abrir direito no GIMP, agora começa a ordem inversa pra vc vê, engraçado que os caras pregam o ~Open Source~ nos quatros cantos, só falta colocar a foto do Stallman nas palestra e na hora de viver fazem oq? usam tudo fechado. kkkkk

**Comment by Rxon7** [comment]
e aqui encerro minha participacao. vlw flw

[Imgur](http://i.imgur.com/GT28uCF.jpg)

**Comment by Rxon7** [comment]
[img]http://i.imgur.com/GT28uCF.jpg[/img]

**Comment by fabiomirandaa** [comment]
"Photocú".. Isso parece meio infantil. O ideal é que o software menos popular, se integre e consiga renderizar corretamente o formato mais popular, que no caso é o PSD. Não adianta, o GIMP é muito ruim, a anos só recebe bugfix e não vai apresentar nada de melhoria, porque não tem nada pressionando o software a melhorar.

**Comment by Rxon7** [comment]
vou sair dessa discussao que nao vai levar a nada, fuiii

![teste](http://i.imgur.com/GT28uCF.jpg)

**Comment by Rxon7** [comment]
@fabio claro né o bagulho já ta monopolizado, seria igual eu fazer um texto no Office esperar que fique identico no Libreoffice, mas desculpa pelo photocu, vlw flw

**Comment by didiraja** [comment]
@Rxon7 

> claro se a parada for feita no Photocú ele nao vai abrir direito no GIMP, agora começa a ordem inversa pra vc vê

Poxa, mas se o caminho PS > GIMP não funciona, mas o GIMP > PS sim, o problema é do software que tá abrindo o formato proprietário de outro e não o faz de maneira correta. Mais um ponto pro Photoshop. 😉

>  seria igual eu fazer um texto no Office esperar que fique identico no Libreoffice

E isso só não é possível, por culpa do próprio Libre e OpenOffice. Após experiências ruins com esses, descobrimos o [WPS Station](https://www.wps.com/), que herda os atalhos e funções mais comuns, além da compatibilidade. Resultado: refutou qualquer reclamação, de um determinado setor, já que a ferramenta permitia fazer tudo como antes.

Não faz o menor sentido migrar para o Open-Source se isso dificulta nossa vida ou inviabiliza nosso trabalho.

**Comment by kivervinicius** [comment]
Uma boa alternativa para se aproximar do Gimp de uma forma mais fácil é utilizar o mod GimpShop https://www.gimpshop.com/, não arruma os problemas mencionados acima pelos colegas, mas é uma alternativa para descobrir as coisas que o Gimp é capaz de fazer ou não, sinceramente prefiro o photoshop, e uso em uma VM só para isso, é complicado mas como hoje sou bem mais produtivo no PS é dificil de migrar completamente ao Gimp, mas não é impossível.

**Comment by didiraja** [comment]
@kivervinicius opa, valeu a sugestão, vou dar uma analisada nele. Vamos ver se ajuda por aqui.

**Comment by kivervinicius** [comment]
@didiraja Fico feliz em ajudar, espero que de certo.

**Comment by romulosousa27** [comment]
Valeu pessoal, ajudou muito!
