### ISSUE TITLE
Flex container acompanhar o tamanho dos filhos

### ISSUE THREAD

**Issue by wilcorrea** [frontendbr/forum#612]
Oi pessoal, estou com um problema que não estou conseguindo resolver.

Tenho esse fiddle que representa o problema https://jsfiddle.net/wilcorrea/tzcrL2xk/
Ao rolar a barra é possível ver que o background do "container" não acompanha o tamanho dos filhos
![image](https://user-images.githubusercontent.com/803733/27772123-5250920a-5f32-11e7-969b-f22645166aff.png)

O resultado esperado seria algo assim
![image](https://user-images.githubusercontent.com/803733/27772129-64ab2e10-5f32-11e7-9c3c-cf9ee6762347.png)

Na prática esse protótipo é o que acontece aqui nessa aplicação onde a visão inicial é
![image](https://user-images.githubusercontent.com/803733/27772144-956e3808-5f32-11e7-87d5-124d9e1aa7e7.png)

e quando rola o scroll
![image](https://user-images.githubusercontent.com/803733/27772135-84c96982-5f32-11e7-9c52-bda874451b9f.png)

Aparentemente é preciso que o "container flex" acompanhe o tamanho dos filhos enquanto crescem.

Grato, desde já, por qualquer ajuda : )

**Comment by kvnol** [comment]
A resolução que encontrei é colocar o `overflow-x auto` direto no container, ao invés de dois containers:

https://codepen.io/kvnol/pen/VWXEme

**Comment by wilcorrea** [comment]
Obrigado @kvnol !

O problema é que uma lista de itens e para eu renderizar com aquela estrutura no Vue vai ser bem mais complexo (usando o v-for)

Atualizei o fiddle com dados para ficar mais evidente o contexto https://jsfiddle.net/wilcorrea/tzcrL2xk/

**Comment by kvnol** [comment]
@wilcorrea pode crer, com flexbox não consegui resolver esse problema. Estou invocando o @afonsopacifer.

**Comment by wilcorrea** [comment]
@kvnol obrigado pelo apoio ae. Ressalto também que não faço questão de usa flexbox. Se tiver qualquer estrutura que possa ter o  mesmo efeito me deixará feliz : )

**Comment by afonsopacifer** [comment]
@wilcorrea nesse caso.. como vc tem uma tabela.. bastaria usar um <table> que ele vai ter o comportamento que você espera.. alias, as tables foram deitas para isso..

um exemplo:
https://simoneas02.github.io/contracts-list/

😃

**Comment by kvnol** [comment]
@afonsopacifer puts, pode crer! hahahaha

**Comment by wilcorrea** [comment]
@afonsopacifer muito obrigado pela resposta : )

Eu estava tentando evitar a table para poder fazer a visão do grid (`table`) quando a tela for muito pequena colocando as colunas como linhas de uma célula central. Vou tentar mudar o display das `td`s` então, provavelmente vai ser mas simples do que pelejar com isso dae que não está andando desde ontem : )

Obrigado a todos os envolvidos pelo apoio e ajuda

**Comment by wilcorrea** [comment]
Oi pessoal, só para dar um feedback sobre as possíveis soluções

Usando 'flexbox', detalhe para o display `inline-flex` e a `witdh` baseada em `vw` (dica do @SkyaTura)
https://jsfiddle.net/wilcorrea/tzcrL2xk/58/

Usando `<table>`
https://jsfiddle.net/wilcorrea/tzcrL2xk/55/

**Comment by fdaciuk** [comment]
Deixa aberta a issue, que se outras pessoas tiverem um problema parecido fica mais fácil de encontrar =)
