### ISSUE TITLE
Problemas para o projeto rodar no servidor

### ISSUE THREAD

**Issue by marcospaulosss** [frontendbr/forum#614]
Boa tarde galera.
Estou tendo um problema na hospedagem do meu projeto em angular 2 e preciso da ajuda de vcs.

Tenho um projeto desenvolvido em php, html e jquery ja rodando.
criei um projeto em angular 2 que funciona perfeitamente no local host, porem quando tento colocar esse projeto dentro de uma pasta no servidor ele apresenta o seguinte erro.
GET http://sis.bluefitacademia.com.br/inline.bundle.js 
sis.bluefitacademia.com.br/:16 GET http://sis.bluefitacademia.com.br/scripts.bundle.js 
sis.bluefitacademia.com.br/:16 GET http://sis.bluefitacademia.com.br/vendor.bundle.js 
sis.bluefitacademia.com.br/:16 GET http://sis.bluefitacademia.com.br/main.bundle.js 
sis.bluefitacademia.com.br/:16 GET http://sis.bluefitacademia.com.br/styles.bundle.js 
sis.bluefitacademia.com.br/:16 GET http://sis.bluefitacademia.com.br/inline.bundle.js 
sis.bluefitacademia.com.br/:16 GET http://sis.bluefitacademia.com.br/scripts.bundle.js 
sis.bluefitacademia.com.br/:16 GET http://sis.bluefitacademia.com.br/styles.bundle.js 
sis.bluefitacademia.com.br/:16 GET http://sis.bluefitacademia.com.br/vendor.bundle.js 
sis.bluefitacademia.com.br/:16 GET http://sis.bluefitacademia.com.br/main.bundle.js 404 (Not Found)

o projeto principal esta na raiz e estou colocando o projeto do angular 2 dentro de uma pasta

**Comment by LFeh** [comment]
Alterei o titulo para ter maior clareza da dúvida

**Comment by kivervinicius** [comment]
Como você realizou o deploy da sua aplicação? Verifique as permissões ao arquivo main.bundle.js

**Comment by mikejavier** [comment]
Possivelmente sua aplicação é uma SPA. Para poder hospedar vai ter que fazer algumas pequenas configurações. Estas configurações variam de acordo as configs do server (apache, nginx, etc).

Tenta procurar no google por "Angular 2 Deployment" ou coisas relativas. Abaixo to deixando alguns links que podem te dar uma luz.

[https://medium.com/@ryanchenkie_40935/angular-cli-deployment-host-your-angular-2-app-on-heroku-3f266f13f352](https://medium.com/@ryanchenkie_40935/angular-cli-deployment-host-your-angular-2-app-on-heroku-3f266f13f352)

[https://github.com/angular/angular/issues/11884](https://github.com/angular/angular/issues/11884)

**Comment by fernandomoraes** [comment]
Pode ser que, dependendo da configuração do server, você precise colocar esses arquivos dentro de uma pasta para ter visibilidade. Tipo jogar tudo, exceto o index.html.

**Comment by marcospaulosss** [comment]
não há uma configuração no angular 2 onde possamos especificar a pagina de origem, ele somente funciona na pasta raiz da hospedagem?

**Comment by marcospaulosss** [comment]
Problema resolvido galera.
muito obrigado pela ajuda de todos.
a solução encontrada foi a de adicionar a tag base com o direcionamento na pagina do index.html

<base href="/test/myapp/">
