### ISSUE TITLE
Como fazer testes usando Polymer-TS?

### ISSUE THREAD

**Issue by jamilelima** [frontendbr/forum#620]
Olá, pessoal. 
Como posso testar meus elementos Polymer usuando o Polymer-TS? O Polymer-CLI nativo me retorna um erro por causa da separação do código HTML e o código JS. A suíte de teste espera por um código mais ou menos assim:

```
    MyElement = Polymer({

      is: 'my-element',

      created: function() {
        this.textContent = 'My element!';
      }

    });

```
E o transpilador não retorna no mesmo formato do nativo.
Alguma ideia? :smile:

**Comment by yanmagale** [comment]
@JamileLima vou invocar o @afonsopacifer , talvez ele possa dar um report melhor.

Não costumo usar o TS quando crio os meus components ... acredito que para poder rodar este tipo de teste dentro do `polymer-cli` eles vão precisar implementar algo para dar este tipo de suporte. Dei uma olhada no repositório oficial para ver se ja existia alguma issue sobre isso mas não encontrei nada.

Também dei uma olhada na doc do [PolymerTS](https://github.com/nippur72/PolymerTS/), não consegui identificar se eles oferecem algum tipo de API para fazer estes testes nos componentes. Pela [documentação](https://www.polymer-project.org/2.0/docs/tools/tests) não encontrei nada referente ao TS.

**Comment by JamileLima** [comment]
Obrigada pela ajuda, @yanmagale. Já tinha olhado na documentação e procurado alguma issue a respeito, já até conversei com alguns outros desenvolvedores, mas ainda nada. Espero que o @afonsopacifer me dê uma luz! 😄
