### ISSUE TITLE
inicialização do terminal no MacOS - Caminhos de projetos/Alias - Git 

### ISSUE THREAD

**Issue by deppbrazil** [frontendbr/forum#623]
Não consigo mudar o caminho de inicialização do git no Mac. No Windows sempre ia  `propriedades > iniciar em > e pronto ` por default o terminal iniciava no caminho que você colocava ali, já no Mac não acho essa opção, e como comecei a subir meu código PHP no GitHub mudei da pasta `X` que tava no Mac para uma pasta `Y` dentro do htdocs do MAMP. e dai tenho que ficar usando sempre o `cd ..` ou `cd NomeDaPasta` para ir pro projeto, então quando abrir o teminal do Hyper já quero deixar para iniciar dentro do htdocs do MAMP. =s

Tem como?

**Comment by kazzkiq** [comment]
Olha, não sei como iniciar o terminal já uma pasta específica, mas você pode criar um *alias* que já abre essa pasta específica ao ser executado.

Exemplo:

```bash
# Ao invés de ter que fazer isso toda vez:
$ cd ~/caminho/maluco/do/meu/htdocs

# Você faria apenas isso
$ myapps    # <-- (mesma coisa que executar o comando acima)
```

Pra criar um alias no macOS é só seguir estes passos:
1. No terminal, digite: `cd ~/ && open .`; *(sim, esse ponto no final faz parte do comando)*
2. Com a janela do Finder aberta, procure pelo arquivo `.bash_profile` (caso ele não exista, crie-o);
3. Adicione o *alias* no arquivo recém criado (ou aberto) usando a seguinte sintaxe:
```php
alias myapps='cd /caminho/do/seu/htdocs'
# myapps é só um exemplo, você pode usar qualquer nome para o seu alias
```
4. Salve o arquivo, mate o terminal e abra-o de novo, e teste o *alias*.

Agora, toda vez que você abrir qualquer terminal no seu mac e digital `myapps` (ou qualquer outro nome que você tenha dado para o alias), ele já vai cair direto na sua pasta.

----

A parte legal disso é que você pode criar vários *alias*, "automatizando" algumas tasks e criando atalhos específicos para cada projeto. Você pode definir um alias que já abra o seu editor de código em uma pasta específica, inicie o banco de dados, e dê start no servidor, por exemplo.*

*Isso é bem útil quando você tá trabalhando em vários projetos ao mesmo tempo e precisa ficar chaveando entre eles durante o dia mas não quer ficar trocando o ambiente de desenvolvimento na mão toda vez.*

**Comment by thiagommedeiros** [comment]
@deppbrazil Faz exatamente o que o @kazzkiq disse só que sem o `alias`, ou seja, coloque no seu `.bash_profile` apenas o comando `cd /caminho/desejado/`. Pronto, toda vez que vc abrir o terminal ele vai iniciar na pasta. =)

**Comment by kvnol** [comment]
@deppbrazil pegando o gancho do que os brothers (@kazzkiq e o @thiagommedeiros) disseram, é massa tu versionar e salvar esse arquivo no GitHub. Eu me inspirei no repositório do @woliveiras e criei meu Dotfiles. Recomendo muito criar seu [.bashrc](https://github.com/kvnol/.dotfiles/blob/master/.bashrc). :grin:

**Comment by deppbrazil** [comment]
@kazzkiq sensacional, não conhecia esse  `alias` show deu certinho valew =) 

@thiagommedeiros boa tb deu certo fazendo o caminho sem o `alias` =) 

@kvnol Show man, valew pela dica, vou criar um repo desses arquivos =) 

Galera só reforçando que por default o arquivo

> .bash_profile 

Não esta na pasta inicial do Finder, é necessário criar, porém depois para conseguir visualizar no Mac é necessário habilitar visualizações de pastas ocultas com o comando:

`defaults write com.apple.Finder AppleShowAllFiles TRUE`
Assim o arq. **.bash_profile** fica visível =)  

Mas não esquecer de voltar ao normal para não correr o risco de deletar algum arq. de config. então voltar ao normal com: 
`defaults write com.apple.Finder AppleShowAllFiles FALSE`

Valew pela ajuda de vcs =)

**Comment by didiraja** [comment]
Muito boa a dica dos _alias_. O que eu fiz pra solucionar o problema apresentado, foi configurar o Terminal pra assim que abrir executar um comando específico. E esse comando era o que levava pra minha pasta de projeto.

**Comment by barraponto** [comment]
@deppbrazil vc pode mudar a pergunta pra "... inicialização do terminal" ou "... inicialização do shell"? só pra ficar mais fácil de procurar depois. `git` é um programa que vc roda no terminal, não o terminal todo.

**Comment by deppbrazil** [comment]
@barraponto Boa man... alterado... =)
