### ISSUE TITLE
Aplicação .NET para enviar arquivos para uma conta no Office365

### ISSUE THREAD

**Issue by BellonGN** [frontendbr/forum#629]
Boa noite pessoal,

Anteriormente eu estive desenvolvendo uma aplicação .NET em c# para criar uma planilha no google spreadsheet utilizando o Google API e para a autenticação do usuário usei OAuth. Agora estou tentando implementar as funcionalidades da minha aplicação para enviar arquivos para uma conta de um usuário no Office 365 (no caso, para o OneDrive e etc). Eu cheguei a testar alguns exemplos, mas nada chegou perto do resultado que eu quero. Com as minhas  #pesquisas li que tem a possibilidade de usar o Azure, mas a minha dúvida é a seguinte: Se eu comprar uma assinatura do Office365 e sendo administrador da conta e podendo acessar o Azure livremente, eu consigo fazer o usuário se autenticar pela minha aplicação com OAuth e enviar arquivos para o OneDrive, Word, ou seja qual serviço que eu queira fazer para o Office365? Se essa não for a melhor opção, gostaria que me dessem alguma orientação para isso pois estou procurando a melhor alternativa para a minha aplicação.

**Comment by eduardojmatos** [comment]
@BellonGN tudo bem? Essa dúvida parece não estar ligada ao desenvolvimento front-end. Nesse caso vamos fechar a issue, ok?

Só parafraseando o README:

> Alguns posts em grupos de front-end em redes sociais geram debates legais que poderiam ser disponibilizados em local melhor estruturado para tal. A busca do Facebook em grupos, por exemplo, tem vários problemas. Discussões épicas foram perdidas, e pessoas que ingressam agora nos grupos não tem mais acesso a esses posts.
>
> A ideia desse repositório é portar ou iniciar essas discussões nas issues. Estando no Github, fica mais fácil procurar respostas a perguntas já respondidas por esses grupos.
>
> O objetivo é unificar todas as discussões em um só local e o Github foi o escolhido para isso.
