### ISSUE TITLE
Comportamento adequado loader página

### ISSUE THREAD

**Issue by RafaelAdao** [frontendbr/forum#632]
Olá a todos,

Em uma página, tenho um Select que traz informações do backend. Conforme o fluxo:
1. Abre a página
1.1 Mostra um loader
1.2 Pesquisa no back
2. Back retorna 
3. Oculta loader

Quando o backend retorna vazio, a impressão para o usuário é que a tela dá uma piscada, pois o loader aparece e some muito rápido. A dúvida é se o mais correto é abrir a página somente quando todos os dados forem carregados, ou colocar um tempo para o loader aparecer (tipo uns 0,8 segundos)

**Comment by abnersajr** [comment]
Você tem algumas formas de abordar isso.
- Aplicar o loader somente na parte onde as informações são exibidas. Exemplo de e-commerces que usam loader em seus produtos.
- Aplicar um timeout mínimo. Digamos que sua resposta seja _too fast_, afinal não tem nada para carregar, coloque um delay mínimo para não dar essa percepção de piscada na tela. Exemplo: Aplique um delay mínimo de 300ms, quando for executar o _hide_ do loader independente do resultado 300ms mínimo de delay para começar a animação proposta. Ai você pode experimentar o tempo, não precisa ser algo MUITO grande, apenas para remover esse efeito indesejado de piscar a tela.

O Loader pode aparecer instantaneamente. Inclusive tente otimizar para que ele seja uma das primeiras coisas a serem executadas.

Espero que consiga resolver da melhor forma seu problema seguindo essas dicas. E qualquer coisa se quiser postar prints e etc para podemos dar mais ajuda é válido :)

**Comment by LFeh** [comment]
Resolveu @RafaelAdao?
