### ISSUE TITLE
Licenças e Direitos autorais no GitHub

### ISSUE THREAD

**Issue by deppbrazil** [frontendbr/forum#635]
**Blz galera? Uma dificuldade que tenho e que preciso de ajuda. =s**

Quando se trata de **Licenças**... Sei que o GitHub disponibiliza padrões de vários tipos de licenças para projetos... sei que a licença MIT em projetos da direito a tudo praticamente, e por ai vai... 

**Porém eis que surge a duvida, quando e como usar?** 

Ex:
> Se eu crio um projeto de minha autoria porém utilizo alguns frameworks ou libs (bootstrap, jquery, etc...) qual tipo de licença preciso usar? 

Outro exemplo:
> Se eu crio um projeto de minha autoria porém não utilizo nenhum framework ou lib de terceiro, ou seja, o projeto ou ideia 100% criação própria, qual licença usar?

Mais um exemplo:
> Se pego parte de um projeto no Github como eu menciono autoria do terceiro em meu projeto? Qual a forma correta de fazer isso?

**Enfim, tem alguma documentação ou artigo falando sobre licenças e padrões?**

**Comment by WandersonAlves** [comment]
Wardando pois interessado nas respostas

**Comment by kvnol** [comment]
Uma dica: http://escolhaumalicenca.com.

**Comment by alexandreab** [comment]
A dica do @kvnol  já explica bem os pontos principais.
Resumidamente, ao utilizar códigos de terceiros, a licensa do seu código precisa ser compatível com esses códigos para que você possa disponibilizá-los juntos. Os termos dessa compatibilidade vão depender de cada licensa.
Para o primeiro exemplo:
> A sua licensa precisa ser compatível. O que pode facilitar (se pretender fechar o código em algum momento) é procurar libs com licensas permissivas.

Para o segundo exemplo
> já está explicado no link.

Para o terceiro exemplo:
> Igual ao primeiro caso: precisa ser compatível. Projetos no Github estão sob os Termos de Serviço do mesmo (também explicado no link)

https://en.wikipedia.org/wiki/License_compatibility

**Comment by Diego-Brocanelli** [comment]
@kvnol excelente link, não conhecia o site :)

**Comment by deppbrazil** [comment]
@kvnol tudo que eu precisava... valew =)

**Comment by HugoSpark** [comment]
O site esta off, alguém sabe se existe esse conteúdo em algum outro site?

**Comment by felipemfp** [comment]
@HugoSpark, tem em inglês: https://choosealicense.com/

**Comment by edmolima** [comment]
@deppbrazil uma talk que pode agregar e sanar suas dúvidas:
https://www.youtube.com/watch?v=hcdI1ybGnac

**Comment by HugoSpark** [comment]
opa vlw pessoal vou dar uma olhada!

**Comment by tarciozemel** [comment]
Desculpa o site off, pessoal. Estamos migrando ele para uma nova estrutura e já já estará de volta. :-)

**Comment by tarciozemel** [comment]
Voltou! \o/ http://escolhaumalicenca.com.br/

**Comment by Miltonr87** [comment]
Valeu, galera! Essa dica do EscolhaUmaLicenca é realmente muito boa. Por vezes fico confuso! Salvei em favoritos o sítio!
