### ISSUE TITLE
Tópico para a criação dos cursos gratuitos para a comunidade!

### ISSUE THREAD

**Issue by alinebastos** [frontendbr/forum#636]

**Comment by NandoKstroNet** [comment]
Qual seria a ementa proposta?

**Comment by kvnol** [comment]
Creio que a primeira ideia seja criar um nome para essa "escola" e abrir uma org para ela aqui no GitHub.

**Comment by alinebastos** [comment]
Não consigo editar o tópico, meu github tá bugado.
Mas criei a issue para elaborarmos os cursos abertos para a comunidade aqui.
Podemos listar os tópicos (cursos), ver quem se responsabliza por cuidar de cada curso, etc.

**Comment by LFeh** [comment]
This issue was moved to frontendbr/open-source#29
