### ISSUE TITLE
SMACSS, BEM, ITCSS e OOCSS qual estilo usar?

### ISSUE THREAD

**Issue by clarabatt** [frontendbr/forum#64]
Ultimamente eu tenho estudado sobre CSS eficiente, estou lendo o livro da casa do código e tenho ficado muito na dúvida de qual desses estilos adotar, qual o melhor jeito de escrever e organizar os arquivos. E ai pessoal, o que vocês tem usado?

**Comment by vitorbritto** [comment]
Olá @clarabatt. Temos a _issue_ #35 publicada com este tópico. Acompanha lá. Obrigado. =]

**Comment by clarabatt** [comment]
Obrigada @vitorbritto, vou lá dar uma olhada! :smile:
