### ISSUE TITLE
Componentes React, bastiani.github.io/bah

### ISSUE THREAD

**Issue by Bastiani** [frontendbr/forum#640]
Oi pessoal, não conhecia essa comunidade aqui, show de bola!
Então, tenho estudado React e ES6 e para por em pratica oque tenho aprendido eu resolvi fazer alguns componentes, [bah-componentes React](https://bastiani.github.io/bah/)
Qualquer contribuição é bem vinda!
Vlw!

**Comment by LFeh** [comment]
Temos um repo exclusivo para open source, coloca lá? 😄 

https://github.com/frontendbr/open-source
