### ISSUE TITLE
BRASIL API 

### ISSUE THREAD

**Issue by lukBarros** [frontendbr/forum#641]
Fala galera!!! Fiz um projeto bem bacana totalmente FREE para desenvolvedores BR.

Trata-se da BRASIL API, UMA API VOLTADA PARA DADOS BRASILEIROS como ações, tempo e clima, busca cep taxa de câmbio, geográfico, financeiro como bancos, dados contábil e de cunho fiscal.

Estarei desenvolvendo sempre novas API's com o tempo. Esse é um projeto beta, logo podem reportar problemas e sugestões. Em breve estará com o fonte e o projeto todo no GitHub.

http://www.brasilapi.com/

**Comment by eluizbr** [comment]
Legal...
qual é o github do projeto ?

**Comment by lukBarros** [comment]
@eluizbr Eu não subi no github ainda, mas farei logo logo

**Comment by eluizbr** [comment]
@lukBarros Legal,
talvez possa contribuir...

**Comment by lukBarros** [comment]
@eluizbr está feito em PHP com YII2

**Comment by eluizbr** [comment]
@lukBarros não é minha stack hoje ..

**Comment by lukBarros** [comment]
:)

**Comment by kvnol** [comment]
Achei :top:, @lukBarros! Seria massa colocar esta issue no https://github.com/frontendbr/open-source, que tal? :smile:

**Comment by kivervinicius** [comment]
quando colocar como open compartilha pra gente. Gostaríamos de contribuir

**Comment by vmarcosp** [comment]
@lukBarros Animal bro! Suba para o GItHub para podermos contribuir!!

**Comment by lucianobragaweb** [comment]
Show cara. Parabéns pelo projeto.

Cara seria muito legal desenvolver uma API para consulta de processos em tribunais. Eu não conheço uma que faça isso. Vamos contribuir galera!!

**Comment by LFeh** [comment]
This issue was moved to frontendbr/open-source#33

**Comment by lukBarros** [comment]
[UPDATE #1 - 08/08/17]

Projeto liberado no github - https://github.com/sururulab/brasil-api

Definido retorno em JSON, removido a validação do e-mail que estava com problemas

Todas as contas não confirmas por problema de não recebimento do e-mail foram confirmas e estão ativas
