### ISSUE TITLE
Como ofuscar chaves API com javascript?

### ISSUE THREAD

**Issue by rafa-acioly** [frontendbr/forum#642]
Atualmente venho trabalhando bastante com APIS e autenticação via `consumer_key`, `api_secret` e etc, e sei que essas chaves são extremamente sensíveis pois elas permitem as requisições `post`, minha duvida é como faço para ofusca-las quando faço o deploy da minha aplicação?

**Comment by AmandaFonseca** [comment]
Ac

**Comment by expalmer** [comment]
As chamadas de API são possíveis serem vistas abrindo o devtools e vendo os heades, não tem muito o que fazer. Mas tu diz que não quer que elas fiquem expostas no repositório ou na aplicação ?!

**Comment by rafa-acioly** [comment]
@expalmer na aplicação, se as chaves ficarem visiveis "qualquer um" pode enviar uma requisição post e tentar danificar tudo entende?

**Comment by icaromh** [comment]
@rafa-acioly talvez valha a pena tu dar uma lida no ciclo de vida do oauth2 e como funciona o lance de tokens que expiram. Ofuscar as chaves não fazem sentido, elas vão ser visíveis no header como o @expalmer mencionou, em dado momento tu PRECISA mandar elas pro teu servidor. 
Provavelmente tu tá com isso em mente pois elas nunca mudam, dai o oauth2 é interessante 👍 

Além disso é uma boa tu manter uma configuração de CORS ok, permitindo requests só de hosts válidos.

E, aproveitando, configurar bem o teu nginx https://github.com/yandex/gixy

**Comment by AmandaFonseca** [comment]
@icaromh A 2 semanas atrás eu estava pirando com um erro Cors quando minha página fazia requisição para outro domínio  tive que pedir ajuda a 2 amigos. 
Excelentes links que vc postou são10/10.

**Comment by barraponto** [comment]
não é melhor vc deixar as chaves no backend?

**Comment by rafa-acioly** [comment]
@barraponto A aplicação que estou desenvolvendo não necessita de backend pois ela consome apenas uma `api`, por isso estou fazendo apenas com javascript para renderizar dados vindo do `GET` e atualizar dados através do `POST`

**Comment by rafa-acioly** [comment]
a resposta do @icaromh já me ajudou e acredito que vá ajudar muita gente caso procurem por este assunto.

**Comment by onhernandes** [comment]
@rafa-acioly apareci meio tarde, mas pra complementar, da uma lida sobrer JSON Web Token. Tu consegue criar tokens no back-end com várias opções, como principalmente, data de expiração.

Digamos que eu faça um login no meu webapp. Envio user+pass pro backend, lá eu valido, crio um jwt e retorno pro front, com duração de 2h. Nas próximas requisições que o front precisar, ele vai me enviar esse jwt(aqui, tu pode trabalhar o que a galera la em cima falou, como CORS e etc). No backend eu verifico esse token, se é válido(não foi gerado de fora ou coisa parecida, e não expirou) eu prossigo, caso contrário eu cancelo ali mesmo. Isso tu pode armazenar na session, localstorage, etc. 

[Site oficial](jwt.io)
[Understanding JSON Web Token](https://medium.com/vandium-software/5-easy-steps-to-understanding-json-web-tokens-jwt-1164c0adfcec)
[Conhecendo o JWT na prática - iMasters](https://imasters.com.br/desenvolvimento/json-web-token-conhecendo-o-jwt-na-teoria-e-na-pratica/?trace=1519021197&source)
