### ISSUE TITLE
Trabalhar no exterior [Remoto]

### ISSUE THREAD

**Issue by lucianobragaweb** [frontendbr/forum#644]
Opa, tudo bom pessoal.
Quero levantar aqui um assunto e acredito que muita gente tem dúvida e que também muitos desenvolvedores mais experientes tem muito a contribuir com a galera que está ai em busca de melhores oportunidades.

Então vou formular aqui algumas perguntas mas fica aberto a discussão. Em resumo quero saber a opinião de vocês sobre qual o caminho a seguir para conseguir trabalho no exterior [REMOTO/PRESENCIAL].

- O que é necessário para trabalhar no exterior?
- O peso de uma formação acadêmica brasileira para se conseguir emprego no exterior.
- Como conseguir contato com empresas no exterior afim de conseguir emprego.
- Dicas úteis para os marinheiros de primeira viagem.
- Conte sua experiência.
- Melhores paises para trabalhar.

Fique a vontade para acrescentar mais conhecimento, perguntas, respostas e o que mais julgarem útil a essa discussão.

**Comment by netojose** [comment]
[Aqui já tem coisa suficiente](https://github.com/frontendbr/forum/issues/56)

**Comment by lucianobragaweb** [comment]
@netojose realmente. Eu não havia visto essa issue #56 mas realmente é uma mina de ouro. Muita informação de altíssimo nível. Estou desde ontem lendo as postagens e seguindo os links que foram indicados lá. Muito conteúdo para digerir. Valew!!

**Comment by netojose** [comment]
:D massa mesmo

**Comment by eduardojmatos** [comment]
@lucianobragaweb pode fechar então, certo?

**Comment by lucianobragaweb** [comment]
Sim @eduardojmatos, com certeza!!

**Comment by eduardojmatos** [comment]
Valeu @lucianobragaweb
