### ISSUE TITLE
Publicar um fork no npm: fere algum código de ética?

### ISSUE THREAD

**Issue by fxcosta** [frontendbr/forum#645]
Pessoal, boa noite! Há uma lib no github que não está no npm, abri uma issue pro autor postar mas parece que ele não mexe no projeto tem mto tempo e nem aceitou os prs... eu dei fork e alterei algumas coisas e corrigi outras... nesse caso eu posso ainda subir o meu fork pro npm? isso infringe alguma regra ou algum código de ética? obs, no repo ele deixa livre para mexer no projeto e distribuir mas não especifica qual licença o projeto está usando exatamente...

a lib é essa: https://github.com/leemachin/say-cheese

**Comment by kvnol** [comment]
Está como MIT, isso te permite modificar e publicar a vontade: http://escolhaumalicenca.com.br/licencas/mit/

**Comment by eduardojmatos** [comment]
@fxcosta em termos práticos não fere nenhuma regra. Mas pensando em ética, talvez faça sentido você solicitar que ele suba pro npm. Se ele não responder, ou não achar interessante, não vejo problemas em você subir não.

**Comment by eberhara** [comment]
@fxcosta eu publicaria e deixaria isto documentado na issue que vc abriu para o autor.

**Comment by fxcosta** [comment]
Obrigado, pessoal! Eu abri uma issue no repo original sugerindo a publicação e vou tentar contato com ele. Caso não consiga vou publicar o meu fork mesmo já que a licença permite. Valeu!

**Comment by barraponto** [comment]
eu publico no meu namespace se eu preciso. aí já tá disponível pra mim, mesmo antes do PR ser aceito no repo original. vide https://docs.npmjs.com/getting-started/scoped-packages
