### ISSUE TITLE
Expandir box ao clicar botão, uma de cada.

### ISSUE THREAD

**Issue by pxntxs** [frontendbr/forum#646]
Confesso que estou com um pouco de vergonha, pois é minha primeira vez mergulhando de cabeça em JavaScript. Minha primeira vez aqui também, então desculpe-me qualquer coisa.

Minha página irá carregar vários desses box, sendo que os mesmos virão de um API.
Eu fiz um script que quando clica o botão 'Preview', ele expande o texto, e que se clicado de novo, esconde o texto. O problema é que esse script que eu fiz (creio que de maneira errada) expande somente o primeiro elemento que levou a `id` chamanda `note`. Sendo assim, outros box não conseguem fazer o mesmo. Creio que o problema seja em chamar o `id` do elemento, pois o mesmo é estático. 

O que vocês acham? Irei ter que renderizar estes elementos via JavaScript para manipulá-los?

Segue imagem do primeiro elemento renderizado funcionando:

![box-1](https://user-images.githubusercontent.com/8277449/29009201-7f84e25e-7af7-11e7-93b0-a11f57fed62c.png)
![box-2](https://user-images.githubusercontent.com/8277449/29009202-7f88c7c0-7af7-11e7-85ce-2f519b50e203.png)

**Comment by houstondapaz** [comment]
Oi @pxntxs para saber como te ajudar é mais fácil vc divulgar o js é o HTML.

Mas de início, já te adianto que o problema é vc manipular via id, os ids não podem ser repetidos, é um identificador único para o elemento na página.
Então se vc tá buscando ele via jquery ou getelementbyid ele sempre vai trazer o primeiro.

E relaxa sobre dúvidas simples, todos nós já fomos iniciantes um dia. Abraço e manda o código ai

**Comment by pxntxs** [comment]
Obrigado por responder, @houstondapaz.

Segue o HTML:

```
<div class="col col-3">
  <div class="bookmark">
  <div class="actions-bar">
  <div class="rmbrr-tooltip">
  <a href="#" id="edit">
  <i class="fa fa-pencil-square"></i>
  </a>
  <span class="content">Edit</span>
  </div>
  <div class="rmbrr-tooltip">
  <a href="#" id="favorite">
  <i class="fa fa-star"></i>
  </a>
  <span class="content">Favorite</span>
  </div>
  <div class="rmbrr-tooltip">
  <a href="#" id="delete">
  <i class="fa fa-trash"></i>
  </a>
  <span class="content">Delete</span>
  </div>
  <div class="rmbrr-tooltip">
  <a href="#" id="preview-btn">
  <i class="fa fa-eye" id="fa-eye"></i>
  </a>
  <span class="content">Preview</span>
  </div>
  </div>
  <div class="bookmark-info">
  <p id="name">Brazil Anthem</p>
  <p class="note" id="note">I
Texto grande aqui
  </p>
  <p id="date">Jul 24th 2017</p>
  </div>
  </div>
  </div>
```
Segue o JS:

```
previewNote: function(){
		const btnId = document.getElementById('preview-btn');
		const noteId = document.getElementById('note');
		let click = true;

		if(btnId){
			btnId.addEventListener('click', function(){
				if(click){
					btnId.innerHTML = '<i class="fa fa-eye-slash" id="fa-eye"></i>';
					noteId.style = 'white-space: pre-line'
					click = false;
				}else{
					click = true;
					noteId.style = 'white-space: nowrap'
					btnId.innerHTML = '<i class="fa fa-eye" id="fa-eye"></i>';
				}
			});
		}else{
			console.log('error in const = previewBtnId');
		}
	}
```

**Comment by houstondapaz** [comment]
Segue o código que alterei para seu problema, tentei comentar o maximo possivel para ser entendido.
Qualquer dúvida é só gritar

```javascript
 //muda de id para class o preview-btn
//aqui passo por cada botao e adiciono o evento click, passando ele para o função que vai fazer o toggle
for (let element of document.getElementsByClassName('preview-btn'))
    element.addEventListener('click', () => togglePreview(element));

function togglePreview(element) {
    //pego o dado se ele foi clicado ou nao (inicial é true)
    let clicked = element.getAttribute('data-clicked') || 'true';

    //criei um metodo para pegar o 'note' do bloco dele
    let note = getMyNote(element);

    //faço a mudança com base no valor do clicked
    //usei uma varial de estados para eliminar os ifs
    note.setAttribute('style', toggleValues[clicked]['note-style']);
    element.innerHTML = toggleValues[clicked]['element-html'];

    //seto o estado do botão com o contrario do que está atualmente
    element.setAttribute('data-clicked', !(clicked == 'true'));
}

//funcao responsavel por pegar o 'note' do bloco do preview
function getMyNote(element) {
    //subo até o nivel do bloco e pego o proximo que é o bookmark onde contem o 'note'
    //acho meio gambiarra mas é o que temos para agora
    let bookmark = element.parentElement.parentElement.nextElementSibling;

    //passo por cada filho do bookmark até achar o 'note' e devolvo ele
    for (let node of bookmark.childNodes) {
        if (node.className == 'note')
            return node;
    }
}

//os valores para quando o botao for clicado e nao clicado
const toggleValues = {
    'true': {
        'note-style': 'white-space: pre-line',
        'element-html': '<i class="fa fa-eye-slash" id="fa-eye"></i>'
    },
    'false': {
        'note-style': 'white-space: nowrap',
        'element-html': '<i class="fa fa-eye" id="fa-eye"></i>'
    }
}
```

**Comment by pxntxs** [comment]
Nossa, cara. Perfeito. Vou levar um tempinho para entender algumas funções ali, coisa que nunca havia visto(por ser novo nisso). Mas me esforçarei bastante.

Achei interessante demais como fez para saber quando foi clicado. Bem diferente.

Muito obrigado mesmo!

**Comment by houstondapaz** [comment]
@pxntxs o atributo 'data-clicked' não é do javascript, eu que criei ele, é meio que um controle no elemento, poderia ser qlqr nome, tipo 'data-foi-clicado'.
Só esclarecendo

**Comment by AmandaFonseca** [comment]
@houstondapaz estou começando no mundo de front tbm achei interessante o seu código principalmente pelo uso do "let" e "const"  e o seu for que acredito se equivalente a um for each onde vc aprendeu esses comandos?

**Comment by clucasalcantara** [comment]
Olá @AmandaFonseca, então, let e const são recursos do es6, são novas formas de se declarar uma variável no JavaScript :). 

Tem muito material aqui no forum aqui no fórum,mas, já de cara dá uma lidinha nesse [post](https://medium.com/@matheusml/o-guia-do-es6-tudo-que-voc%C3%AA-precisa-saber-8c287876325f) do @matheusml, é um bom lugar pra começar.

**Comment by AmandaFonseca** [comment]
@clucasalcantara  Muito interessante vou ler sim com toda certeza.
Obrigada pela dica :)

**Comment by lucianobarauna** [comment]
@houstondapaz gostei muito da solução de criar uma variável de estados

**Comment by LFeh** [comment]
@pxntxs avisa se resolver :)

**Comment by houstondapaz** [comment]
@AmandaFonseca como o @clucasalcantara  falou, são sintaxes do ecma2015, mas se for pré requisito rodar em browser antigos não recomendo usar, ou usar o [babel ](https://babeljs.io/)para ele "compilar" para a sintaxe antiga.

@lucasbento eu sempre uso essa solução para matar uns ifs e switchs, aliás serve pra muita coisa

**Comment by pxntxs** [comment]
@LFeh resolveu bastante. Agradeço demais pela ajuda. Espero um dia poder ajudar alguém aqui.
