### ISSUE TITLE
Desenvolvimento super rápido de jogos e o game Dória Ovo

### ISSUE THREAD

**Issue by rubenmarcus** [frontendbr/forum#652]
Galera, não tem nem 24h que o Dória levou uma ovada em Salvador e o Alex fez um jogo em JS (meio que imitando Angry Birds) do Dória levando ovada

http://dropsdejogos.com.br/index.php/noticias/indie/item/3353-exclusivo-lizard-games-de-alex-leal-desenvolve-o-game-doria-ovacionado-em-homenagem-ao-prefeito

http://www.lizardsgames.com.br/doriaOvo/index.html

Preferências politica a parte, como o pessoal faz um jogo em js tão rápido? 

Existe já scripts, plataformas ou coisas semi prontas, que em um dia, o cara configuraria mais a parte visual do que o mecanismo do jogo em si, e conseguiria em tão rápido desenvolver um game??

Se alguem souber mais sobre isso, estou interessado.
Valeu, Abraço

**Comment by joaodfmota** [comment]
Eu fiz meu tcc em 2012 usando o http://impactjs.com/


Em terça-feira, 8 de agosto de 2017, Ruben Marcus <notifications@github.com>
escreveu:
> Galera, não tem nem 24h que o Dória levou uma ovada em Salvador e o Alex
fez um jogo em JS (meio que imitando Angry Birds) do Dória levando ovada
>
>
http://dropsdejogos.com.br/index.php/noticias/indie/item/3353-exclusivo-lizard-games-de-alex-leal-desenvolve-o-game-doria-ovacionado-em-homenagem-ao-prefeito
>
> http://www.lizardsgames.com.br/doriaOvo/index.html
>
> Preferências politica a parte, como o pessoal faz um jogo em js tão
rápido?
>
> Existe já scripts, plataformas ou coisas semi prontas, que em um dia, o
cara configuraria mais a parte visual do que o mecanismo do jogo em si, e
conseguiria em tão rápido desenvolver um game??
>
> Se alguem souber mais sobre isso, estou interessado.
> Valeu, Abraço
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/qv5NeeRFvWjb8z__lkSDNnVLsCAfwlZ_CZUMbrkw_SqYNHpryJ0KxejiuK1f2xRvLvPgBBTSSgJnNGJnbXWOxVSJTwgRIeKHVsiMt0Zk4YqcUfjDZWz0awu6xecC2zL4WTTHOxF7Mq0LkgeNlkMXhL5nuUUj3w=s0-d-e1-ft#https://github.com/notifications/beacon/ADnNvVQ5VCUSUdtTl4pZstR5rJxC13Doks5sWOz5gaJpZM4OxaQR.gif>

**Comment by tarciozemel** [comment]
Deve ter feito fork de algum Angry Birds generics já pronto e trocou gráficos/sons.

**Comment by pxntxs** [comment]
Vi isso no index.html
```
< !-- Generated by GameMaker:Studio http://www.yoyogames.com/gamemaker/studio -->
```

**Comment by rubenmarcus** [comment]
@pxntxs  Muito bom eu tinha dado um ctrl + f no .js só e quando abri ele nao entendi nada kk esse: http://www.lizardsgames.com.br/doriaOvo/html5game/doria_eggs.js?AYQZB=1329147406

**Comment by barbier** [comment]
O Unity também exporta para o browser, mas precisa de um plugin específico para rodar os jogos.
Outra opção seria o Phaser.
