### ISSUE TITLE
Inserindo checkout PagarMe em uma aplicação React

### ISSUE THREAD

**Issue by WiechersV** [frontendbr/forum#658]
Oi gente.

A dúvida é bem específica, mas sei que tem uma galera aqui do Pagar.me ou talvez alguém que já tenha feito algo do tipo, então...

Tô tentando inserir o [Checkout Pagar.me](https://pagar.me/checkout/) na minha aplicação. Porém, aqui, vamos trabalhar com `Subscriptions`. Até aí, ok, nada que nos impeça de usar o Checkout.
Segundo a [documentação do Pagar.me](https://github.com/pagarme/docs.pagar.me/blob/master/docs/source/checkout.md), dá pra incluir o checkout de duas maneiras via tag de script (Injeta o elemento na página) ou via API.
Aqui começa minha dor de cabeça.

Via script não consegui. O React não carrega o widget, não insere o elemento e eu fico com um formulário vazio. Pensei em algumas coisas mais pra testar mas soaram tão "gambiarrescas" na minha mente que eu nem me atrevi a tentar passar pro código hahauahuauh

Via API até funciona, mas rola algo bem estranho. 
Segundo a documentação do Pagar.me, quando o Checkout for utilizado em conjunto com Subscriptions (Seção "Checkout em Assinaturas" nos docs), simplesmente deve ser passado o atributo `create-token` com valor falso, ele não gera token de transação, manda os dados pro servidor e lá ele se vira. 
Na teoria, ótimo.
No código:
```
const checkout = new window.PagarMeCheckout.Checkout({
            "encryption_key": "bla_bla_bla_whiskas_sache",
            "success": (data) => {
               // !!!!!!!!!!
               // Como o token tá sendo retornado aqui se eu solicitei que o mesmo não fosse criado?

              const token = data.token

              Fetchable(`https://api.pagar.me/1/transactions/${token}/capture`, "POST", {amount: this.props.chosen.amountCentavos, api_key: "bla_bla_bla_whiskas_sache_denovo"})
                .then((json) => { console.log(json) })
          }})
  
    checkout.open({
      "uiColor": colors.primary,
      "createToken": false,
      "amount": this.props.chosen.amountCentavos
    })
```

Mesmo passando o `createToken` como falso, ele *SEMPRE* me retorna o token.
Depois de um tempo pensando, imaginei que sei lá, talvez não dê pra usar o Checkout com Subscription via API, então teria que ser via inclusão de script mesmo, mas como eu falei ali em cima, não rolou (Tentei inclusive usando o `react-load-script` e não rolou).

Alguém aí pode dar uma força? D:

**Comment by LFeh** [comment]
c/c @felquis

**Comment by rafaelverger** [comment]
@WiechersV a resposta do pagar.me não tem o card_hash?

**Comment by felquis** [comment]
Use `createToken: "false"` como uma string.

**Comment by alexsandro-xpt** [comment]
Alguem sabe me falar se o Pagar-me possui gateway de pagamento?

**Comment by augusto-jm-amaral** [comment]
@alexsandro-xpt Possui gateway sim.
