### ISSUE TITLE
React - BSD / Patente de Licença pelo Facebook

### ISSUE THREAD

**Issue by SergioJrDev** [frontendbr/forum#670]
_"A Apache incluiu a licença usada pelo Facebook para o React na Categoria X, uma lista de licenças que violam sua política.

O problema se encontra especificamente neste [parágrafo](https://github.com/facebook/react/blob/master/PATENTS#L14-L26) da garantia de patente. Se você usa o React, você não pode processar o Facebook por violação de patentes, em qualquer parte de qualquer software, mas o Facebook, por outro lado, pode te processar por isso.

Apesar dos pedidos, o Facebook respondeu com a decisão de manter intacta a licença do React, mesmo reconhecendo que poderá perder membros da comunidade, “We recognize that we may lose some React community members because of this decision.”. Membros conhecidos da comunidade, como Nicholas Zakas e Feross, também estão se posicionando contra a decisão do Facebook."_

https://medium.com/@charbelrami/fim-do-react-95888fdddff0

Vocês acham que essa decisão do Facebook podem prejudicar o futuro do React ou vcs irão re-pensar antes de iniciar um projeto com ele, por questão dessa patente?

Eu sei que é mais uma questão jurídica, portante, um pouco confusa pra nós e o que pode impactar no nosso trabalho. Mas eu gostaria de saber a opinião de vocês sobre isso.

Outros links
https://medium.com/@gdi2290/facebooks-bsd-patents-license-and-how-it-affects-you-66088e052845

https://wptavern.com/facebook-isnt-budging-on-reacts-bsd-patents-license

https://meshedinsights.com/2017/07/27/5-reasons-facebooks-react-license-was-a-mistake/amp/

**Comment by rubenmarcus** [comment]
isso aqui é foda..
_I’ll use WordPress as an example. If WordPress adopts React, which they are currently using to build the Gutenberg project which is the planned replacement for the main editor in WordPress, it could have consequences to the entire WordPress ecosystem of commercial WordPress products. Yes, many of these are small businesses. But, many of these have also been acquired by bigger businesses. If WordPress adopts React and that startups product is built on top of WordPress… those bigger businesses could back out of acquisitions because their legal team raises a red flag during due diligence over the React clause._

**Comment by franklinjavier** [comment]
Mais um link pra ajudar... Uma advogada especializada em licenças open source
https://heathermeeker.com/2017/08/19/open-source-community-over-reacts-to-x-rated-code/

**Comment by joselitojunior1** [comment]
Outro link importante foi esse daqui de FAQ que o Facebook soltou: https://code.facebook.com/pages/850928938376556/open-source-license-faq/

Tá bem complicado de interpretar, mas parece um jogo de palavras bem feito pra "se safar"

ainda estou refletindo pra formar uma opinião mais concreta (tem muita informação vindo defendendo ambos os "lados", mas em resumo meu mindset agora é:
- Ferramentas Internas/Site institucional e derivados: ok usar React
- Startup/Produto, etc: melhor nao usar React

**Comment by fernandofleury** [comment]
http://writing.jan.io/2017/08/19/understanding-the-facebook-vs-asf-license-kerfuffle.html

mais um pra ajudar na referência

**Comment by khaosdoctor** [comment]
Mais uma https://medium.com/@dwalsh.sdlr/react-facebook-and-the-revokable-patent-license-why-its-a-paper-25c40c50b562

**Comment by danilovaz** [comment]
Eu li todos esses links e mais uma meia dúzia ahuahuaha. Não tenho embasamento jurídico pra dizer se isso se aplica à nivel global, US, etc.

But, queria deixar minha opinião, alguém talvez possa me ajudar a esclarecer :) 

Trabalhei em uma startup de gerenciamento de redes sociais aka Facebook, Instagram, Twitter etc. Aí já temos 2 produtos do Facebook Inc. Nosso FW lá foi o Ember, mas a dúvida que fique é: e se eu tivesse utilizado React e derivados? Entendo que dificilmente o Facebook vai bater de frente com AWS, Netflix etc. 

Mas e um produto que bate de frente com o agendamento e Facebook Insights? Será que essa patente daria vazão para eles tentarem derrubar o produto? 

Sei que muita gente diz: "Isso só vai te afetar se você for criar o novo Facebook/Instagram/Whatsapp". Mas não é bem assim, tem muita ferramenta de mkt do tipo: mLabs, RDStation, Hootsuite etc. E se o Telegram Desktop fosse em React?

Sei que não tem nada do Facebook indo atrás de ninguém no momento. Mas promessa de empresa é Patente e Contrato. O resto dito, são palavras ao vento rs.

Acredito que não seja fim de React e nem boicote, mas dúvidas como acima acredito que são plausíveis.

**Comment by danilovaz** [comment]
Outra coisa: O Angular.js é licença MIT (assim como praticamente todos os outros FWs) e não vi ninguém indo processar eles por terem migrado para Angular (2+) e dado um "deprecated" no 1.x

Alguém sabe de algum caso de alguém que já processou uma empresa por trás de um FW? Porque aparentemente é esse o motivo o Facebook não retirar as patentes. Como o @SergioJrDev citou acima, é resguardar o Facebook de tomar um processo. Mas faz sentido isso em OS?

**Comment by icaioincau** [comment]
Pelo sim, pelo não, eu evitaria React em projetos para novos produtos.

**Comment by kazzkiq** [comment]
>Alguém sabe de algum caso de alguém que já processou uma empresa por trás de um FW? Porque aparentemente é esse o motivo o Facebook não retirar as patentes.

@danilovaz Cara, minha opinião de completo leigo jurídico: Não existe isso de processar projeto open-source. A própria licença MIT por exemplo diz que **não existe nenhum tipo de garantia** no uso do projeto em questão:

```
(...)
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
```

Fora isso, projetos open-source não possuem nenhum tipo de vínculo "financeiro" com os usuários (no máximo, existem doações, que não são obrigatórias), ou seja, não faz o menor sentido abrir processos contra donos de projetos.

Pra mim isso é jogada suja do Facebook sim. Todos os posts que li defendendo o uso da patente deles me pareceu extremamente tendencioso (até beirando publieditorial). Na minha humilde opinião, a reação da comunidade OSS tem sim que ser enérgica justamente pra mostrar que nesse meio, esse tipo de jogada corporativa não é bem vinda.

Se uma empresa decide mudar a licença no meio do jogo, depois que todo mundo já tá usando o software dela, tudo bem. Ela só não deve esperar que a reação da comunidade seja positiva, né?!

**Comment by wmsbill** [comment]
Li isso um tempo atras e achei importante compartilhar para enriquecer essa discussão.

https://medium.com/@dwalsh.sdlr/react-facebook-and-the-revokable-patent-license-why-its-a-paper-25c40c50b562

**Comment by LFeh** [comment]
Sinceramente? 

Não entendo nada de juridiquês, mas só a necessidade de debater esse tipo de coisa me faria evitar o uso do React em produtos (nenhum problema em usar para open-source e sites institucionais).

A comunidade de software precisa agradecer o React por todas as melhorias e conceitos que trouxe, mas é vida que segue. Temos vários outros SPAs tão bons quanto e que não vão gerar nenhuma dor de cabeça no futuro.

**Comment by joselitojunior1** [comment]
Uma extensão do que o @danilovaz falou: "Isso só vai te afetar se você for criar o novo Facebook/Instagram/Whatsapp". Eu também ando escutando isso direto. A questão é **quando é que você sabe que tá criando o novo Facebook?**

Qualquer produto criado pode ter uma relevância ao ponto do Facebook, que nunca estaria no seu mercado, querer competir com você, independente do produto. Não existe isso de ele não vai competir com X ou Z, se dá dinheiro e é viável, *ele vai*. Anos atrás ninguém diria que ele iria competir com o YouTube, mas tá aí a situação.

Você usando React pra um produto, o Facebook pode até não processar você por isso (e é isso que tá sendo espalhado aos 4 ventos), mas se você for gigante e ele tiver essa arma contra você, ele não só pode como vai usar.

**Comment by cuducos** [comment]
Oi gente. Primeira participação minha aqui nesse forum/repo e tudo que entendi até agora é que pelo jeito ninguém usa ❤️ como reação ; ) 

Mas seguinte… concordo muito com o que o @joselitojunior1 falou no último comentário dele:

> Qualquer produto criado pode ter uma relevância ao ponto do Facebook, que nunca estaria no seu mercado, querer competir com você, independente do produto. Não existe isso de ele não vai competir com X ou Z, se dá dinheiro e é viável, ele vai.

E por isso mesmo não entendi o primeiro comentário dele:

> Ferramentas Internas/Site institucional e derivados: Ok usar React
> Startup/Produto, etc: melhor não usar React

Me explico: imagina que tu fez um site institucional pra uma empresa, sei lá, de Drones. E que o o Facebook resolve entrar no mercado de carros robôs (_driverless_) usando drones para mapear o trânsito, o melhor caminho etc. (Ok, ideia tecnologicamente péssima, mas vai servir pro exemplo.) Aí eles descobrem que aquela empresa para qual tu fez um site institucional usa React no frontend. Pronto… eles podem pegar toda a tecnologia de drones dessa empresa e ela não pode processar o Facebook de volta.

Aí tu me diz: _Tsc ah_, mas é só o site institucional. Dá um `rm -rfv public_html/` e sobe qualquer template no lugar_. Ok. Mas quando essa hora chegar a startupzinha dos drones para quem você trabalhou já perdeu a tecnologia pro Facebook — e a única alternativa é processa-los depois que tu botar o novo site no ar. Mas… e aí? Essa empresa tem fôlego (ou seja, dinheiro em caixa) para brigar na justiça contra o departamento legal do Facebook?

Por questões como essa que eu questiono também o resumão que o @SergioJrDev fez:

> Eu sei que é mais uma questão jurídica, portante, um pouco confusa pra nós e o que pode impactar no nosso trabalho

Não é uma questão jurídica que impacta nosso trabalho. É uma questão jurídica que impacta os modelos de negócios dos nossos clientes. Pode destruí-los e, por efeito dominó, destruir-nos. 

Enfim… sei que soou um pouco como trombetas do apocalipse. Exagerei no tom. Mas é que no geral achei que a discussão aqui estava sendo muito suave com uma decisão que eu vejo como mega importante. Então puxei pro outro lado ; )

Por fim, mais recomendação de leitura (meu favorito sobre o assunto): [If you’re a startup, you should not use React (reflecting on the BSD + patents license)](https://medium.com/@raulk/if-youre-a-startup-you-should-not-use-react-reflecting-on-the-bsd-patents-license-b049d4a67dd2)

**Comment by renatofrota** [comment]
Muito bom exemplo, @cuducos 
> Aí eles descobrem que aquela empresa para qual tu fez um site institucional usa React no frontend. Pronto… eles podem pegar toda a tecnologia de drones dessa empresa e ela não pode processar o Facebook de volta.

Foi exatamente o que eu pensei quando li [esse post aqui](https://heathermeeker.com/2017/08/19/open-source-community-over-reacts-to-x-rated-code/) da Heather J. Meeker e, até o momento, ela não respondeu ao comentário enviado pelo Joe Shabadoo:

> “The Facebook patent license also terminates if the licensee brings a claim against Facebook, or against any party accusing a Facebook product. ”
> 
> Having read several articles on this it seems like non-lawyers, myself included, are reading this to mean that if Facebook infringes on a patent that I own, whether or not it pertains to React, then I would not be able to use React any longer.
> 
> The perception is that Facebook could basically enter any business they want, or infringe patents, and those trying to defend their patent would be at the disadvantage of having to sacrifice React.
So it would not be about the licensee misbehaving but trying to protect their patent from Facebook.
> 
> Can you clarify as to why that is not the case?

Era exatamente o que eu ia perguntar pra ela e estou ansioso pela resposta dela, rsrs.

**Comment by baltazarparra** [comment]
https://preactjs.com/

**Comment by bernardodiasc** [comment]
interessante post sobre o assunto https://medium.com/@ji/the-react-license-for-founders-and-ctos-b38d2538f3e5

**Comment by danilovaz** [comment]
novos episódios dessa novela,  a Automattic vai remover o React do WordPress :cry: https://ma.tt/2017/09/on-react-and-wordpress/

**Comment by kivervinicius** [comment]
migra pro inferno.js (@devnaestrada)

**Comment by devigor** [comment]
React agora usa a MIT License
https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

**Comment by amaurycatelan** [comment]
Cheguei tarde, já postaram o link. 
Podemos ficar tranquilos, agora? 🤔 

> Next week, we are going to relicense our open source projects React, Jest, Flow, and Immutable.js under the MIT license. We're relicensing these projects because React is the foundation of a broad ecosystem of open source software for the web, and we don't want to hold back forward progress for nontechnical reasons.

> This decision comes after several weeks of disappointment and uncertainty for our community. Although we still believe our BSD + Patents license provides some benefits to users of our projects, we acknowledge that we failed to decisively convince this community.

> In the wake of uncertainty about our license, we know that many teams went through the process of selecting an alternative library to React. We're sorry for the churn. We don't expect to win these teams back by making this change, but we do want to leave the door open. Friendly cooperation and competition in this space pushes us all forward, and we want to participate fully.

> This shift naturally raises questions about the rest of Facebook's open source projects. Many of our popular projects will keep the BSD + Patents license for now. We're evaluating those projects' licenses too, but each project is different and alternative licensing options will depend on a variety of factors.

> We'll include the license updates with React 16's release next week. We've been working on React 16 for over a year, and we've completely rewritten its internals in order to unlock powerful features that will benefit everyone building user interfaces at scale. We'll share more soon about how we rewrote React, and we hope that our work will inspire developers everywhere, whether they use React or not. We're looking forward to putting this license discussion behind us and getting back to what we care about most: shipping great products.

**Comment by eduardojmatos** [comment]
#737

**Comment by eduardojmatos** [comment]
@kivervinicius hahah Inferno S2
