### ISSUE TITLE
Erro PHP

### ISSUE THREAD

**Issue by AmandaFonseca** [frontendbr/forum#674]
Oi gente, um cliente precisa de um form com PHP  e euuu nunca mexi com PHP. Então comecei a estudar do zero copiei o seguinte código:

`<html lang="en">
`<head>
`<meta charset="utf-8">
`<meta name="viewport" content="width=device-width, initial-scale=1.0">
`<title>Contact Form</title>
`< ?php'
`$ nome = 'Mauro George';
`$ ano ='1998';
`$ city ='Rio de Janeiro';
` ?>
`</head>

`<body>
'<div> 
  '<p><?php echo $nome; ?>,     nascido em <?php echo $ano; ?> nasceu no <?php echo $city; ?></p>
'</div> 
'</body>
'</html>`

Não funcionou, alguém sabe o por que ?

Coloqui no codepein também: https://codepen.io/AmandaFonseca/pen/xLzyxx

**Comment by fernandocchaves** [comment]
preciso entender de onde vem essas variaveis?

segue codigo mais legivel
<html lang="en">
<meta charset="utf-8">
<title>Contact Form</title>
<body>
	<div>
		<p>
			<?php echo $nome; ?>, nascido em <?php echo $ano; ?> nasceu no <?php echo $city; ?>
		</p> 
	</div>
	</body>
</html>

**Comment by fernandocchaves** [comment]
preciso entender de onde vem essas variaveis

`<html lang="en">
<meta charset="utf-8">
<title>Contact Form</title>
<body>
	<div>
		<p>
			<?php echo $nome; ?>, nascido em <?php echo $ano; ?> nasceu no <?php echo $city; ?>
		</p> 
	</div>
	</body>
</html>`

**Comment by fernandocchaves** [comment]
Preciso entender de ondem vem essas variaives, segue codigo mais legivel

```php
<html lang="en">
<meta charset="utf-8">
<title>Contact Form</title>
<body>
	<div>
		<p>
			<?php echo $nome; ?>, nascido em <?php echo $ano; ?> nasceu no <?php echo $city; ?>
		</p> 
	</div>
	</body>
</html>
```

**Comment by fernandocchaves** [comment]
Qual erro ele retorna? 
Esta com o PHP rodando certinho ?
Servidor apache ou PHP server?

**Comment by AmandaFonseca** [comment]
@fernandocchaves desculpe envolvi todo código com o marcador "insert code" mas não apareceu, agr  alterei o conteúdo da Issue e acredito que agora esteja visível.

**Comment by fernandocchaves** [comment]
Sim eu respondi depois vi correto :)

**Comment by gadielkalleb** [comment]
<html lang="en">
<meta charset="utf-8">
<title>Contact Form</title>
<?php

$nome = 'Mauro George';
$ano ='1998';
$city ='Rio de Janeiro'; 
?>


<body> 
    <div>
        <p>
        <?php 
            echo $nome .''. 'nascido em'.''.$ano.''.' nasceu no'.''.$city; 
        ?>
        </p> 
    </div>
</body> 
</html>

**Comment by fernandocchaves** [comment]
@AmandaFonseca testa seu codigo aqui: http://phpfiddle.org/
Rodei ele aqui e foi certinho

**Comment by AmandaFonseca** [comment]
Então estava rodando ele local mesmo pois esse é o meu primeiro contato com PHP, depois inicializei o wamp server e rodei localhost mas não não exibiu o conteúdo das variáveis.

Esta aparecendo assim:
![contact form - google chrome](https://user-images.githubusercontent.com/22720192/29634934-d0dd73a0-8821-11e7-99ad-e82f5da09776.jpg)

Deveria aparecer o conteúdo das variáveis, ou seja algo assim:

Mauro George, nascido em 1998 nasceu no Rio de Janeiro.

**Comment by fernandocchaves** [comment]
Aparentemente voce esta rodando ele da forma errada ou seu wamp n esta funcionando corretamente. Seu codigo esta correto

**Comment by gadielkalleb** [comment]
vc pode usa assim na tag <p>
echo $nome .' '. 'nascido em'.' '.$ano.' '.' nasceu no'.' '.$city;

**Comment by dtfialho** [comment]
@AmandaFonseca o codepen.io não tem suporte para php se eu não me engano, o melhor é rodar local mesmo, ou se não tiver como procurar por uma outra IDE online.
https://www.tutorialspoint.com/codingground.htm nesse site tem algumas, a de php não é perfeita porque a saída do código é em um console, então fica meio feio, mas funciona. Devem ter outras também que possam até ser melhores, mas eu não costumo usar muito. Espero ter ajudado.

**Comment by AmandaFonseca** [comment]
@fernandocchaves  testei no http://phpfiddle.org/  e funcionou obrigada!

@gadielkalleb  obrigada pela dica!
 
@dtfialho  vou pesquisar essas IDEs  acredito que eu estou compilando(não sei bem se esse termo se aplica ao php) de forma errada mesmo, fiz esse mini código só para teste a partir de agr usarei uma IDE online.

**Comment by gabrieldarezzo** [comment]
Alguns links de php que podem ajudar:

http://br.phptherightway.com/

https://www.cursoemvideo.com/course/curso-php-iniciante/

https://www.cursoemvideo.com/course/curso-de-poo-php/

Rodar o php no ambiente local para testes simples:
http://php.net/manual/pt_BR/features.commandline.webserver.php

**Comment by AmandaFonseca** [comment]
@gabrieldarezzo obrigada pelos links.

**Comment by LFeh** [comment]
@AmandaFonseca O pessoal de backend criou um port desse forum para esses assuntos, recomendo que poste essas dúvidas lá ;)

https://github.com/backend-br/forum

**Comment by AmandaFonseca** [comment]
@LFeh eu não sabia na verdade não reparei, mas entendo a importância de  categorizar as duvidas e de como isso pode ajudar na organização e no compartilhamento de informações.

Afinal minha dúvida pode ser a dúvida de outros também, da próxima vez abro a Issue por lá.

**Comment by LFeh** [comment]
Relax, hehe. 

É que o fórum é focado em Front-End, então evitamos sair muito do escopo 😄

**Comment by fhferreira** [comment]
Opa não reabrindo o tópico, mas caso tenha dúvidas sobre php @AmandaFonseca me marca lá que ajudo se puder

**Comment by LFeh** [comment]
Boa!
