### ISSUE TITLE
Dúvida na consulta do Firebase

### ISSUE THREAD

**Issue by Pedro-Souza** [frontendbr/forum#680]
Galera, eu tenho um consulta no firebase on faço: 
```
ref.orderByKey().equalTo(this.celular).on('child_added', nuumber => {
    this.ctrlCelular = true;
});
```
Porém as vezes, antes de acabar a 'consulta' ele já realiza o cadastramento. Aí eu estou colocando isso em uma Promise, e caso ache o celular no firebase eu 'rejeito' a promise o problema é na hora de resolve a promise, pq se eu colocar um resolve() logo abaixo do `ref.orderByKey()`  não vai nem esperar fazer a consulta e já vai resolver.
Como eu posso contornar isso?

**Comment by LFeh** [comment]
c/c @danilodevhub

**Comment by danilodevhub** [comment]
olá @Pedro-Souza pode postar aqui a `chain` inteira das Promises do seu código?
Se você deseja esperar que a consulta termine talvez um `Promisse.all([...])` funcione pra você

**Comment by eduardojmatos** [comment]
@Pedro-Souza nesse caso, sua dúvida seria "Dúvida na consulta do Firebase"? Pode mudar o título da issue?

**Comment by Pedro-Souza** [comment]
@eduardojmatos pode sim.

**Comment by Pedro-Souza** [comment]
@danilodevhub, o problema é em saber quando a consulta acabou.
tipo:
`      firebase.database().ref('/celulares/').orderByKey().equalTo(this.celular).on('child_added', a => {
           console.log('Me achou');
      })`
com isso eu sei que achou o celular, porém eu preciso saber quando não acha... entendeu?
fiz um teste rápido aqui com Promise.all e não obtive resultado.

**Comment by danilodevhub** [comment]
Entendi...
Vamos lá, esta implementação do firebase SDK abre um websocket (quando browser suportar) pra se comunicar com o realtime-database no back-end. 

Isto significa que a arrow function `a => console.log('Me achou')` é na verdade um _listener_ a qualquer modificação do dado no nó em que você especifica `/celulares/`.
Então creio que quando ele não ache a variável `a` estará `undefined`. Tente fazer esse teste 😉 

_Ps.: Pra entender o funcionamento do Websocket + realtime-database, coloque um `debugger` dentro da sua arrow function e modifique o dado diretamente pelo console do firebase, vais ver que sua function é executada automaticamente_

**Comment by Pedro-Souza** [comment]
Obrigado @danilodevhub, eu acabei resolvendo de outra forma, porém tenho certeza que é a forma errada de se fazer. Mas como o projeto está muitooo atrasado, vai ter que ficar assim por um tempo. Logo logo eu implemento da forma correta. Valeu!
