### ISSUE TITLE
Como decidir em qual área se especializar?

### ISSUE THREAD

**Issue by fndcarlos** [frontendbr/forum#685]
Ultimamente tenho muitas dúvidas sobre front ou back, e não tá fácil escolher, afinal eu gosto das duas áreas. Enfim, quem já passou por isso poderia me ajudar?

**Comment by kivervinicius** [comment]
Você já trabalha na área? Em qual se sente mais confortável? Geralmente a pessoa tenta se especializar por afinidade ou por necessidade em atuar em determinada área. Você precisa analisar a onde você quer chegar, onde se encaixar e mirar nisto.

**Comment by munizart** [comment]
@fndcarlos caso ainda não trabalhe na área e tiveres um tempo livre razoável, pegue um projeto com um pouco mais de complexidade.

É uma decisão que não é fácil mesmo, mas ajuda saber que não é uma decisão definitiva. E caso venhas a mudar de decisão a experiencia de uma é beneficio pra outra

**Comment by LFeh** [comment]
Tem umas issues igualzinhas essa. Da uma olhada lá:

- #353 
- #132 
- #527
