### ISSUE TITLE
[ATENÇÃO] Não queremos dividi a comunidade

### ISSUE THREAD

**Issue by evandro90** [frontendbr/forum#688]
Vamos com calma, pessoal! Vai terminar dividindo nossa comunidade. Lá no twitter ta maior pega pacapá em debate sobre feminismo. Vamos respeitar as opiniões de cada um, é o melhor que fazemos.

Recentemente acompanhei um tweet no twitter de um cara dizendo que apoiava as mulheres, mas não apoiava o feminismo. Resultado? Foi atacado por homens e mulheres que defende o movimento. E se você for lá no twitter agora elas estão atacando todos que se dizem contra o movimento. Estão dizendo que todos homens é um potencial estuprador. Inclusive, estão cobrando satisfação de páginas conhecidas que seguem a pessoa.

Acho bom abrirmos os olhos e não permitir esse tipo de comportamento dentro da nossa comunidade. Nosso foco é Front-End e aqui todo mundo é igual, não tem essa de um melhor que o outro. 

Se permitimos movimentos e política dentro da comunidade vai começar a ficar chato e vamos perder muitos membros importante por conta disso. A sociedade de uns tempos pra cá está totalmente dividida por conta da política.

Não é uma boa entrarmos nessa, a não ser que queiramos nos dividi em 2 comunidades e cada um segue a sua ideologia.

Nada de confusão. Vamos debater e refleti apenas. Talvez, surja algo bom pra gente através daqui.

**Comment by alinebastos** [comment]
"Elas"? Tu sabia que "elas" estão aqui na comunidade?

**Comment by alinebastos** [comment]
As mulheres terem o respeito e o direito que merecem é muito chato pra ti?

**Comment by alinebastos** [comment]
"Acho bom abrirmos os olhos e não permitir esse tipo de comportamento dentro da nossa comunidade. "
É uma comunidade machista, então?

**Comment by alinebastos** [comment]
Sério, acho melhor tu ler, estudar, te informar melhor sobre o que é o feminismo antes de falar tanta bobagem novamente ;)

**Comment by gadielkalleb** [comment]
Se foi no Twitter a coisa tá lá . É desnecessário esse tipo de post ,nem devíamos tratar essas coisas aqui no Git Hub 

Cadê os moderadores?

**Comment by leandroc** [comment]
Já começa errado: dividi**R**

**Comment by lucasjs** [comment]
Perai, o cara diz que apoiava as mulheres mas não apoiava o feminismo? Coerência kd? O comportamento que não devemos permitir é o de desrespeito as mulheres, cujo VOCÊ deveria ficar chocado ao invés de ficar chocado com uma besteira dessas. Todo grupo há extremistas, e não é por causa disso que devemos deslegitimar a causa das mulheres, negros, LGBT e minorias em geral.
Na teoria é muito lindo isso de somos todos iguais, mas a prática é outra, e por isso há pessoas lutando por diversas causas.
Acredito que diversas pessoas estão lutando sim pela união. Se há alguém se sentindo "exclúido" por ser machista, racista ou homofóbico, é porque mereceu.

**Comment by alinebastos** [comment]
Inclusive o cara que disse isso no twitter já entendeu que estava errado e pediu desculpas. Sabia? Sabia? Não, né?

**Comment by alalbuquerque** [comment]
Não é questão de você ou não gostar do assunto. A questão é muito maior, quando falamos de comunidade falamos de pessoas e os debates de inclusão são importantes, já que nossa sociedade anda tão dividida assim. O dialogo aberto é importante sim, mas é sempre bom manter o respeito e ter empatia pelo problema do outro.

**Comment by lucasjs** [comment]
E que bela conta fake :wink:

**Comment by gdomiciano** [comment]
Caro @evandro90, tenho uma lista de perguntas que quero que me responda:

1. Quantas vezes você foi questionado sobre **TPM** em uma **entrevista**?
1. Quantas vezes você foi questionado se tinha ou gostaria de ter **filhos** em uma **entrevista**?
1. Quantas vezes você foi questionado se era **comprometido** em uma **entrevista**?
1. Quantas vezes você precisou ouvir "**Ah, mas você fala isso porque é novo**" quando diz que **não** quer casar ou ter filhos?
1. Quantas vezes você foi chamado de **Histérico** por ser **mulher**?
1. Quantas vezes você foi perguntado se **existem** boas mulheres desenvolvedoras no mundo?
1. Quantas vezes você **deixou** de colocar a foto no currículo por ser mulher?
1. Quantas vezes você foi **negado** numa vaga por ser mulher trans?
1. Quantas vezes foram **verificar** e o que você disse era **verdade**?, afinal se é uma mulher dizendo que a boa prática é 'X' e bom validar na documentação.
1. Quantas vezes disseram que você **conseguiu** uma promoção porque **deu** pro chefe?
1. Quantas vezes disseram que você **saiu** com o professor pra ser **uma** dos três alunos que passaram na prova que os outros 28 machos não passaram, mas engraçado que os outros **dois** que passaram comigo **não deram pro professor**, né?
1. Quantas vezes você ouviu: '**Nossa você é uma desenvolvedora, e é mulher?**'
...

se quiser tenho uma lista muito maior de perguntas para te fazer e mostrar que o que queremos é basicamente **igualdade e respeito**, e o feminismo é um movimento que se baseia nesses dois pontos. NENHUMA das mulheres querem agredir homens, odeiam Homem ou sequer querem ser melhores do que eles, queremos apenas sermos respeitadas e tratadas como igual, pelo nosso conhecimento e valor que temos como profissionais, independente de sexo, cor, raça religião orientação sexual ou identidade de gênero.

Fico no aguardo de sua resposta.

PS.: dividi**r**

**Comment by Mendrone** [comment]
Issue removida e bloqueada por ir contra o CDC
