### ISSUE TITLE
ARROGANCIA

### ISSUE THREAD

**Issue by evandro90** [frontendbr/forum#689]
AS FEMNINISTAS TAO QUERENDO TOMAR O PODER DAS COMUNIDADES DE TI E UM MONTE DE BABACA FICAM PAGANDO PAU PRA ELAS PELO FATO DE SEREM MULHERES..

DEIXEM DE SER ARROGANTES.. DEPOIS RECLAMAM PORQUE GANHAM POUCO. CRIEI O BAGULHO AQUI PRA SER DEBATIDO NUMA BOA

FIM AO FEMINISMO, COMUNISMO, SOCIALISMO E TODOS MOVIMENTOS QUE SE VITIMIZAM.

**Comment by LarissaAbreu** [comment]
@Mendrone @fdaciuk @LFeh @eduardojmatos really???

**Comment by evandro90** [comment]
SABEM NEM PROGRAMAR DIREITO E QUEREM SENTAR NA JANELA

**Comment by raulfdm** [comment]
Alguém da ban nesse cara... Pfv

**Comment by grsabreu** [comment]
Calma cara tá muito exaltado, escuta isso aqui pra relaxar
https://www.youtube.com/watch?v=U06jlgpMtQs

**Comment by alalbuquerque** [comment]
Desculpe o desrespeito https://www.youtube.com/watch?v=-MK1q9fZjeI

**Comment by evandro90** [comment]
BURRICE É O QUE VOCÊS FAZEM QUANDO ESTÃO PROGRAMANDO OU DIRIGINDO

**Comment by evandro90** [comment]
SÓ CAGAM O CÓDIGO, ASSIM COMO SÓ CRIA ACIDENTES NA PISTA..
