### ISSUE TITLE
Tenho muito tempo livre e quero chamar a atenção 

### ISSUE THREAD

**Issue by ghost** [frontendbr/forum#693]

**Comment by AmandaFonseca** [comment]
Não gosta é só sair

**Comment by alinebastos** [comment]
Tchau! Vai pela sombra!

**Comment by gadielkalleb** [comment]
Vai transar cara é para de enche o saco.

**Comment by alalbuquerque** [comment]
Tá faltando job só pode

**Comment by AmandaFonseca** [comment]
![atencao](https://user-images.githubusercontent.com/22720192/29887949-7b771a1e-8d95-11e7-91e3-3749828540b3.jpg)

**Comment by mateusmiguel** [comment]
eu tenho é medo

**Comment by gadielkalleb** [comment]
Deve tá faltando mesmo. Alguém manda o link dos Challenger de front pra ele passa o tempo

**Comment by guilhermependezza** [comment]
Gasparzinho era um fantasma legal. Ghost, aprenda com ele.

**Comment by jaydson** [comment]
A equipe jurídica da Nasc (empresa responsável pela BrazilJS) já foi acionada e o pessoal aqui do frontendbr já está em contato com o GitHub.
Ter bons amigos trabalhando no GitHub é bom numa hora dessas, né? Fica bem mais fácil :wink: 
Deixem o usuário se manifestar, quanto mais usuário fake e mais comentários melhor.

**Comment by Mendrone** [comment]
E o cara acha mesmo que essa comunidade é feita de peixe pequeno né? 

Agora nós vamos te acha, bobão :D

**Comment by alalbuquerque** [comment]
![lovelace_1000x561](https://user-images.githubusercontent.com/9285479/29888157-472d5bbe-8d96-11e7-9436-51475b5af21f.png)

**Comment by didiraja** [comment]
Cheguei tarde pra treta :(

**Comment by JoseCage** [comment]
Opa.. Já foi banido do Github.. :+1: :+1: :cake: 


Cheguei para saber a história toda mas se foi banido é porque mereceu..

Viva a comunidade organizada e respeitadora..
