### ISSUE TITLE
QUE FIQUE CLARO

### ISSUE THREAD

**Issue by n40p4rt1d0** [frontendbr/forum#698]
NÃO SOMOS POTENCIAIS ESTUPRADORES!

FEMINISMO NA COMUNIDADE DE DEVELOPERS NÃO

**Comment by WeltonSanches** [comment]
Que cara chato.

**Comment by viniciusdocanto** [comment]
Não tem como limitar a criação de Issues não? por pra ser aprovadas todas, sei-lá.

**Comment by gabrieldarezzo** [comment]
A comunidade é tão bacana, tanta coisa legal pra você motivar seu tempo/esforço.
Aprender/compartilhar/ajudar.

Pega algum projeto OpenSource, uma tecnologia que você não conhece ou se especializa em algo que já tem domínio.

Perda de tempo isso cara 👎

**Comment by n40p4rt1d0** [comment]
VAI MESMO PERMITIR SER CHAMADO DE ESTUPRADOR?

ME RESPONDA.. VOCÊ É?

**Comment by n40p4rt1d0** [comment]
NEM TODO MUNDO CONCORDA COM ESSA PRÁTICA.

ALIAS, NÃO ENTENDO PQ TEM ALGUNS QUE AINDA CONCORDAM EM SER CHAMADO DE ESTUPRADORES.

**Comment by gabrieldarezzo** [comment]
Don't feed the troll, enfim. 
Da uma refletida sobre usar seu tempo/nosso de forma mais útil.
Deixa eu voltar pro meu paperfiy que tenho umas task pra entregar....
