### ISSUE TITLE
VOCÊ É ESTUPRADOR? REFLITA!

### ISSUE THREAD

**Issue by n40p4rt1d0** [frontendbr/forum#699]
VOCE HOMEM..

CONCORDA SER CHAMADO DE ESTUPRADOR PELAS MULHERES?

VÃO CONCORDAR COM ESSE TIPO DE ATITUDE E FICAR CALADO SÓ PELO FATO DE SEREM MULHERES?

QUE DIREITO ELAS TEM DE NOS CHAMAR DE ESTUPRADOR?

**Comment by alalbuquerque** [comment]
![image](https://user-images.githubusercontent.com/9285479/29921480-192606e8-8e28-11e7-9f15-b096966bcaf4.png)

**Comment by raulfernando** [comment]
Que cara chato!!! Vai procurar oq fazer

**Comment by lucasbento** [comment]
Num podem ter porra nenhuma legal que já querem estragar.
