### ISSUE TITLE
Combatendo o câncer feminista e esquerdista

### ISSUE THREAD

**Issue by psycl0n** [frontendbr/forum#700]
Caros colegas.

Aposto que vários vocês já estão de saco cheio destes SJW hipsters e gamer gurls de cabelo colorido burras invadindo a nossa área, querendo forçar esquerdismo e inclusão em nossas palestras técnicas.

A real é que temos que começar a tomar uma reação contra isto. Temos que começar a boicotar os SJW de nossas próprias empresas. Lugar de mulher é na cozinha preparando sanduíche, lugar de esquerdista é dentro de faculdade de humanas fedendo a lixo.

As mulheres simplesmente não tem capacidade mental para trabalharem com exatas. É só ver aquela BrazilJS e  o nível daquela Alda. A única coisa que elas querem fazer é chamar atenção para chupar a maior quantidade de rolas possíveis.

**Comment by rubenmarcus** [comment]
Putz , mano se quiser e passo o endereço de um bom psicólogo, mas pohan da pra fazer uma lista imensa aqui de "hipsters" e "feministas e esquerdistas", que contribuiram muito mais que eu ou você.

**Comment by rubenmarcus** [comment]
"nossa área" , parece criança do jardim de infância

**Comment by lucasbento** [comment]
Reportem: https://github.com/contact/report-abuse

**Comment by psycl0n** [comment]
Contribuem com o que? Hue. 

As únicas merdas que sabem falar é sobre inclusão e diversidade, pasmem, em uma área técnica.
Não vi palestra nenhuma sobre código, framework, qualidade. Tudo o que vejo é bostejamento político.

**Comment by rubenmarcus** [comment]
Entendi, porque código é só feito por robo, não existem pessoas por trás do código não.

**Comment by MarcoWorms** [comment]
@mtmr0x @willianjusten @LFeh alguem aqui pra acabar com essa piada de issue? É muito choro pra pouco código bom :P

**Comment by psycl0n** [comment]
Eu entrei na computação achando que esta é uma área onde eu poderia fazer o que eu gosto. Trabalhar com tecnologia e ver meus animus. Do nada eu começo a ver uma porrada de hipster SJW magrelo e gamer gurls de cabelo colorido forçando esquerdista e enchendo o saco. 

O dia que forçaram uma gerente mulher burra pra caralho eu toquei o foda-se. Mandei tomar no cu e se foder e pedi as contas. 

A única área que o câncer está longe são os concursos públicos porque eles não tem culhões. Em concurso público a admissão é por via de prova. Então você sabe que não vai ser uma outra vagabunda do RH que vai selecionar a vadia e não vai usar critérios do tipo se o sujeito tem ou não namorada.

É isto que os judeus querem.
