### ISSUE TITLE
indexOf ou Includes?

### ISSUE THREAD

**Issue by gkal19** [frontendbr/forum#702]
O que vocês preferem para usar em um `array`?

- `indexOf`
```js
if (arr.indexOf(el) !== -1) {
    ...
}
```
- `includes`
```js
if (arr.includes(el)) {
    ...
}
```

Na opinião de vocês, qual o melhor em legibilidade ou performance?

**Comment by kivervinicius** [comment]
O includes ainda é uma proposta né, mas como sou das antigas e acostumado com outras linguagens indexOf para mim ainda é melhor.

**Comment by TiagoDanin** [comment]
Prefiro o `includes` por ele já retorna `true` ou `false`.

**Comment by danielGalvao** [comment]
O indexof é pouca coisa mais performático, mas vale mais usar includes pela legibilidade dependendo do tamanho do array

**Comment by kivervinicius** [comment]
legibilidade por legibilidade teria sido melhor se tornar contains hehe, mas já foi explicado que "quebraria" muito a web.

**Comment by leobetosouza** [comment]
Você sempre pode usar

```
if (~arr.indexOf(el)) {
    ...
}
```

**Comment by lnfnunes** [comment]
Sem dúvidas, para verificar se um item existe numa lista, use ```includes```

**Comment by geovanerocha** [comment]
Uso includes pra array, e contains pra strings.

**Comment by fdaciuk** [comment]
Na verdade, são dois métodos que servem para propósitos diferentes. 

---

Só um adendo: O `contains` iria entrar na nova especificação, mas foi pivotado porque ele iria quebrar muito a web. O `includes` foi adicionado no seu lugar.

---

Antes do `includes`, o `indexOf` era bastante utilizado para checar se algum valor batia com algum índice em um array, ou se alguma string continha algum trecho de texto.

Mas é importante frisar que o `indexOf` serve para retornar o **índice** - no array ou na string - onde aquele trecho de texto foi encontrado.

O **includes** entrou para não precisar transformar o resultado do `indexOf` - que sempre vai ser um número - em um booleano, pois o `includes` já retorna sempre `true` ou `false`.

Mas um não substitui o outro. Se você precisar do **índice** de um array onde um texto se encontra, você não vai conseguir isso com o `includes`, somente com o `indexOf`.

Exemplo: você tem um CSV, e precisa pegar apenas uma coluna desses dados, mas não sabe a posição em que essa coluna está. Como você faz? Vamos ver como fazer usando o `indexOf`:

```js
const csv = `Id,Nome,Idade,email
0,João,20,joao@gmail.com
1,Maria,22,maria@gmail.com`

// Queremos só os nomes.
// Vamos quebrar a string em "toda quebra de linha" e transformá-la em um array, para pegar as linhas
const lines = csv.split('\n')

// o retorno de `lines` é:
// ['Id,Nome,Idade,email', '0,João,20,joao@gmail.com', '1,Maria,22,maria@gmail.com']

// Agora temos as linhas, mas não sabemos exatamente em qual coluna o "Nome" está no CSV. Vamos então quebrar a primeira linha com os títulos - nas vírgulas -, e usar o `indexOf` para retornar o índice de onde está a coluna "Nome"
const nameIndex = lines[0].split(',').indexOf('Nome')

// Agora `nameIndex` tem o índice da coluna onde estão os nomes, nesse caso, "1". Agora é só usar o map, que irá transformar o array, mas irá retornar um novo com o mesmo tamanho, e pegar só os nomes:
const names = lines
  .slice(1) // remove a linha com os títulos
  .map((line) => line.split(',')[nameIndex])

// Agora, em `names` temos apenas os nomes:
// ['João', 'Maria']
```

Acho que ficou claro que um método não substitui o outro, mas conhecendo a linguagem, você saberá usar o melhor método para o momento certo :)

**Comment by raphaguasta** [comment]
A partir do que o @fdaciuk respondeu, me veio uma outra questão.

E quanto ao [findIndex()](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex), vcs costumam usar? Em quais situações?

Ou indexOf e includes resolve tudo pra vcs?

**Comment by fdaciuk** [comment]
O `findIndex` é legal usar quando você precisa, por exemplo, pegar uma parte da string que está em um array, ou algum valor de propriedade dentro de um objeto, por exemplo.. o `indexOf` só vai retornar maior que `-1` se a string - ou o valor - encontrada for exatamente igual à passada para a função. No caso, o `find` e `findIndex`, como recebem um predicado (função que retorna um booleano), dá pra fazer uma busca bem mais específica no array =)

**Comment by leobalter** [comment]
O includes já foi publicado como especificação há um bom tempo, ES2016, já estamos com o ES2017 publicado e trabalhando no ES2018.

Além do que já foi falado, pode adicionar que includes também serve para encontrar `NaN`.

Ele não é diferente do que foi inicialmente proposto como `contains`, apenas o nome foi ajustado para evitar quebrar a web.

**Comment by barraponto** [comment]
Vale lembrar que tanto `.includes` quanto `indexOf` trabalham com a identidade do objeto, não o valor. Por exemplo:

```js
const list = [{a:1}, {a:1}, {a:1}];
list.includes({a:1}); // RETORNA FALSO
```

Isso porque a lista tem 3 objetos *diferentes mas com os mesmos valores*.
E na hora de procurar, nós procuramos por um *quarto* objeto (ainda que com os mesmos valores).
Mas funciona com referências:

```js
const x = {a:1};
const list = [x, {a:1}, {a:1}];
list.includes(x); // RETORNA TRUE
list.includes(list[1]); // RETORNA TRUE mas é meio óbvio.
```

Ou seja: se você não tem uma referência ao objeto, não vai poder checar se ele está no array com `.includes` (ou `.indexOf`). Nesse caso, o ideal é usar `.find`, com um predicado que checa o valor:

```js
const list = [{a:1}, {a:1}, {a:1}];
list.find(item => (item.a === 2)); // RETORNA undefined que vale por FALSO
list.find(item => (item.a === 1)); // RETORNA {a:1} (o primeiro) que vale por TRUE
```

**Comment by suissa** [comment]
@raphaguasta cara eu ja cheguei a usar, se não me engano foi no Angular e era para eu achar um objeto no meio dum Array e ou modificá-lo ou eliminá-lo, sorry não lembro direito hehehehhe.

Por exemplo com o includes você só saberá se aquilo existe ou não no Array, com find você irá receber o elemento procurado, mas nenhum deles lhe diz em que posição do Array ele se encontra, ou seja, para qualquer funcionalidade onde você dependa de saber qual a posição do elemento no Array o findIndex é super indicado.

Mas se eu estiver falando besteira por favor me corrijam.

@fdaciuk vc prefere usar indexOf ou findIndex? Eu pelo menos prefiro o último 💃

**Comment by fdaciuk** [comment]
@suissa depende do que precisa xD
Se for pra buscar o índice de algum valor primitivo que eu saiba exatamente qual o valor, eu usaria `indexOf`. Em todos os outros casos, o `findIndex` :)
