### ISSUE TITLE
Ajuda com Carousel

### ISSUE THREAD

**Issue by gadielkalleb** [frontendbr/forum#704]
ola pessoal

to com um problema, estou com 3 banners que estão num carousel, só que um deles é um gif que esta muito mal feito, ele quebra nas suas proprias transições.
esse material era pra ter pronto. ligamos na agencia o cara falou para fazer a animação com html. ?????????

isso não era pra vir pronto ?

tenho aqui o psd com esse banner mas como crio um gif com isso ? que ele fique animado 

alguem pode me ajudar.

**Comment by gadielkalleb** [comment]
@LFeh obrigado pela labell to no desespero aqui rs

**Comment by LFeh** [comment]
Dê uma estudada em [CSS Animations](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations) e [CSS Transitions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions).

Na verdade é bem simples desenvolver o que foi pedido, só precisa entender essas propriedades.

**Comment by kivervinicius** [comment]
@gadielkalleb  se você está "desesperado" use essa ferramenta do google "like a flash" https://www.google.com/webdesigner/ já salvou minha vida uma vez, mas o código gerado é terrível. Use para entender primeiro como funciona depois tente fazer sem a ferramenta.

**Comment by gadielkalleb** [comment]
na verdade o carousel com bootstrap eu fiz tranquilo, o problema é esse gif que ja veio zoado dessa agencia e eu só tenho um psd do mesmo essa é minha duvida alguma ferramenta que possa aminar esse psd pois não sei nada de photoshop

**Comment by kivervinicius** [comment]
@gadielkalleb exporte todas imagens do psd que você queira animar e utilize a ferramenta que te falei.

**Comment by gadielkalleb** [comment]
vou olhar aqui, essas agencias são uma merda mesmo

**Comment by kivervinicius** [comment]
Peça que eles exportem os PNG para você.

**Comment by gadielkalleb** [comment]
eu liguei la mas falei com uma mula que mexe com o pc, escutei o cara falar só merda "eu fiz a arte se vira ai "

**Comment by kvnol** [comment]
Você tá muito bravo, mano, tem que ter um pouco mais de calma e estudar o problema antes de xingar meio mundo. Estressando-se dessa forma, desnecessariamente, tu não vai aguentar 5 anos na profissão.

**Comment by clucasalcantara** [comment]
Então mano, gerar GIF com psd é mó easy, fora o trampo manual de exportar os treco. Mas ó, concordo com o @kvnol ^^. Agência é quase sempre assim mano, respira fundo e busca uma solução alternativa, antes de infartar.

Bom, vamo lá tem esse tio aqui http://gifmaker.me/ que eu já usei. Basicamente, vc exporta a sequência de imagens que quer transformar em gif e clica em `create gif animation`, as configs defaults devem ser o suficiente pra web, eu sugiro o ajuste do tamanho do canvas somente.

**Comment by gadielkalleb** [comment]
@kvnol não to nervoso não man, pq só disse que o cara só falou um monte de merda.

penso da seguinte forma se for par fazer algo faça direito, na verdade isso foi um meio trabalho.
a empresa aqui pagou para eles fazerem isso o mais justo é entregar o oq foi tratado.

@clucasalcantara eu usei aqui sua solução mas continua a mesma coisa, passei para uma pessoa olhar realmente foi mal feito mesmo o banner. mas obrigado @clucasalcantara @kivervinicius 


vou ligar la e cobrar isso.

**Comment by clucasalcantara** [comment]
:/ @gadielkalleb tranquilo mano! Boa sorte ai! :/
