### ISSUE TITLE
Como "deployar" o código em produção?

### ISSUE THREAD

**Issue by kazzkiq** [frontendbr/forum#71]
Então galera, qual processo e/ou serviço que vocês usam para enviar o código de um projeto para produção?

Atualmente eu faço todo o processo manualmente (rodo o build do projeto, pego os arquivos, envio pro server, reinicio ele), mas já ví algumas empresas usando serviços específicos pra isso. To curioso pra  saber o que a galera daqui anda usando pra facilitar a vida nesse sentido :)

**Comment by victormiguez** [comment]
Aqui onde trabalho nós temos um servidor que deixamos instalado o [Jenkins](https://jenkins-ci.org/), ele fica "escutando" os branches master e develop no [bitbucket](https://bitbucket.org/), quando há uma alteração ele faz um pull desse branch, roda build, testes, etc.
Depois disso envia para o servidor utilizando git também.
O jenkins é uma ferramenta muito boa, e gratuita. Porém você leva um tempo para instalar e configurar seus jobs para cada projeto. Mas existem outras soluções de integração contínua no mercado.

**Comment by luisfmsouza** [comment]
Sempre que vou começar um projeto pessoal, eu uso uma ferramenta diferente.

Atualmente tenho projetos usando:
- https://codeship.com/
- https://travis-ci.org/
- https://www.heroku.com/

Gostei da experiencia em todas elas, mesmo usando o plano gratuito.

**Comment by leandromarques** [comment]
Git + Capistrano

**Comment by diogorodrigues** [comment]
@victormiguez Na empresa que trabalho quando fazemos um push na master precisamos ir na pasta do projeto no Jenkins e clicar em "Construir agora". Da maneira como você disse esse processo já é automático?

**Comment by rkb81** [comment]
Aqui depois que descobrimos o capistrano, chora nenem é uma maravilha, basta rodar:

- `cap staging deploy` para subir para homologação
- `cap production deploy` para subir para produção

Ainda estamos melhorando o capistrano pra definir regras que faça o sync de algumas pastas em repositórios próprios e sync do banco de dados também, a idéia é automatizar o máximo possível.

**Comment by leandromarques** [comment]
@rkb81 Aqui também usamos o Capistrano, puxando repositório no Bitbucket.

Basicamente temos 3 branchs principais: dev, beta e production (os nomes já são auto-explicativos). Com isso no servidor é só usar `cap beta deploy` e `cap production deploy` já devidamente configurados no `deploy.rb`.

O bom é que além do deploy do projeto, dá pra usar e definir tasks a serem executadas, como importar o banco, entre outras coisas. Realmente é uma mão na roda!

**Comment by victormiguez** [comment]
@diogorodrigues sim, ativamos essa opção nas configurações do job:
![untitled-1](https://cloud.githubusercontent.com/assets/4250355/13360780/9161b18a-dc99-11e5-8f9b-ea7ee66d9614.jpg)
E ativamos um webhook no projeto do bitbucket, dessa forma os builds passam a ser automáticos.

**Comment by diogorodrigues** [comment]
Que maravilha @victormiguez . Tentarei fazer aqui. Valeu!!

**Comment by victormiguez** [comment]
@diogomoretti beleza! Qualquer dúvida estou por aqui! :)

**Comment by juniorconte** [comment]
Aqui nós fazemos algo parecido com o feito pelo Capistrano, mas usando a stack de plugins do Grunt mesmo. O build acontece normalmente, e no final executamos um rsync com grunt-shell

```
shell: {
  'deploy-staging': {
    command: 'rsync -av --update --delete ./dist/ user@staging.local:/var/www/project',
    options: {
      stdout: true
    }
  },
  'deploy-production': {
    command: 'rsync -av --update --delete ./dist/ user@prod.com.br:/var/www/project',
    options: {
      stdout: true
    }
  }
}
````
ps: o Shell é bacana prq tem um setup pequeno, mas com rsync depende de um ambiente UNIX.

Outra ferramenta que estamos usando é o https://www.deployhq.com que pode ser integrado ao GIT, e permite executar scripts shell pré e pós deploy (sendo possível fazer o build na implantação). Tem um bom custo benefício, e é free para um projeto, mesmo privado.

Se puder escolher a hospedagem, e se for front / back separados, estamos testando o aerobatic.com , que tbm se integra muito bem ao bitbucket.

**Comment by vitorbritto** [comment]
Para este tipo de tarefa, utilizo Shell Script (meu canivete suíço). Tenho um _set_ de _scripts_ e coloco-os em uma pasta nomeada como `./bin` para realizar as tarefas.

**Comment by robsonbittencourt** [comment]
Na empresa que trabalho utilizamos Jenkins + Shell Script + alguns scripts em Python. 

Em outra empresa que trabalhava, utilizavámos algo parecido, mas também tinha este plugin do Jenkins que acho bem interessante:

https://wiki.jenkins-ci.org/display/JENKINS/Build+Pipeline+Plugin

Com ele você monta um pipeline com todos passos necessários para o seu deploy, e fica bem fácil de visualizar. Muito útil quando o deploy envolve diversos passos.

**Comment by tcelestino** [comment]
Jenkins + Shell Script + Operações (responsável pela instalação do pacote).

**Comment by Deigounico** [comment]
Galera, comei a usar o jenkins em uma maquina linux (centOS 7), criei um job e apontei para uma pasta onde tem um shell script, porem, ele me apresenta o seguinte erro:

================================================================
Building in workspace /home/diego.silva/automacao
java.io.IOException: Failed to mkdirs: /home/diego.silva/automacao
	at hudson.FilePath.mkdirs(FilePath.java:1171)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1210)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:560)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:485)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)
Finished: FAILURE
================================================================

Alguem saberia me dizer oque esta causando este erro?

**Comment by icaioincau** [comment]
Failed to mkdirs, o seu user tem permissão para criar pastas na home? /home/diego.silva/automacao

**Comment by Deigounico** [comment]
Já consegui resolver, o jenkins estava executando com o usuário padrão... alterei as configurações para o meu usuário e funcionou.
Segue o link :
http://blog.manula.org/2013/03/running-jenkins-under-different-user-in.html
