### ISSUE TITLE
...

### ISSUE THREAD

**Issue by AmandaFonseca** [frontendbr/forum#710]

**Comment by mikejavier** [comment]
Haters você vai encontrar em toda esquina.
Mantenha o foco e persistência que logo logo as recompensa chega.

**Comment by bernardodiasc** [comment]
Acha um lugar melhor pra vc trabalhar, com pessoas melhores.

**Comment by glauberramos** [comment]
Acho que tem muito preconceito com mulheres programadoras, eu sugeria tu achar um lugar que tenha um ambiente mais seguro e mais respeitoso. Tu pode aplicar para uma das empresas da lista de melhores lugares para mulher trabalhar por exemplo: http://www.meioemensagem.com.br/home/ultimas-noticias/2017/05/10/as-melhores-empresas-para-as-mulheres-trabalharem.html

Eu acho que tbm existe um certo preconceito com frontend (javascript, html e css). E php tbm, apesar de ser usado em uma grande porcentagem dos sites hoje. Não de bola para isso e continue estudando, o mundo frontend é bem grande e tem muita coisa legal, va em eventos, participe da comunidade.

**Comment by AmandaFonseca** [comment]
Quando eu comecei a estudar front eles começaram com um papinho de que quem trabalha com front-end nem pode ser chamado de desenvolvedor. Até que a menina do front saiu eles começaram a ter que se virá ai falaram que trabalhar com front era difícil.  A única coisa que me motiva é que me dou bem com os donos eles confiaram em mim pq como eu era da área da saúde ninguém me queria nem para suporte.

**Comment by waldemirflj** [comment]
Complicado, já passei por essa mesma situação. Geral se esquecem que já foram "junior" e perdem a noção. Na boa @AmandaFonseca faz o seu, e já era. O reconhecimento que você precisa é o seu próprio, claro que sozinho tudo é mais  difícil.

**Comment by rubenmarcus** [comment]
Olha com 7 anos de front, e ganhando mal, porque tive atitudes erradas de confiar meu trabalho e reconhecimento em empregadores, e ter passado por situações parecidas com a sua eu recomendo uma coisa: estude sempre, e deixa esses manés pra lá. Procure uma vaga que pague melhor, e saia o quanto antes.

Mas também analise, Love Mondays e outros sites que ex funcionários falam da empresa, avalie o potencial que a empresa pode tornar pra sua carreira, porque tem empresa que pode prometer até creche pra filho, bonus em salário,etc etc e quando você vê bonus é só em hora extra e trabalho.

Eu fiquei 2 anos sem estudar JS , parte por preguiça minha, parte porque a empresa que trabalhei bloqueava npm, porque era tão burocratico pedir pro pessoal de redes que não valia.

Eu sei o que é apresentar um projeto pra gerência , que você levou um tempo elaborando e os caras não dão a mínima.

Mas vai em frente o mercado é enorme, e quem tem pro-atividade e vontade de crescer, com certeza no meio tempo se destaca mais.

**Comment by rubenmarcus** [comment]
Eu já tive empregador, que disse na minha cara, mais de uma vez: "Você não é designer, não é desenvolvedor, não é profissional, não é ninguem". E meses e anos depois veio pedir freelances meus.

Na real, uma grande parcela do mercado tem uma mentalidade bem tacanha, e se vangloria de uma posição economica e social perante os outros, usando para enaltecer o ego, mas tecnicamente se for ver são bem sofríveis.

E tem uma grande parte que também, especialmente na parte de gerência, e não formado em TI que vem de berço de ouro, e acha que tudo é facil.

Já tive um empregador, que ficava vendo walking dead, dando risada, mudando escopo de projeto todos os dias, e a cada minuto vinha analisar linha a linha de código do que estava sendo feito e perguntando o que cada coisa fazia.

É insalubre. Mas tente ser profissional, dá uma caprichada no curriculo e cai pro abraço, pq vagas tem, e o mercado só tende a crescer.

**Comment by AmandaFonseca** [comment]
@glauberramos também acho, mas eu não sou tonta hj mesmo ele fizeram essa piadinha do PHP na hora da saída e depois me deram tchau na maior cara de pau, eu fingi que não ouvi. Um montou uma tela de relatório com os grids desalinhados, imagina uma tela feia e estática típica dos anos 2000, aposto que naquele código não deve ter nenhum tag semântica tbm.

**Comment by AmandaFonseca** [comment]
@rubenmarcus obrigada pelas dicas.

**Comment by glauberramos** [comment]
@AmandaFonseca pois é, o pessoal acha que frontend é fácil, mas na hora de fazer uma interface acessível, semântica, fácil de usar, cross-browser, responsiva e bonita, ninguem consegue fazer hehehe.

**Comment by herberthenrique** [comment]
> Mas também analise, Love Mondays e outros sites que ex funcionários falam da empresa, avalie o potencial que a empresa pode tornar pra sua carreira, porque tem empresa que pode prometer até creche pra filho, bonus em salário,etc etc e quando você vê bonus é só em hora extra e trabalho.

Sempre verifique o que as pessoas falam das empresas na [Love Mondays](lovemondays.com.br) ou [Glassdoor](glassdoor.com), é um ótimo lugar para saber o que acontece dentro do local de trabalho.

E sendo bem honesto, se você quer seguir um carreira de dev e se ve presa num lugar onde trabalha como suporte, saia já dai! Estude por conta, tente algumas vagas e faça uns desafios pra se aprimorar, da uma olhada nesse repositório do @LFeh: https://github.com/LFeh/frontend-challenges

Agora, quanto aos idiotas do seu trabalho... Bem, ignore. Esse tipo de pessoas não vão muito longe por pura ignorância e machismo :)

**Comment by AmandaFonseca** [comment]
É que eu não posso e nem quero expor o site que eu estou falando mas só te digo um coisa tem site aqui que ainda usa <a href=""><img src=""></a> no lugar da tag <button> hoje em dia com bootstrap, materialize, jqueryUI e outras ferramentas você precisa uma a tag img para deixar o seu botão bonitinho?

Pois é.....

**Comment by rubenmarcus** [comment]
Olha @AmandaFonseca ,as vezes ter um superior com experiência em TI, pode ajudar também. Não sei você , mas eu já tive um gerente e um chefe dono de uma startup, que só porque vendeu outra empresa por 30 milhões, e andava em bmws e etc, achava que era o Steve Jobs reencarnado, e toda semana queria chamar a equipe para palestrar sobre os livros que andava lendo.
O cara gastava 2 milhões na reforma do apartamento, mas quando pediamos devices para testar nossos aplicativos que estavamos desenvolvendo para ele, ele não comprava.

Mas o machismo em TI ainda é bem presente, mas não só isso, eu por exemplo sou uma pessoa noturna, e sempre tive problemas pra chegar e trabalhar das 9 ás 18. Mesmo batendo metas, entregando projetos, estudando por fora, muito gerente vai preferir o cara das 9 as 18.

**Comment by AmandaFonseca** [comment]
Eu fiz faculdade de Analise de sistemas  so nunca tinha trabalhando na area, entrei como estagiaria mas eles insistiam com a brincadeira de desplugar os cabos do meu computador, colocar um papel colado no meu mouse e chamar eu e o outro menino de estagiotarios a diferenca e q eu rebati, principalmente depois q descobri o lance da foto.

**Comment by rubenmarcus** [comment]
@AmandaFonseca  Love Mondays neles, e se possivel até um processo cabe

**Comment by synga** [comment]
Olha meu primeiro trampo foi no front de uma empresa onde NINGUÉM manjava de front, ou seja fui me virando. Tudo que eu aprendia a galera menosprezava, "css pra que se no C# eu tenho drag and drop pra formulario?", "HTML bem feito pra que? O usuario só quer clicar".

Haviam panelinhas e acabei até saindo por que um cara de outra área me ferrou bonito com coisas de fora do ambiente de trabalho, mas eu já estava estressado, desinteressado, desmotivado e tudo mais de ruim.

Fiquei um bom tempo em casa parado até arranjar outra coisa, nesse tempo eu estudei MUITO e hoje to num trampo que eu amo demais e que não tenho problemas.

Arranja outra coisa, independente de chefe que gosta do seu trabalho ou sei la o que, como já falaram panelinha e gente chata tem em toda empresa, mas você não é obrigada a suportar, e se conversar não deu certo só sai e vai atrás de outra coisa. Só não se desgasta por causa de trampo por que isso é um veneno. Então sai mandando currículo, cria uma conta no Medium e vê sobre o que a galera de tecnologia ta falando e recomendam de estudos (tem até um blog chamado **FreeCodeCamp** que tem um roadmap de estudos muito bom), mas mesmo assim fala com algum superior e chega peitando falando que cansou do jeito que te tratam e boa sorte, que consiga algo melhor.

**Comment by kazzkiq** [comment]
Já passei por situação muito parecida no meu primeiro emprego.

Pelo que você relatou, sem rodeios, a dica que eu tenho pra dar é: **Sai fora desse trabalho!**

Parece uma medida extrema? É pra ser! Esse tipo de atitude pode acabar te causando traumas que depois vão ser difíceis de reverter. E, pela minha experiência, as atitudes não melhoram com diálogo (na verdade, é bem provável que as piadinhas e indiretas piorem se você tentar escalar a situação).

É difícil orientar uma atitude assim tão drástica quando a gente não sabe exatamente tudo que rolou, o quanto a pessoa se sente afetada com isso, o quanto ela precisa do emprego e tal. Mas eu te garanto que arriscar procurar outro emprego é **muito, mas muito** melhor do que ficar se expondo a esse tipo de ambiente tóxico.

Mais uma vez, é difícil dizer o que se deve ou não fazer em uma hora dessas, mas se fosse eu, hoje, eu pediria demissão e relataria exatamente os motivos, os envolvidos, e como aquele ambiente faz mal para empresa como um todo (afinal, eles estão perdendo um recurso bom como você justamente por conta dessas atitudes anti-profissionais).

Ambiente de trabalho é pra se encorajar, não ridicularizar. A equipe tem que somar, não se boicotar. É claro que um ambiente sadio tem muitas brincadeiras, mas isso vem com o tempo, com intimidade. Cada um precisa conhecer os limites dos colegas, afinal isso é ser profissional, e acima de tudo, isso é viver em sociedade.

Sobre os caras zoarem as coisas que você tá estudando? Na boa... a real é que provavelmente lá no fundo eles tem medo e inveja, porque você é aplicada e corre atrás de conhecimento, e toda vez que você se destaca na empresa isso incomoda eles.

Pessoas normais ficariam felizes pela colega sendo elogiada. Pessoas aplicadas se sentiriam instigadas a também buscar mais conhecimento em busca de crescimento. Pessoas **limitadas** só conseguem fazer piadinha e mandar indireta mesmo.

Mete o pé desse lugar e vai crescer onde tenha os dois primeiros tipos de pessoas! O que não falta é empresa por aí com equipes incríveis buscando profissionais com o seu perfil pró-ativo e desbravador!

**Comment by alannaidon** [comment]
1) NUNCA pare de estudar e NUNCA deixe sua vontade de querer aprender mais, de querer se mais, sumir da tua vida, ainda mais se for por causa de invejoso. Isso tudo é INVEJA !  
2) Se possível, tenta achar um lugar melhor, com um ambiente de trabalho bom.    

> eles insistiam com a brincadeira de desplugar os cabos do meu computador, colocar um papel colado >no meu mouse e chamar eu e o outro menino de estagiotarios  
Cara, só eu acho isso um puta absurdo ? Mas, tchê ! Se é aqui na minha cidade eu já tinha arrebentado os cara a soco ou metido um processo bem bagual neles !  Onde já se viu aturar isso em ambiente de trabalho, to chocado cara, na moral...

Agora é sério, se tu puder se manter até arrumar um outro emprego, sai desse trampo !  
Ninguém merece trabalhar com gente medíocre e passar pelo que tu conta estar passando. Sério, moça. Sai dai !

**Comment by AmandaFonseca** [comment]
Quando eu passei a situacao para o dono ele disse que isso era inaceitavel e eles pararam de falar na cara agr so falam nna entrelinhas.. eu tive a certeza do machismo pq eles tbm implicam com uma moca que trabalha numa loja de cosmetico perto do escritorio ela tem  o cabelo rosa e sobrancelha rosa falam que ela parece um bicho e toda vez que passam pela loja ficam falando da menina.

**Comment by AmandaFonseca** [comment]
Eu nao acho q ela parece um bicho ela eh estilosa sempre esta bem arrumada ate pq trabalha numa loja de cosmetico ela ficam la de boa e toda vez q eles passam pela loja ficam olhando pra ela e dando risada de um jeito pra ela perceber mesmo.

**Comment by AmandaFonseca** [comment]
Obrigada pelas dicas meninos vcs sim sao maduros <3

**Comment by rkb81** [comment]
Olha @AmandaFonseca se vc precisar de um lugar bacana, estes dias eu o e o @rubenmarcus estavamos num evento de Front e os caras tavam contratando (aqui em SP, não sei se te serve), a [Lambda3](https://www.lambda3.com.br/pessoas/) e os caras são super respeitadores.

**Comment by AmandaFonseca** [comment]
@rkb81 Serve sim, tenho interesse.

**Comment by alinebastos** [comment]
Amanda, eu passei dois anos trabalhando num lugar onde eu sofria muito assédio moral. Saí de lá com depressão, me achando um nada, tô até hoje me tratando. Então meu conselho é: foge daí!!!
Já conhece o Training Center? Se não conhece, é um projeto pra comunidade se ajudar, tem mentores, grupos de estudo, ajuda para que a gente precisar na área.
Temos um slack bem movimentado, e podemos te ajudar a achar outras vagas, até pra se preparar bem pras entrevistas!
Temos um grupo só de mulheres lá dentro que só tá aumentando :)
https://github.com/training-center/sobre
Entra no nosso slack:
https://ctgroups.herokuapp.com/

**Comment by AmandaFonseca** [comment]
@alinebastos eu dar uma olhada sim obrigada pelas dicas, gostaria de crescer aonde eu estou mas estou começando a duvidar se isso vai ser possível.
Eu também participo de outro grupos de mulheres no site Meetup o JSLadies é bem legal tbm.

**Comment by alinebastos** [comment]
Que legal, eu faço parte do JS Ladies tb :)

**Comment by kvnol** [comment]
Tem muito maluco babaca na área (e é fato que para as minas é muito pior do que para os caras), nunca fui de ficar em panelinhas e, na maioria das vezes, trampava sozinho. Sem pedir ajuda, mas cobrando o que a galera tinha para fazer para que meu trampo fluísse. E outra que, algo que eu acho que pode até me prejudicar, é que sempre fui mais sério e até estourado em casos de panelinhas em casos de "tiração" eu não consigo segurar um **vai se fo$%&3r**.

**Comment by lidimayra** [comment]
É realmente complicado! Lidar com babacas é, sem dúvida, a pior parte do trabalho.

Eu também amo participar dos eventos voltados para mulheres, porque a gente continua se desenvolvendo em comunidade, mas já filtra os machistinhas que colocam tanto esforço em serem desegradáveis... em novembro, vai rolar o [Women Dev Summit](https://doity.com.br/women-dev-summit-talks#about) que vai reunir diferentes comunidades (incluindo a PHPWomen) 😉 

Tenho acompanhando muitas iniciativas de gente que tá voltando as energias pra se desenvolver com mais autonomia pra não ficar amarrada a um ambiente em que não se sente bem. O curso [Welcome To The Django](https://welcometothedjango.com.br/), do @henriquebastos tem uma pegada forte nesse sentido... aborda a parte técnica e essa parte relacionada a autonomia também, talvez seja interessante pra você! Recomendo assistir a [essa palestra](https://www.infoq.com/br/presentations/quanto-dinheiro-voce-esta-perdendo-por-nao-fazer-software-livre), que é bem legal pra ampliar os horizontes. Outra muito legal é a [Programando a Felicidade](https://www.infoq.com/br/presentations/programando-a-felicidade), do @renzon, mega interessante, uma das minhas preferidas!!

PS: eu tô aqui falando, mas eu atuo no mercado "tradicional". mas sei o tanto de babaquice que a gente esbarra no mundão corporativo e acho que é interessante considerar outras alternativas.

**Comment by AmandaFonseca** [comment]
@lidimayra vou dar uma olhada em tudo! Sobre o evento de novembro eu vou passar por um procedimento cirúrgico em Outubro se estiver recuperada vou ir sim, outra coisa vi que ele vai ser no Senai entrei no face deles para ver se eles falavam mais alguma coisa e descobri outra iniciativa legal, eles estão oferecendo cursos de Mobilie, Front-end, Back-end, e OIT de graça, você só paga uma taxa para fazer a prova ganha a bolsa segue a dica galera:

[https://www.facebook.com/senaiinformatica/posts/1568857819802126](url)

**Comment by vagnerlucas** [comment]
E eu aqui incentivando a colega (única mulher do setor) do suporte a virar desenvolvedora, rs.
@AmandaFonseca, você está no caminho certo. Faça o dever de casa do iniciante, bole um portfólio, invista em conhecimento e se especialize. Aproveita essa gente legal aqui e mantenha o foco!

Infelizmente o preconceito vai existir até quando você estiver mais preparada, então você não pode deixar isso te abater.

**Comment by lidimayra** [comment]
> eles estão oferecendo cursos de Mobilie, Front-end, Back-end, e OIT de graça, você só paga uma taxa para fazer a prova ganha a bolsa

ai que dica linda!! isso eu não tinha visto, obrigada por compartilhar, vou passar adiante também!! :heart:

**Comment by vitocaio** [comment]
@AmandaFonseca Só gostaria de dar uma dica, não desperdice seu tempo, na nossa area isso é o bem mais valioso, ao meu ver, você esta desperdiçando seu tempo nessa empresa, empregadores prometem mundos e fundos, mas você nunca sera prioridade, meu conselho, acesse www.apinfo.com.br e manda bala.

**Comment by CristopherJonas** [comment]
minha fia, sai dae. 
Procure uma outra empresa, uma capaz de te valorizar e te fazer crescer junto com ela.

**Comment by dougaraujos** [comment]
No ambiente corporativo, principalmente na nossa área, é comum encontrarmos pessoas imaturas pela pouca idade e/ou pela dificuldade de manter relações interpessoais agradáveis. 

Se posso contribuir, sugiro que repense nas prioridades a curto, médio e longo prazo sobre sua carreira e objetivos pessoais e quanta resiliência você está preparada para atingir essas metas. Ás vezes o que te prende nessa situação não seja compensatório pelo desgaste emocional diário e outras escolhas possam te favorecer muito mais como investimento na sua vida.

De qualquer forma, é triste saber que esse tipo de comportamento seja frequente em um ambiente que passamos a maior parte da nossa vida =/

**Comment by AmandaFonseca** [comment]
Obrigada pelas dicas pessoal eu preciso terminar o meu portfólio logo

**Comment by daniellucindo** [comment]
Primeiramente parabéns pelo seu empenho e você tem muitas conquistas...
Bem complicado, que tem muita gente que é mlandro quando esta em bando, no mundão vira bundão...

Continue com seus estudos e progresso!

**Comment by henriquebastos** [comment]
Obrigado pela lembraça, @lidimayra! ^_^

@AmandaFonseca o que funciona pra mim é buscar interagir com pessoas que fazem o que eu quero/gosto de fazer. Se dentre as pessoas que trabalham com você existir alguém, legal. Se não existir, eventos e cantos digitais não faltam para conectar as pessoas.

Sobre o trabalho em si. Não me sinto a vontade pra mencionar nada em específico por falta de contexto. No entanto, na minha experiência, estabelecer limites é sempre saudável. E pode ser feito de forma civilizada e serena.

O meu viés é sempre pensar no que **eu** posso fazer para melhorar a situação em vez de tentar mudar os outros. Certamente há limites nisso e é importante não negligenciar quando eles surgem. A arte, na minha opinião, é buscar observar e se antecipar para se posicionar melhor, endereçando os conflitos e com sorte, evitando confrontos.

[]'s, HB.

**Comment by MendesGabriel** [comment]
@henriquebastos  por aqui... esse fórum está de encher os olhos.

**Comment by gss-patricia** [comment]
@AmandaFonseca, já passei por isso!

Era uma multinacional e só tinha babacas na minha área, o gestor era um amor, mas não fazia nada diante das bizarrices e comentários que os otários faziam. Continuei estudando e estudando, como eles eram babacas, não perdia meu tempo com eles, logo comecei a mexer os pauzinhos, queria sair de lá, foquei em procurar um desafio, um desafio que mesmo com medo eu iria, caso me aceitasse e não foi muito difícil, logo encontrei. Após 6 anos que sai de lá, vejo onde estou e estou muito feliz, pq assim como fizeram com vc... (de falar que não pode se chamar de desenvolvedora), desenvolvedora de software é minha profissão, onde ganho o pão!!! E eles, eles eu sei onde estão, no mundo medíocre deles, não pq o emprego ou empresa que eles trampam é medíocre, medíocre pq eu lembro deles assim, para eles limparem a imagem deles perante mim, muitas atitudes boas eu teria que ver neles.... e nem sempre a gente tem essa oportunidade de ver se a pessoa ainda é um babaca ou se é gente bacana... Eqto isso nao acontece, sempre serão uns babacas!

Ahh o mundo da TI é pequeno, qualquer dia esbarro neles por ai...

Continue no seu caminho, não deixe ngm te derrubar... Não se prenda aos donos, vc é dona de vc, vc pode ir onde quiser.
Bjssss

**Comment by AmandaFonseca** [comment]
@gss-patricia <3

**Comment by mathvbarone** [comment]
@AmandaFonseca é foda essa parada, você passa a maior parte do seu dia dentro do ambiente de trabalho, convive com os colegas de trabalho mais tempo do que com a familia, namorado(a) e amigos. Trampando como Dev eu nunca tive problema, porém, ano passado resolvi tentar a vida morando nos EUA, e lá trabalhava como instalador de piso (carpete, madeira, etc). E foi onde tive a experiência de trabalhar com pessoas enchendo o saco o dia inteiro, fazendo chacota de você, e essas coisas que você citou no seu desabafo.

Olha, o que eu posso te falar é pra simplesmente confiar no teu taco, seguir focada no seu objetivo, e simplesmente IGNORAR essa galera. Quando mais você demonstrar que se importa, mais eles vão querer te importunar. Então faz cara de paisagem e segue estudando.

Tenha certeza que daqui um tempo, quando você olhar pra tras, vai perceber que eles não eram absolutamente nada, e que você sempre foi melhor que eles.

Me coloco à disposição caso precise de ajuda com algo beleza?

Segue o jogo!

Um abraço!

**Comment by AmandaFonseca** [comment]
@mathvbarone obrigada

**Comment by wmsbill** [comment]
@AmandaFonseca Eu ia te escrever umas palavras sobre o que eu acho dessa situação mas @kazzkiq disse tudo. Ninguém pode nem deve tirar o prazer que você tem de fazer o que você faz. Arranje outro lugar, dê o feedback para o seu chefe e vaze dai.

**Comment by kvnol** [comment]
Legal já até linkar aqui o [Dev na Estrada sobre Ambiente: Panelinha](http://devnaestrada.com.br/2017/09/08/ambiente-panelinha.html) justamente por conta dessa issue. :tada:

**Comment by AmandaFonseca** [comment]
@LFeh Gostaria de agradecer por todo apoio galera.
Mas eu gostaria de deixar de saber se é possível excluir essa Issue pois  por enquanto ainda não arrumei nenhum outro para trabalhar e acho que se alguem do meu serviço ler o conteúdo dessa Issue a conversa pode chegar errado no ouvido do meu chefe e me causar mais problemas ainda.

**Comment by AmandaFonseca** [comment]
No dia que abri essa Issue estava muito estressada e não pensei nisso hoje vejo que quanto mais discreta eu for melhor.

**Comment by lidimayra** [comment]
Até onde eu sei (posso estar errada), deletar issue não rola @AmandaFonseca 😞 
Apenas abrir e fechar...

O que você pode fazer é editar os seus comentários, apagando o conteúdo...

**Comment by AmandaFonseca** [comment]
@lidimayra  Então  vou alterar o titulo e conteúdo do desabafo kkkkk obrigada

**Comment by kvnol** [comment]
Não fecha a issue nao, poxa. O conteúdo pode servir para outras pessoas.

**Comment by AmandaFonseca** [comment]
@kvnol pode sim mas por enquanto me atrapalha porque eu não abri com um perfil anônimo se quiser pode abrir futuramente desse modo.

**Comment by kivervinicius** [comment]
Já entendi o que ta rolando :(

**Comment by brunooomelo** [comment]
to  boiando!

**Comment by eduardojmatos** [comment]
@AmandaFonseca comentamos algo meio por cima do que a galera aqui da issue comentou num episódio do DevNaEstrada: http://devnaestrada.com.br/2017/09/08/ambiente-panelinha.html

**Comment by alinebastos** [comment]
@AmandaFonseca, entendo o teu sentimento, eu tb iria querer deletar a issue qdo me desse conta que qualquer um pode ver =/
