### ISSUE TITLE
Graduação tecnológica 

### ISSUE THREAD

**Issue by gmmoraes** [frontendbr/forum#718]
Boa noite galera.

Eu estou interessado em cursar uma graduação tecnológica em análise de sistemas para poder aumentar minhas chances de conseguir um emprego na area dw T.I  mesmo que a principio não seja uma vaga de desenvolvedor, porém eu estou com receio de que o mercado veja esse diploma como inferior em relação aos diplomas de graduação por isso eu queria pedir a ajuda de vocês pra saber qual é a opinião de vocês em relação aos diplomas tecnologicos e se vocês acham que eles são vistos como inferiores quando comparados com um diploma de bacharelado pelo mercado ?

**Comment by felipeuntill** [comment]
Existem várias issues em abertas que abordam esta mesma dúvida, seguem:

#518 - Curso Tecnólogo
#509 - Diploma VS Portifólio
#654 - Voltar para faculdade ou focar em um curso
