### ISSUE TITLE
Gerar PDF dinâmico com PHP ou JavaScript

### ISSUE THREAD

**Issue by deppbrazil** [frontendbr/forum#720]
Fala galera, vcs já precisaram criar uma aplicação para gerar PDF dinâmico a partir do HTML? 

Ou seja temos Webaulas em html e precisamos de um botão que quando clicado ele pegue todo conteúdo da Webaula (texto + imagens) e monte um doc PDF para impressão... 
___
# Achei 2 soluções: #
* #### Uma com JavaScript porém ele retorna um PDF como imagem (printScreen da tela) ####

* #### Outra com PHP, usando a classe mpdf ele retorna o conteúdo html  em um doc PDF com textos selecionaveis, mas adequado para leitores de telas....mas tenho que jogar todo conteúdo html que quero retornar dentro do script em PHP, como a volumetria de Webaulas é grande aqui fazer manual colocando todo html dentro do PHP se torna meio improdutivo aqui ####
___
Tem alguma forma mais dinânimca para esse tipo de aplicação?

**Comment by AmandaFonseca** [comment]
Ac

**Comment by LFeh** [comment]
Oh só https://coderwall.com/p/5vmo1g/use-phantomjs-to-create-pdfs-from-html

Já usei e recomento

**Comment by vicainelli** [comment]
Já usei essa daqui, aliás, to usando ainda.

http://www.fpdf.org/

**Comment by suissa** [comment]
Eu já usei um que converte HTML para PDF e outro de MD para PDF, no npm tem vários módulos para isso ;)

[https://www.npmjs.com/package/electron-pdf](https://www.npmjs.com/package/electron-pdf)
[https://www.npmjs.com/package/html5-to-pdf](https://www.npmjs.com/package/html5-to-pdf)
[https://www.npmjs.com/package/phantom-html2pdf](https://www.npmjs.com/package/phantom-html2pdf)

**Comment by felipejsm** [comment]
Também estive na mesma situação e esse atendeu bem as minhas necessidades:

[http://www.cloudformatter.com/CSS2Pdf.APIDoc.Usage](http://www.cloudformatter.com/CSS2Pdf.APIDoc.Usage)

**Comment by loracsilva** [comment]
Essa solução atendeu bem as minhas necessidades.

http://pdfmake.org/


*Caroline Silva Rodrigues*
CSM,CSPO <http://www.scrumalliance.org/profiles/355115-caroline-s-rodrigues>
------------------------------
*Cel:  *+55 85 98709-6160









2017-09-13 9:18 GMT-03:00 Felipe Moysés <notifications@github.com>:

**Comment by Raffesmind** [comment]
Apesar de não recomendar muito, consegui resultados com o: https://wkhtmltopdf.org/ 
Mas acho que as opções com Phantom são mais fáceis de serem implementadas (:

**Comment by deppbrazil** [comment]
Valew galera vou testar qual dessas opções funciona legal na minha aplicação! 
# =)

**Comment by giioohbernini** [comment]
Na época me ajudou, então vou deixar ai mais um para a lista: [DomPDF](https://github.com/dompdf/dompdf), e é em PHP!

Fiz esse repo [aqui](https://github.com/giioohbernini/dompdf) com uma explicação bem básica e também tem uma [demo](https://dompdf.net/examples.php) que os caras da lib disponibilizam.

:+1:

**Comment by osmarcs** [comment]
Tem um que vi semana passada da própria Google,  [Puppeteer](https://github.com/GoogleChrome/puppeteer) .

**Comment by pedroguilhermelima** [comment]
Eu apenas uso Jquery e API Chrome do Google.  

index.html
~~~~~
<button id="gerar"> Gerar</button>
~~~~~

arquivo.js
~~~~~
$('gerar').click(function () {
   window.print()
  });
~~~~~

Depois de abrir uma janela é só clicar em salvar o arquivo como PDF. ;D

**Comment by pedroguilhermelima** [comment]
Ou, você pode usar isso https://github.com/JeyDotC/md-pdf.js
Que converte do markdown para PDF. ;D
