### ISSUE TITLE
Erro ao abrir WEBCAM HTTP no Chrome

### ISSUE THREAD

**Issue by VitorBueno** [frontendbr/forum#722]
Olá,

Estou com um dificuldade, tenho uma implementação em PHP,HTML e Javascript que usa uma webcam, no google chrome antes estava ok, mas algum tempo atras começou um problema, quando clico para abrir essa webcam fica branco, isso apenas quando o link Inicia em HTTP, quando inicia em HTTPS está Ok, gostaria de saber se alguém já passou por isso, ou algo parecido, relacionando a permissões quando e HTTP ao invés de HTTPS, e como solucionou ?

![image](https://user-images.githubusercontent.com/31930562/30386308-e4bdf822-987f-11e7-9a6a-2532b021c8f1.png)

![image](https://user-images.githubusercontent.com/31930562/30386326-efcc8ac6-987f-11e7-9a0c-6776da6a2aac.png)

**Comment by munizart** [comment]
> tenho uma implementação em PHP,HTML e Javascript

Cara, na verdade parece que você ta usando Flash player, como mostra no print.
Da pra tentar usar a WebAPIs. A MDN tem um tutorial muito bom sobre isso https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos

**Comment by VitorBueno** [comment]
@munizart  Então cara, parece que meu problema é com o Protocolo HTTP, quando utilizo o HTTPS ele funciona sem problemas, no caso esta acontecendo isso apenas no chrome, e o link que os clientes acessar é o http+link do sistema, quando mudo de http para https ele funciona, porém são muitos clientes, fica inviável explicar um a um para fazer esse procedimento, tentei este link, realmente é muito bom, porém aconteceu a mesma coisa, gostaria de saber se tem algo que eu possa fazer no navegador, pois apenas nele esta acontecendo isto, ou se teria alguma outra opção que não fosse barra pelo protocolo :( 

![image](https://user-images.githubusercontent.com/31930562/30391911-84737ac0-9891-11e7-9e6c-947f6bc7c84d.png)

**Comment by gabrieldarezzo** [comment]
>  quando mudo de http para https ele funciona

Você pode forçar um redirecionamento nesse caso.

Está usando qual servidor ai?
Apache?
NgIX?


De qualquer forma você tem a opção de fazer com o JS tmb, se liga:
```js
if (location.protocol != 'https:') {
	location.href = 'https:' + window.location.href.substring(window.location.protocol.length);
}
```

**Comment by VitorBueno** [comment]
@gabrieldarezzo  Legal Cara, vou usar esse mesmo, valeu 👍
