### ISSUE TITLE
Oportunidade para FrontEnd em Barcelona

### ISSUE THREAD

**Issue by italomouzinho** [frontendbr/forum#727]
Fala pessoal!

**Queria começar pedindo imensas desculpas se este post é off topic e entendo se os moderadores quiserem remove-lo ou talvez me dar um toque para colocar em algum outro lugar.**

Eu sou consultor de posições de TI aqui em Barcelona e estamos com algumas oportunidades que dão _**sponsorship**_ (A companhia te paga a passagem e te da o visto por tempo indeterminado) para cá.

Uma delas é para um **Senior FrontEnd developer**. Eles estão procurando um mestre de Javascript, portanto noções avançadas (não só de libraries e frameworks) de JS são uma grande vantagem. Dito isto, eles estão trabalhando com Angular 1 e estão em processo de analise se migran para Agular 2(4) ou React. Ingles avançado (boa comunicação, não precisa ser absolutamente fluente) e/ou Espanhol. 

Bonus points: AngularJs, NodeJS, Jasmine/Mocha, Grunt/Gulp, npm.

De novo, se for o local errado para isso eu peço desculpas aí galera! Com a possibilidade de buscar profissionais em qualquer lugar do globo para esse cliente eu puxo a brasa para minha sardinha e aponto para profissionais brasileiros porque sei da qualidade do nosso pessoal!

Quem tiver interesse é só dar um toque: italo@akuaro.com ou meu [Linkedin](linkedin.com/in/italomouzinho).

PS: Se quiserem ajudar brothers devs tambem tenho Sr. Backend - Java (Barcelona), Backend Ruby (Austria), e Sr. iOS (Austria).

Abração!

**Comment by lucasbento** [comment]
@italomouzinho: abre uma issue no https://github.com/frontendbr/vagas, repositório específico de vagas de front-end.

**Comment by italomouzinho** [comment]
@lucasbento Perfeito Lucas! Obrigadão meu caro! Fecho esse aqui então?

**Comment by lucasbento** [comment]
@italomouzinho: acredito que sim!
