### ISSUE TITLE
BEM - Nomeação de components

### ISSUE THREAD

**Issue by paulinhoerry** [frontendbr/forum#731]
Fala galera, queria saber como vocês nomeiam os elementos filhos dos components utilizando a metodologia BEM. Estou na dúvida se é melhor inserir uma classe e estilar ela ou jogar o estilo direto nos elementos. Em qual caso vocês acham que deixa o código mais limpo?

```
.product { 
 .product__box {
    .product__title { /* estilo aqui*/ }
 }
}
```

ou 

```
.product { 
 .product__box {
    h4 { /* estilo aqui*/ }
 }
}
```

**Comment by pietrobp** [comment]
Segundo o RSCSS:

Use classnames whenever possible. Tag selectors are fine, but they may come at a small performance penalty and may not be as descriptive.

.article-card {
  > h3    { /* ✗ avoid */ }
  > .name { /* ✓ better */ }
}

mesmo sendo de outra metologia , o que eles falam faz sentido, usar a classe deixa mais entendivel hahahah

**Comment by kvnol** [comment]
Discutimos sobre BEM na issue #721.

**Comment by mahenrique94** [comment]
Eu utilizo apenas classes, e para cada nível adicione um _

```
.elemento
    &__filho
        &___outroFilho
```

E no seu caso como trata-se de um componente eu adicione o *namespace* `c`

```
.c-elemento
    &__filho
        &___outroFilho
```

**Comment by luisfmsouza** [comment]
Eu também prefiro usar classes, mas evito aninhar demais elas. Sempre que possível, deixo com apenas um nível de profundidade. Mais ou menos assim:

```
.product { 
  &__box {...}

  &__title {...}
}
```

**Comment by paulinhoerry** [comment]
Então galera, deu pra ter uma boa ideia de como organizar aqui. Vi na issue #721 uma explicação bem maneira que o @LFeh que seria aninhar como você falou, @luisfmsouza .

**Comment by LFeh** [comment]
@paulinhoerry complementando

[Evite, evite mesmo, estilizar componentes. Use classes](https://www.felipefialho.com/blog/2016/porque-usar-classes-para-estilizar-elementos)

**Comment by victorsilent** [comment]
Eu ja tinha lido a issue que citaram mas não tinha visto esse link do @LFeh, finalmente as coisas que faço meio com o pé atrás foram consolidades o/
Eu escrevo meu CSS da forma como você citou no ultimo exemplo, mas a parada de ficar redundante me deixa um pouco neurado, mas é isso mesmo, faz sentido e funciona :p
