### ISSUE TITLE
Algum de vocês conhecem Riot.js ?

### ISSUE THREAD

**Issue by realmocaccino** [frontendbr/forum#734]
Estou montando um styleguide com esse framework.
Ele dispõe de uma abordagem simples e excelente leitura de código.
O Vue.js e React fornecem mais soluções.
Mas o Riot.js está atendendo bem minhas necessidades.

https://github.com/riot/riot

**Comment by expalmer** [comment]
Sim, acho muito legal testar e ver o código de pequenos frames...
[MoonJs](http://moonjs.ga/)
[Choo](https://choo.io/)

**Comment by Cleysonlb** [comment]
Esse MoonJS me lembra muito o VueJS

**Comment by leandroruel** [comment]
quando Li Riot.js ja pensei em League of Legends... vai entender.

**Comment by bernardodiasc** [comment]
@leandroruel un dos escritórios mais animais que ja tive oportunidade de conhecer https://twitter.com/bernardodiasc/status/709065668369383424

**Comment by leandroruel** [comment]
@bernardodiasc caraca, como você conseguiu?

**Comment by leandroruel** [comment]
@LFeh o cara fechou a issue denovo...

**Comment by lgustavoms** [comment]
Sim.

Os últimos 4 comentários não enriqueceram em nada o tópico.

**Comment by bernardodiasc** [comment]
@lgustavoms verdade, mas deixa aberta ai. Eu conheço Riot.js, cheguei a ler os docs alguns anos atras e queria muito ter tido tempo pra aprender e usar em algo. Acabei aprendendo React e outras coisas, mas ainda assim acho que Riot vale a pena tentar. :)

**Comment by didiraja** [comment]
@leandroruel Já eu, li Riot e já pensei que era alguma voltada pra política e manifestacões
