### ISSUE TITLE
Sobre desenvolvimento Frontend atualmente, pergunta básica para quem trabalha na área

### ISSUE THREAD

**Issue by TechSlave** [frontendbr/forum#738]
Pessoal, tenho uma pergunta bem simples e básica, mas que pra mim que estou há uns anos fora dessa área tem sido... estranho de entender.

Há muitos anos, ali na época em que o Tableless começou a aparecer, eu escrevia meus htmls e phps e subia pelo FTP, ou já fazia isso salvando direto no host mesmo. Hoje em dia, com Node.js pra cá e Github pra lá e eu tentando voltar pra essa área e me reciclar, eu percebi que, com estes frameworks todos, foi-se o tempo de incluir um jquery.js na pasta script e tá tudo certo.
Percebi isso tentando usar o Angular no trabalho, onde não posso instalar nada e preciso do Node.js pra "instalar o Angular", acabei deixando pra fazer em casa, mas fiquei com isso na cabeça.

A pergunta é a seguinte: pra quem trabalha na área de fato, vocês desenvolvem SEMPRE localmente e depois sobem ou existe outra forma? Eu não consigo simplesmente abrir um bloco de notas e sair codando como fazia antigamente, preciso sempre setar um ambiente de desenvolvimento se quiser estudar os frameworks atuais?

Me perdoem pela pergunta idiota =D

**Comment by loracsilva** [comment]
Eu penso da seguinte forma, tudo depende do seu objetivo...
A forma como as coisas eram feitas antigamente não deixaram de funcionar, assim se vc programar arquivos em php linkando seu js no HTML e subir num servidor pelo FTP vai funcionar. 

Mas, se você quer se manter atualizado e por dentro das novas tecnologias, sim...é sempre bom vê o que tem de novo no mercado e como as coisas funcionam.

Na área de TI vivemos um eterno aprendizado, onde novas tecnologias surgem todos os dias, a maioria delas melhoram sua produtividade e ajudam bastante, por isso sempre vejo como válido qualquer conhecimento....ai cabe a você definir se vai aplicar esse conhecimento no seu dia-a-dia.

**Comment by TechSlave** [comment]
Olá, obrigado pela resposta!

Sim, meu objetivo é me atualizar e entrar de cabeça na área, de vez, a minha dúvida é mais com relação ao estudo, pelo que eu entendi eu só consigo usar estas tecnologias em um ambiente pré-implementado, certo?
Contratei uma hospedagem web pra jogar meus estudos e fuçar no trabalho (que não é dev) e reparei que eu não consigo enfiar o Angular lá, pois não tem Node.js, neste caso eu preciso especificamente de um host preparado pra Node?

**Comment by Raffesmind** [comment]
> A pergunta é a seguinte: pra quem trabalha na área de fato, vocês desenvolvem SEMPRE localmente e depois sobem ou existe outra forma? 

Pessoalmente acho que é bom você desenvolver localmente para ter um melhor controle do que está acontecendo com seu código e ambiente, mas não é a única forma de você começar a desenvolver, você pode usar alguma solução como o https://c9.io/ para ter um ambiente pré-configurado para você focar mais na prática do código :)

> Eu não consigo simplesmente abrir um bloco de notas e sair codando como fazia antigamente, preciso sempre setar um ambiente de desenvolvimento se quiser estudar os frameworks atuais?
Depende do que queira codar direto. Angular nas primeiras versões tinham um link que você poderia incluir no seu html para fazer isso, react também possuí. Só que uma coisa que você pode se atentar e pensar nessa "complexidade atual"é que o pensamento inclui a questão de automatização de tarefas e tirar do dev alguns trabalhos manuais, como controlar as dependencias do projeto (vulgo, garantir que o Jquery esteja sempre atualizado, etc...)

> Contratei uma hospedagem web pra jogar meus estudos e fuçar no trabalho (que não é dev) e reparei que eu não consigo enfiar o Angular lá, pois não tem Node.js, neste caso eu preciso especificamente de um host preparado pra Node?
Depende de como está sendo o foco do estudo/como está sendo produzida sua aplicação, pois se há algum processo que precisa fazer o build do código no seu local, então precisará ter o serviço configurado no servidor. Uma dica para você que está estudando apenas e quer economizar, pode usar o Heroku, que facilita bastante nessa hora, é gratuito e tem integração com o git e o c9

Espero que tenha ajudado um pouco (:

**Comment by TechSlave** [comment]
esse Heroku é parecido com o Openode, mas mais simples, bem o que eu preciso ( já que não entendi muito bem o Openode)

Muito obrigado, era tudo o que eu precisava! Vou ver se minha conta do cloud9 ainda existe haha

**Comment by LFeh** [comment]
> A pergunta é a seguinte: pra quem trabalha na área de fato, vocês desenvolvem SEMPRE localmente e depois sobem ou existe outra forma? Eu não consigo simplesmente abrir um bloco de notas e sair codando como fazia antigamente, preciso sempre setar um ambiente de desenvolvimento se quiser estudar os frameworks atuais?

Depende.

Se você está num projeto que precisa de escala e engenharia aplicada, sem dúvidas é inviável (e não recomendado) começar um projeto, sem um puta estudo do workflow, ferramentas e tecnologia que vai ser usada.

Porém, claro, em um projeto estático, não tem necessidade de criar um ambiente de desenvolvimento. Mas sem dúvida ajuda e economiza muito trabalho, especialmente se você pretende entregar projetos performáticos, com assets otimizados e etc.

No meu caso, tenho um boilerplate, (Kratos](https://github.com/LFeh/kratos-boilerplate) que criei para usar em projetos estáticos, não fico configurando toda hora. De tempos em tempos atualizo e uso quando for preciso. Portanto, não gasto tempo nenhum depois da primeira vez que fiz essa configuração.

Já em projetos que existem lógica e integração, analiso cada caso separadamente, para escolher as tecnologias junto com a equipe.

**Comment by gabrieldarezzo** [comment]
Alguns pontos que pode ajudar:


> Contratei uma hospedagem web

A maioria das hospedagens mesmo compartilhada libera um ssh do linux, isso permite fazer controle de versionamento (git/svn) e usar [composer](https://getcomposer.org/doc/00-intro.md) (seria o 'npm' do php) tranquilamente...

> Contratei uma hospedagem web pra jogar meus estudos e fuçar no trabalho (que não é dev) e reparei que eu não consigo enfiar o Angular lá, pois não tem Node.js

O Angular ( 2x + ), gera no fim das conta uma especie de 'jquery.min.js', assim você pode fazer o deploy sem a necessidade de ter 'node' na sua hospedagem....
https://angular.io/guide/deployment


Não se assuste com versionamento, ele é seu amigo e vai facilitar muito a sua vida.
Com alguns comandos você faz milagre, a proposito recomendo:
https://www.udemy.com/git-e-github-para-iniciantes/

Ps: caso necessite de um repositório privado e gratuito, [BitBucket ](bitbucket.org)é uma ótima opção.

Já que você é da velha guarda....

O @leandrooriente tem um [post ](https://leandrooriente.com/como-me-tornar-um-desenvolvedor-front-end/) bem bacana

**Comment by TechSlave** [comment]
@gabrieldarezzo peguei esse curso de git há algum tempo, mas não fiz ainda, vou fazer, até agora só sei a teoria...

Vou ver se acho um terminal no meu host, isso vai ajudar bastante, obrigado pelas informações!
