### ISSUE TITLE
Front End Stack - Quais caminhos posso seguir

### ISSUE THREAD

**Issue by Cleysonlb** [frontendbr/forum#75]
Todos nós sabemos que no mundo do front existem diversas ferramentas, tecnologias, metodologias etc.
Gostaria de trazer a discussão de quais caminhos podemos seguir no meio profissional, qual "combo" de tecnologias podemos aprender e quais estão bombando no mercado

**Comment by afonsopacifer** [comment]
Opa,
Eu cheguei a apresentar em alguma faculdades aqui no Rio a talk **Fron-End no mundo real**,
com o objetivo de tentar levar um pouco da nossa realidade para a galera que ainda não trampa e só tem a facul como referência..

Ai os Slides, talvez ajude :)

https://speakerdeck.com/afonsopacifer/fron-end-no-mundo-real

**Comment by Cleysonlb** [comment]
Boa @afonsopacifer !!!!!!!!!! :D

**Comment by LFeh** [comment]
Fala @Cleysonlb, na issue #54, o pessoal mostra um pouco do workflow e as ferramentas que estão utilizando.

Como bem disse o @afonsopacifer, Workflow é uma coisa muito pessoal e pode inclusive variar muito dependendo do projeto.

Mas recomendo você criar pelo menos um coding-style pra você seguir, tipo [esse meu](https://github.com/LFeh/coding-style)(desatualizado). Já ajuda muito e os padrões em tese, deveriam ser usados sempre.

**Comment by Cleysonlb** [comment]
Boa @LFeh  curti esse coding-style, vou implementar no meu workflow!!
