### ISSUE TITLE
Menu lateral flexivel com CSS

### ISSUE THREAD

**Issue by grodrigues** [frontendbr/forum#758]
Boa Tarde como eu faço para deixa o menu no meio do elemento com css, como está nesse menu lateral ?
Quando reduz tela ele acompanha.

https://undsgn.com/uncode/homepages/portfolio-photographer/

**Comment by kvnol** [comment]
Dá pra fazer com `text-align: center` e com flexbox `justify-content: center`.

**Comment by grodrigues** [comment]
Muito Obrigado @kvnol.
