### ISSUE TITLE
Internet Explorer a saga continua...

### ISSUE THREAD

**Issue by simaodeveloper** [frontendbr/forum#76]
Acabei de encontrar um problema no IE10 meus amigos, isso mesmo "10", quando se coloca
```css
background-color: transparent 
``` 
em uma ancora (tag A), o mesmo perde toda a àrea de clique, como se nem estivesse ali, resolvi adicionar qualquer cor mais opacidade: 

```css
background-color: black 
opacity: 0 
```

Vocês com certeza se encontraram em várias situações com esse nosso amigo, compartilhe aqui os problemas que encontraram e sua solução o/ @fdaciuk @vitorbritto @LFeh

**Comment by LFeh** [comment]
@simaodeveloper Resolveu o problema?

**Comment by simaodeveloper** [comment]
Não achei que esse caso era relevante como exemplo, mas acho legal criarmos um tópico para algumas soluções em cima do IE, provavelmente vai ajudar bastante o pessoal.

**Comment by LFeh** [comment]
Pode criar uma issue se quiser :)
