### ISSUE TITLE
Qual é o estado atual do Web SQL?

### ISSUE THREAD

**Issue by RatoX** [frontendbr/forum#760]
Eai negada,

Estou trabalhando em uns problemas onde a ideia de se ter um Web SQL rodando bateu na minha cabeça, ai eu fui procurar a [especificação](https://www.w3.org/TR/webdatabase/) e achei esse aviso nela: `Beware. This specification is no longer in active maintenance and the Web Applications Working Group does not intend to maintain it further.`

Alguém sabe dizer o por que dessa especificação ter morrido? E se temos alguma outra alternativa?

**Comment by kivervinicius** [comment]
IndexedDB melhor alternativa! Talvez considere utilizar a biblioteca localForage https://github.com/localForage/localForage da mozilla, utilizo a muitos anos e tem me servido muito bem.
