### ISSUE TITLE
Como aprender JS

### ISSUE THREAD

**Issue by romulosousa27** [frontendbr/forum#769]
Quero aprender JS, queria umas dicas para aprofundar o meu conhecimento.

Libs mais usadas e tal. 

vlw!

**Comment by ewerto0n** [comment]
Tem uma galera na comunidade aqui com bom conteúdo. Segue a dica de [ouro](https://www.felipefialho.com/blog/2016/do-zero-a-heroi-do-front-end-parte-1), tradução do @LFeh. Se eu tivesse lido isso antes, seria bem melhor.

**Comment by calaca** [comment]
Além da dica do @ewerto0n, aqui vão mais duas:
- [Front-End Developer Handbook 2017](https://github.com/kvnol/front-end-handbook-2017)
- [freecodecamp](https://www.freecodecamp.org/) (excelentes exercícios para fixação)

**Comment by kvnol** [comment]
E aí, mano. Na issue #270 temos um roadmap sobre por onde ir no JavaScript.

**Comment by AlexsandroSA** [comment]
Aprender qualquer linguagem de programação é teoria e muita, muita prática!

Minha sugestão é que você identifique a sua melhor forma aprendizado e seja feliz. Eu gosto muito de livros e desafios

__Livros__:
 - PT-BR [You-Dont-Know-JS](https://github.com/cezaraugusto/You-Dont-Know-JS)  (muito bom)
- [http://eloquentjavascript.net/](http://eloquentjavascript.net/)

__Desafio__:
 - [CodeWars](https://www.codewars.com) - (excelentes exercícios para fixação)

**Comment by LFeh** [comment]
Tem várias issues sobre o tema

#270 
#563 
#229

**Comment by romulosousa27** [comment]
Valeu pessoal!
