### ISSUE TITLE
Crawlers - afinal é crime?

### ISSUE THREAD

**Issue by kivervinicius** [frontendbr/forum#773]
Dúvida em geral, juridicamente alguém já foi penalizado por raspar sites alheios? Caso eu queira agrupar informações de outros sites em um lugar só, como posso ser penalizado? Qual a forma certa em fazer isso?

**Comment by fabiomirandaa** [comment]
Creio que você agrupar informações privadas, aí sim você tem de enfrentar alguma penalidade.Enquanto forem informações públicas, está  de boa.

**Comment by caiogaspar** [comment]
Se está disponível na internet sem nenhum tipo de autenticação (bloqueio de segurança), então é público e você pode pegar essas informações sem nenhum problema. 
Existe um único porém nesse meio, certas páginas na internet que não querem ter seus conteúdos acessados por bots, então pra isso criaram uma metatag pra [robots](https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag?hl=pt-br#diretivas-de-indexao-e-veiculao-vlidas). 
Um crawler bem intencionado de maneira geral deve respeitar o que está configurado nessa meta tag.

**Comment by onlurking** [comment]
Tem de ver se o conteúdo possui alguma licença ou se você não está infringindo os termos de uso do site por exemplo, o problema não é o ato de crawling em si, mas sim o que você faz com o conteúdo.

Mas tem alguns pontos éticos, como limitar o número de requests por segundo(para não causar DoS) e respeitar o robots.txt do site.

Como já dizia essa campanha da EFF:<br>
![](https://daniel.haxx.se/blog/wp-content/uploads/2016/10/wget-is-not-a-crime.jpg)

**Comment by kivervinicius** [comment]
Show galera, então minha intenção seria agregar vários sites de conteúdo de entretenimento da minha cidade e disponibilizar em um app, tenho a intenção de colocar o link para os sites de origem mas achei meio complicado ter que pedir a permissão de todos donos de estabelecimentos por isso a pergunta.

**Comment by suissa** [comment]
Se for então eu estou fudido ahahahahaha

Tenho crawler pra baixar musica e video pelo terminal, alem dos comuns para dados.

**Comment by suissa** [comment]
E os mais legais são bem aqueles que tem proteções ou N passos até chegar nos dados desejados.

Uma dúvida que eu tenho, se eu pegar dados de um sistema onde eu precisei logar antes e tal, mas não existe nenhum termo de privacidade dizendo que você não pode pegar esses dados de forma externa, sendo assim é de boas né?

Sei que se existir um Termo para isso dai zica o bonde.

**Comment by bernardodiasc** [comment]
O cache do google seria ilegal se nao pudesse.

**Comment by kivervinicius** [comment]
@suissa já fiz um crawler para extrair dados da receita e inep, possui autenticação mas o usuário fornece os dados. Nestes sistemas não há nenhuma informação que são para uso somente visual, kkk espero que nada de errado então.

**Comment by suissa** [comment]
@kivervinicius Já fiz um pra pegar processo ehehhee, esse foi beeem chato

**Comment by lidimayra** [comment]
O livro [Raspagem de Dados Web com Python](https://novatec.com.br/livros/web-scraping-com-python/) contém um apêndice bem legal dedicado exclusivamente a questões relacionadas aos aspectos legais e éticos do web scraping, vale a pena dar uma olhada! :wink: 

O ato de praticar scraping em si é totalmente legal!
Mas, como já foi dito aqui em cima, sim, o mau uso dos dados coletados pode resultar em infrações. Ao raspar um conteúdo que tenha direitos autorais e exibi-lo em seu site, você pode ser penalizado (não por ter praticado scraping, mas sim por infrigir a lei de direitos autorais).

Masss, um ponto que é levantado nesse livro que mencionei é que a lei só se aplica a trabalhos de **criação**. Estatísticas ou fatos (que representam a maior parte dos dados procurados por web scrapers) não se enquadram nesse quesito.

Uma curiosidade é que recentemente, o LinkedIn [tem tido problemas](https://www.infoq.com/news/2017/08/linkedin-ruling-scraping) justamente pelo cenário oposto: eles impedem o scraping em dados que são públicos na plataforma. E isso sim, a justiça considerou errado. Em agosto desse ano, ordenaram que o scraping fosse liberado dentro por eles de 48 horas... algo que eles não cumpriram até hoje!

**Comment by kivervinicius** [comment]
@lidimayra pontos importantes muito obrigado pela contribuição, vi um artigo também onde a catho foi processada por [roubo de dados](http://economia.estadao.com.br/noticias/negocios,justica-condena-grupo-catho-por-roubo-de-dados,78486e).

**Comment by TiagoDanin** [comment]
Só a louca da Google pode fazer isso, quando você faz isso acaba como essa cara:
- http://meiobit.com/374266/quando-pegar-uma-imagem-da-internet-pode-sair-caro/

**Comment by aicoutos** [comment]
@suissa se tiver que hackear o sistema de autenticação tecnicamente já está infringindo a [Lei Carolina Dieckmann](https://pt.wikipedia.org/wiki/Lei_Carolina_Dieckmann) que como a maioria das leis é ambígua.

acredito que a única brecha para essa lei é para dados que estão expostos, tipo arquivos estáticos de música e video que não requerem que o usuário gere cookies hackeando o sistema de autenticação.

**Comment by suissa** [comment]
@aicoutos então o negócio é ninguém saber ehhehee

**Comment by mikejavier** [comment]
Pegando carona na discussão, alguém poderia me orientar de como posso fazer com que meu bot faça login na pagina ? andei pesquisando sobre o assunto mais a parte de authentication não ficou mt clara.

**Comment by lidimayra** [comment]
@mikejavier com que linguagem você está trabalhando? Se for Python, sugiro que dê uma olhada na biblioteca [requests](http://docs.python-requests.org/en/master/). Facilita bastante pra solicitações um pouco mais complexas (com a  nativa, fazer qualquer request que não seja um `GET` fica bem complicado)...

E simplifica a manipulação de cookies, headers, etc...

A biblioteca _requests_ não é nativa, portanto é necessário instalá-la a parte! 😉

**Comment by mikejavier** [comment]
@lidimayra estou usando node e utilizando uma lib para deixar as requisições amigáveis tb, muito similar a esse que você comentou. Nesse caso eu teria que varrer a pagina procurar o form pegar a url do action dele e fazer um post passando usuario/senha ? ou teria alguma outra forma?

**Comment by lidimayra** [comment]
@mikejavier acredito que sim, da forma como eu entendo, o procedimento seria bem parecido com isso mesmo... o _requests_ tem um módulo específico pra lidar com autenticações, que é o [auth](http://docs.python-requests.org/en/master/user/authentication/)... com ele a gente cria um objeto contendo os dados de login e passa esse objeto como parâmetro no _post_, imagino que deva haver algo parecido com a lib node que você está usando também...

e aí seria o esquema que você falou... encontrar a url action do form e fazer o post passando esses dados... 😃

**Comment by mikejavier** [comment]
Obrigado @lidimayra !

**Comment by aicoutos** [comment]
@mikejavier simplificando:
1. fazer login usando um sniffer para acompanhar o caminho da requisição até a paǵina de resposta com os cookies de autenticação
1.1 pode ser o sniffer do firefox (ctrl+shift+e) que já gera as strings para download através do curl
1.2 é importante conferir o prazo de validade com cookie. caso ele seja curto será necessário você replicar todo o processo de login até obter a resposta autenticada
3. tentar replicar a resposta o com cookie gerada no firefox usando um programa de downloads simples como o curl
4. acessar a resposta usando o mesmo cookie de autenticação através de bibliotecas específicas da sua linguagem 
5. aplicar o mesmo cookie de autenticação a outras requisições do site
5.

**Comment by mikejavier** [comment]
@aicoutos, perfeito mano. Muito obrigado pelos detalhes.

**Comment by kivervinicius** [comment]
Vocês utilizam algum servidor de proxy rotativo? Qual?
