### ISSUE TITLE
Landing Page Vue.Js

### ISSUE THREAD

**Issue by reginaldojunior** [frontendbr/forum#775]
Vale a pena fazer uma landing page utilizando o Vue js ou outro framework SPA?

**Comment by reginaldojunior** [comment]
Não só landing page o site completo, que vai ter todo o conteudo da empresa etc...

**Comment by onlurking** [comment]
Nah, SPAs resolvem um problema muito específico que é renderizar páginas do lado do client (o navegador das pessoas), se você não precisa ter o teu site interagindo com um backend(APIs) e que ele seja atualizado em tempo real sem necessidade de recarregar a página, não acho que SPA seja uma boa ideia.

O porque de *não usar* é que o conteúdo é gerado dinamicamente através de Javascript, isso impacta o *SEO* do site(aka o Google rankear teu site bem na busca), você teria que usar estratégias um tanto complicadas pra sanar isso de forma efetiva(SSR, Server Side Rendering), na real, um site de empresa é quase sempre um site institucional, tu está melhor servido em usar até mesmo um gerador de site estático(sem backend algum), se o objetivo é apenas mostrar conteúdo a respeito da empresa.

**Comment by reginaldojunior** [comment]
Hm vdd, acho que compensa mais eu ir com o velho e bom wordpress neste caso. Já tem toda a parte de SEO feita, e não preciso me preocupar muito.

**Comment by bernardodiasc** [comment]
> Já tem toda a parte de SEO feita, e não preciso me preocupar muito.

Isso pois voce ja sabe tudo sobre SEO ou pq nao quer saber? 😄

**Comment by bernardodiasc** [comment]
Landing page... Da pra fazer com HTML e CSS puro, o que justificaria algo mais complicado que isso? Algum requisito específico? Pq fazer landing page em wordpress tambem me parece exagero.

**Comment by onlurking** [comment]
De qualquer forma, o Google não é tão estúpido, ele consegue indexar bem sites com conteúdo gerado dinamicamente com [alguns cuidados](http://www.vuejs-brasil.com.br/indexando-paginas-no-google-de-sua-spa-vue-js) claro, mas se tu quiser fazer como uma SPA usando Vue.js, eu recomendo fortemente usar o [Nuxt.js](https://nuxtjs.org) como base pois ele é lindo, tem SSR por padrão, ele cria as rotas automaticamente através da estrutura de arquivos e pastas, e.. dá pra usar [Pug](https://pugjs.org/) pra escrever as páginas.

Obs. acho 1.000 vezes melhor usar Nuxt e gerar o site estaticamente(pelo SSR) a ter que usar Wordpress(por razões de segurança e manutenção).

**Comment by reginaldojunior** [comment]
@bernardodiasc eu coloquei landing page, mas foi jeito de dizer. Eu vou querer construir um site mesmo, que vai mostrar toda parte de produto, vai ter menu com ferramentas, área de contato, e provalvemente vou ter que utilizar parte de artigos para postagem no blog.

Essa parte de artigos que seria interresante para o conteúdo dinamico.

**Comment by reginaldojunior** [comment]
@onlurking vou dar uma olhada.

**Comment by nandomoreirame** [comment]
Eu to usando o Nuxtjs em meu projeto [pessoal/portfolio/blog](https://nandomoreira.me/) e tá indo bem... ele continua sendo SPA e não perde a semântica do HTML para o Google e para a acessibilidade... tá em desenvolvimento ainda mas tá massa. O código tá aqui > https://github.com/nandomoreirame/nandomoreirame.github.io

**Comment by LFeh** [comment]
Se for uma Landing Page de uma página, simples, meramente institucional e que vai ficar pouco tempo no ar, não complicaria. 

Faria usando CSS, HTML e JavaScript puro ou jQuery, sem build, sem task runner, sem nada 😄

**Comment by kvnol** [comment]
Pra ficar mais organizado do que só 1 HTML e CSS, utilizaria o Jekyll ou outro gerador de site estático.
