### ISSUE TITLE
Pesquisa rápida sobre o mercado a uns tempos atrás

### ISSUE THREAD

**Issue by woliveiras** [frontendbr/forum#78]
Galera, poderiam me ajudar respondendo esse formzinho safadão rapidinho? ;D

https://t.co/M9fhdcizzJ

**Comment by LFeh** [comment]
Done ;)

**Comment by woliveiras** [comment]
\o/ Valeu @LFeh

**Comment by Cleysonlb** [comment]
Pronto @woliveiras ;)

**Comment by luisfmsouza** [comment]
Feito @woliveiras !

**Comment by woliveiras** [comment]
Valeu jovens! :D

**Comment by Carlosxell** [comment]
Feito

**Comment by BielRibeiro** [comment]
Feito :)

**Comment by woliveiras** [comment]
Maravilha, obrigado pela ajuda :D

**Comment by FranklinSilva** [comment]
feito!

**Comment by alanbeda** [comment]
pronto :P

**Comment by woliveiras** [comment]
Valeu galera! :D

**Comment by diogorodrigues** [comment]
Fechou? :/

**Comment by woliveiras** [comment]
Fechei @diogorodrigues kkk
Já consegui 100 respostas. Valeu! :D

**Comment by woliveiras** [comment]
Bom fechar a issue né @LFeh?
