### ISSUE TITLE
Redirecionamento automático com React Router

### ISSUE THREAD

**Issue by barbier** [frontendbr/forum#800]
Olá! Estou com um probleminha e dificuldade em achar soluções.
Estou desenvolvendo uma aplicação usando React/Redux e o React Router para definir as rotas da aplicação.
Quando o usuário entra na aplicação, ele deve se logar para ver as informações delee ao ser autenticado, eu consigo redirecionar para a página correta e coloco uma propriedade no estado e no localStorage informando que ele está logado.
Quando o usuário volta na aplicação, se ele estava logado antes, verificando o localStorage, eu vejo que ele ainda tem a permissão para ver os dados, mas não estou conseguindo fazer o redirecionamento automaticamente. Na verdade eu consegui, mas a aplicação não renderizou o componente correto.
Alguma ideia?

**Comment by giioohbernini** [comment]
Você já deu uma olhada nesse exemplo?

https://reacttraining.com/react-router/web/example/auth-workflow

No caso o fakeAuth seria seu estado do login. Já implementei isso com redux
e não tive esse problema que você esta tendo, mas não sei muito afundo pois
só sei essa maneira de implementar rotas autenticadas com react-router.

Em ter, 7 de nov de 2017 às 18:07, Gabriel Barbier <notifications@github.com>
escreveu:

**Comment by barbier** [comment]
Sim, eu fiz baseado nesse modelo e funcionou até o ponto de autenticar, para redirecionar automaticamente eu consegui usando o [Switch](https://reacttraining.com/react-router/web/api/Switch).

Muito obrigado pela ajuda! :)

**Comment by guilaunn** [comment]
Como você resolveu o problema?

**Comment by aluxen** [comment]
Estou usando `this.props.history.push('/path')`.

**Comment by Mynameisjohndev** [comment]
Eu não estou usando as states, pois estou fazendo com os hooks, como eu poderia redirecionar este usuário após ele ter feito um login de sucesso?
