### ISSUE TITLE
Qual melhor pratica para pré processadores SASS/LESS/Stylus

### ISSUE THREAD

**Issue by deppbrazil** [frontendbr/forum#806]
## Fala galera.... ## 

Com a necessidade de um projeto aqui parti para os pré-processadores, pois precisava alterar cores com um certa frequência e as variáveis foi uma mão na roda....

Mas a questão é como vcs usam no dia-a-dia e quais as boa praticas desses carinhas?

Como to NUB com pré-processadores, fui pesquisando em artigos e fóruns e acabei decidindo usar o SASS, criando o arq. `.scss` e não o `.sass` e compilando pelo terminal do ruby e não do node, sendo assim criei a gema do ruby para gerenciar pacotes e não o npm...

então instalei o sass com o terminal do ruby e entrando dentro da pasta do projeto com:
`cd <nome da pasta>` dei o seguinte comando `gem install sass` e ele iniciou a gema dentro da pasta do meu projeto

### Mas vejo que o npm é mais utilizado no mercado ### 
é possível e é adequado usar sass mas gerenciado os pacotes com npm?

ou se alguém tiver um roadmap de boas praticas desses carinhas pinga ai....

# Valew ;) #

**Comment by theandersonn** [comment]
@deppbrazil Tbm utilizo scss e gerencio as dependências de front-end com NPM, de inicio fiquei meio perdido, mas em pouco tempo me adaptei, a impressão é que as coisas ficam jogadas na pasta node_modules, mas flui. 

Utilizo gulp pra facilitar o gerenciamento de outras tarefas que variam de projeto para projeto.

Aqui um exemplo em casos que uso o Bootstrap:
https://github.com/theandersonn/gulp-bootstrap-3

**Comment by doug2k1** [comment]
Usa [node-sass](https://github.com/sass/node-sass). É mais rápido e não precisa de Ruby. Daí você pode usar o executável direto ou integrar no seu build com webpack ou algo do gênero.

**Comment by kvnol** [comment]
Quando eu comecei a usar SASS, uns dois anos atrás eu também utilizava com Ruby, achava mais fácil pois não sabia mexer com os npm scripts e tal, mas depois que precisei fazer outras tarefas junto percebi que com Gulp (ou o próprio NPM Scripts) seria mais fácil.

**Comment by bernardodiasc** [comment]
Node-sass FTW :)

Mas se a utilidade do seu caso são variáveis e separação de arquivos (os casos mais comuns), essas funcionalidades já podem ser conseguidas no CSS nativo e HTTP/2, estão com uma cobertura boa dos browsers (lógico que to descartando browsers antigos nessa sugestão). :)

**Comment by deppbrazil** [comment]
@bernardodiasc Show por momentos pensei que o CSS3 poderia msm me auxialiar com as variáveis nativamente sem a necessidade dos SASS, mas ai veio a duvida do cross-browser ai acabei correndo atrás do SASS... 
# =) #

**Comment by deppbrazil** [comment]
@kvnol show mano.... é tb fiquei um pouco perdido com o npm, ai fui na sulução que achei mais facil em um tutorial... 

mas boa dica vou cair de cabeça no npm 
# =) #

**Comment by deppbrazil** [comment]
@doug2k1 toppp mano.... vou testar... vcs usam isso ai na Ci&t?

**Comment by deppbrazil** [comment]
@theandersonn boa man.... valeww pela dica 

# =) #

**Comment by nandomoreirame** [comment]
# =)

**Comment by didiraja** [comment]
Aproveitando o tópico, eu devo começar a utilizar pré-processador pelo mesmo motivo do @deppbrazil. Poderiam me dizer qual a diferença, se é que há, entre os três?

Eu tinha duvida entre Grunt e Gulp, mas ai como falaram que Gulp permite multi-thread foi fácil decidir. Queria saber se rola algum diferencial assim, ou se é só preferência mesmo.

**Comment by LFeh** [comment]
@didiraja Sugiro abrir uma issue nova ;)
