### ISSUE TITLE
Webpack parando a build (Possível conflito com git)

### ISSUE THREAD

**Issue by leticiacostadias** [frontendbr/forum#807]
Olá, pessoas!
Depois de uma tarde de sofrimento, achei melhor compartilhar essa treta com vocês.

Estou com algum problema com o webpack que está interrompendo a build sempre em 28%. A build simplesmente para e fica eternamente em 28%.
Reparei que, quando os arquivos estão iguais ao que está na HEAD, o webpack funciona normalmente. Depois de fazer qualquer alteração no javascript, a build para de novo (para sempre) em 10%.

![screen shot 2017-11-10 at 16 28 29](https://user-images.githubusercontent.com/20451772/32672954-375abf02-c634-11e7-974b-6f898847da3e.png)

Já atualizei o node, npm, webpack, deus e o mundo e nada resolveu. Seria obra de satanás?
Alguém está tendo ou já teve esse problema?

**Comment by LFeh** [comment]
Qual versão do React você está usando?

**Comment by giioohbernini** [comment]
Se der, coloca uma versão reduzida desse seu código em um repo e linka aqui.

**Comment by leticiacostadias** [comment]
@LFeh Estou usando a 15.6.1. Mas não acho que seja questão de versão porque o bug só está acontecendo na minha máquina.

**Comment by bernardodiasc** [comment]
https://twitter.com/kamilogorek/status/928390958151954432

```
Whenever your node project fails, just use this snippet:

say 'please work'; npm cache clean --force && rm -rf node_modules && npm i && npm start && if [ "$?" == "0" ]; then say 'thank you'; else say 'goddamn'; fi

60% of the time, it works every time.
```

😂

**Comment by leticiacostadias** [comment]
@bernardodiasc Nem limpando o cache rolou T.T

**Comment by bernardodiasc** [comment]
Manda o config do seu webpack para podermos dar uma olhada @leticiacostadias

**Comment by bernardodiasc** [comment]
@leticiacostadias alguma chance de voce estar usando Sass no seu projeto? Se sim, já tentou atualizar o `node-sass`? Fiz uma repida pesquisa e parece que é comum o Sass causar esse tipo de problema.

**Comment by Raffesmind** [comment]
Se estiver usando o Yarn, já tentou dar um `yarn check --integrity` para conferir se nenhuma das bibliotecas quebrou ou está desatualizada para o build?

**Comment by leticiacostadias** [comment]
@Raffesmind nesse projeto não estou usando yarn
@giioohbernini como é do projeto do trampo não posso postar muita coisa do código, só o config do webpack até então :/
@bernardodiasc Realmente, estou usando sass e vi algumas pessoas comentando sobre isso, mas atualizando não tive mudança aqui.
E o config do webpack está assim:

```
const webpack = require('webpack');
const path = require('path');
const chalk = require('chalk');
const autoprefixer = require('autoprefixer');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const ProgressBarPlugin = require('progress-bar-webpack-plugin');

const svgoConfig = JSON.stringify({
    plugins: [
        {removeTitle: true},
        {convertColors: {shorthex: false}},
        {convertPathData: false}
    ]
});

module.exports = {
    devtool: 'eval',
    devServer: {
        host: '0.0.0.0',
        port: 1337,
        colors: true,
        contentBase: 'public',
        historyApiFallback: true
    },
    entry: path.resolve('app'),
    output: {
        path: path.resolve('public'),
        filename: 'facelift.js'
    },
    resolve: {
        modules: [
            'node_modules',
            '.',
            path.join('app', 'screens', 'Components')
        ]
    },
    externals: [{
        xmlhttprequest: '{XMLHttpRequest:XMLHttpRequest}'
    }],
    plugins: [
        new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /pt-br/),
        new ProgressBarPlugin({
            format: '  build [:bar] ' + chalk.green.bold(':percent') + ' (:elapsed seconds)',
            clear: true
        }),
        autoprefixer
    ],
    module: {
        rules: [
            {
                test: /.js$/,
                include: path.resolve('app'),
                use: [
                    'babel-loader',
                    'eslint-loader'
                ]
            }, {
                test: /.s[a,c]ss$/,
                use: [
                    'style-loader',
                    'css-loader',
                    'postcss-loader',
                    'sass-loader'
                ]
            }, {
                test: /\.(jpe?g|png)$/i,
                use: [
                    'url-loader?limit=10000'
                ]
            }, {
                test: /\.gif$/,
                use: [
                    'url-loader?limit=10000&name=[name].[ext]'
                ]
            }, {
                test: /\.svg$/,
                exclude: /node_modules/,
                use: [
                    'svg-inline-loader',
                    'svgo-loader?' + svgoConfig
                ]
            }, {
                test: /\.css$/,
                use: [
                    ExtractTextPlugin.extract('style-loader', 'css-loader', 'postcss-loader')
                ]
            }, {
                test: /\.(eot|ttf|woff|woff2)$/,
                exclude: /node_modules/,
                use: [
                    'file-loader?name=public/fonts/[name].[ext]'
                ]
            }
        ]
    }
};
```

**Comment by leticiacostadias** [comment]
Update: Achando que pudesse ser algum bug na máquina, cheguei a formatar.
Porém, o problema persiste.

**Comment by bernardodiasc** [comment]
Nossa, que treta. @leticiacostadias voce conseguiria montar um prototipo usando essa config do webpack e o mesmo package.json? Cria um repo separado com isso e coloca o minimo de js possivel só pra rodar. Vai ficar mais facil para entendermos o problema.

**Comment by fdaciuk** [comment]
@leticiacostadias tenta ir removendo as coisas que não são necessárias para o build, só pra ter certeza que não é isso que está travando o build :)

Comece removendo o `ProgressBarPlugin`, e veja se o erro persiste :)

**Comment by LFeh** [comment]
> Update: Achando que pudesse ser algum bug na máquina, cheguei a formatar.
Porém, o problema persiste.

Carario!

**Comment by leticiacostadias** [comment]
Boa notícias!
@fdaciuk não era o `ProgressBarPlugin`, mas você me deu a ideia de tirar um loader/plugin por vez pra descobrir qual deles estava dando problema. Turns out, o eslint estava travando a build. Agora, o motivo é outra história, vou tentar arrumar isso agora pra ele voltar a funcionar normalmente.

**Comment by fdaciuk** [comment]
Boa @leticiacostadias! Coloca o eslint separado, em outra regra, com o `enforce: 'pre'`, que ele vai executar antes dos outros loaders :)

**Comment by leticiacostadias** [comment]
Fiz a seguinte alteração, mas ainda não tive resultados:
```
...
    rules: [
           {
              enforce: 'pre',
              test: /\.js?$/,
              include: path.resolve('app'),
              loader: 'eslint-loader'
            }, {
                test: /.js$/,
                include: path.resolve('app'),
                use: [
                    'babel-loader'
                ]
            },
...
```

**Comment by fdaciuk** [comment]
É isso mesmo! Só coloque `use` no lugar de `loader`, não precisa do `?` na regex do `eslint` e adicione a contrabarra antes do ponto no loader do `babel` :)

Você não teve resultados para gerar o build, ou não teve warning de erros de lint? xD

**Comment by matheusml** [comment]
@leticiacostadias 

Se isso que o @fdaciuk não funcionar, você pode simplesmente tirar o `eslint` do webpack e deixar como um npm script. Exemplo:

```
scripts: {
  build: "webpack",
  lint: "eslint"
}
```

**Comment by leticiacostadias** [comment]
@fdaciuk Estou mantendo o `loader` porque, como estou usando `options`, o webpack lança um erro quando troco para `use`, no mais, as alterações não surtiram efeito.

A real é que o webpack nem chega a terminar de compilar pra gerar os erros. Ele fica forever buildando (em 25%, de acordo com o plugin de progresso).

@matheusml é usa solução também, mas acho mais prático usar o eslint junto com o webpack pra fazer as correções "em tempo real"

**Comment by fdaciuk** [comment]
@leticiacostadias você está usando o webpack 1 ou o 2+?

**Comment by leticiacostadias** [comment]
@fdaciuk estou usando a versão 3.4

**Comment by fdaciuk** [comment]
Não era pra dar erro ao usar o `use`, na real, esse seria o correto xD
O `loader` normalmente você usa quando tem um array de loaders, onde você precisa configurar cada um de forma separada, aí você usa o `loader` dentro do objeto:

```js
rules: [
  {
    test: /\.js$/,
    include: path.join(__dirname, 'app'),
    use: [
      { loader: 'some-loader', options: {} },
      { loader: 'babel-loader' }
    ]
  }
]
```

Consegue postar qual erro ele dá quando você troca o `loader` pelo `use`? E, se remover o `eslint-loader`, ele builda corretamente?

**Comment by leticiacostadias** [comment]
@fdaciuk Sim, quando tiro o `eslint-loader` builda normalmente.

E o webpack está devolvendo esse erro aqui:
```
Error: options/query provided without loader (use loader + options) in {
  "enforce": "pre",
  "test": {},
  "include": "/Users/leticiacosta/Desktop/projects/omz-facelift/app",
  "exclude": {},
  "use": "eslint-loader",
  "options": {
    "emitWarning": true
  }
}
``
`

**Comment by leticiacostadias** [comment]
Pessoas, resolvi aqui!
Atualizei o eslint-loader pra versão 1.9.0 e voltou ao normal!
Obrigada a todo mundo que ajudou :)

**Comment by fdaciuk** [comment]
Legal @leticiacostadias! Só sobre o esquema do `use` vs `loader`: na real a config seria:

```js
{
  enforce: 'pre',
  include: path.resolve('path'),
  use: {
    loader: 'eslint-loader',
    options: { emitWarning: true }
  }
}
```

O `options` e o `loader` tem que ser dentro do `use` :)

**Comment by leticiacostadias** [comment]
@fdaciuk Agora sim hahaha
