### ISSUE TITLE
Onde posso encontrar material para aprender CSS?

### ISSUE THREAD

**Issue by Lysandroc** [frontendbr/forum#808]
# galera, preciso da ajuda de vocês

Estou tentando fortalecer meus conhecimentos sobre css, existe algum material bom e gratuito para que eu possa acompanhar e ter um retorno(conhecimento)? 

Se vocês possuem algum livro, blog, slack, podcast ou qualquer outra solução para este meu problema, compartilhem aí...

**Comment by waldemirflj** [comment]
@Lysandroc eu recomendo você estudar pré processadores como: Less ou Sass e alguns padrões eu gosto e utilizo o smacss.

Talvez isto de ajude:
https://tableless.com.br/oocss-smacss-bem-dry-css-afinal-como-escrever-css/
https://smacss.com/

**Comment by afonsopacifer** [comment]
Tem algumas coisas no meu canal no youtube :)
https://www.youtube.com/csscastshows

E o canal do Henrique ❤️ 
https://www.youtube.com/channel/UC4W-b9Q1I0mzGGzFKOu-66g

**Comment by EmanoelLopes** [comment]
Fala @Lysandroc, tudo tranquilo?

Recomendo você dar uma olhada no [CSS Reference](http://cssreference.io/) (em inglês), que é um guia visual muito bom e com exemplos práticos explicados de maneira bem didática.

Também tem o [DevDocs](http://devdocs.io/css/) (também em inglês) como ótima referência, não só para CSS mas também para diversas outras linguagens.

**Comment by deppbrazil** [comment]
@Lysandroc não te aconselharia a começar com pré-processadores, pois vai te confundir no começo estude ele nativamente vc acha ótimas referencias e exemplos no [Maujor](http://www.maujor.com/) e no [W3Schools](https://www.w3schools.com/css/default.asp) e depois parta pros frameworks [Bootstrap](https://getbootstrap.com/) [Foundation](https://foundation.zurb.com/) ou [Materialize](http://materializecss.com/) e depois otimize seus projetos com os Pré-Processadores [SASS](http://sass-lang.com/) [Less](http://lesscss.org/) ou [Stylus](http://stylus-lang.com/) que vai te dar opções de fazer encadeamento, trabalhar com variáveis, funções etc...

Se quer depois avançar mais conhecendo padrões de Design avançado da uma olhada no [Origamid](https://www.origamid.com/) alguns cursos são pagos mas valem mto a pena.... tem a página deles no face com ótimas dicas tb [Origamid Faceboook](https://www.facebook.com/origamid/)

## Espero ter ajudado =) ##

**Comment by ezp127** [comment]
Se você está realmente começando do zero com CSS, recomendo você primeiro adquirir um bom conhecimento em CSS2. Apesar de haver muita coisa nova, ainda é possível fazer muita coisa apenas com CSS2. Depois é só ir evoluindo pra CSS3 e outras ferramentas e frameworks. 
É meio chato estudar coisas "antigas"? Sim.. mas é necessário hehe.

Se você já tem essa base, deixo como sugestão dar uma olhada no Tailwind CSS https://tailwindcss.com/ 
Dá uma olhada no Twitter dos caras, parece promissor, foi lançado oficialmente a poucos dias.

**Comment by leonardosouza** [comment]
Aqui amiguinho, seja feliz:

https://www.caelum.com.br/apostila-html-css-javascript/

[]'s

**Comment by LFeh** [comment]
> Se você está realmente começando do zero com CSS, recomendo primeiro adquirir um bom conhecimento em CSS2. Apesar de haver muita coisa nova, ainda é possível fazer muita coisa apenas com CSS2. Depois é só ir evoluindo pra CSS3 e outras ferramentas e frameworks.
É meio chato estudar coisas "antigas"? Sim.. mas é necessário hehe.

Penso que nem deveriamos separar mais o CSS assim (CSS2, CSS3, CSS4...). CSS é CSS. Mesmo o CSS3 já é realidade faz alguns anos e não teria motivo para não aprender as features dele de cara. 

 Um ponto importante, como dito pelo @deppbrazil é aprender CSS **antes** de tentar aprender qualquer pré-processador. Stylus, Sass, Less, PostCSS no fim geram apenas CSS, e se você não tiver um bom entendimento da base, vai te atrapalhar bastante.

De resto, o pessoal já compartilhou vários links. Não deixe de conferir o [MDN](https://developer.mozilla.org/pt-BR/docs/Web/CSS) e de acompanhar o [CSS Tricks](https://css-tricks.com/) quando tiver mais avançado.

**Comment by kvnol** [comment]
> "Um ponto importante, como dito pelo @deppbrazil é aprender CSS antes de tentar aprender qualquer pré-processador." @LFeh 

Eu vejo aprender frameworks ou pré-processadores como algo para ajudar o desenvolvimento, como quando começamos a aprender HTML no bloco de notas e depois, quando precisávamos desenvolver com mais facilidade, utilizávamos o Dreamweaver, Sublime, etc...

**Comment by cristofersousa** [comment]
@Lysandroc  peguei alguns links dos meus favoritos e de lugares que sei que vale a pena para quem desejar fazer imersão em CSS, segue: 


 #### Layout/Estrutura

- 1. [Position] (https://www.w3.org/TR/css-position-3/)
- 2. [Flexbox] (https://www.w3.org/TR/css-flexbox-1/)
- 3. [CSS-grid] (https://www.w3.org/TR/css-grid-1/)


#### Video Aula
- 0.  (https://www.youtube.com/watch?v=T65y3oj9s50)[ - Stevan Maito Youtube]
- 1.  (https://cursocss.com.br) [Stevan Maito ]
- 2. (https://www.devmedia.com.br/curso/curso-de-css-gratuito/183)  [ DevMedia]
- 3. (https://www.udemy.com/css-um-passo-adiante/) [- Tácio Zemel ]
- 4. (https://www.udemy.com/css-grid-layout/) [- Tácio Zemel]
- 5. (http://www.maujor.com/tutorial/joe/cssjoe1.php ) [ Maujor]
- 6. (https://cursos.timtec.com.br/course/css3/intro) [Design de Interfaces com CSS3 pela TimTec]

####  Extras: 
- 0. [CSS Sustentável] (http://csssustentavel.com.br/)
- 1. [ CSS Básico com Mozz!la]( https://developer.mozilla.org/pt-BR/docs/Aprender/Getting_started_with_the_web/CSS_basico)
- 2. [GSS] (http://gss.github.io/)

[],s

**Comment by Lysandroc** [comment]
Estes materiais já estão me ajudando... muito bom ter pessoas que compartilham conhecimento sem medo. **Obrigado galera!**

**Comment by mahenrique94** [comment]
Os que eu sempre compartilho:

### Livros:
#### Maujor:
- [CSS3](http://livrosdomaujor.com.br/css3/)

#### Casa do Código:
- [HTML5 e CSS3](https://www.casadocodigo.com.br/products/livro-html-css)
- [Web Design Responsivo](https://www.casadocodigo.com.br/products/livro-web-design-responsivo)
- [A Web Mobile](https://www.casadocodigo.com.br/products/livro-web-mobile)
- [CSS Eficiente](https://www.casadocodigo.com.br/products/livro-css-eficiente)

### Apostilas:
- [Desenvolvimento Web com HTML, CSS e JavaScript](https://www.caelum.com.br/apostila-html-css-javascript/)

### Cursos:
- [Alura](https://www.alura.com.br/)
- [School of net](https://www.schoolofnet.com/)

### Sites
- [Tableless](https://tableless.com.br/)
- [CSS Tricks](https://css-tricks.com/)
- [w3schools](https://www.w3schools.com/)

**Comment by adrianoavelino** [comment]
Esses dias eu vi esse conteúdo no Training Center e achei bem legal: https://github.com/marcelabomfim/CSSEHFODA

**Comment by merciakeila** [comment]
Vocês são M A R A V I L H O S O S ! <3

**Comment by LucasJantschChitolina** [comment]
> Se você está realmente começando do zero com CSS, recomendo primeiro adquirir um bom conhecimento em CSS2. Apesar de haver muita coisa nova, ainda é possível fazer muita coisa apenas com CSS2. Depois é só ir evoluindo pra CSS3 e outras ferramentas e frameworks. É meio chato estudar coisas "antigas"? Sim.. mas é necessário hehe.
> 
> Se você já tem essa base, deixo como sugestão dar uma olhada no [Tailwind CSS](https://tailwindcss.com) Dá uma olhada no Twitter dos caras, parece promissor, foi lançado oficialmente a poucos dias.

Será que vingou? haha
