### ISSUE TITLE
Qual faculdade para tecnologo  ? 

### ISSUE THREAD

**Issue by Lucas1906** [frontendbr/forum#809]
Pessoal decidi q irei fazer um curso superior...  Mesmo analisando e vendo q não é algo tao necessário para área de front end algumas coisas fizeram eu decidir em fazer... Quero algo rapido entao irei fazer um tecnólogo. Quais faculdades vcs indicariam ? andei vendo 3, FIAP, São Judas, Anhebi.  Ja q é um curso rapido to levando em consideração o nome delas no mercado e a nota no Mec. Se alguem estuda/etuou em algumas delas poderia deixa uma opinião. Obs: to quase decidindo pela FIAP pela localização e pelo nome

**Comment by edmolima** [comment]
@Lucas1906 

Dos nomes citados te indicaria FIAP. Ela é uma faculdade "disruptiva" mas ao mesmo tempo é uma faculdade conservadora no que diz respeito a linguagens de programação. Você vai ver muito Java, .Net e etc porque a faculdade tem boa relação com os principais players de tecnologia (IBM, Itaú e etc).

Você vai poder ter contato com muita coisa se tiver tempo e focado nisso.

O modelo de criar uma startup no final do curso, o modelo de não ter disciplinas semestrais e sim anuais enfim, são bem diferentes da maioria das faculdades. Mas é bem bacana, é um modelo que funciona bem.

Espero que possa ter te ajudado.

**Comment by LFeh** [comment]
Complementando: #39 #653 #518

**Comment by florbraz** [comment]
A sua idéia é que seja algo realmente rápido? Ou é, de fato, ganhar mais
conhecimento?

Falando da miinha experiência, eu fiz um tecnólogo (Sistemas para a
Internet) e hoje em dia penso muito que eu deveria ter cursado ciência da
computação.

Primeiro, porque, por já trabalhar na área há bastante tempo, não aprendi
muita coisa no tecnólogo - acabou sendo muito mais um diploma do que
aprendizado real. Não sei se seria assim em toda faculdade, mas dos relatos
que já ouvi, é meio que a regra - um curso mais raso, para abordar diversos
assuntos práticos, porém com pouca base teórica.

Segundo, porque, mesmo não sendo explícito no início, a base teórica te dá
insumos para ir mais facilmente para qualquer lado dentro da programação,
qualquer linguagem ou paradigma se torna muito mais palpável com uma boa
base teórica.

[]'s
Flor Braz
*http://florbraz.com <http://florbraz.com/>*

**Comment by nathpaiva** [comment]
Eu faria [Engenharia de Software](https://www.unicesumar.edu.br/ead/cursos-graduacao/engenharia-de-software/)

**Comment by MatCunha** [comment]
@Lucas1906 

Já passei por Analise e desenvolvimento de Sistemas na Unip e também na Faculdade Impacta que é focada em tecnologia, na Unip foi tudo uma decepção e na Impacta foi ótimo, faculdade com estrutura e focada em conhecimento prático com apresentações e eventos, ano passado rolou o Google Dev Fest lá e foi bem legal. 

Hoje por motivos de grana e morar sozinho (não tá fácil), estou migrando pra Fatec SP em ADS também, possui uma base teórica extensa e pode ser comparado a um (quase) barachel por que são 4 anos. Conversando com um amigo que é dev no Canadá e que fez Fatec tbm, ele disse que foi muito fácil reconhecer o diploma e arranjar trabalho. 

Acho que você deve escolher não por ser rápido e etc, mas pelo que você pretende do seu futuro.

Abçs

**Comment by silvaMatheus** [comment]
Alguem mais ja estudou/estuda na impacta ? oq acham ?

**Comment by olegon** [comment]
Uma opção é a FATEC _(Faculdade de Tecnologia)_, uma faculdade pública que oferece cursos tecnólogos. Aproveita que as [incrições](https://www.vestibularfatec.com.br/home/) para o vestibular estão abertas.

**Comment by lidimayra** [comment]
Sou formada em ADS pela FATEC Jundiaí. O curso foi excelente para o meu crescimento em diversos aspectos. Desenvolvimento de competências técnicas e generalistas, aprendizagem baseada em projetos, possibilidade de atuar com pesquisa científica (Iniciação Científica e Tecnológica e Jornada de Pesquisa), diversas atividades de extensão (participei do Clube de Arduino, desenvolvimento mobile, entre outros. Há também oficina de games e Linux), participação em eventos (Semana de Tecnologia)... enfim, uma série de fatores que superaram as expectativas que eu tinha em relação à faculdade. Recomendo fortemente! :smiley:

**Comment by MatCunha** [comment]
@lidimayra 

Lidiane, você sabe dizer se os cursos da Fatec são reconhecidos ou podem ser validados internacionalmente? Tenho o sonho de trabalhar no Canadá e isso seria o ideal. 

Att.

**Comment by lidimayra** [comment]
Oi @MatCunha!!
Os cursos dada FATEC são de ensino superior, tem duração de 6 semestres e são reconhecidos pelo MEC. Desta forma, para revalidar o diploma no exterior é necessário verificar quais são as exigências específicas do país que você deseja.

Aliás, tenho amigos que fizeram graduação sanduíche, na qual cursaram parte do curso na FATEC e parte do curso em universidades estrangeiras (como dá pra ver [aqui](http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4646737T2)  e [aqui](http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4959206U5)).

**Comment by jturetta** [comment]
> @Lucas1906
> 
> Dos nomes citados te indicaria FIAP. Ela é uma faculdade "disruptiva" mas ao mesmo tempo é uma faculdade conservadora no que diz respeito a linguagens de programação. Você vai ver muito Java, .Net e etc porque a faculdade tem boa relação com os principais players de tecnologia (IBM, Itaú e etc).
> 
> Você vai poder ter contato com muita coisa se tiver tempo e focado nisso.
> 
> O modelo de criar uma startup no final do curso, o modelo de não ter disciplinas semestrais e sim anuais enfim, são bem diferentes da maioria das faculdades. Mas é bem bacana, é um modelo que funciona bem.
> 
> Espero que possa ter te ajudado.

Eu estava bem na dúvida entre a Impacta e a FIAP para o curso de banco de dados, mas depois de alguns depoimentos, inclusive o seu, creio que irei acabar pagando um pouco mais na FIAP por um retorno maior em termos de aprendizado e custo-benefício (mais caro, mas melhor).
