### ISSUE TITLE
O icone de Sanduiche da versão mobile em svg do Boostrapt 4 não carrega no firefox, como eu posso resolver isso ?

### ISSUE THREAD

**Issue by grodrigues** [frontendbr/forum#812]
Icone do menu de Sanduiche

**Comment by LFeh** [comment]
Sua dúvida está bem dispersa. Coloque mais informações (imagens, prints, código) e reformule a pergunta para entendermos melhor.

**Comment by grodrigues** [comment]
Ok

**Comment by grodrigues** [comment]
navbar-light .navbar-toggler-icon {
    background-image: url(data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://ww…p='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E);
}

**Comment by bernardodiasc** [comment]
Mano @grodrigues, me parece que está te faltando o básico de conhecimento de SVG e CSS. Responder a sua dúvida seria fácil, mas resolver o problema para voce não me parece boa ideia. Sugiro dar uma aprofundada no assunto antes de tentar soluções prontas. O que posso lhe recomendar é uma boa leitura sobre o assunto, por exemplo começando por aqui https://css-tricks.com/using-svg/. Sua dúvida é muito simples, assim que entender do assunto a resposta vem naturalmente. Boa sorte :)

**Comment by grodrigues** [comment]
Mais a grande questão é que no Firefox ele não carrega e no chrome sim.

**Comment by bernardodiasc** [comment]
@grodrigues nao se prende a isso pq pode ser o caso do browser estar corrigindo o erro pra voce, o chrome faz essas coisas, as vezes usamos código errado e nao percebemos. (saudade dos tempos que as paradas eram hardcore, pra ser válido tinha que ser strict, forçava o codigo a sair perfeito)

**Comment by grodrigues** [comment]
@bernardodiasc Verdade e Obrigado

**Comment by grodrigues** [comment]
@bernardodiasc Tudo resolvido.

**Comment by bernardodiasc** [comment]
Show! 🎉 Parabéns mano @grodrigues, coloca a solução ai para nós 😄

**Comment by grodrigues** [comment]
Foi gerado no ilustrator o svg novamente e coloquei no background do elemento assim:
background: url(../img/logo-detalhe.svg) no-repeat #fff;

**Comment by grodrigues** [comment]
Antes ele estava vindo de um cdn externo.

**Comment by LFeh** [comment]
Parabéns @grodrigues :)

**Comment by grodrigues** [comment]
@LFeh Obrigado
