### ISSUE TITLE
Existe alguma ferramenta easy para desenhar árvores de pastas somente com caracteres?

### ISSUE THREAD

**Issue by danilowoz** [frontendbr/forum#813]
Tipo isso:

```sh
├── README.md
├── build
│   ├── css
│   │   └── style.css
│   ├── img/
│   ├── svg/
│   └── js
│       └── main.js
│   ├── index.html
├── gulpfile.babel.js
├── package.json
└── src
    ├── img/
    ├── svg/
    ├── js/
    ├── styl
    │   ├── _core/*.styl
    │   ├── atoms/*.styl
    │   ├── molecules/*.styl
    │   ├── organisms/*.styl
    │   ├── widgets/*.styl
    │   ├── pages/*.styl
    │   └── style.styl
    └── pug
        └── index.pug
```

@LFeh ajuda noix

**Comment by kvnol** [comment]
A única coisa que achei foi isto: http://mama.indstate.edu/users/ice/tree/, mas não testei pois não estou com Linux aqui.

PS: Mas seria massa organizarmos para tentarmos desenvolver algo similar com Markdown, hein.

**Comment by vicentedealencar** [comment]
https://www.npmjs.com/package/tree-cli

**Comment by danilowoz** [comment]
Era exatamente isso @vicentedealencar, valeu!

**Comment by LFeh** [comment]
Ia indicar o [tree-cli](https://www.npmjs.com/package/tree-cli) mesmo. Boa @vicentedealencar ;)
