### ISSUE TITLE
Onde vcs trabalham e o que fazem? Como é o dia-a-dia de vcs? Qual o foco da entrega? Quais principais Stacks?

### ISSUE THREAD

**Issue by deppbrazil** [frontendbr/forum#816]
#### Entre outras não mto conhecidas e comentadas... ao contrario de alguns anos atrás que o Webdesigner fazia tudo até msm backend ####
___
## Função/Cargo ## 
Eu por exemplo aqui na Kroton sou Dev. Specialist Mutimedia => Desenvolvedor Especialista em Multimídia, tendo como principais stacks: html5, css3 ,javaScript e audio/video.

## Foco no usuário ##
Como a Kroton é uma holding de educação temos o foco principal voltado na acessibilidade para deficiêntes visuais e auditivos e na experiência do aluno nos portais da faculdade e nos materiais digitais que produzimos... 

## Problemas e desafios no dia-a-dia ##
O Workflow principal aqui é basicamente a criação de templates em html5 dentro de uma ferramenta chamada [Webflow](https://webflow.com/) um CMS para criação de templates responsivos, nosso time de Especialistas Multimídia atua na performance desses templates,  implementações de códigos javaScript e PHP para melhorias e integrações com projetos feito fora do Webflow... e tb para deixar o modelo de webaulas pronto paras os assistentes multimídia fazer a diagramação do material... Fazemos bastante animações tb para deixar o material interativo e dinâmico e futuramente gamificado, fazemos mtos projetos fora do Webflow tb, diretamente no codigo usando algumas libs em js para fazer animações ou algo interativo, ou animações em video feitas no After Effects e Animate CC... as vezes surge tb alguns jobs com backend, nada mto complexo, são desafios como criação de formulários de feedback com html5 + PHP e MySQL, integração e criação de database, consultas SQL, etc... nada tão hardcore focado no backend...

# Gostaria de saber um pouco sobre vcs, onde atuam, o que fazem no dia-a-dia e problemas e desafios que enfrentam diariamente... #

**Comment by LFeh** [comment]
Se liga @deppbrazil  :) -> #412

**Comment by mahenrique94** [comment]
Função/Cargo

Desenvolvedor Full Stack na Atena Informática

Foco em sistemas para transporadora

Aqui nosso foco é desenvolver sistemas para transporte, mas também também contamos com outros sistemas web e realizamos a criação de sites.

Problemas e desafios no dia-a-dia

Aqui é o problema, como a empresa é pequena, todo mundo faz tudo kkk, ai depende do dia ou da semana eu faço umas *tasks* que estão no meu trello.

Tem dia que eu desenvolvo para Android, outro dia mexo nos sites em PHP, em outro mexo no sistema de transporte ou outros sistemas web em Java, também temos um sistema de documentação dos nossos sistemas, tipo um manual, feito em MEAN.

Além de desenvolver também cuido dos nossos clouds e mexo com banco de dados, como pode ver, o fato da empresa ser pequena, complica um pouco as coisas, por exemplo, somente eu faço uso de uma metodologia ágil.

Abraços

**Comment by LFeh** [comment]
@mahenrique94 Coloca sua reposta na issue #412 :)

**Comment by deppbrazil** [comment]
@LFeh boa man... vou postar la tb =)

**Comment by mahenrique94** [comment]
demoro @LFeh vou postar la
