### ISSUE TITLE
Black Friday dos Cursos Ninja do Fernando Daciuk

### ISSUE THREAD

**Issue by Roger-Melo** [frontendbr/forum#822]
Oportunidade de ouro pra quem quer aprender JS, React, Git e Github!  

- [Curso JavaScript Ninja](https://www.udemy.com/curso-javascript-ninja/?couponCode=SOUNINJAMASQUEROBF)
- [Curso React.js Ninja - React Completo](https://www.udemy.com/curso-reactjs-ninja/?couponCode=SOUNINJAMASQUEROBF) 
- [Curso Git e GitHub Ninja](https://www.udemy.com/git-e-github-ninja/?couponCode=SOUNINJAMASQUEROBF)

![image](https://user-images.githubusercontent.com/29297788/33140618-a87d21f4-cf97-11e7-8704-b9b6343302ff.png)

![image](https://user-images.githubusercontent.com/29297788/33140630-aefefb10-cf97-11e7-8fd7-bf88cd2af42f.png)

![image](https://user-images.githubusercontent.com/29297788/33140636-b3a61aae-cf97-11e7-8fdd-831cce657011.png)

**Comment by marcusvcribeiro** [comment]
Fiz a compra hoje mais cedo, cheguei em casa e nao tive acesso.
Acabei de fazer a compra novamente, espero que nao venha 2 faturas rsrs


2017-11-22 15:14 GMT-02:00 Roger Melo <notifications@github.com>:

**Comment by ewerto0n** [comment]
Tava esperando essa promoção NINJA 'dos meus sonhos'.

**Comment by fabriciofmsilva** [comment]
Promoção bacana demais. Mesmo já trabalhando a um bom tempo com JavaScript decidi comprar o curso de JS Ninja (mesmo não curtindo o termo ninja), pois os conteúdos do Daciuk, é top demais!

**Comment by LFeh** [comment]
@fdaciuk

**Comment by fdaciuk** [comment]
Opa, valeu por divulgar @Roger-Melo :heart:

**Comment by meendoo** [comment]
Cheguei tarde 😭

**Comment by fdaciuk** [comment]
@meendoo em dezembro vai ter mais pra quem perdeu essa \o/

Só ficar ligado no meu Twitter e FB que vou divulgar por lá :D
