### ISSUE TITLE
Utilizar uma página 404 customizada ou redirecionar para a index?

### ISSUE THREAD

**Issue by heliomsolivas** [frontendbr/forum#825]
Pessoal, o que vocês costumam fazer quando o usuário acessa uma página que não existe? Em questão de SEO faz alguma diferença?

**Comment by LFeh** [comment]
O maior problema de direcionar para a home, não é com relação ao SEO e sim com relação a experiencia do usuário.

#### Imagine uma pessoa tentando acessar uma página que está indisponível ou digitando o endereço errado

Se ela for direcionada para a home, não vai entender o que aconteceu. "A página recarregou?", "Fiz alguma coisa errada?"

Páginas de erros são fundamentais para fornecer um feedback para o usuário, e podem ser inteligente, por exemplo, indicando conteúdo parecido ou relevante para não travar a navegação.

**Comment by mahenrique94** [comment]
Geralmente costumo apresentar uma página de erro 404 estilizado passando um *feedback* para o usuário do problema ocorrido, além de adicionar um link para ele mesmo voltar para a página inicial.

**Comment by edmolima** [comment]
Adote o fallback! leve o usuário para o 404. Como o @LFeh falou, a experiência do usuário fica comprometida quando você direciona ele para a index.

Lembra que o código de erro do servidor tem que transparecer para o usuário algo que esteja realmente acontecendo seja um 200 ( ok, veio conteúdo) ou um 404 (esse conteúdo não existe).

Tente fazer com que a navegação seja fluida ou seja leve esse cara até onde ele quer ir. Mesmo que seja ir a lugar algum (404). 

Quando projetar uma pagina 404 implemente de uma forma que seja explicativa e que ele possa ter uma ação para sair dali.

Espero ter te ajudado =)

**Comment by bernardodiasc** [comment]
Depois que trabalhei num projeto que o editor de conteúdo, que era quem lidava com os usuários e pegava feedbacks, me pediu para incluir "Clique aqui para..." nos botões porque seus usuarios não encontravam as coisas (tava tudo muito obvio, era um botão, era só clicar!!!), ficou muito claro que o usuário é um sujeito distraído que não vai gastar mais que alguns segundos no seu projeto pra entender o que fazer. O que é óbvio para nós pode ser um enigma que o usuario não ta afim de desvendar.

Ou seja, como foi dito ai em cima, se a página não foi encontrada, ofereça soluções e ações para o usuário. Não espere que o visitante saiba o que fazer, pq se não tiver uma forcinha tvz ele(a) apenas feche o site e parta pra outra.

**Comment by barbier** [comment]
Eu trabalhei numa empresa em que a página 404 dizia que o que o usuário estava procurando não existe e apresentava alguns produtos para ele
