### ISSUE TITLE
About your english / Sobre seu inglês

### ISSUE THREAD

**Issue by Lysandroc** [frontendbr/forum#830]
Hey guys, what's up?

Vocês realmente acham que precisamos fazer cursos para conseguimos nos comunicar bem com outras pessoas? Como vocês aprendem/aperfeiçoam seu inglês?

**Comment by kelciocajueiro** [comment]
Lendo e ouvindo muito

**Comment by mahenrique94** [comment]
Atualmente faço na [Alura Lingua](https://www.aluralingua.com.br/) e [English Live](https://englishlive.ef.com/pt-br/), mas ja um pouco de particular, porém preferi mudar para o online.

**Comment by raisiqueira** [comment]
Costumo ler, as palavras que enfrento dificuldades eu faço uma tradução mesmo ¯\_(ツ)_/¯

**Comment by heliomsolivas** [comment]
Eu leio e escuto muito, mas acho que na conversação não to bem, @mahenrique94 eu não conhecia esse Alura Lingua, é bom?

**Comment by LFeh** [comment]
Fechando essa, já tem duas sobre esse tema :) 

#109 #643
