### ISSUE TITLE
Clip-path

### ISSUE THREAD

**Issue by kivervinicius** [frontendbr/forum#831]
Pessoal, vocês sabem se na ultima versão do chrome mudou algo referente a propriedade clip-path, tenho um site em produção (https://omegaeducacional.com) que desde a última atualização a regra abaixo deixou de funcionar, mas no firefox e em versões antigas funciona.

```
#slideshow {
    -webkit-clip-path: polygon(0 0,100% 0,100% 92%,51% 100%,0 92%);
    clip-path: polygon(0 0,100% 0,100% 92%,51% 100%,0 92%);
}
```

**Comment by mahenrique94** [comment]
Aqui esta funcionando normal @kivervinicius, também uso em um site que esta em produção, o mesmo ainda continua funcionando.

**Comment by kvnol** [comment]
Aqui também está funcionando normal, estou rodando na última versão do chorme.

**Comment by kivervinicius** [comment]
me desculpem pessoal, verifiquei que estou utilizando a versão beta do linux (Versão 63.0.3239.52 (Versão oficial) beta 64 bits) mas mesmo assim, será que será removido.

**Comment by Theomg** [comment]
É, no windows com o chrome beta (Version 63.0.3239.59 (Official Build) beta (64-bit)) tá quebrado mesmo o clip-path nessa situação, mas não em qualquer situação, o exemplo do mdn funciona normalmente https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path#Result

**Comment by kivervinicius** [comment]
@Theomg obrigado estranho ter quebrado... mas valeu pela solução.

**Comment by kivervinicius** [comment]
Resolvido o problema, mas ainda fica no ar o motivo do problema :(

**Comment by Theomg** [comment]
É possível que isso nem vá ao ar no chrome stable, né.
Talvez seja uma boa reportar como bug, já que não se conforma a especificação, que realmente era pra aplicar em todos os descendentes.
https://drafts.fxtf.org/css-masking-1/#clipping-paths

**Comment by mahenrique94** [comment]
@kivervinicius o motivo do problema é utilizar versão beta, se fosse stable como o @Theomg provavelmente não teria acontecido.

**Comment by kivervinicius** [comment]
Valeu galera!
