### ISSUE TITLE
É um prazer estar aqui!

### ISSUE THREAD

**Issue by igorthurow** [frontendbr/forum#837]
Olá, tudo bem? Eu me chamo Igor e gostaria de dizer que é um imenso prazer (agora) também estar fazendo parte desta maravilhosa comunidade. Gostaria de dizer o porquê:

Sou gaúcho, tenho 23 anos e apaixonado por tecnologia desde cedo, e como muitos aqui, comecei brincando, baixando arquivos pra criar servidor privado de games, baixando página fake lá na época do orkut, formatando o PC da galera que precisava, e assim foi... eu entrei na área de T.I em 2015/2, porém na parte de infraestrutura em uma boa empresa de atuação no Brasil todo, chamada Linx.

Após sair desta empresa em fev. deste ano e passar por um momento conturbado em virtude disto, decidi retomar os estudos de desenvolvimento front, que havia visto na faculdade em 2014/1, antes de trancar naquele mesmo semestre. Confesso que me senti um pouco sozinho nessa caminhada, afinal estou desempregado e sem amigos desenvolvedores, me senti velho pra ingressar na área pois "já" estou com 23 anos.

Porém,  hoje eu não me sinto mais sozinho nessa caminhada, eu vejo que quanto mais eu pesquiso e procuro, mais gente FODA e disposta a ajudar, a motivar, a compartilhar conhecimento, eu encontro. Este fórum, diversos artigos motivacionais e inspiradores, muito conteúdo de qualidade sendo disponibilizado com fácil acessibilidade. Então eu só tenho a agradecer a vocês, comunidade amante desta tecnologia, que fazem desta nossa paixão, algo tão diferente, compartilhado e que abre espaço para novas pessoas adentrarem também.

Neste momento eu sigo estudando e estipulei uma meta de ingressar no mercado de trabalho novamente até fev. Neste momento estou estudando JS principalmente através do curso JS Ninja.
Meu primeiro freela está quase concluído, falta implementar algumas coisinhas e conferir novamente a versão mobile, mas já gostaria de orgulhosamente apresentar a vocês, afinal quem sabe posso ter um feedback bacana? Obrigado novamente! - http://www.actimpermeabilizacao.com.br

**Comment by LFeh** [comment]
Opa, valeu os elogios mano 👊
