### ISSUE TITLE
Como verificar se uma promise já foi resolvida

### ISSUE THREAD

**Issue by robsonbittencourt** [frontendbr/forum#839]
Meu conhecimento sobre promises é intermediário, e hoje cai em um problema novo. Já cheguei em uma possível solução, mas pensei em trazer para cá, pois acredito que a solução não foi muito boa. Se alguém ver uma forma melhor de resolver o problema, por favor poste aqui. Obrigado.

**Problema**

_Cenário 1 - Promise resolve rápido_
- Faz a chamada assíncrona em um ponto do código. 
- Em outro ponto verifica se a promise já esta resolvida
- A promise já está resolvida, executa o callback de sucess

_Cenário 2 - Promise demora a responder_
- Faz a chamada assíncrona em um ponto do código. 
- Em outro ponto verifica se a promise já esta resolvida
- A promise não está resolvida ainda
  - **Espera pelo menos 3 segundos para verificar novamente. Se ela resolver antes não quero saber o resultado, somente depois de 3 segundos.**
   - Depois de 3 segundos verifica novamente se a promise foi resolvida e executa o callback de sucesso quando ela resolver.

**Solução**
https://jsfiddle.net/robsonbittencourt/p3fhu0fb/1/

**Dúvida**
Como pode ser visto no jsfiddle o seguinte trecho

```javascript
let jaExecutou = false;

outputPromise.then(function(result) {
   jaExecutou = true;
});

if (jaExecutou) {
   log('executou rápido...');
   return;
} 
```

é executado de forma assíncrona. Ou seja mesmo que a promise já esteja resolvida neste ponto, a linha seguinte a este trecho, já é executada antes da linha que está dentro do then, e não entra no if. Sei que estou misturando código assíncrono com síncrono, porém neste caso específico a situação é exatamente esta.

Por conta disso a solução que encontrei foi colocar um setTimeout com um valor muito baixo, no código que vem depois desta verificação da promise. 

A dúvida é se teria alguma forma síncrona de fazer isso para evitar o uso deste setTimeout?

Para realizar testes alterem o valor passado para a função `doSomethingAsync` colocando 0 por exemplo.

**Comment by mahenrique94** [comment]
Talvez esse seu IF seja desnecessário, pois se você quer executar algum código apenas se a mesma esta resolvida, então o código deve estar dentro do `.then`assim só será executado quando a mesma estiver sido realizada.

**Comment by Theomg** [comment]
Ou async/await pra escrever o código de maneira síncrona, continuando após a resolução da promise 

https://jsfiddle.net/p3fhu0fb/2/

**Comment by robsonbittencourt** [comment]
Pessoal talvez o problema não tenha ficado claro, pois é chato mesmo :)

O ponto chave é o tempo de espera se a promise não tiver sido resolvida.

Vou colocar alguns casos de uso para exemplificar:

Cenário 1 - Promise resolve rápido
- Faz a chamada assíncrona em um ponto do código. 
- Em outro ponto verifica se a promise já esta resolvida
- A promise já está resolvida, executa o callback de sucess

Cenário 2 - Promise demora a responder
- Faz a chamada assíncrona em um ponto do código. 
- Em outro ponto verifica se a promise já esta resolvida
- A promise não está resolvida ainda
**- Espera pelo menos 3 segundos para verificar novamente. Se ela resolver antes não quero saber o resultado, somente depois de 3 segundos.**
- Depois de 3 segundos verifica novamente se a promise foi resolvida e executa o callback de sucesso quando ela resolver.

**Comment by renatoagds** [comment]
@robsonbittencourt não existe nada na documentação que te mostre o `status` da Promise, a única maneira de saber se a `Promise` já foi resolvida, é pelo `.then`, a outra solução é a maneira apontada pelo @Theomg, você colocar um `await` no seu código, e "bloquear" a execução até a Promise ser resolvida. Olhando pelo que você descreveu no **Cenário 2**, você pode manter o que você está fazendo na descrição da issue, e mudar de `setTimeout` para `setInterval`, com `3000ms` de time. Mas acho que a melhor maneira, seria você adequar seu código para a maneira como a qual funciona a `Promise`. 👍

**Comment by darkfrontcode** [comment]
hey dude, 
Check it out the code below or try it out with codepen link: https://codepen.io/darkfrontcode/pen/EbMgbr?editors=0010

class delay
{
    private time : number
    private counter: number
    private status: boolean

    constructor(time:number)
    {
        this.time = time
        this.counter = 1
        this.status = false
        this.check()
    }

    private async check()
    {
        let result: Promise<boolean>

        while (true)
        {
            let result = await this.doSomethingAsync(this.time)
            console.log(this.status)
            if(result) break
        }
    }

    private pooling(): void
    {
        let interval = setInterval(() => {
            if(this.status) clearInterval(interval)
        }, 300)
    }

    private doSomethingAsync(time:number) : Promise<boolean>
    {   
        return new Promise(resolve => {
            setTimeout(() => {
                if (this.counter == 2)
                {
                    this.status = true
                    resolve(true)
                }
                else
                {
                    this.counter++
                    resolve(false)
                }
            }, time)
        })
    }

}

new delay(3000)

**Comment by kazzkiq** [comment]
Você poderia usar **Observables**.

A ideia é criar um "evento" que será disparado apenas quando sua Promise resolver. No outro ponto do código, você se sobrescreve nesse evento, e assim que ele for disparado dentro da Promise resolvida, seu código "remoto" sabe que deve rodar.

A vantagem é que você não precisa mais ficar checando se a Promise foi resolvida ou não a cada "X" segundos, pois ela mesma vai "avisar" (através do evento disparado).

Como eu só usei isso recentemente no Angular, não consigo te dizer como aplicar esse *pattern* de forma independente, mas com certeza já existem libs mais simples que te permitem usar Observables sem depender de frameworks gigantes.

Para referência:
https://netbasal.com/javascript-observables-under-the-hood-2423f760584

**Comment by gabrieldarezzo** [comment]
Não faz mais sentido simplesmente transformar tudo em callback e tratar caso tenha erro?

**Comment by robsonbittencourt** [comment]
Pessoal, primeiramente gostaria de agradecer a ajuda de todos. Vou postar aqui, algo perto da solução que acabou sendo utilizada.
Lembrando que apesar de um pouco complexa, resolveu o problema que também era um pouco complexo :)

Coloquei em um [fiddle](https://jsfiddle.net/robsonbittencourt/oad3yh5z/) também se alguém quiser brincar.


```javascript
function success(outputPromise) {
  isResolved(outputPromise).then(isResolved => {
    // A promise já estava resolvida
    if (isResolved) {
        log('Finalizou rápido');
    } else {
        // Espera pelo menos 3 segundos utilizando uma promise para isso
        Promise.all([outputPromise, getWaitPromise(3000)]).then(() => {
            log('Finalizou pelo caminho mais lento');
        })
    }
  });
}

// Faz um race com uma promise já resolvida e uma recebida por parâmetro.
// Se a promise que for passada no parâmetro estiver resolvida, o value
// não vai ser $$pending e vice-versa
function isResolved(promise, callback) {
  return Promise.race([promise, Promise.resolve('$$pending')]).then(function(value) {
    return value !== '$$pending';
  }, function() {
    return false;
  });
}

// Retorna uma promise que resolve depois do tempo passado por parâmetro
function getWaitPromise(time) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve();
    }, time);
  });
}

function log(text) {
  console.log(new Date(), ` - ${text}`);
}

log('Iniciou')

// A promise principal resolve depois de 3 segundos
let outputPromise = getWaitPromise(3000);

// Espera-se dois segundos para iniciar
// Com estes valores, espera-se que a promise não esteja resolvida na primeira
// verificação, pois ainda faltará 1 segundo
// O tempo total de execução deve ser 5 segundos. 2 do início e 3 
// do tempo de espera definido.
setTimeout(() => success(outputPromise), 2000);
```

**Comment by LFeh** [comment]
:clap :clap :clap

**Comment by LFeh** [comment]
👏 👏 👏
