### ISSUE TITLE
O Quanto de cada tecnologia eu preciso conhecer?

### ISSUE THREAD

**Issue by Bruno413** [frontendbr/forum#842]
Pessoal, resolvi abrir essa issue pois tenho uma dúvida e acredito que quem está começando também tem. Nas vagas de estágio e júnior pedem o básico que é HTML, CSS e JS, a minha dúvida é: o quanto preciso saber dessas tecnologias? Preciso saber fazer uma página responsiva, uma página comum?
Percebo que conforme aumenta a quantidade de tecnologia, aumenta o nível, mas não sei identificar o quanto de conhecimento da tecnologia as vagas pedem.

**Comment by laurindo** [comment]
Fala @Bruno413 ,

É dificil da uma resposta ao certeira nesse caso. Se é vaga de estágio, geralmente sub entendesse que é o basico de html, css e JS. Se espera que você tenha noção do básico e consiga ir evoluindo com o tempo de experiência.

Eu acredito que o importante é você sempre ir estudando padrões(design patterns, aplicações SPA, design responsivo, atomic design, sempre pesquisar o que tem de novo pra CSS, JS, HTML, MVC).

Se você é um cara que está ligado nesses conceitos, pelo menos ouviu falar, leu e aplicou em algum teste básico, isso te torna um cara diferenciado. 

A medida que você vai lendo sobre isso, mais você acha que ainda não sabe de nada, mas ao mesmo tempo você está se alimentando de muita informação bacana onde você estará confiante pra entrar em projetos grandes, capaz de criar aplicações mais robustas, etc.

Não sei se isso responde a sua pergunta, mas realmente é dificil dizer "quanto de conhecimento as vagas pedem".

Negocio é ir estudando e ir testando essas diferentes tecnologias.

**Comment by felipeqburian** [comment]
Como o amigo disse acima, é difícil abordar o necessário para o que as empresas pedem, pois, cada uma tem uma demanda específica sobre determinado conhecimento, que normalmente é muito mais amplo do que as pessoas acham que ele realmente é. 

O importante é saber, se você busca saber, é questão de tempo para você ter o conhecimento, mas se você quer saber primeiro o que é 'mais pedido', sugiro que veja o vídeo abaixo que achei interessantíssimo sobre o assunto..

https://www.youtube.com/watch?v=nfk3G3VB0OY

Boa sorte! Vale ver mais vídeos do Front in Sampa caso tu queira entrar de vez nisso!

**Comment by Bruno413** [comment]
@laurindo  e @felipeqburian muito obrigado pelas respostas de vcs, vou continuar me aprofundando na base e ficar de olho  no que está sendo pedido nas vagas, e vou acompanhar os das talks, valew

**Comment by didiraja** [comment]
Bruno, dica de quem também está começando: Essas três são os pilares, então essas são as que voce mais tem que dominar. Quanto mais souber melhor, o **IDEAL** acredito seria domínio intermediário chegando ao avançado. O **NECESSÁRIO** pra você trabalhar, acho que é basicamente não ter medo de ver esses códigos e saber se virar quando te pedem algo.

Sobre essa divisão de Básico, Intermediário e Avançado tem um roadmap top na issue #815  

P.S. Não sou nenhum dos dois, estou caminho para o nível necessário mas é o que percebo olhando aqui o fórum e vagas de emprego.

**Comment by felipebernardes** [comment]
fala @Bruno413 !

cara, minha dica pra você é: apenas comece. Ponha em prática o que você aprender. Se você aprendeu fazer responsividade, faça.

crie um site pra você. Vá melhorando-o conforme for aprendendo.

se souber coloá-lo no github, coloque e mande o link junto com seu currículo. Se não souber usar git/github, mande zipado mesmo.

o mais importante é: aplique o que você aprender -> aprenda mais -> se aplique a vagas -> repita isso infinitamente, independente de ser estag, jr, pleno ou senior. nunca pare.

boa sorte, e caso tenha qualquer dúvida mais pontual sobre algo que queira/esteja aprendendo, pergunte aqui no fórum.

abraço!

**Comment by Charlinho** [comment]
@Bruno413 

Cara a minha dica segue o que os demais falaram aqui.
Apenas comece, tente fazer algo simples com algumas tecnologias que te interessa aprender, depois disso você vai avançando com casos mais complexos.

Mas a melhor maneira de vc aprender de fato e trabalhar/estudar todos dias assim vc vai consolidar o conhecimento aprendindo.

Forte abraço!

**Comment by leandroruel** [comment]
@Bruno413 por coincidência li um artigo hoje falando disso, sobre tecnologias emergindo e sobre desenvolvedores iniciantes ficando estressados com tanta coisa para se aprender, quando na verdade devem se focar no básico primeiro. nos pilares.

**Comment by Bruno413** [comment]
Obrigado pelas dicas galera :D 👍
