### ISSUE TITLE
FB Open Graph: propriedade não pertinente

### ISSUE THREAD

**Issue by kvnol** [frontendbr/forum#844]
Bueno, pessoal.

Então, estou implementando o Facebook Open Graph no @devnspiration e na página de artigos (que conteria o `og:type=article` está retornando a seguinte mensagem no debugger: 

> **Propriedades não pertinentes especificadas**
As propriedades a seguir estão especificadas na página da Web, mas NÃO são aceitas para o "og:type" especificado: article:author, article:section, article:tag, article:published_time
(Como mostra o print abaixo)

Sendo que, na própria documentação, eles pedem para implementar com essas tags. Com vocês também está acontecendo isso?

![print do erro citado no debugger do facebook open graph](https://user-images.githubusercontent.com/3299130/33673311-8db812c8-da93-11e7-8d8d-eabd9497dea3.png)

**Comment by LFeh** [comment]
Delegando: @eduardojmatos

**Comment by kvnol** [comment]
***Update:*** fiz um teste com uma [notícia do New York Times](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.nytimes.com%2F2017%2F12%2F06%2Fworld%2Fmiddleeast%2Ftrump-jerusalem-israel-capital.html) e está dando o mesmo problema, Open Graph está bugado mesmo.

**Comment by Theomg** [comment]
Mas a situação do NYTimes parece diferente da sua, o artigo deles tá sendo identificado com type article, o seu aparece como website.

As propriedades do article que ele reclama pro artigo deles realmente não são válidas de acordo com o facebook (https://developers.facebook.com/docs/reference/opengraph/object-type/article/),
enquanto o seu ele tá ignorando as propriedades válidas por não se encaixar no type certo, não?

Só não entendi o porque dele ignorar seu og:type.

**Comment by kvnol** [comment]
@Theomg, sim, percebi que o Debugger está identificando o meu com `og:type=website`, mas ambos estão com o mesmo erro. Vou fazer uns testes no posicionamento desta tag para ver se isso muda.

**Comment by jhonnymoreira** [comment]
Pelo o que vi em uma das mensagens ao ver o OGD:

"The parser's result for this metadata did not match the input metadata. Likely, this was caused by the data being ordered in an unexpected way, multiple values being given for a property only expecting a single value, or property values for a given property being mismatched. Here are the input properties that were not seen in the parsed result: 'fb:app_id, article:author, article:section, article:tag, article:published_time, og:site_name, og:locale:locale'"

![screenshot from 2017-12-07 18-08-25](https://user-images.githubusercontent.com/2177742/33736671-9c9d356a-db7a-11e7-8253-886cfb19b378.png)

Ao tentar acessar os namespaces (`fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#`) presentes no HEAD, ele me retorna esse conteudo:

```json
{
   "error": {
      "message": "An access token is required to request this resource.",
      "type": "OAuthException",
      "code": 104,
      "fbtrace_id": "Bv8MYLoJEAS"
   }
}
```

E nisso eu devo perguntar: Se ao tentar acessar dá isso, o seu site não precisaria colocar um token específico pra ter acesso a esses namespaces ou isso é só ao tentar o acesso direto?

Outra tentativa, colocar nessa ordem:

`og:type`
`og:description`

**Comment by jhonnymoreira** [comment]
Btw, o snippet do nytimes:

```html
<meta property="og:url" content="https://www.nytimes.com/2017/12/07/us/california-fire-ventura-county.html" />
<meta property="og:type" content="article" />
<meta property="og:title" content="Southern California Fires Live Updates: More Areas Under Siege as Wind Gains Strength" />
<meta property="og:description" content="Emergency crews in the Los Angeles area were contending with brisk winds, steep terrain and fatigue from days of relentless work." />
<meta property="article:published" itemprop="datePublished" content="2017-12-07T09:55:15-05:00" />
<meta property="article:modified" itemprop="dateModified" content="2017-12-07T15:22:58-05:00" />
<meta property="article:section" itemprop="articleSection" content="U.S." />
<meta property="article:section-taxonomy-id" itemprop="articleSection" content="23FD6C8B-62D5-4CEA-A331-6C2A9A1223BE" />
<meta property="article:section_url" content="https://www.nytimes.com/section/us" />
<meta property="article:top-level-section" content="us" />
<meta property="fb:app_id" content="9869919170" />
```

**Comment by jhonnymoreira** [comment]
E é válido notar que esse é o exemplo do IMDb na página do OpenGraph:
```html
<html prefix="og: http://ogp.me/ns#">
```
O seu está assim:
```html
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
```

Isso quer dizer o seguinte, segundo a especificação do RDFa: Olha, esse trecho aqui eu eu to colocando `prefix`, caso não seja compreendido o vocabulário, essa é a língua que eu to falando.

O teu `prefix` está especificado para o `head` não para a tua page inteira (`html`).

E isso vai resolver.

**Comment by jhonnymoreira** [comment]
Desculpa vários comentários seguidos, mas o último mata o teu problema hahahahahahaha

**Comment by Theomg** [comment]
Se esse for o fix e for o comportamento correto, então tá errada a [documentação do facebook](https://developers.facebook.com/docs/reference/opengraph/object-type/article/) que mostra:

```html
 <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
  <meta property="fb:app_id" content="302184056577324" /> 
  <meta property="og:type"   content="article" /> 
  <meta property="og:url"    content="Put your own URL to the object here" /> 
  <meta property="og:title"  content="Sample Article" /> 
  <meta property="og:image"  content="https://s-static.ak.fbcdn.net/images/devsite/attachment_blank.png" />

**Comment by kvnol** [comment]
Pois é, segui a documentação do Facebook, mas vou testar.

**Comment by kvnol** [comment]
Testei as sugestões do @jhonnymoreira, mas ainda assim ele não reconhece a página como `og:type=article`, muito estranho isso.

**Comment by Theomg** [comment]
Se você pede para "Buscar novas informações de verificação" na página de object debugging, ele mostra o erro de verdade, que é:

`O objeto na URL "https://devnspiration.com/blog/input-boas-praticas" do tipo "article" é inválido porque o valor "pt-br" fornecido para a propriedade "og:locale:locale" não pôde ser analisado como o tipo "enum".
`

O valor correto seria `pt_BR` ao invés de `pt-br`.

**Comment by kvnol** [comment]
Caramba, @Theomg, que mancada a minha. [Funcionou certinho com esse ajuste na `og:locale`](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fdevnspiration.com%2Fblog%2Finput-boas-praticas).

Valeu, galera, vocês são fodas. :heart:

**Comment by eduardojmatos** [comment]
Que show, nem precisei responder @LFeh huahuauha

Esse fórum é foda <3

**Comment by LFeh** [comment]
Essa galera é monstra demais!

**Comment by editorasegmento** [comment]
Estou com um problema semelhante mas não igual.

seria possivel um Help, 

a saida do Debug é a seguinte 

<meta charset="UTF-8" />
<meta property="og:url" content="/paises-educacao-excelencia/" />
<meta property="og:title" content="Quatro países com educação de ponta que servem de inspiração e alerta" />
<meta property="og:description" content="" />
<meta property="og:image" content="" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
<meta name="description" content="Coreia do Sul, China, Finlândia e Estônia têm seus ensinos reconhecidos em avaliações internacionais com modelos de educação distintos" />
<meta property="og:locale" content="pt_BR" />
<meta property="og:type" content="article" />
<meta property="og:title" content="Quatro países com educação de ponta servem de inspiração e alerta" />
<meta property="og:description" content="Coreia do Sul, China, Finlândia e Estônia têm seus ensinos reconhecidos em avaliações internacionais com modelos de educação distintos" />
<meta property="og:url" content="http://www.revistaeducacao.com.br/paises-educacao-excelencia/" />
<meta property="og:site_name" content="Revista Educação" />
<meta property="article:publisher" content="https://www.facebook.com/revistaeducacao" />
<meta property="article:tag" content="destaque" />
<meta property="article:section" content="Edição 254" />
<meta property="article:published_time" content="2018-11-27T11:00:52+00:00" />
<meta property="article:modified_time" content="2018-11-27T14:39:00+00:00" />
<meta property="og:updated_time" content="2018-11-27T14:39:00+00:00" />
<meta property="fb:app_id" content="966242223397117" />
<meta property="og:image" content="http://www.revistaeducacao.com.br/wp-content/uploads/2018/11/Na-Finlândia-ensino-é-direcionado-às-competências-futuras-e-às-habilidades-contemporâneas-dos-alunos.jpg" />
<meta property="og:image:width" content="469" />
<meta property="og:image:height" content="354" />
<meta property="og:image:alt" content="Entenda a educação na Finlândia" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:description" content="Coreia do Sul, China, Finlândia e Estônia têm seus ensinos reconhecidos em avaliações internacionais com modelos de educação distintos" />
<meta name="twitter:title" content="Quatro países com educação de ponta servem de inspiração e alerta" />
<meta name="twitter:site" content="@revistaeducacao" />
<meta name="twitter:image" content="http://www.revistaeducacao.com.br/wp-content/uploads/2018/11/Na-Finlândia-ensino-é-direcionado-às-competências-futuras-e-às-habilidades-contemporâneas-dos-alunos.jpg" />
<meta name="twitter:creator" content="@revistaeducacao" />
<meta property="fb:app_id" content="639851609497742" />



e o erro apontado é 
As propriedades a seguir estão especificadas na página da Web, mas NÃO são aceitas para o "og:type" especificado: article:publisher, article:tag, article:section, article:published_time, article:modified_time



**a pergunta não pesquisando não consegui solucionar é, se essas informações não são aceitas quais seriam aceitas ??**

**Comment by tardelipires** [comment]
Sei que faz tempo o topico, mas gostaria de saber se vocs poderiam me ajudar, estou com um problema semelhante no meu blog, seu a mensagem:

"As propriedades a seguir estão especificadas na página da Web, mas NÃO são aceitas para o "og:type" especificado: fb:page_id"

"Propriedades ausentes: As duas propriedades obrigatórias a seguir estão ausentes: og:type"
