### ISSUE TITLE
Selecionar path id de um svg

### ISSUE THREAD

**Issue by fredmosc** [frontendbr/forum#845]
Bom dia pessoal,

tenho varios svg na minha pagina, nesse estilo: 

https://pastebin.com/tJGpmaNV

Preciso que ao clicar em qualquer um desses SVG, pegar o id do path clicado. To aqui quebrando a cabeça para fazer isso com JS puro, mas quando clico em um ele pega todos os Id's te todos os svg.

**Comment by Theomg** [comment]
Seria isso aqui, ou entendi errado?
https://jsfiddle.net/gz8cppr2/

**Comment by fredmosc** [comment]
@Theomg isso mesmo, obrigado! To migrando do back pro front, tinha tempo q nao mexia com essas coisas. vlw

**Comment by LFeh** [comment]
Rápidos, rs
