### ISSUE TITLE
Como substituir a jQuery utilizando JS Vanilla?

### ISSUE THREAD

**Issue by diogorodrigues** [frontendbr/forum#849]
Fala galera!

**Já faz um tempo que venho estudando JS com mais intensidade, mas a questão que sempre me deparo é: como substituir a jQuery, uma vez que sempre leio "aprenda JS puro e não use jQuery por causa disso, por causa daquilo..."?**

Fazendo um panorama geral da minha experiência com JS:

Ao longo da minha carreira sempre começava a estudar JS e por algum motivo sempre acabava desistindo, ora porque eu voltava para a zona de conforto utilizando jQuery, ora porque abordava assuntos mais complexos que eu não fazia muito ideia do que estava aprendendo de fato.

Esse cenário mudou quando conheci o curso do @fdaciuk (olha o jabá). Digo que mudou porque eu passei a estudar JS por outra perspectiva: antes eu estava mais interessado em aprender JS para manipular o DOM; e com o curso passei a focar mais na linguagem em si. E essa mudança fez com que eu passasse a gostar de aprender JS, pois, de fato, passei a entender mais os frameworks e lidar com JS Vanilla em mais trechos de códigos em meu dia-a-dia. Por exemplo: uma vez precisei utilizar a função some() em um projeto - me senti o máximo pois tinha acabado de aprender isso no curso do @fdaciuk . =D

E não parei por aí. O curso me ajudou bastante a entender muitas coisas da linguagem: JS funcional, objetos, arrays, funções...

Logo depois, quando eu já tinha um conhecimento mais interessante, li o livro "Segredos do Ninja Javascript", onde pude realmente entender mais sobre closure, funções (e seus 4 modos de invocação, principalmente com call() e apply()), objetos e todo seu poder, temporizadores, problemas cross-browser e como resolvê-los... 

A partir daí consegui entender e utilizar o Revealing Module Pattern para modularizar o JS do [Iceberg Boilerplate](https://github.com/diogorodrigues/iceberg-boilerplate), um projeto que desenvolvi para treinar o que venho aprendendo e também para usá-lo no meu dia-a-dia.

Hoje, apesar de eu ainda estar aprendendo a utilizar AJAX e promises, consigo entender mais o Angular, por exemplo. Mas a pergunta que sempre fica após tudo isso é: como vocês fazem para substituir a JQuery -pois ainda não vejo uma alternativa utilizando JS puro em meus projetos, mediante a dificuldade e problemas cross-browser? Como vocês lidam com esses problemas? É realmente necessário substituir a jQuery quando estamos lidando com o DOM - a não ser quando utilizamos um framework ou libray? Sobre o conhecimento de JS puro para trabalhar com o DOM, o que vocês levam em consideração?

É isso pessoal! Compartilhem suas experiências comigo e me ajudem a entender mais essa questão.  =D

**Comment by Charlinho** [comment]
Dominar o JS puro é essencial na minha opiniâo, mas acho que vc não precisar ser um cara tão radical ao ponto de não querer usar frameworks JS.

Ao meu ver quando se fala: "Estude JS e não o framework", nada mais é que entenda como framework funciona, entenda o que o JS puro está fazendo por tras do framework, isso pra mim é o que importa de verdade, conhecer a linguagem ao ponto de conseguir trabalhar sem o framework, mas utilizar um jQuery por exemplo não é ruim, desde que vc saiba o que ele está fazendo de fato.

**Comment by fdaciuk** [comment]
Penso exatamente da mesma forma que o @LFeh e o @Charlinho! O problema não é usar jQuery (ou qualquer lib/framework), mas simplesmente usá-lo sem conhecer JS.

Quando você conhece JS puro, você sabe quais problemas a lib que vc quer usar vai resolver. Esse é o ponto principal. Libs são criadas para agilizar nosso trabalho como dev. Não devemos nos apegar a elas, mas entender os problemas que elas resolvem, e usá-las a nosso favor =)

**Comment by doug2k1** [comment]
Um site interessante, que mostra como fazer com JS puro o que o jQuery faz: http://youmightnotneedjquery.com/

Outra dica é, se você precisa só de uma parte das funcionalidades do jQuery, pode usar outra lib mais específica. Por exemplo, usar [axios](https://www.npmjs.com/package/axios) ou [whatwg-fetch](https://www.npmjs.com/package/whatwg-fetch) pra fazer requisições Ajax.

**Comment by Theomg** [comment]
Um complemento legal e mais atualizado pra o [You might not need jQuery](http://youmightnotneedjquery.com/) é [esse artigo do css-tricks](https://css-tricks.com/now-ever-might-not-need-jquery/) que mostra coisas como fetch, já que esse site é mais antiguinho.

**Comment by jmlavoier** [comment]
E ai @diogorodrigues! Excelente assunto. 

Acredito que o jQuery é uma ótima ferramenta que facilita e ajuda na sua produtividade, porém ela te impossibilita de navegar a fundo no conhecimento do JS. Por isso, eu tenho a mesma posição que o @LFeh, precisa entregar algo pra ontem? Não vai inventar a roda né. Pelo que li no seu questionamento, você até um bom conhecimento do onde você pode chegar com o JS, talvez falta mais pratica para você sentir o quanto vale a pena. 

Eu escrevi um artigo relatando minhas experiência em deixar o jQuery pra trás, os conhecimentos que isso me proporcionou, vale a pena dar uma lida, acredito que se encaixa direitinho com sua dúvida, e pode te tirar bastante dúvidas, e até te encorajar a se aventurar mais no Vanilla. 

[Vivendo sem jQuery - parte 1](https://medium.com/iclinic/vivendo-sem-jquery-parte-1-de4ed1efa5bf)
[Vivendo sem jQuery - parte 2](https://medium.com/iclinic/vivendo-sem-jquery-parte-2-d64652908f13)

**Neles eu aborto assuntos como:**

**Parte 1**
- Introdução à API DOM
- Acessando elementos DOM
- Manipulação do DOM
- Eventos

**Parte 2**
- Ajax
- Animation
- Polyfill
- Apresentação do React

> Aprender e crescer como desenvolvedor ganhando skills com a experiência, acredito que é um ótimo argumento para se pensar.

Abração.

**Comment by lBrunol** [comment]
Ainda hoje uso jQuery. É muito do que o pessoal falou acima, depende do projeto, das exigências e do tempo. Na empresa onde eu trabalhava, praticamente todos os sites exigiam compatibilidade com o IE 9, alguns até com o IE8.

Outra coisa que impediu que abandonassemos o jQuery é a quantidade de plugins que ele tem, carousel, máscara de formulário, validação, várias vezes nós precisamos extrair funcionalidades complexas que levam um pouco de tempo para serem desenvolvidas em Vanilla JS. 

Outra coisa importante a ser falada é que jQuery foi muito importante para o desenvolvimento Web, ajudou muitos Devs a simplificar o trabalho e a tornar os sites mais 'parrudos' em termos de funcionalidade. Então não dê ouvidos aos haters, veja a necessidade do projeto, tempo e requisitos de compatibilidade.

Por último, mas não menos importante, sempre separe um tempo para aprender javascript puro e se puder, entenda o que acontece por trás dos panos nas libs que você usa, até porque frameworks e bibliotecas morrem e são substituídos, mas o javascript vai continuar vivo por muito tempo.

**Comment by mahenrique94** [comment]
Fala ai @diogorodrigues já faz alguns meses que retirei o jQuery de todos os projetos particulares e do trabalho, particularmente não vejo porque usar jQuery sendo que tudo pode ser feito de forma simplista com JavaScript puro, o motivo da retirada do jQuery foi por questões de bug, apresentava comportamentos diferentes na mesma função em diferentes navegadores, então cheguei a conclusão "vou fazer com js puro, assim todos os navegadores irão entender, depois da retirada e refatorada de código, nunca mais tive problemas.

Para você conseguir o mesmo feito, acredito que deva saber JavaScripit puro, não precisa dominar, pois conforme a necessidade novos conhecimentos irão sendo adquiridos e necessários, apenas precisa saber um tanto quanto intermediário.

Acho que dificilmente eu usaria jQuery nos dias de hoje, essa seria minha opinião e experiência vivida com o mesmo, abraçooos \o/

**Comment by diogorodrigues** [comment]
Fala galera! Obrigado pelos feedbacks.

Então @LFeh, @Charlinho e @fdaciuk . Realmente, percebo a cada dia o quanto é importante entender melhor JS para lidar com frameworks e libs de modo mais fácil e fluído, sabendo o que se está sendo feito de fato. 

Mas é essa questão do uso do jQuery que me incomoda, pois para mim ele atende perfeitamente nos projetos que desenvolvo no dia-a-dia - com exceção de soluções utilizando o Angular aqui na empresa, que utilizamos typescript e as funcionalidades do Angular (mas, nesse caso, não se trata também de JS Vanilla).

Muito legal esse site heim @doug2k1 , não conhecia. Através dele já é possível ver o quão complexo é utilizar JS puro em projetos que dependem muito do JQuery - justamente pelo que foi citado pelo @lBrunol . Mas em contradição a esse meu pensamento, vou ler mais atentamente as dicas do @jmlavoier e ver como posso fazer alguns experimentos sem jQuery, mesmo que seja apenas para fixar algumas coisas na mente.

@mahenrique94 interessante. Lendo seu comentário até tive uma ideia de criar um repositório de soluções com JS puro conforme eu for lidando com os problemas e descobrindo novas soluções. Assim, aproveito para colocar em prática o que já sei, aprender coisas novas e deixar o código lá para uso futuro ou para outras pessoas. ;)

**Comment by munizart** [comment]
@diogorodrigues ótima thread!

Pra acrescentar ao papo de "jQuery faz sentido ser usado para algumas situações" vale citar também que o jQuery tem uma filosofia por traz dele, que dependendo do projeto é muito bem vinda, que é a de ser um lib monádica.

Isso por que todo objeto jQuery é um monad e a maioria dos métodos são functores.
Na pratica isso significa que o jQuery te ajuda a escrever o código de um jeito bem mais funcional, enquanto ele lida com os side-effects da manipulação do DOM. Ou seja, você escreve funções puras e o jQuery faz a parte impura pra você.

Exemplo:
```javascript
function upperCase2ndArg (ignored, string) {
  return string.toUpperCase()
}

$('.my-text').text(upperCase2ndArg)
```
O exemplo acima transforma todos os elementos com a classe `my-text` para upper case sem precisar ter escrito nenhuma função impura.

É legal tentar sempre entender a filosofia por traz de um lib/framework além do problema que ele resolve antes de tomar a decisão de usar ou não em um projeto.

**Comment by ninetails** [comment]
Sempre bom lembrar que a motivação inicial do movimento pra não utilizar mais jQuery foi o fato de que agora os browsers possuem suporte a seletores css (usando querySelector), fetch API pra substituir o AJAX, tornando-o redundante ocupando memória e banda desnecessária pro usuário para uso em casos triviais.

**Comment by LFeh** [comment]
@ninetails Bem colocado.

E continuo batendo na tecla do **browser modernos**, nem sempre é o cenário de developers.

**Comment by isaacguerreir** [comment]
Bom, primeiramente ótima pergunta! Inclusive eu acho que existe muitas coisas interessante a pontuar sobre isso.

jQuery é uma biblioteca JavaScript. Ela foi criada para abstrair várias funções que desenvolvedores achavam serem comuns no desenvolvimento de aplicações web. Ela tem uma própria estrutura lexical ($) e funções próprias. Isso é muito útil, pois elimina do desenvolvedores uma série de decisões (mais especificamente como realizar ações no DOM via JavaScript) que deveriam tomar para alcançar aquilo que se desejava. Entretanto, como toda a abstração, você deixa de aprender como e porque certas coisas existem e acontecem debaixo dos panos. Mas lembre-se, o JavaScript é uma abstração, assim como todas as linguagens de programação.

Cenário

Atualmente existe todo um movimento para entender melhor não só o JavaScript e o DOM, mas também como ele funciona por baixo dos panos (ahá!) e como é possível construir ferramentas melhores (e não menos complexas).  Javascript também saiu do ambiente web e agora acessa outras áreas (de embarcados a redes neurais), graças principalmente ao Node, que deu a possibilidade real das pessoas usarem JS fora do browser e poder criar basicamente qualquer coisa. Então não é nenhuma surpresa que as pessoas agora querem conhecer a fundo como funciona esse negócio de "JS Puro".

Por isso eu recomendo que você não fique inseguro sobre usar ou não jQuery. No final essa ideia de usar JS puro ao invés de jQuery é muito mais parte do ecossistema que a gente vive hoje do que necessariamente porque um é melhor que o outro. Use-o! Faça bom proveito dele e decida você mesmo o que você quer usar/aprender/contribuir.

**Comment by diogorodrigues** [comment]
Obrigado pela super explicação @isaacguerreir Já se vê pelo seu comentário o quanto aprender JS puro realmente tem se tornado importante.

@ninetails estou procurando entender mais sobre essas novas features, inclusive, aqui no meu serviço ajudei a implementar um recurso de carregamento de arquivos JS e CSS de modo assíncrono e definir a ordem de carregamento deles usando promises. =D

Obrigado pela dica @munizart . Ainda não tinha pensado por esse lado.

**Comment by TiagoFuelber** [comment]
Não sei se é off-topic, mas enfim, postaram esse link hoje em outro fórum achei muito massa. São desafios com javascript vanilla. https://javascript30.com/

**Comment by diogorodrigues** [comment]
Caraca, que show @TiagoFuelber Obrigado por compartilhar.

**Comment by diessica** [comment]
só uso jquery se faço um freela e quem vai manter são pessoas que só sabem jquery. 

**como assim não ficar inseguro em usar jquery?** é uma biblioteca gigante que faz coisa pra caramba e vai dizer como seu projeto será escrito; afinal, como o pessoal falou aí, tem uma filosofia por trás dele que você vai ter que levar até o fim. tem que pensar duas vezes; não precisa pensar tanto, mas pensa duas vezes.

eu escolho módulos (_"tiny libraries"_) separados que fazem as coisas que preciso, conforme preciso. eu escrevi um pouco sobre isso uma vez: https://diessi.ca/blog/o-que-ha-de-errado-com-a-cultura-jquery/ está meio desatualizado, mas acho que até dei ideia de alguns módulos.

não tem nada de errado em usar jquery mesmo, mas ele faz coisa demais e prefiro ir plugando o que preciso – exploro o ecossistema, uso coisa melhor  (tipo o [axios](https://github.com/axios/axios)) e de quebra ainda economizo uns kbs! :P

**Comment by ninetails** [comment]
Acho que o maior problema em não usar jQuery e usar o nativo é depender de polyfill dependendo da feature, se for algo muito novo. Nisso acaba gerando outro problema que é o gerenciamento de polyfill, que se for granularizar e não botar todo o pacote do core-js no bundle, é tentar fazer algo parecido com o serviço de polyfill tipo do [Financial Times](https://github.com/Financial-Times/polyfill-service), mas aí entra pra outra discussão.

Também pra quem não quer abandonar, aproveitando o que foi dito, tem a alternativa ao jQuery lightweight chamado [Cheerio](https://github.com/cheeriojs/cheerio). Hj eles se dizem alternativa jQuery para servidor, mas quando eu conheci, diziam eles que era uma alternativa lightweight pro navegador tb, não sei como tá hj.

@diogorodrigues legal :D alias, se o que vcs fizeram não for core do teu business (não tiver implicações legais/juridícas em publicar), bota no github, mesmo caso ninguém veja ou contribua, é sempre bom ter online como referência. Sempre me bate um arrependimento quando lembro que fiz algo legal e não subi pra um repositório e provavelmente teria que fazer de novo do zero :\

**Comment by diogorodrigues** [comment]
Obrigado pela dica @ninetails :)

**Comment by diogorodrigues** [comment]
Pessoal, na Udacity descobri alguns cursos bem interessantes sobre JS:


#ficaAdica ;)

**Comment by diogorodrigues** [comment]
Tinha fechado sem querer. Foi malz!

**Comment by yanmagale** [comment]
"Foco no projeto, não na tecnologia" - Sábias palavras do @LFeh 

E como ele bem disse, **browsers modernos** não são a realidade da maioria dos developers.

Tem uma série de questões ai: compatibilidade, prazo ... 

Se a ferramenta em questão esta te ajudando nos seus projetos e suas entregas, por quê parar de usa-la ?

Mas sim, mega importante você aprender como as coisas funcionam. Até porque, se você precisar de alguma feature que a ferramenta não provê, você vai precisar do JS Puro para poder fazer aquilo que precisa :smile: 


Ferramentas são apenas um meio para nos auxilar a fazer uma tarefa :smile:
