### ISSUE TITLE
Definir página inicial em um PWA usando SPA

### ISSUE THREAD

**Issue by felipefialho** [frontendbr/forum#852]
Boa tarde pessoal,

Estou criando uma estrutura básica de PWA para uma aplicação. Estamos usando Angular como framework frontender.

O caso é que está tudo funcionando bem, porém se eu altero o `"start_url": "/",` dentro do `manifest.json` e coloco por exemplo, `"start_url": "/app"`, acusa um erro no [Lighthouse](https://developers.google.com/web/tools/lighthouse/?hl=pt-br).

![screen shot 2017-12-12 at 2 07 42 pm](https://user-images.githubusercontent.com/3603793/33894730-d88464d0-df45-11e7-8c5d-0a24b0eaf0cf.png)

Acredito que por se tratar de uma Single Page Application, o erro ocorre pois o `index.html` não é encontrado nesse path. 

Alguém já passou por essa dificuldade?

**Comment by joselitojunior1** [comment]
Felipe, ao acessar `meuapp.com/app` diretamente, sem cache sem nada, a rota funciona?

Se não, é por isso. Se sim, eu ainda não entendo o que exatamente seria. O SW está em `/`, certo? Em teoria ele pega o escopo inteiro.

**Comment by LFeh** [comment]
@joselitojunior1 Funciona sim. Tanto que se eu for no DevTools, entrar no manifesto e clicar no link, ele abre normalmente.

Também acho que devia pegar o escopo inteiro. Mas o fato é que só funciona, se coloco na raiz. Porém ainda não testei no PWA no celular, estou usando o Lighthouse para verificar a auditoria primeiro.

**Comment by LFeh** [comment]
Puts, descobri o problema, como grande parte das coisas em desenvolvimento, era a solução mais boba possível.

Como não é possivel rodar o PWA diretamente em dev, precisa buildar o projeto e rodar um `http-server` depois. 

O que acontece, é que consigo navegar normalmente nas páginas, mas se acesso diretamente `/app`, rola um 404. A solução foi mudar o `http-server` para um que tenha suporte a SPAs.

Valeu! 🎉

**Comment by waldemirflj** [comment]
@LFeh compartilha o esqueleto dessa arquitetura, tem como?

**Comment by LFeh** [comment]
@waldemirflj Do Angular?

**Comment by waldemirflj** [comment]
@LFeh  tbm, digo do PWA + Angular... Eu estou estudando e até o momento estou fazendo com .html puro mesmo. O Angular que vc está usando é o 4/5 ou JS?

**Comment by LFeh** [comment]
Nesse momento estamos usando a `5.1.0`.

Mas não tem muito segredo com relação a estrutura. Estamos usando a default do Angular, com lazyload e adicionamos um básico (`manifest.json` e `service work`) de PWA agora.

**Comment by leandroruel** [comment]
depois faz um artigo ai nos dizendo como foi fazer esse PWA, como tem muita gente noob no assunto :) (like me)
