### ISSUE TITLE
Rastreamento / Telemetria de interface

### ISSUE THREAD

**Issue by kivervinicius** [frontendbr/forum#856]
Galera, já pesquisaram ou viram algo referente a rastreio ou telemetria comportamental do usuário em uma interface web? Por exemplo como grandes e-commerce sabem que um botão azul vende mais que o verde por exemplo. Gostaria de coletar todas informações que o usuário faz no meu sistema desde onde clica por onde acessa e por ai vai. Existe algum software/método/forma/hadouken que possa me ajudar a entender melhor este processo.

**Comment by laurindo** [comment]
Fala @kivervinicius ,
Não sei muito sobre o assunto, mas acredito que o que voce procura é relacionado a Teste A/B.
Segue um link que acho que pode ajudar: https://www.optimizely.com/optimization-glossary/ab-testing/

**Comment by kivervinicius** [comment]
Opa @laurindo, então citei o caso do botão como exemplo, o caso do test a/b é bem especifico mesmo para saber se tal tela é mais utilizada que a outra, por exemplo, mas caso eu quisesse analisar o comportamento do usuário na página tipo, se ele clicou na parte da direita da página se ele arrastou um conteúdo, algo assim.

**Comment by phsantiago** [comment]
Um teste A/B resolve isso do botão azul, você pode fazer desta forma: metrificando com google analytics quantos acessos você tem no total, disparando um evento para o analytics que diz qual a cor do botão o usuário está vendo, e disparando um evento para a conversão da sua aplicação, por exemplo, quando a ordem de compra está feita. No analytics você consegue ver fácil de todo mundo que entrou qual a maior taxa de compra para cada cor.

Uma outra ferramenta muito legal para você melhorar a experiencia dos seus usuários é o [Hotjar](https://www.hotjar.com/). Com ele você tem mapas de calor para clicks, como esse:
![image](https://user-images.githubusercontent.com/10498833/34021523-8f615294-e121-11e7-81cd-17bbec5b9ae0.png)

Com o Hotjar você também pode ver gravações dos usuários navegando no seu site, isso permite ver muitas coisas legais e entender melhor como os usuários estão usando sua interface.

**Comment by kivervinicius** [comment]
@phsantiago valeu era isso q eu estava procurando o hotjar, muito obrigado

**Comment by gabrieldarezzo** [comment]
Recomendo fortemente ouvir:

https://hipsters.tech/testes-ab-hipsters-59/
https://hipsters.tech/ux-pesquisa-com-o-usuario-hipsters-44/

**Comment by munizart** [comment]
[off] Lembrando que todas esses serviços de rastreamento/telemetria externos podem (e vão) repassar os dados de comportamento dos seus usuários para terceiros.
Além disso se a infraestrutura desses serviços for comprometida, seu site fica vulnerável a XSS.
Sempre se lembre de importar scripts de estranhos usando HTTPS, já que isso ajuda a mitigar as chances de um MITM.
