### ISSUE TITLE
Eventos em Floripa?

### ISSUE THREAD

**Issue by KumoMg** [frontendbr/forum#858]
Boa tarde a todos!

Navegando pela internet eu acabei encontrando um evento bem legal chamado de [Floripajs](http://floripajs.org), por isso eu gostaria de perguntar pra galera do forum se vocês conhecem algum evento nesse estilo que costuma ocorrer em Florianópolis na primeira metade do ano ?

**Comment by lucasfcosta** [comment]
Olá @KumoMg! Tudo bom?

O FloripaJS costuma ocorrer mais ou menos uma vez a cada 1 mês e meio. Como somos um Meetup os encontros são recorrentes 😄 

Recomendo muito que você [dê um "join" lá no nosso grupo do Meetup.com](https://www.meetup.com/floripajs/).

Além disso tem também o [FrontInFloripa](http://frontinfloripa.com.br/) que costuma acontecer todo final de ano e é muuuuuuuuuuuito bom.

E se tiver qualquer dúvida, [te esperamos no Slack :)](http://slack.floripajs.org/)

**Comment by KumoMg** [comment]
@lucasfcosta  muito obrigado!

**Comment by diogomoretti** [comment]
Quando fui responder o @lucasfcosta já deu todas as coordenadas! =]

**Comment by rsmelo** [comment]
além do  FrontInFloripa e do floripaJS, em floripa tem muitos meetups de tecnologias e afim aqui em Floripa. Tem meetup de react, docker, vue, python e mais vários. Recomendo dar um search por meetups na cidade lá no próprio site do https://www.meetup.com/
