### ISSUE TITLE
Livros e blogpost sobre pattern e qualidade de código?

### ISSUE THREAD

**Issue by Cleysonlb** [frontendbr/forum#860]
Fala galera! Resolvi abrir esse tema aqui no fórum, tenho buscado uns conteúdos mais teóricos e conceituais sobre programação, qualidade de código, patters, técnicas etc...
Se tiverem indicações de livros, blog posts, cursos sobre o assunto ou até mesmo experiências pessoais para compartilhar seria bem legal!

**Comment by kvnol** [comment]
Tem awesome de tudo no GitHub, todo dia me impressiono. Se liga: https://github.com/abiodunjames/Awesome-Clean-Code-Resources :zap:

**Comment by jmlavoier** [comment]
Cara, se você estiver falando de Javascript este livro não é muito recente, mas é muito bom.[JavaScript Patterns](https://www.amazon.com/JavaScript-Patterns-Better-Applications-Coding/dp/0596806752). Mesmo o livro sendo baseado em **ES5** super recomendo.

**Comment by Cleysonlb** [comment]
@kvnol curti esse repo! tem muito conteúdo bom ai 💃

**Comment by Cleysonlb** [comment]
@jmlavoier esse livro da um bom direcionamento, eu to buscando uns conteúdos mais agnósticos, mas valeu pela dica 💃

**Comment by ninetails** [comment]
Se quiser ir pro mais roots, não sendo adaptação:
- [Refactoring](https://ler.amazon.com.br/kp/embed?asin=B007WTFWJ6&preview=newtab&linkCode=kpe&ref_=cm_sw_r_kb_dp_juloAbZ6M48SM)
- [Refactoring to patterns](https://ler.amazon.com.br/kp/embed?asin=B001TKD4RQ&preview=newtab&linkCode=kpe&ref_=cm_sw_r_kb_dp_AuloAbB9WPHYM)
- [Clean Code](https://ler.amazon.com.br/kp/embed?asin=B001GSTOAM&preview=newtab&linkCode=kpe&ref_=cm_sw_r_kb_dp_3sloAbJ71WDZP)

Os dois primeiros me abriram os olhos, o último acho hypado mas válido.

Sobre blogs, recomendo acompanhar o [medium](http://medium.com/), em particular cito:
- [FreeCodeCamp](https://medium.freecodecamp.org/)
- [Kent C. Dodds](https://blog.kentcdodds.com/@kentcdodds)
- [Addy Osmani](https://medium.com/@addyosmani)

Mas pra JS acho que o cenário está mudando... Tem patterns que ainda são válidos, mas tem muita coisa "nova" vindo ae com Programação Reativa e/ou Funcional. Mas desconheço livros bem estabelecidos tão quanto os acima citados.

**Comment by helderburato** [comment]
Apenas para reforçar o comentário do @ninetails. 

Um dos melhores livros que já li sobre o assunto e sempre recomendo para os amigos/colegas de profissão é o [Clean Code](https://ler.amazon.com.br/kp/embed?asin=B001GSTOAM&preview=newtab&linkCode=kpe&ref_=cm_sw_r_kb_dp_3sloAbJ71WDZP&reshareId=0MKEPEVZEV0KS7EB566F&reshareChannel=system).

**Comment by espudaro** [comment]
Recentemente li o [Como ser um programador melhor](https://books.google.com.br/books/about/Como_ser_um_programador_melhor.html?id=bEMxBgAAQBAJ), do Pete Goodliffe e recomendo a todos que queiram melhorar a qualidade do seu código. Foca bastante no dia-a-dia do programador com recursos práticos e de fácil implementação. Possui capítulos curtos e independentes, então, dá para começar a ler de qualquer parte do livro.

**Comment by tarciozemel** [comment]
Como ficou bem generalizado, segue sobre APIs RESTful:

* http://desenvolvimentoparaweb.com/miscelanea/api-restful-melhores-praticas-parte-1/
* http://desenvolvimentoparaweb.com/miscelanea/api-restful-melhores-praticas-parte-2/
