### ISSUE TITLE
Formatando texto com array

### ISSUE THREAD

**Issue by didiraja** [frontendbr/forum#861]
Seguinte pessoal, ando praticando JS e ultimamente estou me focando no [Last.fm Dynamic Loader](http://www.didiraja.net/pratice/ajax/) que nada mais é, uma requisição simples em ajax pra retornar os artistas mais ouvidos da última semana registrados na rede social.

O exercício tem sido ótimo pra praticar coisas diferentes. Mas tem uma que eu não sei como resolver. Vejam que quando é exibida a resposta da requisição, junto aparece um botão do Twitter. O texto é dinâmico e escreve **"Eu estou ouvindo fulano[0], fulano[1], fulano[2], fulano[3], fulano[4] e fulano[5] nos últimos 7 dias."**
`// iterando com código sujo e formatação correta`
`tweetButton.attr("data-text", "Eu ouvi " + $(".card-title")[0].textContent + ", " + $(".card-title")[1].textContent + ", " + $(".card-title")[2].textContent + ", " + $(".card-title")[3].textContent + ", " + $(".card-title")[4].textContent + " e " + $(".card-title")[5].textContent + " nos últimos 7 dias")`

Mas o único jeito que pensei para deixar o tweet exatamente desse jeito, foi selecionando manualmente os nomes e selecionando as casas do array, o que deixa o código frágil no instante que eu mudar a quantidade de artistas que quiser exibir.

Eu até tentei fazer a escrita por dentro da iteração do for mas o resultado não ficou satisfatório, e ficou **"Eu estou ouvindo fulano[0], fulano[1], fulano[2], fulano[3], fulano[4], fulano[5],"**.
`// iterando com código limpo e formatação insatisfatória`
`tweetButton.attr("data-text", tweetText + artists[i].name + ",");`

Poderiam me ajudar com isso? As duas tentativas estão marcadas no código para vocês analisarem, no arquivo **main.js**. Aqui está o [repositório](https://github.com/didiraja/Last.fm-Dynamic-Loader). Quem não tem conta no last.fm, teste com a minha, o user é **didiraja** mesmo.

Qualquer dica ou sugestão para otimização do código é bem-vinda.

P.S. Eu sei que o $.get não é a melhor maneira mas eu sou fominha e nem esperei a aula explicar com calma o $.ajax e já fui praticar haha

**Comment by jmlavoier** [comment]
@didiraja 
Atribui a uma variável. 

``` javascript
let artistsName = '';

for (let i = 0; i >= artists.length; i++) {
  artistsName += artists[i].name;
  artistsName += i < artists.length ? ',' : '';
}

tweetButton.attr("data-text", 'Eu ouvi  ' + artistsName + ' nos últimos 7 dias');
```

Veja se te ajuda.

**Comment by didiraja** [comment]
@jmlavoier testei aqui e talvez o problema seja de escopo. Se eu coloco DENTRO DO FOR fica como na imagem e o texto dos tweets está com a variável vazia.

![captura de tela 2017-12-18 as 16 20 32](https://user-images.githubusercontent.com/10463976/34121315-b54c16ec-e40f-11e7-9e5f-97cf6c25f0b4.png)

Se deixo fora, ele diz que artists[array] é undefined, afinal esse array é declarado dentro do for.

Aliás, o que essa linha significa? Ainda não to por dentro do **ES2015**.
`artistsName += i < artists.length ? ',' : '';`

**Comment by jmlavoier** [comment]
Isso não é algo particular do **ES2015**, é um `if` [ternário](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator). 

Então, eu não sei bem certo o que você está concatenando aí, primeiramente achei que era um texto com os nomes dos artistas. Não consegui abstrair sua dúvida, poderia explicar melhor!?

Se eu entendi, acredito que seu problema é que você está na linha [45](https://github.com/didiraja/Last.fm-Dynamic-Loader/blob/c570e88b9a573837645d7a70bd7989863645bf25/main.js#L45). Onde vc chama uma função e da um **append** a cada iteração.

**Comment by munizart** [comment]
@didiraja Vi que você possui o um array com os nomes dos artistas.
Basta fazer `artists.join(", ")` e terás uma string com os nomes separados por `", "`.
Mas nesse caso você quer que os `4` primeiros sejam separados por `", "` e o quinto por `" e "`.
Então algo desse tipo deve servir:
```javascript
function ptBRList (list, lenght) {
  var begin = list.slice(0,lenght - 1).join(', ');
  var last = list[lenght - 1] ? " e " + list[lenght - 1] : "";
  return begin ? begin + last : list[lenght - 1];
}

tweetButton.attr("data-text", 'Eu ouvi  ' + ptBRList(artists, 5) + ' nos últimos 7 dias');
```
Pra mudar a quantidade de artistas é só trocar o `5` do `ptBRList(artists, 5)` pela quantidade que precisares :)

Legal gastar um tempinho na documentação do Array e conhecer os métodos do prototype dele
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

Bons estudos.

**Comment by didiraja** [comment]
Valeu @jmlavoier pelo caminho das pedras que fez eu me virar na direção correta. E valeu @munizart pela solução e explicação.

Realmente, vai ser necessário dar uma estudando especifica em arrays, valeu galera
