### ISSUE TITLE
meu quase redux =D

### ISSUE THREAD

**Issue by rmlSardinha** [frontendbr/forum#864]
Boa tarde a todos, sou novato em react, e comecei a estudar sério js inicio do ano, fiz uma brincadeira ontem que fiquei com vontade de compartilhar, 
um único local de estado e único local com métodos, queria algo menor que o redux para coisas mais simples para mim. Opiniões sempre bem vindas.

https://github.com/rmlSardinha/nanux
https://codesandbox.io/s/j75w2o875

**Comment by SergioJrDev** [comment]
Olá, @rmlSardinha, sua lógica está certa e funciona perfeitamente, numa aplicação pequena, mas todos os componentes dependeriam do index.js e vc teria que passar o estado global por seus filhos e quando houver uma alteração, todos serão atualizados, mesmo que não usem o estado.

Com Redux ou [Mobx](https://github.com/mobxjs/mobx) os componentes continuam independentes, o que melhora a perfomance.

Sugiro que vc dê uma olhada, no começo eu sofria mais pra configurar o redux do que utilizar, hoje uso o padrão [Redux Ducks](https://github.com/erikras/ducks-modular-redux) pra organizar o código, tem me ajudado muito.

**Comment by edmolima** [comment]
Concordo com os pontos que o @SergioJrDev falou acima.

@rmlSardinha confere esse cara: https://github.com/concretesolutions/redux-zero

É um projeto bacana que o pessoal da Concrete Solutions criou =)

**Comment by rmlSardinha** [comment]
Hum.. legal @SergioJrDev , blz vou olhar esse Redux Ducks ai. obrigado pela dica

**Comment by rmlSardinha** [comment]
obrigado tbm @edmolima ... obrigado os dois por esse material de estudo kk
