### ISSUE TITLE
Quais media queries vocês centralizam um desenvolvimento responsivo?

### ISSUE THREAD

**Issue by waldemirflj** [frontendbr/forum#867]
Opa! Galera, em um projeto responsivo vocês centralizam o desenvolvimento em cima de quais media queries? Essas "ramificações" de aparelhos medidas/resoluções eu não sei por quais me basear.

**Comment by leandroruel** [comment]
eu não uso uma específica, o layout é fluido, onde der o ponto de quebra eu coloca a media querie. o que é o certo na minha opinião.

**Comment by phsantiago** [comment]
Nos ultimos projetos não tenho usado media queries para quebras menores, apenas para as maiores, ou seja, o css que rodaria em telas menores fica fora de media queries, já os para telas maiores como tablet e desktop ficam dentro das media queries.
Assim como o @leandroruel não me prendo muito a quebras específica não, no máximo procuro um projeto parecido na empresa que tenha acessos e vejo no analytics qual a quebra mais comum em todos os acessos, assim vou considerando as mais frequentes.

**Comment by LFeh** [comment]
Opa, continuem aqui :)

#153
