### ISSUE TITLE
Erro contribuição git

### ISSUE THREAD

**Issue by thiagofrancisquete** [frontendbr/forum#869]
Galera seguinte, to com uns problemas com o git e nao achei nada na internet que me ajudasse, queria saber se alguém ja passou por algo parecido possa me ajudar.

Eu consigo enviar, deletar etc mas como `usuario fantasma`, não conta como contribuição minha. Alguém tem idéia do que pode ser? o user.name e user.email são iguais os do github. Criei um [repositório teste](https://github.com/thiagofrancisquete/teste) do absoluto zero, mas continua sem autenticar a contribuição, em outros repositorios da o mesmo erro, só conta como contribuição minha se eu faço as alterações pelo github.

**Comment by AmandaFonseca** [comment]
Você já configurou o seu nome e email no git ?
Digite no console:
cd nomeDaPastaDoProjeto

git config --global user.name "seuNome" 
git config --global user.email "seuEmail"

**Comment by thiagofrancisquete** [comment]
Já sim. O nome e e-mail estão iguais os daqui no github. :(

**Comment by lucasfcosta** [comment]
Qual output dos comandos que a @AmandaFonseca postou?

Quando você usa a flag `--global` ele vai settar essas configurações pra sua install inteira do git (global), então deveria funcionar em qualquer pasta.

Se você estiver tentando reescrever a identidade associada ao último commit tente fazer um `--amend` com `--reset-author`, dessa forma: 

```
git commit --amend --reset-author
```

**Comment by thiagofrancisquete** [comment]
User.name "thiagofrancisquete"
User.email "thiago.francisquete@gmail.com"

Por ser exatamente o mesmo user e e-mail deveria reconhecer não é?

Não sei se tem a ver, mas quando eu dou um push e ele pede user e senha, ele vira o meu user`@github.com.`

**Comment by willianjusten** [comment]
Usando via `http` realmente pede senha e o email é um atrelado pelo Github, mas via `ssh` é o seu email configurado.

Como disseram acima, você pode usar o `--global` ou não passar a flag, mas rodar o comando só no repositório que deseja e as informações ficariam certas lá.

Para contar como contribuição, o Github tem um mini conjuntinho de regras:

```
Commits will appear on your contributions graph if they meet all of the following conditions:

- The email address used for the commits is associated with your GitHub account.
- The commits were made in a standalone repository, not a fork.
- The commits were made:
  - In the repository's default branch (usually master)
  - In the gh-pages branch (for repositories with Project Pages sites)

In addition, at least one of the following must be true:

- You are a collaborator on the repository or are a member of the organization that owns the repository.
- You have forked the repository.
- You have opened a pull request or issue in the repository.
- You have starred the repository.
```

Já tentou deslogar e verificar se é exatamente esse email `thiago.francisquete@gmail.com` cadastrado? As vezes é algum outro...

**Comment by willianjusten** [comment]
Opaaaa, acabei de clonar seu projeto e está mostrando o author como:

`Author: thiagofrancisquete <thiagofrancisquete@gmail.com>`

Repare que não tem o ponto como no informado acima! Então só fazer o seguinte:

```
git config --global --unset user.email
git config --global user.email thiago.francisquete@gmail.com
```

**Comment by thiagofrancisquete** [comment]
Nossa eu olhei tantas vezes e o ponto sempre esteve lá. Não sei se meu cérebro foi no automático e eu lia o ponto ou se tô ficando louco o.O

Era isso. Obrigado por disponibilizarem o tempo de vocês no ano novo pra me ajudar. Happy new year guys 🎊🎉

**Comment by willianjusten** [comment]
Yeeeey! \o/
