### ISSUE TITLE
Como vocês trabalham com o design responsivo?

### ISSUE THREAD

**Issue by AmandaFonseca** [frontendbr/forum#871]
Oi gente !

Eu estou começando na área e eu sempre quebro a cabeça com medias queries.. Nos meus projetos pessoais sempre que eu defino e ajusto os elementos conforme uma resolução eu acabo como  eu posso dizer ... "zuando" a outra kkk. Trabalho com suporte e as vezes me passam 1 ou outro serviço de front eu acabo fazendo a manutenção de um site antigo e a situação piora 1 vez que além da dificuldade de deixar o site responsivo tenho que levar em conta o CSS anteriormente já definido.

Então eu gostaria de saber ? se vc usam um reset de CSS tipo o do  Eric Meyer? quais os breapoints que vcs utilizam? Algum framework? enfim .... como vocês lidam com esse tipo de B.O ?

Obs: Dicas de tutorias são bem vindas :)

**Comment by klarkc** [comment]
Existem algumas boas práticas. Desenvolver mobile-first é a primeira delas. Você escreve primeiro o CSS para a menor tela, e usa as media queries apenas com min-width, quando houver espaço disponível. Outra boa prática é usar algum padrão de nomeação no CSS (tipo o BEM) que facilita a leitura e manutenção do código. Outra boa prática, considerada por muitos, é padronizar os break-points (pontos fixos de quebra com as media queries) e colocá-los em folhas de estilo separadas (para todos ou por cada break point).

**Comment by LFeh** [comment]
Fala @AmandaFonseca, temos algumas issues discutindo esse tema, veja se te atende.

#40 #794 #153 #220 #86

**Comment by tarciozemel** [comment]
@AmandaFonseca Com certeza a dica do @klarkc é preciosa: trabalhe com mobile first, iniciando o visual a partir do mobile, sem breakpoints, e vá "subindo" a partir daí. Tem um livro bem legal, especificamente sobre isso: https://abookapart.com/products/mobile-first

CSS Reset você pode usar sim, mas não é estritamente relacionado à web design responsivo; é para reduzir algumas inconsistências entre browsers.

Sobre as media queries, para começar, você pode usar um conjunto predefinido de breakpoints (os "clássicos" 468, 720, 1024 etc.), mas a medida em que for pegando o jeito da coisa, idealmente (caso o cliente não solicite em contrário) os breakpoints devem ser colocados quando o layout começar a prejudicar a UX e/ou ficar "desagradável", genericamente falando.

A ideia é usar as media queries para sobrescrever somente as propriedades que devem ser diferentes na nova viewport. Se um elemento qualquer tem 10 propriedades e você vai mudar somente sua largura no breakpoint, não precisa repetir todas as outras 9, entendeu?

Aqui um livrinho básico sobre o tema: https://www.casadocodigo.com.br/products/livro-web-design-responsivo.

Att

**Comment by AmandaFonseca** [comment]
@klarkc @tarciozemel li sobre a Mobile-first e realmente e uma ótima e eficaz abordagem e faz vc refletir: como eu não pensei nisso antes? rsrsrs 
Obrigada pelas dicas maravilhosas
@LFeh estou lendo o conteudo dessas issues que vc linkou e pesquisando sobre todas as abordagens e dicas que são interessantíssimas adorei a sua dica sobre Picturefill + lazysizes.

**Comment by LFeh** [comment]
@AmandaFonseca acredito que esse é o melhor texto que já escrevi sobre o assunto, da uma olhada depois -> https://www.felipefialho.com/blog/2015/otimizando-e-organizando-as-media-queries

**Comment by AmandaFonseca** [comment]
@LFeh porque vc usa `$space= 20px`  com esse sinal '$' e vc define isso no css?
Desculpe a pergunta estou iniciando meus estudos de front

**Comment by laurindo** [comment]
@AmandaFonseca EU acredito que o $ é uma representação de variaveis dentro do CSS.

**Comment by LFeh** [comment]
@AmandaFonseca uso para definir variáveis no [Stylus](http://stylus-lang.com/docs/variables.html)

**Comment by AmandaFonseca** [comment]
@LFeh @laurindo hum entendi
