### ISSUE TITLE
AJAX, qual é o problema de se fazer requisições com XMLHttpRequest usando JS Vanilla?

### ISSUE THREAD

**Issue by diogorodrigues** [frontendbr/forum#877]
Fala galera, blz?

Complementando a [issue 849](https://github.com/frontendbr/forum/issues/849) , estou buscando entender quais os problemas de utilizar requisições AJAX apenas com XMLHttpRequest do JS Vanilla (não me refiro ao ES6)?!

Vejo que muito se fala sobre utilizar as funcionalidades da jQuery ou Axios. Muito também se fala das novas funcionalidades e incompatibilidades dos browsers em se utilizar ES6 para se fazer isso. No entanto, por mais que eu pesquiso ainda não consegui encontrar uma explicação convincente sobre essas diferenças, vantagens e desvantagens.

Me ajudem a entender? =D

**Comment by icaioincau** [comment]
O principal problema para mim, é a sintaxe que é enorme e complexa, enquantoa  sintaxe é mutio mais enxuta ao lidar com axios e afins.

As coisas melhoraram muito com o fetch e se você usa babel, compatibilidade não será problema.

**Comment by diogorodrigues** [comment]
Certo @icaioincau 

Então, se o problema é apenas a sintaxe, sendo assim, para não ter que usar códigos de terceiros - e não ficar toda hora reescrevendo o request -, poderia ter uma função abstraindo a sintaxe, concorda? Ou, além disso, vê mais algum problema?

**Comment by edmolima** [comment]
@diogorodrigues  Na verdade eu só vejo vantagem utilizar. Posso ta falando besteira mas:

O XMLHttpRequest você consegue fazer algo que nem um outro recurso da pra fazer. Cancelar a request.

Se você pensar bem uma promise lançada ela tem que ser resolvida (recusada ou completa). No XMLHttpRequest  enquanto a request não chega no stage 4 que é quando essa requisição tá pronta, você pode em qualquer estado cancelar.

Mas lembra que fetch api, axios, jquery e etc fazem implementação dessa api. E quanto a opção da syntax ser verbosa e tal, o que falo é: Esse cara pode ser feito através de High Order Function e ser reaproveitado. Que no final das contas você tá criando só uma abstração.

Então é bem isso, você poderia usar ou um fetch ou axios da vida por facilidade ou criar uma função abstraindo o XMLHttpRequest. 

Se alguém puder contribuir com outros pontos de vistas seria legal.

**Comment by ninetails** [comment]
Para contribuir com a discussão, sobre abstrair: se o problema for usar código de terceiros, basta pegar um source com uma licença permitiva e bem testada, não? Reinventar roda pode se tornar custoso ao software e mais linhas de código no projeto serão mais linhas de possíveis bugs, mesmo adicionando testes.

E realmente, creio que o fetch dê apenas para ignorar, não cancelar.

**Comment by munizart** [comment]
@diogorodrigues não vejo nenhum problema. Assim como o @edmolima diz, só vejo vantagem...
A principal pra mim é poder abstratir ele pro formato que você quiser. Axios abstrai pra uma API baseada em Promises por exemplo.
Mas você pode implementar como quiser e isso junto com javascript ser multiparadgimas lhe da muitas possibilidades.

BTW: da pra cancelar sim uma request do fetch

**Comment by jhonnymoreira** [comment]
Não vejo mais vantagem em usar o `XMLHttpRequest` cruzão, sendo que a tendência (ao menos é o que parece) é solidificar o `fetch`, tanto pro _node_ quanto pro _browser_.

Ao invés de fazer attach de um evento, basta um then.

```js
fetch('https://jailsonmendes.com.br')
  .then(response => response.json())
  .then(({ saborSuco }) => saborSuco)
  .then(console.log)
```

**Comment by helderburato** [comment]
Olá @diogorodrigues !

Sou a favor que você deve utilizar o que te faz mais produtivo, e que a equipe que trabalha em conjunto com você esteja ciente do formato utilizado.

Se o objetivo for alcançado, equipe satisfeita com o formato e clientes com os resultados, acredito que não há problema algum na forma que é escrita a chamada para o `AJAX`.

**Comment by woliveiras** [comment]
Por baixo dos panos essas ferramentas estão utilizando as APIs JavaScript de qualquer maneira, @diogorodrigues. Então o que da pra fazer com um da pra fazer com outro.

A única diferença prática, de verdade, é que em uma das opções alguém já escreveu o código que você teria que escrever pra fazer requisições.

Não tem muito o que discutir sobre... É só isso mesmo. :joy: 

É pegar o código de alguém que já escreveu a abstração que você vai escrever (aquela função que você comentou) e usar o que a pessoa já fez ao invés de escrever tudo do zero.

A única real diferença, que eu vejo, é sobre cenários que a lib resolve: um código open source em que várias pessoas contribuíram e com certa maturidade pode ter mais soluções para problemas que você, futuramente, enfrentaria escrevendo do zero. Seja de uso da API ou de manutenção de código.

Não sou contra escrever tudo do zero quando você acha que pode fazer algo **melhor** do que o que já existe no mercado, mas se for só por "resistência" a lib, sem muitos pontos contra, além de querer usar x ou y por preconceito com o código de terceiros, então pode ser um tiro no pé, viu. Lembre-se que projetos tem prazos, custam dinheiro e qualquer tempo ganho (sem comprometer a qualidade do produto) é lucro.

No demais eu vejo que é muito mais questão das pessoas se assustarem a utilizar código "nativo" e preferir as sintaxes das libs que o que um ou outro pode ou não fazer, pois tudo faz a mesma coisa no final das contas.

**Comment by icaioincau** [comment]
Exato, sempre da para abstrair e tal, ma para que reinvetar a roda? As libs de request já resolveram dezenas de problemas que você só irá descobrir quando já estiver rolando.

**Comment by diogorodrigues** [comment]
Ótimas respostas galera! 

Você tem razão @icaioincau ; eu imaginava que haviam muito mais problemas além da sintaxe: algum tipo de incompatibilidade ou tratamento de erros, por exemplo.

Vi que a versão AJAX da jQuery era compatível com IE 6 e 7 em um cenário onde não se era possível fazer uma requisição com XHLHttpRequest de modo fácil para essas versões do navegador. Talvez minha dúvida tenha surgido desse ponto.

Realmente galera, não é preciso inventar a roda. =D
Com certeza as respostas me ajudaram a entender algumas diferenças entre XMLHttpRequest e fetch API Vs. Axios.
