### ISSUE TITLE
Idéias para o mundo real 

### ISSUE THREAD

**Issue by diegoslva** [frontendbr/forum#883]
Salve galera. 

Hoje depois de algumas doses de vodka com os amigos, resolvi ver alguns videos das palestras da Brasil Js  2017 e cara, namoral, podemos fazer tanta coisa foda pro mundo real, que nem mesmo consigo organizar as ideias na cabeça.

Duas palestras que achei super foda, que foram a da mão mecânica e da máquina de bebidas. Fiquei super empolgado vendo essas paradas  e pensei, por que não organizarmos uma lista de coisas que poderíamos estar fazendo pra não só, melhor nosso dia dia, como  tornar mais divertido. Afinal a graça de aprender toda essa porra que estudamos quase todo dia é  devolver algo pro mundo real. Lanço o desafio para que tenhamos uma lista de idéias mesmo que simples, mas que além de nós ajudar a desenvolver nossas habilidades, ajudar  pessoas ou simplesmente criar por que é divertido. O que vocês acham? 
Desculpe o português complicado mais ainda to bebendo kkk

**Comment by LFeh** [comment]
@diegoslva Eu tinha visto essa issue e curti a ideia, hehe

Pensou em alguma coisa nesses dias?
