### ISSUE TITLE
[Segurança] - Controle de acesso e permissões numa aplicação

### ISSUE THREAD

**Issue by Sergioamjr** [frontendbr/forum#887]
Estou participando do desenvolvimento de algumas aplicações no trabalho e estamos buscando soluções pra resolver o controle de acesso e gerenciamento de tipos de perfis com permissões diferentes. Hoje no login o front recebe, além do token da sessão e informações do usuário, um grupo de roles (admin, coordenador, fiscal, usuário, etc), grava no localStorage e isso habilita/desabilita alguns menus e restringe o acesso a outras páginas. Mas se um usuário com com mais conhecimento alterar as roles no localStorage, ele pode acessar algo que não deveria.

(Se ele não tiver mais conhecimento técnico e má intenção e usar uma ferramenta como o [Burp](https://portswigger.net/burp) pra interceptar as requisições, alterar os headers, parâmetros ou resposta.)

Sei que a verificação não deve estar apenas de um lado, estamos trabalhando com o backend pra ter um double check mas gostaria de saber se há outras opções de contornar isso; criar alias menos obvias p/ roles, encriptar os dados, etc.

Outras referências que encontrei.
https://hackernoon.com/role-based-authorization-in-react-c70bb7641db4
http://frontendinsights.com/role-based-authorization-using-react-router/
https://stackoverflow.com/questions/37982473/permission-checks-from-components-in-a-react-redux-application

**Comment by waldemirflj** [comment]
Boa!! @SergioJrDev eu deixo essa lógica no Back-end. Antes de qualquer requisiçao eu passo por um middleware que verifica se o solicitante tem as permissões necessarias. Também não tenho o hábito de inflar o meu token, deixo o mínimo do mínimo.

**Comment by LFeh** [comment]
No front dá para oferecer apenas uma camada minima de segurança. 

Como o @kazzkiq disse, qualquer um mal intencionado e com paciência, se debuggar seu código, consegue contornar a segurança no cliente, por melhor pensada que seja.

**Comment by vitorbritto** [comment]
Sugiro pesquisar por [role-based access control (RBAC)](https://pt.wikipedia.org/wiki/Role-based_access_control).

> "Mas se um usuário com com mais conhecimento alterar as roles no localStorage, ele pode acessar algo que não deveria."

Todas as regras de autenticação devem ser mantidas no server. Procure criar regras a respeito **do que** e **qual** usuário "pode" ou "não pode" fazer em determinados endpoints.

Veja se é útil para você: https://github.com/seeden/rbac

**Comment by SergioJrDev** [comment]
Tudo isso era exatamente o que eu estava pensando sobre segurança no front.

Já dei uma olhada nesses itens citados e vamos avaliar aqui no trabalho.

Mas já me ajudaram muito, obrigado @kazzkiq, @vitorbritto, @LFeh, @waldemirflj :v:

**Comment by thulioph** [comment]
Acredito que vale também do bom senso do dev.. Se eu to desenvolvendo uma aplicação que o nome é **Kambam** (por exemplo) e eu preciso salvar algo no Storage, a primeira coisa que eu faço é mudar o nome pra algo como: **kb** ou **kmb**.  
Lógico, isso é o mínimo do mínimo do mínimo que eu faço.

> O **burp** é uma ferramenta irada, participei de um Capture The Flag, e a turma utiliza-va ele, muito foda!

**Comment by pedroguilhermelima** [comment]
Vou fazer um texto enorme e espero que ajude! ;D
 
**Controles de acesso**

1.  Você pode uma usar API para isso. Dependendo da API, esse controle de acesso pode ser mais seguro. 

**Observações:**

1. 1. Depende do que você quer fazer. Por exemplo, API do Facebook é segura, mas usam de forma errada. 

O fato é que muitos usuários tiveram informações roubadas por permitirem que os jogos tivessem essas permissões tais como: nome, perfil, idade.... Assim, como acontece ao você instalar um aplicativo ou você se cadastrar em um site. 

O que quero dizer é que o site ou aplicativo não possui essas informações, você é que diz se quer ou não. E isso envolve muitos aspectos, vou resumir alguns:

> 1. Licença, 2. Recursos e Usos de Software. 3. Aspectos de Código.  4. Busca e forma da informação.

**Outras questões** 

1. Existe a possibilidade que essa informação deve ser pública e outra que deve ser privada, segura, anônima, encriptada.  

2. Existe diferença entre dado, informação e conhecimento.

**Uma pequena história.**

Para a internet funcionar devem ter pessoas que queiram informações públicas. Assim, como querem informações seguras, privadas, anônimas, encriptadas. E cada uma tem processo, análise. 

**Uma bom exemplo**
Informações como rotas de carros não podem ser públicas para pessoas. Veja "Disse: Informações como rotas de carros não podem ser públicas para pessoas." Isso quer dizer, que não devem. Mas, podem. Considerando esses fatos

1. O que acontece é que muitos compartilham sua localização com perfil. E isso, faz com que toda internet saiba do que você faz. 

2. Isso é bom? Depende. Por exemplo, se a gente descobrir qual melhor rota para salvar uma vida, sim. Se a gente usa para fazer melhores preços com base na localização, talvez. Depende, você está olhando como empresário ou como cliente? 


Informação segura, pode ser no processo de ser privada, verdadeira. Ou, de transmitir confiança, verdade.


2. 

**Permissões**


Existe uma maneira da aplicação ficar 100% segura. 




1. Você pode usar as APIS dos próprios serviços. Por exemplo, se você fizer um front-end você poderia criar um codepen.io e usar essa API para exibir esse projeto criado. 

2. Você pode usar um proxy reverso para o localhost. Por exemplo, existe o ngrok. Se alguém tiver acesso, terá um ip num proxy reverso. Você poderia 

1. Oculte os links do acesso do arquivo visual. E isso pode ser feito assim, você faz o arquivo e chama internamente essas coisas visuais.

2. Você

**Comment by pedroguilhermelima** [comment]
Permissões numa aplicação 

**Licença inclui e centraliza os termos de uso, termos de privacidade, termos de segurança, termos de software.** 

**Questão Geral**

Você pode ter uma aplicação com certos recursos como 'localização via GPS'. Mas, se esse recurso não é utilizado, porque desenvolveriam? Então, a pessoa para usar o recurso 'localização via GPS' deve permitir que  o recurso GPS seja realizado. E isso inclui: compartilhar as informações 'as rotas' da sua localização, Outra, se esse aplicação tiver um recurso de chat com esse recurso. Então, pode enviar a mensagem com essa localização. E isso, não deveria acontecer. O recurso 'localizar GPS' deveria ser separado do recurso 'Enviar Mensagem'.  Até por um motivo: Alguém poderia ter acesso ao seu servidor e já ter a localização da pessoa. Agora,  se você separa os recursos. A pessoa pode ter acesso a um ou outro recurso. E isso, pode aumentar a segurança.

**Comment by pedroguilhermelima** [comment]
**Outras questões** 

1. Existe a possibilidade que essa informação deve ser pública e outra que deve ser privada, segura, anônima, encriptada.  

2. Existe diferença entre dado, informação e conhecimento.

**Comment by pedroguilhermelima** [comment]
**Uma pequena história.**
Para a internet funcionar devem ter pessoas que queiram informações públicas. Assim, como querem informações seguras, privadas, anônimas, encriptadas. E cada uma tem processo, análise. 

**Uma bom exemplo**
Premissa: Se as informações como rotas de carros não podem ser públicas para pessoas. Veja "Disse: Informações como rotas de carros não podem ser públicas para pessoas." Isso quer dizer, que não devem. Mas, podem. 

_**Considerando esses fatos**_

1. O que acontece se muitos compartilham sua localização com perfil público?

a. Toda internet 'rede de computadores' sabe. 

**Perguntas Iniciais** 
1. Isso é bom? Depende. Por exemplo, se a gente descobrir qual melhor rota para salvar uma pessoa de um acidente, sim. Mas, se a gente essa informação para melhorar os preços com base na localizações divulgadas por perfis públicos? Talvez, mas depende. Você poderia incentivar um consumo que não deveria ser. E isso, é errado. É como incentivar alguém a comer mais. E isso, produz cada dia mais e mais pessoas com a saúde ruim. 

**Observação**
Agora, cabe a escolha de cada um. E não podemos questionar ou interferir nesse processo. Muitos comentam que a Internet deveria ser um espaço bom, mas ocorre se existe 'uma empresa que avalia essas questões', a Internet passa de uma rede de pessoas que não falam o que podem, querem e sim o que deveriam. E isso, é errado. 

**Motivos**

1. Por exemplo, tira a escolha individual das pessoas e faz com que seja 'boas e comportadas'. E isso, é errado. Pois, passa uma ideia de um bem maior que não é verdadeiro.  
2. Além disto, faz com que muitas coisas boas que podiam, deviam ser realizadas sumirem do mapa. Pois, para que as pessoas criariam melhores sistemas, ideias, projetos se as pessoas não olham para isso nem possuem atenção.

**Comment by pedroguilhermelima** [comment]
**Problema Geral, Soluções**
 
**Existem várias questões, algumas observações** 

**Casos Reais**

1. Se a aplicação exige um cuidado com as informações. 

a. Avalie como a aplicação usa os recursos.

**Considere os pensamentos**

1. O sistema de login 'a interface gráfica' deve ser carregada ou deve pedir autenticação para o servidor?

**Casos**

_Sim_

1. Se ela deve ser carregada para o servidor, qual informação deve ser encriptada. Toda? Alguma? Essa?
2. Se ela deve ter uma autenticação, qual autenticação, qual criptografia utiliza? A rede está criptografada ou deve está para usar?

**Solução**
1. E se você apenas fizer a interface sem chamar para o servidor? 

a. O próprio usuário iria carregar essas informações.
b. Se precisar autenticar, autentica, mas se não... não.

**Voltando**
 
1- Você usa qual método GET, POST? Ps: Repara no código e nos cabelhaços do http dentro da rede.
2- Usa proxy, vpn?

**Comment by pedroguilhermelima** [comment]
Solução Real para o Front-end

**Um exemplo com Jquery**
**Como ocultar o html e exibir o html ?**

```
$( "#result" ).load( "ajax/test.html", function() {
  alert( "Load was performed." );
});

```
