### ISSUE TITLE
Procurando o livro "JavaScript o guia definitivo".

### ISSUE THREAD

**Issue by MatheusNtg** [frontendbr/forum#893]
Alguém tem esse livro que não use mais e possa doar ?

**Comment by cristofersousa** [comment]
Cara eu tenho a 4ª edição dele, se desejar eu posso envia mas acredito que você queira a versão que aborda es5, html5 e apis, certo?  

!(http://t3.gstatic.com/images?q=tbn:ANd9GcRCwNAkGOYNZ0M4bsQR0YbLKonfSAmhdJt-M3wAPjqvK5mnxRbQ)[JS Guia Definitivo]5

**Comment by cristofersousa** [comment]
Olhei no Mercado Livre e tem uma pessoa vendendo a 6ª edição por 40,00 > https://produto.mercadolivre.com.br/MLB-961635151-livro-didatico-javascript-6-edico-_JM

**Comment by LFeh** [comment]
Opa, temos um repositório especifico para doação, pode postar lá :)

https://github.com/frontendbr/doe-um-livro

**Comment by geniton** [comment]
https://docero.com.br/doc/v8scn

**Comment by marcelovelame** [comment]
> https://docero.com.br/doc/v8scn

esse ainda está ativo, recomendo

**Comment by Leodominoni** [comment]
O link acima não está funcionando, porém esse está: https://www.pdfdrive.com/javascript-o-guia-definitivo-d185837261.html

**Comment by felquis** [comment]
Embora em alguns fóruns seja comum compartilhar links de PDFs, aqui a gente prefere não compartilhar estes links pois o GitHub pode penalizar nosso fórum de maneiras incontornáveis.

Por este motivo vou fechar a discussão, qualquer dúvida relacionado a alguma parte de algum livro, abra uma discussão para a gente discutir.
