### ISSUE TITLE
Tela de "Recarregar" [Angular 2/5]

### ISSUE THREAD

**Issue by ojonathanleal** [frontendbr/forum#894]
Boa tarde.

Estou pensando/pesquisando como implementar um comportamento parecido com o do instagram em uma web app com Angular 2/5.  Quero que quando for acessado uma tela, a mesma tente carregar os dados, e caso não consiga, apareça uma tela em branco com um botão de recarregar no meio.

Alguém já implementou isso ou possui alguma ideia?

**Comment by LFeh** [comment]
@ojonathanleal Mas por qual razão a tela não conseguiria carregar os dados? Erro no retorno da API?

**Comment by ojonathanleal** [comment]
@LFeh exatamente. Isso poderia ser feito especificamente com um ng-view ou ng-if, porém queria alto mais genérico, que atendesse o projeto inteiro.

**Comment by WandersonAlves** [comment]
@ojonathanleal o que imagino que você possa fazer, é criar uma view em uma rota X e nos interceptors que você usar, quando um request der erro, dar um router.navigate pra essa rota.
De plus, teria também que passar a referencia da rota que estava quando deu erro pro refresh de fato funcionar (o refresh seria mais um router.navigate).

Não sei se faz sentido pra você, mas pensando rapido cheguei nessa solução

**Comment by leandroruel** [comment]
é igual acontece no app do facebook.

**Comment by ojonathanleal** [comment]
@WandersonAlves boa ideia, isso já me atende. Obrigado pela ajuda!

**Comment by WandersonAlves** [comment]
De nada @ojonathanleal 😄
