### ISSUE TITLE
Semântica e SEO

### ISSUE THREAD

**Issue by bomfas** [frontendbr/forum#896]
Boa Pessoal,

A um tempo eu fiz um curso de html e na época uma boa prática de SEO era fazer as páginas de conteúdo dessa forma:

```html
<article>
      <header>
           <h1>Meu Post</h2>
           <h2>Meu post super legal</h2>
      </header>
      <main>
           <p> meu texto do post super legal</p>
      </main>
     <footer>
             Autor do post super legal
     </footer>
</article>
```
Queria saber se isso é valido, se mudou e como vocês criam a estrutura para um página de conteúdo.

**Comment by bernardodiasc** [comment]
H2 Ali não deveria ser usado como subtitulo pois eh uma tag de cabeçalho. O restante está correto.

**Comment by phsantiago** [comment]
Para mim `header` e `footer` sempre foram de fato o header e footer do site e não do conteúdo. Agora fiquei em dúvida, logo logo vou pesquisar.

**Comment by bernardodiasc** [comment]
Vc pode ter header e footer dentro de sections, assim como dentro do main out article. Vai depender de como o conteúdo estiver delimitado, e não importa se houver vários desses elementos na pagina, contanto que a semântica da marcação faça sentido.

**Comment by luizbills** [comment]
Quanto a tag `<main>` é recomendado ter somente **um** na página e que este mostre somente o conteúdo principal da página.

**Comment by bernardodiasc** [comment]
Bem observado @luizbills 

> There must not be more than one <main> element in a document. The <main> element must NOT be a descendant of an <article>, <aside>, <footer>, <header>, or <nav> element.

Ou seja, no código do exemplo tem esse erro onde a tag main esta dentro de article quando deveria ser o oposto.

**Comment by LFeh** [comment]
Além do ponto levantado pelo @luizbills sobre o `<main>`, é interessante colocar o conteúdo dentro de `<article>`, `<section>`, `<header>`, etc, já que a função do `<main>`, até por ser unico na página, é servir como um wrapper para os conteúdos.

Portanto o correto seria.

```
<header></header>
<main>
  <article></article>
</main>
<footer></footer>
```

**Comment by bfmjr** [comment]
Valeu pessoal :)

**Comment by Matheus-de-Souza** [comment]
Eu também tenho curiosidade sobre html semântico, vocês conhecem algum material de estudo (curso/video/livro)?

**Comment by bernardodiasc** [comment]
http://html5doctor.com/

**Comment by thismarcoantonio** [comment]
Caramba, nesse HTML5 doctor tem muitas tags que eu nunca pensei q existiam. Interessante demais, já vou deixar aqui no meu bookmark
