### ISSUE TITLE
Backend e frontend junto ou separado?!

### ISSUE THREAD

**Issue by Cleysonlb** [frontendbr/forum#899]
Pensando em arquitetura, o que faz mais sentido:
- Backend junto com o front, mesmo que o backend só sirva API para o front consumir
- Backend separado do frontend

Quais as vantagens e desvantagens?! 🤔

**Comment by ericOnda** [comment]
Posso estar enganado, mas não vejo muitas vantagens em misturar as camadas. Recentemente, iniciei um projeto MEAN, e uma das primeiras decisões que tomamos foi desacoplar o máximo possível front e back, coisa que não havia sido feita em projetos anteriores. 

No nosso caso, uma das maiores motivações (além da organização, claro), foi a liberdade de pensar o lado Rest da forma mais genérica possível, independente de qual tipo de aplicação e dispositivos venham a consumi-la.

**Comment by lBrunol** [comment]
Eu tive essa dúvida recentemente. Estou desenvolvendo um sistema na empresa que trabalho e escolhi fazer o back-end como API e o front sendo uma SPA. Ou seja, estão desacoplados.

Antes de tudo, veja a necessidade do seu projeto. Faça perguntas como: qual é o tamanho? Precisa escalar? Será apenas para web ou também terá aplicativo? Qual é o tempo para desenvolver? Tenho prazo para usar uma arquitetura mais complexa?

Dito isso, aqui vão algumas considerações:

Back-end separado
Penso que é mais complexo, pois serão duas arquiteturas, a do seu Front, provavelmente uma SPA e a sua API. É bem provável que você leve mais tempo para desenvolver e consequentemente, custará mais dinheiro. Em contrapartida, você terá mais flexibilidade, pois poderá aproveitar sua API num APP ou até em outro site se for o caso. Os deploys também serão desacoplados, pode ser uma vantagem. Acho que é vantajoso usar isso numa aplicação complexa e com potencial para escalar.

Back-end acoplado
Aqui você vai levar menos tempo para desenvolver. Geralmente demanda menos conhecimento, já que você provavelmente não vai ter nenhum framework ou biblioteca de SPA. Esse cenário é interessante em um projeto com um grau de complexidade baixo e para projetos com um prazo e orçamento apertado.

**Comment by renzorodrigues** [comment]
Pessoal, tenho o frontend e backend separados. Como faço pra criar um repositório com os dois projetos?

**Comment by tcelestino** [comment]
@renzorodrigues, vc precisa criar uma "[Organização](https://github.com/organizations/new)" dentro do Github e na hora de criar um repositório, você "seta" qual organização ele faz parte.

**Comment by mahenrique94** [comment]
Com certeza separado é bem melhor, assim você ganha muito com escalabilidade, manutenção, organização, etc...

**Comment by diegopereiramendes** [comment]
Existe alguma regra de nomenclatura para os projetos? ex:

o front:   projetoFront
o back:    projetoBack
para deixa mais organizado?

**Comment by gabebarbosa** [comment]
> Existe alguma regra de nomenclatura para os projetos? ex:
> 
> o front: projetoFront
> o back: projetoBack
> para deixar mais organizado?

Acredito que não exista uma regra, da forma que você colocou(projetoFront e projetoBack) já deixa bem clara a responsabilidade de cada um. 
Hoje onde eu trabalho costumamos usar da seguinte forma:
meuProjeto.presentation - FrontEnd
meuProjeto.webservices - BackEnd

Já estamos acostumados a este padrão, é o padrão estabelecido pela empresa. Você(ou sua empresa) pode criar o seu.
