### ISSUE TITLE
Como controlar variáveis de dev/prod

### ISSUE THREAD

**Issue by samuelsilvadev** [frontendbr/forum#902]
Eae galera fmz?

Como vocẽs controlam esses dois ambientes? 
 
 - development
 - production

Vi alguns exemplos utilizando arquivos _.env_, essa estratégia funciona bem? Existe alguma outra maneira?

**Comment by eduardojmatos** [comment]
@samuelsilvadev fala mano! Acho que usar .env é a melhor estratégia mesmo. Pelo menos a mais segura. Usar variáveis de ambiente é a prática mais segura por remover do código qualquer referência a dados sensíveis.

No GetNinjas usamos um esquema com o Parameter Store da Amazon. Fazemos o download das ENVs via `curl`, e nós, no script de build, fazemos o export via bash script.

**Comment by samuelsilvadev** [comment]
Putz, massa 💪💪

Vou tentar essa abordagem mesmo.
