### ISSUE TITLE
Preciso deixar um "a" selecionado mais não esta ficando poderia me ajudar achar o erro?

### ISSUE THREAD

**Issue by raphaelgs** [frontendbr/forum#908]
Não estou conseguindo colocar ele ativo de acordo com a pagina que ela está. Eu to puxando através do slug

      <script>   
                   function mostrarAtivo(tag){
                   var tag_li = document.getElementById('lista_menu');
                   var tag_a = tag_li.getElementsByTagName('a');
                   for (i=0; i<tag_a.length; i++ )
                   {
                      tag_a.style.color = "";
                   }
                      tag.style.color = "#000";
                   }
       </script>
      <ul class="menu-programas" id="lista_menu">
                  <?php
                        $categorias = get_terms('categoria-programacoes',
                            array(
                                'hide_empty' => false,
                                'orderby' => 'slug',
                            )
                        );
                   ?>
                  <?php
                        foreach ($categorias as $categoriaitem):
                            echo '<li class="menu-programas-li categoria-'. $categoriaitem->term_id.'" >';
                            echo '<a href="'.get_term_link($categoriaitem->term_id).'" class="link-nav-categoria" 
                            onclick="mostrarAtivo(this)">';
                            echo $categoriaitem->name;
                            echo '</a>';
                            echo '</li>';
                        endforeach;
                    ?>
          </ul>

**Comment by ninetails** [comment]
Assumindo que é wordpress, não seria melhor verificar se o termo é o atual direto no PHP? Adicionar uma classe, exemplo `selected` após o `link-nav-categoria` e estilizar via css?

Não sei se está correto, mas:

```php
echo '<a href="'.get_term_link($categoriaitem->term_id).'" class="link-nav-categoria ' . (get_queried_object()->term_id === $categoriaitem->term_id ? 'selected' : '') . '">';
```

Source: https://stackoverflow.com/a/12289287

Aliás, o clique provavelmente não vai funcionar, pq ele vai te levar para uma página nova, e creio que não executando o seu javascript.

**Comment by LFeh** [comment]
@raphaelgs Conseguiu resolver?

**Comment by raphaelgs** [comment]
@ninetails Muito obrigado pela ajuda agora deu certo.
@LFeh deu certo sim

**Comment by raphaelgs** [comment]
[resol]
