### ISSUE TITLE
Quais são os principais estágios na carreira de um programador?

### ISSUE THREAD

**Issue by Cleysonlb** [frontendbr/forum#909]
Movido por [este post](https://www.quora.com/What-are-the-growth-stages-of-a-programmer/answer/Andreas-Blixt) que tem até um teor cômico, quero trazer essa discussão para o forum, quais os principais estágios na carreira de um programador?! Como foi a evolução na sua carreira?!

![Alt Text](https://media.giphy.com/media/vzO0Vc8b2VBLi/giphy.gif)

**Comment by lucasfcosta** [comment]
Posso resumir em tom cômico também?

* Eclipse
* Sublime Text
* Vim

**Comment by LFeh** [comment]
#132 #353 #456 Acho que essas issues atendem.
