### ISSUE TITLE
Quais as habilidades técnicas e habilidades sociais para começar a dar consultoria?

### ISSUE THREAD

**Issue by Cleysonlb** [frontendbr/forum#918]
Qual o caminho para se tornar um consultor?! Quais soft e hard skills são necessárias?!
Se alguém tem experiência para compartilhar, pode falar um pouco do workflow?!

**Comment by letanure** [comment]
<joke>Uma delas é saber se expresar bem, tipo colocando uma descricao melhor no seu tópico</joke>

serio agora, explica melhor o que quer, comeca com uam lista do que imagina, acho que vai ter uma discussao melhor

define front, back, full, etc

**Comment by Cleysonlb** [comment]
@letanure especifiquei melhor 💃

**Comment by LFeh** [comment]
@Cleysonlb escalando um pouco, o que você entende como um "desenvolvedor consultor"?

**Comment by letanure** [comment]
isso é bem generico. melhor comecar entao dizendo onde ou como gostaria de trabalhar

**Comment by bernardodiasc** [comment]
"soft e hard skills", "workflow", etc... essas palavras em outro idioma são fáceis de entender para quem ta acostumado ou conhece bem o outro idioma. Mas usá-las em consultoria demonstra despreparo. É muito comum pessoas usando terminologias estrangeiras pra mascarar falta de conhecimento ou mesmo injetar um punhado enorme de significados em um único termo, as vezes por não conseguir compreende-lo a ponto de não conseguir encontrar a tradução plausível.

Veja, não sou contra usar essa palavras num meio técnico onde sei que todos sabem do que to falando, mas não pense que vai soar bonito quando for dar uma consultoria e as pessoas não entenderem o que quer dizer pq escolheu a forma de comunicação mais xique.

"Skills" são habilidades. "Soft e hard skills" é um monte de coisa empacotada e só faz sentido pra quem ta ligado no assunto, que tal "habilidades empáticas" e "habilidades técnicas", ou qualquer outra coisa, ja que esses termos são usados pra resumir uma pancada de coisas, melhor ainda ser específico dentro do contexto. "Workflow" é "fluxo de trabalho", faz muito mais sentido falar sobre o fluxo de trabalho do que do workflow, especialmente pra quem não fala _fancy-gringuês_...

Como foi comentado logo no inicio dessa discussão, "saber se expressar bem" é uma habilidade crucial, fundamental e decisiva ser um consultor bem sucedido.

**Comment by Cleysonlb** [comment]
@bernardodiasc estou utilizando termos comuns no ambiente de um desenvolvedor, e estamos no github certo?!
Mas é bom saber que nem todo mundo aqui entende termos em inglês tão comuns :)
Vou editar para seu melhor entendimento!

**Comment by bernardodiasc** [comment]
@Cleysonlb como disse, não estou te criticando nem a ninguem que usa esses termos. Não leve pra esse lado, usei de exemplo pra explicar sobre a questão. :)

**Comment by bernardodiasc** [comment]
> Vou editar para seu melhor entendimento!
Não por mim mano, eu entendo. Vc pediu dicas sobre consultoria, minha dica foi sobre consultoria. 😄

**Comment by bernardodiasc** [comment]
@Cleysonlb nao fecha nao, esse assunto é muito bom 😄

**Comment by Cleysonlb** [comment]
A issue não ficou muito clara, fechei pra não poluir a listagem de issues abertas!
Vou recriar depois trazendo uma discussão mais direcionada :)

**Comment by LFeh** [comment]
@Cleysonlb Se abrir outra, joga as respostas do @bernardodiasc lá ;)

**Comment by Cleysonlb** [comment]
show ;)
