### ISSUE TITLE
Procurando por novas experiências.

### ISSUE THREAD

**Issue by leonardoperlim** [frontendbr/forum#919]
E ai pessoal, sou estudante de Ciência da Computação e estou me interessando bastante pela área de desenvolvimento web, fiz alguns cursos online, mas acho a parte prática um pouco vaga, queria participar de algum projeto para explorar melhor meus conhecimentos na área e poder ganhar uma bagagem maior para o mercado de trabalho.

Se tiverem algo estou a disposição de fazer coisas simples e complexas também.

Abraços.

**Comment by silvaMatheus** [comment]
De uma olhada nesse [repositório](https://github.com/LFeh/frontend-challenges)

**Comment by LFeh** [comment]
#801
