### ISSUE TITLE
Quem são suas referencias em desenvolvimento frontend ?

### ISSUE THREAD

**Issue by letanure** [frontendbr/forum#921]
Estava conversando com um colega sobre isso e resolvi perguntar aqui. (sei que existe outro post parecido ( #879 ) mas gostaria de saber sobre quais pessoas e como seguem.

E nao é minha ideia uma lista generica, e sim quem realmente seguem, prestam atencao quando veem o nome em algo

entao, comecando:

## Como acompanho
- Uso o [devspace](https://devspace.io/), 
- twitter 
- follow no facebook principalmente, 
- às vezes ir nos blogs diretamente

## Quem sao minhas referencias hj:

- @addyosmani
- @codepo8
- @sindresorhus
- @yyx990803
- @LeaVerou
- @eddyerburgh
- @paulirish
- @ebidel
- @zenorocha
- @cowboy
- @bradfrost
- @darkwing
- @jeresig
- @stubbornella
- @stevesouders

**Comment by icaioincau** [comment]
Fora os citados, tbm sigo:

https://github.com/sergiolopes
https://github.com/wesbos
https://github.com/kittens

**Comment by eduardojmatos** [comment]
@letanure manolo, teve uma issue parecida uns dias atrás:

https://github.com/frontendbr/forum/issues/879

**Comment by LFeh** [comment]
@letanure Mergeia sua issue na outra?

**Comment by letanure** [comment]
minha ideia era mais sobre pessoas e como seguir tanta gente ao mesmo tempo

**Comment by pedroguilhermelima** [comment]
Depende.
