### ISSUE TITLE
Quanto cobrar pelo serviço freela?

### ISSUE THREAD

**Issue by lpdlima** [frontendbr/forum#924]
E ai galera tudo bem? Sou estudante do 6º semestre de Ciência da Computação e me surgiu um trabalho de freelancer para uma empresa local na minha cidade.

Seria um site de vendas em PHP e eu vou fazer um sistema para gerar arquivos em pdf com alguns dados de cada venda feita no site deles.

Como é a primeira vez que trabalho como freelancer fiquei na dúvida de quanto cobrar pelo serviço, se puderem me ajudar com valores ou experiências de como vocês fazem quando trabalham como freela, ficaria muito agradecido.

Abraço.

**Comment by phsantiago** [comment]
Por ser o primeiro trabalho te recomendo cobrar barato, porém orçar muitas horas e tentar receber por feature entregue. Também acho bom você focar em aprender o máximo agora e só depois começar a cobrar caro por já ter experiência.

**Comment by caina** [comment]
maior bobagem é vender o projeto fechado, já me ferrei várias vezes! ahahahha se conseguir vender features e entregar semanalmente alguma coisa seria muito melhor.

**Comment by weltonsanches** [comment]
Cobrar por projeto fechado não é fácil, principalmente se você tem pouca experiência e consequentemente dificuldades pra fazer uma estimativa de horas. Melhor forma é cobrar por hora. Também é legal cobrar por sprint ou algo assim (com um tempo curto), dessa forma é mais fácil de cobrar e você ainda deixa o cliente bem por dentro do andamento do projeto.

**Comment by LFeh** [comment]
Por ser o primeiro complica um pouco.

Mas tente fazer uma estimativa de quanto vale sua hora e de quanto tempo você precisa para entregar o escopo acordado, então você cobra por horas e mostra como a cobrança está sendo feita.

Se o escopo muda você adiciona mais horas.

**Comment by laurolnunes** [comment]
Concordo com o @weltonsanches e o @phsantiago, tente dividir o projeto em partes entregáveis, que o cliente consiga ver a funcionalidade e cobre por elas separadamente. Facilita bastante pra você e pra que ele também saiba o andamento do projeto.
Com já foi dito antes, eu também já me ferrei muito por cobrar um valor fechado para o projeto todo. Você nunca sabe as dificuldades que vai encontrar. Boa sorte e bom trabalho!

**Comment by bernardodiasc** [comment]
![dvsanwjxuae0cl4](https://user-images.githubusercontent.com/131859/35819584-4188ebc6-0a8a-11e8-8bd4-c746aaf4f534.jpg)

**Comment by gabrieldarezzo** [comment]
Tente definir o máximo de esforço que você vai precisar,

> Seria um site de vendas em PHP e eu vou fazer um sistema para gerar arquivos em pdf com alguns dados de cada venda feita no site deles.

Uma descrição bem definida pode te ajudar, assim ninguém fica triste. 

Ex:
- Areá de Login
- Esqueci a Senha
...

Nessa parte:
> alguns dados 

É interessante definir o escopo nos mínimos detalhes até para criação da estrutura de dados/base 
Por exemplo:
- Exibir se é a primeira compra daquele cliente / Qnt de compras por Cliente 
- PDF mais vendido/baixado
- Exibir tempo médio por pagina. 
- Peso máximo do .pdf 
- Qnt de pdf previstos para armazenar 10 / 200 / 2000 / 10kk ?
- Possibilitar Download
- Atualizar PDF? CRUD completo do PDF?
- No Mobile o pdf: abrir diretamente do Browser ?
- Proteção paliativa para acesso do pdf para pessoas externas / que não possuem login
- Relatórios de uso
- Gráficos com indicadores
... 


Na minha trajetória de freelas, a parte mais difícil é conseguir prever / fazer todas essas perguntas, assim facilitando o desenvolvimento.

Outro ponto já comentado acima pelos colegas seria uma coisa q da certo pelo menos pra mim:
Após definir o projeto, estimar uma qnt de horas para cada tarefa e fechar as funcionalidades:

Ex:
Crud de PDF: 8hrs
Valor H : x 
x * 8 = y;

Beleza, tudo acima seria apenas para orçamento, (recomendo fortemente ter uma proposta descritiva com hrs , valor hora, validade de proposta (Ex: 10 dias, após isso precisa ser refeita), estimativa de dt de entrega, formas de pagamento junto com possibilidade de parcelamento, se vai possuir valor para iniciar o projeto, etc)

Ahhh sobre descontos, recomendo dar uma olhada nesse cara:
https://www.youtube.com/watch?v=B2ARbvMsP6E


Após estar definido oq fazer e o que deve ser entregue pelo valor x eu basicamente possuo três ambientes abusando do uso do Git.

Desenvolvimento (local)
Homologação (controle meu)
Produção (normalmente controlado pelo cliente)

Assim possibilitando validar aos poucos e alinhar expectativa com possibilidade técnica (mostrar uma demo pro cara)

OK, Está tudo certo no ambiente de homologação e alinhado com a proposta?
-> Pagamento
-> Subo para a produção / ambiente controlado pelo cliente.


Basicamente é esse o fluxo, espero ter ajudado.

**Comment by gabrieldarezzo** [comment]
Mais informação em:

#52
#142

https://devnaestrada.com.br/2016/08/26/vida-de-freelancer.html

**Comment by lpdlima** [comment]
Pessoal, 

muito obrigado pelas dicas, fiz a estimativa de horas/trabalho mandei pro cliente e vai sair o projeto.

@gabrieldarezzo Não tinha pensado em todas as coisas que tinham que ser levadas em conta, valeu por abrir meus olhos para esse lado.

Então, obrigado novamente pessoal foi muito importante essas experiências para eu poder começar o primeiro projeto. 

Acho bacana o pessoal seguir contando suas experiências, então se caiu aqui por agora conta como é pra ti.

Abraço.

**Comment by felipechalreo** [comment]
Prova a calcular a tua hora com isso aqui ... 

https://www.calculadorafreela.com/pt/

**Comment by guilhermealveslopes** [comment]
Acho que é como o @phsantiago  falou ali. Inicialmente foca em aprender.
Certamente por ser seu primeiro freela vai te surgir algumas dúvidas na hora de desenvolver, e pra isso vc vai gastar tempo aprendendo, ao meu ver, horas que você não pode cobrar do cliente.

Então como já foi dito, não foca tanto no valor agora, mas pede um prazo que fique bom pros dois lados.

Com o tempo tu vai aumentando a eficiência e consequentemente o preço.
O foco pra mim sempre foi aprender mais com cada job, a grana veio como consequência, e sempre veio muito bem por sinal <3 

Abraço e sucesso pra ti :)
