### ISSUE TITLE
Estou aprendendo. 

### ISSUE THREAD

**Issue by brunojokubauskas** [frontendbr/forum#925]
Bem, já tentei várias vezes aprender desenvolvimento Front-End e das vídeos aulas que vi não gostei da didática do professor. Já assinei o Alura e não gostei por ter achado muito superficial (Gosto de me aprofundar em tudo). Até que então eu achei o curso do Andre Fontenelle de desenvolvedor web no udemy na promoção e estou gostando bastante. Quais boas práticas pra iniciantes vocês recomendariam? Já pesquisei no Google mas eu fico muito na duvida de como praticar e que tipos de projetos posso colocar em prática.  O que me recomendariam? Gostaria de ouvir de quem já está na área a um bom tempo e de quem está começando também.  (:

**Comment by luizbills** [comment]
- Caso você queria ser um *front-ender* mais programador recomendo que **procure um problema e desenvolva uma solução para ele**. Pode ser problema de outra pessoa, grupo, empresa ou de preferência um seu mesmo. 

- Se você quer ser um front-end mais na pegada designer, eu sugiro você fazer **copywork**. Que é nada mais que pegar um site/interface e recria-lo.

Repita várias vezes cada um desses tópicos e procure freelas também para te dar uma motivação ($) a mais.

**Comment by Leocardoso94** [comment]
Olha esse repositório [frontend-challenge](https://github.com/LFeh/frontend-challenge) tem diversos desafios para vagas de front-end. 

Creio que seria de grande valia tentar resolver alguns desses desafios com os conhecimentos que você adquiri no seus estudos.

Uma plataforma que me ajudou bastante com front-end no início foi o [freeCodeCamp](https://www.freecodecamp.org/) lá eu aprendi bastante coisa e tem vários desafios muito legais, e ainda te dá um certificado ao final dos cursos, tudo de graça!

**Comment by danielschmitz** [comment]
Você nao vai ficar bom apenas vendo vídeos. Aquilo ali é para dar um norte. Somente treinando você irá melhorar.

Recomendo:
https://github.com/LFeh/frontend-challenge (https://link.getmailspring.com/link/local-a474f5aa-36dd@linux/0?redirect=https%3A%2F%2Fgithub.com%2FLFeh%2Ffrontend-challenge&recipient=reply%2B0017093c0d0369fdfb488623c5fa1d042604ee1ed5b2d06a92cf000000011690bcb992a169ce118e6a54%40reply.github.com)

**Comment by brunojokubauskas** [comment]
Então. Respondendo a pergunta do  @luizbills  quero ser mais _**programador**_. Eu peguei o básico hoje, fiz 6 seções do curso se não me engano e acabei fazendo uma lista do que quero estudar e o que estudar como prática básica. Tenho que implementar algumas coisas fora os exercícios do curso. Comecei o curso hoje e to gostando bastante.  E desculpe-me pela pergunta meio fora ou dentro da issue, cursos online como os do udemy é válido no mercado de trabalho?  E uma pergunta meio " fora" ou  não, como organizar meus repositórios? Eu tinha uma conta antiga no GitHub acabei excluindo pela desorganização que estava e não tinha/não tenho tanto conhecimento em Git/GitHub. Só sei abrir algumas issues e fazer pesquisa. É recomendável colocar TUDO o que eu fizer no GitHub?
