### ISSUE TITLE
Testes de Snapshot e Tipagem com React

### ISSUE THREAD

**Issue by thulioph** [frontendbr/forum#927]
Gostaria de compartilhar com vocês alguns questionamentos que tive sobre **testes** e **tipagem estática** utilizando o `react-create-app`.  A idéia é que com os levantamentos daqui, eu consiga bolar uma estratégia legal pra ir adicionando os testes na aplicação, iniciando pelos **stateless componentes** e depois indo para os **containers**.  

Estou pensando no seguinte fluxo:

1. Adicionar checagem de tipos em todos os stateless components;
2. Adicionar teste de snapshot;
3. Escrever os primeiros testes para os stateless components (utilizando jest);

Alguns questionamentos foram surgindo no momento de desenvolver, são eles:

## Testes de Snapshot
Em um projeto sem nenhum tipo de testes, vale a pena adicionar [teste de snapshot](https://facebook.github.io/jest/docs/pt-BR/snapshot-testing.html)? Por ser o mais simples, seria uma boa aplicar aos **stateless components**?

## Type Checker
Por não ter nenhum tipo de testes, imagino que a adição de um `type checker` seria útil pelo fato de realizar uma verificação mínima dos tipos? Faz sentido? 

## Flow
Tentei adicionar o [`Flow`](https://flow.org/en/), mas me incomoda o fato de ter que adicionar um comentário `//@flow` para que ele "atue" sobre o arquivo. 

1. Existe alguma configuração diferente disso? 
2. Também não obtive sucesso em executá-lo com `watch`, tive que fazer uma ["gambiarra"](https://stackoverflow.com/a/41766695/4008711) para que rolasse, é isso mesmo?

## Typescript
Não tive sucesso na adição do `Typescript` (em um projeto já em andamento), o `react-create-app` só oferece suporte, [caso você esteja iniciando um novo projeto](https://github.com/facebook/create-react-app#popular-alternatives). É possível utiliza-lo sem a necessidade de um `react-scripts eject`?

----

Alguém com mais experiência, que já tenha passado por esse tipo de dúvida/problema, poderia dar uma luz? 😄

**Comment by arojunior** [comment]
Para os testes de snapshot, utilizo o [storybook](https://github.com/storybooks/storybook), ele tem uma integração com o Jest, bem fácil de configurar no `create-react-app`

Para type checking, você pode começar com algo mais simples, como [prop-types](https://reactjs.org/docs/typechecking-with-proptypes.html)

**Comment by LFeh** [comment]
Curiosidade @thulioph, como chegou na ideia de usar tipagem estática no React?

Pergunto isso porque "ganhei" o TypeScript usando o Angular e to curtindo bastante.

**Comment by thulioph** [comment]
Já conheço o **Storybook**, mas queria saber se é "útil" adicionar `testes de snapshots` onde não existe, nenhum tipo de teste. 

Optei por utilizar esta ferramenta apenas quando estava começando um projeto, onde tenho controle de tudo e posso criar cada componente separado, só plugando-os depois. Mas neste caso, o projeto já está em andamento e o objetivo é melhorar a cobertura de testes (seguindo um fluxo de trabalho lógico).

E sobre `type checking`, já existe `Prop-Types` para os componentes, e se adicionando o `Flow` ou `Typescript` iria ajudar em alguma coisa, se valeria a pena, (já que não tem nenhum dos dois).

@arojunior, minha dúvida era mais em relação a se faz sentido utilizar, não qual ferramenta. 😄

**Comment by bernardodiasc** [comment]
Eu particularmente gosto dos snapshots pra poder revisar o HTML 😄 Em várias situações identifiquei bugs ou "edge cases" revisando os snapshots. A parte de prevenir regressão não tem sido util pra mim pois sempre que os snapshots sofrem alterações, nos meus casos, são alterações intencionais.

**Comment by thulioph** [comment]
Imagino que a melhor maneira para melhorar a cobertura de testes de um projeto que não tem nada de teste, seria:

1. adicionar um `type checking`;
2. adicionar `testes de snapshot` (mínimo teste possível);
3. adicionar os `testes unitários`;

Cc: @LFeh

**Comment by bernardodiasc** [comment]
PropTypes é uma espécie de type checking, da pra viver só com isso dependendo da complexidade do projeto. Imagino que Flow a TypeScript vai te ajudar mais nos métodos unitários, mas caso vc inclua um desses no projeto, pode substituir o PropTypes.

**Comment by bernardodiasc** [comment]
> Em um projeto sem nenhum tipo de testes, vale a pena adicionar teste de snapshot? Por ser o mais simples, seria uma boa aplicar aos stateless components?

Sim, especialmente para os componentes stateless. Cria snapshots para cada estado previsível. O teste mais simples é o "minimal render" quando vc chama o componente sem propriedade nenhuma (ex: `<ComponentName />`). Se voce colocar proptypes obrigatórias nos componentes vc vai perder o benefício desse teste, recomendo abrir mão das props obrigatórias pra voce poder ter controle total do que renderiza na tela, até mesmo pq PropTypes não bloqueia a execução como Flow faz, e pega mal aparecer um "undefined" na tela, melhor do que assumir que a prop obrigatorias sempre vai estar lá é tratar as excessões.

> Por não ter nenhum tipo de testes, imagino que a adição de um type checker seria útil pelo fato de realizar uma verificação mínima dos tipos? Faz sentido?

É útil, pode evitar muitos problemas em sistema complexos. Mas a complexidade do sistema aumenta muito com sistema de tipagem. Avalia o custo benefício se PropTypes não estiver atendendo. A alternativa mais "barata" é tratar os valores, definir defaults, etc... mas barato as vezes sai caro... então uma verificação mínima dos tipos pode ser útil, especialmente pros métodos unitários.

Sobre o flow, vc pode colocar no https://github.com/okonet/lint-staged, funciona legal, nao precisa ser no watch. E o lance do `//@flow`, acho que ele coloca automaticamente, talvez o `eslint --fix` com plugin do flow faça isso, não tenho certeza.

**Comment by thulioph** [comment]
Valeu pela ajuda @bernardodiasc
