### ISSUE TITLE
Como saber se tenho Experiência com API's?

### ISSUE THREAD

**Issue by crisgon** [frontendbr/forum#930]
Pessoal, estava olhando algumas vagas aqui no repo e notei que muitas vagas pedem experiência com API's. Mas me bateu a duvida, o que exatamente querem dizer com isso?

**Comment by diessica** [comment]
recomendo: [Nobody introduced me to the API](https://www.robinwieruch.de/what-is-an-api-javascript/)

**Comment by romulosousa27** [comment]
Hoje API's são essenciais na vida de um Dev. Eu era leigo até um tempo, continuo haha.
Mas agora sendo menos.
