### ISSUE TITLE
Devo estudar UX/UI Design junto com HTML, CSS & JavaScript? 

### ISSUE THREAD

**Issue by brunojokubauskas** [frontendbr/forum#933]
Bem, estou começando e acabei a grade de HTML e vou começar CSS e depois partir pra JavaScript. É importante eu estudar UX/UI Design junto com o estudo front-end  focado na parte de programação ou devo estudar mais pra frente? E quais cursos de UX/UI Design vocês recomendariam?

**Comment by simaodeveloper** [comment]
Bruno eu recomendo você fortificar sua base para realizar o trabalho de um Front-End Junior primeiro:

- HTML, CSS, Javascript e jQuery
- Baixe templates free de PSDs na internet para fixar o conhecimento obtido.
- Aprenda a utilizar plugins, validar formulário, slides, draggable, animações com CSS e JS (Veja TweenMax)
- Desenvolva sites responsivos (mobile, tablet e desktop)
- Estudo framework CSS como o Bootstrap (recomendo), Foundation ou SemanticUI
  
Depois sim recomendo fazer esse curso aqui, pois você pode trabalhar em uma empresa que necessite muita comunicação com o time de UI/UX, esse curso é praticamente uma especialização para designers que querem focar em desenvolvimento de interfaces (eu estou fazendo e estou curtindo):

- https://www.udemy.com/design-de-interface

E por último estudar back-end, sugiro PHP pela demanda de projetos que há no mercado para freelas ou qualquer linguagem que você goste e consiga desenvolver uma aplicação web, assim você vai entender como uma aplicação web funciona num todo, sugiro o canal e cursos do Brad Traversy:

- Canal: https://www.youtube.com/user/TechGuyWeb
- Cursos: https://www.udemy.com/user/brad-traversy/

O importante é você ter uma base geral, mas focar em algo, o front-end é muito mais do que eu disse acima, pois há mais bibliotecas, frameworks, ferramentas a se aprender, mas com o tempo e com ajudar dos amigos, tanto da comunidade ou do futuro time que você trabalhar, você vai entendendo melhor o que precisar aprender e por em prática.

Espero ter ajudado!

See ya!!!

**Comment by willianjusten** [comment]
Como é uma issue duplicada, deletando essa aqui e deixando a outra =)

**Comment by LFeh** [comment]
@simaodeveloper Joga sua resposta lá?

**Comment by simaodeveloper** [comment]
Uai mas ta la, eu dupliquei a resposta também hahaha

**Comment by LFeh** [comment]
ahh, hahahahahaa
