### ISSUE TITLE
Como se escreve Front-end?

### ISSUE THREAD

**Issue by ghost** [frontendbr/forum#934]
Front-end?
Front End?
Front-End?

Qual seria a forma correta?
Cada vaga que vejo escreve de uma forma, nos sites a mesma coisa.

**Comment by luizbills** [comment]
Se alguém descobriu, ele não contou para ninguém.

**Comment by rubenmarcus** [comment]
@luizbills  kkkkkkkk

**Comment by caioincau** [comment]
Gosto de seguir a CGC
http://gcc.gnu.org/codingconventions.html#Spelling

"front end" para substantivo e "front-end" para adjetivo.

**Comment by LFeh** [comment]
hahahaha.
