### ISSUE TITLE
Ser registrado como Front-end ou Full-stack?

### ISSUE THREAD

**Issue by ghost** [frontendbr/forum#937]
O que vocês acham? 
Tenho essa possibilidade de escolha.

**Comment by luizbills** [comment]
Você fala registrar na carteira de trabalho?

**Comment by robennelson** [comment]
Sim

**Comment by robennelson** [comment]
Desenvolvedor Front-end ou Desenvolvedor Full-stack?

**Comment by alexsandro-xpt** [comment]
Acredito que só pode nomes reconhecidos pela legislação como por exemplo:
Programador de sistemas, analista de sistema e etc...

**Comment by rubenmarcus** [comment]
eu já fui registrado como Desenvolvedor Front-end Pleno..

**Comment by rubenmarcus** [comment]
a empresa que escolhe o cargo, se você tem a opção você tem que ver o que quer pra sua carreira.. continuar como Front e focar nisso, ou ir pra Fullstack.

**Comment by woliveiras** [comment]
Já fui registrado como front-end junior, front-end pleno e hoje como desenvolvedor de software.

O registro em carteira depende de questões sindicais também.

Mas o registro na carteira não te impede de mudar de especialização (se quiser) depois, por exemplo.

Até hoje nenhuma empresa perguntou pra mim como eu era registrado, viu. :grin:

**Comment by caioincau** [comment]
Eu sou registrado como "Desenvolvedor Front-End", até pq, só faço front, acho que se você quer fazer só front, esse é o correto, até por que, se estiver como Full Stack, seu Job description inclui mais coisas do que Front-End e isso pode de prejudicar em um possível processo trabalhista.

**Comment by LFeh** [comment]
Não acho que o nome do registro faz muita diferença. Já tive registros em coisas como "Programador HTML", hoje estou como "Analista de Sistemas", mas na pratica não muda nada, depende mais da empresa que está trabalhando.

**Comment by danielmakowiesky** [comment]
Na verdade se for parar pra analisar friamente a maioria das empresas registram como " desenvolvedor de software" e caso tenha um plano de cargos e salários bem definido dependendo do seu histórico profissional te contratem como " especialista " ou analista. No caso eu sou contratado como Desenvolvedor de software e mas sou full-stack

**Comment by trevobr** [comment]
Essa questão me veio a mente depois de ter sido registrado como Front end ... não tenho a especificação - junior - pleno - senior. O que , na minha opinião, dá uma enorme vantagem de barganha para a contratante. O que você acha?

**Comment by robennelson** [comment]
Escolhi Desenvolvedor Front-End Júnior. Vou investir na área de front. Até hoje me considerava full-stack, sempre fui mais envolvido com o back-end, mas curto CSS e JavaScript. É uma pena que o salário de front-end esteja um pouco abaixo do back-end. Estou migrando da área de infra, por isso só consegui entrar como júnior.

**Comment by rubenmarcus** [comment]
@robennelson  depende da linguagem usada no back-end, e a empresa que você é front-end.
