### ISSUE TITLE
Recomendações de livros 

### ISSUE THREAD

**Issue by silvaMatheus** [frontendbr/forum#941]
Pessoal poderiam recomendar alguns livros sobre a nossa área ou até mesmo livros q vcs acham interessante de um jovem desenvolvedor ler,  gostaria de livros mais cotidianos para ler na ida e volta do serviço.

**Comment by woliveiras** [comment]
@silvaMatheus você manja de inglês ou consegue ler livros nesse idioma?

**Comment by silvaMatheus** [comment]
Consigo ler em inglês

**Comment by camillodev** [comment]
Da uma olhada nessa lista que o @woliveiras fez. Tem livros tecnicos e nao tecnicos e gostei bastante. 
Atualmente to lendo O Poder do Hábito

Lista
https://woliveiras.com.br/posts/Livros-que-todo-desenvolvedor-de-software-deveria-ler/

**Comment by silvaMatheus** [comment]
obg @camillodev  pelo link foi  muito útil e obg @woliveiras  pelas indicações

**Comment by isaacguerreir** [comment]
Se já souber Javascript esse livro é uma mão na roda.

http://sd.blackball.lv/library/JavaScript_Patterns_(2010).pdf

**Comment by MatCunha** [comment]
@silvaMatheus 

Eae mano! ;D

Para JavaScript eu recomendo o Eloquent JavaScript --> http://braziljs.github.io/eloquente-javascript/

Veja também os livros desse artigo do TableLess --> https://tableless.com.br/primeiros-passos-fullstack-javascript/

Att.

**Comment by tarciozemel** [comment]
"Código Limpo", do Uncle Bob.

**Comment by gabrieldarezzo** [comment]
Se falou q consegue ler Ingles, manda bala:
https://jsbooks.revolunet.com/

Físico q eu li e curti:
https://www.novatec.com.br/livros/ninja-javascript/

Um Curso q eu comprei tmb e recomendo pra geral q esta querendo aumentar o nível de JS é o de TDD:

https://www.udemy.com/js-com-tdd-na-pratica/
( Estava 200 pila qnd comprei kkk, está 23 )

**Comment by didiraja** [comment]
Recomendo começar por esse aqui pois é geralzão https://www.casadocodigo.com.br/products/livro-guia-frontend

**Comment by Predoff** [comment]
Gosto muito dos livros da editora [The Pragmatic Bookshelf](https://pragprog.com/).
