### ISSUE TITLE
Recomendações de Empresas em SP

### ISSUE THREAD

**Issue by camillodev** [frontendbr/forum#942]
Fala, galera
Sou do RJ e estou querendo trabalhar em SP e gostarja de trabalhar em empresas legais onde possa aprender bastante. E em SP tem milhares de empresas.
Quais são as empresas que vocês amariam trabalhar ou tiveram otimas experiências quando trabalharam la ou ainda trabalham?

**Comment by LFeh** [comment]
Acho que rola aproveitar essa sua issue mesmo hein? haha #504
