### ISSUE TITLE
Procurar emprego como Junior ou Estágio na área?

### ISSUE THREAD

**Issue by MatheusWTF** [frontendbr/forum#946]
Ando estudando Front End há um tempo, (on and off por uns 4 anos, mais centrado há uns 6 meses). E como estou desempregado há quase um ano, resolvi buscar agora um emprego na área mesmo, só que ainda estou fazendo faculdade (à distância), não sei se devo procurar de cara um emprego como Junior ou se é melhor fazer um estágio, e se for melhor estágio, como encontrar um direcionado mais para Front end? porque a maioria que vejo por ai é para help desk

**Comment by LFeh** [comment]
Essas issues podem te ajudar #222 #118 #456 #717
