### ISSUE TITLE
Como eu posso fazer autenticação com cookie em redux?

### ISSUE THREAD

**Issue by viniosouza** [frontendbr/forum#947]
Estou com alguns problemas em minha aplicação, por conta de alguns problemas no retorno do token, eu preciso refatorar o código, mas nunca utilizei cookie e gostaria de saber se tem algum artigo ou vídeo falando sobre isso. Obrigado pela atenção.

**Comment by LFeh** [comment]
Pode ajudar aqui @fdaciuk ?

**Comment by grsabreu** [comment]
Melhor usar localStorage
Como vc usa o token? Passando como Authorization header? Se sim nem precisa de Redux

**Comment by grsabreu** [comment]
localStorage é mais simples e bem sussa de usar

basicamente só
```
localStorage.setItem('USER_TOKEN', 'asdlfjasdfa')
localStorage.getToken('USER_TOKEN') => retorna o valor
localStorage.removeToken('USER_TOKEN')
```

https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by edmolima** [comment]
@viniosouza como o pessoal falou, acho que seria interessante você usar essa abordagem do localstorage. dessa forma tu pode usar esse token no Authorization Header sem muitas complicações, faria algo assim:

`Bearer ${localStorage.getItem(ACCESS_TOKEN_KEY)}`

Hoje eu tenho uma abstração só pra usar o localstorage e consigo fazer exatamente isso que o @grsabreu faz, para setar, buscar e remover.

**Comment by grsabreu** [comment]
isso ☝️ , sempre bom fazer uma abstração pra evitar aqueles typos marotos no nome da key haha

**Comment by viniosouza** [comment]
@grsabreu Uso passando pelo authorization header, muito obrigado vou refatorar mudar para localStorage, mas muito obrigado mesmo!

**Comment by viniosouza** [comment]
@edmolima  Muito obrigado
