### ISSUE TITLE
A Verdadeira Razão De Você Ir Mal Na Faculdade

### ISSUE THREAD

**Issue by rrrichter** [frontendbr/forum#948]
Mensagem editada

**Comment by luizbills** [comment]
Pô se fosse de graça eu iria ler.

**Comment by mahenrique94** [comment]
Descordo de algumas coisas e o demais é algo que todo mundo já deve saber.

**Comment by MendesGabriel** [comment]
"Digital Influencer" chegaram aqui no forum do Github. Péssimo sinal.

**Comment by LFeh** [comment]
Ta de sacanagem

**Comment by diogomoretti** [comment]
Aposto que é da "área de marketing digital" onde pessoas fracassadas trabalham postando coisa para redes sociais e acham que todo mundo é soft user a ponto de não saber diferenciais uma captura de lead de um compartilhamento de conteúdo.

RIP
