### ISSUE TITLE
Equivalente da graduaçāo tecnológica em ingles?

### ISSUE THREAD

**Issue by KumoMg** [frontendbr/forum#949]
Boa noite galera.

Vendo os issues antigos eu notei que tem uma boa quantidade de pessoas que escolheram a graduaçāo tecnológica, a minha dúvida é em relaçāo a nomeclatura desse diploma em ingles, existe algum equivalente da graduaçāo tecnológica lá fora ?(caso nāo exista como se chamaria a graduaçāo tecnológica em ingles?)

**Comment by felipemfp** [comment]
@KumoMg, encontrou?
