### ISSUE TITLE
Monetização de blog

### ISSUE THREAD

**Issue by mahenrique94** [frontendbr/forum#950]
Bom dia galera, esse ano estou pegando firme no meu blog, estou vendo meios para monetizá-lo, estava pensando em Google AdSense para adicionar algumas propagandas, além disso, também preciso aumentar o número de visitas e assinantes na newsletter.

Gostaria de dicas de vocês para estar progredindo e conseguir unir o útila e agradável, ou seja, tentar compartilhar algum conhecimento e ter algum retorno.

**Obs:** Também estou pensando em gravar webnars com o eventials e disponibilizá-las por preços bem acessíveis, tipo R$10,00, o que acham?

Abraçoooos

**Comment by LFeh** [comment]
Mano, sinceramente não sei até que ponto vale a pena.

Todo mundo sabe onde o calo aperta, mas a questão é que você vai lotar seu site de propagandas (as vezes de gosto duvidoso) para ganhar uns trocados no fim do mês.

Entendo como "pagamento" pelos meus textos, o próprio sentimento de retorno para a comunidade, a exposição gerada e as oportunidades que surgem por conta disso. 

Claro, dinheiro nunca é demais, mas não acho que vale a pena. Opinião puramente pessoal.

**Comment by mahenrique94** [comment]
Estava exatamente com essa dúvida, o blog esta tão bonito sem ads kkk mas um extra sempre é bom, talvez vou mais para o lado das webinars, obrigado pelo feedback

**Comment by elfiservice** [comment]
Opa.. cara pra captura de Leads estão usando muito o funil de vendas, usando uma isca digital. 
Da uma busca sobre o assunto. ;)

**Comment by woliveiras** [comment]
@mahenrique94, ao invés de colocar propaganda no seu blog por que não criar cursos numa Udemy da vida?

Eu posso até tentar colaborar contigo para montar grades, pensar em assuntos para os cursos ou coisas do tipo, mas poluir o seu site seria algo "chato" no fim das contas. - não quero nada em troca, só que você continue com seu excelente trabalho no blog sem poluir ele :heart: 

Use o blog como vitrine para as pessoas darem credibilidade para o que você fala/ensina e crie conteúdo pago em uma plataforma como a Udemy, pois ai vai diminuir o trabalho com marketing, fora que o sistema de recomendação da Udemy é bem legal. - já comprei vários cursos que pingaram no email.

**Comment by DiegoFSFlor** [comment]
Melhor forma é usar funil de vendas, assim consegue monetiza melhor sua aplicação.

**Comment by marcusvcribeiro** [comment]
William, estava pensando nisso essa semana, em começar a montar cursos para
colocar na Udemy, só que não tenho a menor ideia de como começar, material
que tenho que comprar para gravar, ferramentas utilizadas para tais coisas.
Da uma Luz ai :)

Me interessa demais

Em 20 de fevereiro de 2018 10:09, William Oliveira <notifications@github.com

**Comment by mahenrique94** [comment]
boa @woliveiras estava em dúvida de monetizar o blog ou ir para um recurso como a Udemy ou eventials, então vou seguir o conselho, ajudou esclarecer minha dúvida.

Assim como o @marcusvcribeiro não tenho ideia alguma por onde começar, gostaria muito da sua colaboração sim.

Ainda estou em dúvida de Udemy ou Eventials, pois teoricamente utilizando Eventials eu irei abordar temas específicos e iria direto ao ponto, me poupando um trabalho de criar um curso inteiro, o que me aconselha?

Abraçooos

**Comment by luizbills** [comment]
Se for colocar ads coloca do **carbon ads** pelo menos kk
Mas a melhor forma que eu acho de monetizar é você vender seu peixe cara, cursos, softwares, temas, coisas que você faz/fez.

**Comment by mahenrique94** [comment]
Valeu galera, vou dar uma analisdada no Udemy ou Eventials, obrigado a todos.

**Comment by Pedro-Souza** [comment]
Deixa um espaço para doações

**Comment by tarciozemel** [comment]
Udemy posso dar minha opinião de novato: está sendo MUITO melhor do que na vez que experimentei colocar AdSense no blog (Carbon nunca tentei).

**Comment by Pedro-Souza** [comment]
Algo tipo "Gostou desse e dos demais posts? Ajude o autor doando qualquer quantia" aí tu deixa paypal, bitcoin e etc...

**Comment by mahenrique94** [comment]
Saquei @Pedro-Souza, valeu

**Comment by woliveiras** [comment]
@marcusvcribeiro, @mahenrique94, bora agilizar isso ae, então!

Vou chamar vocês por email pra gente ir montando esses cursos ae \o/

**Comment by TailoMateus** [comment]
Se precisarem de ajuda para revisar o conteúdo. Tamo aí!

**Comment by mahenrique94** [comment]
Demoro @woliveiras e @TailoMateus, obrigado pela força de vocês e todos que participaram da discussão.

**Comment by LeonardoSousa89** [comment]
Oi, esse tema está excelente me ajudou também a ter uma visão do assunto!
Abraços a todos!
