### ISSUE TITLE
Lugares para deixar anotações  de estudo ? 

### ISSUE THREAD

**Issue by silvaMatheus** [frontendbr/forum#952]
Pessoal como estou iniciando na area agora, estou estudando muito e sempre vou anotando as coisas no caderno, porem gostaria de sempre ter essas anotações comigo, indicariam algum app ou site para isso ? sao anotações um pouco grandes principalmente agora que comecei estudar js

**Comment by caioincau** [comment]
Eu uso Evernote

**Comment by kivervinicius** [comment]
Google Keep

**Comment by elfiservice** [comment]
<img width="1221" alt="screen shot 2018-02-21 at 15 45 19" src="https://user-images.githubusercontent.com/16091365/36498834-53ca5e8c-171e-11e8-9d07-6574b87cb172.png">

tenho usado bastante o OneNote da Microsoft .. funciona muito bem para este fim! 👍🏽

**Comment by fernahh** [comment]
@silvaMatheus Um repositório no github acho a solução mais fácil :wink:

**Comment by kivervinicius** [comment]
@fernahh acredito que não, um gist até poderia ser.

**Comment by kivervinicius** [comment]
A vantagem do Google Keep é se vc já possui uma conta no google (hoje quem não tem) já fica tudo vinculado,

**Comment by raisiqueira** [comment]
Uso Trello como um "Dailylog", quando estou estudando e tenho alguma dificuldade, coloco a solução lá ;)

**Comment by marcelgsantos** [comment]
Eu costumo fazer as **anotações** em Markdown e guardá-las no Dropbox. Dessa forma, as minhas anotações estão comigo em **qualquer lugar**. Posso acessá-las pelo smartphone na fila do banco ou no trabalho quando preciso revisar algum conteúdo.

**Por que Markdown?**
Utilizo Markdown pois ele me dá a **_flexibilidade_** de utilizá-lo com qualquer editor (pois trata-se apenas de texto) e me permite uma **_representação_** e **_visualização_** mais aprimorada quando renderizado. 

Com isso, consigo fazer anotações em tópicos, colocar o link para o artigo ou vídeo original no título da anotação, destacar termos importantes com **negrito** ou _itálico_ e colocar fragmentos de códigos `inline` ou em bloco.

Escrever arquivos em Markdown é muito fácil e alcança-se a fluência em pouquíssimo tempo. Você pode editá-lo utilizando um editor mais simples como o Bloco de Notas ou um mais avançado como o VSCode e vê-lo renderizado utilizando um plugin para SublimeText ou nativamente no VSCode ou ao subir o seu projeto para o GitHub.

**Por que Dropbox?**
Porque é simples e direto. E poderia ser qualquer outra ferramenta de armazenamento em nuvem.

**Exemplos:**

_1. lista de anotações no editor com pré-visualização_

![anotacoes-markdown](https://user-images.githubusercontent.com/753958/36512353-d0a2fb74-1748-11e8-815b-1eb7d15793e7.png)

_2. exemplo de anotação no GitHub com pré-visualização_

* https://github.com/marcelgsantos/curso-elm/blob/master/README.md

Recomendo o artigo do @fdaciuk para aprender mais sobre Markdown.

* https://blog.da2k.com.br/2015/02/08/aprenda-markdown/

[]s

**Comment by silvaMatheus** [comment]
Vlw pessoal  hoje fui vendo cada sugestão e  resolvi criar um repositório mesmo  obg pelas sugestões

**Comment by mahenrique94** [comment]
Costumo utilizar o Trello para isso, crio cards que precisam ser estudados e sigo a ideologia do Kaban.

**Comment by woliveiras** [comment]
Costumo utilizar o Evernote para salvar conteúdos e anotações de estudos.

**Comment by mariojvr** [comment]
Uso 3...

1. Evernote
2. Google Drive
3. Github

**Comment by brunoravanhani** [comment]
Para mim o Evernote funciona bem também, é fácil e está em qualquer lugar também, as vezes eu tento usar o trello ou repositórios no github pra isso, mas chega um dia que fica bagunçado e acabo apagando algumas coisas, com o evernote não tenho essa sensação, as coisas ficam lá "para sempre".

**Comment by LFeh** [comment]
Recomendo dar uma olhada no [iA Writer](https://ia.net/writer/).

Muito, mas muito leve e totalmente em markdown.

**Comment by lucianobarauna** [comment]
@silvaMatheus Eu costumo utilizar o github para anotar tudo utilizando markdown
https://github.com/lucianoMeusCursos/ReactNinjaNotes

**Comment by MatCunha** [comment]
Olá! :D 

Pra anotações costumo usar acima de todos o Google Keep, é fácil, sincroniza com Android e é multiplataforma. Em segundo lugar o Trello.

**Comment by LFeh** [comment]
Uma outra sugestão é fazer algo [nessa pegada](https://github.com/LFeh/dailylog)

**Comment by silvaMatheus** [comment]
@LFeh  Acabei fazendo os dois o Log para fazer um breve resumo do que estudei no dia, e um outro repositório com as notas mais a fundo
