### ISSUE TITLE
Android Studio TextView 

### ISSUE THREAD

**Issue by welwvs** [frontendbr/forum#954]
Olá povo estou estudando um pouco o android studio e fiquei com uma pequena duvida:

Eu fiz uma String a1 na **Mainactivity.java** e queria chama ela no TextView do **activity_main.xml** na parte **android:text=""** 

Minha duvida é, se é possível fazer isso e como seria?

Mainactivity

public class MainActivity extends AppCompatActivity {

    String a1 = "";

activity_main

  <TextView
            android:id="@+id/cifra1"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginBottom="8dp"
            android:layout_marginEnd="8dp"
            android:layout_marginStart="8dp"
            android:layout_marginTop="8dp"
            android:text="" //<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Queria chama-la aqui
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_bias="0.06"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintVertical_bias="0.3"
            />

**Comment by kivervinicius** [comment]
@welwvs posta no https://github.com/backend-br/forum galera vai te ajudar melhor lá.
