### ISSUE TITLE
Alguém usando JAM Stack?

### ISSUE THREAD

**Issue by luizbills** [frontendbr/forum#958]
Alguém anda desenvolvendo algo no modelo do [JAM Stack](https://jamstack.org/)? Pode falar um pouco dos desafios que você enfrentou ou que anda enfrentando?

**Comment by ribeiroevandro** [comment]
Interessante, não conhecia e vou dar uma olhada com mais calma sobre o assunto, parece interessante...

**Comment by julioc98** [comment]
Gostaria de saber também
