### ISSUE TITLE
Pesquisa: Evolução da carreira de desenvolvedor Front-end

### ISSUE THREAD

**Issue by lnfnunes** [frontendbr/forum#963]
Galera, estou querendo fazer uma análise de nossa carreira e buscar opiniões dos mais diversos cenários do país. Agradeço quem puder responder as seguintes perguntas:

1. Qual o tipo da sua empresa (agência, startup, software house...) ?
2. Tua empresa possui um _Plano de Carreira_? Se sim, qual o caminho planejado na evolução de um Desenvolvedor Front-end ?
3. Se tu já foi um Desenvolvedor Front-end e hoje atua em outro papel que considere como uma evolução, qual papel é ? O que te motivou a trocar de papel (estagnação, insatisfação, salário...) ?

**Comment by woliveiras** [comment]
@lnfnunes, não seria melhor montar um form pra depois você conseguir visualizar melhor as respostas?

Fora que, nos foruns, normalmente a gente começa respondendo as perguntas e no meio das respostas a conversa vira outra coisa, daqui a pouco o foco já se foi. :joy: 

O legal seria, também, depois disponibilizar os dados aqui nessa issue. :grimacing:

**Comment by lnfnunes** [comment]
Boa @woliveiras!
Vou preparar e já disponibilizo aqui pra galera

**Comment by lnfnunes** [comment]
Pessoal, segue o form:
https://docs.google.com/forms/d/e/1FAIpQLSdcX1zfx9PAbxTbURGWPfWjGsr-531KgfzeUB1JZNuIC2HgUw/viewform
