### ISSUE TITLE
Modal para capturar newsletters

### ISSUE THREAD

**Issue by mahenrique94** [frontendbr/forum#965]
Galera, estou pensando em adicionar um modal para tentar capiturar mais _newsletter_ no meu blog, o que acham?

Pergunto isso, pois estou em dúvido quanto a UX, será que não vai prejudicar o leitor? Minha ideia era após 5 segundos ou assim que carregar.

**Comment by kvnol** [comment]
Desculpa corrigir, mas no caso seria para **capturar leads**.

Mas então, pop-ups são sempre chatos, tem muitas pesquisa sobre isso na internet, que eles expulsam os leitores e tal. O que você acha do rodapé do post ter um input para capturar esses leads ou até no rodapé do site? Talvez seja melhor.

**Comment by TailoMateus** [comment]
Cara, eu acredito que isso não é muito bom. 
Na minha opinião, deixa um "botão" pra se cadastrar, em um lugar visível. Se eu quero me cadastrar, não vai ser por causa de modal.

Posso estar errado. Mas como usuário acho que isso não funciona.

**Comment by mahenrique94** [comment]
É que eu vários sites que eu acesso a abordagem é essa, ai tenho que fechar o modal para ler ou eu me cadastro, fiquei na dúvida dai.

Acho que vou adicionar um form de newsletter no final do post, ficaria melhor.

**Comment by caiobubb** [comment]
Eu acredito que dessa maneira pode ser a mais rentável para você:

Coloque o modal pra aparecer quando o cara entra no site, algo chamativo, convidativo, mostrando o por que seria interessante ele se cadastrar. Esse modal tem que ser de uma maneira que você sentiria vontade de se inscrever. E aí usa um plugin de cookie, pra armazenar se é o primeiro acesso ou não do usuário, e assim não fica se repetindo toda vez que ele entrar, você fez sua primeira tentativa com sucesso. E pra complementar, deixa no rodapé do post, caso ele tenha perdido o modal por infinitas possibilidades e ainda sim quer se cadastrar.

**Comment by mahenrique94** [comment]
Então, como citei, os sites que abrem o modal para mim, sempre abrem, vou verificar essa abordagem @caiobubb, obrigado.

**Comment by Pedro-Souza** [comment]
Penso o mesmo que o @TailoMateus, deixa um 'cadastre-se' em algum lugar visível. Eu particularmente acho uma bosta esses pou-ups.

**Comment by luizbills** [comment]
Sugiro colocar seu formulário no final dos seus artigos e em algum ponto estratégico na sua página inicial. Não vale a pena incomodar um leitor que ainda nem é interessado pelo seu conteúdo. E quem já é interessado (e possivelmente assinante) vai ficar mais incomodado ainda.

**Comment by mahenrique94** [comment]
Estou tendo problemas para atualizar a nova versão, ai eu disponibilizo para vocês verem, adicionei o formulário após o término de cada post e na página inicial subi ele como primeira opção lateral.

**Comment by linconkusunoki** [comment]
Se a leitura de determinado blog me agrada eu sempre busco receber novidades dele. 
Espero encontrar de forma fácil, mas não que o blog jogue isso na minha cara a qualquer momento.
Concordo com a dica do @luizbills

**Comment by LFeh** [comment]
Sinceramente?

Se entro em um site de conteúdo (especialmente um que nunca entrei) e abre um popup pedindo meu e-mail, eu fecho e nunca mais entro. 

Isso não funciona nem pra sites famosos, irrita bastante o usuário.

**Comment by mahenrique94** [comment]
Estranho seu ponto de vista @LFeh pois os sites que eu busquei referência para isso são os blogs da: Caelum e Alura.

Empresas bem pequenas né? Quase nem são referência.

**Comment by fdaciuk** [comment]
Tenho a mesma opinião do @LFeh. Mas @mahenrique94, não significa que porque a empresa é grande, que ela faz tudo certo.

Pode até ter um bom resultado, mas que irrita muita gente, isso irrita =)

Ae vai de você ver se vale a pena "converter" em muitos leads que se cadastram, ou se teria valido a pena ficar com os que saíram por conta da pop-up ;)

**Comment by lucianobarauna** [comment]
Tenho essa mesma impressão do @fdaciuk  e um adendo seria que esses modais ou popup só aparecem quando o usuário encosta no botão de fechar a aba no navegador.

**Comment by mahenrique94** [comment]
Ja adicionei no final do post e na lateral da home, não irei abordar o modal, se der resultados tudo bem, senão farei um teste com o modal, entre tentativas e erros tudo se resolve.

Obrigado a todos.

**Comment by nandosangenetto** [comment]
Pode ser legal fazer um teste A/B, tentar conhecer melhor como seu público e ver como ele se comporta.
Seria legal ver quanto cada versão está convertendo e o quanto cada uma pode estar prejudicando o leitor.

Na minha opinião, não vale a pena fazer uma intervenção para gerar leads, apesar de ter uma taxa de conversão alta em comparação à outras abordagens, pois prejudica bastante o usuário.

Vale também ter em mente que o Google adotou uma nova política de anúncios e este conteúdo pode ser considerado um anúncio, principalmente no mobile, pois vai esconder o conteúdo do site e forçar o usuário a tomar alguma ação, não sendo mobile-friendly. Vale a pena ler esta notícia: https://marketingland.com/surviving-googles-new-policy-interstitial-ads-154239 (existem outros conteúdos falando sobre isso nas últimas semanas)

Lembre-se que a web hoje é dominada por dispositivos móveis, portanto criar essa intervenção impacta bastante nos usuários móveis.

**Comment by kvnol** [comment]
Eu poderia fazer um texto para endossar as opiniões dadas nessa issue, mas vou resumir:

:top:

**Comment by mahenrique94** [comment]
boa @nandosangenetto, vou partir para um teste A/B nesse primeiro momento.

**Comment by LFeh** [comment]
```
Estranho seu ponto de vista @LFeh pois os sites que eu busquei referência para isso são os blogs da: Caelum e Alura.

Empresas bem pequenas né? Quase nem são referência.
```

@mahenrique94 Podia ser o Facebook ou o Google, isso não muda minha opinião como usuário. 

Inclusive pode ser uma decisão de negócio que eu, como desenvolvedor, não tenha como refutar, e tenha que adicionar em algum momento nos produtos que trabalho. Isso não quer dizer que eu concorde.

É extremamente desconfortável.

**Comment by mahenrique94** [comment]
Pois é, as vezes os emails que eu mandar, nem ler serão lidos dessa maneira, diferente se o interesse partir do usuário, aos poucos o blog vai crescendo, é algo que leva tempo, mês passado consegui bater mais de 1200 views, antes era dificil passar de 1000.

Algo que eu reparei é a necessidade de postar todo dia, o foda é tempo para isso.

Mas a discussão foi boa, todos ajudaram e colaboraram, obrigado galera.

**Comment by joaodfmota** [comment]
@mahenrique94 Esse modal vem da plataforma [RD Station](https://www.rdstation.com/).

Também não gosto da abordagem de modal para capturar leads.

Quero algum dia testar a abordagem de chat que a [intercom](https://www.intercom.com/pt-BR/messages) oferece, pois pelo que li tu consegue fazer várias segmentações algo que o rdstation não oferece atualmente.
