### ISSUE TITLE
[OFF] Cómo declarar rendimentos recebidos via PayPal? 

### ISSUE THREAD

**Issue by clmadrazo** [frontendbr/forum#969]
Fala galera! 

Chegou o mês de março e com isso as dúvidas a hora de fazer a declaração de imposto de renda. Procurando um pouco por informação fiquei sabendo que como faço trabalhos freelance e recebo via Paypal devia declarar esses valores através do carné leão. Alguém tem experiencia sobre o assunto? Devo declarar o valor total sem a taxa cobrada por Paypal ou já descontando a taxa? Emfim, qualquer experiencia compartilhada será bem-vinda.

**Comment by lhbzr** [comment]
@clmadrazo, vou compartilhar contigo a minha experiência até o momento, pois efetuo o pagamento do Carnê Leão desde fevereiro do ano passado.

Geralmente, o melhor dos cenários é você realizar o pagamento do Carnê Leão emitidno uma DARF todos os meses em que você receber algum rendimento de fora do país, para não ter que realizar o pagamento com juros e multa no ano seguinte quando for declarar seu Imposto de Renda.

Então para isso, você precisa baixar o software do Carnê Leão da Receita Federal e ir adicionando os rendimentos mensalmente no Livro Caixa do mesmo. Eu declaro com o valor cheio da transferência bancária mesmo, sem descontar qualquer tipo de taxa, mas no próprio programa é possível adicionar algumas despessas dedutíveis como aluguel, telefone, entre outros.

Uma coisa boa é que no ano seguinte você consegue importar os dados do Carnẽ Leão para o programa do Imposto de Renda da Receita Federal e a sua declaração fica mais fácil de fazer, caso você não pague um contador para fazer isso por você.

É claro que não sou um especialista nisso, então seria bom dar uma conversada com um contador que entenda os trâmites de dinheiro recebido do exterior.

Qualquer duvida que eu puder ajudar é só chamar! :smile:

**Comment by clmadrazo** [comment]
Eu não declarei nada por meio do Carnê Leão porque os meus rendimentos mensais eram inferiores ao limite de isenção em 2017. 

> Recolher o carne-leão mensalmente só é obrigatório se a renda desse tipo foi acima do limite de isenção de R$ 1.903,98 por mês.... - Veja mais em https://economia.uol.com.br/imposto-de-renda/noticias/redacao/2017/02/07/voce-pode-ja-estar-devendo-para-a-receita-antes-mesmo-de-declarar-seu-ir.htm?cmpid=copiaecola

Minha dúvida agora é se devo declarar esses valoras na minha declaração de imposto de renda ou não? Caso precise, como deveriam ser declarados...

Obrigado @lhbzr

**Comment by lhbzr** [comment]
Se você não ultrapassou o limite, eu particularmente não vejo muita necessidade de você declarar esses rendimentos no Imposto de Renda.

Você pode fazer uma simulação no programa de Imposto de Renda da Receita Federal no menu _Rend. Trib. Recebidos de PF/Exterior_ e ver se vai influenciar no Imposto a Restituir, se não influenciar em nada, eu nem adicionaria.

**Comment by clmadrazo** [comment]
Certo. Obrigado novamente @lhbzr

**Comment by lhbzr** [comment]
De nada @clmadrazo! :smile:

**Comment by barraponto** [comment]
Olha, até onde eu entendi, vc declara os dolares recebidos segundo a cotação do ultimo dia do mês anterior ao mês do recebimento. É confuso mas é isso aí.

**Comment by PedrodeLima** [comment]
tenho dúvidas se essa ai é a forma certa.
nós não recebemos dólares. e sim reais.
Ao verificar o meu extrato bancário da caixa, a origem do TED feito pro paypal na minha conta, consta o seguinte:
banco : 745 (CitiBank)
Agencia/Conta Remetente: 0001/0000001609316-0
Nome do Remetente: PAYPAL DO BRASIL SERVIÇOS DE P
CNPJ: 10878448000166

Notem que PAYPAL DO BRASIL SERVIÇOS DE P é uma empresa sedeada no Brasil, com CNPJ e Endereço constituídos.

O documento probatório da transação, prova que voce recebeu de uma empresa no Brasíl e não de uma empresa fora do País. Logo você não recebeu em dólar, e sim em reais..

a não ser claro que tenha recebido diretamente de fora, via código swift . o que seria uma transação bancária internacional. 

Acredito que tenha que olhar no extrato a origem do depósito. se for crédito TEV , DOC ou TED só pode ser feita por instituição bancária brasileira.

Não sendo recebimento em dólares, acredito que a forma certá é o rendimento recebido de pessoa juridica. Já que PAYPAL DO BRASIL é uma empresa com CNPJ

**Comment by barraponto** [comment]
@PedrodeLima a menos que vc trabalhe pra PAYPAL, ela é irrelevante. O que importa é quem está te pagando e por que. E, de novo, se ela paga em dolares, vc precisa calcular com base no valor do dolar no ultimo mês.

dica: transferwise é *MUITO* melhor pra receber dinheiro de fora, tanto na taxa (1.5% contra os quase 10% do paypal) quanto no câmbio (tw usa praticamente o mesmo valor do google, enquanto o paypal sempre tira vantagem).

**Comment by shrimpgo** [comment]
Galera, estou em uma situação atípica. Fui contratado recentemente por uma empresa canadense e eles vão me pagar via Wise (antigo TransferWise). Até aí tudo bem, mas disseram q vão pagar pela minha empresa. O problema é q a Wise não tem suporte à CNPJ no Brasil. Como eu faria pra vincular meu ganho (pagando diretamente na minha conta PF) com a minha empresa?
