### ISSUE TITLE
Usar somente o Git ou uma extensão?

### ISSUE THREAD

**Issue by MatCunha** [frontendbr/forum#978]
Eae, pessoal! 

Tô terminando o curso de Git e Github do @willianjusten mas, me surgiu uma dúvida. 

Eu comecei a desenvolver usando o Visual Studio e não quero largar dele por enquanto, e vi que nele há a possibilidade de usar de maneira nativa o Git e conectar com o Github, simplesmente instalando uma extensão. 

E também ainda não entendi como usar o vscode dentro do terminal do Git, ai que está. 

1. É melhor que eu continue tentando aprender o Git pelo seu próprio terminal? 

2. Não seria mais eficiente e direto utilizar pela extensão do Visual Studio? 

3. Isso faria alguma diferença pra alguma vaga? 

Qualquer explicação ou outro detalhe que esqueci será útil também.

**Comment by julioxavierr** [comment]
Eu particularmente recomendo que use o terminal, pois assim você não dependerá de ferramentas. Ferramentas vêm e vão, no decorrer do tempo a gente usa e deixa de usar várias, mas o terminal não.
Não se preocupe, provavelmente no seu dia-a-dia você não vai usar com frequência tudo o que aprendeu no curso e sim apenas parte disso, com um pouquinho de tempo fica bem tranquilo.
Não sei te dizer se isso faria diferença em uma vaga também, mas se sim, provavelmente o terminal seria mais bem visto.
Se quiser usar as ferramentas, sinta-se à vontade, mas essa é minha recomendação.

**Comment by bernardodiasc** [comment]
Se voce está aprendendo algo, eficiência não é seu objetivo, seu objetivo é aprender.

**Comment by weltonsanches** [comment]
1. É melhor que eu continue tentando aprender o Git pelo seu próprio terminal?
Sim, aprenda pelo terminal primeiro. É mais completo e importante pra saber se virar caso não possa usar o Visual Studio em algum momento.

2. Não seria mais eficiente e direto utilizar pela extensão do Visual Studio?
Acho que sim. Eu gosto de usar pelo vscode algumas coisas, se for fazer algo mais complexo prefiro pelo terminal. Mas é legal conhecer as duas formas.

3. Isso faria alguma diferença pra alguma vaga?
Workflow muda conforme a empresa, se você souber trabalhar com o terminal vai ver que é rápido aprender outra ferramenta.

O @willianjusten lançou um curso mais completo de [git e github](https://www.udemy.com/git-e-github-na-vida-real/) e nesse curso ele trabalha com o vscode também.

E como disse o @julioxavierr 

> Ferramentas vêm e vão, no decorrer do tempo a gente usa e deixa de usar várias

**Comment by sbvorpagel** [comment]
Para mim, ferramentas para o git confundem mais do que ajudam. Acho muito mais efetivo e simples diretamente pelo terminal.

**Comment by Predoff** [comment]
Se o objetivo é aprender, o ideal é você usar o git pelo terminal.

Recomendo também que saiba comandos básicos de navegação no terminal: `cd`, `ls`, `pwa`.

**Comment by willianjusten** [comment]
Como eu mostro e falo nos meus cursos:

É importante que você aprenda como você funciona o sistema, entender os estados, como os arquivos funcionam ali e os comandos para ir manipulando isso. Após você aprender todo o conceito, não há problemas em utilizar algo que facilite e agilize seu trabalho.

[No primeiro curso que eu dou para iniciantes](https://www.udemy.com/git-e-github-para-iniciantes/), eu uso somente o terminal e mostra toda a base ali. Eu sequer uso um editor, para continuar no terminal 100% do tempo, para facilitar a pessoa a entender e focar ali.

Já no curso de [Git e Github na Vida Real](https://www.udemy.com/git-e-github-na-vida-real/?couponCode=PROMOSITE), eu ensino a usar as mesmas coisas simples que aprendemos no terminal (add, commit, pull, push, fetch) via Visual Studio Code, pois é uma ferramenta que já está ali para auxiliar nas tarefas simples. Mas depois quando vou explicar todas as coisas mais complexas, eu volto a trabalhar com o terminal, pois é o limiar onde o VSCode não consegue alcançar e é aí que fica claro a importância de conhecer o Git no terminal.

> Por mais que uma ferramenta te auxilie nas coisas simples, nem sempre ela vai chegar até o fundo para auxiliar em questões mais complexas. Aprenda os conceitos e a base do Git e sempre que você precisar, não será limitado pela ferramenta.

**Comment by MatCunha** [comment]
Compreendi os pontos, pessoal. Muito obrigado!

**Comment by FerreiraRaphael** [comment]
Na minha opinião ferramentas como https://www.sourcetreeapp.com/ e https://www.gitkraken.com/ aumentam a produtividade com o git em 1000%, por que ? Por causa da visualização do trabalho da equipe e facilidade de utilização das features do git.

Sim você pode utilizar o terminal para aprender, eu aprendi pelo terminal, é muito bom para aprender o fluxo.

Porém depois que você já sabe como utilizar o git, e está trabalhando com uma equipe, é muito melhor utilizar uma ferramenta com visualização do trabalho da equipe.

**Comment by gerardo-junior** [comment]
após aprender a fundo como funciona a ferramenta eu acho super legal o uso de extensões, isso aumenta muito produtividade.

a propósito eu recomendo: [git-flow](https://danielkummer.github.io/git-flow-cheatsheet/index.pt_BR.html), [gitkraken](https://www.gitkraken.com/) e [tig](https://github.com/jonas/tig)
