### ISSUE TITLE
Programador Júnior, Pleno ou Sênior?

### ISSUE THREAD

**Issue by wesmelo** [frontendbr/forum#982]
Como posso saber se já deixei de ser Júnior e sou Pleno, ou se já sou Sênior? 
É um tema complicado, confuso porque não há uma delimitação clara.

**Comment by TiagoFuelber** [comment]
Isso aqui pode ajudar a ter uma base: https://github.com/concretesolutions/front-end-guide
Mas depende muito de empresa à empresa.

**Comment by caioincau** [comment]
Peça o seu Job Description para sua empresa, caso não exista, é hora de começar a cutucar ela para definir um plano de carreira.

Mas o da concrete já da uma boa base.

**Comment by LFeh** [comment]
Likando algumas issues que podem te ajudar

- #968
- #770
- #503

**Comment by SergioJrDev** [comment]
Ouça esse podcast, pode te ajudar.
https://devnaestrada.com.br/2015/10/30/devcast-junior-pleno-senior.html

**Comment by wesmelo** [comment]
Valeu pessoal pelas dicas!
