### ISSUE TITLE
Aumentar a velocidade da transferência ao pressionar o mouse (hold)?

### ISSUE THREAD

**Issue by dropecosta** [frontendbr/forum#987]
Estou tentando utilizar os botões para transferir o valor de um usuário para o outro, mas gostaria de, ao clicar e pressionar o mouse (hold) aumentar a velocidade, já quando clicar apenas, passar os valores de um a um.

Alguém pode me ajudar? Já comecei a fazer algumas tentativas com a função addSpeed(), no JS, mas ainda sem sucesso.
Segue [JsFIDDLE](https://jsfiddle.net/9xamta0b/5/)

**Comment by Marlysson** [comment]
Só tem dois botões e as mesmas letras de cada lado da view.. O que era pra acontecer quando clicasse/segurasse..

**Comment by dropecosta** [comment]
Está funcionando offline, realmente a view não mostrou,  era para transferir os valores de um usuário para o outro. Mas a questão é que estou tentando, quando ao clicar e pressionar alterar a velocidade.

**Comment by kvnol** [comment]
Não sei se vou conseguir ajudar, mas tô reproduzindo essa feature no meu Codepen com Vanilla. Se eu conseguir, mando aqui.

**Comment by dropecosta** [comment]
Valeu pela força @kvnol, obrigado!

**Comment by kvnol** [comment]
@dropecosta estou muito feliz por dois motivos, por estar conseguindo te ajudar e por eu ter conseguido resolver esse problema.

Olha, resolvi o problema utilizando os eventos `mousedown` e `mouseup` junto com `setInterval()`. Se liga: https://kvnol.github.io/studiesjs/features/lendValues/

O source está aqui: https://github.com/kvnol/studiesjs/tree/master/features/lendValues

:tada: :tada: :tada:

**Comment by kvnol** [comment]
Conseguiu resolver, @dropecosta?

**Comment by dropecosta** [comment]
Fala @kvnol , desculpa pela demora em responder. Na verdade, consegui implementar o seu código, apesar de bem mais simples e limpo, ele é similar ao meu antigo (no funcionamento), onde somente um valor (no mousedown) regula a velocidade. Seu aumentar, não consigo passar de um em um. O que precisava era que a velocidade aumentasse bastante ao estar com o mouse pressionado, mas quando clicar apenas, ele incrementar de um em um.

Achei uma solução que faz isso, mas de uma forma mais simples. Ele não tem dois valores, só vai para um lado. 
https://codepen.io/maehana/pen/Gxqgpy

Na verdade, estou tentando implementar essa lógica para os dois, mais ainda sem sucesso.

**Comment by dropecosta** [comment]
`//var minValue = 10; //10MB

function formatNumberComma (num) {
  return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1,")
}

function formatNumber(num){
   num = num/1000;

  if(num == parseInt(num)){
    return formatNumberComma(parseInt(num));
  }

  return formatNumberComma(num.toFixed(2));
}

//server side values
var initialValuesUserbar = {
  'minValue': 10, //min value
  'usersInfo': [
    //left
    {
      name: 'Marianna',
      phone: '(21) 0000-0000',
      value: 50000,
      avulso: 4000,
      bloqueado: true
    },
    //right
    {
      name: 'Ludmilla',
      phone: '(21) 0000-0000',
      value: 50000,
      avulso: 0,
      bloqueado: false
    }
  ]
}

var currentValuesUserbar = [];
var timer = 0;
var exp = 1.10; // 1.02
var totalTime = initialValuesUserbar.usersInfo[0].value + initialValuesUserbar.usersInfo[1].value;

var setInitialBarValues = function(values){
  //console.log(values)
  var usersInfo = values.usersInfo;
  var left = usersInfo[0];
  var right = usersInfo[1];

  var primary = document.getElementById('primary');
  var secondary = document.getElementById('secondary');
  var btnLeft = document.getElementById('btn-left');
  var btnRight = document.getElementById('btn-right');

  
  var interval;

  currentValuesUserbar.push(left.value)//[0]
  currentValuesUserbar.push(right.value)//[1]

  //$('.warn-message-info.ator-desabilitado').hide();
  $('.blocknumber-left').hide();
  $('.blocknumber-right').hide();

  if(left.bloqueado) $('.blocknumber-left').show();
  if(right.bloqueado) $('.blocknumber-right').show();

  //left
  $('.left-name').text(left.name)
  $('.left-phone').text(left.phone)
  $('.left-value').text(formatNumber(left.value));

  // if(left.avulso) {
  //   $('.left-avulso-value').text("+" + formatNumber(left.avulso) +" GB avulso")
  // }

  $('.right-name').text(right.name)
  $('.right-phone').text(right.phone)
  $('.right-value').text(formatNumber(right.value))

  // if(right.avulso){
  //   $('.right-avulso-value').text("+" + formatNumber(right.avulso) +" GB avulso")
  // }
}

function clearErrorAdd(){
  $('.left-container-avulso').removeClass('nactive')
  $('.right-container-avulso').removeClass('nactive')
  $('.warn-message-info.ator-desabilitado').removeClass('active');
  $('.warn-message-info.ator-desabilitado').addClass('nactive');
  $('.panel-heading__blockNumber').removeClass('dipnone');

}

function showWarningMessage(className){
  $(className).addClass('nactive')
  $('.warn-message-info.ator-desabilitado').removeClass('nactive');
  $('.warn-message-info.ator-desabilitado').addClass('active');
  $('.warn-message-info.ator-desabilitado .phone').text(initialValuesUserbar.usersInfo[0].phone);
  $('.panel-heading__blockNumber').addClass('dipnone');
}

function incrementRight(hasAnimation){
  if(currentValuesUserbar[0] > initialValuesUserbar.minValue){
    currentValuesUserbar[0] -= 10;
    currentValuesUserbar[1] += 10;
    $('.left-value').text(formatNumber(currentValuesUserbar[0]))
    $('.right-value').text(formatNumber(currentValuesUserbar[1]))

    clearErrorAdd();

    $('.right-container-avulso').addClass('animate')

    if(hasAnimation){
      setTimeout(function(){
        $('.right-container-avulso').removeClass('animate')
      }, 300)
    }
    timer++;
    console.log(timer);
    if (timer > 10) {
      
      initialValuesUserbar.usersInfo[1].value =  Math.round((initialValuesUserbar.usersInfo[1].value - 1) / exp);
      primary.innerHTML = formatNumber(initialValuesUserbar.usersInfo[1].value);
    }
  } else {
    $('.right-container-avulso').removeClass('animate')
    showWarningMessage('.left-container-avulso')
    return true;
  }
}

function incrementLeft(hasAnimation){
  if(currentValuesUserbar[1] > initialValuesUserbar.minValue){
    currentValuesUserbar[1] -= 10;
    currentValuesUserbar[0] += 10;
    $('.left-value').text(formatNumber(currentValuesUserbar[0]))
    $('.right-value').text(formatNumber(currentValuesUserbar[1]))

    clearErrorAdd();

    $('.left-container-avulso').addClass('animate')

    if(hasAnimation){
      setTimeout(function(){
        $('.left-container-avulso').removeClass('animate')
      }, 300)
    }
    timer++;
    console.log(timer);
    if (timer > 10) {
      
      initialValuesUserbar.usersInfo[0].value =  Math.round((initialValuesUserbar.usersInfo[0].value + 1) * exp);
      primary.innerHTML = formatNumber(initialValuesUserbar.usersInfo[0].value);
    }
  } else {
    $('.left-container-avulso').removeClass('animate')
    showWarningMessage('.right-container-avulso')
    return true;
  }
}




//document ready
$(document).ready(function(){

  var userEventClickId = 0;
  var incrementTimeInterval = 200;

  $('.panel-heading__blockNumber').hover(function(){
    $('.tooltip__blocknumber').toggleClass('teste-opacity');
  });*/

  $('[data-toggle="tooltip-user-left"]')
    .tooltip({html: true, title: tooltipUserInfo})


  $('[data-toggle="tooltip-user-right"]')
      .tooltip({html: true, title: tooltipUserInfo})

  
  $('.btn-right').click(function(event){
    event.preventDefault();

    incrementRight(true);
  })
  .on('mousedown', function(event) {
      event.stopPropagation();
      event.preventDefault();

      userEventClickId = setInterval(function(){
        if(incrementRight()) {
          clearInterval(userEventClickId);
          return;
        }
      }, 150);
  })
  .on('mouseup mouseleave', function(event) {
      event.stopPropagation();
      event.preventDefault();

      clearInterval(userEventClickId);
      $('.right-container-avulso').removeClass('animate')
  });

  $('.btn-left').click(function(event){
    event.preventDefault();

    incrementLeft(true);
  })
  .on('mousedown', function(event) {
      event.stopPropagation();
      event.preventDefault();

      userEventClickId = setInterval(function(){
        if(incrementLeft()) {
          clearInterval(userEventClickId);
          return;
        }
      }, 150);
  })
  .on('mouseup mouseleave', function(event) {
      event.stopPropagation();
      event.preventDefault();

      clearInterval(userEventClickId);

      $('.left-container-avulso').removeClass('animate')
  });

  //set initial
  setInitialBarValues(initialValuesUserbar);
})`

**Comment by kvnol** [comment]
> O que precisava era que a velocidade aumentasse bastante ao estar com o mouse pressionado

Mas aí é só alterar o valor de tempo do `setInterval`.

**Comment by dropecosta** [comment]
mas o que acontece é que quando aumenta o valor do tempo, ele não consegue passar mais de um em um, porque é só um valor que regula o tempo.

**Comment by dropecosta** [comment]
Tipo,

**Comment by dropecosta** [comment]
Se você só clicar e o tempo do clique for menor do que 100ms (um clique normal) ele conta 1 por 1, se você deixar clicado, quando passar de 100ms ele vai somando 1 por 1 a cada 0ms, ou seja, bem rápido

**Comment by dropecosta** [comment]
Mas com esse código não estou conseguindo faz a relação entre os dois valores...

**Comment by LFeh** [comment]
@dropecosta Quando for responder, na sequencia de um comentário seu, edite a mensagem, se não configura flood.

**Comment by dropecosta** [comment]
Beleza, desculpe @LFeh!

**Comment by dropecosta** [comment]
Boa tarde pessoal,

Consegui implementar parcialmente a lógica que regula a velocidade como tinha imaginado.

Segue o desenvolvimento. Está em:
https://codepen.io/dropecosta/pen/eMZEez

Tenho agora novas questões para compartilhar e pedir sugestões de impelementação.

1 - Preciso que o valor mínimo seja 0.01. Estou tentando implementar isso através da funcão (comentada) minimalValues, mas não está dando certo.

Preciso que esse valor mínimo realmente pare na 0.01. Atualmente, quando corro com o hold, ele acaba parando em -0.01, -0.03, o que não é legal.

Alguém me dá uma força? 

Obrigado!!!
