### ISSUE TITLE
Repositório para iniciantes treinarem

### ISSUE THREAD

**Issue by woliveiras** [frontendbr/forum#99]
Fala galera, iniciei um projeto para a galera iniciante ter como praticarem o que estão estudando.

Se chama CT (Centro de Treinamento), basta a pessoa se envolver em um grupo e praticar em algum projetinho ou montarem um grupo de estudos.

A intenção é fazer o pessoal praticar, usar mais o Git/GitHub e ainda fazerem bons amigos. :smile: 

https://github.com/training-center/sobre

**Comment by LFeh** [comment]
@woliveiras Se pá se encaixa bem [nesse nosso outro repo](https://github.com/frontendbr/open-source)

**Comment by woliveiras** [comment]
Show mano! Vou levar pra lá :smile:

**Comment by nighto** [comment]
Hello!

 

You have a new message, please read <http://city-barber.co.uk/participation.php?tl62>

 

nighto@nighto.net
