### ISSUE TITLE
Git com Wordpress

### ISSUE THREAD

**Issue by romulo2735** [frontendbr/forum#999]
Estou começando no mundo de wordpress, sendo que me deparei com um problema grande, que é o versionamento do projeto.

Já versionei o projeto, mas quando clono o repositório ele não vem do jeito que estava em outra máquina local. Como fazer?

**Comment by kvnol** [comment]
Seguindo as dicas que a galera me passou na issue #577 (aconselho ler, aliás), eu costumo versionar só o tema.

**Comment by leandroruel** [comment]
versiona-se apenas o tema, como dito pelo colega acima.

**Comment by viniciusdocanto** [comment]
Aqui na agencia nos agora estamos só versionando o theme e plugins

**Comment by allysonsouza** [comment]
Versiono tudo, instalação completa. Versionar o tema só funciona se estou, bem, desenvolvendo um tema. Se estou fazendo um projeto WordPress, que engloba tema, plugins, imagens que são armazenadas na wp-uploads, versiono tudo. A menor parte do seu repositório será WordPress, não irá sobrecarregá-lo nem nada do tipo.

Além disso versiono o banco de dados, sempre que há uma alteração, fazemos um export com wp-cli em uma pasta do repositório e comitamos ele. (Essa ainda é uma parte deficiente, já que ainda depende de comunicação dos envolvidos para saber quem irá mexer em banco de dados)
